### ISSUE TITLE
Better function formatting

### ISSUE THREAD

**Issue by daarxwalker** [prettier/prettier#8665] opened 2020-06-29 12:50 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wEsiBBAGyoBlyYBJeAWyIGEALOMAazgAmeALx4AFCwgCArlThI8AWSmy4AShEA+AtjgBDeAGU4csDBxiA5nBgBxBHGx6qAGjzWoj51rzAAOlB4eH4wISGEJL54pKxEbmDcfIJ4AL4i7g5OVADakjJyALoAdFQMAWGhMKQAZuIAhDFwbHgAPi14dQk8-AIaujDS2IHVzkRw5ZUhNeKNbCUIljCcIsKiAAyt7V1JAvNQi8ur6302g8Oj41AVIf1n0bF7Byui2z2PSxMhKS4TauWemBw+Ai+GsMHokVEEhUcgUyny6h8YF0BjgxlM5mwVhs9k8WTcHi8VB8hKyuRhcGKpRIahALhAEAwVWgRGQoD02GwEAA7gAFDkIVkoZzcvQAT1Z9IARk4kjBDBg9GBSPtkDBsNI4PTODAWFQAOqcRpERVgNGCmKkABuMTFyHARElIBVY1wvKclhYemQIyoY3pACsiGgAEKy-jyvQsOD0Tw+i6B4OGFWWOQARWkEHg8b9WpAiuwrvtUr0UpMdPz2BVMH1pAES2QAA41vSMFyxvqnBh7W24K6rXAKwBHTPwd2MoUgPREAC0nkEggruhHpF07r0nu9SF9-pAYxYpDVGrzRBT6dHg+3CZAMFLtfrnGQACZ6eq9KRSvt2BAWF77X2AFYK2kMYABVSyFHc8ytTVGCgAQEHlZFSCZCh4MMGAxTkHMxhSFIgA)
```sh
--parser babel
```

**Input:**
```jsx
export const isAllListItemsChecked = (module: Module) => createSelector(getGeneral, general => {
  			const { items, checked } = general[module].list
			if (!items || !checked) return false
			if (items.length === 0 || checked.length === 0) return false
			return items.length === checked.length
		},
	)

export const getList = (module: Module) => createSelector(getGeneral, general => general[module].list)
```

**Output:**
```jsx
export const isAllListItemsChecked = (module: Module) =>
  createSelector(getGeneral, (general) => {
    const { items, checked } = general[module].list;
    if (!items || !checked) return false;
    if (items.length === 0 || checked.length === 0) return false;
    return items.length === checked.length;
  });

export const getList = (module: Module) =>
  createSelector(getGeneral, (general) => general[module].list);

```

**Expected behavior:**
Correct formatting of function arguments, chain functions, etc... Just newline after every arg and chain, like old version:

```javascript


export const isAllListItemsChecked = (module: Module) =>
	createSelector(
		getGeneral,
		general => {
			const { items, checked } = general[module].list
			if (!items || !checked) return false
			if (items.length === 0 || checked.length === 0) return false
			return items.length === checked.length
		},
	)

export const getList = (module: Module) =>
	createSelector(
		getGeneral,
		general => general[module].list,
	)
```

**Comment by sosukesuzuki** [comment] 2020-07-01 05:43
We cannot add options for your request. But It may be possible to fix a specific formatting as a bug. Please rewrite this issue with using issue template.

**Comment by daarxwalker** [comment] 2020-07-01 12:34
@sosukesuzuki Updated

**Comment by thorn0** [comment] 2020-07-01 13:30
Duplicate of #6921

**Closed by thorn0** 2020-07-01 13:30 UTC
Labels: lang:javascript
