### ISSUE TITLE
Line comment between "break" and leading semicolon triggers an error

### ISSUE THREAD

**Issue by aleclarson** [prettier/prettier#10636] opened 2021-03-29 22:14 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjATnAhgawDpQD0hABAKIAeWAtgA4A2cJk11CMBA3ANpYC6JALwlUIADQgItGAEtoAZ2Sgs6dBADuABRUJFKLPXVYAnookYsYHHBgBlWpZlQA5shjoArnAlxqqOAAmAYEAMlguHljOcABiEOjUWDCyLsggWB4wEOIgABYw1PQA6rky8PIOYHC2umUyAG5lxmlg8mYgTvJw6DCa6FGJyABmBl0SAFbyFABC-VY2tjRwIU5ww6PeIJMUtk7OjACKHhDw6-RjIA7oXehpqFj+9Dm06E4wRTIBMLnIABwADBIXhAukV+rQ0i84Dd6msJABHY7wPpSPTpeQAWigcECgRymERMkwfQGWDOFy61Bk5M28j2hyRayQI3OmxgDw+Xx+SAATBJ3FgZPQ9gBhCCsMkoaEAVhyHi6ABUHnoWRd6l4AJJQYKwWxgV7SACC2tsMGMjBpAF9LUA)

```sh
--no-semi
```

**Input:**

```jsx
break
// Example comment
;[a] = b
```

**Output:**

```sh
Error: Comment "Example comment" was not printed. Please report this error!
```

**Expected behavior:**

No error.

**Comment by thorn0** [comment] 2021-03-29 22:23
Duplicate of #7126

**Closed** 2021-03-29 22:23 UTC
Labels: type:duplicate
