### ISSUE TITLE
JSX Brackets with Spaces

### ISSUE THREAD

**Issue by fforw** [prettier/prettier#5301] opened 2018-10-25 17:54 UTC
I'd like to have the option to format one-line JSX brackets with a space character after the opening and before the closing bracket.

In my opinion that's by far the prettiest way to have one-line JSX brackets.

**Comment by lydell** [comment] 2018-10-25 18:19
Hi! This was asked for in #1871 (and #1584 is a bit similar), and it was decided not to do this.

**Comment by lydell** [comment] 2018-10-25 18:19
Duplicate of #1871

**Closed by lydell** 2018-10-25 18:19 UTC
