### ISSUE TITLE
Overzealous function parameter new lining

### ISSUE THREAD

**Issue by darsain** [prettier/prettier#9113] opened 2020-08-31 11:05 UTC
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBXAznA0nAngCgHIACQgGmIzgGEBDAG3oCNawBrffASmIF4A+YglpN6cAMoALCACcYYVDHTEAZCuIwIAcy1juFANrDRE6XIVKAuly4BuEGRAQADjACW0dMlC0ZMiADuAAq+CF4oDAG0uF6OTDKsbHAw4s6sblBayDAyqHCOcAC2THAAJqVlADK0mai0WnAAYrKFtDDumcggtIoQDiCSMIX0AOqSbvDoaWASYRNuAG4TuF1g6LEgGZhyQQlarcgAZgyYjgBW6AAeAEIJ7MnitIVwlRlwRyf5IBeX4hm6cAAiqgIPAPvRTiA0jJtl0WCV6P1nDIMjARm5SjBJMgABwABkcyIgmBGCWcXWRcG2C3ejgAjiD4LsXOFuugALRQOBlMr9GRwBlufm7eoHJDHCFfTCFNzZXJS-5iYGg97iz6OGAidGY7FIABMGoSbno-2oEEKYpAVIArP0qAAVEThCWQhZ5ACSUAqsHEYBRrgAgl7xDBcGJwZgAL6RoA)
```sh
--parser babel
```

**Input:**
```jsx
useKey(' ', useCallback(() => enableShortcuts && toggle(), [enableShortcuts]));
```

**Output:**
```jsx
useKey(
  " ",
  useCallback(() => enableShortcuts && toggle(), [enableShortcuts])
);

```

**Expected behavior:**

This is a pretty simple and concise declaration that fits on a single line, it shouldn't be broken ino 4.

**Comment by evilebottnawi** [comment] 2020-08-31 11:22
> it shouldn't be broken ino 4.

We don't have `4`, duplicate of #6921

**Closed by evilebottnawi** 2020-08-31 11:22 UTC

**Comment by darsain** [comment] 2020-08-31 12:34
Sorry for the dupe. Finding these issues is hard :x 

> We don't have 4

I've meant that single line statement was broken into 4 lines.
