### ISSUE TITLE
Option unkown with pnpm

### ISSUE THREAD

**Issue by Xenfo** [prettier/prettier#11008] opened 2021-06-03 21:57 UTC
**Environments:**

- Prettier Version: 2.3.0
- Running Prettier via: CLI
- Runtime: Node.js 14
- Operating System: Linux
- Prettier plugins (if any): @trivago/prettier-plugin-sort-imports

**Steps to reproduce:**
https://github.com/Xenfo/prettier-example
```
npm i
node_modules/.bin/prettier --write .
```
Observe
```
rm -rf node_modules
rm -rf package-lock.json
pnpm i
pnpm prettier --write .
```
Observe

**Expected behavior:**
The @trivago/prettier-plugin-sort-imports option to work

**Actual behavior:**
It doesn't work

**Comment by thorn0** [comment] 2021-06-04 12:30
Duplicate of #8474

**Closed** 2021-06-04 12:30 UTC
Labels: type:duplicate
