### ISSUE TITLE
Blockquotes break when a line ends with a non-text node, and the next line starts with a non-text node 

### ISSUE THREAD

**Issue by paleite** [prettier/prettier#15575] opened 2023-10-30 11:02 UTC
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA+ABAbQIYF0A6UGAVMQEamGEnHaVHqkXFUMB+b2H1j59IAGhAQADjACW0AM7JQ2AE7yIAdwAKChDJTYANsuwBPGULLzsYANZwYAZWwBbOABlxUOMgBmuqXBNnL1jYi5q4A5sgw8gCuviA+9uIR0bFSYTpwAIpREPCe3rEAVlIAHjZpmdm5SF46PkIAjpVwqkoiWiDYUgC0bnAAJv2CIJHY4jphAMIQ9vbYyB06OkOpUKHpAIIwkeJkUfCqcPIubnm1sQAWMPY6AOrn4vBSwWBwNpoP4gBuDwbzYFLGECfGIASSgA1gNjA8nEYnW4JsMAM6VOdRAIiUPhuZhE8wxcB88k+7iErkJMBa2FCs1RsWC8kJ81m8gsfRUUCGGNcMBu4j6MHOyAAHAAGITyOCNcQSynUubVfJCGDYMi8-mCpAAJiEUR8ABUVVoami4PYyP0Bn0nNhVlEqXAAGIQeSzLZhebYPYQEAAXx9QA)

```sh
--parser markdown
```

**Input:**

```markdown
> [a]
> **b**

> **a**
> **b**

> ~~a~~
> **b**

```

**Output:**

```markdown
> [a] > **b**

> **a** > **b**

> ~~a~~ > **b**

```

**Expected behavior:**

I expected no changes. NB: this doesn't happen when the first line ends with plain text, or the second line starts with plain text.

```markdown
> [a]
> **b**

> **a**
> **b**

> ~~a~~
> **b**

```

**Comment by kachkaev** [comment] 2023-12-11 15:39
Duplicate of https://github.com/prettier/prettier/issues/9099

**Closed by kachkaev** 2023-12-11 15:39 UTC
Labels: type:bug, lang:markdown
