### ISSUE TITLE
`prettier.format` behaves differently with `opts.parser` set to string vs function

### ISSUE THREAD

**Issue by RamIdeas** [prettier/prettier#4008] opened 2018-02-20 16:50 UTC
I believe there is a bug with your node API.

```js
prettier.format( input, {
    filepath,
    parser: 'babylon',
    ...config,
});
```

produces different output to:

```js
prettier.format( input, {
    filepath,
    parser: (source, parsers, options) => parsers.babylon(source, parsers, options),
    ...config,
});
```

For this input:

```ts
export interface A {
    a: {
        b: {
            c: string;
        },
        d: string,
    },
}
```

Setting `parser: 'babylon'` yields this output:

```ts
export interface A {
    a: {
        b: {
            c: string;
        };
        d: string;
    };
}
```

Setting parser to the function calling `parsers.babylon` yields this output:

```ts
export interface A {
    a: {
        b: {
            c: string,
        },
        d: string,
    };
}
```

Notice the line ending characters - comma vs semicolon...

I haven't been able to figure this out while debugging. Those 2 methods of invoking the parser should be identical. (I need access to the AST to mutate it before handing it off to prettier to prettify.)

**Comment by ikatyang** [comment] 2018-02-20 17:05
It looks like the difference between `typescript` and `babylon` parser.

---

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAS1jmwDMBDMOPAQT2AB0o8W9yl6nXu8AjDxsx7CwHAM4xsRAOYBuLsLwBfADQLhAE3GSZaoS1VMlIFSAgYYBaGOShy2bBADuABXsIbKcgDcIBDSYg5BLIFAA2YnCmvNiUANZwMADKGJQyyJIArlEgGhBgoeQROUSRuC6x0gC25IXFpgBWYmgAQrFgCcnkVXAAMkRwdZGmEJkwGGMATEM5qdhlyCC85LwAnmHQgRhSsADq-jAAFsgAHAAMptsQkbuxGIvbcGXeg6bYcACOmQTvFeTVtSQ4WGIEiVQIGWw2VMYhkYTgAEVMhB4DNTDAVvsNEdkJN0bECGEZABhCBVGqLIphQKZSIAFRWnmBcCUSiAA)
```sh
--parser babylon
--trailing-comma all
```

**Input:**
```jsx
export interface A {
    a: {
        b: {
            c: string;
        },
        d: string,
    },
}
```

**Output:**
```jsx
export interface A {
  a: {
    b: {
      c: string,
    },
    d: string,
  };
}

```

---

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAS1jmwDMBDMOPAQT2AB0o8W9yl6nXu8AjDxsx7CwHAM4xsRAOYBuLsLwBfADQLhAE3GSZaoS1VMlIFSAgYYBaGOShy2bBADuABXsIbKcgDcIBDSYg5BLIFAA2YnCmvNiUANZwMADKGJQyyJIArlEgGhBgoeQROUSRuC6x0gC25IXFpgBWYmgAQrFgCcnkVXAAMkRwdZGmEJkwGGMATEM5qdhlyCAwAJ4YcGJgUhaBGFKwAOr+MAAWyAAcAAymuxCR+7EYi7vrJN6DpthwAI6ZBJ8V5GqtSQ4WGIEiVQIGWw2VMYhkYTgAEVMhB4DNTDByLxDhoTshJpjYgQwjIAMIQKo1RZFMKBTKRAAq2M8oLgSiUQA)
```sh
--parser typescript
--trailing-comma all
```

**Input:**
```tsx
export interface A {
    a: {
        b: {
            c: string;
        },
        d: string,
    },
}
```

**Output:**
```tsx
export interface A {
  a: {
    b: {
      c: string;
    };
    d: string;
  };
}

```

**Comment by thorn0** [comment] 2020-05-26 17:42
Closing as this issue is ancient and can't be reproduced with newer versions of Prettier.

**Closed by thorn0** 2020-05-26 17:42 UTC
Labels: area:api
