### ISSUE TITLE
Ternary formatting should be more consistent

### ISSUE THREAD

**Issue by mvolkmann** [prettier/prettier#4087] opened 2018-03-01 17:40 UTC
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEbICc6YC8mA7ANwA6UkUG2EAtnAGoCGuRVm2eBAPJgCMABkwB+TAHI0jAgBtoAc2wxcASyiLJmJFx4R8mAQCZREyTAAWatJhuYFEANYblAB1yMbr7bqjccA35MAGYzKTdWNDQfHT1AwwEAFnDJDwgAMzUwNQQYXz1JOAAPNzhcfLIQABoQCDcYNXRkUHZPAHcABXYENGQQVgA3CDUAExqBjGQM1jk0OFqAI1xWMCc4GABlSJzNZFUAVwWQUYgwadn52o15is6VxQZWC7njgCs0YoAhFbWNzdYTAAMho4C8rnUDjA3FDjODjpFcLd+otWIsAJ4KKATDwaGAAdTGVmQAA5hLV0vN8Ss3P0PHBboMwbV8ABHA5qfD3ViPZ5IGavWrzBhqfa4I5C1xyOAARQOEHg8NqMDRhNGxKQxmVKzUclcAGFGE9+lBoMyQAd5gAVNF9fmXOAAX0dQA)

**Input:**
```jsx
const score = 7;
const someVar =
  score < 10 ? 'some long string' :
  score < 20 ? 'this is looking promising' :
  score < 30 ? 'passing' :
  score < 40 ? 'proficient' :
  'expert';
```

**Output:**
```jsx
const score = 7;
const someVar =
  score < 10
    ? "some long string"
    : score < 20
      ? "this is looking promising"
      : score < 30 ? "passing" : score < 40 ? "proficient" : "expert";

```

**Expected behavior:**
If the entire expression does not fit on one line then each condition should be on a separate line like this:
```jsx
const score = 7;
const someVar =
  score < 10
    ? "some long string"
    : score < 20
      ? "this is looking promising"
      : score < 30
        ? "passing"
        : score < 40
          ? "proficient"
          : "expert";
```
This would be similar to how function parameters are treated. They are either all on one line or all on separate lines.

But honestly I think the original formatting at the top before Prettier changed it is the best.

**Comment by duailibe** [comment] 2018-03-01 18:15
I'm closing it as duplicate of #737 since there's a lot of discussion there already.

**Comment by j-f1** [comment] 2018-03-01 18:16
Duplicate of #737

**Comment by duailibe** [comment] 2018-03-01 18:20
Oops I misread the issue, sorry. You want the ternary to expand even if it's in one-line if it's nested

**Comment by xixixao** [comment] 2018-03-01 21:56
Agree, even two levels formatted different way look weird, and make you think the one line ternary somehow works differently.

**Comment by duailibe** [comment] 2018-03-02 14:49
#3018 is the issue I was thinking about

**Closed by duailibe** 2018-03-02 14:49 UTC
Labels: lang:javascript

**Comment by j-f1** [comment] 2018-03-02 15:05
Duplicate of #3018
