### ISSUE TITLE
Comment sometimes moved out of function using flow parser option

### ISSUE THREAD

**Issue by ryanhomer** [prettier/prettier#938] opened 2017-03-07 23:30 UTC
I'm not sure of the exact cause, but I've been able to reproduce it with the following example:
```js
class MyComponent extends Component {
    someId: number;

    handleAppStateChange = (appState: AppState) => {
        if (appState === 'active') {
            /* Some useful comment. */
            this.someOtherFunc();
        }
    }

    someOtherFunc() {
    }
}
```
becomes:
```js
class MyComponent extends Component {
    someId: number;

    handleAppStateChange = (appState: AppState) => {
        if (appState === 'active') {
            this.someOtherFunc();
        }
    };
    /* Some useful comment. */
    someOtherFunc() {}
}
```

It doesn't seem to happen if there is no code before `handleAppStateChange` (i.e. no `someId` definition) or no code after. It can also be prevented by added the semi-colon manually after the `handleAppStateChange` definition. Prettier does put it but too late to prevent the issue.

I'm seeing this behaviour across multiple files and I've only just started to investigate so I don't know how similar the behaviour will be when I get to the other files.

**Comment by vjeux** [comment] 2017-03-07 23:33
Your example doesn't reproduce on the latest version of prettier. We've done a lot of work on comments recently. Do you mind trying it again on prettier 0.21 and see if you still see issues?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20MyComponent%20extends%20Component%20%7B%5Cn%20%20%20%20someId%3A%20number%3B%5Cn%5Cn%20%20%20%20handleAppStateChange%20%3D%20(appState%3A%20AppState)%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20if%20(appState%20%3D%3D%3D%20'active')%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%2F*%20Some%20useful%20comment.%20*%2F%5Cn%20%20%20%20%20%20%20%20%20%20%20%20this.someOtherFunc()%3B%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%5Cn%20%20%20%20someOtherFunc()%20%7B%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by ryanhomer** [comment] 2017-03-08 14:04
This happened to me using prettier-atom 0.21.2. I'm installing 0.22.0 now and will report back. Thanks.

**Comment by vjeux** [comment] 2017-03-09 03:55
Oh wow this is crazy, looks like a bug with the flow parser, thanks!

**Comment by vjeux** [comment] 2017-03-09 03:56
I would suggest you to use babylon parser, it knows about all the flow types and is more robust overall.

**Comment by ryanhomer** [comment] 2017-03-09 16:13
Thanks @vjeux. I have switched to the babylon parser. Looks like this is something out of the scope of this project then. I'll go ahead and close.

**Comment by vjeux** [comment] 2017-03-09 16:15
Absolutely not, we should fix it :) I just wanted to find a way for you to get unblocked.

**Comment by vjeux** [comment] 2017-03-19 22:17
This is fixed by https://github.com/prettier/prettier/pull/1038

**Closed** 2017-03-20 17:21 UTC
Labels: bug, Comments, has pr
