### ISSUE TITLE
Option to add parenthesis to multiline expressions

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier#2065] opened 2017-06-08 20:59 UTC
By default, Prettier will remove parentheses surrounding multiline expressions, for example:

``` ts
export const jsonDecodeString: jsonDecodeString = type => value => (
    // Widen Left generic
    typecheck<Either<JsonDecodeError, any>>(jsonParse(value)).chain(validateType(type))
);
```

… becomes:

``` ts
export const jsonDecodeString: jsonDecodeString = type => value =>
    // Widen Left generic
    typecheck<Either<JsonDecodeError, any>>(jsonParse(value)).chain(validateType(type));
```

However, this is not always desirable. I think the parentheses add to the readability of the code, especially when there is further indentation.

Would it be possible to add an option to enforce parentheses whenever an expression spans multiple lines?

Related: https://github.com/prettier/prettier/issues/1980

**Comment by vjeux** [comment] 2017-06-09 16:35
Genuinely curious, why not use `{}` if the expression spans multiple lines?

My view on arrow functions is that they should be used for simple things. If you need something more complex you should likely be using {}. Trying to write everything as a single expression leads to code that is hard to understand and hard to "play with" as you can't easily console.log pieces of it.

So, my current line of thoughts is to make arrow functions generate as less noise as possible to make the simple case very elegant and push `{}` for the more complex ones.

**Comment by OliverJAsh** [comment] 2017-06-10 13:10
Hey @vjeux. I tend to follow this pattern not just for multiline single-return arrow functions, but any other multiline expression, such as a variable assignment where the value being assigned spans multiple lines:

``` js
// This is a shorter example that fits within the column limit, but you can see the pattern.
const foo = (
  x
    ? 1
    : 2
);
```

**Comment by Nase00** [comment] 2017-06-15 21:46
Just because an arrow function is multiline doesn't necessarily make it complex and call for using `{}`. React pure function components and other expressions that include JSX are a great example of this:
```js
const SomeComponent = () => (
  <div>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit
  </div>
);
```
Which is highly preferable to:
```js
const SomeComponent = () => 
  <div>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit
  </div>;
```
My team is currently locked on version `1.3.1` because these changes touch nearly every one of component files, and nobody is really on board with how it affects expressions that include JSX. Would really appreciate if this was configurable so that we could continue to use Prettier in the project.

**Comment by mdapper** [comment] 2017-06-16 16:01
I have to agree with @Nase00 on this one, for functional stateless components in React I prefer the first option with parenthesis. I was surprised to start a new project and find out that Prettier was removing the parentheses from my components.

**Comment by panjiesw** [comment] 2017-06-16 16:45
I was also a bit surprised when trying to use prettier and it removes the parenthesis in my react components. I want to use version `1.3.1` but I'm using typescript, which isn't supported by that version.

I've also read the intention of #1733 but I think user should be able to opt out the parenthesis stripping.

**Comment by rattrayalex** [comment] 2017-07-14 06:59
I think an option for this is extremely unlikely. 

However, I do see its appeal as default behavior. 

Separately, worth noting that for JSX stateless function components, the parens are back in (on master, not yet released).

**Comment by dmmarmol** [comment] 2017-08-17 20:51
I vote for this feature +1
### I Prefer this
```javascript
{array
    ? array.map((item, i) => {
            return (
                <div>
                    <p>{item}</p>
                </div>
            );
        })
    : (
        <div>
            <p className="lead">Lead paragraph</p>
            <p>Less important one</p>
        </div>
    )}
```
### Instead of
```javascript
{
	array
		? array.map((item, i) => {
				return (
					<div>
						<p>
							{item}
						</p>
					</div>
				);
			})
		: <div>
				<p className="lead">Lead paragraph</p>
				<p>Less important one</p>
			</div>;
}
```

I'm using Visual Studio Code Prettier extension with this settings
```
{
	"prettier.singleQuote": true,
	"prettier.semi": true,
	"prettier.useTabs": true,
	"prettier.jsxBracketSameLine": true
}
```

**Comment by rattrayalex** [comment] 2017-08-19 06:25
@dmmarmol as I said in the comment immediately above yours, that is the behavior on master for JSX 😄 

(it hasn't yet been released; see https://github.com/prettier/prettier/issues/2589)

this thread is only about non-jsx.

**Comment by jabacchetta** [comment] 2018-03-10 04:27
Since this is still filed under "needs discussion", might be worth noting the [reasoning and example for parentheses in Airbnb's style guide](https://github.com/airbnb/javascript#arrows--paren-wrap), since so many of us follow it.

**Comment by rattrayalex** [comment] 2018-03-12 15:46
@jabacchetta would you be interested in submitting a pull request?

Perhaps for arrow function expression bodies and ternaries? (People said "any expression" but those are the examples I see, and my hunch is that "any expression" wouldn't come out as hope 😄)

**Comment by jabacchetta** [comment] 2018-03-21 15:21
Sure, sounds good. I'll update in this thread when I get around to working on it (just in case someone else decides to jump in before I do).

**Comment by isnifer** [comment] 2018-04-29 09:57
@jabacchetta @rattrayalex Hope, it will cover case described in #4184. The only reason to do not use prettier at all.

**Comment by andrey-shostik** [comment] 2018-10-11 19:54
So, what is decided? I really need fix of the issue.

**Comment by jakepark** [comment] 2018-12-07 18:43
@Nase00  Thank you for your suggested fix. I have tested and confirmed that it fixes a current Prettier problematic behavior. 

Recently there has been an issue raised about templating and Prettier automatically (unwanting) formatting.

I think requesting a setting is a solution, for this issue. please see this discussion:

https://github.com/prettier/prettier/issues/5588#issuecomment-445301657

If you have figured out a better way to use Prettier in React projects, please let us know!

**Comment by j-f1** [comment] 2018-12-07 19:07
Prettier currently formats that code in the way you’d expect @Nase00:

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlCBbOAYXwAdoEsBeTACgEpNKA+WgHSk0wB4ATASwBuTdp04AZCACc4eTHxJoArrJ4QANlMxo+WAIYEYAGkyQoaOGHgxFkzLv4k+aMHygBzTHDU6R3APT8Qux0ANwghiAQJDB86MigupKSEADuAAqJCGjIILoCEHw84SAARpK6YADWcDDYJBWubsgwkopwEQAWMHhqAOodOnBo9WBw2Fk6gjoAnjlgaNkRruaSMGnlbni6yABmumrmEQBWaAAeAELlVTXY+nBirnC7+4cgJ6fYjWpwAIqKEPBngd2iB6pIVjkSroStMNFBiiRJK4YL1CjAOsgABwABgiiIg5l65RIOURQzgkgETwi0gAjoo+NJ1rpNtskHtgRFzHg+M1WiDtO5vn8AU92S8QTBoaieOjkAAmCItXR8bzuYh4LY5KDkYqKcwAFWh2XFwIAvmagA)
```sh
--parser babylon
```

**Input:**
```jsx
const SomeComponent = () => (
  <div>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit
  </div>
);
```

**Output:**
```jsx
const SomeComponent = () => (
  <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit</div>
);

```

**Comment by rattrayalex** [comment] 2019-02-01 16:42
I'm going to close this as resolved, just because this discussion has covered a few cases and it's gotten a bit confusing. 

I think there may be a few cases that still warrant considering a change, especially with prettier 2.0 approaching, but it'd be best to split those out into new, more specific github issues.

**Closed by rattrayalex** 2019-02-01 16:42 UTC
Labels: lang:javascript, status:needs discussion, type:option request
