### ISSUE TITLE
TypeScript: Variable declarations with type declarations aren't wrapped

### ISSUE THREAD

**Issue by pmer** [prettier/prettier#8619] opened 2020-06-22 21:44 UTC
**Prettier 2.0.5**

I like adding type declarations to my variables sometimes when I feel it increases the readability of a particularly complex piece of code. 

However, if this pushes the length of the line over the print width, Prettier will not wrap the line.

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAE3PqzgvA4nSKAZxkwFsBPAGWgHMA1AQwCcBLNgIwBs4AOTbU4STAFkGzACq0ADsNFxMAH0xQArv36YAvDRlQmAMS1QwMLtADCbXQAk4HOAAoAlAG4MJbAF9fHECofxAAGhAIBWtocmRQTg4IAHcABU4EeJQHFLZaeMjeDjYwAGs4GABlBVKuE2QYDi04SIALGGp+AHU2rnhyWrA4Kqz+rgA3ftpkcHJCkHryFxg0kqZqNmQAMwdlyIArcgAPACES8sqqlXp6uB291pAj46r6pkEARS0IeAf+fYgWocZYcWYwRRwchgbgxCJA7iwbpcAAmMDayAAHAAGSIKZLLbolBSzfFQlwTe6RACOP3ga2i2RAbHIAFooHA4CiufDXLSuK41mwNlskLsAU9ltQuI1mpL3l86fcxY9IjA+Mi0RikAAWNUlLj8d62CDUTazKEAVnhWmWsj42XFgImLQAklBubAqjCuDEAIIeqoQwT-Zb+fxAA)
```sh
--parser typescript
--tab-width 4
```

**Input:**
```tsx
{
    {
        {
            const myLongVariableName: MyLongTypeName | null = myLongFunctionCallHere();
        }
    }
}
```

**Output:**
```tsx
{
    {
        {
            const myLongVariableName: MyLongTypeName | null = myLongFunctionCallHere();
        }
    }
}

```

**Expected behavior:**
```tsx
{
    {
        {
            const myLongVariableName: MyLongTypeName | null =
                myLongFunctionCallHere();
        }
    }
}

```

**Comment by thorn0** [comment] 2020-06-22 22:09
Duplicate of #2482

**Closed by thorn0** 2020-06-22 22:09 UTC
