### ISSUE TITLE
JSX line ending with quoted space not wrapping at printWidth

### ISSUE THREAD

**Issue by patspam** [prettier/prettier#6696] opened 2019-10-22 22:20 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAxCFMC8mADgE4TFqEB8mAFADpSaYA8AJgJYBu1TLLAB7CRwzKPEjJkwTNGCAGkuWZla1WvlSts+cAYhMBgL782Aei68mAShAAaEBRid0yUAENS5AO4AFLwQ0ZBAPbghOdgcQACNSDzAAazgYAGViBM4oAHNkGFIAVzhHAAsYAFsAGwB1Es54NAywOFSg+p56gE8QsDRgxyy0OFIYP3js8o9kADMPSqHHACs0QQAheKSU1I9yuAAZLLgZuYWQZcFUrOzKuABFAoh4Y-nikAzSIdIQmI8YuEromQsjBqpEYCVkAAOAAMjjIECG1XixBCZDgn24R0cAEcHvAxhRgigPGgALRQOBwdhU6KkOC4zh0sYeCZTJCzF6OIblTh5QqvNBXG73R5HdknV4wX6g9jg5AAJkc+Q8nEqVwAwhBypMQlBoFiQAUhgAVX5EjlDYzGIA)
```sh
--parser babel
```

**Input:**
```jsx
const Foo = props => (
  <div>
    xxxxxxxx xxxx xxxx xx xxx xxxxxxxxXXXXXX XXXXXXX XXXXXxxxxxxxx xxxxxxx xxxxx{" "}
  </div>
);
```

**Output:**
```jsx
const Foo = props => (
  <div>
    xxxxxxxx xxxx xxxx xx xxx xxxxxxxxXXXXXX XXXXXXX XXXXXxxxxxxxx xxxxxxx xxxxx{" "}
  </div>
);

```

**Expected behavior:**

Should wrap at 80 chars.

**Comment by lydell** [comment] 2019-10-23 04:51
Duplicate of #2553

**Closed by lydell** 2019-10-23 04:51 UTC
