### ISSUE TITLE
React Tailwind macro

### ISSUE THREAD

**Issue by ghost** [prettier/prettier#7399] opened 2020-01-20 16:42 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgGcYBPAGzgBN8AzHCdfAHRGPKoFpItoEZCWTKBmx58MAO616jFjACGqMhNRRKAOnTyw9QVAD0+-AEEyZfADc4OQqmgCokKMXwAhAK4wY0fAF4ipBQaAEae3lAABkL4+AAkwJJRUMEA5hzBZO5w+AAWEFY4SKnpmXAclPI4ANbicAAeMBwSOajw+JgcAEz49O5qVEIRAL4A3INChuKKyqoaWjoQAAJQ9TBCTi4eXj7+kuqh25HR+MUZWbn51kVpZ2UV1bUNTS1tHd29-ZSDIAA0IBCYGB2ZzIUCVegSAAKlQQhGQIHkFggqEovxAwRw2iqcBgAGVMNpVClkDAcFk-jkYOgyAB1F5wQgEsBwXGw1qoCytEjwsCEOF-VSEawwSGYlJaZA0eRkIV-ABWhDqrkxYGxePk6DgABlVHBJdLZSAFXVcUSKABFdwQeD6mVwP4EmzWeHBeTBOBkNGYHCqGA0lEwHLIAAcAAYHfQhTTMZh4d6GdYrGiAI5W+CigFwlDyQgcFZUKhonBwVOoYui+Ti+S2w1C9CoElk+2sM1wS3WvVIKV2v4KYL+yiB5CdXuYpREgDCDAlKCgvDR7iFABU3Vnu4aLFkAJL9WC4nSoQHGNS4wKd9dwIZDIA)
```sh
# Options (if any):
--single-quote
```

**Input:**
```jsx
import styled from "styled-components"
import tw from "tailwind.macro"
// All versions
const Button = styled.button`
  ${tw`
bg-blue hover:bg-blue-dark text-white p-2 rounded
`};
`
// tailwind.macro@next
const Button = tw.button`
  bg-blue hover:bg-blue-dark text-white p-2 rounded
`
```

**Output:**
```jsx
// code snippet
```

**Expected behavior:**
The code should be organized and styled better

**Comment by kachkaev** [comment] 2020-01-20 16:46
Prettier core cannot support all library-specific formatting needs. See https://github.com/prettier/prettier/issues/4424 for a general discussion of this issue.

**Comment by LittleHamster** [comment] 2020-01-20 16:52
@kachkaev 
oh I see, can it be manually configured?
the problem is with indentation 

```jsx
const Button = styled.button`
  ${tw`
         bg-blue hover:bg-blue-dark text-white p-2 rounded
 `};
  background-image: url(${background});
  padding: 10px;
`
```

for example something like the above will be perfect

**Comment by kachkaev** [comment] 2020-01-20 17:03
Prettier does not distinguish between

```js
tw`
    bg-blue hover:bg-blue-dark text-white p-2 rounded
 `
```

and, say,

```js
foobar`
    bg-blue hover:bg-blue-dark text-white p-2 rounded
 `
```

Because in a general scenario spacing does make the difference within `` ` ` ``, Prettier is unable to add indentation in your case.

The only two exceptions I know of are styled-components (``styled.xxx`...` `` / ``styled(X)`...`  ``) and graphql (``gql`...`  ``). These were added to prettier quite a long time ago. Because template tags with the same name can mean different things in different libs and thus cause formatting collisions, it was decided to first discuss a general approach to this problem in #4424.

**Comment by thorn0** [comment] 2020-11-18 12:20
closing in favor of #4424

**Closed by thorn0** 2020-11-18 12:20 UTC
Labels: area:multiparser, lang:javascript, type:enhancement
