### ISSUE TITLE
Prettier needs 2 passes to arrive at stable comment formatting

### ISSUE THREAD

**Issue by mariusschulz** [prettier/prettier#10247] opened 2021-02-04 18:18 UTC
Prettier v2.2.1 needs 2 passes to arrive at stable formatting for the input shown below.

Ideally, it should format the code shown under "Input" directly to the code shown under "Expected Output". Currently, it produces the code shown under "Actual Output" after the first pass and then produces the code shown under "Expected Output" after the second pass.

## Input

```js
class SomeClass {  
  someMethod() // foo
  {
    // bar
  }
}
```

## Expected Output

```js
class SomeClass {
  someMethod() {
    // foo
    // bar
  }
}
```

## Actual Output

```js
class SomeClass {
  someMethod() { // foo
    // bar
  }
}
```

## Playground

https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMoQC2cAwhtjsADpQ46ZFwCycMAFhACYAUAlDgHoBOAGYQINOtVp1BwgEboATpJwBfGhqggANCAgAHGAEtomZKGVKIAdwAKyhOZTpUN9AE9ze+UvRgAa1Y8A39jKABzZBglAFc4PThCeThOTlSAGXRI2PQIuAAxCCVCdBgTSOQQdFiYCF0QNhhCVAB1NmN4TFCwODwnTuMAN06PKrBsBvDMOCUYOz8I0uQRVxm9ACtMAA8AIT9A4PRiDPC4FbWEkC3tvHCI1DgARViIeAvUdZBQpRmlKsUKVQDQMSnCMFaxk47GQAA4AAx6UEQGatPwGKqguB-IbnPQAR1e8AWhmc1UwAFooHBUqkGko4ITjAyFnllkhVp8rjNCMZonFufdHi83ucOZc9DB0PJIdC2MgAEySvzGVD3EhEdkgbEAVgasRmABVpc5OV8hvEAJJQdKwPBgMFGACCNrwMA8jw+MzUaiAA

**Comment by thorn0** [comment] 2021-02-04 18:46
Duplicate of #7745

**Closed** 2021-02-04 18:47 UTC
Labels: type:duplicate
