### ISSUE TITLE
Make code folding possible for all blocks; else starts on newline

### ISSUE THREAD

**Issue by nyteshade** [prettier/prettier#4610] opened 2018-05-31 05:13 UTC
**Prettier 1.13.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQwE4CucAlJsADpSaaRQDOEANnAHSMQDm2A5AwLZwYAC1RQO3YgG5KAX0pxGdOGUrVaDZm049+gkWMwKlE2SAA0ICAAcYqaHWSgAhnjwQA7gAUXCByicAbhCoACbmIABGeE5gANaCAMpWMaIcyPhEFqJKeDCe0Rx8TsjoTopwFgBWdAAeAELRcYlOAgAyonAlZUoWyXg5yJFOEQCe7FDhVniiMADqocLIABwADL1uSrPRVoNTcDkBnRZ4cACOBKgn+U6FxUil5RZKfKjphBUgdKnMAIoEEPAuo8QDBhvMQoskAAmCz4JyoRipADCED4RUGUGgRxABCUABVhn4HkoZDIgA)
```sh
# Options (if any):
```

**Input:**
```js
// code snippet
if (true) {
  console.log('something');
}
else {
  console.log('something else')
}
```

**Output:**
```js
// code snippet
if (true) {
  console.log("something");
} else {
  console.log("something else");
}
```

**Expected behavior:**
```js
if (true) {
  console.log('something');
}
else {
  console.log('something else')
}
```

The reason behind requesting this is that in many IDEs and editors, code folding is allowed. Fundamentally I am not really at odds with the way prettier formats things like `} else {` other than that it prevents nearly every editor and IDE out there from successfully folding the `if` and not the `else`. 

If `else {` starts on its own line, this problem goes away. For my team, given how we document our code, this is crucial and should be allowed. It is one of the only reasons, we are not currently able to use prettier to solve our needs.

**Comment by ikatyang** [comment] 2018-05-31 05:30
Closing as duplicate of #840.

If you can't live without it, [`prettier-eslint`](https://github.com/prettier/prettier-eslint) + [`brace-style`](https://eslint.org/docs/rules/brace-style) should be what you want.

**Comment by ikatyang** [comment] 2018-05-31 05:30
Duplicate of #840

**Closed by ikatyang** 2018-05-31 05:30 UTC
