### ISSUE TITLE
MDX linting fails when encounters jsx double curlies {{}}

### ISSUE THREAD

**Issue by Milesanator** [prettier/prettier#6998] opened 2019-11-18 14:56 UTC
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: CLI
- Runtime: NodeJS v12.13.0
- Operating System: macOS

**Steps to reproduce:**

Lint mdx file that includes double curly braces.

```
## Test001

<div>
  <h1 style={{ test: 'fail' }}>Fail</h1>
</div>

```

[playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKUCGBbOJAAgCEBXAcyLwBMAPLdVLLAYlaIFE78AHAGzgsoAHhoBLAG4A+LESIiAFgEYiAZxgBPQQF5gwIvA3EA5ADMc4-iaIBfW9IBil-iID0K2aLcSZWEAA0IBC8MOLQasigOABOMRAA7gAKsQiRKDiSEOI0gSAARjE4YADWcDAAyrzF4lAUyDAxZHBBijB4-ADqiuJG1WBwFWm9Ur2ayOBqkUG1anAxMElFFHg4yBb8c0EAVmp0JEWl5RX4cAAytXDrOJstILt0FbUUggCKZBDw17dB1TFzMQmtDoeV4MVqME6ORgimQAA4AAy-eJzTpFXgTMFwAGSK5BACOH3gSxC6RAODUqCgcDgNFpeRicEJ4kZSxwKzWSA2WxAczw4gaTTuamebyJVy5Nx5MBw+ShNBhyAATEFGi5ngBhCB4VYTKDQPEgMhzAAqsvS3LukmaAEkoHTYBUwODQgBBe0VLSCb5zexAA)

**Expected behavior:**

Same behaviour as in v1.18.2

**Actual behavior:**

`SyntaxError: Unexpected closing tag "${tagName}".`

**Comment by thorn0** [comment] 2019-11-18 15:42
Duplicate of #6943

**Comment by thorn0** [comment] 2019-11-18 15:43
It's been fixed, but not yet released.

**Closed by thorn0** 2019-11-18 15:42 UTC
