### ISSUE TITLE
wrapped await calls removed parens - (await a())[0] becomes await a()[0]

### ISSUE THREAD

**Issue by Metroninja** [prettier/prettier#5863] opened 2019-02-14 15:50 UTC
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#.....)
```sh
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaACgEpdgAdKXXAGzhl1QCM8BeXC1AHdUpduggBbOADFiYMpWABfKlQD8AOgDaABgC6uAD6HcAclMMmSkABoQEAA4Ko6ZKFQAnDxEEAFTwiuKKgAbhCkACa2IJweqGAA1mwAyg7xpFAA5sgwHoRwdgAWMBLMAOqFonDoaWBwyYGipCGimMjg6K52GehwHjC+cZkSqMj4qMy9dgBW6AAeAEJxiSmoUgAyGXBjE1Mgs3PJGZmsAIqEEPA7kwUgaR69Hu2z0NEOHhkwZZEwhcgAHDo7O8IL0ynEHO13tU+iFtnYPHAAI6EUiIwaoYajJDjG52XoSUg5PK3dDHM4XK443a3GBcb4RX7IABMdlyImYxwAwpIRu0oNB4SBCL0ACpcIK43pKJRAA
```

**Input:**
```jsx
async function() {
  let abc = (await someFunction({}))?.[0] || ''
  }
```

**Output:**
```jsx
async function() {
  let abc = await someFunction({})?.[0] || "";
}

```

**Expected behavior:**

Note that prettier rips out the wrapped await breaking the promise chain, so you can't get the value out.  potential regression of [239](https://github.com/prettier/prettier/issues/239) ?

**Comment by evilebottnawi** [comment] 2019-02-14 16:28
Duplicate https://github.com/prettier/prettier/issues/5857?

**Comment by lydell** [comment] 2019-02-14 16:30
Duplicate of #5857

**Closed by lydell** 2019-02-14 16:30 UTC
