### ISSUE TITLE
Angular decorator styleguide support

### ISSUE THREAD

**Issue by dolanmiu** [prettier/prettier#5177] opened 2018-10-02 17:20 UTC
Can we have a rule which adheres to the Angular style guide for `Decorators`?

https://angular.io/guide/styleguide#decorate-input-and-output-properties

```
Consider placing @Input() or @Output() on the same line as the property it decorates.

Why? It is easier and more readable to identify which properties in a class are inputs or outputs.
```

Relevant SO post:

https://stackoverflow.com/questions/51821817/vs-code-prettier-adds-new-line-after-input-decorator-in-angular

**Comment by michaeljota** [comment] 2018-10-02 17:31
Duplicate #4924

**Comment by lydell** [comment] 2018-10-02 17:31
Yes, this is an upcoming feature: https://github.com/prettier/prettier/issues/4924#issuecomment-425659254

Duplicate of #4924

**Comment by lydell** [comment] 2018-10-02 17:32
Duplicate of #4924

**Closed by lydell** 2018-10-02 17:31 UTC
