### ISSUE TITLE
JSX code not copying with directives?

### ISSUE THREAD

**Issue by zeg-io** [prettier/prettier#3815] opened 2018-01-24 14:56 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMGAGn2HwGEItoECBffAMxwfwHIdTyPADpQM2PPgA2EAOYQOXdLwB0AemlzlAZwBuM4aMYSeagIKZMysFq0GxuAjQAys1FCoaA8gFdWC7jw2EAC0JJiowRpuBiJgkiQ2+OaY+HAAHvBQACZadAzYUMzUIvj4kFBaMDje5LgAFACUxVClpVremHA4jSWtMAAWqFraMCTw+AC8za2t3lpdSNT4WUOY8QCeAPpQJOhwizxQEAQaMnBZ+NH4LL2lNy3Xvf0k2ZJwpr79zKhgY3B1cy6TWAt3wAyG2jgMAAyqN4HUaICcNcGr17qV+Nkuo1pq1+DBvDgWnVQaUADwrHRleI2AByuzgEyEIGSzIAfKTWmSviQsl1qQktPS9kyWRZgjy+Th2ZyZmSMDJ8FocGAJsANBA2HFBcLGczkpFZBBmfgSJIYKKNSbVByHjM5f0AIwCukM0UGmCoGBvdkAdTgkkgezB8mIZBgZNUTtt9q5UdIUpjsfwZJS2tdIv14rcVWNICTyfwABV5GcCJUSHhzlRzl6U5A+WzlWBVMllAArLSRhtwNmm7JKkg6OAh-D8aS85SylOqTAF+1klwyNzT0pDD4Db6-eBZNXsM3zdGF-DQDdfWA-P5q8HDZ6vd6fLd-ZQAIzcWTqN4aR8LoxwZYAUWybAc1FfoYBgTAkFUdQIF+SR+ggSokAAZkdAAGdDVBIT5mWnG1p2AVQACpuQAJjZABVeZkU8F92zgcgiChQlCiySN+go4jVB-Bc52AG8RmfJFlBWLQ1hILYdj2FhIznTlI0pedUQee57hEdJxAIPl928c0kgsEQQAoEAIEwT1oC0ZBQErLgAHcAAVKwQKyUCHCBUCyYyQASGBkH3SR5hMl8cDIABrKFoUwMg3BkZAqm8OATKyOD-IPJK0AqLoYAc0KZHQEg0sCjLOzSAAhUKwAimEGScNw4CKoLTN8TBfDIxqMuinAaOQEAXxIF91mkKBvMwHAc19TyBmQAAOdCTLGpC4F9ULMF6sa4Bo4dvP4ABHbxUH4XKSHywqkACpr5nQVAOpMrRYreABFbxjgapAEoy0YX0mrJpqQMiTKqEhUEkWL6HQAreqOQpvMBIsBtci64BYFggA)
```sh
--no-semi
--single-quote
```

**Input:**
```jsx
import React, { Component } from 'react'
import logo from './logo.svg'
import './App.css'
import { Login, logOut } from 'sso-api-login'

class App extends Component {
  constructor() {
    super()
    this.state = {
      user: { display_name: 'not logged in' }
    }
  }
  handleAuthenticate(user) {
    this.setState({ user })
  }
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <Login
          isAuthenticated={false}
          onAuthenticate={this.handleAuthenticate.bind(this)}
          targetEndpoint="http://localhost:3100/auth"
        />
        {/*<h2>User Object Returned</h2>*/}
        <p>{this.state.user.display_name}</p>
      </div>
    )
  }
}

export default App

```

**Output:**
```jsx
import React, { Component } from 'react'
import logo from './logo.svg'
import './App.css'
import { Login, logOut } from 'sso-api-login'

class App extends Component {
  constructor() {
    super()
    this.state = {
      user: { display_name: 'not logged in' }
    }
  }
  handleAuthenticate(user) {
    this.setState({ user })
  }
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <Login
          isAuthenticated={false}
          onAuthenticate={this.handleAuthenticate.bind(this)}
          targetEndpoint="http://localhost:3100/auth"
        />
        {/*<h2>User Object Returned</h2>*/}
        <p>{this.state.user.display_name}</p>
      </div>
    )
  }
}

export default App

```

**Expected behavior:**

I'm looking for a way to:

- Have function definitions have a SPACE between the function name and the parenthesis, like this `render ()`
- Have JSX parameters use single quotes
- Have JSX parameters use spacing from bracket spacing (default on) so that `<Login isAuthenticated={false} ...` would instead be `<Login isAuthenticated={ false } ...`

Is there a way to achieve this currently?  If not, can these options be added?

**Comment by j-f1** [comment] 2018-01-24 15:03
> Have function definitions have a SPACE between the function name and the parenthesis, like this `render ()`

Duplicate of #1139 

We probably won’t introduce an option for this.

> Have JSX parameters use single quotes

Duplicate of #1080

We’re still figuring out how we should implement this



> Have JSX parameters use spacing from bracket spacing (default on) so that `<Login isAuthenticated={false} ...` would instead be `<Login isAuthenticated={ false } ...`

We don’t have an option for this.

We [generally don’t add configuration options](https://github.com/prettier/prettier/issues/40), and instead encourage you to use [`prettier-eslint`](https://github.com/prettier/prettier-eslint-cli), a tool that runs your code through an ESLint config of your choice after running Prettier, enabling you to choose and enforce your own style guide while still taking advantage of Prettier’s features.

**Closed** 2018-01-24 15:03 UTC
Labels: lang:javascript, type:question
