### ISSUE TITLE
In `"semi": false` mode an empty line before a leading semicolon is collapsed

### ISSUE THREAD

**Issue by ArturBaybulatov** [prettier/prettier#9465] opened 2020-10-21 14:50 UTC
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAlAAgLwD5PAA6UmmkUAzhADZwB01EA5qgOQBmEEr6xxpAbgDarAIasANJlYAjSdLCsAunU4AnAKKiwAC1QAPHPiIlSZaFVoNmB3qYC+d+8RASQEAA4wAlheShRNTUIAHcABUCECmQQUWoQ0QBPaLcZNW0AazgYAGUPbW8oJmQYNQBXODc4AFsZOAATeoaAGVEistEmOAAxCDVq0RgfIpjRMpgIVxAdGGrqAHUdb3gKfLA4HKjl7wA3ZcSYsAoUkEKKODUYMPSmAeR2OPO3ACsKfQAhdLAs3NFquGahTg90elRAr30OUKTFoAEUyhB4CDqE8QPk1Oc1DEZKI6tQph41IUYPNvPUYDpkAAOAAMbkJEHO83SHhihLgmJ2wLcAEcEfBrp5oihRBQALRQOANBpTNRwPneOXXTp3JAPFFg87VbzI1EUaFw-nAtWgtwwXGk8mUpAAJjN6W81GhAGEINVVSAOQBWKZlc4AFVxwvVqJ2FQAklAmrAcmAiV4AIJRnIwRK0XVwez2IA)
```sh
--parser babel
--no-semi
```

**Input:**
```jsx
() => {
  console.log('foo')

  ;['a', 'b', 'c'].forEach(x => {
    console.log(x)
  })
}

```

**Output:**
```jsx
;() => {
  console.log("foo")
  ;["a", "b", "c"].forEach((x) => {
    console.log(x)
  })
}

```

**Expected behavior:**

An empty line after `console.log("foo")` kept

**Comment by fisker** [comment] 2020-10-21 15:31
duplicate of #1510

**Closed by fisker** 2020-10-21 15:31 UTC

**Comment by ArturBaybulatov** [comment] 2020-10-22 12:32
Sorry, tried searching, wasn't able to find anyway.
