### ISSUE TITLE
Prevent link definition labels in markdown from being lowercased.

### ISSUE THREAD

**Issue by marcofranssen** [prettier/prettier#10007] opened 2021-01-05 12:54 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAQgGwgcwDJwwDOAolGAE4CeADjALpIAEA9AEbY4tFGYC0YOBRgBLAGYiwAQ3h8xECnyoQAroqkAvNXD4B3OGyIjZKo1Bx9MhIgkq0YLJgB0QAZV5NBw8ZJlwiTPIUTMpqTJraTPqGxnBMpiLmTATEttR0Lk5QGJwASnBSYDAAcjiJAB4AEgAq1QAKAEyMrBy4LBQFRXwUqvDqUAAmfOYVfBAAbkJ8ABYwMDQNji75hTBMub1C4YNMpRVME1s19SwNmVBZAJJQTAC2VEyoNB3jIqoBrTj0ObgrRXtQKq1Rr0JiXJjTKSTcKYDpSAYPIjTCC6G6hCEopgwCDxGxMGyYMR8Iw4KBwAaeISiCTSeABRK7MqArE40xxY51U6BAowbREAB0YIhULiUkwRBxugoxngNykTE+4SY2CSoluopwOOgj2RuhZTBwhCVKRs5HSay81N88ECChCqmCAEEtB0ogYjPBvlhcCayHY6PR+SAADQgCB0N5QIjIUBSCg9XR1OMIaMoMW6KRUaOhtgUQoAa0IrhohUSOGQMAoKjgobgtzY5IG5LwUnMKikhoAYgpbjJROZkCApCpsSGQLNbpgAOrTWJEEuCVwp4wiV4wKiDsA8MeJGzCOp5nC95BiMU2UMAKyI5XQebAhZgrik6rwiTgJ7PNZAV-KrjLVgARRUCB4A-cUvxLCg90HW4BnKMdnkSGApxEAYYGmZAAA4AAZQ2eCAbCnPMaEHZ5-CESYxwAR2A+AD3DVMhyIYY4HJckxw6GiRA6A8O2PJBT3A0MbFuEQKyrL8zBwQDaPfATP1DGApDYFC0IwpAGkUvMREwMsAGEIFufiQH8ABWMc2WqZTU0E88QHGatribWBXEoEQ6EdQZXHXKwwJsABffygA)

```sh
# Options (if any):
--single-quote
```

**Input:**

I have the following setup to do some migration of my markdown files from https://hexo.io to https://nextjs.org.

```jsx
    const contents = remark()
      .use(gfm)
      .use(stringify)
      .use(frontmatter, "yaml")
      .use(fixFrontmatter)
      .use(textr, { plugins: [ellipses] })
      .use(replaceVimeo)
      .use(replaceCodeBlock)
      .use(replaceBlockQuote)
      .use(imgToJsx)
      .use(prefixRelativeLinks, { prefix: "/blog" })
      .processSync(fs.readFileSync(filePath))
      .toString();

    const formatted = prettier.format(contents, {
      ...prettierConfig,
      parser: "mdx",
    });

    fs.writeFileSync(`${outputDir}/${slug}`, formatted);
```

The input markdown trimmed down to make the point for this issue looks like this.

```md
[BlogLetsEncrypt]: /blog/ssl-certificate-for-your-azure-website-using-letsencrypt/ "Ssl certificates for your azure website using Letsencrypt"
[BlogReactNginxHTTP2]: /blog/react-router-and-nginx-over-http2/ "React Router and Nginx over HTTP/2"

In my [previous blog][BlogReactNginxHTTP2] I have already shown you how to use self-signed certificates in Nginx to use HTTP/2 features. I have also written a blog a long time ago on [how to get a Letsencrypt certificate for your Azure website][BlogLetsEncrypt].
```

**Output:**

```md
[blogletsencrypt]: /blog/ssl-certificate-for-your-azure-website-using-letsencrypt/ "Ssl certificates for your azure website using Letsencrypt"
[blogreactnginxhttp2]: /blog/react-router-and-nginx-over-http2/ "React Router and Nginx over HTTP/2"

In my [previous blog][blogreactnginxhttp2] I have already shown you how to use self-signed certificates in Nginx to use HTTP/2 features. I have also written a blog a long time ago on [how to get a Letsencrypt certificate for your Azure website][blogletsencrypt].
```

Using git diff the change look like this as opposed to the original input. **Caused by the `prettier.format` line**

```diff
-[BlogLetsEncrypt]: /blog/ssl-certificate-for-your-azure-website-using-letsencrypt/ "Ssl certificates for your azure website using Letsencrypt"
-[BlogReactNginxHTTP2]: /blog/react-router-and-nginx-over-http2/ "React Router and Nginx over HTTP/2"
+[blogletsencrypt]: /blog/ssl-certificate-for-your-azure-website-using-letsencrypt/ "Ssl certificates for your azure website using Letsencrypt"
+[blogreactnginxhttp2]: /blog/react-router-and-nginx-over-http2/ "React Router and Nginx over HTTP/2"

-In my [previous blog][BlogReactNginxHTTP2] I have already shown you how to use self-signed certificates in Nginx to use HTTP/2 features. I have also written a blog a long time ago on [how to get a Letsencrypt certificate for your Azure website][BlogLetsEncrypt].
+In my [previous blog][blogreactnginxhttp2] I have already shown you how to use self-signed certificates in Nginx to use HTTP/2 features. I have also written a blog a long time ago on [how to get a Letsencrypt certificate for your Azure website][blogletsencrypt].
```

**Expected behavior:**

I would like to keep existing labels for link references like this, because that helps with the readability of those labels.

```md
[BlogLetsEncrypt]: /blog/ssl-certificate-for-your-azure-website-using-letsencrypt/ "Ssl certificates for your azure website using Letsencrypt"
[BlogReactNginxHTTP2]: /blog/react-router-and-nginx-over-http2/ "React Router and Nginx over HTTP/2"

In my [previous blog][BlogReactNginxHTTP2] I have already shown you how to use self-signed certificates in Nginx to use HTTP/2 features. I have also written a blog a long time ago on [how to get a Letsencrypt certificate for your Azure website][BlogLetsEncrypt].
```

Is there any way to keep using prettier, but skip lowercasing the link labels? E.g. are there markdown options/configuration possibilities. from a playground perspective and documentation perspective I don't see those options.

**Comment by ChristianMurphy** [comment] 2021-01-05 15:11
related https://github.com/remarkjs/remark/discussions/601

**Comment by sosukesuzuki** [comment] 2021-01-07 06:56
Please use the issue template.

**Comment by marcofranssen** [comment] 2021-01-07 10:09
@sosukesuzuki I have updated the issue to use the template.

**Comment by thorn0** [comment] 2021-01-20 13:31
Duplicate of #7118

**Closed by thorn0** 2021-01-20 13:31 UTC
Labels: lang:markdown
