### ISSUE TITLE
MDX issues with adjacent elements and unexpected closing tag

### ISSUE THREAD

**Issue by muuvmuuv** [prettier/prettier#7303] opened 2020-01-13 15:31 UTC
**Prettier 1.19.1**
[Playground link 1](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgDMBnInCdfAchKoB0oNs99h8AFHOAYQgBM4+AL5kK1AHTiA9JCzQEMYvSgMAPMThgYqaAD4G+fKs49+gyAIC8wEuK4BDPgDFUAGzgBlAJ5QwACgB9AL5UHCh7dEEAamopdwBzezAvACZxRSoAShFXeyh4gFd7eLhLOhAYL0w4YjAcVEwYct1VKRNeAX0oVo0tHSgu9U1tPQMjEIA3fDBc4mIAOQjS8sIcYsjYIkc4AFoIAqaQfGJK92s2SFdcJGouPiphIS7DQwB1AAsvAH58AEEoLz4EKEQhwLi+OBfKFfMatSaDKS9EYDEAAGhAEEa-WIyFA9hw5AA7ux8QgcSh7BMIKg+GiQAAjNZgADWcBgHkwSVQ+WQMBwBTg6PeMHQrg+qHgxE5YE8ZIlqAmEq8yHAczp3I0eE463syEI9lcGnRACtiAAPABCTNZ7KWABluXA9QajSBTWaPNz4u4AIoFCDwZ2GwUgTk4TUq9B8M10zD1WCvGkwd7IAAcAAZ0XGIBpXmtMCq4zUwRMneiAI7++CcTHkkD2Yg7KBwOACWnoriV0JwbXxdC6pD64PojToVC8-kh4he31Vp2Dl0hmD2emJvjJ5ApdF8+xuL28dD9lVQeR0goaAAqK-JQ40QiEQA)
[Playground link 2](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwAk4AbdOAgX3wDMcJ18ByHOAQzBgFoALcpV4cAzgE8oYFgB0oGbHnwBlAKIB5eo2YsAdDoD0kLNAQwR+1WplRZAHlIUq+AEYQAJmICCMGDlTOAV3gRAF5gYEwOAHM4JGkQT1cg+OpqAD5bfQchNLtLfBhUGDI4EPjEiGSQDIt1XJsofHwAYnwKoJAAGhAITELoEWRQDhxGAHcABRGEQZQOADcIVDcukGccLgBrKiVIsFQoKORfALhuvhh0MgB1PiK4ET24JRmi1HmisWRwEUHug5EcDwEw2UXQHGQdA4ZEB3QAViIAB4AIQ2YG2MCUHEoABkDnBIdDYSAEYilAcoiUAIoBCDwQkws4gSI4QE4b7oNyI1aYPywa7LGB8ZAADgADN1eRBAdcNphvryHkD5gTugBHWnwEG9WYgUQ8KBwOBuY2rdga1DsEHRcEM4mA9CoY44U7dEQU6maglIKGM7owDjOAVuIXIABM-o2qDIFIAwkxbSgoCZVgFAQAVQOzX2A1JAA)
```sh
--parser mdx
```

There was previously opened an issue on that already but it doesn't seem to be fixed (#6331), so I can't format my MDX correctly where it says `SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (2:1)` but I assume this is also caused by the first issue.

**Input:**
```mdx
import fs from 'fs'
import { PreCode } from '../components'

<section>
  <PreCode code={fs.readFileSync(__dirname + '/legacy2.ts')} language="typescript"></PreCode>
</section>
<section>
  <div className="fragment fade-out" style={{ color: 'red' }}>
    Why? Any difference????
  </div>
</section>
```

```mdx
import { Helmet } from 'react-helmet-async'
import SEO from '../components/SEO'

<Helmet bodyAttributes={{page:"About"}}></Helmet>
<SEO title="About"></SEO>

     # About
```

**Output:**
```mdx
SyntaxError: Unexpected closing tag "PreCode". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (2:84)
  1 | import fs from 'fs'
> 2 | import { PreCode } from '../components'
    |                                        ^
  3 | 
  4 | <section>
  5 |   <PreCode code={fs.readFileSync(__dirname + '/legacy2.ts')} language="typescript"></PreCode>
```

```mdx
SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (2:1)
  1 | <Helmet bodyAttributes={{page:"About"}}></Helmet>
> 2 | <SEO title="About"></SEO>
    | ^
```

**Expected behavior:**

```mdx
import { Helmet } from 'react-helmet-async'
import SEO from '../components/SEO'

<Helmet bodyAttributes={{ page: "About" }}></Helmet>
<SEO title="About"></SEO>

# About
```

**Comment by muuvmuuv** [comment] 2020-01-13 15:33
Even more strange is if I format it with VS Code Prettier and self-closing tags:

```mdx
import { Helmet } from 'react-helmet-async'
import SEO from '../components/SEO'

<SEO title="About" />
<Helmet
bodyAttributes={{
page:
"About"
}}
/>

# About
```

Ref: https://github.com/gatsbyjs/gatsby/issues/20542

**Comment by thorn0** [comment] 2020-01-13 15:37
Duplicate of #6943

**Comment by thorn0** [comment] 2020-01-13 15:37
This has been fixed, but not yet released.

**Closed by thorn0** 2020-01-13 15:37 UTC
