### ISSUE TITLE
bug on `*=`

### ISSUE THREAD

**Issue by bolan9999** [prettier/prettier#11776] opened 2021-11-07 12:29 UTC
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABAKgLzoBQBGA1AIwCUA3CADQgQAOMAltAM7KioBOXEA7gAVuCdilQAbPqgCe7WgS6owAazgwAyqgC2cADJMocZADMJrOPMUq16+koMBzZDC4BXCyDhaCcACa+-XVQoB1dUBzgAMQguLVQYZhDkNFcYCBoQAAsYLXEAdUymeFY7MDh1ESKmADci6WSwVjkQA3MuGAFFBziTMw8AK1YAD3VHcTgARVcIeF7xc1o7LjbkglQfcQz6LgMYPKZfGEzkAA4ABkXeczzFemTtuDbqo1oAR2n4ToZRNFYAWkMfj8GS4cHeTFBnXCPSQpnmHnMWiYzjcCLGkw+RlhfVoMHW+0OxyQACZcYomOJHABhCBaGGeVgAVgyrnMABV1qI4QsQNV3ABJKABWDqMA7RgAQSF6hg0nGc3MAF9FUA)

```sh
--parser babel
```

**Input:**

```jsx
a *= (b+1);
```

**Output:**

```jsx
a *= b + 1;

```

**Expected behavior:**
a *= (b + 1); 

@alexander-akait please do not close recklessly without brain! They are completely  different,  let my code get error, and difficult to debug it.

**Comment by kachkaev** [comment] 2021-11-07 13:12
Looks like a duplicate of #11746

**Comment by alexander-akait** [comment] 2021-11-07 13:25
Answered, please do not duplicate and can continue discussion in https://github.com/prettier/prettier/issues/11746

**Closed by alexander-akait** 2021-11-07 13:25 UTC
