### ISSUE TITLE
Turnery conditions have unclear grouping

### ISSUE THREAD

**Issue by KyleDavidE** [prettier/prettier#13689] opened 2022-10-19 20:49 UTC
This issue is already mentioned in #4157 but I think it deserves its own issue. The output for a turnery directly in an if statement with logical operators in its condition is confusable with a logical operator where the last operand is a turnery operator.

I encountered this issue in a real codebase were the bug slipped past both the author and reviewers. Parenthesis around the condition in this case would go a long way to make this issue easier to spot. More specifically, I would suggest that the condition of a turnery operator be wrapped in parentheses if it is a binary operator and the turnery operator itself not wrapped in parentheses.

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA6gCwIYwYDueAzsQE4CWM8UAOlFQGYYAUjGGkUAJjVWgB5KHAwAycZ27R+MQVAAqRCBKlQuPOQsU4KcMZOlaB0AGIQArhTXTmAGzwBzAMKzTDDVwwB+bmTgROGkuJH9SOGUIRgBKDGBGAF9GRnRifEIScipYBF44XnZmCAoAWwJ4QuYcsTIMKlIYxhZ2Y3d5YVFbLxMOpRVuzXadPQNBmT4PC2txtgdnN0m+33DArrCwAKimqDiEqGSoEAAaEAgABz7SZFA8CgoIIgAFO4RrlDx7EgBPa9OAIwoeDAAGs4DAAMp4UpwAAyNWQzE+EQBQNB4Ih52BOScyBgFEscFOcFK-wK+V4sLwUCclmccAsZQqOOQIDwlhgEBOIBwMFK9lwNDgpCxYDgELeAgAbjRvqywKQ-iAchEKDAnkCnOVEciiSAAFakAAeEJx9jgAEVLBB4Dr7CiQFiKKrWf88GT7NzztRYFgqLwYDhkAAOAAMp29EAiWCB51Z3uFcAoUrg3IAjtb4BqLu82aQALSiAoFbn6DNUfQa5zapBI+16iKlKh4gkNs2WzOp2u604wd1+gNBpAAJl7QKo9hxblKNZAwoArNzLBFFO73nWHVLCQBJPgISFgaiXACCfAhMG+5rtEUSiSAA)

```sh
--parser babel
```

**Input:**

```jsx
// What was written
if (
  conditionOne &&
  conditionTwo &&
  conditionThree &&
  conditionFour &&
  flagCondition
    ? caseOne
    : caseTwo
) {
}

// what was intended (formatted fine as is)
if (
  conditionOne &&
  conditionTwo &&
  conditionThree &&
  conditionFour &&
  (flagCondition ? caseOne : caseTwo)
) {
}

```

**Output:**

```jsx
// What was written
if (
  conditionOne &&
  conditionTwo &&
  conditionThree &&
  conditionFour &&
  flagCondition
    ? caseOne
    : caseTwo
) {
}

// what was intended (formatted fine as is)
if (
  conditionOne &&
  conditionTwo &&
  conditionThree &&
  conditionFour &&
  (flagCondition ? caseOne : caseTwo)
) {
}

```

**Expected behavior:**

```js
// What was written
if (
  (conditionOne &&
  conditionTwo &&
  conditionThree &&
  conditionFour &&
  flagCondition)
    ? caseOne
    : caseTwo
) {
}

// what was intended (formatted fine as is)
if (
  conditionOne &&
  conditionTwo &&
  conditionThree &&
  conditionFour &&
  (flagCondition ? caseOne : caseTwo)
) {
}

```

**Comment by thorn0** [comment] 2022-10-19 21:56
Duplicate of #3805

**Closed** 2022-10-19 21:56 UTC
Labels: type:duplicate
