### ISSUE TITLE
How to use ESLint alignment formating instead of prettier's one

### ISSUE THREAD

**Issue by tamtakoe** [prettier/prettier#10267] opened 2021-02-08 02:44 UTC
I want to use formatting like
```js
const Tom   = 1;
const Jerry = 2;

// and
{
  foo:   1,
  barrr: 2
}

// etc.
```
but Prettier rewrites ESLint rules. How I can disable Prettier formatting for these cases (Similar question was in the topic https://github.com/prettier/prettier/issues/1622 without no suitable solution)

**Comment by thorn0** [comment] 2021-02-08 09:05
Duplicate of #188

**Closed** 2021-02-08 09:05 UTC
Labels: type:duplicate

**Comment by tamtakoe** [comment] 2021-02-08 18:27
So that is good time to unfreeze option requests! Or at least to read some typography books, which say us that data which amount is more than several should be formatted as table data. E.g.
![Screenshot 2021-02-08 at 19 45 25](https://user-images.githubusercontent.com/2244675/107257265-8d42f880-6a4b-11eb-8472-286e2a63d078.png)
and it's better to use grouping
![Screenshot 2021-02-08 at 19 48 06](https://user-images.githubusercontent.com/2244675/107257405-acda2100-6a4b-11eb-8bfc-08d6650d1d96.png)
(Sorry for non English example, but there are a lot of the same typography books for each language, because these rules are international). 

I found quote from @azz https://github.com/prettier/prettier/issues/1622#issuecomment-302932729, which sounds reasonable, but if we see the example we have find that Robert C Martin uses alignment in wrong place (because of it is ordinary code), and has problem with automatic reformatting tools. 

"The problem is the length of the lists, not the lack of alignment" sounds also reasonable, but there are different situations. If you have e.g. an adapter which maps data from one structure to another - the best way - to use alignment. Especially if this transformation occurs multiple times in your file. You will have blocks of aligned code of data structures around ordinary code and that file will be pretty readable.

The best way for Prettier is to recognize user input and format it with alignment if it looks like aligned and vice versa. It is difficult but it is not rocket science. Any way Prettier shouldn't prevent user to format table-like data as he want.

The good idea is to open special issue for that conversation. It is not debates over styles, it is situation when Prettier ignore typography traditions, best practices and simple logic.
