### ISSUE TITLE
Unstable format when multiple comments on same line

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#9671] opened 2020-11-14 08:12 UTC
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA3AHSgegFQCMeO+ATMdvgMwVQBGWU2GlhtZx1tDIANCBAAOMAJbQAzslCoATjIgB3AAqyEklKgA2C1AE9J-OjNRgA1nBgBlQSZFQA5shgyArnH5wAtnTgATX34AMqgOLqj2cABiEDKeqDCiDshoLjAQfCAAFjCemgDqmSLw4jZgcJZqRSIAbkW6yWDiBiB24nAyMErG9nHIAGZabfwAVuIAHgBCxmYWlqiecIF2cP2D7iCjY5Z29ppwAIouEPCrmkMgNjJtMsl0qD6aGYIydjB5Ir4wmcgAHAAM-GeEDaeWMgmSzzg12qK34AEcjvAukJ1GhxABaKBwPx+DIyOAIkT4rrhXpIAZndZtTwiJyuKk7PaHY4rclrfgwe7vT7fJCkDnGESaHYAYQgnjJIChAFYMi42gAVe7qCnnapuACSUACsEsYBewgAgtrLDBdHtTm0AL5WoA)
```sh
--parser babel
```

**Input:**
```jsx
a;
/*1*//*2*/
/*3*/
b;

a;
/*1*/
/*2*//*3*/
b;
```

**Output:**
```jsx
a; /*2*/
/*1*/ /*3*/
b;

a; /*3*/
/*1*/
/*2*/ b;

```

**Second Output:**
```jsx
a; /*2*/ /*3*/
/*1*/ b;

a; /*3*/
/*1*/
/*2*/ b;

```

**Expected behavior:**

Should be stable

**Comment by thorn0** [comment] 2020-11-15 15:18
Duplicate of #3532 ?

**Comment by fisker** [comment] 2020-11-15 16:27
I think it's the same, and seems #9672 fixed it too

**Prettier pr-9672**
[Playground link](https://deploy-preview-9672--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwHIdTy6BuAHSg4HoAqDjbHnwBnGAE8ANnAAm+KjXqMyMALRx0EGKmisOHSFFH4AgsMxxyhElogAhCAA98AXhHip0gHTTUANwAGHPj4AGRISABGcBS4cPjAQcH4BvCwSPS6UEn4AO6o0jAAFukAjJgO7FlJ6CQ4AOaoUCpSFDDpKmUVicEUEhDW6S0wldmFcKh1hW34AAwjSZgk0j5QdSowEJjpACTAmNSYwi4AfPglMzP4XPj7m8KeJGYWMFY2AL4ApPNvelVhSCRWnAcPFulcePgACoQZJSWpyPrWfA8Li8MEpBDTOiZbI+MwSEhidIwEgRKTzYJgOE4dIRTSFb4cfyVFG-AxGUzmSzWbT2JyuAAUCSqjy5Lx5EAANIkwIVUBJpIwoNKqp41bdDhw3gBKE74AWJAA8Pl86IJwmEADkSOg4M5gP4xhMpuk5okIL5gb0IDl0nLlgh5otlo01hstvhdhqjs5TudLtdow8ntz3l9EhEyABrOrUACuUGk6RycvgQYgwlQNig6UYBK0npY-h+VWOYONfmOwFl8sVCDehq4JrbVUHw442sqHDgDkEBGk0RIeYkBE5z1evMcLBAkpAm2rwmQoFq1ByAAVaghDygSBIcoTD7uIjhs3AYABlRZgUPIGA4PNwLu6hRAG0gADIkKseYkHUcAAGK4DUMBaKsyAgEuGw7iAUzoBIADqpZwGYZBwO+V5Vn4VZiGhYAWlhjTCMCMBni+dQ1MgFC3oxu4AFbCA4tgvmAWZvu+NpwGBjRwBxXGASAfEOO+oZSAAinmmjSUgnESNxICLDgjE4GhmZRBIWH7I0MB4fkRTIAAHDMu63IxeEvpgaH7ERwKelhACO6nwCxdxoY8KhQHAMgyFhjD+agjAsTB7FabJu6MegqC-v+cmVqsqkBZp2m6SSETWQUhTIAATLuf4kPKoYAMI0ElIBEQArFheaMZCpLXoVcm+ABACShaYu+YA4KgmAwMYhbvu4BWyW8bxAA)
```sh
--parser babel
```

**Input:**
```jsx
import React from 'react';

/*
import styled from 'react-emotion';

const AspectRatioBox = styled.div`
  &::before {
    content: '';
    width: 1px;
    margin-left: -1px;
    float: left;
    height: 0;
    padding-top: ${props => 100 / props.aspectRatio}%;
  }

  &::after {
    /* To clear float *//*
    content: '';
    display: table;
    clear: both;
  }
`;
*/

const AspectRatioBox = ({
  aspectRatio,
  children,
  ...props
}) => (
  <div
    className={`height: 0;
  overflow: hidden;
  padding-top: ${props => 100 / props.aspectRatio}%;
  background: white;
  position: relative;`}
  >
    <div>{children}</div>
  </div>
);

export default AspectRatioBox;
```

**Output:**
```jsx
import React from "react";

/*
import styled from 'react-emotion';

const AspectRatioBox = styled.div`
  &::before {
    content: '';
    width: 1px;
    margin-left: -1px;
    float: left;
    height: 0;
    padding-top: ${props => 100 / props.aspectRatio}%;
  }

  &::after {
    /* To clear float */ /*
    content: '';
    display: table;
    clear: both;
  }
`;
*/

const AspectRatioBox = ({ aspectRatio, children, ...props }) => (
  <div
    className={`height: 0;
  overflow: hidden;
  padding-top: ${(props) => 100 / props.aspectRatio}%;
  background: white;
  position: relative;`}
  >
    <div>{children}</div>
  </div>
);

export default AspectRatioBox;

```

**Comment by thorn0** [comment] 2020-11-18 12:10
Another similar issue: https://github.com/prettier/prettier/issues/7724

**Closed** 2020-11-30 05:51 UTC
Labels: area:comments, lang:javascript, type:bug
