### ISSUE TITLE
Inconsistent indentation of intersection types

### ISSUE THREAD

**Issue by aboyton** [prettier/prettier#2533] opened 2017-07-24 02:49 UTC
According to prettier these are all formatted correctly. The first one looks off to me.

```ts
type Foo = Bar & {
  mow: string;
} & {
    cow: string;
  };

type Foo = Bar & {
  mow: string;
};

type Foo = {
  mow: string;
} & {
  cow: string;
};
```

This is reproducible in the [playground](https://prettier.io/playground/#%7B%22content%22%3A%22type%20Foo%20%3D%20Bar%20%26%20%7B%5Cn%20%20mow%3A%20string%3B%5Cn%7D%20%26%20%7B%5Cn%20%20%20%20cow%3A%20string%3B%5Cn%20%20%7D%3B%5Cn%5Cntype%20Foo%20%3D%20Bar%20%26%20%7B%5Cn%20%20mow%3A%20string%3B%5Cn%7D%3B%5Cn%5Cntype%20Foo%20%3D%20%7B%5Cn%20%20mow%3A%20string%3B%5Cn%7D%20%26%20%7B%5Cn%20%20cow%3A%20string%3B%5Cn%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D).

I suspect the first should be formatted as

```ts
type Foo = Bar & {
  mow: string;
} & {
  cow: string;
};
```

**Comment by ikatyang** [comment] 2018-01-15 12:41
Duplicate of #3064, fixed in #3074.

**Closed by ikatyang** 2018-01-15 12:41 UTC
Labels: lang:flow, lang:typescript, type:bug
