### ISSUE TITLE
Trailing comma is added to comments in SCSS maps

### ISSUE THREAD

**Issue by stormojm** [prettier/prettier#13288] opened 2022-08-15 14:48 UTC
There is an issue in the SCSS parser where a missing trailing comma is being added to the end of a comment instead of the property.  This leads to errors when checking the formatting, since even though the file was "formatted", it wasn't done correctly.

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASADgQwCbYJZQDmSABABQA6UJJATnoQBYykAMJA9ByTI3gM4kBJTCUgBbcQhhUAlAG4QAGhAR0MPNH7JQmWrQgB3AAp6E2lJgA2hzAE9tKgEa1MYANZwYAZUxSAMgRwyABm1vxwzq4eXt5YYASEyDC0AK6RIHDiTnC4uf6YRKmYhHAAYhC04pgwGkTIIJipMBDKIMziVgDqfPD88XDe5ngaAG4jdg1g-I4gBBG0MMauhNWh4RkAVvwAHt6JVnAAiqkQ8OtWESpYtAsN-NOz6PSwXXjYvMgAHKzXBhFdVzoBrPOALUbBFQAR1O8GWagsjX4AFooHBcrk2rQ4DC8NjliU1kgwpcMhFxHhkmkyQdjrDgsSNioYJgnG8PoxkAAmZmuPBWRIAYQgkkwDTBAFY2qkIgAVVkWElXECjdIASSg2Gk3jA9HUAEFNd4YHZDhcIgBfC1AA)

```sh
--parser scss
```

**Input:**

```scss
$padding: (
  right: 0 // this is a comment
);
```

**Output:**

```scss
$padding: (
  right: 0 // this is a comment,
);

```

**Expected behavior:**
The added trailing comma to the comment is certainly not expected.  Instead the comma should be added after the property value
```scss
$padding: (
  right: 0, // this is a comment
);

**Comment by thorn0** [comment] 2022-08-15 15:15
Duplicate of #7752

**Closed** 2022-08-15 15:16 UTC
