### ISSUE TITLE
comment in array destructuring

### ISSUE THREAD

**Issue by artola** [prettier/prettier#14241] opened 2023-01-27 08:11 UTC
The comment is incorrectly moved to another element.

**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtTB6AKkwDMBLAJw0wLwBpM05IoATemACwpYF1MBeHAEZ6AJnoBmHgG4AOlBC0QEAA4xS6ZKACG5chADuABV0I0yENoA2B7QE9zSgEbltYANZwYAZW0BbOAAZUig4ZGJrRmdXDy9vFTcQgHNkGHIAVzglOD8nOBYWfMDtKCT07SS4ADEIcj9tGHVSi210mAhFEA4YPysAdS54NASwOG8zUnUAN0m7CzA0RxAQxnIYI1ck+vDIrJAAKzQAD29kqzgARXSIeB2rKJAEyjhyCydtPKtOlXIQmD7SCxOMgABwABiUPwgjD6rhUFh+cFWUzCSgAjtd4BtVOYUNo0ABaUL5fKdchwDEUOAbCrbJARe57Rh+UipDJMs5wACCjV+Tja1JewVCdweaE5VxuYXpuyUMA+AKBHGQ4hAaW0pCsyQAwhA-HSQEiAKyddKMAAqH1xDIeU0yAElWAgfGBfmouaxvDA7OdRXAAL7+oA)

```sh
--parser babel
```

**Input:**

```jsx
const [ /* first */, second, third] = [1, 2, 3];

```

**Output:**

```jsx
const [, /* first */ second, third] = [1, 2, 3];

```

**Expected behavior:**

```jsx
const [/* first */, second, third] = [1, 2, 3];

```

**Comment by fisker** [comment] 2023-01-29 22:20
Duplicate of #14242

**Closed** 2023-01-29 22:20 UTC
Labels: type:duplicate
