### ISSUE TITLE
Breaking tslint disable next line comments

### ISSUE THREAD

**Issue by leobrdar** [prettier/prettier#4875] opened 2018-07-23 15:55 UTC
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wEsiAhbCAdyLmzwF48BCVgCgB0o88B6fnhhEANqVhIAJuQCGAI1FwAtFHQxl4tUigRlMAJ4Y4EAGbKArlClxTEuFJ59Dxs3hoSptNkxYByKxs7NSk-PAAycKd3T1oAOi8wCwBbBHxI6I9reMSUtLiwbDhZeABRJVTYCKjeNg4-DGowOCIiMIkY7JoASh5ugG4QABoQCAwYUmgiZFBZbGoaAAU5hGmUWQA3CFIpYZB5bFkwAGs4GABlDCOJAHNkGGwLOBGJelxFw5vk2WRTWVF6CMAFZENBUI6nC6yVIAGXsv3+gJAV2wb2Q+wUBlE0D2jQkMAA6jsYAALZAADgADCNGhB6ATDhh0Y0WgwNnA9kUAI4WUhFD6yL4-JB-AHPED0ZKke6PcVEW5KACKFgg8ARYpGMAURKkpOQACZNYdSFobgBhCDJb7o3RqPYWegAFQUa1F9AAvu6gA)
```sh
--parser babylon
```

**Input:**
```jsx
export const isBrowser = !!(
  // tslint:disable-next-line:no-typeof-undefined
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement &&
  !('process' in window)
);
```

**Output:**
```jsx
export const isBrowser = !!// tslint:disable-next-line:no-typeof-undefined
(
  typeof window !== "undefined" &&
  window.document &&
  window.document.createElement &&
  !("process" in window)
);

```

**Expected behavior:**
I'd expect prettier not to change format of this code or, if it had to, I'd expect
```jsx
export const isBrowser = !!( // tslint:disable-next-line:no-typeof-undefined
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement &&
  !('process' in window)
);
```

**Comment by j-f1** [comment] 2018-07-23 16:58
As a workaround, you can use `tslint-disable-line`:

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wEsiAhbCAdyLmzwF48BCVgCgB0o88YAnhjgQAZnhqkoAE1psmLAOQBXGXFFS40xXgD0u-kQA2UmEmnkAhgCMjcALQmocJFAj3BwsfdXT1m6R4+ADJgoIkpWRoAOlkwZQBbBHxQ8MkZWliIeKTYaLBsOEt4AFE7XJSw3jYORQxqMDgiIh0pCIyaAEoeToBuEAAaEAgMGFJoImRQS2xqGgAFGYRJlEsANwhSaUGQa2xLMABrOBgAZQwDqQBzZBhsZTghqXpcef2rhMtkUUsjeiGAFZENBUA7HM6WJIAGU031+-xAF2wL2QuxsAiM0B29VMAHUtjAABbIAAcAAYhvUIPRcfsMKj6k0GGs4DtCgBHZSkQpvSwfL5IH5-R4gegJUi3e4iojXOwARWUEHgcOFQxgNnx0iJyAATGr9qQnFcAMIQBKfVFuZw7ZT0AAqNhWQvoAF8XUA)
```sh
--parser babylon
```

**Input:**
```jsx
export const isBrowser = !!(
  typeof window !== 'undefined' // tslint:disable-line:no-typeof-undefined
  &&
  window.document &&
  window.document.createElement &&
  !('process' in window)
);
```

**Output:**
```jsx
export const isBrowser = !!(
  typeof window !== "undefined" && // tslint:disable-line:no-typeof-undefined
  window.document &&
  window.document.createElement &&
  !("process" in window)
);

```

<sub>sorry about the label spam — my GitHub reader app was uncooperative.</sub>

**Comment by thorn0** [comment] 2020-05-07 15:48
Duplicate of https://github.com/prettier/prettier/issues/5121

**Closed by thorn0** 2020-05-07 15:48 UTC
Labels: area:comments, lang:javascript, type:bug
