### ISSUE TITLE
Destructuring with long and nested properties does not wrap at the expected print width

### ISSUE THREAD

**Issue by hollandThomas** [prettier/prettier#10218] opened 2021-02-02 11:21 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEB9AlgE0wF5N8BDGMgOjACc4K4AVODAWVbTIHM4B1XDAAWAQQBKDADaSAngBlo3AHJkAtnCpoI6gGpxa8xQAVaEAA76YMqsNxoAkmhGStIhVG4nzl63nwBuAB0oYMgoDExgPwBfYlIKajoGeBZ2Th5+QVEJMmlDDxV1TW04PQN3T1MLWisbITtHZ1cKr2qrIJDOsIiogiQCWJJyShp6RlSYDjQuXgFhcSlZCsKNLV19fMrvGutbBycXCDdjKp8OkAAaEHMYXHRkUDJaUwB3IyeENGQQXJeyGS+VwARrQyGAANZwGAAZTMYNwHmQMFoAFc4Fc4KogXB8PgcXIyB4URkAGIQWiqCi3REoMgomAQS4gIQwVSSPj1eBoOFgODQz6CXAAN0EMm+YGmTIRaEsJh4lOQADNcjKrgArNAADwAQqCIVDoWo4HIEXAlSr0SANZroQjuJI4ABFFEQeDmlyWuG0GW0b5AsjYyRMsy0BEwAT4YTIAAcAAYriGIDK+KCzN8Q6x9EKzVcAI4u+CtL60tAAWigcBxOKZ9HzuHocu4CqQyo9VxlqlwSNRlrQdodztdZpbFqulCBEajSAATGPQbhJHaAMLaZsgVgAViZKJlTADxdbqpAQrR9igeNg0LouDMMBE5+hVgd7pl0WiQA)
```sh
--parser babel
```

**Input:**
```jsx
const _id = data.createTestMessageWithAReallyLongName.someVeryLongProperty.thisIsAlsoALongProperty._id;

const {_id} = data.createTestMessageWithAReallyLongName.someVeryLongProperty.thisIsAlsoALongProperty;


const {_id:id} = data.createTestMessageWithAReallyLongName.someVeryLongProperty.thisIsAlsoALongProperty;

```

**Output:**
```jsx
const _id =
  data.createTestMessageWithAReallyLongName.someVeryLongProperty
    .thisIsAlsoALongProperty._id;

const {
  _id,
} = data.createTestMessageWithAReallyLongName.someVeryLongProperty.thisIsAlsoALongProperty;

const {
  _id: id,
} = data.createTestMessageWithAReallyLongName.someVeryLongProperty.thisIsAlsoALongProperty;

```

**Expected behavior:**

I'd assume that this would be the expected behavior

```jsx
const _id =
  data.createTestMessageWithAReallyLongName.someVeryLongProperty
    .thisIsAlsoALongProperty._id;

const { _id } = 
  data.createTestMessageWithAReallyLongName.someVeryLongProperty
    .thisIsAlsoALongProperty;

const { _id: id } = 
  data.createTestMessageWithAReallyLongName.someVeryLongProperty
    .thisIsAlsoALongProperty;

```

**Comment by thorn0** [comment] 2021-02-02 13:13
Thanks for reporting. This falls under #3227. I'll copy your code example to that issue.

**Comment by thorn0** [comment] 2021-02-02 13:13
Duplicate of #3227

**Closed by thorn0** 2021-02-02 13:13 UTC
