### ISSUE TITLE
Typescript Class which only extends does not break when too long

### ISSUE THREAD

**Issue by appleseedexm** [prettier/prettier#13358] opened 2022-08-26 14:22 UTC
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAVUJm2IGUBXDObANVYE8AZaAcwDCJcgDliAWzh508KABMKHbJyU9+AQQBGpWsTAwhZUgBUAFsRgBxCHFIB5AG6sAssTTcEfGKbzAAvgA6UEFB6Fi4BMIU1LpMLOxcvFCCUWKSeACW4hiEcJKwFEl8AJKwrABmenBmFta2ji5uHsnevoHBHWE4+ERGVDR0cayqRYaiElIyCAp4Wjp0+mMUWTl5CDAUxfSm3W0gADQgEBgwGdCkyKDE2NgQAO4ACtcIFyjEhHfEnBeHmgsA1nAYPQJtwMlA4MhKoRSHBfgCgfQMHpwXxkLRGHDUOJNHA5HI8dxiMlGMQ+HAAGI4cQWU7JZAgYiMGAQA4gUwwcSEADqpgy8FIyLAcHoL35GQc-M4DLA5DZ4NhuAedD4NKh71hhwAVqQ0PRUbkAIqMCDwdUwrHI7CKhkwTgsUhgbAZE5sjDO2DcjJybzIAAcAAZDu6ILDuXQMAz3bZWE42QBHE3wZXHV6M0gAWgheLxbOwcETGXzyrJaqQ0M1IFh4gy6OwmMOpANcGNpsh5Y1WJgxE0Xp9pmQACZDroMoRUQIIOIy6hSABWNmMWHGHuvCtYhyY0oE2D0J0umDqeT0O25c2wvx+IA)

```sh
--parser typescript
```

**Input:**

```tsx
export class UltraSuperVeryLongClassName extends VeryVeryLongAbstractClassThatGoesOverMaxLength {}


export class UltraSuperVeryLongClassName implements LongInterfaceThatGoesOverMaxLength {}


export class UltraSuperVeryLongClassName extends AbstractClass implements IShort {}
```

**Output:**

```tsx
export class UltraSuperVeryLongClassName extends VeryVeryLongAbstractClassThatGoesOverMaxLength {}

export class UltraSuperVeryLongClassName
  implements LongInterfaceThatGoesOverMaxLength {}

export class UltraSuperVeryLongClassName
  extends AbstractClass
  implements IShort {}

```

**Expected behavior:**

Prettier should break on class export with only an extends that goes over the max length. A shorter line which implements an interface does so.

**Comment by thorn0** [comment] 2022-08-26 14:40
Duplicate of #5156

**Closed** 2022-08-26 14:40 UTC
