### ISSUE TITLE
LESS: Function object parameter incorrectly formatted

### ISSUE THREAD

**Issue by eddie-dunn** [prettier/prettier#7143] opened 2019-12-16 13:12 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6ARgJwgdwM5yYAWAhmANYD6AlnABTAA6UABCwA4kAmX1UA5khYAGFgCZh7AB4BuZmwBkSADYk8MALRgi1ZVxZNWbFgAFgnHn34BfIROlyj15tYCUMkABoQEdjGrQeMigJJjYOAAKoQhBKCQAbhDUXF4gWGTkcDAAypxgVsgwmACucN5EMAC2ygDqOvB4eXDZMdT+8W0AnsjgeEHefASYMBGYJPyVJMgAZiTKBN4AVnhSAEJjFFnZJJVwADJ8cDNzCyDLUtlWynAAisUQ8MfzZSCcmEM9132p7Jh8MDVkjAiMgABzCby-CAEGpjdg9X5wIbxI7eACO93go18sRAag0UDgcC4xNSmDgGOo5NG40mT1OBEq1EKJReeCut0xRyQs2e3hgJHQgK4wOQYn5Y10VgAwhBKnSUFBoKiQMUCAAVQWxXmneKlACSUBJsGyYD+fgAgkbsjBOtd6XBrNYgA)
```sh
--parser less
```

**Input:**
```less
.browserhack_ie({
  padding: 0 20px;
  &:last-child {
    @{padding}: 20px;
  }
});
```

**Output:**
```less
.browserhack_ie({padding: 0 20px; &: last-child {@{padding}: 20px;}});

```

**Expected behavior:**
Reformatting `&:last-child` to `&: last-child` breaks the code which should not happen.

Ideally, input should be unchanged.

**Comment by evilebottnawi** [comment] 2019-12-16 13:18
Duplicate of #4524

**Closed by evilebottnawi** 2019-12-16 13:18 UTC

**Comment by eddie-dunn** [comment] 2019-12-16 13:40
@evilebottnawi Thanks for the quick reply, but the line collapsing is not the main issue here; it's that the formatting by prettier _breaks_ the code if it includes a colon (`:`).

**Comment by evilebottnawi** [comment] 2019-12-16 13:43
@eddie-dunn it is bug on postcss-less, we need update version and fix test, issue related to this problem too
