### ISSUE TITLE
Exit code 1 on dry run of prettier

### ISSUE THREAD

**Issue by AlexCppns** [prettier/prettier#4730] opened 2018-06-21 17:17 UTC
I thought a similar bug was fixed in 1.13.3 but I keep getting the error on the first run (the next one doesnt produce any error).

**Prettier 1.13.3**

```sh
prettier --config ./.prettierrc --list-different \"src/**/*{.ts,.js,.json}\" --write
```

**.prettierrc file**
```
{
 "printWidth": 120,
 "singleQuote": true,
 "useTabs": false,
 "tabWidth": 2,
 "semi": true,
 "bracketSpacing": true
}
```

**Expected behavior:**

Exit without error

**Actual behavior:**

```
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c prettier --config ./.prettierrc --list-different \"src/{app,environments,assets}/**/*{.ts,.js,.json,.css,.scss}\" --write
```

**Comment by suchipi** [comment] 2018-06-22 16:42
Could you create a repo where we can reproduce this that we could clone?

**Comment by j-f1** [comment] 2018-06-22 16:51
I think this is happening because passing `--list-different` causes Prettier to exit with a failure code if any files aren’t formatted correctly. It’s probably a bug that it still does that if `--write` is passed.

**Comment by suchipi** [comment] 2018-06-22 16:54
Duplicate of https://github.com/prettier/prettier/issues/4144

**Closed** 2018-06-22 16:54 UTC
Labels: area:cli, status:awaiting response
