### ISSUE TITLE
Typescript imports formatting does not obey printWidth limit

### ISSUE THREAD

**Issue by liolick** [prettier/prettier#3066] opened 2017-10-19 06:46 UTC
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22import%20%7B%5Cn%20%20%20%20eeeeeeeeeeeeeeeeeeeeee%5Cn%7D%20from%20'xxx%2Fyyyyyyyyyyyyyy%2Fzzzz%2Fqqqq%2Fwwwwwwwww%2Feeeeeeeeeeeeeeeeeeeeee'%3B%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```ts
import {
    eeeeeeeeeeeeeeeeeeeeee
} from 'xxx/yyyyyyyyyyyyyy/zzzz/qqqq/wwwwwwwww/eeeeeeeeeeeeeeeeeeeeee';

```

**Output:**
```ts
import { eeeeeeeeeeeeeeeeeeeeee } from "xxx/yyyyyyyyyyyyyy/zzzz/qqqq/wwwwwwwww/eeeeeeeeeeeeeeeeeeeeee";

```

**Expected behavior:**
Set --print-width to 100.
Import line is expected to be 100 symbols or less.

**Comment by ikatyang** [comment] 2017-10-19 06:49
Hi, thanks for the issue. This is a duplicate of #1954 which was closed with the following [comment](https://github.com/prettier/prettier/issues/1954#issuecomment-306067705):

> This is actually intended. We have a special case for import and require with single elements where we keep them in a single line. You don't get much more information when they are in two lines and they look worse with a series of imports. This was done due to common request from people using prettier.

**Closed by ikatyang** 2017-10-19 06:49 UTC
