### ISSUE TITLE
Prettier adds spaces which cause the linter to prohibit compiling.

### ISSUE THREAD

**Issue by Kashilas** [prettier/prettier#4269] opened 2018-04-06 08:47 UTC
No matter how I try to format this code snippet, Prettier formats it and adds two spaces for each part of the statement. This causes the linter to give me a compilation error because of unexpected spaces.

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOi3GGDKAc12wEEATACQjAEUBXOAJwE8AdKTmX3gPwACABQBHFhwDirDFQDKBIqSwAZYgGshAXiEUADvoDC0eAA8YOME1asEl-XapwAZsThVmbdotYA3DDA4HBICAHkAIwArODAYGTlFQmIydSgNEW5+PhzedGwcRw9Xd09JdgBJKizcmABKOprspFEJbwSFJRS1TR09QxNYOAsrGztYQqcSqA8vDl8AoJCCOfYOpOVUzUyeWuz83CLnNxmy7yqmnIaAbizd3kgoLBghYgwiAEMAG3WulTStLoDMZTMNLNZbPZJsUTrNygtAsEPoYEFQKlB3hhvqsNt0jLJ4LIPlgdtleG1pLJOsl-poADSXXgANQwcAA7gAVdj6YIcj4RL5wBn3HIHHCYKjOKAAMVZXyoWGFZMImFw+BpZBwFPYLPZlzq1xAdJAEH0RGgWGQoA+tggbIACjaEJaUB8-BA5EaQMSYMgXN98MaIqwPmANAR5PpQylkDBWCxjVR6H6A0KQMR8KwYPaQyQALYfFNfQMgKJYMwAIRDYYjHzzcDScCLJYgTBg+jbACZm2mo6xM8gQBF+ewvtAvY5iDAAOpydDIAAcAAZjY4IPhpyH9IOipm-E3jSHSHAAKJQKjIFcgI+heQwG2+pBXuwSDB2HMffOFpD+4tp-B5hgsbxv+KSCswEDwD2xr3hEs5UPOSCdjBIYYF8KQmHmBaDlA0AHiATD4HyEQur++AAL7kUAA)
```sh
--range-end 
--range-start 
```

**Input:**
```jsx
this.settings.isAdHocQuery
			? (queryGridSettingsLink = AppContext.current.predefinedQueryService.getObjectGridSettingsLink(
					this.predefinedQueryId
			))
			: (queryGridSettingsLink = AppContext.current.predefinedQueryService.getQueryGridSettingsLink(
					this.predefinedQueryId
			));

		const initialGridSettingsLink = AppContext.current.predefinedQueryService.appendInitialQuerySettingsCriterias(
			queryGridSettingsLink,
			ViewType.Table,
			this.hiddenFields,
			this.settings.queryView
		);
```

**Output:**
```jsx
this.settings.isAdHocQuery
  ? (queryGridSettingsLink = AppContext.current.predefinedQueryService.getObjectGridSettingsLink(
      this.predefinedQueryId
    ))
  : (queryGridSettingsLink = AppContext.current.predefinedQueryService.getQueryGridSettingsLink(
      this.predefinedQueryId
    ));

		const initialGridSettingsLink = AppContext.current.predefinedQueryService.appendInitialQuerySettingsCriterias(
			queryGridSettingsLink,
			ViewType.Table,
			this.hiddenFields,
			this.settings.queryView
		);
```

![image](https://user-images.githubusercontent.com/10863324/38411431-5da82340-3987-11e8-81a1-01343583d4c9.png)

**Expected behavior:**

Prettier should format the code so it doesn't provide unexpected spaces.

**Comment by ikatyang** [comment] 2018-04-06 10:11
Hi, there's already an issue for discussing the same topic, so please follow along there instead.

Duplicate of #4199

**Closed by ikatyang** 2018-04-06 10:11 UTC

**Comment by j-f1** [comment] 2018-04-08 14:32
Duplicate of #4199
