### ISSUE TITLE
Formatting of template literals is broken

### ISSUE THREAD

**Issue by sourabhv** [prettier/prettier#6359] opened 2019-08-06 12:09 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAtgIYDmOYAYptnlABQAmxMxAlPsADpT74A2cGPihwA7gBEWxANw8+AZzE4YYABb4m0gHTFa0Dt1598YYgrj4A5AoiE4AYXNwrSeSb6jJ0-AF5O7h58LKzq9rAKSPgA2oFBfEbx8ajE-PwARnoA1lEABgAkwMys2go4hAAOggCqFgBOUMT2AL74dXAVEHXwjPjE+BV1EOmChPg4vFwghXFJJsXE2qg4gksrcAByTXCzSc1TuQA0ux7Nx8bxALrn8c1yFybp7cRZ93z7UM0ghyAQFbjQBTIUDEOpDMQABVBCCBKGIADcIDhGN8QE9skIAMoVPQTUjIGB1dBwH5qGCEfgAdTUKjgChxYDgmJhKhw8JUAE9kOAFECfhN6jAIXUyCRkCl+BYfgArBQADwAQiKwFksdsADITODi1JSkCyuWYvGCACK6Ag8B1kpJIBxdXq3My6Tg-FRgwgFkpIoq3MGdLgdXh2p+AEdzfBhX9YSBzABaURwRiJ1HtMM4drC0XEK16iyEHAEok2spQUim8PapASvWsdKU5EwNTIABMP0JxBWeIcdjFKCg0GDIHQFgAKsR0rDqzbBhMYPXGI3kAAWAAMzWaQA)

**Input:**
```js
function magicFunction(data) {
  let newData;
  switch (data.action) {
    case 'someCase':
      newData = {
        attachments: [
          {
            fallback: `${data.simpleUsername} reported a problem in "${
              data.file.fileName
            }"`,
          },
        ],
      };
      break;
  }
}
```

**Output:**
```jsx
function magicFunction(data) {
  let newData;
  switch (data.action) {
    case "someCase":
      newData = {
        attachments: [
          {
            fallback: `${data.simpleUsername} reported a problem in "${data.file.fileName}"`
          }
        ]
      };
      break;
  }
}
```

**Expected behavior:**

Output should be same as input. This used to work fine in **v1.16.4**

**Comment by lydell** [comment] 2019-08-06 12:38
Hi!

[This was changed in 1.18.](https://prettier.io/blog/2019/06/06/1.18.0.html#stop-breaking-simple-template-literals-5979-by-jwbay).

This is being discussed in #6192.

**Comment by lydell** [comment] 2019-08-06 12:38
Duplicate of #6192

**Closed by lydell** 2019-08-06 12:38 UTC
