### ISSUE TITLE
JSX using TypeScript parser: error parsing multiline string literal

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier#4692] opened 2018-06-14 10:00 UTC
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AJ0CGMBAtAGYQQC8AOiDVLrgBYwwAOAzkgPQ8UQAdJAC2DOrh4A+EABoQEdjEzROyUAQBOmiAHcACloRqUBbBEzo5IAEaaCYANZwYAZXYPMUAObIYmgFc4eS9OOE0YfXtvEQJkMgIAGzD5ACtOAA8AIXsnF1cCETgAGS84eKSUkA9NMM1kEBgAT3Y4TjBNTCVrdk7YAHVLGGZkAA4ABnleiDD++3YG3rbw7HL5TTgARwDMDaiCGLikBOTgkDCRTD9As84vb0S4AEUAiHgK0-liG0H0YeQAExfeyYRL3ADCEBEsQaSUS1gCYQAKgQbCYTmEAL6YoA)
```sh
# Options (if any):
--parser typescript
```

**Input:**
```tsx
<div data-foo="
  https://foo.com
" />
```

**Output:**
```
Error: Comment "foo.com" was not printed. Please report this error!
    at https://prettier.io/lib/standalone.js:10488:13
    at Array.forEach (<anonymous>)
    at ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:10486:15)
    at coreFormat (https://prettier.io/lib/standalone.js:10535:3)
    at format (https://prettier.io/lib/standalone.js:10690:16)
    at formatWithCursor (https://prettier.io/lib/standalone.js:10702:12)
    at https://prettier.io/lib/standalone.js:19324:15
    at Object.format (https://prettier.io/lib/standalone.js:19332:12)
    at formatCode (https://prettier.io/worker.js:156:21)
    at handleMessage (https://prettier.io/worker.js:107:18)
```

**Expected behavior:**
No error.

Workaround: don't use string literals. Use template strings instead:

```tsx
<div data-foo={`
  https://foo.com
`} />
```

**Comment by ikatyang** [comment] 2018-06-14 10:35
This looks like the same root cause as #2347, let's track the issue there.

**Comment by ikatyang** [comment] 2018-06-14 10:35
Duplicate of #2347

**Closed by ikatyang** 2018-06-14 10:35 UTC
