### ISSUE TITLE
unstable member chain with object expression

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#5273] opened 2018-10-15 18:42 UTC
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASARgVwJYBsAmcATgDpQAE5AdEXAObYDO8RAFAOQBmEEAjOwBpy7AMK4Aho0bsAlGUpVx+fAEEidTAFsEMVvPIkYwYQGs4AT3ZJhAN2LmAtHaKPnr+049vPLn+9-euNB0TuK4mHDs5AC+ZDIA3GRkGDgExPo09EwsHNx8gsJiktJyFNRKqupaOnplhsD6lJTsZpbW7N6dXt0BPf79fg5BUCE2YRHsjTFxiVAgAiAQAA4w2NCMyKDiREQQAO4ACtsIGyjiNhDY+PMg6ETiYGYwAMpLD9gjyDBEEQsfjMQYAd7nRNOJkJwwgCFgArRgADwAQvdHnAXuJtAAZD5wCFQuALN5EAFEZC3cToczDG5LIgfGAAdSuMAAFsgABwABkJuwBDPuSzJtLgJLsN1oAEccLRgeJQeCkJDcNCQADNNgvj8CaqPnRcHAAIqYCDwPHK7UwClM-Cs5AAJgW33EeF1IggmjBZKg0FxC0wAIAKhTTkqAdFokA)
```sh
--parser babylon
```

**Input:**
```jsx
$builder
  .register('foo1', 'Class')
  .addArgument(
  	{ 'key': 'very-very-very-very-very-very-very-very-very-very-long-value' }
);

$builder
  .register('foo1', 'Class')
  .addArgument(
    {
      'key': 'very-very-very-very-very-very-very-very-very-very-long-value'
    }
);

```

**Output:**
```jsx
$builder
  .register("foo1", "Class")
  .addArgument({
    key: "very-very-very-very-very-very-very-very-very-very-long-value"
  });

$builder.register("foo1", "Class").addArgument({
  key: "very-very-very-very-very-very-very-very-very-very-long-value"
});

```

**Second Output:**
```jsx
$builder.register("foo1", "Class").addArgument({
  key: "very-very-very-very-very-very-very-very-very-very-long-value"
});

$builder.register("foo1", "Class").addArgument({
  key: "very-very-very-very-very-very-very-very-very-very-long-value"
});

```

**Expected behavior:**

```jsx
$builder.register("foo1", "Class").addArgument({
  key: "very-very-very-very-very-very-very-very-very-very-long-value"
});

$builder.register("foo1", "Class").addArgument({
  key: "very-very-very-very-very-very-very-very-very-very-long-value"
});

```

**Comment by duailibe** [comment] 2018-10-15 18:52
Duplicate of #2803

**Closed by duailibe** 2018-10-15 18:52 UTC
