### ISSUE TITLE
bug when dealing with arrow function

### ISSUE THREAD

**Issue by jiixing** [prettier/prettier#11495] opened 2021-09-11 21:39 UTC
It is removing the bracket in the second function, which results in different code

I tried with 2.3.2 and it is the same behavior

**Prettier 2.4.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdA3AhgJ1WAE1QF5UAKKAGlTgEoSA+c+4psuVAH09SjPZKpgcAB4AHCDhgBnJEIC+82gDpREqdOp0tq8ZJm0QlEBDEwAltGnJQuHBADuABVwJrKLABsHWAJ7XjACMcLDAAazgYAGUsAFs4ABlzKDhkADMvaTggkPDIqLFQ5IBzZBgcAFdskDhYwLgCAgaErChiiqxiuAAxSVisGAs25BAsCpgIIxAACxhYzwB1afN4aUKwOCi3FfMMFd8RsGkAkGSsqScQ4v70zOqAK2kRKJLPOABFCoh4W88s40KOHOI0CWHqnimYhwyRgC3MBBg02QAA4AAwA+xZBYhMQjKFwc4YVLGACOX3gl1M7lG0gAtCkGg0pjg4GTzCzLp0bkgMn9qllYuYypV+a8PuTUjy7sYYGC4QikUgAEwykLmTwlADCEFi3Jq0gArFMKlkACpg9y8-4gDBVACSUCasCiYGhZgAgo6ojBfG9fllFEA)

```sh
--parser babel
```

**Input:**

```jsx
   var cd = (n, e) => () => (e || n((e = {exports: {}}).exports, e), e.exports)
```

**Output:**

```jsx
var cd = (n, e) => () => e || n((e = { exports: {} }).exports, e), e.exports;

```

**Expected behavior:**

**Comment by fisker** [comment] 2021-09-12 14:01
This one should be the same as  https://github.com/prettier/prettier/issues/10955

**Comment by thorn0** [comment] 2021-09-13 18:41
Duplicate of #10955

**Closed** 2021-09-13 18:41 UTC
Labels: type:duplicate
