### ISSUE TITLE
Incorrectly removing parentheses breaks code.

### ISSUE THREAD

**Issue by GabrielGorta** [prettier/prettier#14201] opened 2023-01-18 13:06 UTC
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AAXgFsAHAGwEN5dgAjCCCuKqAX1wBUd8iyqAJyok6XTo2a8ChAcNHB0nAG5UKAVzjSiguDHWCoAZzG44AD3hQAJiZiDNuAPy4j9gJZQA5riS4o6iT0cILs0qg4AGbqUGAw7tBm5iKUcAAUkhQANLiqGnAAlHQ4uvqGuGm4GNhQMjAAnmRwphZWtrj2ji5ugp4+fgFBIWG1qLiZzrgAyh7eaXmaRX4AcoHBgvNqiwU47CBZIBBk8dBGyKBCghAA7gAKQghnKGrXVPVnB-TCYADWelMiOAAGU8cGQkTURjgn2+fxgUwEYD6yE60JAcCG1mscGsQLYXnUVC8cAAYhBBCQaPFvMgQFR1DAIPsQAALGAkCgAdRZ7ngRkRcCmj157mUvPqtLARg+IE8UMEMFuwi8lPBkLRACsjOYpn0WABFdQQeBqihQg5yeW0hpNIxgXrHZlkXqwTnuawwFnIAAcAAYLVcoZzhGRac64PLlGCDgBHI3wJVHJ50owAWigcBxOOZujj7l0SqJqqQELNaKhJHcKIc5b1cAAgjAPPQGXBbiEQRnTeaQEY64bjWCS+qDjAqPQ3R6vUgACyj4TuCh9ADCEBIxfRRgArMz1FCuOOnqWe8pNABJGwIeH29zHes2Gb1FjduDsdhAA)

**Input:**

```js
/**
 * @template {boolean} T
 * @param {T} bool
 * @param {*} value
 * @returns {T extends true ? string : number}
 */
function example(bool, value) {
return ( /**
* @type {T extends true ? string : number}
*/ bool ? String(value) : Number(value))
}
```

**Output:**

```js
/**
 * @template {boolean} T
 * @param {T} bool
 * @param {*} value
 * @returns {T extends true ? string : number}
 */
function example(bool, value) {
    return /**
     * @type {T extends true ? string : number}
     */ bool ? String(value) : Number(value);
}
```

**Expected behavior:**

as you can see, in input I have `(` after return statement. In that case, example function returns either string or number based on bool. But if I format it, `(` is removed, and in result, void is returned, [because of early ";" semicolon  insertion by runtime](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#automatic_semicolon_insertion). In result, prettier breaks code.

**Comment by fisker** [comment] 2023-01-18 14:21
Duplicate of #11358

**Closed** 2023-01-18 14:21 UTC
Labels: type:bug, type:duplicate, lang:javascript
