### ISSUE TITLE
Prettier breaks HTML, can it detects HTML and don't format?

### ISSUE THREAD

**Issue by michaellee8** [prettier/prettier#4518] opened 2018-05-21 01:56 UTC
I just generated some ugly html using some tool, and used prettier to format it because I used the format in save option in vscode. As a result, it broke this https://michaellee8.github.io/iclass-pdftohtml-demo/single-page.html into https://michaellee8.github.io/iclass-pdftohtml-demo/single-page-broken-by-prettier.html . So my question is does prettier actually accepts HTML for being formatted? If not, can it identify which file is html and just touch it as if it is JSX and ruins it?

**Comment by ikatyang** [comment] 2018-05-21 02:37
Currently, the HTML support is still WIP and it's not released, I guess the root cause here is that our default parser is babylon, which means it'll consider everything as JavaScript (JSX) files if it can not identify which parser to use, see #2884 for more info.

As a temporary workaround, you'll have to disable formatOnSave for html files in vscode:

```json
{
  "[html]": {
    "editor.formatOnSave": false
  }
}
```

**Comment by ikatyang** [comment] 2018-05-21 02:37
Duplicate of #2884

**Closed by ikatyang** 2018-05-21 02:37 UTC
