### ISSUE TITLE
[TypeScript 3.7] add support for optional chaining

### ISSUE THREAD

**Issue by patrik-piskay** [prettier/prettier#6595] opened 2019-10-02 09:30 UTC
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI

**Steps to reproduce:**
I was able to reproduce in the playground when using the typescript parser, which I guess it's the parser that ends up being used by prettier in typescript files? In my case its happening for both `.ts` and `.tsx` file extensions.

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAdAIwPzrCAGhAgAcYBLaAZ2VFQCd6IB3ABQYRpVQDcJyAJoRCZ6qMAGs4MAMolx5KAHNkMegFc4RABYwAtgBsA6tvLwq8sHBmcz5HmYCeycFRpFFVOPRisxSvVRkADNUAy8iACsqAA8AITFJaRlUPTgAGUU4ELCIkGiYmUUlAzgARXUIeBzwrRB5ei96FxhHEjgqMHpyMmESbtgjQRhtZAAOAAYifogvIzESF36O7x5sogBHSvg-Ui40KgBaKDg4ATPhejgt8iu-VACgpFDaoi89clUNOqpi0oqqtlnrk6jBUJghgIRsgAExENSocgGYoAYQgekCLig0HWIHUXgAKuCuC8vABfMlAA

**Expected behavior:** does not throw "Expression expected" syntax error when using optional chaining in typescript files

**Actual behavior:** throw "Expression expected" syntax error when using optional chaining in typescript files

**Comment by sosukesuzuki** [comment] 2019-10-02 09:39
Thanks for creating the issue. It is still in dev, we have not support it yet as mentioned in #6574.

**Comment by lppedd** [comment] 2019-10-02 09:47
@sosukesuzuki but you mean `dev` for Prettier or for TypeScript?

**Comment by sosukesuzuki** [comment] 2019-10-02 09:50
@lppedd I meant `dev` for TypeScript. But, I think we should prepare for TS 3.7 :+1:

**Comment by lppedd** [comment] 2019-10-02 09:53
@sosukesuzuki thanks! Here we are already using TS 3.7 `beta`.

**Comment by evilebottnawi** [comment] 2019-10-02 11:23
I think we need update ts parser

**Comment by sosukesuzuki** [comment] 2019-10-02 11:28
@evilebottnawi I'm worried that we can't update `typescript-estree` that because of the version of Node that Prettier supports... (also, updating `typescript-estree` enable to fix #6569 )

**Comment by 0rvar** [comment] 2019-10-02 13:59
Could we use the babel parser instead? It already has support for Typescript when using the typescript preset

**Comment by evilebottnawi** [comment] 2019-10-02 14:18
@0rvar https://github.com/prettier/prettier/pull/6400, should be shipped in `1.19`

**Comment by lppedd** [comment] 2019-10-02 14:38
@evilebottnawi so that means after merging that PR, potentially I could build Prettier and use the Babel parser with 3.7?

**Comment by evilebottnawi** [comment] 2019-10-02 14:43
@lppedd should be, but we still need add tests to avoid regression

**Comment by lppedd** [comment] 2019-10-02 14:51
@evilebottnawi sure. It would be only a temporary solution to keep using Prettier.

**Comment by fisker** [comment] 2019-10-03 15:56
Can `typescript` v3.7.0-beta https://www.npmjs.com/package/typescript/v/3.7.0-beta help?
As I tested yesterday when I do #6519 , it's safe to update to `v3.7.0-beta`

**Comment by evilebottnawi** [comment] 2019-10-03 15:58
@fisker sometimes ts command do big changes on alpha or beta, better wait stable release

**Comment by fisker** [comment] 2019-10-03 16:13
@evilebottnawi you're right, but I'm going to test on 3.7.0-beta to prepare for 3.7 stable release

**Comment by fisker** [comment] 2019-10-03 16:15
https://deploy-preview-6600--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBDAdAIwPzrCAGhAgAcYBLaAZ2VFQCd6IB3ABQYRpVQDcJyAJoRCZ6qMAGs4MAMolx5KAHNkMegFc4RABYwAtgBsA6tvLwq8sHBmcz5HmYCeycFRpFFVOPRisxSvVRkADNUAy8iACsqAA8AITFJaRlUPTgAGUU4ELCIkGiYmUUlAzgARXUIeBzwrRB5ei96FxhHEjgqMHpyMmESbtgjQRhtZAAOAAYifogvIzESF36O7x5sogBHSvg-Ui40KgBaKDg4ATPhejgt8iu-VACgpFDaoi89clUNOqpi0oqqtlnrk6jBUJghgIRsgAExENSocgGYoAYQgekCLig0HWIHUXgAKuCuC88jxNABJKDnWAyLo9GAAQWpMlapRqXgAvpygA

3.7.0-beta can parse this now, but not printing it right

**Comment by thorn0** [comment] 2019-10-04 18:05
@fisker There is a [`typescript-estree`](https://www.npmjs.com/package/@typescript-eslint/typescript-estree) between TypeScript and Prettier. It transforms TS AST to the format that Prettier understands. So it should be updated too, however see [this comment](https://github.com/prettier/prettier/issues/6595#issuecomment-537450297)...

**Comment by lppedd** [comment] 2019-10-09 11:10
So, as I need to format TS 3.7, I forked this repository and merged on `master` what was needed to use it. I've published a temporary NPM package at https://www.npmjs.com/package/prettier-next-lppedd, feel free to use it, I will remove it as soon as 1.19 is out.

**Comment by fisker** [comment] 2019-10-09 11:54
Youshould not publish a npm package cause you cant unpublish after 24 hours , should install from your repo

**Comment by jwulf** [comment] 2019-10-11 15:29
> Remember to alias the command prettier-next-lppedd with prettier

What does this mean? Is it an npm or shell operation?

**Comment by lppedd** [comment] 2019-10-11 15:51
@jwulf yes, that happen because you're still using the standard Prettier.
When you install Prettier, a new runnable command is also created under `node_modules/.bin`.
The temporary package has the command `prettier-next-lppedd` in bash.
![image](https://user-images.githubusercontent.com/19871649/66665809-9487a580-ec4f-11e9-8e3c-c635b622c8c5.png)
But lets not clutter this issue, if you still have problems hit me up on mail.

**Comment by bradzacher** [comment] 2019-10-14 17:12
FYI, we just landed and released https://github.com/typescript-eslint/typescript-eslint/pull/1045 which adds support for optional chaining + nullish coalescing in `typescript-estree`.

**Comment by thorn0** [comment] 2019-10-15 13:43
@bradzacher Unfortunately, Prettier has troubles with updating to the new version of `typescript-estree` because we still support Node 6 and aren't ready for a major release yet. Is bring back the support for Node 6 probably something we can ask you of?

BTW, didn't you miss [this 3.7 syntax addition](https://github.com/prettier/prettier/issues/6661)?

**Comment by bradzacher** [comment] 2019-10-15 16:24
hmmm, I did miss it. It wasn't listed in the beta release post.
I've raised https://github.com/typescript-eslint/typescript-eslint/issues/1086 to track it.

---

We still have full compat with node 6, we just don't explicitly test against it any more. We only dropped explicit support to keep sync with ESLint themselves, and because it was EOL in April. AFAIK there weren't any breaking changes between node 6 -> 8 that should effect our codebase.
I guess we can add back explicit support if you'd like?

**Comment by thorn0** [comment] 2019-10-15 16:33
> I guess we can add back explicit support if you'd like?

It would be wonderful.

**Comment by thorn0** [comment] 2019-10-16 20:39
@bradzacher `chokidar`, one of your dependencies, requires `"node": ">= 8"`, so it looks like we're out of luck.

**Comment by bradzacher** [comment] 2019-10-16 20:48
In the process of exploring the removal of that dep.
We added a feature in 2.4 to attempt to alleviate problems with IDE plugins when using the parser in full typecheck mode (which prettier doesn't use).
I've got some thinking to do on this feature, as it's pretty complex, and has caused some problems for some users. I'll get back to you soon.

**Closed** 2019-10-28 16:53 UTC
Labels: lang:typescript, scope:dependency

**Comment by MLoughry** [comment] 2019-10-30 19:33
@lydell Is there a stated plan for releasing a version with this change?

**Comment by lydell** [comment] 2019-10-30 19:38
@MLoughry Yes! We’ve just finished all blocking items for the [1.19 milestone](https://github.com/prettier/prettier/milestone/32).

**Comment by capaj** [comment] 2019-11-05 20:25
@lydell typescript 3.7 just came out, please run the release 
![http://giphygifs.s3.amazonaws.com/media/CT5Ye7uVJLFtu/giphy.gif](http://giphygifs.s3.amazonaws.com/media/CT5Ye7uVJLFtu/giphy.gif)

**Comment by lydell** [comment] 2019-11-05 20:30
I was going to a couple of hours ago but ran into problem. I'll try again tomorrow.

**Comment by emadow** [comment] 2019-11-06 05:16
> I was going to a couple of hours ago but ran into problems. I'll try again tomorrow.

👏 👏 👏

**Comment by nodece** [comment] 2019-11-06 16:07
@lydell Thank your team for looking forward to this feature.  typescript 3.7 is faster.

**Comment by ShanonJackson** [comment] 2019-11-07 01:23
Please prettier team, i'm too excited to use the new features

**Comment by kripod** [comment] 2019-11-07 01:37
The maintainers are definitely trying their best to cut a release as soon as possible. Postponing is still better than rushing towards a pile of potential issues.

We all appreciate the hard work put into this project and wish the best to everyone involved!

**Comment by JCMais** [comment] 2019-11-07 11:58
For the ones that cannot wait for the new release, you can just install prettier from the master branch For those that cannot wait you can just install prettier from the master branch `yarn add --dev prettier/prettier#master`

**Comment by yordis** [comment] 2019-11-07 14:31
No
![](https://i.kym-cdn.com/photos/images/original/001/483/310/4f2.jpg)

Give me a release

P.S:

Thumbs-down voters: come on folks, don't make somebody feel shame (I would feel like that) because they are so happy to have such amazing feature, do you realize how exciting this feature is?

They want to share with you 🤷🏻‍♂️ why not?! be friendly and welcome, it takes less energy and will make you feel better.

I get it, you get useless notifications (like mine), unsubscribe if that bothers you that much, the ticket is closed anyway ☮️

**Comment by vernondegoede** [comment] 2019-11-07 15:53
The goal of issues is to discuss the actual issue itself and/or stuff that has to be done around the issue, instead of creating a place to distract the maintainers from actually fixing the issue. @yordis

**Comment by yordis** [comment] 2019-11-07 15:59
@vernondegoede I agree with you, that is why you close the threads 😉

So you avoid toxic environments where some people want to focus on pragmatism but at the cost of people that don't understand that 🤷🏻‍♂️ I am just trying to help you.

Hard to disagree with your thoughts since I am more alike to you, but I refuse to justify toxic behaviors for such pity thing.

Close the thread as soon as things are resolved, the problem is solved.

**Comment by BrandonKowalski** [comment] 2019-11-07 15:59
Not to beat a dead horse further but this is the ultimate irony @yordis ....

https://github.com/facebook/create-react-app/pull/7438#issuecomment-533205086

With that said thanks for the workaround @JCMais!

**Comment by yordis** [comment] 2019-11-07 16:02
@BrandonKowalski you are right thinking that way, but you are wrong thinking that people don't change and calling this irony, that is a simple conclusion.

Because of those exact words, I figured out what the solution for this issue is 😉 

I figured out that being toxic helps nobody included the maintainers, so now I more proactive.

Close threads if you want to stop these things from happening.

**Comment by evilebottnawi** [comment] 2019-11-07 16:08
Locking for avoid toxicity, release will be tomorrow (Friday)
