### ISSUE TITLE
0️⃣ Template strings don't line-break like other strings

### ISSUE THREAD

**Issue by Sawtaytoes** [prettier/prettier#10556] opened 2021-03-16 22:55 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAjANgQwAtMBeTYAHSk0wwgCc4lMByABwLDhYBoqaYENgEswzAAYxCwtJhmYAtgE9MU4VADmzACTBhAEwQxhAM2Fx6AX3F8olqiB4ghx9MlD569CAHcACp4IaMgg+Lg++ErBTtj0+GAA1nAwAMps8eoayDD0AK5wTnAK2HD6hvoAMviaufgacABiDAr4MMaaIfi5go4ghDAKuADq0vBo6VwpQcLGAG4zSiFgaNEg6mgWMH5xGi3IJmEbTgBWaAAeAEJxickp+ApwFepw+4cFIKdnKZm4cACKuQg8FeuCOIHS9A29BC2HwJVwvTY9HUMCGBikyAADE4kRANkM4mwQki4FDZi8nABHQHwbZCYIofBoAC0UDgpVKvUY1OEjG2dT2SAOoPeGwUwmyeVFP3+NJeQreThgcLR+gxSAATEq4sJcJkAMIQBSCkCkgCsvVyGwAKnCGcKwbN8gBJKCGWApMDItgwACCbpSMCUvxBG0sliAA)

```sh
# Options (if any):
--print-width 0
```

**Input:**

```jsx
const blah = {
  store: 'place',
  topic: `this is my thing: ${identifier}`,
}
```

**Output:**

```jsx
const blah = {
  store:
    "place",
  topic: `this is my thing: ${identifier}`,
};
```

**Expected behavior:**
```jsx
const blah = {
  store: (
    "place"
  ),
  topic: (
    `this is my thing: ${identifier}`
  ),
};
```

Or at least a compromise to keep things consistent:
```jsx
const blah = {
  store:
    "place",
  topic:
    `this is my thing: ${identifier}`,
};
```

If you're going to drop strings, why not template strings? Template strings are almost always pretty lengthy. Tabbing it back a couple spaces will help with readability and at least keep it line-breaking consistently with other strings.

Seems weird to have a special case for template strings. Is it because there could be an interference with how tabs are formatted when dropping the template string down a line?

**Comment by thorn0** [comment] 2021-03-17 00:04
Duplicate of #4719

**Closed** 2021-03-17 00:04 UTC
Labels: type:duplicate
