### ISSUE TITLE
Vertical bars enclosed in backticks are parsed like table column delimiters

### ISSUE THREAD

**Issue by jsamr** [prettier/prettier#11922] opened 2021-12-04 13:35 UTC
**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAFAlgGwjAPgQXQCcAHCImAHSgFobck6lqADXNgZQGkBxakADQgIJGOmgBnZKACGRIhADuqOQikoZmRTICeUoQCMiMsAGs4MDjIC2cADLoocZADNNEuIeNmLHEiccAc2QYIgBXTxA4awM4ABM4+LsZKECwmUC4ADFyaxkYMVTkEBkwmAhBEAALGGtMAHUq9HgJfzA4DjVm9AA3Zp1isAl9EEcPClRjQLzXd0iAKwkADw4gzDgARTCcZyQ3TA8hfyJx4ryiUzilKEqSIkcYevQ4mCrkAA4ABiOFD3rjEjFO5wcY9ZxCACO23gkxE6hKEhoTni8UqRDgUOIcEmGRmezmQg81nQIXCkQka020N2+0OIBgMgMTxebyQACYhKEZFgggBhCDWPFRCQAVkqYQ8ABVGepaZEehEAJJQRKwDhge6ifAqjgwHTrWYHOAAX2NQA)

```sh
--parser markdown
```

**Input:**

```markdown
Pilot|Airport
--|:--:
`|`|SKG

```

**Output:**

```markdown
| Pilot | Airport |
| ----- | :-----: | --- |
| `     |    `    | SKG |

```

**Expected behavior:**
```markdown
| Pilot | Airport |
| ----- | :-----: |
| `|`   | SKG     |
```

**Comment by kachkaev** [comment] 2021-12-04 13:46
Looks like a duplicate of https://github.com/prettier/prettier/issues/9146

The fix:

**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAFAlgGwjAPgQXQCcAHCImAHSgFobck6lqADSy3F3AZQGkBxaiAA0ICCRjpoAZ2SgAhkSIQA7qkUJZKeZhXyAnrNEAjIvLABrODG7yAtnAAy6KHGQAzHdLgmzl69wk5i4A5sgwRACuPiBwdsZwACaJSY7yUCGR8iFwAGLkdvIwkhnIIPKRMBAiIAAWMHaYAOq16PDSQWBw3Jpt6ABubfplYNJGIC7eFKhmIYUeXjEAVtIAHtyhmHAAipE4bkiemN6iQURTZYVEFomqUDUkRC4wTeiJMLXIABwADKfK3iaZhIZUecCm-TcogAjnt4DNxFpytIaK4kkkakQ4LDiHAZtl5odFqJvHZ0OEojFpJsdnCDkcTiAYPJjK93p8kAAmUQReRYUIAYQgdkJsWkAFYapFvAAVFlaBkxfrRACSUBSsG4YCeEnw6u4MH0WwWxzgAF8zUA)

```sh
--parser markdown
```

**Input:**

```markdown
Pilot|Airport
--|:--:
`\|`|SKG

```

**Output:**

```markdown
| Pilot | Airport |
| ----- | :-----: |
| `\|`  |   SKG   |

```

**Rendered output:**

| Pilot | Airport |
| ----- | :-----: |
| `\|`  |   SKG   |

**Comment by alexander-akait** [comment] 2021-12-04 13:47
Yep, I see

**Closed by alexander-akait** 2021-12-04 13:47 UTC
Labels: type:bug, lang:markdown

**Comment by jsamr** [comment] 2021-12-04 14:32
There seems to be a serious inconsistency in the GFM specs.

In [**6.1, backslash escapes**](https://github.github.com/gfm/#backslash-escapes), `\|` is listed as a known escape sequence. But in [**6.3, code spans**](https://github.github.com/gfm/#code-spans), the following is asserted:

> Note that backslash escapes do not work in code spans. All backslashes are treated literally.
>
> Backslash escapes are never needed, because one can always choose a string of n backtick characters as delimiters, where the code does not contain any strings of exactly n backtick characters.

According to the spec, backslash escapes must not work in code spans. Unfortunately, I haven't found a place where the GFM spec is publicly discussed.
