### ISSUE TITLE
Function argument indentation bug with chained function calls

### ISSUE THREAD

**Issue by ridjis** [prettier/prettier#7177] opened 2019-12-26 09:03 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB3ATgQwA7bugHSgAJiA6AMwEsoATACgHIBRWqmANSrlWIEko2AK4xGASiKlKVdAGcY9CSXLZ0EbE2gBhABaYoAczjj6wSaWIxM6IzCTEzyi8SiYAtnHuNqcmADl3YwAac2cAN0wAGyFPYkYAWSoAa2DQ4gBfEOV0sQBuECCQdRgqaFlkUGs1VAAFawRylEwwiCpaApAAIywwFJgAZWxMMBoDZBh0GMKdGDdIgHUddjhZIbA4fob2KjD2AE9kcFlywppZfBgarAM3TGQKKPPCgCtZAA8AIR6+-sCAGRocHujzgL3e-VGkTgAEUhBB4MDIk8QEM5PhDjA9nhZGB0FRsDAOqoaDB5m0YDpkAAOAAMhVUEHO8yw2EOqhW+DCQMKAEc4fArupGiBMLIALRQOBwWjSjroOB8mRwK6YG53JAPJGgkDnNxUcaTbWySEw-lAjUgwpWTpk2gU5AAJitWCokVGWggbluhyg0G5ICE5wAKphOo1NciwjEBDLYP1cfiYABBOj9TFQxHndLpIA)
```sh
--parser typescript
```

**Input:**
```tsx
wrapper
  .find('EditView Input')
  .first()
  .prop('onChange')({
    target: {
      name: 'firstName',
      value: 'Mike',
    },
  });
```

**Output:**
```tsx
wrapper
  .find("EditView Input")
  .first()
  .prop("onChange")({
  target: {
    name: "firstName",
    value: "Mike"
  }
});

```

**Expected behavior:**

I expected it to indent target object just like it does when `)(` is replaced with `,`. [Example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB3ATgQwA7bugHSgAJiA6AMwEsoATACgHIBRWqmANSrlWIEko2AK4xGASiKlKVdAGcY9CSXLZ0EbE2gBhABaYoAcziMANMWCTSxGJnRGYSc5avEomALZxHjanJgA5D2MTZysAN0wAGyEvYkYAWSoAa2DQgF8Q5TSxAG4QExB1GCpoWWRQWzVUAAVbBDKUTDCIKlp8kAAjLDAUmABlbEwwGgNkGHQYgp0Yd0iAdR12OFlBsDg++vYqMPYAT2RwWTKCmll8GGqsA3dMZAoos4KAK1kADwAhbt6+oIAZGjgdwecGebz6I0icAAikIIPAgZFHiBBnJ8AcYLs8LIwOgqNgYO1VDQYHNWjAdMgABwABgKqggZzmWGwB1Uy3wYUBBQAjrD4Jd1A0QJhZABaKBwOC0KXtdBwXkyOCXTDXW5Ie6IkEgM7uKhjCZa2QQ6F8wHq4EFGwdUm0cnIABMlqwVEiIy0EHcNwOUGgXJAQjOABVMB0GhqkWEYgJpbA+ji8TAAIJ0PoYyEIs5pNJAA).

**Comment by sosukesuzuki** [comment] 2019-12-26 20:21
Duplicate of #6476

**Closed** 2019-12-26 20:22 UTC
Labels: lang:javascript, type:bug, type:duplicate
