### ISSUE TITLE
Line break on single import 

### ISSUE THREAD

**Issue by FeliceGeracitano** [prettier/prettier#2802] opened 2017-09-13 13:37 UTC
**Prettier Version:** 1.6.1 / master

([playground](https://prettier.io/playground/#%7B%22content%22%3A%22import%20%7B%20Mycomponent%20%7D%20from%20'.%2Fmycomponent-parent-directory%2Fpath%2Fpath%2Fpath%2Fpath%2Fcomponent.component'%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

**Expected behavior:**
```js
import {
  Mycomponent
} from "./mycomponent-parent-directory/path/path/path/path/component.component";
```
**Actual behavior:**
```js
import { Mycomponent } from "./mycomponent-parent-directory/path/path/path/path/component.component";
```

**Comment by FeliceGeracitano** [comment] 2017-09-13 13:39
Is that a wanted behaviour?

**Comment by ikatyang** [comment] 2017-09-13 13:47
Hi, thanks for the issue. This is a duplicate of #2441, which was closed with the following [comment](https://github.com/prettier/prettier/issues/1954#issuecomment-306067705):

> This is actually intended. We have a special case for import and require with single elements where we keep them in a single line. You don't get much more information when they are in two lines and they look worse with a series of imports. This was done due to common request from people using prettier.

**Closed by ikatyang** 2017-09-13 13:47 UTC
