### ISSUE TITLE
Comments in decorators are moved

### ISSUE THREAD

**Issue by maxime1992** [prettier/prettier#2009] opened 2017-06-06 20:22 UTC
I do have an angular starter (with ngrx setup amongst other things) where I wanted to setup `prettier` on it. It's a `Typescript` project.

So I gave a try and when I was checking the changed files, I noticed that I have some of my comments that are moved.

A picture is often worth a 1000 words : 
![image](https://user-images.githubusercontent.com/4950209/26849885-03101688-4b06-11e7-8957-ccb2b07c0607.png)

If you want to give a try on my repo, here's how to do that quickly : 
```
git clone https://github.com/maxime1992/angular-ngrx-starter.git
cd angular-ngrx-starter
git checkout setup-prettier
yarn
yarn run prettier:write
```

(which will call : `prettier --parser typescript --single-quote --trailing-comma es5 --write "./{e2e,src}/**/*.ts"`)

**Comment by azz** [comment] 2017-06-06 22:23
Closing as a duplicate of #1956.

Can you confirm the issue goes away if you delete `export`? If not, please re-send.

**Closed by azz** 2017-06-06 22:23 UTC
Labels: bug

**Comment by maxime1992** [comment] 2017-06-07 06:56
Yes it does work great if I remove the `export`. Sorry for duplicate, I should have look before posting ... !
