### ISSUE TITLE
MDX: React component props lead to incorrect behavior when single/double quotes are used and string contains HTML text

### ISSUE THREAD

**Issue by TimeDropsSB** [prettier/prettier#7408] opened 2020-01-21 20:46 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAFQJYwDZwA6UxAPALICeAwhALYAO0CMx66AJnAM5gBO2BjGzQAvMEIgeMAGYcZCyQF826ABYw6eAKIE6LbuIDaAA1IAPALSRGzWAD4TAGnRmrNplBaWAhlAgwanB8jgC6KlAA9PbExKgYABJwPhzYUADm6ABMsVAAMhB8cHTogtwAriUcEHiF6Ny46D76MC6QUNxwYPAw5XxNqQzYvGmZcHi4Lp0cnBDocNjl3HQQM-C2-Wlg2Kkc5bDo5TDoeD4ARoVw88fVtUXodD7pUD5NEwCO5T4AdOgAqscENgSikHmlgegAG5A5ouT7DdD+bgwPjlGZwczBbYwHzCaCHPCnOiQE7nQoIqDDbCHY4+D7lQTzczzV42FbVdDtTqfXG-AAiDO4TSOV2wqPutzqaXQRQYRSCUC4AmO0shNXKQlxV2hE0B3E6nOwhMqszuVzg5XQMnK6WwuMR5UJrwYPgEuL6v205jAcCEFv6DQOEDAYB8XXtYA1O1x9v8UHQcogOxYU32KvjkbwLvQ8PQEAU2G2ry4nVRBxWhMafghO3myNJF1RdG+xBAThAECEIg6yFArr4EAA7gAFV0IbjIEA+NU7NsgM58HxgADWcBgAGUXdsMsgUeU4O2NFoAOpqXA8Ldwdfj3DYSG4SiTsD6udpUswYeL9KPZAyOmddsACtuHMAAhRcVzXddmjgPI0jgX9-wPEBgPMddRgIABFcoAgQpA-zwACQBdPhS0nOgOHMOc5TSGBjx2QJkAADgABnbRNOmPRcGEnOUeGCaE50+XDP07CcUB8bhLC8OAuA4OcinhIpPyeH98KQ9tOjobBd1RZDA3SLCcPgRDCOQnEznojhGKQLJ2xRHwjVGWg6DUkA4wQ9sljgTBznEgiiMhfcAElFRYdd+EEGAAEFFXXGBKAIUzOiUJQgA)
```sh
--parser mdx
```

**Input:**
```mdx
# Title

<MyComponent
  description={"estfdfff"}
  htmlElements={[`<x-component>`, `<x-component-another>`]}
/>
```

**Output:**
```mdx
SyntaxError: Unexpected token (1:14)
> 1 | <x-component>
    |              ^
```

**Expected behavior:**
This should format correctly.  The issue is actually caused by the `description` using double quotes which leads to the error in the `htmlElements`.

Current workaround solution is to change the double quotes in `description` to backticks and it will work.  Like so:

```mdx
# Title

<MyComponent
  description={`estfdfff`}
  htmlElements={[`<x-component>`, `<x-component-another>`]}
/>
```

**Comment by thorn0** [comment] 2020-01-21 20:52
This has been fixed, but not yet released. See https://github.com/prettier/prettier/issues/7176

**Comment by thorn0** [comment] 2020-01-21 20:53
Duplicate of #6943

**Closed by thorn0** 2020-01-21 20:53 UTC

**Comment by TimeDropsSB** [comment] 2020-01-21 20:56
Ah oops, I wasn't sure if it was the same issue or not.  Thanks a bunch.
