### ISSUE TITLE
Formatting off for indented parameters to function

### ISSUE THREAD

**Issue by mzedeler** [prettier/prettier#3376] opened 2017-12-02 14:34 UTC
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0BUABALYCeAygIYDmlAzgBQCUhwAOlIYaTnADYATQnFSo42OgDoYlANZwAogDc4AJ1IMOXLqrgAPAA666UytjxQAKqQNwpAJQUBFAKoLylgPoeAgvcsANFraGFi4BAzAhDhCAL4s7JzaXJBQdBB8cJJ8ENQMMUwA3MHJPPxCuobGpubQjHQwELpMkgDuqjjwABJwlAL5AgGEACwADKNFJdplgoSVRnY14WkMDU1wLQj9MUMA5AbQ1LuTScmp6ZnZuQz7h8fFp4SxwSexIAEgEAbLdMig9DBkKhKHw6HAPgAjVRmeQwcgGMw4KDUZAwVTocEgAQQMBAkFgj5IsGqGAABWh1GIlDxoMxACs6HoAELQsCwqjEOAAGSRcBpBM+6BgBiFACZ+ZiEapicgQBDKBDSDkoO8QEYkTAAOoxGAAC2QAA5Rh8jBAwZroQZUejMboAI7oHC6ck0KkSj5g4g4a0Yj1I6iZJzoCDwd0gGQQ7UCPXIUUfNGUHB8f0AYQgxDdKCg0D5H3QYMsCt+SGBtNisSAA)

**Input:**
```jsx
function* mySagas() {
  yield effects.takeEvery(
    rexpress.actionTypes.REQUEST_START,
    function*({ id }) {
      console.log(id);
      yield rexpress.actions(store).writeHead(id, 400);
      yield rexpress.actions(store).end(id, 'pong');
      console.log('pong');
    }
  );
}
```

**Output:**
```jsx
function* mySagas() {
  yield effects.takeEvery(rexpress.actionTypes.REQUEST_START, function*({
    id
  }) {
    console.log(id);
    yield rexpress.actions(store).writeHead(id, 400);
    yield rexpress.actions(store).end(id, "pong");
    console.log("pong");
  });
}

```

I have two concerns here: (1) the opening yield keyword and the closing }); should be the only things at this tab column. The }) { on line four is really confusing and (2) hiding the opening function*({ at the end of the line is confusing (a symptom of (1), I guess).

**Expected behavior:**

Something like this:

```
function* mySagas() {
  yield effects.takeEvery(
    rexpress.actionTypes.REQUEST_START,
    function*({ id }) {
      console.log(id);
      yield rexpress.actions(store).writeHead(id, 400);
      yield rexpress.actions(store).end(id, "pong");
      console.log("pong");
    }
  );
}
```

(`rexpress` lines up with `function*` and is indented further.)

**Comment by lydell** [comment] 2017-12-02 15:14
This isn’t specific to `yield` and generator functions.

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAtgJ4DKAhgObkDOAFAJT7AA6U++ATnDOp+3FSo42GgDoY5ANZwAogDc4nYnTYcO3AB4AHbjXHlseKABVi2uOIBKsgIoBVWaRMB9ZwEErJgDRr1GLFxoOmB8HAATfABfJlZ2dQ5IKBoIABs4MVSISjoIhgBuPw4ovwK2KJBvEAhtIOTkUFoYZFRyVJo4KoAjTkMZGFJtQxwoSmQYTnROkHCIMBa2jqqRjs4YAAVeykJyBfbpgCsaTQAhXrB+ikI4ABkRuD2l6vQYbReAJkfpoc5V5BAuuQusQslBKiBdCMYAB1CIwAAWyAAHAAGKq6CAdaG9bTjSbTbgAR3QOG4myoOy+VQ6hBweKm1JGlHStnQEHgVJAki6sPCCOQ7yqE3IOFSTIAwhBCJSUFBoA8qugOiYgTQvlEokA)

**Input:**
```jsx
function mySagas() {
  return effects.takeEvery(
    rexpress.actionTypes.REQUEST_START,
    function({ id }) {
      console.log(id);
    }
  );
}
```

**Output:**
```jsx
function mySagas() {
  return effects.takeEvery(rexpress.actionTypes.REQUEST_START, function({
    id
  }) {
    console.log(id);
  });
}

```

I think that the thing here is that it feels unnatural to break inside the parameter list of the callback, rather than further up. #3014 might be the solution.

It feels as if we already have at least one issue open for this, but I can’t find it right now.

**Comment by mzedeler** [comment] 2017-12-03 14:50
I've renamed the issue, @lydell

**Comment by vjeux** [comment] 2018-03-27 21:29
I've been working on a pretty printer for a different programming language lately and I used a different algorithm in order to handle last argument expansion. It hasn't been battle tested and I'm still finding edge cases so I'm not sure if it's going to work for everything but it's promising so far.

----------------------------

I'm so excited, this has been a big issue in prettier and the solution was extremely complex, not performant, and didn't solve all the edge cases. Since I was very hesitant to reintroduce all that complexity, I tried to find another way and I found one!

The problem is the following, we want to inline a lambda if it's the last argument and all the arguments before fit in one line.

```js
call(a, b, x -> {

});

call(
  a,
  veryVeryLongB,
  x -> {

  },
)
```

The way prettier does it is to build multiple IR for all the cases and try them all out. It heavily relies on reference equality in order to skip repeated computation.

The key idea for this implementation is the following: when we try to print in a single line, we want to try and figure out if everything before the `{` fits in one line. If it does, then continue in one line, otherwise break.

```js
     vvvvvvvvvvvv
call(a, b, x -> {
```

The problem with this approach is how do you build that range. We're talking about partial results of three nested ast nodes, including the complicated List. The idea is to print it as is but to put a `Marker` at the position that we are interested in.

With that Marker in place, then we can tweak the `fits()` call to return true as soon as you see the marker. You don't want to go all the way through the end as it's going to look inside of the lambda implementation which --will-- break.

And that's it, it just works(tm)!

## Challenges

It requires a bit of machinery inside of the doc printer but the Skip printer changes are very minimal.

There are some small challenges with this approach:

- The way Indent() is setup is that it is used to print spaces when a newline is reached. We used to have an invariant saying that we would always break the outer one first, so the inner Indent would be no-ops because you wouldn't actually print a newline inside. But with this setup, we can actually have an Indent in a group that doesn't break but that's going to have newlines inside. So we remove those in the case where we know they will be in the way.

- We need to figure out a way to associate a Marker with its group.

But nothing insurmontable.

**Closed** 2020-11-14 11:17 UTC
Labels: area:function calls, lang:javascript
