### ISSUE TITLE
Destructured object parameter doesn't allow opt-in breaklines

### ISSUE THREAD

**Issue by pushkine** [prettier/prettier#10937] opened 2021-05-23 13:15 UTC
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAMwFcowYBLaPAZQFEAVAfQDEAZAQQHFqAKAHSh48AYQA2AQwDOkpHnFQAngBoBQ4HlVC8AVQBy1ds1qN2w4bWrU8AXjwxsROCsFa9u2ucvsASgE1G2gAKACLs9BY2dg5wmgC+zgCUeMCxIEogEBgU0JLIoOLY2BAA7oEFCLko4qLF4gq56QBG2OJgANZwMNQYreRQAObI9o7pcAC2jXAAJlPTrPL9ROL9cMw4Y+IwFAPIIOJEMBBpIAAWMGOiAOon5PCSPWBw1BW35AButwq7YNLHfZJwXCBFr9DbIAjVAHpABWkjQACEWu1OtRxGM4Kw+nBwZCnCBYWhqH1+qI4ABFIgQeA40RQkA9bAA7C7RriSaiY4YbB9GCXchTGAnZAADgADOkuRAAZcWhhdly4Ey3tj0gBHSnwYGZSp7SQAWigcGm02O2Dg6vIZuByzBSAhtLxALG5CG0XSkmJpIpVOxdtx6RgbL5AqFSAATAGWuRRMThBAxrbUJIAKzHIgA+hsyr2ulvRwASSgs1g1DA3Ky7CL1BgClJNIBsViQA)

```sh
--parser babel
```

**Input [= Expected] :**

```jsx
export function SET_FLAGS(
  Class: any,
  { 
    UNSAFE_ACCESS = true,
    UNNECESSARY_UPDATES = true
  },
) {}
```

**Output:**

```jsx
export function SET_FLAGS(
  Class: any,
  { UNSAFE_ACCESS = true, UNNECESSARY_UPDATES = true }
) {}

```

**Comment by thorn0** [comment] 2021-05-23 22:14
Duplicate of #2550

**Closed** 2021-05-23 22:15 UTC
Labels: type:duplicate
