### ISSUE TITLE
No way to add spaces

### ISSUE THREAD

**Issue by Nicitaa** [prettier/prettier#14983] opened 2023-06-26 08:54 UTC
**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
/* Products Page */
import GridView from "./GridView"
import ListView from "./ListView"

import ProductsHeader from "./ProductsHeader"

export { ProductsHeader, ListView, GridView }








/* Home Page */
import { Navbar } from "./Navbar"

export { Navbar }

```

**Output:**

```jsx
/* Products Page */
import GridView from "./GridView"
import ListView from "./ListView"

import ProductsHeader from "./ProductsHeader"

export { ProductsHeader, ListView, GridView }

/* Home Page */
import { Navbar } from "./Navbar"

export { Navbar }
```

**Expected behavior:**
With spaces looks better - no way to add spaces

**Comment by kachkaev** [comment] 2023-06-26 16:47
Please see https://prettier.io/docs/en/rationale.html#empty-lines. You can find [a few more related discussions](https://github.com/prettier/prettier/search?q=%22https%3A%2F%2Fprettier.io%2Fdocs%2Fen%2Frationale.html%23empty-lines%22&type=issues) via search.

Closing as duplicate of https://github.com/prettier/prettier/issues/13301

**Closed by kachkaev** 2023-06-26 16:47 UTC

**Comment by Nicitaa** [comment] 2023-06-27 09:27
As I worte - no way to add empty lines
Add this feature
