### ISSUE TITLE
Template string literals do not get a line-break when they are object values

### ISSUE THREAD

**Issue by cprecioso** [prettier/prettier#13822] opened 2022-11-08 22:45 UTC
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mwAOlJpgG5wBOAngDbQDmA1nHdfU1Gx14xbtOtQb2ECefEdyH9RU4QEYkmEiABGAQxpL1AGjIVJcmWOknx82VbOLr5iQtMAmVQANtNF+8NQAviD6IBAADjAAlujIoDo0EADuAAo6CGjIIFoMCVp06cEaNFpg7DAAyloAtnAAMhFQcMjYWWhwBUUlcOWhxfXMyDA0AK5tIHCVGnAAJlPTNVq8Q1rMcABiEDSVWjCRvBlaQzAQQSAAFjCVDADqpxHwaD1gcGVpdxGUd3QZYGj5IPWtGgwJJFZhbJotUYAKzQAA8yn0GHAAIpDCDwCEMVrBHo0QEZbSTBgnUI0eowK4RKYwU7IAAcAAYcfFWlciqEMqS4IDqCcAI5o+AgsLpFBaNAAWga02mJxocAFEXlIOW4KQzSxo1alQiA2GWsRKMFjXVkOCMC0Gkp1NpSBc5qKEQYfQAwhBKmqxmgAKwnIatAAqltFGuxIEoIwAklBZrAymAyeEAIIxsowRgm0Nwfz+IA)

```sh
--parser babel
```

**Input:**

```jsx
const foo = {
  verylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkey1: "bar1",
  verylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkey2: `bar2`,
}
```

**Output:**

```jsx
const foo = {
  verylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkey1:
    "bar1",
  verylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkey2: `bar2`,
};

```

**Expected behavior:**

```jsx
const foo = {
  verylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkey1:
    "bar1",
  verylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkeyverylongkey2:
    `bar2`,
};

```

**Comment by thorn0** [comment] 2022-11-10 15:54
Duplicate of #12408

**Closed** 2022-11-10 15:54 UTC
Labels: type:duplicate
