### ISSUE TITLE
Long import paths not respecting print width

### ISSUE THREAD

**Issue by symbyte** [prettier/prettier#2441] opened 2017-07-10 17:14 UTC
It seems single entity imports are not being broken to multiple lines when the name of what you are importing or the path to that thing cause the import statement to be longer than print width:

something like this:
```typescript
import { unbelieveablyLongFunctionName } from 'my/very/nested/path/that/is/really/really/long';
```
is being printed as above when it should probably be:
```typescript
import {
  unbelieveablyLongFunctionName
} from 'my/very/nested/path/that/is/really/really/long';

**Comment by bakkot** [comment] 2017-07-10 18:54
We get this right for [exports](https://prettier.io/playground/#%7B%22content%22%3A%22export%20%7B%20unbelieveablyLongFunctionName%20%7D%20from%20'my%2Fvery%2Fnested%2Fpath%2Fthat%2Fis%2Freally%2Freally%2Flong'%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)! Probably just an equivalent change needs to be made to `import`.

**Comment by josephfrazier** [comment] 2017-07-10 19:12
I think this is actually a duplicate of https://github.com/prettier/prettier/issues/1954, which was closed with the following [comment](https://github.com/prettier/prettier/issues/1954#issuecomment-306067705):

> This is actually intended. We have a special case for import and require with single elements where we keep them in a single line. You don't get much more information when they are in two lines and they look worse with a series of imports. This was done due to common request from people using prettier.

**Closed by josephfrazier** 2017-07-10 19:12 UTC
Labels: bug, easy, help wanted

**Comment by symbyte** [comment] 2017-07-10 19:16
Ah, ok. Sorry about the dup! That makes sense.

**Comment by josephfrazier** [comment] 2017-07-10 19:20
No problem! For future reference, here's are some related issues I dug up:

* https://github.com/prettier/prettier/issues/1833
* https://github.com/prettier/prettier/pull/841
* https://github.com/prettier/prettier/issues/752
* https://github.com/prettier/prettier/issues/2077
* https://github.com/prettier/prettier/pull/1729
* https://github.com/prettier/prettier/issues/2050#issuecomment-307159477
* https://github.com/prettier/prettier/issues/1110#issuecomment-294166812
