### ISSUE TITLE
"?." formatting breaks JS code

### ISSUE THREAD

**Issue by arthur-adriansens** [prettier/prettier#16506] opened 2024-07-25 17:35 UTC
**Environments:**

- Prettier Version: 3.3.3
- Running Prettier via: 
- Runtime: 
- Operating System: 
- Prettier plugins (if any): 

**Steps to reproduce:**

`const fullTitle = await textSelector?.evaluate((el) => el.textContent);`

**Expected behavior:**
`const fullTitle = await textSelector?.evaluate((el) => el.textContent);`
(stays the same)

**Actual behavior:**
`const fullTitle = await textSelector ? .evaluate((el) => el.textContent);`
This breaks the code!!! I've experienced this issue for 2 years already.

**Comment by kachkaev** [comment] 2024-07-25 17:51
Can you provide a Playground link please? I can’t reproduce this issue:

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzArgG3wBUBLGfOTAXkwEMB3WszeADxgGU4KwYIAnAPwA6OADda+XLXgAKWdwCU1AHyZuwtjADC0eLEUBuEABoQEAA4wS6ZKFr9+EegAUHCNMhCTGAT09mAEb8tGAA1nCctAC2cAAyJFBwyNiSaHBBIeGRHBahiQDmyDD8uBkg6dEkxaXlcKwWcPwksbCSRE1QDiRwnkip+OlmaIUUAIq4EPApaeUAVmisHKNwE1PJ-bNmAI6T8C5OFn3eaAC0SXAAJlemICVM+IW60dG0XpL4tyNQBRQAgjASiRArh9k0EkkZoNygALGDRfAAdRhZF6eTAcC4UBG1jEZF8XjAaACIDEZQAklBrrAOGBmlY-lSODBfBQoUMQBYnOlESELF4ub0mmJkmZEul+DADrQCq92eU8vwJV5ArRAtxblzEjBESRLjAYcgABwABjM-DguxIFulsrem2hZhgat1+sNSAATGZcOkiGq+gMOXBourLtdLnFaD9pAU4AAxASvQGFd6giAgAC+GaAA)

```sh
--parser babel
```

**Input:**

```jsx
const fullTitle = await textSelector?.evaluate((el) => el.textContent);
```

**Output:**

```jsx
const fullTitle = await textSelector?.evaluate((el) => el.textContent);

```

**Comment by arthur-adriansens** [comment] 2024-07-29 20:18
That's weird, I'm currently trying to reproduce it in the plagyround.

I'm using the vscode extension, and these are my "Prettier Options:"
```json
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": true,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 150,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 4,
  "trailingComma": "es5",
  "useTabs": false,
  "embeddedLanguageFormatting": "auto",
  "vueIndentScriptAndStyle": false,
  "filepath": "c:\\Users\\arthu\\Documents\\projects\\4. python\\Snapchat bot\\server\\index.js",
  "parser": "babel"
}
```
I hope this can help, maybe the problem is in vscode? Thank you so much for the help so far!!! I've been using Prettier for a very long time and I love it!

**Comment by kachkaev** [comment] 2024-07-29 23:40
Yeah the problem might be related to an outdated Prettier binary on your machine (`"filepath": "c:\\Users\\art...`) or some clash with other formatting software. You can try debugging Prettier in VS Code via the Output tab (in the bottom panel). It should give you some clues. You can also try searching for similar questions in a separate repo, specific to our VS Code extension: https://github.com/prettier/prettier-vscode/discussions

I’ll close this issue because it does not seem to be related to Prettier core. But if you find a bug that’s reproducible in the [Playground](https://prettier.io/playground/), feel free to open a new one!

**Closed by kachkaev** 2024-07-29 23:40 UTC

**Comment by arthur-adriansens** [comment] 2024-09-19 15:54
Hi! I found something new. Now, I'm getting an error when I try and format `.?`! Look at this:
```
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": true,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 200,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 4,
  "trailingComma": "es5",
  "useTabs": false,
  "embeddedLanguageFormatting": "auto",
  "vueIndentScriptAndStyle": false,
  "experimentalTernaries": false,
  "filepath": "/platform game + countdown/index.js",
  "parser": "babel"
}
["ERROR" - 5:51:03 PM] Error formatting document.
["ERROR" - 5:51:03 PM] Unexpected token (142:11)
  140 |     inFullScreen ? wrap.classList.add("small") : wrap.classList.remove("small");
  141 |
> 142 |     if (e.?type != "click") return;
      |           ^
  143 |     if (inFullScreen) {
  144 |         document.exitFullscreen();
  145 |     } else {
SyntaxError: Unexpected token (142:11)
  140 |     inFullScreen ? wrap.classList.add("small") : wrap.classList.remove("small");
  141 |
> 142 |     if (e.?type != "click") return;
      |           ^
  143 |     if (inFullScreen) {
  144 |         document.exitFullscreen();
  145 |     } else {
	at t.exports
	```
	
	I hope someone can help me! Thanks in advance!

**Comment by kachkaev** [comment] 2024-09-19 16:43
👋 @arthur-adriansens! This makes sense because is invalid syntax:

![Screenshot 2024-09-19 at 17 42 03](https://github.com/user-attachments/assets/61a93dc9-c770-4efd-8fdf-ebb7035ae5ad)

[AST Explorer](https://astexplorer.net/#/gist/e90f9d536883f4e230f1657f5a43ed22/7b78baa1db7cc63350da5a58579e7eb7644d30ca)
