### ISSUE TITLE
Styled Components prop-based styling incorrect line-breaks

### ISSUE THREAD

**Issue by vincentbollaert** [prettier/prettier#8956] opened 2020-08-11 05:24 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAVOHMC8mGAngDZwAmAdJQJYBuABgDpQsyRkQBOSmPKgG42omABJgAB0IA+TFOrx8AMhWZW7GBy69+AIzIBXOCK0d9AQzABrAOY8IRqJQC0uvgOFimAXzNMIAA0IBBSMHToyKCWPI4A7gAKsQhoyCCWZPGWJGkh+jzWNnAwAMpS1nRQdsgwPCYhABYwALZkAOqNdMoVYHClqd2M3STpdHZQvHDBIFVocDwwiYV2LZbIAGaZ8yEAVmgAHgBChbYlpZYtcAAyVdNIW2Q7IPsHpVV2FACKRhDwm9s4CEKjx5jx0lZ9HAyDMpDwqjB2nRKDBGsgABwABmBjnm7UKUnSmWyuRmAEdfvBlmE0ig4XgFgxpiFBBS6IJlpZVusHoCQvMWnRavUgSA0B9vpT7o9njBLPokSi0UgAEwhOqWOhkD4AYQgLTW6UmUGZICM82w8tpMtFDBMAEkXAgymB4eEAIIuUowcjSvkZDAAp6iygQMBB55OGBSIwwFUR0WFar9OWLZDYkBJuxwACiLmQAEYAMwAdl8viAA)
```sh
--html-whitespace-sensitivity ignore
--parser babel
--prose-wrap always
--quote-props preserve
--range-end 137
--range-start 0
--trailing-comma none
```

**Input:**
```jsx
const Test = styled.div`
	color: red;

	${p => p.test && `
		color: blue;
		background-color: red;
	`};
`
```

**Output:**
```jsx
const Test = styled.div`
  color: red;

  ${(p) =>
    p.test &&
    `
		color: blue;
		background-color: red;
	`};
`;

```

**Expected behavior:**
```jsx
const Test = styled.div`
	color: red;

	${(p) => p.test && `
		color: blue;
		background-color: red;
	`};
`;
```

**Comment by thorn0** [comment] 2020-08-23 22:23
Duplicate of #1872

**Closed by thorn0** 2020-08-23 22:23 UTC
Labels: area:multiparser, lang:css/scss/less, type:enhancement
