### ISSUE TITLE
Long named import clauses leak beyond width limit 

### ISSUE THREAD

**Issue by mohsen1** [prettier/prettier#3776] opened 2018-01-20 08:37 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCp8BDAZ3xgoDMcJ18ByGAT0zjLB1UxkYG4AOlGEZsefMHyQsqADZx8AX3y16TAHQB6GZnlwcA0VlwEpOOCTAwAUgGUAsiQDWcAAp1MZAIJQAJnYwJPAAkrAG1FZwACo4JFBk1LjoAGJWMLgsadaZyqp0DIzaMHEJSTjoZFoW6QC0AFZktegucLWYnk3xfrVkQfC1JfGJyUZQYqaS+DXWABIQqH0A4ggGqGBkscPlqemZ2Rk4LHlqhcWlIxVVMzC1ABYLfbUA5qvcG4MXO2MTEuaW1gASnB0BAAG7uTzRNgcbxkMioZ5QdAIGBbMrJA77PZHE4FTRaIYYq7VAG3CygiHtTyDGFdeGI5Goz7bUZCcYmP7TMkOcGQiCYaHsTYQADCcnImy+mJxWVlePURUJ0pJN2afOpAtpwsGEFqYAl8JZxPQP05ZmkEDkEq8cDC8BwZDg1lQ0HtESiUtZFSxR19xxUpwJRMulR0VptTtqqHCjudMFdUGjsciYA4xtDZvEFpuwMpcECwXWHgFQo4DhBACMDOjQ-7-QqzsrvWG1RSNX0i2BNZhtemUehqzgM992cI4AAPbOSYT4Ofc9K8iElwV06Jiw1ek312UAGln85u9icrhXPn8hdCKaitZ2O5yR33UHnC7mjxgKygaw2t5lD7l-5Pi+kDWiQtrunGLputeaZbnWsr+kBh5knmfIrmWPgMkiKKwL+PoIXuB5zrmIJ8pexZQnSFaDjWKq7P+iFEZasgKE+Shjl+U6TJACQECQ1p4ZU+AALz4AA2kxNxLvyq7Cuu4qSoJ96HCwSHEWSx6tGevgBP0dowTEdHKZkamvjA8yLB+bzrHBd4EYBTEgZG+kOk6UFQBBqYcEp9kqaZJH5uhdJwgi2Goj5DGEc+yHpKhELkWAQXCtRQ4RSpjFQAAuhxk7Tqw7D4Gl2L-iJ+AABT5XAop3M6rg4EglBkBoZbVbVBgAJQiQAfI1zV0QY-oADxUBodgQAArjgaYpPoXUcVohCELOxCAuNz7Auk+A2CQYIkHYXA8AQGSFTC+3cLwlB0aouCqPopAEAABtQ+huMEdwPct+AAAKYCQcQMM9CivTAdzLVo45cRI1Bre50xrWVgPuG9DV9NwUDPO1KMlDGzwztF6kwJNz66PoCMvW9u6kAJdFkO17JKMIIC7iAAoJtAZDIKAf10AA7q9FgJMgIA7QsfhM8LfTIJEchOszlZxGArgwHYv1gDjyAlONcDM34EBgFL-Gy2gCQGDAHgkM8LQGzL2sgI0E4AEIK0rdgkCiAAyMZwNbRsTTAmDjTAABMPu279cY4ELlYkJWLByNA4sdDGMAAOqoH4IPIAAjEHAAMzMdBATop3EmBCx0HAGBC4sWAAjuNqAWOblskKHzNOugqAazgWvtzjCgAIrjRA8BtyAQSVmnGd3MgAAszNDPIOOivQVsoFA0De8z41OtEMcc0g0tOkoShAA)
```sh
# Options :
--print-width=120
```

**Input:**
This file:
https://github.com/lyft/react-javascript-to-typescript-transform/blob/623cffeef1be6be1fed768078414b02d97254739/src/index.ts#L1

**Output:**
```jsx
import { reactJSMakePropsAndStateInterfaceTransformFactoryFactory } from "./transforms/react-js-make-props-and-state-transform";
import { reactHoistGenericsTransformFactoryFactory } from "./transforms/react-hoist-generics-transform";
import { reactRemovePropTypesAssignmentTransformFactoryFactory } from "./transforms/react-remove-prop-types-assignment-transform";
import { reactMovePropTypesToClassTransformFactoryFactory } from "./transforms/react-move-prop-types-to-class-transform";
import { collapseIntersectionInterfacesTransformFactoryFactory } from "./transforms/collapse-intersection-interfaces-transform";
import { reactRemoveStaticPropTypesMemberTransformFactoryFactory } from "./transforms/react-remove-static-prop-types-member-transform";

```

**Expected behavior:**
```ts
import {
    reactJSMakePropsAndStateInterfaceTransformFactoryFactory
} from "./transforms/react-js-make-props-and-state-transform";
```

**Comment by ikatyang** [comment] 2018-01-20 08:40
Hi, this is a duplicate of #1954.

> This is actually intended. We have a special case for import and require with single elements where we keep them in a single line. You don't get much more information when they are in two lines and they look worse with a series of imports. This was done due to common request from people using prettier.

**Closed by ikatyang** 2018-01-20 08:40 UTC
