### ISSUE TITLE
Inconsistent indentation on chained function calls

### ISSUE THREAD

**Issue by pstanton** [prettier/prettier#6094] opened 2019-04-30 23:23 UTC
If you chain multiple method calls, the indentation for the first chained function is always 0, but the indentation for all subsequent chained function is 1. This incorrectly suggests that the first chained function call is in some way different in terms of importance or context, when in clearly is not.

I would expect all chained function calls to be indented by 1, however it would also be an improvement to indent all by 0.

**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOjGgQwyjgBMAVAdwgAoAnOLAB2izgAIBeAPneAB0o7Ye3TYcpCAGUIAWzhioAcwDqaBHABucOjQCUAbkHCAvnuPs8hYmQDyJGgKEjIs2QSikk7fiABmEHTuMAC0sgCeIZCkcL4ANBbClOpQ3lAQlPoWZhZWRCQUaAxwNDp0gVy8TiKimLiUBFjw5BjyMgA2msRKAAoQxDDtjFgAklhYAK6M+kbOZrOCYrj4+XYO1S5y7p7evgFBBKERURAx8YnsyQhpGVlz5s55NhTU9IwsUGyVfBdLEtJyBSYZRqDTaXSGbIPYRPArkIpwEplCo8H7OYR-BpNOAtNoQTrdPoDIbjMaTaaQ+6zEBxEAQJgwDCsZCgAh0cqUHpshBYZAgAiafqkGkgABGdAIYAA1gopExJd1kDA6FNaWgYLJ2moMPBmJK4FIeTqMF0YOE+WBxiLiGw6DAehKlO5kH4CO02LSAFZYAAeACEJdLZQR5AAZGwut0ekDen1SbpDACKEwg8Ej7rgtPldFtfNFBFF4Xa0BFTDoAxUGFI6GQAA4AAxZ8psFQSph8suMHTaEUARxT8Ad9N5KEaIRIZDIIoY-YwDAdBCdBHT0bYsgwSpVmZAWATcGTqbgK+3MALleraGQACZacqiO1ugBhLbLlDpEgiiZscgFkeujO0o0MDHrSkhgCBdITDATBQVex4mCYQA)
```sh
--parser babylon
```

**Input:**
```jsx
this.chainedOne(arg => {
    this.doSomethingWhenever();
  })
  .chainedTwo({
    command: "format-my-code",
    when: now()
  })
  .chainedThree(arg => {
    this.wasteTimeSolvingPointlessIssues();
  });

this.chainedOne({
    command: "format-my-code",
    when: now()
  })
  .chainedTwo(arg => {
    this.doSomethingWhenever();
  })
  .chainedThree(arg => {
    this.wasteTimeSolvingPointlessIssues();
  });

```

**Output:**
```jsx
this.chainedTwo(response => {
  this.doSomethingWhenever();
})
  .chainedOne({
    command: "format-my-code",
    when: now()
  })
  .chainedThree(error => {
    this.wasteTimeSolvingPointlessIssues();
  });

this.chainedOne({
  command: "format-my-code",
  when: now()
})
  .chainedTwo(response => {
    this.doSomethingWhenever();
  })
  .chainedThree(error => {
    this.wasteTimeSolvingPointlessIssues();
  });

```

**Expected behavior:**
See input.

**Comment by lydell** [comment] 2019-05-01 07:15
Hi! I think this is essentially a duplicate of #5737, so I’m closing in favor of that one. Let me know if I missed anything!

**Comment by lydell** [comment] 2019-05-01 07:15
Duplicate of #5737

**Closed by lydell** 2019-05-01 07:15 UTC

**Comment by pstanton** [comment] 2019-05-01 07:26
@lydell yeah i think you're right - shame the outcome is not fantastic! seems like a pretty silly decision to me. oh well.
