### ISSUE TITLE
weird line breaking

### ISSUE THREAD

**Issue by pvinis** [prettier/prettier#13267] opened 2022-08-09 23:03 UTC
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTACgEp8A+TAJzgHM4APAB0IHpCAzAEzjTEoEsARnAA6IwgB9uvAcIB00ADYBPMZPb8YaifU3bNCqCv0w5aANb9Ga4i2Jz+UMIoCu3QjGWMefKzAAqPDAAYvyKPMQiUCAANCAQjDD86Mig2JSUEADuAArpCGjIINiKWdjKhXGClNhg5nAwAMrYALZwADKOcMjsJWhwVTV1DY2MtY40yDCULgMgcC3CnNyc7dhQNC7YdMEQlC3YMEkbRdguMBCxIAAWMC2KAOrXmjxjYHCNBZr8AG6aykUwGhKiBHP1KDAcjUaAcen05gArND0RoTcIARRcEHgcMU-TiY0o4KKgmwwkUV0YAlgD34nBg12QAEYAAwsgmZfoPGqMIpUnhwSg-bpxACOWPgUIShRQ2DQAFooHA4CsrtRxfxqFDtrCkL08XN+i1+Lj8SA0Gi4Jjsd09fC4jAybT6YykAAmB01MITADCEBauvmaAArFcXP1-GSZfqzT9ZgBJKDcWCNXyJACCScannCprgAF980A)

```sh
# Options (if any):
    "printWidth": 100,
    "semi": false,
    "singleQuote": false,
    "trailingComma": "es5",
    "bracketSpacing": true
```

**Input:**

```jsx
const a = () => regexp(/(fdescribe\(|describe.only\(|fit\(|xit\(|it.only\(|it.skip\()/).include(typescriptTestFiles)
```

**Output:**

```jsx
const a = () =>
  regexp(/(fdescribe\(|describe.only\(|fit\(|xit\(|it.only\(|it.skip\()/).include(
    typescriptTestFiles
  )
```

**Expected behavior:**

```jsx
const a = () =>
  regexp(/(fdescribe\(|describe.only\(|fit\(|xit\(|it.only\(|it.skip\()/)
    .include(typescriptTestFiles)
```

**Comment by thorn0** [comment] 2022-08-22 12:54
Duplicate of #5145

**Closed by thorn0** 2022-08-22 12:54 UTC
Labels: type:duplicate, lang:javascript, area:function calls
