### ISSUE TITLE
Formatting HTML template string introduces breaking changes 

### ISSUE THREAD

**Issue by saschanaz** [prettier/prettier#7100] opened 2019-12-05 12:37 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEALGBbANgAwAQAUAPAM4AOAhlAHwCWUJcATjHjKrSXuRWHACZ5KTBOziMuAIzgwA7nAR5ZEJvxJEA9DxoBKPDgDcIADQgIZGLWglkoCkyYRZABXsIbKCgDcItfiZBJJl4AaxkAZUowegBzZBgmAFc4U3RsAHUOeB4+cPdaSy8CgE9kcBIbU3pGFmdgmIwKZAAzCixGUwArEgAPACFgsDCYcIoMOAAZejgWto6Qbp7w2Kw4AEVEiHhZ9pSQYRqyyQppLACyJnoYdL92ZAAOAAZTC4hGdOCyMovxZi8Z0wAR028Dq5g8IAoJAAtFAFPwBAERMDaCI6hQGk0kK1dqZGBhaPEknsSCt1iCZti5nsYCcbvw7kgAEymBIUWhYWIAYQgGEaZSg0ABIESjAAKicPDj5l5kgBJKAI2DhMCXCwAQUV4RgxVWO0YAF8DUA)

**Input:**
```jsx
html` (<span>insert this spaced parentheses between words</span>) `;
```

**Output:**
```jsx
html`
  (<span>insert this spaced parentheses between words</span>)
`;
```

**Expected behavior:** It shouldn't insert newlines as template string engines including lit-html and hyperHTML do not ignore them. They look different when inserted into `<pre>` and they break tests that don't expect newlines.

**Comment by evilebottnawi** [comment] 2019-12-05 12:40
Duplicate of #7096

**Closed by evilebottnawi** 2019-12-05 12:40 UTC
