### ISSUE TITLE
TypeScript 3.8: ECMAScript Private Fields

### ISSUE THREAD

**Issue by nicholas-ochoa** [prettier/prettier#7271] opened 2020-01-11 16:30 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvABQgEtY9gAdKPPAYjSTygFcBbAEZxsAbmas2ATy69BwsVHEFopGNh5gYOABSdu-IdgA0eafrnYAlAyWsYACxqkAdBzwBePGgWs7jl1Iepj54AL7MSqRwMLoyBsImZrKG1kwsvg5OrmhB3rZ4mQGSQZIh4YrpAObR2qn52NE82CzAXlyF2Ynt-q7FoWURVdFetTbprA0wTSwdHAMVrNX4kqNpvniT0wU9UvPlIEYgEBgwNCrIoMTY2BAA7pRXCKTIIMQAbrQAJgcgAtjEYAA1tEAMoYAF0SrINQ8OCHewwPiEADqjngpHBYDgIKeNFObzxkheYHIPzoUVwlH+lT4xGQADNiIQoocAFakNAAIX+QNBxD4cAAMnQ4AymSyQOy0CDIYQ4ABFHgQeBi5lwkDg7AUl4wSQYOCkMDYGgnH4YY2wZE0T4OZAADgADIdzRAosj-hgXuaDcI3qLDgBHJXwKnHZ4oMgAWigcDgnzjPwaQZoDSpxBpdKQjLVhyifBo0PU6tIsoVwdFWfF6pgxAEVpt9mQACZDmpiDRCJCAMIQPi0l5QaD+kA8KIAFVr4ezEresIAklB47AQUaTTAAIKLkG6uWqqKhUJAA)
```sh
--parser typescript
```

**Input:**
```tsx
export class Point {
  #x: number;
  #y: number;

  constructor(x: number, y: number) {
    this.#x = x;
    this.#y = y;
  }

  set(x: number, y: number) {
    this.#x = x;
    this.#y = y;
  }

  get() {
    return { x: this.#x, y: this.#y };
  }

  get x() {
    return this.#x;
  }

  get y() {
    return this.#y;
  }
}

```

**Output:**
```tsx
SyntaxError: Invalid character. (2:3)
  1 | export class Point {
> 2 |   #x: number;
    |   ^
  3 |   #y: number;
  4 | 
  5 |   constructor(x: number, y: number) {
```

**Expected behavior:**
Should not throw a syntax error. This works with parser set to flow, just not typescript.

**Comment by armano2** [comment] 2020-01-11 17:21
this is not yet supported by typescript in stable channel (only in beta)
#7263

**Comment by thorn0** [comment] 2020-01-14 17:17
Duplicate of #7263

**Closed by thorn0** 2020-01-14 17:17 UTC
Labels: lang:typescript

**Comment by twistedpair** [comment] 2020-04-12 21:07
Is there a target release when private field support for Typescript will be moved GA from beta?
Thanks.
