### ISSUE TITLE
Special characters are escaped in some situations 

### ISSUE THREAD

**Issue by ShreyaThapa** [prettier/prettier#9357] opened 2020-10-08 21:44 UTC
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAZCEDWBnANAAhgAs58ATCAG0oEMAnfbASwHMp8nt85swaAHOGQ6w4dALZMY8WJQCeAOnwASAIwAGTUoA6UNZvX4VGzbpC4QEfjCbRsyUPToQA7gAV6CeyhqUXNOXsLACM6GjBMOBgAZX5wpigWZBg6AFc4CzhxYKEyIVQaRNSaFjgAMQgJGmkEpJ9UmAhzECIYcUoAdSIpHjiwOGivKSYANyk5ZHBsIJAE7DEYNzCWcRpkADNfeYsAK2wADwAhMIio6JpxOFQEuA2tjJA9-ejayjgARVSIeDvKbZA4nR5nRJqs6JgKC4oM1+HQEjAOkwyMRkAAOdQWWEQeYdML8SawnhiEa3CwARy+8CWVm8IBo2AAtFA4EIhM06HAKUwOUsSqtfv95pJkmkHsxEm9Pt9bkhNn8HjAaMFEciiMgAEwWFI0JiUWoAYQg4n5KB4AFZmql5gAVJXeOX-EbpACSUDysGiYDh1gAgm7ojA5G8BXAAL6hoA)
```sh
--parser markdown
```

**Input:**
```markdown
Look, the dollar sign is escaped sometimes. $1000. 
$2000  $3000

```

**Output:**
```markdown
Look, the dollar sign is escaped sometimes. $1000. 
$2000 \$3000

```

**Expected behavior:**
Look, the dollar sign is escaped sometimes. $1000. 
$2000  $3000

**Comment by thorn0** [comment] 2020-10-09 15:43
Duplicate of #6213

**Closed by thorn0** 2020-10-09 15:43 UTC
Labels: lang:markdown, type:bug
