### ISSUE TITLE
single and multi-line JSX in ternary expressions

### ISSUE THREAD

**Issue by leebenmorris** [prettier/prettier#5616] opened 2018-12-09 18:30 UTC
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOAHCBnABAHSnxgH5cAKQ3AmYgHgBMBLANwD5DiuY6AlTHAHFUTBrnRZsAXmAScAX1wB6DlGrr1dJc3ZV1ASk4wkFPRuqNWqjdzoALAIxsAMhACGzKAHNcMO3FwMNy8AqAgAdwAaQIAbODdsAPC3JhhcN1xsOwhUNPC7JjitR2saem0rM1x9AG4QSJAIDBgmaGxkUDdUVAiABS6EdpQ3FghRepAAI1Q3MABrOBgAZSCwJm9kGFQAVzgGuxgAWxiAdQL4bFW4JcHU1lSAT2RwbHaG9cTc3pmvQ7dkABmbhiiQaACtsAAPABCM3miyWbkOcGc6zggOBoJAEMhS3WXjiAEVthB4BiQXsQEFUJ9npM3JMHjFoBMMCJYCdRH5kAAOAAMDTZODgJxmGGebLgnxY6Ia6AAjtsmOhvsE-uSsYlDkxNjtKdh8USSWSkECKQ0YAzOQxuUgACwWmaFfEAYQgh3VKDCUFlIG2iQAKgyhmbEvJ5EA)
```sh
--parser babylon
--tab-width 4
```

**Input:**
```jsx
repos 
	? (
  		<div>
			<ReposGrid repos={repos} />
        </div>
    )
	: (
        <div>
    		<h1>Loading the page now, please wait a short while</h1>
  		</div>
    );
```

**Output:**
```jsx
repos ? (
    <div>
        <ReposGrid repos={repos} />
    </div>
) : (
    <div>
        <h1>Loading the page now, please wait a short while</h1>
    </div>
);

```

**Input:**
```jsx
repos 
	? <ReposGrid repos={repos} />
	: <h1>Loading the page now, please wait a short while</h1>;
```

**Output:**
```jsx
repos ? (
    <ReposGrid repos={repos} />
) : (
    <h1>Loading the page now, please wait a short while</h1>
);
```

**Expected behavior:**
Output should look like input. The way these jsx ternary expressions are reformatted is (to my eye) ugly and hard to read.

**Comment by lydell** [comment] 2018-12-10 06:40
Hi! The "extra" parens were requested in #2208 and added in #2398 (and has since then received a couple of tweaks as well). There's also this similar issue: #3001

The formatting for this has already been decided, and is not going to change at this point. I also thought it looked weird at first, but quickly got used to it. These days I even prefer it!

**Comment by lydell** [comment] 2018-12-10 06:40
Duplicate of #3001

**Closed by lydell** 2018-12-10 06:40 UTC
