### ISSUE TITLE
[SCSS] Multiple files in one @import are all stripped out except the last

### ISSUE THREAD

**Issue by rekateka** [prettier/prettier#2242] opened 2017-06-24 02:03 UTC
Input:
```css
@import "_zoomOut",
  "_zoomOutDown",
  "_zoomOutLeft",
  "_zoomOutRight",
  "_zoomOutUp";
```

or

```css
@import "_zoomOut", "_zoomOutDown", "_zoomOutLeft", "_zoomOutRight", "_zoomOutUp";
```

Output:
```css
@import "_zoomOutUp";
```

As per http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import you should be able to import multiple files in one `@import`, though. Perhaps the intended output should then be:

```css
@import "_zoomOut";
@import "_zoomOutDown";
@import "_zoomOutLeft";
@import "_zoomOutRight";
@import "_zoomOutUp";
```

---
https://prettier.github.io/prettier/#%7B%22content%22%3A%22%40import%20%5C%22_zoomOut%5C%22%2C%5Cn%20%20%5C%22_zoomOutDown%5C%22%2C%5Cn%20%20%5C%22_zoomOutLeft%5C%22%2C%5Cn%20%20%5C%22_zoomOutRight%5C%22%2C%5Cn%20%20%5C%22_zoomOutUp%5C%22%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by azz** [comment] 2017-06-24 02:23
Thanks for the report.

This is a duplicate of #2125, which has been fixed, and will be in the next release!

**Closed by azz** 2017-06-24 02:23 UTC

**Comment by rekateka** [comment] 2017-06-24 02:38
Apologies, @azz - I didn't check the closed issues. Good to hear it's been taken care of. Thanks!
