### ISSUE TITLE
Config option for keeping brackets around single parameter arrow functions

### ISSUE THREAD

**Issue by ismail-syed** [prettier/prettier#1725] opened 2017-05-25 03:49 UTC
Currently prettier strips out brackets around single parameter arrow functions. 

```
[0, 1, 2].forEach((num) => console.log(num));
``` 
outputs to 
```
[0, 1, 2].forEach(num => console.log(num));
``` 

Some teams prefer the consistency of having the brackets always surrounding the parameters. Can this be a config option? With some guidance, I'd be interested in contributing this project by adding support for this config option.

**Comment by lydell** [comment] 2017-05-25 09:09
Hi, thanks for your issue! :)

This is a duplicate of #812, so I’m going to close this one. I’ve renamed #812 so that it is easier to find while searching.

**Closed by lydell** 2017-05-25 09:09 UTC
