### ISSUE TITLE
Flow parser on Node v6 causes Segmentation Fault

### ISSUE THREAD

**Issue by flarnie** [prettier/prettier#3457] opened 2017-12-11 17:29 UTC
Hi! This is an issue showing up in Draft.js CI runs.

We enabled Prettier as part of our Travis CI runs on Github recently - in https://github.com/facebook/draft-js/commit/cd20b992d4b054d70f756c258e5e75e518995e12

During CI we currently install the most recent compatible version of any dependency automatically, and so we started pulling in v1.9.0 and then v1.9.1 when those were released 6 days ago.

At that time we started seeing CI failing due to a segmentation fault when it runs the `eslint` check, which is the step that runs `prettier`.

I verified that disabling prettier or downgrading to v1.8.* does not lead to the segmentation fault - see https://github.com/facebook/draft-js/pull/1567

I have not dug into the Prettier codebase so I'm not sure what could be happening to cause a segmentation fault, but I'm happy to provide any info or help that I can. We'd like to keep using Prettier in Draft.js, and get the goodies in new releases.

Thanks for creating such a powerful and useful tool! 📐✨💕

**Comment by duailibe** [comment] 2017-12-11 17:52
Hi @flarnie! Thanks for the report! I have cloned the draft-js repo to try and reproduce this.

Is it happening on master? It runs find for me:

```
in draft-js/ on master 
› eslint --version
v4.13.0

in draft-js/ on master 
› prettier --version
1.9.1

in draft-js/ on master 
› eslint .

/Users/duailibe/Code/draft-js/src/model/transaction/__tests__/moveBlockInContentState-test.js
  102:11  warning  'data' is assigned a value but never used. Allowed unused vars must match /^_/           no-unused-vars
  103:11  warning  'characterList' is assigned a value but never used. Allowed unused vars must match /^_/  no-unused-vars
  104:11  warning  'depth' is assigned a value but never used. Allowed unused vars must match /^_/          no-unused-vars
  105:11  warning  'type' is assigned a value but never used. Allowed unused vars must match /^_/           no-unused-vars
  106:11  warning  'text' is assigned a value but never used. Allowed unused vars must match /^_/           no-unused-vars

✖ 5 problems (0 errors, 5 warnings)
```

I tried running both `npm install` and `yarn install` (after cleaning `node_modules/`) and got the same results. But I noticed you managed to run locally: https://github.com/facebook/draft-js/issues/1562#issuecomment-350770530

Do you have any other hints or info so that I can reproduce?

**Comment by duailibe** [comment] 2017-12-11 18:17
Oh I can reproduce it with node 6.12.2

**Comment by duailibe** [comment] 2017-12-11 19:37
What I've managed to figure out so far is that if I change to the babylon parser it works correctly. If I downgrade the flow-parser version back to 0.51.1, I get no errors.

So it looks like this is related to the 0.51.1 -> 0.59.0. Unfortunately, upgrading flow to 0.61.0 (latest) doesn't fix the issue.

I'm not sure what we should do here..

**Comment by duailibe** [comment] 2017-12-11 19:43
@flarnie In the meantime, you can change the config to use `babylon` instead. I just ran it in the draft-js codebase and got no diffs :-)

**Comment by azz** [comment] 2017-12-11 23:02
Nice sleuth work @duailibe. We should be able to bisect flow-parser from there.

**Comment by mitermayer** [comment] 2017-12-14 20:54
Could we bump the priority of this issue ?

**Comment by duailibe** [comment] 2017-12-14 21:10
@mitermayer I don't mind labeling as high priority, but that doesn't mean anyone will want to work on this...

I haven't tried, but I believe it's kinda hard to bisect (for each flow commit, build the parser, link to prettier, link to draft-js codebase, run `eslint`) and it's not guaranteed find something actionable in the end.

**Comment by mitermayer** [comment] 2017-12-14 21:14
I completely understand, this is a high priority for using prettier inside Facebook as we use the flow parser. I will see if I can find sometime to look into it 

cc @vjeux, @flarnie

**Comment by vjeux** [comment] 2017-12-14 21:18
cc @mroch. It is an issue with the flow parser generated to JavaScript.

**Comment by duailibe** [comment] 2017-12-15 01:17
Hey guys, I had some free time today after work and was able to quickly bisect this.. If I didn't do anything wrong, this was the commit that made the generated JS segfault: https://github.com/facebook/flow/commit/7141f7b977f7605caa3edd65846062ea1ab2e585

I even prettified its output and its parent commit to try and diff anything but didn't anything useful yet. Hope it helps!

**Comment by duailibe** [comment] 2017-12-15 01:24
FYI running `prettier -l "src/**/*.js"` with the parser generated with this commit also segfaults.. so it's not just the ESLint integration

**Comment by duailibe** [comment] 2017-12-15 01:47
Here's the two generated files btw: https://gist.github.com/duailibe/b2523c2a98c7bd17783f7f78fc7ed85e/revisions

**Comment by mitermayer** [comment] 2017-12-15 07:33
@duailibe thank you very much for looking into this, @mroch do you have any clues on why this could be happening ?

**Comment by mitermayer** [comment] 2017-12-15 21:59
We unblocked draft-js by bumping our builds to use nove v8 instead of v6. This does not seem to afftect node v8

**Comment by grabbou** [comment] 2017-12-18 09:38
We are also experiencing that failure in React Native, https://circleci.com/gh/facebook/react-native/28712

**Comment by azz** [comment] 2017-12-18 11:17
Here's the diff of the built `flow_parser.js` file from the commit @duailibe bisected and it's parent commit (ran through prettier first). 

https://gist.github.com/azz/beeb0e613aa07aaf67279ce28ada0e19

Unfortunately a lot of symbols changed so the diff isn't particularly easy to read.

**Comment by vjeux** [comment] 2017-12-18 16:29
@azz: what helps in those cases is to replace all the symbol names by `_` and do a diff again. It'll help narrow it down.

**Comment by duailibe** [comment] 2018-05-24 18:59
Uh oh looks like our own tests are crashing now 😢

**Comment by duailibe** [comment] 2018-06-06 18:06
I ran flow tests with the `--detectLeaks` Jest flag and it looks like there's a memory leak in the Flow parser. If I skip using the Flow parser at all, everything passes, otherwise, Jest raises an error:

```
 FAIL  tests/flow/union-intersection/jsfmt.spec.js
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.      at node_modules/jest-cli/build/test_scheduler.js:264:22
```

I can't figure out where the problem is yet... I don't know if it's related to a specific Flow syntax or not

**Comment by thorn0** [comment] 2020-05-25 07:57
Closing as Node 6 isn't supported anymore.

**Closed by thorn0** 2020-05-25 07:57 UTC
Labels: help wanted, scope:dependency
