### ISSUE TITLE
Misplaced comments on array destructuring

### ISSUE THREAD

**Issue by scinos** [prettier/prettier#9535] opened 2020-10-29 10:28 UTC
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtTB6AKkwDMBXAG3MwFsBDGMAC0wLwBp8iEA3ASwCdo1BFlYdGtNMwC6mALw16TANwg2ICAAcYvdMlC1+ggO4AFQwjTIQtcsdoBPK+oBG-WmADWcGAGVNHrxQAObIMPykcOpw1C5wACbxCQAytCGktMFwAGIQ-HQwOiHWtKQwEGogjDDU5ADqjLzwaAFgcL6WTbx8MA7WYGjOIEFocPwwpu7BdMjEtqPqAFZoAB4AQu5ePr60wslBcLPzUSDLK75BweRwAIqkEPBH5AsgAfyj-NYutHHklZr8IIwOq8eIwRjIAAcAAZ1ACIKM6u5NNYAXAPtxDuoAI73eCTLRWFCSAC0UDgCQSlX4cFxAjgk0yMyQc2eJ1G1F4YQi7Mu1zuD0OLOO6hgPxBYIhSAATKL3LxyJcAMIQajMkDogCslVIowAKj8iayXtxIgBJKBJWC+MCA7QAQUtvl61yeowAvu6gA)
```sh
--parser babel
```

**Input:**
```jsx
const [ /* full match */, /* environment */, hash ] = match;
```

**Output:**
```jsx
const [, , /* full match */ /* environment */ hash] = match;

```

**Expected behavior:**
```jsx
const [/* full match */, /* environment */, hash] = match;

```

**Comment by thorn0** [comment] 2020-10-29 12:22
Duplicate of #1013

**Closed by thorn0** 2020-10-29 12:22 UTC
