### ISSUE TITLE
[printWidth] improper format

### ISSUE THREAD

**Issue by slvganesh** [prettier/prettier#8218] opened 2020-05-04 11:04 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACActAtAMwFcowYBLaDAZxgEN4BbBGDOADzDjgBMqMGIAJzgYYAC1pQMADgAMGMBMG1ScQVQA6JaDQwAHBNzJQA5gEkoRsPSF8AvNTFk4AG24A6Wi9qCGAcQQ1G0EAYWh8MhNCZXJodxM4GAAFQ2MTADU1KgooMJdCBih0r0I4KgBuLS10DAAxYlIc6jpGZlYOLl5+IRFxSRl5RR8VeHUtSChdA0s0iytg+wwtDEdnN09vXwCoIJghMKgIqJic+MSUmdNM9Ry8gqKSsoAKAEpKqBAAGhAIPVjJ5CgHyCCAAdySPgQVGQIC8oNoAE9od8AEbKMAAa0SAGU9Co0sgYIJSt8xDAGC4AOpOeBUPGcbFQsjkABuzIRMLAVGRIGMVDUyWUJgYtGQ+C8-O+ACsqGwAELorEwbG0JgAGWMcDFErg0tl2LSLjgAEVCBB4NqXJKQHj1GoYTAEQYqGBBGQ-l8bSD+ZTlHoYXphPzBCytd8AI5m+BJEF6aEoWhUXA7Hg8T3CSNkYQx2jC0VIcVW3UgfkMMiE4nF7KmI2m81apBEkkgOgoylkbjiZAAJm+RNoZBcaTCDBFMKg0DDIEI-IAKrQUfHC9aWaU5sxsa73TAAIKWbGOo2W62B4wwdudsTIOQAXxvQA)
```sh
--parser typescript
--single-quote
--trailing-comma none
```

**Input:**
```tsx
// Non-function statement exceeds more than 80 characters
const pendingIndicators = shield.alarmGeneratorConfiguration.getPendingVersionColumnValues;

// Function statement exceeds more than 80 characters
const pendingIndicators = 
  shield.alarmGeneratorConfiguration.getPendingVersionColumnValues();

```

**Output:**
```tsx
// Non-function statement exceeds more than 80 characters
const pendingIndicators =
  shield.alarmGeneratorConfiguration.getPendingVersionColumnValues;

// Function statement exceeds more than 80 characters
const pendingIndicators = shield.alarmGeneratorConfiguration.getPendingVersionColumnValues();

```

**Expected behavior:**

```
// Second statement shall be formatted as below
const pendingIndicators = 
  shield.alarmGeneratorConfiguration.getPendingVersionColumnValues();

```
Prettier version: 2.0.5

**Comment by thorn0** [comment] 2020-05-04 11:08
Duplicate of #2482

**Closed by thorn0** 2020-05-04 11:08 UTC
