### ISSUE TITLE
CSS attribute selector '//' affects bracket spacing

### ISSUE THREAD

**Issue by remcohaszing** [prettier/prettier#12937] opened 2022-05-28 12:34 UTC
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgEpwIYA2AlgM4xFiZwAeeAtgA4FybqoA6UeA2gBYBOcAGYA9ALzsQvGDAYkkqDiAC6mYAF9OnDJgDqEfgGsSmSP0FgYBAJ6sOXPoNESpMuUkmqNWqDoCyRFBEdISYggz8EAAmAK6WRNB2nDwARi6KnmqaUCAANCAQDOTQJMigeOYQAO4AChUIpSiEVXjWpfkp-HhghnAwAMr0cAAygXDIQoQkcB1dPX39DN2BAObIMPwxMyBwdClwUVEHw3hQKzF4K3AAYgYhMqvIIHgxMBB5rnQEurxE8CRLMBwfoNP5EABuf2sTzAJHaIEC034MBqXRWIQmU22ACsSNR+qtmABFGIQeCYgjTfJLfhImFwj4RQIwXREKIwXjIAAcAAZqZFprougwnhE4EjweN8gBHUnwVGFRrPEgAWigcAOBw+gllREEqMuGKQk0p22mdCI602ZsJcBJZPGxqx+RgeBSrPZnKQACYXV0iMQzgBhCB0I07EgAVg+MWmABU3Y0TVSQOCtgBJKBHWD9MD8IhFACCWf6MGszAp03U6iAA)

```sh
--parser css
```

**Input:**

```css
/* Realistic example */
a[href^="https://"] {}

/* Works correctly */
a[href^="https:"] {}

/* Minimal reproduction */
a[b="//"] {}
```

**Output:**

```css
/* Realistic example */
a[href^="https://"]
{
}

/* Works correctly */
a[href^="https:"] {
}

/* Minimal reproduction */
a[b="//"]
{
}
```

**Expected behavior:**

The value of an attribute value selector doesn’t affect spacing of CSS brackets

```css
/* Realistic example */
a[href^="https://"] {}

/* Works correctly */
a[href^="https:"] {}

/* Minimal reproduction */
a[b="//"] {}
```

**Comment by fisker** [comment] 2022-05-28 13:18
Duplicate of #11604

**Closed** 2022-05-28 13:19 UTC
