### ISSUE TITLE
Unwanted line wrapping in nested functions

### ISSUE THREAD

**Issue by robertoschuster** [prettier/prettier#16415] opened 2024-06-19 17:18 UTC
**Prettier 3.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEALAhlAEwBs4BlAVwFtMBeTctOAYVyKICNcwBrACl4BurcnACUtAHyZgAHSiZMAJzgxyi+bkoRysTAGpMQoiIDccgL4AaTAG1N22AF1RJkJZAQADjACW6ZKC4iooQAO4ACkEIaMggrKG4AJ4x7uyKXNwqpJpwADI+UHDIAGasjKnpPFmeXAUA5sgwiiLujJQ+jc1w7nAAHp5wij6UCDCsACqDUEE+cDFIpUTlIGj1JACK5BDwJWXdIABWaL2ka3Cb20ULe+4Ajlvw4SGe83FoALSFcATfbiBNuB8RHqTAglEouFirCIf1WUDqJAAgjAmj52ORHoN8oVdkt9tgYJQiAB1bA+eBoGpgMjRck+ATkxKxMBoFIgAQiACShFGpDAQ28iMIpBgiRIuOWnhCjGJ6U8sSlc0GAiK7gKjEUMCeuDqEIl+xqig1sU47DgMPcUoKMGJPgIMGwyAAHAAGdzKe4+ZTa3WQ6549xjdi2+2OpAAJncDDg41w7Hmi2WcEoZoIPwIuXwdXIOrgADEIIoISj6lCMRAQOZzEA)

```sh
--parser babel
```

**Input:**

```jsx
const handleSum = useCallback((value) => {
  return amount + value;
}, [amount]);
```

**Output:**

```jsx
const handleSum = useCallback(
  (value) => {
    return amount + value;
  },
  [amount],
);

```

**Expected output:**

```jsx
const handleSum = useCallback((value) => {
  return amount + value;
}, [amount]);
```

**Why?**

The input code is much more readable. There is no need for line breaks in this case.
PS: The line breaking only occurs when there are one or more arguments in the useCallback dependency array.

**Comment by kachkaev** [comment] 2024-06-19 17:54
👋 @robertoschuster! I believe this issue is a duplicate of https://github.com/prettier/prettier/issues/11881. Let’s continue the discussion there if you agree.

**Closed by kachkaev** 2024-06-19 17:54 UTC
