### ISSUE TITLE
prettier removes curly spacing inside jsx

### ISSUE THREAD

**Issue by AuroPick** [prettier/prettier#12249] opened 2022-02-06 16:58 UTC
**Input:**

```jsx
<View>
  { something && (
       <View>
          <Text>
              bdfbfdbndbd
          </Text>
       </View>
  ) }
</View>
```

**Output:**

```jsx
<View>
  {something && (
       <View>
          <Text>
              bdfbfdbndbd
          </Text>
       </View>
  )}
</View>
```

**Expected behavior:**

It should not remove curly spaces

prettier config

```json
{
  "requirePragma": false,
  "arrowParens": "always",
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "quoteProps": "as-needed",
  "singleQuote": true,
  "semi": false,
  "printWidth": 100,
  "useTabs": false,
  "tabWidth": 2,
  "trailingComma": "none",
  "endOfLine": "lf",
  "insertPragma": false
}
```

eslint config

```json
{
  "env": {
    "es2021": true,
    "node": true,
    "react-native/react-native": true
  },
  "extends": [
    "plugin:react/recommended",
    "plugin:import/recommended",
    "airbnb",
    "airbnb/hooks",
    "prettier"
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "plugins": ["react", "react-native", "jsx-a11y"],
  "rules": {
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],

    "no-use-before-define": ["error", { "variables": false }],

    "react/prop-types": "off",

    "react/jsx-props-no-spreading": "off",

    "global-require": "off",

    "semi": ["error", "never"],

    "import/prefer-default-export": "off",

    "consistent-return": "off",

    "no-underscore-dangle": ["error", { "allow": ["_id"] }],

    "object-curly-newline": "off",

    "react/jsx-curly-newline": "error",

    "object-curly-spacing": ["error", "always"],

    "react/jsx-curly-spacing": [
      "error",
      { "when": "never", "children": { "when": "always" }, "allowMultiline": true }
    ],

    "linebreak-style": ["error", "unix"],

    "quotes": ["error", "single", { "avoidEscape": true, "allowTemplateLiterals": true }],

    "jsx-quotes": ["error", "prefer-double"],

    "comma-dangle": ["error", "never"],

    "react/jsx-indent-props": ["error", 2],

    "no-shadow": "off"
  }
}

```

if I disable prettier it works normally

https://user-images.githubusercontent.com/53499802/152691855-2efb36ec-301f-477f-818e-d96f8c0c2102.mp4

**Comment by kachkaev** [comment] 2022-02-06 19:42
Removing spaces within `{ ... }` is expected behavior. You can find an example of this [in the Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAagSzgdwHwA6UABMcMQM4QC2cMAFplAObEBkbxAFEaX6Rmz5e-UagAqcAB4xCJUQtIAjACYAzJWpVKo2lSMXFUAekky5ik1lwXiASmIBfIlaF4QAGhAQADjEzQFMigAIYATmEQOAAK4QhBKCEANjghAJ5BXkphIWAA1nQAyiG0ADJMcMhqyRRwWTn5RT65TMzIMGEArnUgcNRKcCoqg6UhLJ0hzHAAYhBh1CEw-izIICGdMBCeIPQw1EkA6ozwFM1gcIXxmP4Abtdpq2AUmSBMtWEw0TnMC1U1PQArChSQqtJJwACKnQg8D+SVqXmaYXeqyUIQGSW2PjCTBgB0wKgYyAAHAAGRGRWoHHI+VbYuDvG6VLwAR2h8C+vgSawoAFooHBBoNtmE4GzMKKvpNfkhqvCerVqJh2l0FWDIezKrL-l4YOj8YT6MgAEy6nKYJKtADCNBlvQoAFZtp1auJ0Qk5QiQDdugBJXQIGCFMA4vwAQV0hRgaXBcNqjkcQA).

Prettier is an _opinionated_ code formatter, so [it won’t be possible](https://prettier.io/docs/en/option-philosophy.html) to add a config option that would keep spaces. If you use other tools like ESLint and some rules are conflicting, feel free to add [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier) – it will disable all conflicting rules and thus resolve the problem for you.

I am going to close this issue because we have an expected behaviour here. However, feel free to add your thoughts in the comments! 🙂

**Closed by kachkaev** 2022-02-06 19:42 UTC
