### ISSUE TITLE
Prettier does not format long imports with aliases

### ISSUE THREAD

**Issue by budarin** [prettier/prettier#15465] opened 2023-09-27 09:57 UTC
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHzBzgEN4AxVAG3hwDkyA3VAcwtWmrrh3zIBnYqQpwe9Jqwl98AX3wAzHBHT4A5ABNVZVFAD0UFu07da9fSXJVzfKSZhcoMnADoYg9QG4QAGhAQmI7QgsigZDgqAO4AChEIoShkNFFkAJ6h-gBGOGRgANZwMADKZOhwADJ6cMiKyYJw2bkFRcWYeXpsyDA4AK6NIA3oqN19A4KdNHAAir0Q8LX1AwBWggAexZMzcwtIdTQN-gCOO3AxKpiJIEIAtFBwcJqPfiA9ujSdAMKq6GTI1zQaC8JlA2FMAIIwHqoLK9eAxPhVe6LA4DAAWMHQNAA6mjUPBBO0wHBigl8ahWDA0v8wIJMiBmP0AJJQJ6wYokVBBcGs4pUqYow4gTAqBrY3KYf4iuANHDMGr+PSymDnMhsX6CgbtHCy-5ZMhZOBA-wivQwbGoTQwNHIAAcAAZ-KQTqhSKr1X89kt-DADRarTakAAmfy9BoAFQNiX2Qrg6ENmiemgqZFBvTV4lwvyhnX+ZDhEBAcjkQA)

```sh
--parser babel
```

**Input:**

```jsx
import { createFilterNavigationFilter as createFilterNaviFilter } from 'domain/navigationFilter/createFilterNavigationFilter.ts';
```

**Output:**

```jsx
import { createFilterNavigationFilter as createFilterNaviFilter } from "domain/navigationFilter/createFilterNavigationFilter.ts";

```

**Expected behavior:**

```jsx
import { 
  createFilterNavigationFilter as createFilterNaviFilter 
} from "domain/navigationFilter/createFilterNavigationFilter.ts";

```

**Comment by auvred** [comment] 2023-09-27 11:23
Hi, this is most likely a duplicate of https://github.com/prettier/prettier/issues/1954

**Comment by budarin** [comment] 2023-09-27 11:27
Should I close the issue in favor of [1954](https://github.com/prettier/prettier/issues/1954)?

**Comment by sosukesuzuki** [comment] 2023-09-27 13:52
Thank you for reporting this. Sorry I think we should close this issue as duplicated.

**Closed by sosukesuzuki** 2023-09-27 13:52 UTC
