### ISSUE TITLE
[Option/Question] JSX curly brackets on their own line

### ISSUE THREAD

**Issue by rart** [prettier/prettier#7954] opened 2020-04-05 06:57 UTC
With full understanding of [Prettier's philosophy](https://prettier.io/docs/en/option-philosophy.html), I still wanted to ask regarding this possible option. Apparently, [I'm not alone](https://stackoverflow.com/questions/50728330/vscode-new-line-after-curly-brace-for-jsx) in wishing for it.

1. Would there be interest in an option to have JSX curly brackets on their own line for complex statements? (see example below as illustration)
2. Even if there's no interest in the option, I'd like to go through the exercise of adding it in my fork; I'd appreciate any guidance or pointers to where/how this would be done.

Thanks.

**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAQgE4CGYA1nDAM4AUAlPsADpT76RQ0z47wBbGvgC8+ANoBdANxsOxaumLs6cjvgA8APjXrmuvX0E0AdANIAHOvzgDRWzQBMcANy3AbAgL4aA9M7cGAw4vAz8ddnwGWSgvEAAaEAgLXGgaZFBSYmIIAHcABSyEdJRSABtc0gBPdMSAIzJKagBlC3IcKABzZBhidDhEgAsYATKAdUGbGjawOGbi-ld+KuRwGlqQDpo4Yhh8sk7zZFRy7cSAKxoADxJyKhhm0gE4ABkOuGPTgZBLq+aOzplOAARXQEHgnzKZxAbWI22IqzqpDqcDKCRhxA6MDGOEcMEGyAAHAAGRIWHLbMZkCyrclweEuD6JACOYPg+2SJRApBoAFooHA4I4heiFKycAp9qRDqRIdDtgIcD0+t8aACgaDwR8kCcod8YMicXiCUgAEyJXqkHBlAEAYQgAiOKHpAFZ0ehtgAVZElXXQlz9ACSUGFsGaYExKQAgiHmjAqkC5XAvF4gA)

**Input:**
```jsx
<>
  {
    items.map(item => <div>{item}</div>)
  }
</>
```

**Output:**
```jsx
<>
  {items.map((item) => (
    <div>{item}</div>
  ))}
</>
```

**Desired:**
```jsx
<>
  {
    items.map((item) => (
      <div>{item}</div>
    ))
  }
</>
```

Does anyone know the history of this JSX formatting (i.e. the "output")? Haven't seen a code style convention where block's body goes inline with the curly (e.g. if/else, loops, functions, etc). Interesting it is popular in JSX.

**Comment by thorn0** [comment] 2020-06-11 15:49
Duplicate of #3686

**Closed by thorn0** 2020-06-11 15:49 UTC
Labels: type:question
