### ISSUE TITLE
Formatter breaks JSdoc function overload syntax

### ISSUE THREAD

**Issue by thw0rted** [prettier/prettier#8473] opened 2020-06-01 10:05 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBJAJgWQIZWwczgCcA6AByIhioE8y4TCYACAXmYDMBXKMGAS2jMAFP3QBKZsAA6UAL4BuWbID0AKjWzma5gFEAHmQhEYAZ2a49sfjBoBhCABtHcPoKgXz2ZgGlMAGWZ0CDAuAFsEFmNfTAAtCyIwAAt+ADcGLR0AAVTsIn5sASEARhj4ojgYLiIoTOYssjzsMKkAeQAjACtXGDlmCDIiqHMAQQ8ILp7mAHcbJOYYJLhOJ0cIWah8ZgoB4gE4UyQ6hqaW4BgiLjg+gaHTEgBrMIAvZlQOBcu4ABoYwNx0Mw4Pp4DVsI5OPwXOZZs5mO1lpAwhQDqY4ID+LAIBZmKZMfgXGVIS4SJljhUqjVzMAAAqUML8NEAHmBRhMPjCjgASgcuI4YBzngA+Pojbb0xnLRaFZgVUxOdLmag4vzxDhQ5bYLzMABCa3apI8ahU6k0RvquXyhXczAATH9ZZVqrVzSciM02pM+DdBu5RuMvSxZosFksVs51vjxbsTPwDkdXY13WcOOC0X0ANq3P2PF6sVOONEAXTeHwLaP6RGYPDRMF+FOdSrDfkC6sJAMdHGICDA6Md8uqvfMmPQaTEXHBjhoZNdDapUjpEAZzNZxgFnJ5pj568cIuYYp2y6lSRlcoVfeVlgm3T4zEgsGwmKji2WLdxFyjHe8o7c0DyNH6D5gVBPAITbZY9QmUxMhULRuF4IYgUMNcOUcYRs2gUxJBkeRlCgEBvhADDhmQUA8koaYaTyBBTGQEBwWmbAaFowj2ndMAHkqABlRowHxZALiuQikhgTkAHUUngUxeLgLiaJsMdbDosBTBYkBMTREw6QIMJsGQcsfhATpTH0HV2M4mAuOaOB-ExOB9LTQzjP0Lj8RcABFLgqHspADMIpNNLo9psARRwCJAChMRgMSxEWZAAA4AAZ-MoNExPdMg6JRTT0nCgBHLz4EXMhaJQLUAFooDgdF0XCioCv4CptPwXSHMLQy0QZASvkIvFNg8wqfL8kAYBCmL0DipBbUIi5H0cfEHDCVqUAOABWcKuDRAAVELSuG1IrlQKB0EiLiwHyQYxnQLjbBcNr0zkIA)

**Input:**

```js
IdManager.prototype.get = function (id) {
};

/**
 * Exports an EntityCollection as a KML document or KMZ archive.
 * @variation 1 KMZ return
 * @param {Object} options An object with the following properties:
 * @param {true} options.kmz If true, KML and external files will be compressed into a single KMZ file.
 *
 * @returns {Promise<exportKmlResultKmz>} A promise that resolves to a KMZ file as a Blob.
 *//**
 * @variation 2 KML return
 * @param {Object} options An object with the following properties:
 * @param {false} [options.kmz=false] If false or unset, returns the KML file and referenced resources individually
 *
 * @returns {Promise<exportKmlResultKml>} A promise that resolved to an object containing the KML string and a dictionary of external file Blobs
 */
 function exportKml(options) {
}
```

**Output:**

```jsx
IdManager.prototype.get = function (id) {};
/**
 * @variation 2 KML return
 * @param {Object} options An object with the following properties:
 * @param {false} [options.kmz=false] If false or unset, returns the KML file and referenced resources individually
 *
 * @returns {Promise<exportKmlResultKml>} A promise that resolved to an object containing the KML string and a dictionary of external file Blobs
 */

/**
 * Exports an EntityCollection as a KML document or KMZ archive.
 * @variation 1 KMZ return
 * @param {Object} options An object with the following properties:
 * @param {true} options.kmz If true, KML and external files will be compressed into a single KMZ file.
 *
 * @returns {Promise<exportKmlResultKmz>} A promise that resolves to a KMZ file as a Blob.
 */ function exportKml(options) {}
```

**Expected behavior:**
When using the `@variation` tag to describe an overloaded function, [the two comment blocks must "nestle"](https://github.com/jsdoc/jsdoc/issues/1017) such that you wind up with the string `*//**` between them.  Prettier should treat the entire joined-up series of comments as a single block and never reorder or separate the component comments.

Weirdly, if I remove the line of code before the comments (`IdManager.prototype.get` etc) then the emit order is correct (variation 1, then variation 2) but a space is inserted into the "nestling", which creates `*/ /**`, and this also breaks JSDoc overloading.

As an aside, I tried adding `// prettier-ignore-start` before the blocks and `//prettier-ignore-end` after, and the behavior didn't change.  Is that pairing not supported in JS, or does it not work on comments?  The docs are unclear on this.  If I'm right that it's supposed to work, and it doesn't, I can open a separate issue.

**Comment by thorn0** [comment] 2020-06-01 10:15
Duplicate of #7724

**Closed by thorn0** 2020-06-01 10:15 UTC

**Comment by thorn0** [comment] 2020-06-01 10:19
`prettier-ignore-start` is supported only in Markdown.

**Comment by thw0rted** [comment] 2020-06-01 10:58
Oops, sorry -- I looked for "jsdoc variation" but forgot to check "overload". Thanks!
