### ISSUE TITLE
Prettier adding extra spaces when executed

### ISSUE THREAD

**Issue by vajahath** [prettier/prettier#4744] opened 2018-06-25 06:44 UTC
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQFcDOcOAvNsAL4DcAOlOvgJ5RjYBmuzMAltNvlwFsADgBs4AMSgAKAJTBa1GASIA6fELhgu6EVxgMA6noAWAYXQwdEAOa442YgpiL1m7bv0BJACb4VYqGsYY2wAPmwABidFRQB+bHQAd3Q9bGs4GABlDS0dPQYAQShvAFl0IXNLERs7KWjnBtdcjwYffAAaepiYIUwIb1wwGAAldEC4Tqhu7uqRWYgRSemYGWwAejXsAB4AWh3sYKJ7LnwE7AAmPiF0MHtvLlZWI+Z7KQAVY3sITC5rLjoRNhIN5jqdLAAjHb-EGwODeGRdGBIbAAbQAujQoOQQO0QBAhNxoPhkKAsH1EgAFLAIYkodCoCBcbw4kDgzA3ADWGWyN3+1mQMEwdlx-0ImBgFPZ1gE6GQrB0hFxACt8AAPABC7LAXKy6AEcAAMv84HKFRMQNdMGLkKz0OCGNUoCzev8YEZvMFkAAOCK43oQQgGdlCG29OBi1Am3GYOAAR1wXBjkvQ0tlSHlIkVIEIAi4AqF5v4gTEAEVcBB4KbM+aIe7PUhzrjBSldIFTBABDKbVBoFGQMo3nbaRnCORyEA)
```sh
--parser babylon
```

**Input:**
```jsx
var user = {};
async function simpleFn(){
	user.specialityWithCatalogue =
		specialityIds.length > 0
			? await getSpecialityAndMapCatalogue(
				specialityIds,
				productRange,
				lollolol,
			) // <-- there is a 2 space difference (The original code is tab-indented)
			: [];
}
```

**Output:**
```jsx
var user = {};
async function simpleFn() {
  user.specialityWithCatalogue =
    specialityIds.length > 0
      ? await getSpecialityAndMapCatalogue(
          specialityIds,
          productRange,
          lollolol
        ) // <-- there is a 2 space difference (The original code is tab-indented)
      : [];
}

```

**Expected behavior:**
Do we really need those extra spaces. Tslint generates an error regarding this.
Expected:
```jsx
var user = {};
async function simpleFn() {
  user.specialityWithCatalogue =
    specialityIds.length > 0
      ? await getSpecialityAndMapCatalogue(
          specialityIds,
          productRange,
          lollolol
      ) // <-- the extra 2 space removed
      : [];
}

```
How it looks like:
![image](https://user-images.githubusercontent.com/12165822/41834210-070041b6-7871-11e8-8a59-4430d200821e.png)
(left is original and right is prettified)

**Comment by ikatyang** [comment] 2018-06-25 06:58
Duplicate of #1271, see https://github.com/prettier/prettier/issues/1271#issuecomment-294163500.

We recommend you to disable all possible conflict TSLint rules using [`tslint-config-prettier`](https://github.com/alexjoverm/tslint-config-prettier).

**Comment by ikatyang** [comment] 2018-06-25 06:58
Duplicate of #1271

**Closed by ikatyang** 2018-06-25 06:58 UTC
