### ISSUE TITLE
watch task

### ISSUE THREAD

**Issue by thejameskyle** [prettier/prettier#575] opened 2017-02-02 18:02 UTC
It would nice to be able to use this as just:

```sh
yarn add --dev prettier
yarn prettier -- --write src/**/*.js --watch/-w
```

And only update the files that are changed as they are changed.

**Comment by vjeux** [comment] 2017-02-02 18:03
I wish there was a unix utility for that instead of each project having to reimplement it in a crappy way :(

**Comment by xtuc** [comment] 2017-02-02 18:07
@vjeux there is actually unix `inotify` but you will still need some sort of Node binding.

**Comment by vjeux** [comment] 2017-02-02 18:11
@xtuc I was more thinking about

```js
watch src/**/*.js | xargs prettier -- --write
```

**Comment by thejameskyle** [comment] 2017-02-02 18:13
I am using https://github.com/mikeal/watch to do effectively that:

```
watch 'prettier --write src/**/*.js' src
```

The problem is that it will just spawn up a new prettier process and go through every single file again

**Comment by xtuc** [comment] 2017-02-02 18:16
Yeah that would be awesome.

**Comment by lydell** [comment] 2017-02-02 18:21
There's also [cli-watch](https://www.npmjs.com/package/cli-watch) and [chokidar-cli](https://www.npmjs.com/package/chokidar-cli). Example:

```
chokidar 'src/**/*.js' -c "test '{event}' = 'change' && prettier --write '{path}'"
```

**Comment by jlongster** [comment] 2017-02-02 18:51
Do you have your editor instantly show changes from the filesystem? If not, how would save a file a file twice, since the second time there will have been changes to the file and you'll overwrite them? (My editor warns me about this and asks to confirm)

**Comment by thejameskyle** [comment] 2017-02-02 19:17
My editor automatically shows changes. It's fast enough that it doesn't cause me any issues for now. If the watch task only rebuilds the file I'm working on it should stay that way

**Comment by jlongster** [comment] 2017-02-02 21:08
Interesting, that's the opposite workflow from usual, where we have editor plugins that will automatically reformat on save. The editor invokes prettier before saving, formats it, and then it's saved.

My experience with watchers has always been painful trying to get them working across operating systems. Is there any reason you don't want to have the editor invoke prettier, @thejameskyle ? Which editor are you using?

**Comment by thejameskyle** [comment] 2017-02-02 21:35
Because I want it to run out of the box for everyone working on the project

**Comment by xtuc** [comment] 2017-02-02 21:36
With Vim, i'm not notified that the file has changed unless I try to save. If I really save I will just override my version with the formated one.

Prettify before save is actually a better solution in my case.

I know many other editors will just load the new version of the file you're currently on.

**Comment by jlongster** [comment] 2017-02-03 21:35
@thejameskyle fwiw, many of the editor integrations also invoke the script from scratch. I think atom is the only one that doesn't because it's written in JS and already supports JS APIs first-class.

A more generic solution might be to introduce a "server" mode that just spawns it in the background and anything can run the CLI as many times as it wants. This would benefit all editors as well as your watch mode. Not sure how much more complex that would be, or if there's already a node module to help with that though.

**Comment by thejameskyle** [comment] 2017-02-03 21:44
You might find this useful: http://langserver.org/

**Comment by Baransu** [comment] 2017-02-14 12:25
If you want quick unix tool without implementing it into package I recomend [entr](http://entrproject.org).

**Comment by olpeh** [comment] 2017-03-10 07:19
FYI: It tried using prettier together with npm-watch but it wrote the files as empty.

Tried using https://github.com/mikeal/watch instead as @thejameskyle suggested and it seems to work.

This is good enough at least for me.

**Comment by vjeux** [comment] 2017-03-10 15:38
@olpeh: could you create a test plan that reproduces the issue? This way we can look into it.

**Comment by olpeh** [comment] 2017-03-10 15:43
@vjeux Sure. Should I create a new issue of that or add it here? 
Is there a template I should follow?

**Comment by vjeux** [comment] 2017-03-10 16:07
A new issue would be great. No template, just make sure there's enough information so that we can investigate :)

**Comment by vjeux** [comment] 2017-05-21 20:54
I'm doing a spring cleaning of the issues and we're unlikely going to implement it, so closing. If someone is interested in building this, there is no opposition.

**Closed by vjeux** 2017-05-21 20:54 UTC
Labels: feature

**Comment by eedrah** [comment] 2017-10-31 05:43
@vjeux - I thought perhaps it might be nice to put in the README how to use this with an [external] watcher - that way it hopefully will please everyone wanting a watcher, without having requests to reimplement this functionality in the code of Prettier.

For those who are coming here from Google wanting this functionality, the short version is:
```
npx onchange '**/*.js' -- npx prettier --write {{changed}}
```
