### ISSUE TITLE
Template string with simple substitution is not wrapped to next line

### ISSUE THREAD

**Issue by hawkrives** [prettier/prettier#3661] opened 2018-01-06 00:40 UTC
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBXATgG0wF5MADACxhgAc0kB6e6gQ2rlzGxgDoMJ9mAM25wAJtiQBOAIySATPVzUw9VgEtFcDPTWx2UZvnoBbCACM1+dnCvM0cVdQ2H8AWmq5d8XGgD82e1wDYzgiABJgAPYAX1IAHSgEyCgMHAJiTABySho6RhY2Di5eGH4hEXEpWQUlFXVNbS99QxNzS2tbe0dnfDcPJp9-QODQiKjcaMyEkAAaEAhqGDV0ZFBmXFwIAHcABXWENGQQZgA3CDVRWeOMZEFDezmzXGYwAGs4GABlFjBdAHNkDBcNg4HNRBAwLd7qCQLpAjAds8-sZmFD8A8QAArNAADwAQs83h9PswQgAZXRwNEYiBcahcOTUmEsHzsI5mZhmACe+GgV36sAA6hcYORkAAOAAMcw8EHsgue1COHi07BOVLmuDgAEdsGotYjmMjUUg7uiYfZjGpAcCLf8rABFbAQeBMuYwTnC0Si5Byd3PSz-ADCEGMKKOUGgGpAUQAKpzDqbodFokA)

**Input:**
```jsx
const url = `https://papercut.stolaf.edu:9192/rpc/api/rest/internal/mobilerelease/api/all-printers?username=${user}`

const url = 'https://papercut.stolaf.edu:9192/rpc/api/rest/internal/mobilerelease/api/all-printers?username=${user}'
```

**Output:**
```jsx
const url = `https://papercut.stolaf.edu:9192/rpc/api/rest/internal/mobilerelease/api/all-printers?username=${user}`;

const url =
  "https://papercut.stolaf.edu:9192/rpc/api/rest/internal/mobilerelease/api/all-printers?username=${user}";
```

**Expected behavior:**
```jsx
const url = 
  `https://papercut.stolaf.edu:9192/rpc/api/rest/internal/mobilerelease/api/all-printers?username=${user}`;

const url =
  "https://papercut.stolaf.edu:9192/rpc/api/rest/internal/mobilerelease/api/all-printers?username=${user}";
```

I'd expect both cases to wrap the "string" to the next line, as the plain string does.

**Comment by duailibe** [comment] 2018-01-06 00:45
Thanks for the report! FYI this isn't specific to an expression inside a template:

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBXATgG0wF5MADACxhgAc0kB6e6gQ2rlzGxgDoMJ9mAM25wAJtiQBOAIySATPVzUw9VgEtFcDPTWx2UZvnoBbCACM1+dnCvM0cVdQ2H8AWmq5d8XGgD82e1wDYzgiAPZSAB0oaMgoDBwCYkwAckoaOkYWNg4uXhh+IRFxKVkFJRV1TW0vfUMTc0trW3tHZ3w3D1qff0Dg0PDcFOiQABoQCGoYNXRkUGZcXAgAdwAFBYQ0ZBBmADcINVExnYxkQUN7cbNcZjAAazgYAGUWMF0Ac2QYXGw4cdEIGAzhc-iBdIEYKsbu9jMxgfhLiAAFZoAAeACEbvdHk9mCEADK6ODwxEQLjULhyEmglg+djbMzMMwAT3w0GOXVgAHVDjByMgABwABnGHgg9i5N2o2w8WnYu2J41wcAAjtg1MqocwYXCkOcEaD7MY1F8foaPlYAIrYCDwanjGBMnmiPnIOQOm6WD4AYQgxlh2yg0EVIHCABUmVs9SCAL4xoA)

**Input:**
```jsx
const url = `https://papercut.stolaf.edu:9192/rpc/api/rest/internal/mobilerelease/api/all-printers?username=user`

const url = 'https://papercut.stolaf.edu:9192/rpc/api/rest/internal/mobilerelease/api/all-printers?username=user'

```

**Output:**
```jsx
const url = `https://papercut.stolaf.edu:9192/rpc/api/rest/internal/mobilerelease/api/all-printers?username=user`;

const url =
  "https://papercut.stolaf.edu:9192/rpc/api/rest/internal/mobilerelease/api/all-printers?username=user";

```

Closing this as a duplicate of #2889

**Closed by duailibe** 2018-01-06 00:45 UTC

**Comment by hawkrives** [comment] 2018-01-06 01:08
Thanks!
