### ISSUE TITLE
Suggestion: retain blank lines between line comments

### ISSUE THREAD

**Issue by branpk** [prettier/prettier#10447] opened 2021-02-28 18:55 UTC
Currently, prettier removes blank lines between line comments within a function (though not at the top level outside of a function). Unfortunately this doesn't interact well with VS Code and certain other IDEs, which skip blank lines when you comment out a chunk of code.

For example, in VS Code with the following code:

```jsx
function foo() {
  let x = 3;

  return x;
}
```

If you highlight the body of `foo` and use Toggle Line Comment, it produces the example below. After formatting and uncommenting, all blank lines have been removed from the code.

Fortunately VS Code has the option `"editor.comments.ignoreEmptyLines": false`, but this is not enabled by default.

My proposal is that prettier should treat line comments similarly to code blocks, allowing at most one line break between them.

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT7AA6UA9LfowDZwz4Ae+AvPgMwDcNRjXqN8AJ1bpxUDoKgBfEABoQEAA65oAZ2SgAhuPEQA7gAVDCXSn1MT+gJ67VAI3H6wAa1YBldR5woAHNkGHF0OFU4AFsXOAATeISAGX1g9H0guAAxCHFo-RhcYOQQfXQYCBUQAAsYaKYAdRqceG1-MDgfK1acADdWh1KwbWcQQO04cRgzdyCC5FRbSdUAK212ACF3L199aLhkwLhF5ciQdfYfQKCWAEV0CHhTphWQf3FJ8VKXfTimarqcSBGCNHDxGA1ZAADgADKogRBJo13OpSkC4F8+idVABHR7wWYaaxlbQAWigcASCWqknxOEks0yCyQS1e50m0RwoXCHJu9wJJ1ZZ1UMD+YIhUKQACZRe4cEwbgBhCDRFkgTEAVmq6EmABU-tY2W8+hEAJJQJKwHxgYGaACClp8MAcLBekwUCiAA)

**Input:**

```jsx
function foo() {
//   let x = 3;
  
//   return x;
}
```

**Output:**

```jsx
function foo() {
  //   let x = 3;
  //   return x;
}
```

**Expected behavior:**

```jsx
function foo() {
//   let x = 3;
  
//   return x;
}
```

**Comment by thorn0** [comment] 2021-02-28 18:59
This is already supported in genera, but not in situations where the entire content of a block is commented.

**Comment by thorn0** [comment] 2021-02-28 19:01
Duplicate of #8234

**Closed** 2021-02-28 19:01 UTC
Labels: area:comments, lang:javascript, type:duplicate
