### ISSUE TITLE
Is it possible to specifty files in .prettierrc instead of command line?

### ISSUE THREAD

**Issue by nico-onmap** [prettier/prettier#4820] opened 2018-07-09 12:57 UTC
**Environments:**
- Prettier Version: 1.13.7
- Running Prettier via: CLI
- Runtime: Node.js v9.2.1
- Operating System: Linux

**Steps to reproduce:**

Create a `.prettierrc` with files in exceptions, like:

```json
{
    "overrides": [
        {
            "tabWidth": 4,
            "semi": true,
            "singleQuote": true,
            "bracketSpacing": true,
            "files": ["npm_scripts/test.js","npm_scripts/test2.js"]
        }
    ]
}
```

Run prettier with `prettier --config .prettierrc`.

**Expected behavior:**
Prettier should check the files `npm_scripts/test.js`, `npm_scripts/test2.js`.

**Actual behavior:**
Prettier shows command line usage since no files have been specified in the command line.

How can I specify the files I want to run prettier on in .prettierrc instead of the command line?

I know I can use globs, but I want to only run prettier on specific files that cannot be configured using a glob.

**Comment by ikatyang** [comment] 2018-07-09 13:20
Looks like a duplicate of #2691, as a temporary workaround you could use [`requirePragma`](https://prettier.io/docs/en/options.html#require-pragma) to achieve it:

```sh
prettier "**/*.js" --write 
```

```json
{
    "requirePragma": true,
    "overrides": [
        {
            "files": ["npm_scripts/test.js", "npm_scripts/test2.js"],
      		"options": {
                "requirePragma": false,
                "tabWidth": 4,
                "semi": true,
                "singleQuote": true,
                "bracketSpacing": true
            }
        }
    ]
}
```

**Comment by ikatyang** [comment] 2018-07-09 13:21
Duplicate of #2691

**Closed by ikatyang** 2018-07-09 13:20 UTC
