### ISSUE TITLE
Markdown: Preserve double-space line break syntax 

### ISSUE THREAD

**Issue by damianobarbati** [prettier/prettier#10464] opened 2021-03-05 09:25 UTC
I'm reopening this https://github.com/prettier/prettier/issues/3319 because I think it's imporant for openapi inline comments.

A snippet like this:
```js
/**
 * @openapi
 * tags:
 *   - name: Auth
 *     description: |
 *       Issue and revoke JWT tokens used for authentication.  <two spaces here>
 *       Yeah!
 */
const myfunc () => {};
```

With the following prettierrc:
```json
{
    "printWidth": 160,
    "semi": true,
    "singleQuote": true
}
```

Causes prettier to trim out the `<two spaces here>` which are in markdown a return line (and so the return line in the resulting automatically generated documentation).

My current workaround is using the `  <br/>` where I should just use `  `.

Is there any plan to support this?

**Comment by thorn0** [comment] 2021-03-05 10:14
Duplicate of #6793

**Closed** 2021-03-05 10:14 UTC
Labels: type:duplicate
