### ISSUE TITLE
Unexpected closing tag "p" with vue parser, but only in very weird and specific cases

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [prettier/prettier#14946] opened 2023-06-17 19:17 UTC
only happens *sometimes*. and only if the last tag is `<p>`, and only if the `<p>` has other tags inside it.

**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlKgM5xgwCW0JUABI6loXuQCYBmqA9G1KlmI0WOasG46WNQALAMzsu3Dj36KpM6f0FNtEvpWp0oW-plwE4hEABoQELLWjlkoPACdPEAO4AFLwQ3FDwcXzwATzcHACNPPDAAazgYAGU8DDgAGRooOGRVHEo4hOTUtKxEvIBzZBhPAFc4BzgMWLhOTk7svCgaxrwauAAxCE8MAlp+5BA8RpgIexA5GAwcAHU5GnhyKrA4NOCdmgA3HcjZsHIYkDzKTxh-BJrJwrCSkAArcgAPNNqODgAEVGhB4O9ii0QFVPA9ZqdmsssJ48jANjRODA5MgABwABgcKIglA2CSwsxRcAepwKDgAjmD4M8nCE5uQALT5TqdZaeOCMmj855DN5IIqfSgYGj1JrQ8iAuAAQRgDRosQWcH8cE8uXykMlitB4IK4o+0JgeFiGKxOKQACYHA08DQcLUAMIQDBikDUgCsy0alAAKlaQhLoYi4ABJKDdWBpMCo5xKuNpGCRIEGuAAXxzQA)

```sh
--parser vue
```

**Input:**

```vue
<template>
<section>
  <p>asdf</p>

                <p>
                  <h3>asdfasdf</h3>
                </p>
            </section>
  </template>
```

**Output:**

```vue
SyntaxError: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (7:17)
  5 |                 <p>
  6 |                   <h3>asdfasdf</h3>
> 7 |                 </p>
    |                 ^^^^
  8 |             </section>
  9 |   </template>
```

**Expected behavior:**
formatting happens

**Comment by fisker** [comment] 2023-06-18 01:59
Duplicate of #11907

**Closed** 2023-06-18 01:59 UTC
Labels: type:duplicate
