### ISSUE TITLE
The return statement has double parentheses if having jsdoc head

### ISSUE THREAD

**Issue by debuggy** [prettier/prettier#6487] opened 2019-09-16 13:14 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABL9XAARgE8AHOXYCAIwCs4wYBfHfdVHAMwFcpmAS2i4AEnAA2EiAHUIAJwkATABTAA5vLhwYgqOtwBeXFhAALSdNMAaXJu3wlR3AHJTcxUtMvbAZ0ESCDDO3ACGEr5wttAAshC8kQDyAG5w8tYsAJTUOOy4gtwqAIT2OnrqmcBaMLzyeFC8UiwA3Ll4+PioqLgAKokAIolIuP3QLsEJVPKhUEoQALb5eFqzaXmBwQ2LxjGhMGYAdNzSCrgqu-sH07MLKtmEAIwAogDUAOyZBzAQAMow8uU7lc4OQJKEwHAVFwsAcsFglC9UIJ1LZTKZMm18NVangVHl8AAeJSCZK4MBg3y+AByoXmcEMLnEUlkCmULlwuhggUMwAABgBNeK4UJaXDJQT+b7yXBbWhpXAAEmAMt4ixYvJYuFi8SSqXkPO1kxSaRYAD5MR0Cb5-tB1KblaVdPoDr4JIIISpcAAGWwPXCfb4AVXIlHkAGFQpE7rgXnYtGVna73ZCHgGIAAZCAAdzSEaj2RYBNQ1vktvN7XwGnjTvUBwQSl8MkE+zxIGs6NwAH4TCAe7hhlbyDNcNbSNzgMBINJ5MM3Fh7KQXCwzTYe0XfEOoKbcGwK7gCXB5uWsDAHdW4E5dyei4fyx1qGd-IFYBi9-hu6ZYSB8R1hqYiqYV57kWxLJHe-qtFAOAsG2IAQOQujQL4yCgCKpZZgACiKCDISgoTJBAghKLBtDTGAADWOg-EOYDlMg-y8FE5gwPMEgyGYzZwBu4JwD8OHNiSzakMg4CUrBeiRPIMAYdM6jzKEyBhBETH0L4AAeABCZGUTAPy0nA6Z6HAinhJE1ggKpak-OUgQAIq8BA8Amcp5lDvIkkibQoS0GO0CweQAKwE2Sj7MgAAcPogAFECRDI0zkCJAVcWkqSwQAjg58AyfBuEgJGAC0UDaEoF6wVoGWCFoMmhHJClIEpZkgJE8yCPR8iMeZ-j6HZmXGfVplMTA3nBaFSAAEzmf8oQBOUYYLPJIlQNAxnmZMPTebhDVwMuQA)

**Input:**
```jsx
/**
  * @type {object}
  */
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  if(!greeting){return null};

     // TODO: Don't use random in render
  let num = Math.floor (Math.random() * 1E+7).toString().replace(/\.\d+/ig, "")

  return (
    <div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}>

    <strong>{ greeting.slice( 0, 1 ).toUpperCase() + greeting.slice(1).toLowerCase() }</strong>
    {greeting.endsWith(",") ? " " : <span style={{color: '\grey'}}>", "</span> }
    <em>
	{ greeted }
	</em>
    { (silent)
      ? "."
      : "!"}

    </div>
  );

}
```

**Output:**
```jsx
/**
 * @type {object}
 */
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return ((
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  ));
}

```

**Expected behavior:**
The output has double parentheses behind ```return``` statement, which is abnormal. And it supposed to not change the original single parenthesis.

**Comment by evilebottnawi** [comment] 2019-09-16 13:16
Thanks!

**Comment by pranshuchittora** [comment] 2019-09-18 05:21
@debuggy can you help me with the file extension `js | jsx | tsx`

**Comment by debuggy** [comment] 2019-09-18 11:53
> 
> 
> @debuggy can you help me with the file extension `js | jsx | tsx`

The issue occurs in (jsx)[https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABL9XAARgE8AHOXYCAIwCs4wYBfHfdVHAMwFcpmAS2i4AEnAA2EiAHUIAJwkATABTAA5vLhwYgqOtwBeXFhAALSdNMAaXJu3wlR3AHJTcxUtMvbAZ0ESCDDO3ACGEr5wttAAshC8kQDyAG5w8tYsAJTUOOy4gtwqAIT2OnrqmcBaMLzyeFC8UiwA3Ll4+PioqLgAKokAIolIuP3QLsEJVPKhUEoQALb5eFqzaXmBwQ2LxjGhMGYAdNzSCrgqu-sH07MLKtmEAIwAogDUAOyZBzAQAMow8uU7lc4OQJKEwHAVFwsAcsFglC9UIJ1LZTKZMm18NVangVHl8AAeJSCZK4MBg3y+AByoXmcEMLnEUlkCmULlwuhggUMwAABgBNeK4UJaXDJQT+b7yXBbWhpXAAEmAMt4ixYvJYuFi8SSqXkPO1kxSaRYAD5MR0Cb5-tB1KblaVdPoDr4JIIISpcAAGWwPXCfb4AVXIlHkAGFQpE7rgXnYtGVna73ZCHgGIAAZCAAdzSEaj2RYBNQ1vktvN7XwGnjTvUBwQSl8MkE+zxIGs6NwAH4TCAe7hhlbyDNcNbSNzgMBINJ5MM3Fh7KQXCwzTYe0XfEOoKbcGwK7gCXB5uWsDAHdW4E5dyei4fyx1qGd-IFYBi9-hu6ZYSB8R1hqYiqYV57kWxLJHe-qtFAOAsG2IAQOQujQL4yCgCKpZZgACiKCDISgoTJBAghKLBtDTGAADWOg-EOYDlMg-y8FE5gwPMEgyGYzZwBu4JwD8OHNiSzakMg4CUrBeiRPIMAYdM6jzKEyBhBETH0L4AAeABCZGUTAPy0nA6Z6HAinhJE1ggKpak-OUgQAIq8BA8Amcp5lDvIkkibQoS0GO0CweQAKwE2Sj7MgAAcPogAFECRDI0zkCJAVcWkqSwQAjg58AyfBuEgJGAC0UDaEoF6wVoGWCFoMmhHJClIEpZkgJE8yCPR8iMeZ-j6HZmXGfVplMTA3nBaFSAAEzmf8oQBOUYYLPJIlQNAxnmZMPTebhDVwMuQA] and also [tsx](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABL9XAARgE8AHOXYCAIwCs4wYBfHfdVHHOAD3IgAnGLkhQAziIDKAV1oBbAJYwAQjJgxouALy4AFMHa56dAHIBDeXAA0RxfPMBzG0fPqAFgDFFAGxdQcFiRcAAVBCHJxAEpggCkpAA0AOgBRPytYHQA+aiMxSWM6ABFFQR1cAAMAEmB3ABMAM3EQ8xh3MLgGxV4WVBqTWgsrFgruPFFoAvE5JRhYunLzcVIoMH0Y0PClcTgAHgA3CEU6nO0cw3H8PxFyQTgAYQh5Byg6oyu4EUhn81fymR2gkeP1eY3w+EUDX0bja3j8UVyl3BMK8vjgLTaiwA7uZlLh6k17j5FAgYEkZOQfBBzHU4XA9AMSoJrLgUXSou9cGwkZD9PIIDJYAAZRSSBEXcHg24PJ4vOrY3E3cJgODicQAWQFsAx7nEegJ4iJJNgLMZpRZ-MFMBFYs53MlvL00uBcvFnPw3zl5WqwGdst+dRYuAAZMHcDVPQGRnajNyjHcYDJBHg9JzdnVFPssu7cLswvZzIJSGoNNAc-h4LwYNoAOSyBTKGvl3DQI1gADW2mA0wbczo9sl4LAPiW4iGcC7YD0nmgMCJo-H4iSVgzMnkLLJDUEUQHktQ2aRu1QGazRg5UG5IGsIAiMEUk2QoEL4SxLTuEmQIHMh2OV5AtEEcwO0+KRyCAxQoEcZAYEEGQbBAdwYHkHwAHV3GUVUwJVKQEHEZRM2UUhPzANU-wgwEYDCJwHGQBpzB8HZr3ocReBUQDgJgKRLDgEUoDgWj6MYkBmN4KQIMcPwAEUZAgeABIY+CwMEQFP1ocxaFIKkoD-W4IJgFDjjaZAAA4AAZr1uCAdhQwDyE-aVAX2fjrwARxk+AwgicRPyWABaPi4DqQK-zuNzSnRQDHBopA6IU68diUaDYPgvDIKk9z+JiwT4JgdSDLqIykAAJmvGDcWJSCXXMT8oGgZyQABOAABV1O8rKFJYFggA)

In (js)[https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABL9XAARgE8AHOXYCAIwCs4wYBfHfdVHAMwFcpmAS2i4AEnAA2EiAHUIAJwkATABQBKajna5B3FQEIA5vLhwYgqIbXATMXvLxReUlgG4tefPlSpcAFQB5ABEApFwg6AByGFxeAGcqeQBDKCUIAFsdPBNUuHltCTNcJ0yAXlwAWSSYAAsAOm5pBVwVKtq65NSM9QJcAEYAUQBqAHY1OpgIAGUYeQtDdQ64cgkksDgVLiw6rCwlIdRBQwAaXCwQc7UPfEKY2lxyvoAmAGZ3Ty8zz1t7PBUS3BDXBJbRqd44FggY4gCDkczQOLIUBJeTyCAAdwACiiEIiUEkAG4QQRKKEgWjJMAAazMU3Ia3myFmvDg0JqMHSEhkNUE8Di9PWU1xvMEBN5pGQ4DiiOhFgS8hgmOShnSSWQ3CSEgS0PocQAHgAhSk0mBTJLpOAAGQscHVmu1IF1eqm80KAEVeBB4HatayQPT5PLJbQkrRSNIoGTyHNYDISbVkAAOAAM0OjEASMmS5El0bg8oJtuhAEdPfAlbC8SAknEALRQUxKOCk6EmUuCExKpIqtVIDW+6EJdKCJnyFmD11wD1e219+1+mChuNKBNIJ7Q2ZJQQSeYAYQyqslUGgRZA8TgflDeP7CRYLCAA] syntax, it works correctly.

**Comment by pranshuchittora** [comment] 2019-09-18 13:07
@debuggy thanks for providing that information.
I am able to reproduce. 
But the behaviour is quite weird, If I replace the JSDoc with this :arrow_down: then it works perfectly. :confused: 
### Input
```diff
-/**
- * @type {object}
- */
+/**
+ * Represents a book.
+ * @constructor
+ */
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  if(!greeting){return null};

     // TODO: Don't use random in render
  let num = Math.floor (Math.random() * 1E+7).toString().replace(/\.\d+/ig, "")

  return (
    <div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}>

    <strong>{ greeting.slice( 0, 1 ).toUpperCase() + greeting.slice(1).toLowerCase() }</strong>
    {greeting.endsWith(",") ? " " : <span style={{color: '\grey'}}>", "</span> }
    <em>
	{ greeted }
	</em>
    { (silent)
      ? "."
      : "!"}

    </div>
  );

}

```
### Output

```jsx
/**
 * Represents a book.
 * @constructor
 */
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}

```

**Comment by debuggy** [comment] 2019-09-19 07:05
@pranshuchittora thanks, I will take this as a solution

**Comment by pranshuchittora** [comment] 2019-09-19 12:05
@debuggy ur welcome :smile: 
If you think this works then I recommend you to pls close this issue. You can always reopen it..

Happy Hacking :+1:

**Comment by j-f1** [comment] 2019-09-19 12:17
This is still a bug which should be fixed though:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AARgE8AHOXYCAIwCs4wYBfHfVHACgEpcBeAHy5ObXAB4AJgEsAbgNG5cAZwCGdCQDMyEKSqUS6WnXoNHd+w9t0SlllTosaVZfVIga6zt1NWa9AayclMjcPMlExVGk5HG4AbhwQABoQCDIYNyglZFAVACc8iAB3AAV8hGyUFRkdCWSQGjyVMH84GABlMmapKABzZBg8gFc4FIALGABbABsAdTGpeGDmuHaKxdlFkmRwJWyUnqU4PJgSpt7JlWQnaaOUuiUADwAhJpa29pVJuAAZHrhripbqMQA9Hu0er1pnAAIpDCDwQHAlJdPJHPI7GgqGgkabQepkPI9GCzKQSGBjZAADgADCjCkdZk0yDtCXB0TIASkAI7w+BnNKVEB6AC0UDgcAkkvqeTgvKksrOKguVyQNzuICOkykA2GIKUkOhcIRALVQI1MGxpPJlKQACYUoMVFJppCAMIQSaXHZQaBckBDI4AFWxlXVcGYzCAA)
```sh
--parser babylon
```

**Input:**
```jsx
/**
 * @type {object}
 */
() => (
  <div>
    sajdfpoiasdjfpoiasdjfpoiasdjfpoiadsjfpaoisdjfapsdiofjapioisadfaskfaspiofjp
  </div>
);

```

**Output:**
```jsx
/**
 * @type {object}
 */
() => ((
  <div>
    sajdfpoiasdjfpoiasdjfpoiasdjfpoiadsjfpaoisdjfapsdiofjapioisadfaskfaspiofjp
  </div>
));

```

**Comment by kaicataldo** [comment] 2019-09-20 04:45
I'm new to the Prettier code base, but I _think_ this is caused by the closure compiler typecast check [here](https://github.com/prettier/prettier/blob/master/src/language-js/needs-parens.js#L13) interacting with the parens printing behavior [here](https://github.com/prettier/prettier/blob/master/src/language-js/printer-estree.js#L177-L197). 

The closure compiler typecast check traverses all the way up the ancestor node chain, but it seems like it should have some kind of condition that stops it from traversing once it's "out of bounds" of the expression it's checking.

**Comment by sosukesuzuki** [comment] 2019-09-20 15:28
Probably, this issue is duplicated to #6283

**Comment by lydell** [comment] 2019-09-20 16:54
Duplicate of #6283

**Closed by lydell** 2019-09-20 16:54 UTC
Labels: lang:javascript, type:bug
