### ISSUE TITLE
Attribute single-quote formatting

### ISSUE THREAD

**Issue by runeabrahams1** [prettier/prettier#5568] opened 2018-11-28 11:27 UTC
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAllADgVxgAngGcYBeAcmGHwB0RiY78AfQgJwEMoiAbD+fAF9B5fAHoAfCAA0ICFhjpoRZKA5s2EAO4AFdQhUoOANwjoAJjJAAjTmADWcGAGUsHMJgDmyGGxxxZAAsYAFseAHVA9GI3MDhnA2j0Y2iAT2RwIhVZTCI4NhgdTk8QjmQAMw4ePNkAKyIADwAhO0cXDhC4ABlMOAqqmpB6hucvHjgARRwIeH7qgJA3Njy2DK5PHD5V2Sw2TBhwixhA5AAOAAYdzTzwziwM3bgV4z7ZNjgARxx0d6KOErKSEq81keRC6B8fgWRDGk2msyBAwWMA41kO5mOyAATLJfBx0DwvABhCAhUoZKDQV4gHB5AAqqMMwLywiAA)
```sh
--parser angular
```

**Input:**
```html
<input test='{{ "test" | translate }}' />
```

**Output:**
```html
<input test="{{ &quot;test&quot; | translate }}" />
```

**Expected behavior:**
```html
<input test="{{ 'test' | translate }}" />
```

The result seems to be be the same. The translate-pipe gets **'test'** as an input, but I think it would be better to format it to **'**, or just do nothing.

**Edit:**
I guess **& quot;** means double-quote, and not single-quote, so it might be more correct to leave it this way or just do no formatting. I'll let the issue stay open and you can decide if it should be changed

**Comment by ikatyang** [comment] 2018-11-28 12:07
Hi, this looks like a duplicate of #5477, let's track the issue there.

**Closed by ikatyang** 2018-11-28 12:07 UTC
