### ISSUE TITLE
Cant modify playground text

### ISSUE THREAD

**Issue by coloradude** [prettier/prettier#4769] opened 2018-06-29 04:27 UTC
Yeah just cant modify ant text on the playground regardless of browser or extensions.

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/)
```sh
--parser babylon
```

**Input:**
```jsx
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  if(!greeting){return null};

     // TODO: Don't use random in render
  let num = Math.floor (Math.random() * 1E+7).toString().replace(/\.\d+/ig, "")

  return <div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}>

    <strong>{ greeting.slice( 0, 1 ).toUpperCase() + greeting.slice(1).toLowerCase() }</strong>
    {greeting.endsWith(",") ? " " : <span style={{color: '\grey'}}>", "</span> }
    <em>
	{ greeted }
	</em>
    { (silent)
      ? "."
      : "!"}

    </div>;

}
```

**Output:**
```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}

```

**Expected behavior:**

**Comment by ikatyang** [comment] 2018-06-29 04:30
Uh, it's a placeholder for demo. 😅

It seems we should add a feature that clicking the placeholder should bring the text to the content area.

**Comment by ikatyang** [comment] 2018-06-29 04:30
Duplicate of #4132

**Closed** 2018-07-01 08:17 UTC
Labels: area:playground, status:has pr, type:feature
