### ISSUE TITLE
[feature request] sort imports

### ISSUE THREAD

**Issue by xialvjun** [prettier/prettier#4654] opened 2018-06-08 08:45 UTC
**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwEMBnAM2IBMB3OARx3wF99ycJ18ByAOgHpiAIzAALbgG4AOlAzY8hfACEArqQA0+AIJhNAaRqjiMTQGVOcAKIAbUnE0B1I-ABucHJqOjN5CBE9kVL50OEKB5CxsHFzcQtwycrgERErQ9viGxgDyUHDEkeycPMSSMjL8-PgAqgCS+ADCnNi5sAlYSYoAshBUxNaaADIQ1O6anQgqmgBiuOiaNVCYKgSshTF26MSwqGAAtCqouzh5YDClsu0KRPUATJr1AIz3AMwF0TwC6ACeAPqQ7S0YKRJCB1CAIJgYKhoKRkKBiDgODQAAoIhCwlDEFwQVBUUEgIQ4YhgADWcBgpkwxNQUAA5sgYDgVPY0FA7HhkUTaZtkJRbCyAFakAAeSiJpPJpmI6DgAxpcF5fTsYKpOHZyAJwi+1mg+MwOBpMAcuJgomQAA4AAwqjh2BxEzAa-VwdlufHHegHY6c4jc4iK-lgjaoBlMlmkGm06xwACKKgg8ADypAMGExqopuQdxTRNQ1kjjXQPJQUDS+LUcAAKsIMXy7MxmEA)
```sh
--parser babylon
```

**Input:**
```jsx
import { asfadweqr } from './abch';
import { Bus, Ac, Kwhat, SomeElse, Whatever, hah, foo, hasdfowerbasdf } from 'b'
import { Bone, whatOnea } from 'a';

// UI Component
import { Modal, Loader, Menu, Form, Input } from 'semantic-ui-react';
import { C2, C1, C3 } from './my_components';
```

**Output:**
```jsx
import { asfadweqr } from "./abch";
import {
  Bus,
  Ac,
  Kwhat,
  SomeElse,
  Whatever,
  hah,
  foo,
  hasdfowerbasdf
} from "b";
import { Bone, whatOnea } from "a";

// UI Component
import { Modal, Loader, Menu, Form, Input } from "semantic-ui-react";
import { C2, C1, C3 } from "./my_components";

```

**Expected behavior:**
```jsx
import { whatOnea, Bone } from "a";
import {
  foo,
  hah,
  hasdfowerbasdf,
  Ac,
  Bus,
  Kwhat,
  SomeElse,
  Whatever
} from "b";

import { asfadweqr } from "./abch";

// UI Component
import { Form, Input, Loader, Menu, Modal } from "semantic-ui-react";

import { C1, C2, C3 } from "./my_components";

```

**TIPS:**
1. absolute path module is at top, relative path module is at bottom;
2. sort module by module path;
3. don't lift up module across comments, because we may use comments to classify modules;
4. default import first, other import should be sorted by origin name rather than as name;

**Comment by xialvjun** [comment] 2018-06-08 08:50
if there is:
```ts
import React as ReactDefault, { PureComponent, Component } from 'react';
import * as React from 'react';
```

Expected behavior:
```ts
import * as React from 'react';
import React as ReactDefault, { PureComponent, Component } from 'react';
```

**Comment by ikatyang** [comment] 2018-06-08 09:11
See https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about:

> ## What Prettier is not concerned about
> - Sorting and hoisting `import`s. (Sorting is unsafe because of side effects, which would violate the [correctness](https://prettier.io/docs/en/rationale.html#correctness) goal.)

Closing as duplicate of #767.

**Comment by ikatyang** [comment] 2018-06-08 09:11
Duplicate of #767

**Closed by ikatyang** 2018-06-08 09:11 UTC

**Comment by xialvjun** [comment] 2018-06-08 09:15
Using too much es module and forgot side effect. 😅

**Comment by xialvjun** [comment] 2018-06-08 10:44
@ikatyang Then, how about just sort the extract import:
`import { C2, C1, C3 } from "./my_components";` to `import { C1, C2, C3 } from "./my_components";`

**Comment by ikatyang** [comment] 2018-06-08 13:59
This kind of transformation (i.e. sorting) is not likely to be implemented in a formatter even if their behaviors are the same, since they did affect the AST, and formatters should only affect styles.

I'd recommend you to use some fixable linter rules to achieve this goal.

**Comment by k15a** [comment] 2018-06-08 14:22
You can also use https://github.com/renke/import-sort to archive what you want.
