### ISSUE TITLE
Should move ES6 imports to new line if it exceeds the print width

### ISSUE THREAD

**Issue by saranshkataria** [prettier/prettier#3707] opened 2018-01-11 05:19 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHgGcZUoBzAX3wDMcJ18ByAGVzidU2IFcmAJhAA2ufMVQEAhujgwANPkhRicMPBi8c+KQO6piYchXxxhkxaoH4hzADpQM2PISnyARjXqMW7HJ3xuPkERMQlpWQUlaFV1OS0dPUwDI0pTcyirGwhmEHkQCEwyGORQKRwGAHcABXKEYmQQKQA3CFQBPKbSZFopYVV89xwpMABrOQBlTBHjZBgcXjh8oTAevoG0FTg8auGKdCk1-qWQACtiAA8AIWGxyZk4VnI4I42IXhhMD4AmV5PpnCqHCNdxSdwAT1EUE6mBw5BgAHV2jAABbIAAcAAZ8rCIKoEcNMI1YXAgc0Xvl-ABHXiofy7KT7Q5IXrHfKqdCoOYLE4SSjCOAARV4EHgf3yMDBSIEqOQ3wlw1Q5koAGFGAdGlBoBSQLxVAAVMENFnrOBUKhAA)

**Input:**
```jsx
import {testing} from 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do'
import {a,b} from 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do'
```

**Output:**
```jsx
import { testing } from "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do";
import {
  a,
  b
} from "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do";

```

**Expected behavior:**
The first import statement should break into multiple lines, as is happening for the second import statement

**Comment by azz** [comment] 2018-01-11 05:58
Hi, this is a duplicate of #1954

> This is actually intended. We have a special case for import and require with single elements where we keep them in a single line. You don't get much more information when they are in two lines and they look worse with a series of imports. This was done due to common request from people using prettier.

**Closed by azz** 2018-01-11 05:58 UTC
