### ISSUE TITLE
Does not respect print width when chaining method call after property

### ISSUE THREAD

**Issue by ytmagalhaes** [prettier/prettier#5051] opened 2018-09-04 14:51 UTC
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaXACTgBsaIB1CAJxoBMAKASl2AB0ouXJCjoYuALaYAMtADmANVTMkuWVDkAVTAAc4AETj5SUUmQoBeXKgDuqM7gDCqOibkB5AEYArOGBgAdDAAFggAsnAhEJxcAahQECFwzF6+-nEJScwRUTEA3AIAviAANCAQOuaiyKDKzBA2AArKCOjIaABuEKRspSCezKhgANaRAMo6Q27IMMyEcGUm6MkwjYNyEqjI+C7LZd7oAB4AQoMj46gScNImcNu7CyCTzMvM7Z6onpj0UH06zCYYAweiFkAAOAAMZX+EGWDEGOna-zgrw6dzKzDgAEdCKRMWtUBstkgdjQ9iBlhJSDM5o90G4aHAAIqERJ3EkPMowT7AtigpAAJi5g1INDcjggEk27QSUHRIEIy00nzaHLJcEKhSAA)
```sh
--parser babylon
```

**Input:**
```jsx
async function HelloWorld() {
  const myLongVar: LongTypeDefinition = await CallingObject.thenMethod().anotherObject.anotherMethod();
}
```

**Output:**
```jsx
async function HelloWorld() {
  const myLongVar: LongTypeDefinition = await CallingObject.thenMethod().anotherObject.anotherMethod();
}

```

**Expected behavior:**
```jsx
async function HelloWorld() {
  const myLongVar: LongTypeDefinition = await CallingObject
    .thenMethod()
    .anotherObject
    .anotherMethod();
}
```

Possibly a duplicate of #2548, but that issue has been open for over a year and have been ignored. Couldn't find a case where people are complaining the chaining from `object to method to object` is not formatting.

**Comment by j-f1** [comment] 2018-09-04 20:07
> Possibly a duplicate of #2548

Yep, looks like it is.

**Comment by j-f1** [comment] 2018-09-04 20:07
Duplicate of #2548

**Comment by j-f1** [comment] 2018-09-04 20:07
Feel free to open a PR!

**Closed by j-f1** 2018-09-04 20:07 UTC
