### ISSUE TITLE
Format flow js files with flotate comments

### ISSUE THREAD

**Issue by xeoneux** [prettier/prettier#4305] opened 2018-04-12 16:50 UTC
[flotate](https://github.com/jareware/flotate) is now part of flow itself.

I use flow with types in the comments rather than using babel to remove them afterwards. This way the files run directly in node without any transpilation.

Support for flow by prettier is quite strong and would love the support for flotate in comments if the comments start with either `/*:` or `/*::`

**Comment by j-f1** [comment] 2018-04-12 16:53
Our issue tracking this is #719.

**Comment by j-f1** [comment] 2018-04-12 16:53
Duplicate of #719

**Closed by j-f1** 2018-04-12 16:53 UTC
Labels: lang:flow, type:duplicate
