### ISSUE TITLE
SCSS media queries with single line comments converts code to comment

### ISSUE THREAD

**Issue by Mathias-S** [prettier/prettier#12932] opened 2022-05-27 16:21 UTC
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtnAJgSwIYAEADgE46wA0BA9NQZOprADpQDOYJcCBwrBNagDoRrAL6sQFEBCIwc0NslB4SJCAHcACqoRKUeADYa8ATyXSARiTxgA1nBgBlPJgAy5OMgBmRtnCsbe0cnIltyAHNkGBIAVwCQOHRLbCxsNzwoCNi8CLgAMQgSdDwYeSzkEDxYmAgpEAALGHRDAHUGnHg2MLA4Jz1OnAA3TtNKsDYLEHJ-EhgtGwiSnz8EgCs2AA8nSMM4AEVYiHgVw39pMJJZyo5J+tJyGFacLBgG5AAOAAYL9X9WmxESqkOCzIZeaQARyO8AWsn0VTYAFooNw0lh6lxoTguAtcsskL4zgl-OgcNE4iTdgcYV5CatpDA8JZnq93kgAEyMmw4QyRADCEEYeEqoIArPVYv4ACrM-RE84gIbxACSUDSsCcnBwcgAguqnDBTHtTv4xGIgA)

```sh
--parser scss
```

**Input:**

```scss
@media print, // comment
screen {
  //...
}

```

**Output:**

```scss
@media print, // comment screen {
  //...
}

```

**Expected behavior:**
```scss
@media print, // comment
screen {
  //...
}

```
The output should not convert code to a comment. The current output is invalid SCSS, and breaks the _correctness_ requirement of Prettier.

**Comment by nex3** [comment] 2022-11-08 01:11
Duplicate of https://github.com/prettier/prettier/issues/7006?

**Comment by alexander-akait** [comment] 2022-11-08 01:39
Duplicate of https://github.com/prettier/prettier/issues/7006

**Closed by alexander-akait** 2022-11-08 01:39 UTC
Labels: type:bug, lang:css/scss/less, type:duplicate
