### ISSUE TITLE
Prettier is improperly formatting Jinja 2 syntax inside of the HTML files.

### ISSUE THREAD

**Issue by mahyarmirrashed** [prettier/prettier#8213] opened 2020-05-04 00:04 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwCkACOAPeUAmAzhgDogA2AhgJ4QCuMAdABYwC25ZGaAviVP3QYARuQhgA1hhgBLGOTjceGADIQA5hgCSUDEIT5R4qb36DMRyRjaUZu01AA8AMwgAnNhkphZ0ALxkAPRi6nZcbHAwzBD4ASAADhCEMGQAfPwYmRiO+DIAbhhgVISEca4eALTqbvTxaRlZjY528QwNjR1eDOIQbPEK8HEQzs5k7Z1ZlN2uYHSE4xOFxaVk5WwVkLA1nCALE1CUEXFzcG4HEWO6i1n93nDR5PincQCqhKfncJfXWTDU8XA4vBcN8JoF0ldMo5Ark8hCmrClpQSmV3OtqrV6pCOs0oK0UtjFkVkSsQGsNtAYNtQT9PnF4iSAO7ufA0663MD3CCPZ5kAAKTJZbMWfwB9MFblZu0JWXB42hsPhWUcwgYMGgSJRZGEMF0OqgFXibhkNjc1C4osBZEIdGEbDkaTUmh00NVMHVUAh0LWEP0BEsJj4UBAABoQBB4r4oIRkKBKG4aoyBW4EDGUJRyIyaDGw8I3N4JJEAMoMsB2dTIKl0OBh1gcADqzDkcEIpbgRdTcnycmoyHAJVDIDs7zcMD5+fUNmQzgz7zDACtCNgAEL5yTFw5wFR2ODT2c1kCL7BF8sKACKdAg8D35DnCXjI77dfIg6Ndhg9Zk+CiyAAHAAGMMjSSOB63zeI+yNFtTjyXcwwAR0veBxwjNMQGRCooDgOAnnwQcU0QmQU3HShJ0oG873ee1Kzcasw0IU84AvK9dyQGdbwPGBKGET9v2YZAABYwypWxyHLABhXopxQFsAFZBxOAAVbi0yrA88mrHQnlgIswGNSMAEECCLP4FAouAeB4IA)
```sh
--parser html
--tab-width 4
--use-tabs
```

**Input:**
```html
{% extends "layout.html" %}

{% block title %} Log In {% endblock %}

{% block main %}
<form action="/login" method="post">
    <div class="form-group">
        <input
            autocomplete="off"
            autofocus
            class="form-control"
            name="username"
            placeholder="Username"
            type="text"
        />
    </div>
    <div class="form-group">
        <input
            class="form-control"
            name="password"
            placeholder="Password"
            type="password"
        />
    </div>
    <button class="btn btn-primary" type="submit">Log In</button>
</form>
{% endblock %}

```

**Output:**
```html
{% extends "layout.html" %} {% block title %} Log In {% endblock %} {% block
main %}
<form action="/login" method="post">
	<div class="form-group">
		<input
			autocomplete="off"
			autofocus
			class="form-control"
			name="username"
			placeholder="Username"
			type="text"
		/>
	</div>
	<div class="form-group">
		<input
			class="form-control"
			name="password"
			placeholder="Password"
			type="password"
		/>
	</div>
	<button class="btn btn-primary" type="submit">Log In</button>
</form>
{% endblock %}

```

**Expected behavior:**

**Comment by thorn0** [comment] 2020-05-04 09:48
Duplicate of #5754

**Closed by thorn0** 2020-05-04 09:48 UTC
