### ISSUE TITLE
Using parentheses around function initialization

### ISSUE THREAD

**Issue by seahindeniz** [prettier/prettier#8145] opened 2020-04-24 08:51 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AARgE8AHOAEzgDNdhgd9dcBnASwC84lcsQANgEMATgHM4-XAB8+IALZV2AV3lTZ-VvKECB6uQA8tOvSAA0TAgF8ruAMLLWMCPIAKIiBREx2cVpaJSCnoHJxd3TzhvX1ZcADJcAAkAFQBZABkAIWUYZygAUQE4RVgrS1QcSCgnXAAjHLzcAF5cAApKCDBVBBgAOjAROCF4QuKe1v563Oh+AEpZgG4cKbzejm5muWFxSRAF8xBPH2hWZFBRDwB3V1EEU5QdS6ESU7MQWpEhMABrOBgAZTIX3YUDEyBgImUcDeAAsYPIBAB1GHseCsIFgOD-O6o9gAN1RJGQ4FYrxAINYURg7iEYm0yBoOkpbwAVqwDJlPj8-v8hIp0iC4AymdCQGyDP8QWIigBFZQQeDCgTMkBAkSUkTE2pCWpwAQHMgiEEwRHsSgwGHIAAcAAY3oaIJTEZ8yMTDX4onihW8AI7y+ARMj3EBCVgAWigcCoVAOgz97EGNLpQiVKsp8nY4Mhoo4oNl-qFSEZytFMB1pvNlqQACY3hChOwBFK7C56Sg-ABWA6OODJHX3YsqvFQgCSUGosH+A3YZBgAEFx-9SEVU3AbEA)
```sh
--parser babel
```

**Input:**
```jsx
/**
 * @typedef {{
 *  size: "large" | "medium" | "small" | "xsmall",
 * }} CustomProperties
 * @type {CustomProperties & HTMLButtonElement}
 */
const button = (document.createElement("button"));
button.size = "large";
```

**Output:**
```jsx
/**
 * @typedef {{
 *  size: "large" | "medium" | "small" | "xsmall",
 * }} CustomProperties
 * @type {CustomProperties & HTMLButtonElement}
 */
const button = document.createElement("button");
button.size = "large";

```

**Expected behavior:**
```jsx
/**
 * @typedef {{
 *  size: "large" | "medium" | "small" | "xsmall",
 * }}
 * @type {CustomProperties & HTMLButtonElement}
 */
const button = (document.createElement("button"));
button.size = "large";
```

With parentheses
![image](https://user-images.githubusercontent.com/5789670/80193514-9af4d200-8621-11ea-9ff1-9cfc54b6e411.png)

Without parentheses
![image](https://user-images.githubusercontent.com/5789670/80193608-caa3da00-8621-11ea-96f2-ce1150dd286f.png)

**Comment by thorn0** [comment] 2020-04-24 09:03
Duplicate of #8096 

Please see https://github.com/prettier/prettier/issues/8096#issuecomment-616516093

**Closed by thorn0** 2020-04-24 09:03 UTC
