### ISSUE TITLE
Format embedded JavaScript in template literal ... in JavaScript?

### ISSUE THREAD

**Issue by xnuk** [prettier/prettier#11517] opened 2021-09-13 08:00 UTC
### Environment
- Prettier 2.4.0
- `--embedded-language-formatting=auto`

### Input
```javascript
const code = javascript`
            ;(
           new class {
          init() {
         for(let n = 1; n < 10; ++n) {
        console.log('')
       Array.from({ length: 9 },
      (_, m) =>
     [n, '*', m+1, '=', n*(m+1)].
    join(' ')).
   forEach(line => console.log(line))
  console.log('')}}}).
 init()
`;

writeFile("/path/to/file.js", code);
```

### Output
In most case (especially default options), output is same as input.

### (Example of) Expected Output

```javascript
const code = javascript`
  new (class {
    init() {
      for (let n = 1; n < 10; ++n) {
        console.log("");
        Array.from({ length: 9 }, (_, m) =>
          [n, "*", m + 1, "=", n * (m + 1)].join(" ")
        ).forEach((line) => console.log(line));
        console.log("");
      }
    }
  })().init()
`;

writeFile("/path/to/file.js", code);
```

**Comment by thorn0** [comment] 2021-09-13 13:17
Duplicate of #5908

**Closed** 2021-09-13 13:18 UTC
Labels: type:duplicate
