### ISSUE TITLE
Add option to set braces style

### ISSUE THREAD

**Issue by sergeysova** [prettier/prettier#3832] opened 2018-01-26 23:45 UTC
```js
if (foo && bar) {
  // branch a
} else if (baz) {
  // branch b
} else {
  // branch c
}

try {
  // code block
} catch (error) {
  // handle error
} finally {
  // after all
}
```

I prefer stroustrup brace style as more clear and readable.

```js
if (foo && bar) {
  // branch a
}
else if (baz) {
  // branch b
}
else {
  // branch c
}

try {
  // code block
}
catch (error) {
  // handle error
}
finally {
  // after all
}
```

**Comment by suchipi** [comment] 2018-01-27 01:53
Closing as a duplicate of https://github.com/prettier/prettier/issues/840

**Closed by suchipi** 2018-01-27 01:53 UTC
