### ISSUE TITLE
Feature: Generate Initial Config on First Run

### ISSUE THREAD

**Issue by merlinpatt** [prettier/prettier#9179] opened 2020-09-10 05:15 UTC
One thing that I like to have in my projects is the ability to see (and likely modify) the various configs that I will use.

**Main Solution**: As such, it would be great to have Prettier generate a config file the first time it is run in a project or perhaps with a `--generate` flag.

This way a developer can quickly see and easily edit all of Prettier's config options as they like, but they don't have to remember what they all are or look them.

**Improved Solution**: An improved solution would be to have Prettier look for a base config file in the user's home folder, copy that over and use that config. This is not meant to be a global config file as I know Prettier is against global configs. But many folks have their preferences that they like to set when starting a project. This would make it even easier to do that. The way I see it, it would work like this

1. Developer creates their ideal prettier config at `~/.prettier.default`
2. Developer creates new project
3. Developer runs `prettier`
4. `prettier` finds `~/.prettier.default`, copies it into the project as `.prettierrc`, and runs using that config

**Comment by evilebottnawi** [comment] 2020-09-10 10:15
Duplicate of #8053

**Closed by evilebottnawi** 2020-09-10 10:15 UTC
