### ISSUE TITLE
Markdown with `proseWrap: "never"` de-formats tables with Chinese characters whose rows are over a certain length

### ISSUE THREAD

**Issue by alanorozco** [prettier/prettier#11799] opened 2021-11-11 20:22 UTC
Using Markdown with `proseWrap: "never"`, tables are de-formatted when:

1. They include a Chinese character, (and possibly of other sets as well—though `ñ` is fine)
2. One of the rows is over a certain character length.

**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAeQNJIDpQEA+6AYhAE4C2AhjOg408y64yQMo1UAOANnCwBXGDxFsSAJTi0KAawDObBkWLoAtJq3aduvfvQl9xrYY0mdhtQDpby+w6Ylb1xy2d23qqCWAATAF90fxoATwUg4AALSKiIIQoI4KpIqgBLKBE4JJIAUQBH7PQEdFyFHhp8iD4zAAM+CDAaAQBeAHJs9SoADzbaq0IoDBx8QZJyajo3aZV0Ll4BYVFxVikZGnklZW8jCz2TM329Q6P1AY9XGauLq9mXaZ3gwKewpOjY+MTU1IysswBWAAM6EAlJrof7oQDwOoA303QAEZgYAwJUA+Sl1BpNVptABeUXUYCgfQGBAwADkIPQRugABRQclpMCCPgZRkIADmMCiAEoCGoJrR6LcvHNuPxBJgRGIBe50NJZIp7I9TkrLLtlWdVftzuh7oKZjdbvrHI9-JE-K9Yh8Em8UslfvAcuDgWCITD4UjUSR6o1mnB2ji8QT+t4CCAADQgCA8GBpaAKZCgDYUCAAdwAChsEHGUM1k68wyAAEYUGhgORwGDzOAAGWZyAAZs0FHBw0WS2WKxUwBlWcgYBQhM2QDIC3A-H5R1WaFBWUIaKy4Hy6NHp8gQDQRBB81EYFQ+AB1KJpe2duAcTNHtIANyPoVXYAUcfDGSbFBgqeLrNo9cbg4AVgpug4bsBAARSEck4G-Pgm3DCpEjgChVzlPwUygfMeAoDIYD3NI-A5ZAAA5AVgpMmz3YseFXKA4EvBD8wAR3A+B30jLM1wUdRqNHUd8woOBGLSPj3znL8kAbaDBybdJe37STgLgMCIKgmCQBgGgCxwvComQAAmcM+xoNImWnABhCAqFEocFH+fMhCbAAVdSs3ElTLwHABJKBx1gDgwEwqMAEEvI4GBQgEZS4ACAIgA)

```sh
# Options (if any):
--prose-wrap=never
```

**Input:**

```markdown
# OK:

| Format                               | Sample Output        | Remarks          |
| ------------------------------------ | -------------------- | ---------------- |
| ...                                  | ...                  | ...              |
| {d} {days} {h} {hours} {m} {minutes} | Eñes en Español | `locale='es-mx'` |

# OK:

| Format                             | Sample Output        | Remarks          |
| ---------------------------------- | -------------------- | ---------------- |
| ...                                | ...                  | ...              |
| {d} {days} {h} {hours} {m} {minute | 50 天 5 小时 10 分钟 | `locale='zh-cn'` |

# Not OK: (notice line length)

| Format                               | Sample Output        | Remarks          |
| ------------------------------------ | -------------------- | ---------------- |
| ...                                  | ...                  | ...              |
| {d} {days} {h} {hours} {m} {minutes} | 50 天 5 小时 10 分钟 | `locale='zh-cn'` |


```

**Output:**

```markdown
# OK:

| Format                               | Sample Output   | Remarks          |
| ------------------------------------ | --------------- | ---------------- |
| ...                                  | ...             | ...              |
| {d} {days} {h} {hours} {m} {minutes} | Eñes en Español | `locale='es-mx'` |

# OK:

| Format                             | Sample Output        | Remarks          |
| ---------------------------------- | -------------------- | ---------------- |
| ...                                | ...                  | ...              |
| {d} {days} {h} {hours} {m} {minute | 50 天 5 小时 10 分钟 | `locale='zh-cn'` |

# Not OK: (notice line length)

| Format | Sample Output | Remarks |
| --- | --- | --- |
| ... | ... | ... |
| {d} {days} {h} {hours} {m} {minutes} | 50 天 5 小时 10 分钟 | `locale='zh-cn'` |

```

**Expected behavior:**

Last table should be formatted

**Comment by Josh-Cena** [comment] 2021-12-02 05:12
This is not a Chinese-specific issue. When the row exceeds a certain width the table is collapsed to `| --- | --- | --- |` instead of attempting to grow indefinitely. The same happens if you replace `50 天 5 小时 10 分钟` with `aaaaaaaaaaaaaaaaaaaa`

**Comment by benface** [comment] 2022-01-12 14:51
Duplicate of #11571

**Comment by thorn0** [comment] 2022-09-08 23:01
Duplicate of #11571

**Closed** 2022-09-08 23:01 UTC
Labels: type:duplicate
