### ISSUE TITLE
Markdown syntax in comments causes different output then expected

### ISSUE THREAD

**Issue by j-a-k-git** [prettier/prettier#10873] opened 2021-05-12 20:13 UTC
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArTAXk2AB0pSYB6AKhvMsxswGI3MBVNASygHNMAWQCGAJwDWAEwgB3KJjQBPWMIAemXpkgBbbQhhotwgK5o4hmAAs4mAGYQANg9m8B3NGmNwAdOUz--ZgAVCA0oM1EsYUwoOBlMB14bMEsxYTB4UUwZG1MbaWMcBxs0AAd0m3snWThJTBxFTH04UV95AKZMADEILLhVYW1S4swrGxw4Z3iMYXg9WDQ2js6-DuYu7lEMBKTsW1HrLQhdfW9-VYDmAGU4SCg6xNi9g+Tj+Zg2xmYLwMwgw4QdQg+1sm22jxsqTqMBkoTKFUMsxeTXuABp6sYsGM7L1tLMYK5MD9OqI4NoIAA3WovbRLNZ-SzuIx5Qx4NDSMCYYT3TAUwyQSQ2XjwJzuBBmUahSTuYbCRrY+CqLCabHE5hVKaEmRypBqtXdMFYCHPbE6d5nG53B67YHIs2nPXtS6YADqr2MDjq0gOTJgoXS1m4VK5Cm42m4DjEmFJngcWBwmI0yvCLQMIZw3D4fBa+rxoj4mhVhwgmNKmLpzv1Gy2Rpt+1NbwdTsC+st0GtT1tDZOsArLYoWBoVAYMAA8uIkJgAIyo8gAXxAqJAEFKBPQyFAYlEsgACmJxcgQMIHNrFGhFyAcKJ0uI4DAruUwK5kDBRF4l2SJpJBZIADLcvhjGEbMelEPEYAJfhDxMP0L0sGBtAcF1GXgeEwDgG5wm4AkKWwxRDzADwL14CIYB3a8+DxZBbGPMwlzZVQACFrzAW970GOBfySajaLgei0FUK5XGKABFYwIHgHiHDokByi2FpDxwYQJgcC9SlEYUXW4SQrGQAAOAAGJd1IgMwXWvUpD3U8wWipC8AEdxPgciV3PFBhDQABaWJalqC9SUczY4HI4CqKQGjpL4kAzHDF83yinh+FEpy4CkmSYGUrSdMsZAACYl1fYQI1cABhN5hEPcwAFYLzyIJlLciKZIpLwAEl7n0K4wA01cAEF7iuGBFGKNK4DnOcgA)

```sh
--parser babel
```

**Input:**

```jsx
const obj = {
    /**
     * ### Using Markdown syntax in comments causes the following issue.
     * To insert a new line character we use double space followed by enter.
     * For example the below statements.
     * 
     * First line of the comment.  
     * Second line of the comment.
     * 
     * The end of first line had two spaces at the end, but the formatting 
     * removed them.
     * This causes jsdoc and vs code intellisense to display the text in the 
     * following way:
     *
     * First line of the comment. Second line of the comment.
     *
     * We could do this to acheive a similar result but it inserts a bigger
     * margin in the output.
     * 
     * First line of the comment.
     *
     * Second line of the comment.
     *
     */
     Ok: 1,
}
```

**Output:**

```jsx
const obj = {
  /**
   * ### Using Markdown syntax in comments causes the following issue.
   * To insert a new line character we use double space followed by enter.
   * For example the below statements.
   *
   * First line of the comment.
   * Second line of the comment.
   *
   * The end of first line had two spaces at the end, but the formatting
   * removed them.
   * This causes jsdoc and vs code intellisense to display the text in the
   * following way:
   *
   * First line of the comment. Second line of the comment.
   *
   * We could do this to acheive a similar result but it inserts a bigger
   * margin in the output.
   *
   * First line of the comment.
   *
   * Second line of the comment.
   *
   */
  Ok: 1,
};

```

**Expected behavior:**
![image](https://user-images.githubusercontent.com/16626680/118038206-74b8e600-b38c-11eb-975b-d074b7582786.png)

**Got this.**
![image](https://user-images.githubusercontent.com/16626680/118038326-9914c280-b38c-11eb-979c-b932ea6843cf.png)

**Comment by fisker** [comment] 2021-05-13 07:12
Duplicate of #6793

**Closed by fisker** 2021-05-13 07:12 UTC
