### ISSUE TITLE
Problem concerning execution of prettier

### ISSUE THREAD

**Issue by khalilazaiez** [prettier/prettier#10600] opened 2021-03-25 14:04 UTC
After installing all the dependencies I tried to execute prettier using yarn test but after the execution was done nothing happened and it just said:
Test Suites: 1115 passed, 1115 total
Tests:       11880 passed, 11880 total
Snapshots:   6547 passed, 6547 total
Time:        1393.035 s
Ran all test suites.
Done in 1450.00s.

What should I do?

**Comment by thorn0** [comment] 2021-03-26 00:12
Please clarify the problem. It's unclear what you expected to happen and what you're trying to achieve.

**Comment by khalilazaiez** [comment] 2021-03-26 21:03
What is the expected result after the execution is done? Should I expect an interface opened in browse?

**Comment by thorn0** [comment] 2021-03-26 22:58
> What is the expected result after the execution is done?

`yarn test` runs tests using [Jest](https://jestjs.io/). The expected result is that the tests all pass. Just like you saw.

> Should I expect an interface opened in browse?

No. What made you think something like that should happen?
If you want to build Prettier's web site locally (if that's what you mean), see `website/README.md`.

I'm going to close the issue since it's not a bug report/feature request/etc.

**Closed by thorn0** 2021-03-26 22:58 UTC
