### ISSUE TITLE
Prettier removes flow type casting expression if used as comment

### ISSUE THREAD

**Issue by jacobp100** [prettier/prettier#4188] opened 2018-03-21 20:59 UTC
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEALOAbPCTAegColMAzCAJzDgGEBDDTU4zAXkwAomTymJlACebYgEoAOlBAAaEBAAOMAJbpkoJjRoQA7gAVtCNMhBMAbhFUATeeYzJKTPGjgKARjSZgA1nBgAZSUfVSgAc2QYGgBXdxAbCDAnFzcFMLcaGANvcIBbJhTXeIArNAAPACFvPwDApjy4ABkwuCK0xRiYJS6AJnb4kJpMsw8mDxFCWQUlGjCYAHVbGGxkAA4ABhndNwXvJTNZuEyLNoUaOABHGNULnKZ8wqRnYoU3PNUo2Pi0MPC8OAARRiEHgAwUMHGSxsK2QvQh3lUeD+DAgeQKZig0DOIBibgAKuNTM9UnAAL5koA)

**Input:**
```jsx
const hello /*: forceCast */ = (a /*: any */)

```

**Output:**
```jsx
const hello /*: forceCast */ = a /*: any */;

```

**Expected behavior:**
It should keep the parentheses. (see [flow docs](https://flow.org/en/docs/types/casting/)).

**Comment by j-f1** [comment] 2018-03-21 21:21
Actually, looks like this is a duplicate of #719.

**Comment by j-f1** [comment] 2018-03-21 21:22
Duplicate of #719

**Closed** 2018-03-21 21:22 UTC
Labels: lang:flow, type:duplicate

**Comment by jacobp100** [comment] 2018-03-21 21:23
To some extent. I think the original bug was when the typecast comments weren't handled at all. But sure, probably very related!

**Comment by suchipi** [comment] 2018-03-21 21:41
We still want to fix this, but as an FYI, you can use this (ugly) workaround:
```js
const hello /*: forceCast */ = /* :: (*/a /* :: : any )*/
```
Or `/* prettier-ignore */`

**Comment by jacobp100** [comment] 2018-03-21 22:00
I went with the latter!
