### ISSUE TITLE
Parentheses around keyword unary expressions

### ISSUE THREAD

**Issue by bakkot** [prettier/prettier#746] opened 2017-02-20 02:56 UTC
It is technically correct that `!(delete a.b)` renders as `!delete a.b`, but I strongly prefer the former. Thoughts?

(This also applies to the other keyword unary expressions, like `!(await x)`.)

See also #728.

cc @vjeux.

**Comment by vjeux** [comment] 2017-02-20 02:58
@jlongster what do you think? I don't mind the lack of parenthesis and it would be consistent with the policy of removing all the parenthesis when possible, but it could be useful to make it clearer what is going on.

**Comment by jlongster** [comment] 2017-02-20 14:58
I agree that we need to choose whether or not to add parens when mixing operators. Whatever we choose though, it should be consistent across everything. Also see https://github.com/jlongster/prettier/issues/187, which we can probably dupe this on.

Currently I'm leaning to avoiding parens because it's less noisy, my gut tells me more people would prefer that, and you'll eventually learn the rules if you don't already. For example, if you typed:

```js
!(await x)
```

And then prettified the code, it would remove the parens:

```js
!await x
```

That behavior "teaches" you that it behaves the way you want without the parens. Over time this reinforces the operator precedence in your mind and it won't look as ambiguous to you. If you are reading code and not sure if it behaves the way you think, you can add parens and see if prettier will remove them. In this way you can poke with the code and let prettier teach you about it.

I'm not sure keeping parens always around helps because when you are reading the code you aren't sure if prettier added them or the author did, so you aren't sure anyway if the intended behavior is what you see (maybe someone else wrote code without prettifying and didn't notice wrong precedence order).

There are also likely many cases where adding parens when mixing operators will add them in many places that we really don't need them and most users don't want them.

Anyway, this is a long-winded way to say that we want to be consistent and I think generally it's better to avoid parens. I would be fine with some exceptions if users want to add them around a few things like mixing `!` and `await`, but I don't want to make tons of exceptions.

**Comment by vjeux** [comment] 2017-03-01 20:21
We're unlikely going to implement this suggestion, so I'm closing this issue.

**Comment by bakkot** [comment] 2017-04-27 23:05
@vjeux @jlongster I believe prettier has relaxed its stance on putting in parentheses which are technically unnecessary since this issue was closed. Any interest in revisiting this?

**Comment by vjeux** [comment] 2017-04-27 23:18
I'm indeed happy to revisit this and would accept a PR for it.

**Comment by vjeux** [comment] 2017-05-21 21:00
I'm going to merge all the parenthesis requests inside of https://github.com/prettier/prettier/issues/187 so we can have a holistic approach for them.

**Closed by vjeux** 2017-05-21 21:00 UTC
Labels: Needs discussion
