### ISSUE TITLE
Vue Custom Parser API

### ISSUE THREAD

**Issue by phamhongphuc** [prettier/prettier#5440] opened 2018-11-11 03:35 UTC
Custom Parser API works with JS but doesn't work with Vue.
**Document:** https://prettier.io/docs/en/api.html#custom-parser-api
**Environments:**
- Prettier Version: 1.15.2
- Running Prettier via: CLI
- Runtime: Node.js v8.11.2
- Operating System: Windows

**Steps to reproduce:**

**.prettierrc.js**
```js
module.exports = {
    semi: true,
    singleQuote: true,
    tabWidth: 4,
    trailingComma: 'all',
    bracketSpacing: true,
    arrowParens: 'avoid',
    printWidth: 80,
    overrides: [
        {
            files: ['*.vue'],
            options: {
                parser(text, { vue }) {
                    return vue(text);
                },
            },
        },
        {
            files: ['*.js'],
            options: {
                parser(text, { babylon }) {
                    return babylon(text);
                },
            },
        },
    ],
};
```

**Actual behavior:**
_All JS files don't throw any errors but Vue files do_
```shell
pages\index.vue

[error] pages\index.vue: Error: unknown type: "root"
[error]     at printPathNoParens (E:\Code\my.project\node_modules\prettier\bin-prettier.js:25717:13)
[error]     at Object.genericPrint [as print] (E:\Code\my.project\node_modules\prettier\bin-prettier.js:23267:28)
[error]     at callPluginPrintFunction (E:\Code\my.project\node_modules\prettier\bin-prettier.js:13502:18)
[error]     at E:\Code\my.project\node_modules\prettier\bin-prettier.js:13453:16
[error]     at Object.printComments (E:\Code\my.project\node_modules\prettier\bin-prettier.js:13187:17)
[error]     at printGenerically (E:\Code\my.project\node_modules\prettier\bin-prettier.js:13452:22)
[error]     at printAstToDoc (E:\Code\my.project\node_modules\prettier\bin-prettier.js:13464:16)
[error]     at coreFormat (E:\Code\my.project\node_modules\prettier\bin-prettier.js:13778:16)
[error]     at format (E:\Code\my.project\node_modules\prettier\bin-prettier.js:13940:16)
[error]     at formatWithCursor (E:\Code\my.project\node_modules\prettier\bin-prettier.js:13952:12)
```

**Comment by ikatyang** [comment] 2018-11-11 07:17
We currently do not support non-JavaScript custom parser, which is tracked in #3150. But there's a workaround that can do what you want:

```js
// my-plugin.js

const prettierParserVue = require("prettier/parser-html").parsers.vue;

module.exports = {
  parsers: {
    vue: Object.assign({}, prettierParserVue, {
      parse: (text, parsers, opts) => {
        return prettierParserVue.parse(text, parsers, opts);
      }
    })
  }
};
```

```sh
yarn prettier filename.vue --plugin my-plugin.js
```

**Comment by ikatyang** [comment] 2018-11-11 07:17
Duplicate of #3150

**Closed by ikatyang** 2018-11-11 07:17 UTC
