### ISSUE TITLE
JSX String Templates still break awkwardly

### ISSUE THREAD

**Issue by MadaraUchiha** [prettier/prettier#3571] opened 2017-12-25 16:03 UTC
Continuing from #3315 (or #3397 or #3368), this was fixed for variables, but is still the case with JSX props which are long string templates.

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflByp8DGGp0OA8vKHx8Nhh0anCAHgBlGAgwAGsAGRwoVO8IvPyC3DSnHmBqADpNZLTyotSnF1yC5oiqlNSAFQBPAAc4UqT27r6AUSh0AFtywbTG8Jbm3BhdUoADBPZ8ABIyyurU8qhDCbgXfAAFahwwOHwOw2pmDnxDKDkZ1Iu2OmvcaE18AAxagQCZ3CA9AC05ycqBoEyy3AoxhI+CSbGeIwAHn1qDAAQBhCCOK5cba7No1OoNNH7VZzAB8TQW+Qp+1q13q1DmLLycQA9B9MtkmVA5t4XCBxCAIX8oJpkKAHiCAO7nB4IBUoQz2CA4OhSkCGKrIIwmMwgABG1EMxRgCR6tsRyECwWldBSpuMpmlWVMeMuhmYE0MXvN0oAVposQAhG12hLHODCuBhn0y9AwHqZgBMaYtjuo-uQIBgvTgmjAVx6MENPVJMAo+pgQmQAA4AAzS+sQUwUG09Ev1itORyGtgAR3QODYgeDoaQZvTpgRLqCFu0XF0AEV0BB4PnpTBDJam3QW8gc0ebTpEUSJiGSyjDTY4PdLVql6cXEA)
```sh
--parser typescript
--trailing-comma all
```

**Input:**
```tsx
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {
if (true) {
  return <StockLink
    ticker={r.stock.ticker}
    stockType={StockTypeEnum.Stock}
    title={`See ${r.stock.name} Price Target and Stock Predictions From Top-Performing Wall Street Experts Covering ${r.stock.ticker} Stock`}
    >
      {r.stock.ticker}
    </StockLink>
  }
}
```

**Output:**
```tsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver,
}) {
  if (true) {
    return (
      <StockLink
        ticker={r.stock.ticker}
        stockType={StockTypeEnum.Stock}
        title={`See ${
          r.stock.name
        } Price Target and Stock Predictions From Top-Performing Wall Street Experts Covering ${
          r.stock.ticker
        } Stock`}
      >
        {r.stock.ticker}
      </StockLink>
    );
  }
}

```

**Expected behavior:**
Should not  break on the `title` string template.

**Comment by duailibe** [comment] 2017-12-26 02:53
Thanks for the report! This is a duplicate of #3571 (not specific to JSX at all).

**Closed by duailibe** 2017-12-26 02:53 UTC

**Comment by j-f1** [comment] 2017-12-26 03:16
@duailibe That’s this issue :)

**Comment by duailibe** [comment] 2017-12-26 03:19
@j-f1 oops! Thanks for catching
