### ISSUE TITLE
Double arrow function with comma operator dissolves parentheses

### ISSUE THREAD

**Issue by spenceryue** [prettier/prettier#11041] opened 2021-06-08 06:09 UTC
**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTACgDMoBKfAPiIA8K9qSpC6AaTOgbhFZAgAcYAS3TJQ2AE4SIAdwAKkhGmQhsAGxnYAnst4AjCdjABrODADK-I0KgBzZDAkBXOLzgBbPXAAm3nwBlsOydsWzgAMQgJd2wYYTsVbCcYCB4QAAsYdzUAdXSheDQrMDhzJQKhADcCrRUwNF0QGzQ4CRg5Q1sY5GJ1Ft4AKzQaACFDEzNzbHc4fxs4Hr7XECGacxtbNTgARScIeEW1fpArCRaJFRgtfjg0MAkhQTT+B9gcoW8YdOQADgAGXgvCAtHKGfgqF63VqVBa8ACOe3gHQEyhQ2DQAFooHAfD40hI4AihASOqFukhekdli13EIHM5qRstrt9gsKUteDBsHp3p9vkgAEycwxCNQbADCEHc5JAtwArGknC0ACrc1GU46VFwASSgflg5nujxgAEE9eYrltDi0AL42oA)

```sh
--parser typescript
```

**Input:**

```tsx
const a = (fn) => (x) => (fn(x), x);
```

**Output:**

```tsx
const a = (fn) => (x) => fn(x), x;

```

**Expected behavior:**
```tsx
const a = (fn) => (x) => (fn(x), x);

```

**Comment by thorn0** [comment] 2021-06-08 13:11
Duplicate of #10955

**Closed** 2021-06-08 13:11 UTC
Labels: type:duplicate
