### ISSUE TITLE
Swapping `(` and comment breaks flow parsing

### ISSUE THREAD

**Issue by zyklus** [prettier/prettier#2977] opened 2017-10-05 03:28 UTC
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22async%20function%20gen%20%2F*%3A%3A%20%3CT%3E*%2F(promise%20%2F*%3A%20Promise%3CT%3E*%2F)%20%2F*%3A%20Promise%3C%5B%3FError%2C%20%3FT%5D%3E*%2F%20%7B%5Cn%20%20try%20%7B%5Cn%20%20%20%20return%20%5Bnull%2C%20await%20promise%5D%3B%5Cn%20%20%7D%20catch%20(err)%20%7B%5Cn%20%20%20%20return%20%5Berr%2C%20null%5D%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%2C%22output2%22%3Afalse%7D%7D)

**Input:**
```jsx
async function gen /*:: <T>*/(promise /*: Promise<T>*/) /*: Promise<[?Error, ?T]>*/ {
  try {
    return [null, await promise];
  } catch (err) {
    return [err, null];
  }
}
```

**Output:**
```jsx
async function gen(
  /*:: <T>*/ promise /*: Promise<T>*/
) /*: Promise<[?Error, ?T]>*/ {
  try {
    return [null, await promise];
  } catch (err) {
    return [err, null];
  }
}

```

**Expected behavior:**

The above is a comment-annotated function generated by flow.  Notice that the prettier output swaps the `(` and the first comment.  This breaks flow's parsing of the annotations.

**Comment by azz** [comment] 2017-10-05 03:40
Minimal repo:

**Prettier 1.7.2**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22function%20f%20%2F*%20comment*%2F(promise)%20%7B%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
function f /* comment*/(promise) {}
```

**Output:**
```jsx
function f(/* comment*/ promise) {}

```

**Comment by azz** [comment] 2017-10-05 03:41
Actually this is a duplicate of #2808, merging it in there.

**Closed by azz** 2017-10-05 03:41 UTC
Labels: area:comments, lang:javascript, type:bug
