### ISSUE TITLE
Incremental non-determinism for jsdoc bracketing

### ISSUE THREAD

**Issue by SMotaal** [prettier/prettier#7050] opened 2019-11-25 10:59 UTC
I'm sorry, but I am really overwhelmed at the moment and that's the best I can do to get this on your radar.

## Setup

<details>

**Visual Studio Code**

```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
```

**Prettier - Code formatter `3.9.0`**

```
Name: Prettier - Code formatter
Id: esbenp.prettier-vscode
Description: Code formatter using prettier
Version: 3.9.0
Publisher: Esben Petersen
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
```

**`.prettierrc`**

```json
"@smotaal.io/tools/prettier.config"
```

**`@smotaal.io/tools/prettier.config/.prettierrc.json` <kbd>package.main</kbd>**

```json
{
  "semi": true,
  "arrowParens": "avoid",
  "printWidth": 120,
  "singleQuote": true,
  "trailingComma": "all",
  "bracketSpacing": false,
  "jsxBracketSameLine": true,
  "endOfLine": "lf",
  "tabWidth": 2,
  "useTabs": false
}
```

</details>

## Presentation

1. Given the following code fragment in `Untitled-1` <kbd>js</kbd>:

   ```js
   typeof /** @type {typeof Matcher} */ (matcher.constructor).clone !== 'function'
   ```

2. Executing **Format Document** once, rewrites it as:

   ```js
   typeof (/** @type {typeof Matcher} */ (matcher.constructor).clone) !==
     "function";
   ```

3. Executing **Format Document** again, as:

   ```js
   typeof (/** @type {typeof Matcher} */ (matcher.constructor.clone)) !==
     "function";
   ```

## Synopsis

Deterministic rewrite can be defined as a rewrite for which the generated output remains intact when subsequently processed by the generator for that output.

Incremental non-determinism is when the output of the rewriter is subsequently altered by the same generator.

It is expected that all features of prettier must include testing where the output must not change when run a second time under the same configuration.

How this bug has not made it through with templates is probably why I decided to not follow it.

Thanks  🙏

**Comment by thorn0** [comment] 2019-11-25 11:57
A simplified bug report:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOEBmACAegCoi8ABdLPYS7fAWQEMYwALOAJwF88iC8AFAFtmbTgDpIUAM4wOAVzAwIHAJSSANtDh4AhAF59eAOQ55UJQEtoxkABoQEDDGszkoRhw4QA7gAVPBGlkEEYANwhLABN7EAAjDkYwAGs4GABlDCTLKABzZDl5OAdWGCENAHVWS3hpLLA4dKCayzCatBCwaWCHHOlOGD9E3JFkHEYNfocAK2kADwAhRJS09MYhOAAZHLgxiamQWbn0nNyNOABFeQh4PcnikCyOfo4QuMY4uA1YjA4cmAq0RgrGQAA4AAwOX4QfoVRIYEK-OAvMK7BwAR2u8CGTmCKEY0gAtFA4HAomTYhw4JjLFShowRow7gd+kJLAUFA9pKdzlcbrskON7g4YB9AVFgcgAEwixKWDSnADCECEoxQUG0sXk-QAKh88UKDmEigBJKDk2DpMB-ZwAQXN6XQ52ZcC4XCAA)
```sh
--parser babel
```

**Input:**
```jsx
typeof /** @type {typeof Matcher} */ (matcher.constructor).clone !== 'function'
```

**Output:**
```jsx
typeof (/** @type {typeof Matcher} */ (matcher.constructor).clone) !==
  "function";

```

**Second Output:**
```jsx
typeof (/** @type {typeof Matcher} */ (matcher.constructor.clone)) !==
  "function";

```

**Comment by SMotaal** [comment] 2019-11-25 12:00
Hey… worth mentioning, this mojo prevents it somehow:

```js
'function' !== typeof (/** @type {typeof Matcher} */ (matcher.constructor).clone) // prettier-ignore
```

**Comment by thorn0** [comment] 2019-11-25 13:01
Seems to have been caused by https://github.com/prettier/prettier/pull/6217

**Comment by thorn0** [comment] 2019-11-26 11:21
Duplicate of #6122

**Closed by thorn0** 2019-11-26 11:21 UTC
Labels: area:idempotency, lang:javascript

**Comment by SMotaal** [comment] 2019-11-26 12:15
@thorn0 I just want to reiterate, this is **not just** about babel doing something different, this is about prettier doing the same thing differently the second time.

1. write code
2. format => new code (okay-ish)
3. format => new new code (not okay at all)

No tools involved, all in vs code with <kbd>option</kbd>+<kbd>shift</kbd>+<kbd>F</kbd>.

There is no amount of AST variance that would lead to non-determinism that would not be covered by test cases.

Sorry to mumble 👍

**Comment by thorn0** [comment] 2019-11-26 12:23
Correctness first, then idempotence.

**Comment by SMotaal** [comment] 2019-11-26 12:51
Sure, so maybe incremental testing can help avoid such regressions.

**Comment by SMotaal** [comment] 2019-11-26 13:01
@thorn0 Please note, I agree with your statement, but honestly don't feel like the feedback I am giving has managed to outline my concerns moving forward.

These kind of secondary effects are screaming of future bugs.

Can you please consider that, maybe share your thoughts about my concerns. Sorry, but finding a linting problem in code you barely worked on that day is something of a nightmare to track.

**Comment by thorn0** [comment] 2019-11-26 13:41
We already [have such tests](https://github.com/prettier/prettier/blob/1.19.1/tests_config/run_spec.js#L109-L114). All the code samples in `tests` are run through it if you run `AST_COMPARE=1 jest` and that's how it's run on CI.

**Comment by thorn0** [comment] 2019-11-26 13:57
I thought we had such tests, but turns out we don't. Discussed here: https://github.com/prettier/prettier/issues/3512#issuecomment-352622275

A new issue should be opened about adding such tests I think.

**Comment by SMotaal** [comment] 2019-11-26 14:00
I appreciate digging, because from my end, I have been working on this project with the same prettier settings (ie only moved the `.prettierrc.json` itself but intact) for more than a year.

So while `May 14` #6122 happens to overlap in some grammar aspects, the fact that the more critical aspect of this issue that is not even covered there that made me file this issue only occured after my last `yarn` update (ie new prettier) freaked me out… I only open few issues but really go above and beyond to make sure we are hitting something that can often be of future significance.

I do that because I struggle personally when tools regress and so I only keep absolute minimum (only `rollup` and `prettier` actually every touch actual code).

**Comment by thorn0** [comment] 2019-11-26 14:02
If you look at [this label](https://github.com/prettier/prettier/labels/area%3Aidempotency) you'll see that unfortunately we have quite a few issues like this, mostly related to comments. So in this aspect, this issue is not that unique as I'd prefer it to be.

**Comment by SMotaal** [comment] 2019-11-26 14:02
> A new issue should be opened about adding such tests I think.

I can give more input there, but I am not sure I can do a good job communicating with good project-relevant emphasis… May be if you suggest title/summary or catch me when I open it so I don't end up making another mess articulating 😅

**Comment by SMotaal** [comment] 2019-11-26 14:05
But can we at least edit out:

> <del>Duplicate of #6122</del>

I fear this really misses the point and makes it seem like an old issue when it is fresh of the awesome efforts of someone on the team who might be interested to handle it while things are on their mind… fair?

**Comment by SMotaal** [comment] 2019-11-26 14:07
@thorn0 I really appreciate your help, and fully relate on parsing-related mindbenders — it's been all I've been doing for a long time.

Thank you ❤️

**Comment by thorn0** [comment] 2019-11-26 14:18
> But can we at least edit out:

Nope. We really have just two separate issues here: #6122 and #7055, which I've just opened.

**Comment by SMotaal** [comment] 2019-11-26 14:25
Okay, this way I can move on from this one 👍

**Comment by evilebottnawi** [comment] 2019-11-26 14:30
@thorn0 hm, why reopen? It is really same problem https://github.com/prettier/prettier/issues/6122

**Comment by thorn0** [comment] 2019-11-26 14:33
@evilebottnawi That's what I wrote.

**Comment by evilebottnawi** [comment] 2019-11-26 14:46
@thorn0 oh, yes, I looked wrong place :smile: , everything is fine
