### ISSUE TITLE
Multiline text got indented

### ISSUE THREAD

**Issue by mariotsi** [prettier/prettier#2587] opened 2017-08-03 12:48 UTC
This code is arelady passed through Prettier:
```javascript
reply(request.params.owner)
  .header("access-control-allow-origin", "*")
  .header("access-control-allow-methods", "POST, OPTIONS")
  .header(
    "access-control-allow-headers",
    "content-type, customdata, kid, msprdrm_server_exception_compat, " +
      "msprdrm_server_redirect_compat, soapaction, cache-control, pragma, " +
      "x-requested-with, Authorization, " +
      "X-Requested-At, X-Requesting-Version, " +
      "x-forwarded-for"
  )
  .header("access-control-allow-credentials", "true")
  .header("access-control-expose-headers", "customdata,errorcode")
  .header("sequoia-owner", request.params.owner)
```

I cannot understand why the line starting with "msprdrm_server... and the following is getting indented. I thought it should be like this:
```javascript
reply(request.params.owner)
  .header("access-control-allow-origin", "*")
  .header("access-control-allow-methods", "POST, OPTIONS")
  .header(
    "access-control-allow-headers",
    "content-type, customdata, kid, msprdrm_server_exception_compat, " +
    "msprdrm_server_redirect_compat, soapaction, cache-control, pragma, " +
    "x-requested-with, Authorization, " +
    "X-Requested-At, X-Requesting-Version, " +
    "x-forwarded-for"
  )
  .header("access-control-allow-credentials", "true")
  .header("access-control-expose-headers", "customdata,errorcode")
  .header("sequoia-owner", request.params.owner)
```

**Comment by josephfrazier** [comment] 2017-08-03 14:22
This seems to be a duplicate of https://github.com/prettier/prettier/issues/869 and https://github.com/prettier/prettier/issues/2235

**Closed by josephfrazier** 2017-08-03 14:22 UTC
