### ISSUE TITLE
Did prettier remove the indentation of multi-line strings in the mdx file because of eslint?

### ISSUE THREAD

**Issue by shervinchen** [prettier/prettier#14986] opened 2023-06-28 15:43 UTC
When I run "prettier --write ." I find that the indentation is removed from the multi-line strings in the mdx file, is there a way to fix this problem? I'm not sure if it's due to eslint or prettier configuration

![Xnip2023-06-28_13-23-18](https://github.com/prettier/prettier/assets/9639671/0a3916a4-122d-4c7d-b29b-ff909eb0b916)
![Xnip2023-06-28_13-23-31](https://github.com/prettier/prettier/assets/9639671/15a15c6e-a088-4abc-8f22-203c9e12edce)
![Xnip2023-06-28_13-23-43](https://github.com/prettier/prettier/assets/9639671/58f59872-9ace-4382-8053-a4fb49bebe75)

**Comment by kachkaev** [comment] 2023-06-29 00:06
👋 @shervinchen! Please use the [issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md?plain=1) to describe the bug. 

You probably face one of the problems that is related to MDX 1  / MDX 2 support (https://github.com/prettier/prettier/issues/12209). I guess it’s a duplicate of https://github.com/prettier/prettier/issues/5795. You can scan for issues tagged with https://github.com/prettier/prettier/labels/lang%3Amdx for more examples. If you believe that this issue is different from the ones that are already open, please let me know and we’ll look closer into it. I will close this one as a duplicate for now.

**Closed by kachkaev** 2023-06-29 00:06 UTC
