### ISSUE TITLE
Prettier removes blank line before statement with leading semicolon

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#3549] opened 2017-12-22 00:27 UTC
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHATgHSngbgG0BdEAGhAgxgEtoBnZUAQyywgHcAFNhJlCwBuEWgBMKIFgxjIAZiwA2DOJQBGWFmADWcGAGUMW2lADmyGFgCuqkGIhh5SlZRMqsMbptMBbFk+VbACsGNAAhTR09fRYfOAAZEzgAlyorGAx0gCYU2yMsd2QQNRY1AE9FaElsExgAdXEYAAtkAA4ABkpsCBU6zQwi7Dh3IWTKLDgARytaCa8WX38kBUDKFR9aXLWTU0U4AEUrCHgtkBhShrFm5CzKSxZaRR2AYQgfPyKoaDGQKxUAFVKAhWKgAvqCgA)
```sh
--no-semi
```

**Input:**
```js
expr

;[]
```

**Output:**
```js
expr
;[]

```

**Expected behavior:**

```js
expr

;[]
```

**Comment by bakkot** [comment] 2017-12-23 18:27
I believe this is a duplicate of #1510. (It turns out to be hard to fix this.)

**Closed by bakkot** 2017-12-23 18:27 UTC
Labels: lang:javascript, type:bug
