### ISSUE TITLE
Doesn't handle Promise<void> with Flow

### ISSUE THREAD

**Issue by dijonkitchen** [prettier/prettier#3160] opened 2017-11-06 23:04 UTC
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnCBXeqB0BzOGACgHIB6EgGgAIBDAZwE8oxqjU4BHJOqRmjvR60+NKHAAeMHgDlJMAGIYWMAJbQAlDwAK6ALar6cADwA3CKoAmAPmoBeW8AC+GkJRAQADmuj1koBhhkADNaABsjdwAjVFowAGtCAGVPONUoPGQYVAw4d0sIMBDwyJAAK3oJACFYhOTaPTgAGXS4Yoi8jyxPLAAmdtLU1CNUZBAo2ijGMOg3EE9UdJgAdSsYAAtkAA4ABncjAyyczvp0vDC4AEUMCHgBzphJ1csN5F73bNpVMLOAYQg9HpaGMoNA2u4MEYACqTPxIUIdJxOIA)

**Input:**
```jsx
router.get('/', async (req: any, res: any, next: NextFunction): Promise<void> => {})
```

**Output:**
```jsx
router.get("/", async (req: any, res: any, next: NextFunction): Promise<
  void
> => {});

```

**Expected behavior:**
Keep `Promise<void>` on same line.

**Comment by suchipi** [comment] 2017-11-06 23:09
Thanks for the report. I'm closing as this is a duplicate of https://github.com/prettier/prettier/issues/1825.

**Closed by suchipi** 2017-11-06 23:09 UTC
