### ISSUE TITLE
markdown formatter issue with some links

### ISSUE THREAD

**Issue by gre** [prettier/prettier#3890] opened 2018-02-05 08:12 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAnhAugCgBYwwAOSA9KQOYQQUA2cAdJALYD8AhgLwCMAZGAFcATkIRh0nAAwBKEABoQEIjACW0AM7JQRIStgB1FQBMYeZAA5JCmOwBGhk2aQAmBer104ARQER4yADN2WnU4ayF2FVoPAGEIZmZ2ZBAoaDh5EFsIsABrOBgAZSJ2MA9kGCEBMJAAK3UADwAhbLzC9mY4ABk9dKQgkOrioVChZMShHKMIAHcoDNDmFXLK6oFQgBU7TT7g0IU9EZgABQiKRMDd6tEARwEVURP2M6SdgYUdCFD9CKJknTgRgA3dIKdgiGZHMEIbYgdiAiDGDJTMAXN6w9QwVF7RQCYi45xYuAAXyJQA)
```sh
--parser markdown
```

**Input:**
```markdown
[yo](http://google.com?a=1&currency=0)
```

**Output:**
```markdown
[yo](http://google.com?a=1¤cy=0)

```

**Expected behavior:**

it should stay as

```markdown
[yo](http://google.com?a=1&currency=0)
```

**Comment by ikatyang** [comment] 2018-02-05 08:14
Hi, this is a duplicate of #3470, and it should be fixed by #3780.

---

**Prettier pr-3780**
[Playground link](https://deploy-preview-3780--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBtAnhAugCgBYwwAOSA9KQOYQQUA2cAdJALYD8AhgLwCMAZGAFcATkIRh0nAAwBKEABoQEIjACW0AM7JQRIStgB1FQBMYeZAA5JCmOwBGhk2aQAmBer104ARQER4yADN2WnU4ayF2FVoPAGEIZmZ2ZBAoaDh5EFsIsABrOBgAZSJ2MA9kGCEBMJAAK3UADwAhbLzC9mY4ABk9dKQgkOrioVChZMShHKMIAHcoDNDmFXLK6oFQgBU7TT7g0IU9EZgABQiKRMDd6tEARwEVURP2M6SdgYUdCFD9CKJknTgRgA3dIKdgiGZHMEIbYgdiAiDGDJTMAXN6w9QwVF7RQCYi45xYuAAXyJQA)
```sh
--parser markdown
```

**Input:**
```markdown
[yo](http://google.com?a=1&currency=0)
```

**Output:**
```markdown
[yo](http://google.com?a=1&currency=0)

```

**Closed by ikatyang** 2018-02-05 08:14 UTC

**Comment by azz** [comment] 2018-02-05 08:15
**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAugCgGRgK4BOBCYAlADpQY4DmMFUIANCBAA4wCW0AzsqAEMiEAO4AFIQj4oBANwicAJsxACeMZADMBAGx5wWAIwICwAazgwAym1OcoNZDAJ4DIRRDBbd+lvf0EMGImNAC2At56bgBWPAAeAEIm5pZWAqFwADL2cJG+rHgwbIUATHlutgQByCDhBGYeIowsbAT2MADqSjAAFsgAHAAMLQQQ+h0mbDWtcAGyuSzEAI54nMTBAmERSNpRLPqhnE4ubjz2NDpwAIp4EPDlLDAChl2KvcgljyacOucAwhBQuEalBoAsQHh9AAVZ7SXb6AC+CKAA)
```sh
--parser markdown
```

**Input:**
```markdown
[](&currenc)
[](&gt)

```

**Output:**
```markdown
[](¤c)
[](>)

```

**Comment by gre** [comment] 2018-02-05 08:15
oh ok, thanks
