### ISSUE TITLE
1.13 breaks Vue / Default parser removal should be breaking change.

### ISSUE THREAD

**Issue by pwang2** [prettier/prettier#4567] opened 2018-05-27 19:04 UTC
> **UPDATE**: Anyone experiencing this from `vue-cli`, please run:
> ```
> npm update --depth=9999 @vue/component-compiler-utils
> ```
> OR `vue-loader`, it is fixed in `vue-loader@13.7.2` and `vue-loader@14.2.3`.
>
> Also, relevant StackOverflow question: https://stackoverflow.com/q/50555953/2010616

**Prettier 1.13.0**

The removal of default parser in 1.13 breaks some tools relied on the default behavior. 
https://github.com/vuejs/component-compiler-utils/blob/8a8a95c84dc2f3f14625e31805f975d11a898990/lib/compileTemplate.ts#L161

**Expected behavior:**
This change should be flagged as obsoleted instead of removal or mark this as breaking change instead.

**Comment by suchipi** [comment] 2018-05-27 19:33
Sorry, we committed the age-old semver sin- we knew this was a breaking change, but because it would only affect a subset of our users, we didn't bump the major version, because we didn't want to create friction for our users to upgrade.

To get the old behavior, add `parser: "babylon"`. You may also want to lock prettier to a specific version in your package.json.

**Comment by pwang2** [comment] 2018-05-27 19:44
No worry and thanks for the quick response. We always commit some type of sin especially we don't know how and when and to whom the karma will result.  

This could be a minor change as the API in respect of a CLI tool should be the cli args the document literally described.  But the community members will always add exceptions of the usage scenario.

I have send a PR to add this to the tool I mentioned above.

**Comment by clementvp** [comment] 2018-05-27 19:59
Yes issue is confirmed with the Vue-cli. The change to version 13 completely break the dev compilation of the Vue CLI.

**Comment by naknode** [comment] 2018-05-27 20:31
Right now, this is breaking a fresh, default Laravel project. Just tried it and got same error.

**Comment by counterbeing** [comment] 2018-05-27 20:43
@suchipi Where do you define the parser in your project to get that default behavior?

**Comment by duailibe** [comment] 2018-05-27 20:57
@counterbeing In a configuration file: https://prettier.io/docs/en/configuration.html

**Comment by pwang2** [comment] 2018-05-28 03:57
new version of @vue/component-compiler-utils release.  
https://github.com/vuejs/component-compiler-utils/issues/14#issuecomment-392412338

Close issue here.

**Comment by duailibe** [comment] 2018-05-28 04:00
@pwang2 Thank you for understanding and sorry for the trouble ❤️

**Comment by lafeer** [comment] 2018-05-28 08:59
npm i prettier@~1.12.0 didn't do anything for me

new version of @vue/component-compiler-utils release means i don't need to do anything to get it working againg?

**Comment by HYordanov** [comment] 2018-05-28 09:10
prettier 1.12.0 was added, parser of prettier was changed to be 'babylon'. Tried with prettier 1.12.1.. Nothing has changed, the error is still there and I'm not able to build brand new project. Is there anything else that has to be done in order to build properly? Project is vue&nuxt one.

**Comment by lydell** [comment] 2018-05-28 16:30
Re-opening to make this easier to find for people

Labeling with awaiting response so it will be auto-closed in case we forget.

**Comment by fbartho** [comment] 2018-05-28 18:19
I came looking for this issue, as this change broke prettier-formatting of my repo's `package.json` -- We have spaces to group different scripts in the JSON file, and auto-formatting was stripping these spacings, and otherwise re-formatting the file in a painful way.

**Comment by lydell** [comment] 2018-05-28 18:40
Adding `"parser": "whatever"` at top level in `.prettierrc` is a really bad idea since it effectively tells Prettier to use the `whatever` parser for _all_ files, disabling the auto-detection based on file extension.

package.json always contains code that is valid JSON but invalid JS so that’s why you get that error.

**Comment by fbartho** [comment] 2018-05-28 19:19
@lydell That makes a lot of sense, thanks. -- Is there a different workaround that restores the expected prettier formatting + blank-line-preservation for our `package.json`?

**Comment by lydell** [comment] 2018-05-28 19:54
@fbartho What command are you running?

**Comment by fbartho** [comment] 2018-05-28 19:57
`yarn prettier --write package.json` or VSCode's automatic format-on-save functionality hooked up with the prettier VSCode plugin. (Both ways exhibit same behavior with prettier `1.13.x`)

**Comment by duailibe** [comment] 2018-05-28 20:07
@fbartho That's unrelated.. can you open a separate issue please?

**Comment by azz** [comment] 2018-05-28 22:17
@fbartho in `.prettierrc`, try:
```json
{
  "overrides": [{
    "files": "package.json",
    "options": { "parser": "json" }
  }]
}
```

**Comment by ForsakenHarmony** [comment] 2018-05-29 00:31
a breaking change is a breaking change and should always be handled as such even if it only affects a small portion of the userbase

**Closed** 2018-05-29 05:43 UTC
Labels: area:api, area:cli, status:awaiting response, type:question

**Comment by lydell** [comment] 2018-05-29 06:18
**UPDATE:** 1.13.1 has be released, which changed the error to a warning. :tada:

Try updating/reinstalling!

**Comment by HYordanov** [comment] 2018-05-29 12:45
The error is fixed (temporarily in 1.13.1+) but still there is an issue (warning) with the parser as I see. How can we specify a different parser or filepath? Please someone with more experience in those kind of issues explain what should be done to prevent another build errors in the future.

**Comment by azz** [comment] 2018-05-29 12:49
You need to go to the repositories using the Prettier API and get them to add `parser: "babylon"` or better: pass the file path. `vue-cli` and `vue-loader` have been patched, but there's probably more in the wild.

**Comment by KarolMilewski** [comment] 2018-06-11 09:01
if you use vuejs try upgrade vue-loader `vue-loader@15.2.4`,  and add on webpack.config new plugin `VueLoaderPlugin`
