### ISSUE TITLE
TSUnionType and TSIntersectionType have different formatting.

### ISSUE THREAD

**Issue by denbezrukov** [prettier/prettier#13444] opened 2022-09-08 08:12 UTC
Hi! Thank you for your work. I'm wondering why `TSUnionType` and `TSIntersectionType` have different formatting. 

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAkrOAJwGc4wYBLabAXm3oDJsBBVt9jz5gHSkewBCQ4SNFiBvfgGEZsufIVTJ2JgBF1GzVu2qA3L17os2AKpQqfOvQA+LLvc7Lb4l+KfZFnxe52+dukAAaEAgMSmhiZFAAQ0JCCAB3AAVYhEiUaIAbBOi0SOCAI0JosABrOBgAZWiAWzgAGQooOGQAMyzSQuKyisqMEqaAc2QYQgBXOGC4GoK4ABM5+froqEGx6MG4ADEIQhromEpV5BBosZgIIJAACxgazIB1a4p4Yn6wOEq0l4oANxe0CcwMR8iAmqRCDAksVBvs2h1JiAAFbEAAelSGmTgAEUxhB4PDMp0QP0SEQTkY4MQwIQKGErhhabAHhQ5jBrsgABwABmCjIgpAexQwJ0ZVKIvxawQAjnj4NDQulTsQALTNebzK6EOCyija6EbOFIdpExGkGoUEbjM2YnFylrGhHBGDRAostkcpAAJmdxQomSGUggNSNICpAFYrmNSAAVV3pE3E34TfCLWCVGl0mDMKBzSroLGE0gAX2LQA)

```sh
--parser typescript
```

**Input:**

```tsx
type Intersection =   & AAAAAAAAAAAAAAAAAAAAAA
  & BBBBBBBBBBBBBBBBBBBBBB
  & CCCCCCCCCCCCCCCCCCCCCC
  & DDDDDDDDDDDDDDDDDDDDDD;

type Union =   | AAAAAAAAAAAAAAAAAAAAAA
  | BBBBBBBBBBBBBBBBBBBBBB
  | CCCCCCCCCCCCCCCCCCCCCC
  | DDDDDDDDDDDDDDDDDDDDDD;
```

**Output:**

```tsx
type Intersection = AAAAAAAAAAAAAAAAAAAAAA &
  BBBBBBBBBBBBBBBBBBBBBB &
  CCCCCCCCCCCCCCCCCCCCCC &
  DDDDDDDDDDDDDDDDDDDDDD;

type Union =
  | AAAAAAAAAAAAAAAAAAAAAA
  | BBBBBBBBBBBBBBBBBBBBBB
  | CCCCCCCCCCCCCCCCCCCCCC
  | DDDDDDDDDDDDDDDDDDDDDD;

```

**Expected behavior:**
Should `TSIntersectionType` have the same formatting as `TSUnionType`?

**Comment by thorn0** [comment] 2022-09-08 08:45
Duplicate of #3986

**Closed** 2022-09-08 08:45 UTC
Labels: type:duplicate
