### ISSUE TITLE
`typeof list[number]` breaks after formatting with prettier

### ISSUE THREAD

**Issue by Shaddix** [prettier/prettier#16030] opened 2024-02-04 05:26 UTC
**Prettier 3.2.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAbAlhzAXkwG0ByAQzQBMyAaTMgRwHc4yBdTKzSKDANwAdWAE8ADnEy54AWzRFMMCXAgAzHPhgkoAV1kAjOACcOwqCDogI4mLnTJQFY8YgsACs4RpkICthYKUR8rA2MKMABrOBgAZQpZOAAZXCg4ZDV-NDhQ8KiY2PEI1IBzZBhjXRyQbNlccsrquAAPSWNcRNh-ABUTKGdcOB8kTOxsqzRS7DgARV0IeAys6oArNGbYqdn5xZHlqyYduHdXcWG-NABaNLhqW8sQCopcPCgSgGEIWVkKX39sB6TN7TACCMAquAMung7hMKTSSzG1QAFjBZNgAOrImRDIpgOCxbwyXAANxkol8YDQIRAJKqAEkoHdYLEwO1bCCmbFlNNEeMQOJXNkMeFxL5BUMTCT0lZUtljDAThQSj8+dUisZ5b5lJI0GzcLYHoLUjAMbhqDBkcgABwABisxjgh1wjqVKt+eyRVhgFAMZotVqQACYrLpst1fcNRvy4IZbndqEkKG9dMq4AAxCDGH7g0p-aEQEAAXyLQA)

```sh
--parser typescript
```

**Input:**

```tsx
const list = ['asd', 'qwe'] as const;
type items = typeof list[number];

```

**Output:**

```tsx
const list = ["asd", "qwe"] as const;
type items = (typeof list)[number];

```

**Expected output:**

```tsx
const list = ['asd', 'qwe'] as const;
type items = typeof list[number];
```

**Why?**
Because `typeof list[number]` and `(typeof list)[number]` mean different things in Typescript (so prettier actually breaks the code). [Stackoverflow](https://stackoverflow.com/a/55505556/291695) reference

**Comment by fisker** [comment] 2024-02-04 05:38
Duplicate of #14990

**Closed** 2024-02-04 05:38 UTC
Labels: type:duplicate
