### ISSUE TITLE
Add support for admonitions

### ISSUE THREAD

**Issue by ctaintor** [prettier/prettier#9154] opened 2020-09-05 11:42 UTC
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZSlQvAOlA6hAVwBsATKAchgAIBLagIziqhrCZoDMqBDEgW2h0a0AM5UA7nABOTEQQAO8iFPgkqAAwCecEQB8M6gPw40SHCAA0ICPJjCoI5KG5SpEcQAUXCRym5Fxbk1HK3opbjAAazgYAGV5CJooAHNkGCkCOCs4PkYSEjgSABluFIJuZLgAMWU+bhg7FOQQbgIYCEsQAAsYPiJcLrodBLZYnyEANzpNZrAREJAkkWkYD3DkuuQOf2WrACsRAA8AIXComNjuPjgipLgtnayQA8PYpOSiOABFAkx7pG2RF2IASUmWUmadSkkRI7ignXkUiSMFwNBIMC6yAAHAAGKyIiDLXDheTNfyBYKdACOv3gaxsvhaIgAtFA4IVCp0ZDSaDI1hVNgDHlZlnwaGkMk8RO9Pj8-g8gU8YNx6Kj0ZikAAmKzpbg0IjvADCED4gpAOgArJ0CMsACoq3yA4ETTIASSgBVgsTASNsAEEPbEYJpPgrlgBfcNAA)
```sh
--parser markdown
--prose-wrap always
```

**Input:**
```markdown
:::note
Wouldn't it be nice if admonitions were supported `yes|no`?
:::

```

**Output:**
```markdown
:::note Wouldn't it be nice if admonitions were supported `yes|no`? :::

```

**Expected behavior:**
I'd expect this to preserve the first line and last line of the block. I know this isn't working because admonitions is an extension of Markdown so I'm wondering if support for this could be added to Prettier. [remark-admonitions](https://www.npmjs.com/package/remark-admonitions) is a remark plugin for this and it is included by default in Docusaurus. There was a ticket about this previously (#3362) but it seemed like part of the reason it wouldn't be supported then was due to a lack of a remark plugin.

I tried working on a patch to prettier to support this but ran into trouble with remark-admonition since prettier would get an `admonitionHTML` element. Something tells me that the way that remark-admonition works will need to be modified to work with Prettier but I'm not familiar with remark plugins.

**Comment by kachkaev** [comment] 2020-09-05 12:31
Not sure how likely this special case would be added to Prettier, but as a workaround, you might be able to use two trailing spaces:

```markdown
:::note{space}{space}
Wouldn't it be nice if admonitions were supported `yes|no`?{space}{space}
:::
```

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZSlQvABFgOlAdQgFcAbAEygHIYsBLWgIziyjrBboDMsBDcgLbQGdaAGcsAdzgAnFmOIAHRRBnxyWAAYBPOGIA+GTQH4c+NEnwgANCAiKYoqGOSheMmREkAFdwhcovKSSvNoutowyvGAA1nAwAMqK0XRQAObIMDLEcLZwAszk5HDkADK86cS8aXAAYqoCvDCO6cggvMQwEDYgABYwAqQEvQx6yRwJ-iIAbgzabWBi4SCpYrIw3lFpjchcQWu2AFZiAB4AQlGx8Qm8AnClqXC7+7kgxycJqWmkcACKxJgnkg9qQDiBkjI1jI2o0ZDFyF4oD1FDJUjACHRyDBesgABwABlsKIgawIUUUbSCITCPQAjgD4Jt7AF2mIALRQOAlEo9OT0uhyTbVHbAl62NYCOiZbKvMRfH7-QHPUGvGC8RgYrE4pAAJlsWV4dFIXwAwhABCKQHoAKw9YhrAAq6oCILB0xyAEkoMVYAkwKiHABBb0JGDaH7KtYAXyjQA)

**Comment by pawamoy** [comment] 2020-09-05 12:58
Ah funny, I came here to open this issue as well.

I'm writing admonitions in Markdown as well, though it seems we have different syntaxes (I'm using Python Markdown and extensions):

```
::: note
    Wouldn't it be nice if admonitions were supported `yes|no`?
    Multiple lines allowed.
```

In my case, I can add two spaces after `::: note`, but even if I also add them at the end of each line of the body, they still get dedented.

**Comment by ctaintor** [comment] 2020-09-05 13:09
Thanks for the tip on 2 spaces! At least from the examples I have tried in my site so far, that seems to work and is preferable to `<!-- prettier-ignore -->` since it will correctly format.

@pawamoy - looks like there are many different ways that people have decided to do admonitions. I believe that the remark plugin only supports the explicit opening and closing tokens. I assume that it is removing your indentation since prettier would expect a blank newline above the indented stuff. e.g.

```
::: note

    Wouldn't it be nice if admonitions were supported `yes|no`?
    Multiple lines allowed.
```

I don't have mkdocs in front of me set up but I assume that that wouldn't get treated as an admonition? (prettier will [remove](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZSkAIoXu9AdKXXAo9AdQgFcAbAEygHIZ0BLZgIzkxbC5YDN0AQ1oBbaGxbQAzugDucAE5dplAA5qIi+LXQADAJ5xpAHyx6A-CSIBZGjBZrqXaiyjHh1ahAW0AdCAANCAQag4yyKBCioo+AArRCNLIIELUckIGycHsikJgANZwMADKavluAObIMIqUcMFwopy0tHC0ADJCUJWUQpVwAGJaokIwDj0pQpQwEEEgABYwotRkC2zG5bwlSZIAbmwGKWDS2SBu0kowcXmVo8j8aZfBAFbSAB4AQnmFxSVCojgHTccAeTwaIDe7xKVWcAEVKNhQUhHtRniByopLooUqNFAVaD4oPM1Io3DAyCxaDAFsgABwABmCpIglzIeTUU3SmTOAEdEfAbqFkighNIALTudrtebKfksZQ3fr3FHg4KXUQsGp1CHSWFwBFIsFoiEwITsSnU2lIABMwVqQhYrh6AGEIKIVSBjABWeaUS4AFXNItR6L29QAklA2rASmAyWEAILRkowAzOY2XAC+WaAA) four spaces if you were to add them on that newline)

**Comment by pawamoy** [comment] 2020-09-05 13:30
Yup, admonitions in mkdocs/python-markdown/pymdownx do not accept a blank line between the `:::` line and the body.

**Comment by thorn0** [comment] 2020-09-28 13:36
Duplicate of #9154

**Closed by thorn0** 2020-09-28 13:36 UTC

**Comment by evilebottnawi** [comment] 2020-09-28 13:38
@thorn0 wrong duplicate? link to this issue

**Comment by thorn0** [comment] 2020-09-28 14:36
Ooops

**Comment by thorn0** [comment] 2020-09-28 14:36
Duplicate of #8640
