### ISSUE TITLE
Template literals formatting not so pretty

### ISSUE THREAD

**Issue by mvila** [prettier/prettier#3286] opened 2017-11-18 23:28 UTC
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEGBOmC8mABgDLQDm2MOAllJbnQ9U1bfW64xwCTABmEHAFsAhjAByAV2EAjODgAUo8nACUAX070iAbhAAaEBAAOMGumShRGZP1EAbNHCOycosAGs4MAMomPJmRqKRcQABMIMDtHZyM6ZxwYAAV3cjEYpzCAKzQADwAhdy8fX1FhOBI6OEy44ykYEwaAJlqwgJxE5BBZUVkATwdoQxATdhgAdRpwmAALZAAOAAYjMYhnCfcTYJxQoxw4AEcpGgPUlQykeyyjZ2EaHb2QNCYHOABFKQh4NqMYPqmM3mSGaf3cNAcTAAwhBhJcQFBoDUjFJnAAVPpoNoaDRAA)

**Input:**
```jsx
const str = `Long string string string string string string ${formatNumber(age)} string`;
```

**Output:**
```jsx
const str = `Long string string string string string string ${formatNumber(
  age
)} string`;

```

**Expected behavior:**

In my opinion the input is more readable than the output, and I think Prettier should not try to do any formatting in this case.

**Comment by suchipi** [comment] 2017-11-19 19:30
This appears to be a duplicate of https://github.com/prettier/prettier/issues/3280 (unless you're referring to the function call hugging specifically). Even though it's kinda bad, we don't have many other options when it comes to template literals.

**Closed** 2017-11-19 19:30 UTC
Labels: lang:javascript, type:duplicate
