### ISSUE TITLE
Wrong indent with ternaries

### ISSUE THREAD

**Issue by caub** [prettier/prettier#4109] opened 2018-03-06 14:12 UTC
Prettier outputs 5 indent levels for the last expression below, instead of 4 (according to eslint):

output
```jsx
		const Bt = controlled
			? Btn
			: React.cloneElement(Btn, {
					'aria-owns': open ? 'user-dropdown' : null,
					'aria-haspopup': 'true',
					onClick: this.toggle,
			  });
```
expected ouput:
```jsx
		const Bt = controlled
			? Btn
			: React.cloneElement(Btn, {
				'aria-owns': open ? 'user-dropdown' : null,
				'aria-haspopup': 'true',
				onClick: this.toggle,
			});
```

I guess it doesn't work well with tabs

With spaces, eslint and prettier are both ok with:

```jsx
    const Bt = controlled
      ? Btn
      : React.cloneElement(Btn, {
          'aria-owns': open ? 'user-dropdown' : null,
          'aria-haspopup': 'true',
          onClick: this.toggle,
        });
```

config:
```json
{
  "singleQuote": true,
  "trailingComma": "all",
  "parser": "babylon",
  "semi": true,
  "jsxBracketSameLine": false,
  "useTabs": true,
  "tabWidth": 2,
  "proseWrap": "never",
  "printWidth": 120
}
```

versions:
```json
"eslint-config-prettier": "^2.9.0",
"eslint-plugin-prettier": "^2.6.0",
"eslint-plugin-react": "^7.7.0",
"prettier": "^1.11.1",
```

**Comment by lydell** [comment] 2018-03-06 16:08
Can you paste a problematic piece of code in http://prettier.io/playground, hit the "Copy markdown" button and paste the result above? That'll make it easier to understand your problem. (Note that there's a "Show options" button in the bottom left.)

**Comment by josephfrazier** [comment] 2018-03-06 16:28
This feels like a duplicate of https://github.com/prettier/prettier/issues/1271.

**Comment by caub** [comment] 2018-03-06 16:40
Yes this issue is similar, sorry

[long playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKkoGcYAIBCeAvLpjAE4QA2VcAJuqjAPwExSMxK4BKcAhmBgA6MFWhwAorQC2CGAApCUADS5gnJgHJ+5AJb8AtBADu2LdwgAHBLlZaArljjlDdSlbqmoW3NygONCqaMDr6RgAW-FhW1g5WFrhaFA5wWsEcMEzQAMJUemAA1twwEXpYwjAQAObVtBm4jbgAvgCUANwgKiDWMHrQWMigupQmAAq6CIMo-ABuEHp0XSDRMMgAZvxUzt0ARuSChXAwAMpWgnpQ1cgpcN1eYBtbOyCXzuQwYwfVMvxP23cQAArLAAD3wByKxxO-DkABlLnB-i8IA4YFY0QAmZGA87kd7IEC7fi7ACe4igyys+lgAHVFqVkABGTEABm61IgzlpByshOpcHesyR3XIcAAjg49GKvvwfn8kJsAd1nDI9DdyKkVZc6nAAIoOCDwDVakAwEn0uiMpCY7oUfh6fJXHIQGS-QlbKjLJxwAAqJOmt2azSAA)

**Closed** 2018-03-06 16:44 UTC
