### ISSUE TITLE
Why does prettier indent multi-line strings?

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#869] opened 2017-03-03 17:49 UTC
See: https://github.com/facebook/jest/pull/3057/files/943d74046ce051d18cc701399fcea65104977aea#diff-d84a3263785159507bcee07550d05530

```js
test(
  'my multiline' +
    'string'
)
```

vs.

```js
test(
  'my multiline' +
  'string'
);
```

Not saying either one is better than the other but if there is only a single (string) argument; which I expect to be the common case, it doesn't really add any value to intend them to separate them from other args. Please make a decision on why it should be either way.

**Comment by vjeux** [comment] 2017-03-03 18:57
Prettier does the same for conditionals inside of calls. The idea is that it's easier to figure out where the arguments are.

```js
test(
  longCondition &&
    secondCondition
)
```

>  if there is only a single (string) argument; which I expect to be the common case, it doesn't really add any value to intend them to separate them from other args.

FYI, the example where you linked to has two arguments ( https://github.com/facebook/jest/pull/3057/files/943d74046ce051d18cc701399fcea65104977aea#diff-d84a3263785159507bcee07550d05530 ). In order to disambiguate we may want to say: don't indent if it's the last argument.

But this now starts becoming very inconsistent. Let say you have a multiline string as a single argument and then you add a second argument, then the entire string gets indented. It's going to feel very weird!

@jlongster added this indentation behavior. While at first I was unsure about it, I'm starting to like it. It's pretty nice to quickly glance at the code and see where the arguments end.

**Comment by SimenB** [comment] 2017-03-03 20:28
In #868 you propose

```js
if (
  this.hasPlugin("dynamicImports") &&
  this.lookahead().type === tt.parenLeft
) {
}
```

Shouldn't it be 
```js
if (
  this.hasPlugin("dynamicImports") &&
    this.lookahead().type === tt.parenLeft
) {
}
```
In order to stay consistent with what you're saying here?

**Comment by cpojer** [comment] 2017-03-03 20:28
uhh no please don't for if statements. They line up so nicely now.

**Comment by SimenB** [comment] 2017-03-03 20:30
I would prefer lining up without indentation 😄 But it should be consistent. Why should these be treated differently?

```js
if (
  something &&
  somethingElse
)
```

```js
someFunction(
  something &&
    somethingElse
)
```

**Comment by vjeux** [comment] 2017-03-03 20:32
The difference is that in a function call, there can be more arguments afterward and it is clearer if everything gets indented.

**Comment by SimenB** [comment] 2017-03-03 20:35
So it'll be

```js
test(
  longCondition &&
    secondCondition,
  somethingElse,
  manyArgs ||
    notSoMany
)
```

instead of

```js
test(
  longCondition &&
  secondCondition,
  somethingElse,
  manyArgs ||
  notSoMany
)
```

I suppose I can see the argument. Thanks for the clarification! 😄

**Comment by vjeux** [comment] 2017-05-21 21:13
I'm going to close this issue as this is the intended behavior. Thanks for the report :)

**Closed by vjeux** 2017-05-21 21:13 UTC
Labels: Needs discussion
