### ISSUE TITLE
Support smarter class formatting in Glimmer (like html, vue, angular, lwc)

### ISSUE THREAD

**Issue by chasegiunta** [prettier/prettier#10944] opened 2021-05-24 20:19 UTC
**Prettier pr-7865**
[Playground link](https://deploy-preview-7865--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOiAAoBOE2m6cdAsnKQK51wkDC0GEUxRWAfXEALTligBzALQMA7rnSKAZgTgAPXNr2LIBLgFsoBnbsUElq3ACsuJGJk0BPY0IQxFrojoYJxc3T29YX1slACM4GBU4BEpLXCICTHkoRUx4MxJ-YSC0jKycvIK7Y19WagA+ADEICFQAeixsOpAAGhAIAAc3aBJkUEDVGkCEEZR0lSIPEd6YuiIwAGt4gGV+tdF5ZBg6LjheuDM49BZ0ABkiBS4ieTgmujMiGDcFZBAiLhgID0QFIYGYCAB1KS5Pi7MBwLbTXI4XIeH5gMhA0QkVgwehPd7ITTpbG9RwkXQAIVWG22RDMcBuojghOJpxAZN0W32OgAilwIPAWQQSSBdnRsXQfvIMmZ6ZLev06KIYODmDApMgABwABgVDGx4NW-R+ir4rGwzN6AEd+fB6AMZr8CmI4NcgbwbZheHj5ASkEThWzsWZMIdjkHuXA+QLmf7Wb1hDFVeh1cgAEwJ1aYDIKQSyog-PgAViBLjgABUiDEZgGRdgTgBJKAsWBbMBKwYAQWbWxgHh0QuxAF8h0A)
```sh
--parser glimmer
```

**Input:**
```hbs
<div class="ProviderMeasuresContainer__heading-row d-flex flex-column flex-lg-row justify-content-start justify-content-lg-between
  align-items-start align-items-lg-center">Foo</div>
```

**Output:**
```hbs
<div
  class="ProviderMeasuresContainer__heading-row d-flex flex-column flex-lg-row justify-content-start justify-content-lg-between
  align-items-start align-items-lg-center"
>
  Foo
</div>
```

**Expected behavior:**
```
<div
  class="
    ProviderMeasuresContainer__heading-row
    d-flex
    flex-column flex-lg-row
    justify-content-start justify-content-lg-between
    align-items-start align-items-lg-center
  "
>
  Foo
</div>
```

**Comment by thorn0** [comment] 2021-05-25 07:38
Duplicate of #10163

**Closed** 2021-05-25 07:39 UTC
Labels: type:duplicate

**Comment by chasegiunta** [comment] 2021-05-25 14:12
@thorn0 saw that issue but didn't think they were technically the same. Wrapping based on line length vs wrapping/grouping based on prefix
