### ISSUE TITLE
Error: Comment "TEST" was not printed. Please report this error!

### ISSUE THREAD

**Issue by FlorianStrobl** [prettier/prettier#13187] opened 2022-07-29 11:58 UTC
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEAPTBeTABgG4AdKAdwAsBLdTAChgCcBXOASk2HM0xoBmjXAEI8BVlAAmcATShwpHXn1WDhmADwFCXAEbM4AQwDWxTAHoLmACoBRAMo2VfOKgDOcHJgC0BAIxkUAC+IAA0IBAADjA00O7IoEbMzBAUAArJCAkoRqgURgCeCREGRmAmGA5GALZwADLycMgCeZ6lzOWVMA5R5fIA5sgs7BFwNXqKMlL1RlADrEYDcABiEMw1RjCx88ggRqwwEOEgVDA1qADqtPDufWBwDtk0sQBuL4V7YO4lIPKezBg6U6A02LTacAiACt3NgHIN0ABFVgQeDgjyQkB9ZgAvZ6IyTVAnKLMeQwS40KQwKjIAAchAiJIgnkunSiexJcABr2aEQAjij4MDojl9u4fApFIoToYBTRDMClmCkK0MRFPDUaMM2Jj3Ai4MjUc0VRCIjACRSqTSkAAmM2dOiDADCEBqypAXIArCdWJ4bAScqr2iBXuwAJLSBA9MCkmIAQWkDhghXQ6M8wWCQA)

**Input:**

```jsx
let x = 0;
while (true) {
  if (x !== undefined)
      if (x <= 0) break; // TEST
    else x -= 1;
}
```

**Output:**

```jsx
// ERROR
```

**Expected behavior:**

```jsx
let x = 0;
while (true) {
  if (x !== undefined)
    if (x <= 0) break; // TEST
    else x -= 1;
}
```

**Comment by fisker** [comment] 2022-08-28 17:08
Duplicate of #12655

**Closed** 2022-08-28 17:35 UTC
Labels: type:bug, area:comments, lang:javascript
