### ISSUE TITLE
${} template literal opening and closing brackets generate unnecessary lines

### ISSUE THREAD

**Issue by yorrd** [prettier/prettier#5718] opened 2019-01-04 11:11 UTC
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEALGBbANgAwDpQAEhAJMAM4QZwyoCWUA5gccQHQYQBOcAFAJQtWbOADcEAgnhgduffgF8COANwgANCAgAHGHWjlkoAIZcuEAO4AFUwkMpjoiHQAmGkACMuxsAGsaAMraPgyMyDBcAK5wmujYAOr08OTBYHABdnR6olkAnsjg5IaaDORwXDBW3owYxsgAZsZYZZoAVuQAHgBC3n6BxtQAMgxwDU0tIO0dAaFYcACKkRDwY80xIMFcZVwFHsYeuVjQ7tpcDDDxrrTIABwADJqnEGXx3toFp3Db4u48AI6ROg8KrGGp1JCNNaaMoYOjhKLrcizBZLFYQ8brGD7S4ua5IABMmgixjoWFCAGEqLUClBoKNNJEygAVfb2SFlBQKIA)
```sh
--parser babylon
```

**Input:**
```jsx
html`
  ${something
    .more()
    .even()
    .more()}
`;
```

**Output:**
```jsx
html`
  ${
    something
      .more()
      .even()
      .more()
  }
`;

```

**Expected behavior:**

The input.

With `lit-html`, one has a lot of parts, in my case a lot of parts with function chaining (rxjs pipes). In a regular component (300 lines), there are sometimes over 30 "empty" lines that don't contain any logic and bloat the file. I'ts working well with functions:

```
@click="${() => {
...
}"
```

**Comment by lydell** [comment] 2019-01-04 11:21
Duplicate of #5672

**Closed** 2019-01-04 11:21 UTC

**Comment by yorrd** [comment] 2019-01-04 11:30
Sorry! and thanks
