### ISSUE TITLE
[ts] Unnecessary line break when adding a return type annotation to a callback arrow

### ISSUE THREAD

**Issue by nicolo-ribaudo** [prettier/prettier#10637] opened 2021-03-30 13:28 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzKAKDBKJACAQzwF4A+PYAHSjzwCc4YBXOm4AXwG5r3tuoQAGhAQADjACW0AM7JQBOnQgB3AAoKEslAQA2yggE9ZwgEZ0CYANaMAyqIsSoAc2Qw6TOMLgBbE3AAm-gEAMgTOTAROcABiEHTeBDCSzsggBEwwEEIgABYw3joA6jkS8NL2YHA2mqUSAG6lBqlg0sYgjtJwdDCq5k4JyKi6ncIAVtIAHgBC5la2BN5wwY5wg8OeIOMTNo5OOnAAikwQ8Gs6IyD2dJ10qSYEfjoAtDBtonSOMIUS-jA5yAAOAAMwneEE6hXMolS7zgNzqq2EAEdjvBemItGlpE8oHAAgFsgwURIGL1IgMkENzhtOt4JK53DTdvsjidVpT1sIYA9vr9-kgAExc8wSHS7ADCEG8FJAcIArNkmJ0ACoPLRUi51DwASSgQVgNjAH3EAEE9TYYAZ9mdOux2EA)

```sh
--parser babel-ts
```

**Input:**

```tsx
fn((): a => {
  return {};
});

```

**Output:**

```tsx
fn(
  (): a => {
    return {};
  }
);

```

**Expected behavior:**

The output should be the same as the input. This already happens if you delete the `: a` annotation.
Flow does not have this issue.

**Comment by thorn0** [comment] 2021-03-30 14:37
Fixed by #10316, not released yet.

**Comment by thorn0** [comment] 2021-03-30 14:37
Duplicate of #7542

**Closed by thorn0** 2021-03-30 14:37 UTC

**Comment by nicolo-ribaudo** [comment] 2021-03-30 17:12
Oh ok thanks! I only searched for open issues :sweat_smile:

**Comment by thorn0** [comment] 2021-03-31 00:22
BTW, have a look at this: https://github.com/prettier/prettier-regression-testing/issues/44#issuecomment-810659755
That's how the upcoming Prettier 2.3 release is going to reformat Babel's codebase. Feedback would be appreciated.

**Comment by nicolo-ribaudo** [comment] 2021-03-31 07:04
It mostly looks good, just a few comments:
1. This line is 79 chars long, I don't understand why the regexp goes on a new line
  ```js
  const EXTERNAL_SOURCEMAP_REGEX = /^[@#][ \t]+sourceMappingURL=([^\s'"`]+)[ \t]*$/;
  ```
2. I see many object destructurings reformatted to take a single line. They look good, but I thought Prettier respected whether objects are on one line or on multiple lines in the input source?

**Comment by thorn0** [comment] 2021-03-31 12:44
> This line is 79 chars long

It's 82 :)

> I see many object destructurings reformatted to take a single line. They look good, but I thought Prettier respected whether objects are on one line or on multiple lines in the input source?

Object literals - yes, destructurings - no. These destructurings are the reason why the release is being delayed. Prettier became smarter about breaking assignments overall, but this had this unintended effect on destructurings: when Prettier finds a way to break after `=` or in RHS, a long complex destructuring may end up on a single line. I'm going to forcefully break destructurings with `:` and `=` in their entries to improve this (`{ x, y, z }` vs `{ x: a, y = 2, z }`).
