### ISSUE TITLE
Odd behaviour with nested bullet points in markdown

### ISSUE THREAD

**Issue by willclarktech** [prettier/prettier#3713] opened 2018-01-11 11:23 UTC
In addition to the issue of inconsistent (and broken) second output shown below, running prettier (v1.8.2) locally wraps all the nested bullet points (along with the parent bullet point) according to line length so the list is lost.

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBidACA4gSxhgYQgFti8MBZOAZ2oEMBzGgHSlYCoMBVauDGABZ8ADgCcaCfPCi8MACmYgAggBMVGAGZw6MAK7jFGKBHyLVKuOq079cRQEoO3WYL45iwuKJ04Abn2IICHUFEAoIfwwwfWoIUX4IADpkw2NTMIiaKJi4hOTEhycAGXdyV00cUWp8ABscKD4YCAwAdgAmKIE6bzB4KoxcmppqJwAlOC1xKDA3Wl0suih1YV0amoxxAEd56uoMOoAjLzo1gE8MOg0+-iEKqtr6uyhOIhkcC3jq7ph6hhu+SCkcjEYaMPgAdzwAguUAuwmEdTAdAOQwwcECACscEhWMwYJwkLxLHUoAwkBgAAaEuDE35ICkYcFCWF0NS-C5GODgzTaPQGNj4jBIA66MmU4Wi+mM5kVAAe7LoGBFDFxguFQQA1tRyVSDprtQymQgLmzSQN4rphCofGaVBBoiDYD5oKqCVA6DgasxmAB9JHiHVId2ev3dOBSo2w4h0DXssBdUlZJpRYJ8aqnVFyOCJBiJfb1fC8GA-UnURwCgniMCnMBDQNVmt1w0y8QaOi9OJx1OuoUaSrh8V9gPN43iQK+LsWc0VIZ7OT1Wu6FTsiyeJYIMA4GjlvGV9twARxXj1-eHqrhkew9xiCLszyiDRxaPTJ67oVMvB2X3xuBgDXen1o1EDVAw-eA-SEP9AO6EDLxNZczVyS1rRLP54F2HskEgGQYFEXRehwF1fXBOINS8QNsOqPCCOgH0SOA8i4OQm00NuEVPWWUR7WGTC9XBH4B11CB+K3CMZWY1DCAASUww9dGPcU5OPOD70fUQyDNeM4hYCshQacFA30sTjVZBC-kVfSMFXBALGmU5MO6LjwQAy1A0c4SfVcpjhAYbwzI5az1zshzRCcgC7XBKA3NCjyIqiuC4t81kFSsuA11s6tePbEDxQObLjNhcR-FEST40WJhqBAAAaEAIGEH5oEqpBQHc8EAAUwxkZAQDoXwIHeaqeuqZA2xqXgaoOHoyJgABlYR21+ZBcPmGq7TAEaTnGkB6l4Eq2u8Bhow2sa4BqjFqFlAAhKa4FmugQRKBpjq2iBdBgFYYDaJa8NOkB5vPURuqAjU4sGsQCwAdXeQRkAADgABhqm9eAh7xhG6sQJFEfxBq2XR+32xgjqQUatt4MhvpWkBqF+IYAEVdBMOBnt+mBkShlQYaQNoatwj0SQYIhSDobrjCemr5LgAAVZEmtJuAAF8FaAA)
```sh
--parser markdown
```

**Input:**
```markdown
### Git Commit Messages

* Use the present tense ("Add feature" not "Added feature")
* Use the imperative mood ("Move cursor to..." not "Moves cursor to...")
* Limit the first line to 72 characters or less
* Reference issues and pull requests liberally after the first line
* Consider starting the commit message with an applicable emoji:
	* :seedling: `:seedling:` when adding a new feature
	* :bug: `:bug:` when fixing a bug
	* :books: `:books:` when adding or updating documentation
	* :nail\_care: `:nail_care:` when making changes to code style (e.g. lint settings)
	* :recycle: `:recycle:` when refactoring code
	* :fire: `:fire:` when removing code or files (including dependencies)
	* :racehorse: `:racehorse:` when improving performance
	* :white\_check\_mark: `:white_check_mark:` when adding or updating tests
	* :construction\_worker: `:construction_worker:` when updating the build process
	* :bowtie: `:bowtie:` when updating CI
	* :house: `:house:` when performing chores
	* :new: `:new:` when adding a new dependency
	* :arrow\_up: `:arrow_up:` when upgrading a dependency
	* :arrow\_down: `:arrow_down:` when downgrading a dependency
	* :back: `:back:` when reverting changes
```

**Output:**
```markdown
### Git Commit Messages

* Use the present tense ("Add feature" not "Added feature")
* Use the imperative mood ("Move cursor to..." not "Moves cursor to...")
* Limit the first line to 72 characters or less
* Reference issues and pull requests liberally after the first line
* Consider starting the commit message with an applicable emoji:
  _ :seedling: `:seedling:` when adding a new feature
  _ :bug: `:bug:` when fixing a bug
  _ :books: `:books:` when adding or updating documentation
  _ :nail_care: `:nail_care:` when making changes to code style (e.g. lint settings)
  _ :recycle: `:recycle:` when refactoring code
  _ :fire: `:fire:` when removing code or files (including dependencies)
  _ :racehorse: `:racehorse:` when improving performance
  _ :white_check_mark: `:white_check_mark:` when adding or updating tests
  _ :construction_worker: `:construction_worker:` when updating the build process
  _ :bowtie: `:bowtie:` when updating CI
  _ :house: `:house:` when performing chores
  _ :new: `:new:` when adding a new dependency
  _ :arrow_up: `:arrow_up:` when upgrading a dependency
  _ :arrow_down: `:arrow_down:` when downgrading a dependency \* :back: `:back:` when reverting changes

```

**Second Output:**
```markdown
### Git Commit Messages

* Use the present tense ("Add feature" not "Added feature")
* Use the imperative mood ("Move cursor to..." not "Moves cursor to...")
* Limit the first line to 72 characters or less
* Reference issues and pull requests liberally after the first line
* Consider starting the commit message with an applicable emoji:
  _ :seedling: `:seedling:` when adding a new feature
  _ :bug: `:bug:` when fixing a bug
  _ :books: `:books:` when adding or updating documentation
  _ :nail*care: `:nail_care:` when making changes to code style (e.g. lint settings)
  * :recycle: `:recycle:` when refactoring code
  _ :fire: `:fire:` when removing code or files (including dependencies)
  _ :racehorse: `:racehorse:` when improving performance
  _ :white_check_mark: `:white_check_mark:` when adding or updating tests
  _ :construction*worker: `:construction_worker:` when updating the build process
  * :bowtie: `:bowtie:` when updating CI
  _ :house: `:house:` when performing chores
  _ :new: `:new:` when adding a new dependency
  _ :arrow_up: `:arrow_up:` when upgrading a dependency
  _ :arrow_down: `:arrow_down:` when downgrading a dependency \* :back: `:back:` when reverting changes

```

**Local result:**

```markdown
### Git Commit Messages

* Use the present tense ("Add feature" not "Added feature")
* Use the imperative mood ("Move cursor to..." not "Moves cursor to...")
* Limit the first line to 72 characters or less
* Reference issues and pull requests liberally after the first line
* Consider starting the commit message with an applicable emoji: _ :seedling:
	`:seedling:` when adding a new feature _ :bug: `:bug:` when fixing a bug _
	:books: `:books:` when adding or updating documentation _ :nail*care:
	`:nail_care:` when making changes to code style (e.g. lint settings) *
	:recycle: `:recycle:` when refactoring code _ :fire: `:fire:` when removing
	code or files (including dependencies) _ :racehorse: `:racehorse:` when
	improving performance _ :white_check_mark: `:white_check_mark:` when adding or
	updating tests _ :construction*worker: `:construction_worker:` when updating
	the build process * :bowtie: `:bowtie:` when updating CI _ :house: `:house:`
	when performing chores _ :new: `:new:` when adding a new dependency _
	:arrow_up: `:arrow_up:` when upgrading a dependency _ :arrow_down:
	`:arrow_down:` when downgrading a dependency \* :back: `:back:` when reverting
	changes
```

<img width="783" alt="screen shot 2018-01-11 at 12 19 44" src="https://user-images.githubusercontent.com/11036220/34823198-d80d4c42-f6c9-11e7-92c5-a584229374c4.png">

**Expected behavior:**

Nested bullet points should preserve their structure.

**Comment by j-f1** [comment] 2018-01-11 11:33
It looks like this is a bug in `remark`, the Markdown parser we use.

**Comment by duailibe** [comment] 2018-01-11 12:18
remark has bugs parsing lists tab-indented instead of space-indented. Closing this as duplicate of #3223

Please comment if anything is not covered in that issue

**Closed by duailibe** 2018-01-11 12:18 UTC
Labels: lang:markdown, scope:dependency, type:bug

**Comment by protoEvangelion** [comment] 2018-06-09 18:33
Using spaces instead of tabs in my md file fixed this :smile:
