### ISSUE TITLE
Prettier fails to parse the actual HTML spec

### ISSUE THREAD

**Issue by binyamin** [prettier/prettier#12669] opened 2022-04-19 00:01 UTC
**Environments:**
- Prettier Version: 2.6.2
- Running Prettier via: CLI
- Runtime: Node.js 16
- Operating System: Linux
- Prettier plugins (if any): none

**Steps to reproduce:**
1. Download [the HTML Living Standard webpage](https://html.spec.whatwg.org/multipage/indices.html).
2. Run prettier on the HTML file.
3. It complains, because there's no ending tag for the `body`.

**Expected behavior:**
Follow the specification. As per [section 4.1.3](https://html.spec.whatwg.org/multipage/sections.html#the-body-element) of the HTML Living Standard, the body element can sometimes omit the ending tag.

**Actual behavior:**
It throws an error, because their body and html elements have no ending tag. Here's the log.
```console
$ prettier cache/html-spec.html
cache/html-spec.html[error] cache/html-spec.html: SyntaxError: Unexpected character "EOF" (3041:1)
[error]   3039 |
[error]   3040 |   <nav><a href=iana.html>← 17 IANA considerations</a> — <a href=./>Table of Contents</a> — <a href=references.html>References →</a></nav>
[error] > 3041 |
[error]        | ^
```

**Comment by fisker** [comment] 2022-04-19 00:17
I also tried it before, but there is nothing we can do here. Try open an issue on [angular-html-parser](https://github.com/ikatyang/angular-html-parser) and [angular](https://github.com/angular/angular). We use an angular fork as html parser.

**Comment by thorn0** [comment] 2022-07-22 22:34
Duplicate of #8210
It throws an error because of the unquoted slash: `<a href=./>Table of Contents</a>`

**Closed by thorn0** 2022-07-22 22:34 UTC
Labels: scope:dependency, status:awaiting response, lang:html
