### ISSUE TITLE
Arrow function with long name or one long parameter exceeds print width

### ISSUE THREAD

**Issue by VincentBel** [prettier/prettier#3067] opened 2017-10-19 10:04 UTC
**Prettier 1.7.4**

### With long name

[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20loooooooooooooooooooooooooooooooooooooooooooooooooooooooongFunctionName%20%3D%20a%20%3D%3E%20'lol'%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
const loooooooooooooooooooooooooooooooooooooooooooooooooooooooongFunctionName = a => 'lol'
```

**Output:**
```jsx
const loooooooooooooooooooooooooooooooooooooooooooooooooooooooongFunctionName = a =>
  "lol";

```

**Expected behavior:**

Don't exceed print width, may put the function body in a new line:

```js
const loooooooooooooooooooooooooooooooooooooooooooooooooooooooongFunctionName =
  a => "lol";
```

### With one long parameter

[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20a%20%3D%20looooooooooooooooooooooooooooooooooooooooooooooooooooooooooongParamName%20%3D%3E%20'lol'%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
const a = looooooooooooooooooooooooooooooooooooooooooooooooooooooooooongParamName => 'lol'
```

**Output:**
```jsx
const a = looooooooooooooooooooooooooooooooooooooooooooooooooooooooooongParamName =>
  "lol";

```

**Expected behavior:**

Don't exceed print width, may put the function body in a new line:

```js
const a =
  looooooooooooooooooooooooooooooooooooooooooooooooooooooooooongParamName =>
  "lol";
```

**Comment by bakkot** [comment] 2017-10-20 20:21
Duplicate of #2482.

Assignments are kind of hard to get right with the current setup :(

**Closed by bakkot** 2017-10-20 20:21 UTC
