### ISSUE TITLE
Maximum line length not obeyed when long variable names

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [prettier/prettier#9785] opened 2020-11-27 17:55 UTC
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzAllAEwHVcCBzOGAIQE8BVKXARwFc4BJAhGXPOAJwDKcADZwwMCP0wBeTAFsAhgGs4AMXzFSFavUasOXWL1wDhYiVIAUASgDcIADQgIABx7pkoRf34QA7gAKPghoyCCKIv6KNGHOAEb8imCqMIKuyfhkyDD8bM5w8vFwBFwEADKKUGQsihRqUkowPNXhiiySTiAAFjDyIkTduPBoGWBwwlBow7gAbsM04WBocSD4aAIwgUlkSsjYkRvOAFZoAB5USSmUgorycOX4cPuHcCfnglliAIosEPAvERHEAZfgbfjheKKYoiLqufj4GAkAgwbrIAAcAAZnPCIBsiElXOF4XBwbNns5WP84Ns3GEUIo0ABaKBwEolLr8OCsXBc7Z1PZIA5At4gDbyXA5PKi6bVH5-AFC17OGDQ5Go5AAJhVSVwIiyAGEIPJBSBSQBWLosDYAFWh9OFwNmbHYhG4gjACPcAEFCIIYDQxICNgBfENAA)
```sh
--parser babel
```

**Input:**
```jsx
const findWidgetByUniqueIdentifierSelector = makeFindWidgetByUniqueIdentifierSelector();
```

**Output:**
```jsx
const findWidgetByUniqueIdentifierSelector = makeFindWidgetByUniqueIdentifierSelector();

```

**Expected behavior:**
```jsx
const findWidgetByUniqueIdentifierSelector = 
  makeFindWidgetByUniqueIdentifierSelector();
```

**Comment by thorn0** [comment] 2020-11-27 18:03
Duplicate of #2482

**Closed by thorn0** 2020-11-27 18:03 UTC
