### ISSUE TITLE
Unexpected token, expected "," when bundling with parcel

### ISSUE THREAD

**Issue by chrisdrackett** [prettier/prettier#7167] opened 2019-12-21 23:29 UTC
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: node
- Runtime: node 13.5
- Operating System: macOS

**Steps to reproduce:**
I've included prettier in my node script:

```
prettier.format(`text here`, { parser: 'typescript' })
```

and I'm then trying to use parcel (watch mode). I get the following:

```
/node_modules/prettier/parser-typescript.js:1:1688278: Unexpected token, expected "," (1:1688278)
```

**Comment by kachkaev** [comment] 2019-12-21 23:41
👋 @chrisdrackett, it's not quite clear what you're trying to achieve. Parsing error is not unexpected because `text here` is an invalid typescript (see [playground result](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8AeMAEALOAnOEAGhAgAcYBLaAZ2VAEM88IB3ABSYTpQYDcIlACbEQAIzwMwAazgwAymSmUoAc2Qw8AVzglsMALYAbAOrZK8GkrBx53C5T4WAnsnA06JFTXwx2k1QMGZAAzBiMfEgArGjQAIUkZOXkGAzgAGRVCJDCI3RAYtHkVVSM4AEUtCHhQ8MiQJTwfPDcYZzI4GjA8SgpRMh7YE2EYbGQADgAGEgGIHxNJMjcBzvw+QhIARyr4f3IeEAYaAFooODghC9ECbcoCfwZA4Jy6-J8DSg1tN5Kyyursrl6jAGGJhkJRsgAEwkTQMShGEoAYQgBiCbig0A2IC0PgAKqCeED8nwdABJKCXWDybq9GAAQUp8jaZVqeQAvuygA)).

If you have something else instead of `text here`, the issue won't be possible to investigate without a full reproduction.

**Comment by armano2** [comment] 2019-12-29 19:25
This type of syntax is considered hard error by parser (tho we can produce ast but it will be invalid).

ast:
 - Identifier: text
 - Identifier: here

**Closed** 2020-01-05 09:03 UTC
Labels: status:awaiting response
