### ISSUE TITLE
Long curried function calls

### ISSUE THREAD

**Issue by adrianmcli** [prettier/prettier#1420] opened 2017-04-26 00:41 UTC
Prettier changed this:

```js
const ArtistInput = connect(mapStateToProps, mapDispatchToProps, mergeProps)(Component);
```

to this due to line-length:

```js
const ArtistInput = connect(mapStateToProps, mapDispatchToProps, mergeProps)(
  Component
);
```

At this risk of making a poorly written issue, I'm actually not sure if there is a more ideal way to format this. Nevertheless, some people on my team have complained about how prettier made this line a bit uglier. Perhaps we can brainstorm a better way to represent this?

**Comment by vjeux** [comment] 2017-04-26 20:59
I'm curious, how would you format this if it didn't fit in a single line?

**Comment by adrianmcli** [comment] 2017-04-26 21:37
As I've said, I am not sure if there is a more ideal way to reformat this. But here are a couple ideas (that might be worse than the status quo):

1. This feels sensible enough:

```js
const ArtistInput =
  connect(mapStateToProps, mapDispatchToProps, mergeProps)(Component);
```

2. This might be over-doing it.

```js
const ArtistInput = connect(
  mapStateToProps,
  mapDispatchToProps,
  mergeProps
)(Component);
```

**Comment by ndresx** [comment] 2017-04-27 20:00
@adrianmcli Think both of the examples you provided fit better into the style of how prettier is currently formatting arrow functions and functions in general with multiple arguments than how this is formatted in its current state.

**Comment by urban** [comment] 2017-05-05 05:20
@adrianmcli I would prefer option 2 over 1. Especially when arguments are partially applied functions. For instance:

```js
import R from 'ramda';

const mapStateToProps = state => ({
  users: R.compose(
    R.filter(R.propEq('status', 'active')),
    R.values
  )(state.users)
});
```

**Comment by threehams** [comment] 2017-06-04 21:40
Option 2 is what naturally happens when once the argument list gets a bit longer.

```
const App = compose(withState('thing', 'setThing'), withHandlers({
  onClick: props => event => { props.setThing(event.target.value); },
}))(BaseApp);
```
becomes
```
const App = compose(
  withState('thing', 'setThing'),
  withHandlers({
    onClick: props => event => {
      props.setThing(event.target.value);
    },
  }),
)(BaseApp);
```

Still, this was previously closed in #1116 and #1035, so we may need to make a `prettier-fp` fork to handle this a bit better at a global level.

**Comment by vjeux** [comment] 2017-06-04 21:48
For the original report, the ideal way would be for prettier to format it as

```js
const ArtistInput = connect(
  mapStateToProps,
  mapDispatchToProps,
  mergeProps
)(Component);
```

The root of the issue here is that the first and second arguments are next to each other in terms of the intermediate representation and not nested. Right now we have very little control around how the low level formatters choses which one to break.

Another issue with the same root cause: https://github.com/prettier/prettier/issues/1825

@threehams please do fork prettier and try to make it work well for functional programming :) If you find great heuristic for them, we should port them back to prettier.

**Comment by threehams** [comment] 2017-06-04 21:53
OK! I was only planning to do that since it was your recommendation in the (closed) linked issues.

Ideally there's a rule that could change formatting for nested functions without negatively affecting other code. I don't think that `function(argument)(argument)` is a very common pattern in non-FP code styles, but I could be wrong. I'll take a look.

**Comment by goldo** [comment] 2017-09-05 09:14
@threehams any news on this ? :)

**Comment by threehams** [comment] 2017-09-05 15:23
I tried a PR, but it made other code worse (I detected function calls within argument lists and forced line breaks). It's tricky to come up with a rule for this one.

Solving the linked issue (#1825) would be the next approach, though I've mostly just accepted that <1% of code will be less readable with Prettier than without. That's a really good tradeoff.

**Comment by testerez** [comment] 2018-01-11 15:44
Any progress on that concern? This is the main reason why our team still hesitate to use prettier...

**Comment by j-f1** [comment] 2018-01-11 15:48
This might be a good time to use `conditionalGroup`:

```js
// condition 1
const ArtistInput = connect(mapStateToProps, mapDispatchToProps, mergeProps)(Component);

// condition 2
const ArtistInput = connect(
  mapStateToProps,
  mapDispatchToProps,
  mergeProps
)(Component);

// condition 3
// (only used if the `Component` part is really long)
const ArtistInput = connect(
  mapStateToProps,
  mapDispatchToProps,
  mergeProps
)(
  Component
);

```

**Comment by rogovdm** [comment] 2018-02-27 10:52
Within increasing popularity of fp patterns in javascript I do believe this issue is important. 

New line for an each function call looks the best for me.

**Comment by rogovdm** [comment] 2018-02-27 10:54
If this is a discussion, lets raised some concrete questions.

1. Do we need this?

2. How can we deal with it, if we do?

**Comment by ericanderson** [comment] 2018-02-27 12:10
@j-f1 I like that. This would be similar code to how print chain works?

**Comment by ericanderson** [comment] 2018-02-27 12:13
As an additional condition, perhaps if the result of a function is then invoked, if the first call has more than 1 (2?) arguments, split into condition 2.

Similarly, if the returned function is invoked with more than N arguments it would also be spread to multi line?

**Closed** 2018-05-08 03:46 UTC
Labels: status:needs discussion

**Comment by adrianmcli** [comment] 2018-05-08 04:07
Thanks everyone for their input and hard work. This was not an easy problem to solve, it's quite satisfying to see an issue I opened over a year ago is now closed 👍

**Comment by j-f1** [comment] 2018-05-08 10:29
Now it looks like this:

**Prettier pr-4431**
[Playground link](https://deploy-preview-4431--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEBBATjASwwEkoAHAVywF5NIoo4wYAKAWwEMyBlGD+ACoQACrghk0AGkycyAESJl+YABZDR4qTLi4A5nA0SAlCwDCENmWgIYRgNwAdKCEkhxhdMlAdcYgO7CPghoyCAcAG4QBAAmLiAARrgcYADWcDDcSmAEULrIMLgUcK45aDowohy6nMgAZhwANmWuAFZoAB4AQkmp6dwcbHAAMjlwdY3NIEq4Zbih8RzxAJ4N0HFkuDkwAOoxMCrIABwADK4bEGXbSWShG3Cz4WOuuHAAjhQEL5XVHONNxSAymwCPlCgC0DldA04ABFCgQeB-SZ8eK7aL7ZAAJlcBQ4BAakPMbBqKCg1jiFDKAkWISQ9X+AF8GUA)

**Input:**
```jsx
const ArtistInput = connect(mapStateToProps, mapDispatchToProps, mergeProps)(Component);

```

**Output:**
```jsx
const ArtistInput = connect(
  mapStateToProps,
  mapDispatchToProps,
  mergeProps
)(Component);

```

**Comment by linesh-simplicity** [comment] 2018-05-08 16:11
And now this: 

```js
export default compose(analyticsDecorator('Login'), connect(mapStateToProps, mapDispatchToProps))(Login)
```

looks like this:

```js
export default compose(
  analyticsDecorator('Login'),
  connect(
    mapStateToProps,
    mapDispatchToProps
  )
)(Login);
```

where the indentation looks perfectly comfortable. I think that's the one last thing that ever held us back(a little bit) and now prettier looks 100% comfortable for me on a medium scaled React Native codebase. Thanks for all the hard work that makes this happen and make prettier such a pleasure to use. 100% satisfaction for an opinionated formatter on a real world project, for me that sounds fabulous.
