### ISSUE TITLE
Add line break before forced space to stay within the print width

### ISSUE THREAD

**Issue by mariusschulz** [prettier/prettier#4527] opened 2018-05-23 15:15 UTC
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaIFs4BqAhgE4CWRARgDZyYC8mAFADpSaYA8AJmQG4A+Nhw4APcRMlTpM2XPkL5wAOSZlAXwCewrgHpegtgEoA3CAA0ICAAcYZdMlCkSEAO4AFUgjTIQRPhBk3BYglCREYADWcDAAytYRZFAA5sgwJACucJZJaHAkMO7hybhEyABmRNR5lgBWaKIAQuFRMbFE+AAySXAVVTUgCSR5JL6UVJrU0CHW5LAA6kEwABbIABwADJazEHnz4da+s3AjfL2WJHAAjhlkl0VEJWVIldXZIHm4ZGmZ72hJyVoAEUMhB4H03pYYFRFtwVsgAExQ8JkagAgDCeFKvig0HOIAyeQAKlQfC9+nB1OogA)

**Input:**
```jsx
const someVariable = (
  <div>
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx{" "}y
  </div>
);
```

**Output:**
```jsx
const someVariable = (
  <div>
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx{" "}
    y
  </div>
);
```

**Expected behavior:**
```jsx
const someVariable = (
  <div>
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    {" "}y
  </div>
);
```

With `--print-width=80`, the forced space (`{" "}`) should be placed on the next line so that the line does not exceed the print width.

**Comment by duailibe** [comment] 2018-05-23 16:32
Context: #1582 #1831 #1964

We decided to do always append to the preceding node (instead of prepending to the following node) because there might be some cases of
```jsx
<div>
  xxxxxxxxxxxx
  {" "}<div>
    <Something />
  </div>
</div>
```

I guess we can improve this heuristic, see what's before and what's after and then chose what's best.

**Comment by lydell** [comment] 2018-05-23 16:35
I actually think this is a duplicate of #2553

**Comment by lydell** [comment] 2018-05-23 16:35
Duplicate of #2553

**Closed by lydell** 2018-05-23 16:35 UTC
Labels: lang:jsx
