### ISSUE TITLE
No idempotence on import + blank line + expression

### ISSUE THREAD

**Issue by cprecioso** [prettier/prettier#10870] opened 2021-05-12 13:53 UTC
It also happens when the expression is a jsx component

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgDMIIicJ18AdEAIwEMcaqoWAKYAXwEoWQAaEBEwxU0AM7JQjcgHcACowSSU9ADaz6AT0mDaOemADWcGAGVMh1FADmyGDgCucQXHS04AE09eAMvVtHehs4ADFcdHoYUVtkEHpHGAgBEAALGHQ1AHVU1HhxSzA4M2U81AA3PK04sHFdNChxODx5AxtI5EJ1JsEAK3EADwAhA2NTM3p0OF9rOE7ulxB+gbNrGzU4AEVHCHh5tR6QSxwmnDiGDzUUzBxrGCzUTxhU5AAOAAZBG4gmrINMOI3OCncpzQQARx28FawhU8XEAFooHAvF4Ujg4JDUBjWsEOkgugdFk10Kh9odxGsNttdnMCQtBDB6LQHk8XkgAEyMgyoNRrADCFHxIGBAFYUo4mgAVZkqQmHcrOACSUB8sDMYFuIgAgqqzDAtBtyXBOJwgA)

```sh
--parser babel
--no-semi
```

**Input:**

```jsx
import foo from "bar"

({})

```

**Output:**

```jsx
import foo from "bar"

;({})

```

**Second Output:**

```jsx
import foo from "bar"
;({})

```

**Expected behavior:**
The first and second outputs are equal

**Comment by thorn0** [comment] 2021-05-12 14:50
Duplicate of #1510

**Closed** 2021-05-12 14:50 UTC
Labels: area:idempotency, area:no-semi, lang:javascript, type:bug, type:duplicate
