### ISSUE TITLE
No editor is capable of working with Prettier's deletion of trailing indentation for padded lines

### ISSUE THREAD

**Issue by Yzrsah** [prettier/prettier#5925] opened 2019-02-28 13:52 UTC
Because issue #5923 was closed, a new issue is created:

@kachkaev 

> I understand your issue and often struggle with it myself too. However, I believe it could be better solved in the text editor

The issue is not solved in any text editor, therefore we need to resolve this so that the use of Prettier does not negatively impact the process of creating code.

## How to solve the issue:

- **Post an example of an editor that allows virtually working with non-existing indentation, so that you can move your cursor around on the virtual indentation as if the indentation existed, completely transparently and without being apparent to the user**

Referenced at: https://github.com/xojs/xo/issues/379

**Comment by j-f1** [comment] 2019-02-28 14:36
We’re not planning on changing this. As mentioned in the other issue, if you write code like this:

```js
const f = x => {
	// something
	g(x)

foo()

	// something else
	h(x)
}
```

Prettier will format it to this:

```js
const f = x => {
	// something
	g(x)

	foo()

	// something else
	h(x)
}
```

No extra whitespace needed!

---

Please don’t open intentionally duplicate issues. If we see significant demand on the other issue, we may reopen it.

**Comment by j-f1** [comment] 2019-02-28 14:37
Duplicate of #5923

**Closed by j-f1** 2019-02-28 14:36 UTC

**Comment by Yzrsah** [comment] 2019-02-28 14:42
@j-f1 The issue was not resolved in any way

**Comment by Yzrsah** [comment] 2019-02-28 14:43
@j-f1 The issue was not resolved in any way, and it is a significant enough issue that my company cannot use Prettier

**Comment by Yzrsah** [comment] 2019-02-28 15:11
Update: we're working on a fork called PrettierForTheActualProgrammerWhoIsWorkingOnTheCodeInsteadOfPrettierForTheServerAndHypotheticalEconomicTheoryAboutWhoIsNegativelyImpactedByThousandsOfExtraBytes

**Comment by Yzrsah** [comment] 2019-02-28 15:12
@j-f1 The issue was not resolved in any way, and it is a significant enough issue that my company cannot use Prettier

Update: we're working on a fork called PrettierForTheActualProgrammerWhoIsWorkingOnTheCodeInsteadOfPrettierForTheServerAndTheHypotheticalEconomicTheoryAboutWhoIsNegativelyImpactedByThousandsOfExtraBytes

**Comment by Yzrsah** [comment] 2019-02-28 15:13
@j-f1 The issue was not resolved in any way, and it is a significant enough issue that my company cannot use Prettier

Update: we're working on a fork called PrettierForTheActualProgrammerWhoIsWorkingOnTheCodeInsteadOfPrettierForTheCPUAndTheServerAndTheHypotheticalEconomicTheoryAboutWhoIsNegativelyImpactedByThousandsOfExtraBytes

**Comment by Yzrsah** [comment] 2019-02-28 15:21
@j-f1 The issue was not resolved in any way, and it is a significant enough issue that my company cannot use Prettier

Update: we're working on a fork called PrettierForTheActualProgrammerWhoIsWorkingOnTheCodeInsteadOfPrettierForTheExecutivesOptimizingDataStorageRevenuesAtAmazonAndFacebookAndGoogleAndTheServerAndTheHypotheticalEconomicTheoryAboutWhoIsNegativelyImpactedByThousandsOfExtraBytes

**Comment by lydell** [comment] 2019-02-28 15:32
@Yzrsah Yeah, I know how you feel – it sucks when you're in a team isn't willing to adopt Prettier :( I've been there myself. But if a bunch of spaces at the right places is a showstopper for your company I don't think the company is ready to start using Prettier.

**Comment by Yzrsah** [comment] 2019-03-06 13:45
`"useTabs": false` + `"tabWidth": 4` can use ~3x more bytes for whitespaces than using `"useTabs": true` + padded-lines-indent

`"useTabs": true` + padded-lines-indent will use less bytes for whitespace than `"useTabs": false` + `"tabWidth": 2`

Out of all of the lines of code, few lines need to use the padded indent. Many files don't even need it at all and have 0 padded indentation lines.

Test it on your own Prettier codebase if you're not afraid.

**Comment by Yzrsah** [comment] 2019-03-06 13:47
`"useTabs": false` + `"tabWidth": 4` can use ~3x more bytes for whitespaces than using `"useTabs": true` + padded-lines-indent

`"useTabs": false` + `"tabWidth": 2` **also** uses more bytes for whitespace than `"useTabs": true` + padded-lines-indent.

Out of all of the lines of code, few lines need to use the padded indent. Many files don't even need it at all and have 0 padded indentation lines.

Test it on your own Prettier codebase if you're not afraid.

**Comment by lydell** [comment] 2019-03-06 15:37
Yeah, I don't buy the "it uses too many bytes on disk" argument either.
