### ISSUE TITLE
Invoking function returned by function

### ISSUE THREAD

**Issue by TrevorSayre** [prettier/prettier#2862] opened 2017-09-19 20:01 UTC
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22export%20const%20firstComp%20%3D%20compose(funcOne%2C%20funcTwo%2C%20funcThree%2C%20funcFour)(component)%3B%5Cn%5Cnexport%20const%20secondComp%20%3D%20compose(funcOne%2C%20funcTwo%2C%20funcThree%2C%20funcFour%2C%20funcFive)(component)%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

When immediately invoking a function returned from a function, if the line length is just right, then the parameters to the invocation are isolated on single lines instead of the parameters to the initial call.

It would be nice if Prettier could favor isolating the longer parameter set. The longer parameter set is the one that is more likely to have additions/deletions in refactoring, and so will benefit from being formatted on a line-by-line basis.

If the parameter counts are equal, favor the parameter set with the longer character count.

As an example, this is incredibly common to deal with when using the `compose` function from Redux, often in a React codebase.

**Input:**
```jsx
export const firstComp = compose(funcOne, funcTwo, funcThree, funcFour)(component);

export const secondComp = compose(funcOne, funcTwo, funcThree, funcFour, funcFive)(component);
```

**Output:**
```jsx
// This seems ugly and unhelpful
export const firstComp = compose(funcOne, funcTwo, funcThree, funcFour)(
  component
);

export const secondComp = compose(
  funcOne,
  funcTwo,
  funcThree,
  funcFour,
  funcFive
)(component);

```

**Expected behavior:**
```jsx
export const firstComp = compose(
  funcOne,
  funcTwo,
  funcThree,
  funcFour,
)(component);

export const secondComp = compose(
  funcOne,
  funcTwo,
  funcThree,
  funcFour,
  funcFive
)(component);

```

**Comment by suchipi** [comment] 2017-09-20 04:56
It may be somewhat difficult to add, but I'd be in favor of this change.

**Comment by ikatyang** [comment] 2017-09-20 05:00
Duplicate of #1420?

**Comment by suchipi** [comment] 2017-09-20 05:04
Looks like it; closing in favor of that one

**Closed by suchipi** 2017-09-20 05:04 UTC
Labels: Needs discussion
