### ISSUE TITLE
Multi-line object being formatted into one line if max line limit isn't exceeded.

### ISSUE THREAD

**Issue by jtodd3** [prettier/prettier#11176] opened 2021-07-08 14:58 UTC
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgFkBPASQx3yOAB0pDDsIIAKASiUIGcZN0AcwA0DAL4MGcAB4AHCJhiFcAIz6Z8SsABtcPHoQBirQqgC2s7XDMIYBspXjUCheo2atOrhkyaQofIQAbrjaAK5EALyuYgDcPr7+gW6+vrKYELJYMKQAjKLuqemZ2aQATAWpTMVZiqQAzJVVNaUALE1FGbU5AKwdhGKE0SHhcPGFhJhwMGGYjADk8+NMElBiIMIgmTCo0DzIoLiYGQDuAApHCPsooSe4pPubKhpgANbTAMqy+ELI-BGbawqOAAExBoIAMrgoIIwrhBHBjJgzLgYDsYcgQLgwjAIBsQAALGBmbQAdQJqHgPG+BA+V0pqCClNImLA+nx6B42TOGkEKOQeG0XM2ACseNIAEIvd4wD64GwQ9BwAWhYUgMXSD5CKwARTCEHgKqFcE230wXMwmJyWR4YAEshg+PS6BgpNQIJgBOQuTKAAZTRkuaSNLJMbd7o8QABHfXwHmZa5YngAWigcFBoPxUxjqCmPPh-KQgrVXLMqD+mABIB42rgeoNyqQ-xNIBgqjdHq9SAqrY0qG0QgAwhAzIWQHAeD18WEuQAVVTXYstoIRSjg2AfO2oB0AQSgII+OSsRq5YjEQA)

```sh
--parser typescript
--print-width 120
--single-quote
--prose-wrap always
```

**Input:**

```tsx
interface MyInterface {
  foo(): string,
}

export abstract class Foo implements MyInterface {
  foo() {
    const value = {};
    const {
      property1,
      property2,
      property3,
      property4,
      property5,
    } = value;
    return '';
  }
}
```

**Output:**

```tsx
interface MyInterface {
  foo(): string;
}

export abstract class Foo implements MyInterface {
  foo() {
    const value = {};
    const { property1, property2, property3, property4, property5 } = value;
    return '';
  }
}

```

**Expected behavior:**
Prior to 2.3.0 the input example would not be formatted into the output example, Prettier didn't turn the multi-line object into a single-line statement. The expected behaviour only happens when we exceed the max line width (120 in our case)

**Comment by thorn0** [comment] 2021-07-08 17:50
> Prior to 2.3.0 the input example would not be formatted into the output example

It would. Just tested it with older versions.

> The expected behaviour only happens when we exceed the max line width (120 in our case)

That's how Prettier works in general. Note that object destructurings and [object literals](https://prettier.io/docs/en/rationale.html#multi-line-objects) are not the same. Prettier has always formatted them differently. The current formatting looks good enough for a comma-separated list of identifiers, so it's unlikely to change. E.g., compare it to how function arguments (another comma-separated list) are formatted. If the line looks too long to you, it probably is, so try reducing `printWidth` (see the recommendations [here](https://prettier.io/docs/en/options.html#print-width)).

I'm going to close this as "works as intended".

**Closed by thorn0** 2021-07-08 17:50 UTC

**Comment by jtodd3** [comment] 2021-07-08 19:12
I understand how Prettier works, my issue is why did the behavior change from 2.2.1 to 2.3.0 though?

**Comment by brodybits** [comment] 2021-07-08 19:24
> why did the behavior change from 2.2.1 to 2.3.0

I tried your input with Prettier 2.2.1 (actually PR #9741 which came very soon before Prettier 2.2.1), seems to be no different:

**Prettier pr-9741**
[Playground link](https://deploy-preview-9741--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgFkBPASQx3yOAB0pDDsIIAKASiUIGcZN0AcwA0DAL4MGcAB4AHCJhiFcAIz6Z8SsABtcPHoQBirQqgC2s7XDMIYBspXjUCheo2atOrhkyaQofIQAbrjaAK5EALyuYgDcPr7+gW6+vrKYELJYMKQAjKLuqemZ2aQATAWpTMVZiqQAzJVVNaUALE1FGbU5AKwdhGKE0SHhcPGFhJhwMGGYjADk8+NMElCrIMIgmTCo0DzIoLiYGQDuAApHCPsooSe4pPubKhpgANbTAMqy+ELI-BGbawqOAAExBoIAMrgoIIwrhBHBjJgzLgYDsYcgQLgwjAIBsQAALGBmbQAdQJqHgPG+BA+V0pqCClNImLA+nx6B42TOGkEKOQeG0XM2ACseNIAEIvd4wD64GwQ9BwAWhYUgMXSD5CKwARTCEHgKqFcE230wXMwmJyWR4YAEshg+PS6BgpNQIJgBOQuTKAAZTRkuaSNLJMbd7o8QABHfXwHmZa5YngAWigcFBoPxUxjqCmPPh-KQgrVXLMqD+mABIB42rgeoNyqQ-xNIBgqjdHq9SAqrY0qG0QgAwhAzIWQHAeD18WEuQAVVTXYstoIRSjg2AfO2oB0AQSgII+OSsRq5YjEQA)
```sh
--parser typescript
--print-width 120
--prose-wrap always
--single-quote
```

**Input:**
```tsx
interface MyInterface {
  foo(): string,
}

export abstract class Foo implements MyInterface {
  foo() {
    const value = {};
    const {
      property1,
      property2,
      property3,
      property4,
      property5,
    } = value;
    return '';
  }
}

```

**Output:**
```tsx
interface MyInterface {
  foo(): string;
}

export abstract class Foo implements MyInterface {
  foo() {
    const value = {};
    const { property1, property2, property3, property4, property5 } = value;
    return '';
  }
}

```
