### ISSUE TITLE
SCSS comments are broken in maps with values that include functions.

### ISSUE THREAD

**Issue by jgerigmeyer** [prettier/prettier#4659] opened 2018-06-08 20:04 UTC
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAtgTwLToIYAOSABABQA6UxxA5AGYQQ0kCMANMQPSfEBijlajQBGeAE7NiAJg7diAIXGDawgK4AvSWDwAbMKRbEA1NICUsnvI3KReTSQAsFhXcqmA3CDYgIBGAEtoAGdkUHExCAB3AAVxBBCUPAA3CH8AEy8QYTE8MABrOBgAZQJc-ygAc2QYMVU4b3KguDEYaJyK-GQ6XSbvACsggA95HPzCorx0OAAZcrgunvqQUrEmsWQQILAgkO8CMXKYAHV0mAALZAAOAAY9iKajnIIN-bg1pPnvMTgAR1V-b5tPAdPALHS9TZwdD+aq1JZBcoVHRwACKqgg8DBEJgeGEJzS52QMhANTw-h0iIAwhB0J0UFBoJ8QKomgAVXEJbrguAAXx5QA)
```sh
--parser scss
```

**Input:**
```scss
$my-map: (
  'foo': 1, // Foo
  'bar': 2, // Bar
  'buz': calc(1 + 2), // Buz
  'baz': 4, // Baz
);
```

**Output:**
```scss
$my-map: (
  "foo": 1,
  // Foo
    "bar": 2,
  // Bar
    "buz": calc(1 + 2),
  // Buz "baz": 4,
  // Baz
);
```

**Expected behavior:**
Ideally:
```scss
$my-map: (
  "foo": 1, // Foo
  "bar": 2, // Bar
  "buz": calc(1 + 2), // Buz
  "baz": 4, // Baz
);
```

But at the very least, this would be most similar to the existing functionality without causing errors:
```scss
$my-map: (
  "foo": 1,
  // Foo
    "bar": 2,
  // Bar
    "buz": calc(1 + 2),
  // Buz
    "baz": 4,
  // Baz
);
```

---
Other example:
```
$spacers: map-merge(
  (
    0: 0,
    1: ($spacer * 0.25), // 4px
    2: ($spacer * 0.5), // 8px
  ),
  $spacers
);
```

**Comment by evilebottnawi** [comment] 2018-06-15 18:35
Bug in parser

**Comment by CiriousJoker** [comment] 2018-10-04 21:52
So what happens now? Do we just wait until that project is fixed?

**Comment by lydell** [comment] 2018-10-05 05:17
@CiriousJoker It's all open source and maintained by volunteers. The first who feels like fixing something in a repo does it.

**Comment by CiriousJoker** [comment] 2018-10-08 13:07
I sadly don't have the time to work my way through the existing sourcefiles of both projects and submit a PR.

For anyone reading this, my temporary solution was to use two formatters for scss files, prettier and some other (don't know atm, just pick one that's not based on prettier). The one file that doesn't work is excluded in prettier. However, this also makes it so that "formatting" a document toggles between the formatting of each plugin, because the other plugin doesn't support .ignore files or exclude flags.

**Comment by jsnajdr** [comment] 2018-12-22 10:07
The parser bug mentioned by @evilebottnawi has a fix proposed in shellscape/postcss-values-parser#60.

**Comment by glen-84** [comment] 2019-08-05 19:04
@evilebottnawi Is this project using `postcss-values-parser` 1.5.0? Can it be updated now?

**Comment by evilebottnawi** [comment] 2019-08-05 19:14
@glen-84 unfortunate no, a lot of breaking changes and css spec violations, it will only make css output worse, i think we need implement own package :disappointed:

**Comment by evilebottnawi** [comment] 2019-08-05 19:14
Not sure about license too https://github.com/shellscape/postcss-values-parser/blob/master/LICENSE

**Comment by evilebottnawi** [comment] 2019-08-05 19:17
For example https://github.com/shellscape/postcss-values-parser/issues/76, very simple bug, what can break many stuff

**Comment by glen-84** [comment] 2019-08-06 18:32
> For example [shellscape/postcss-values-parser#76](https://github.com/shellscape/postcss-values-parser/issues/76), very simple bug, what can break many stuff

I believe that this was fixed in v3.0.5, but it didn't work in v1.5.0 anyway, so I don't see how that would affect the update.

Are there other bugs (regressions) that you are concerned about?

**Comment by evilebottnawi** [comment] 2019-08-07 10:05
@glen-84 we use postcss-less for css-in-js, current version break css-in-js :disappointed: we need switch on postcss-jsx parser for this case, before update something

**Comment by glen-84** [comment] 2019-08-11 13:21
@evilebottnawi Is there an issue for this that I can follow?

**Comment by evilebottnawi** [comment] 2019-08-12 10:40
@glen-84 no issue, it is idea, not sure it will be work, so need experement

**Comment by 7iomka** [comment] 2019-09-28 16:11
How to fix this issue?(
![ezgif-2-7289459cf401](https://user-images.githubusercontent.com/18473137/65819331-c4808300-e223-11e9-95d3-ad0855e520bf.gif)

**Comment by jpdutoit** [comment] 2019-10-08 13:31
Some more examples here: https://github.com/prettier/prettier-vscode/issues/856

**Comment by robert-j-webb** [comment] 2020-02-15 23:44
Look like this is no longer happening on master. I'll add a PR to demonstrate that.

**Comment by jsnajdr** [comment] 2020-02-18 09:45
> Look like this is no longer happening on master.

@robert-j-webb I think that's because `postcss-values-parser` was upgraded from 1.5.0 to 2.0.1 in #6804. And 2.0.1 includes my bugfix from https://github.com/shellscape/postcss-values-parser/pull/60 that I did a year ago.

**Comment by boyenn** [comment] 2020-06-15 13:34
as https://github.com/prettier/prettier/pull/7591 is merged, this can be closed.

**Closed** 2020-06-15 13:52 UTC
Labels: lang:css/scss/less, priority:high, scope:dependency, type:bug
