### ISSUE TITLE
Add option to add a "ignore" section in package.json prettier config instead of using a .prettierignore file

### ISSUE THREAD

**Issue by azizuysal** [prettier/prettier#7676] opened 2020-02-26 23:07 UTC
Please add an option to add a "ignore" section within the "prettier" key in package.json config option. The whole point of using package.json for prettier config is to keep most, if not all configs, in one file, and having to add a separate .prettierignore file goes against that convention. Thank you.

**Comment by thorn0** [comment] 2020-02-26 23:27
Duplicate of #3460

**Closed by thorn0** 2020-02-26 23:27 UTC
