### ISSUE TITLE
Question on implementing "printers" in plugins

### ISSUE THREAD

**Issue by bd82** [prettier/prettier#5747] opened 2019-01-11 20:26 UTC
Hello.

I am working on [prettier-java](https://github.com/jhipster/prettier-java)
And do not fully understand the way printers are implemented.

The [official docs](https://prettier.io/docs/en/plugins.html#printers) say:
> Printing is a recursive process of converting an AST node (represented by a path to that node) into a doc. The doc is constructed using the builder commands:

And I can inspect an example in the python plugin printer:
```javascript

    case "Lambda": {
      return group(
        concat([
          "lambda",
          " ",
          path.call(print, "args"),
          ": ",
          path.call(print, "body")
        ])
      );
}
```
What I do not understand is why the "path" argument is needed.
Assuming:
- I have a data structure representing the source code (in my case it is a CST - Concrete Syntax Tree) not an AST.
- I already have utilities to recursively traverse this data structure.

Could I simply traverse my CST and invoke the "builder" commands as needed?
Without using the path for traversal? 

In what cases would this path be required?

Cheers.
Shahar.

**Comment by j-f1** [comment] 2019-01-11 20:59
The path is a state object. It stores the current node that’s being printed and it makes it easier to recurse. It also allows, if I remember correctly, for embedding languages inside other languages, for example using heredocs.

**Comment by j-f1** [comment] 2019-01-11 23:37
I’m not sure traversal is what you want — with Prettier, you’ll probably find yourself doing the traversal manually.

**Comment by bd82** [comment] 2019-01-12 00:19
It is best if I demonstrate via code.

Let me prototype what I want to demonstrate first and I will link it here afterwards.
If I forget to update here the results of my POC will be posted in this issue
https://github.com/jhipster/prettier-java/issues/107

**Comment by ikatyang** [comment] 2019-01-12 10:18
`FastPath` is used for getting parent nodes in an efficient way, sub-language printing (`printer.embed`), comment printing (`printer.{printComment,handleComments,...}`), and some built-in functionalities such as `prettier-ignore` (`printer.hasPrettierIgnore`).

> Could I simply traverse my CST and invoke the "builder" commands as needed?
Without using the path for traversal?

It's fine to not use `path` if you don't want to use those built-in functionalities.

**Comment by bd82** [comment] 2019-01-12 11:40
Some of those capabilities some useful and relevant, so I may need to find workarounds for those.
Some of that functionality (comments/prettier-ignore) sounds like logical manipulation and analysis of string literals.
So in theory it sounds like it does not have to be necessarily coupled to the FastPath
and/or could be (re-)implemented as pure utilities.

Keep in mind, I don't actually know what is going on under the hood and have still
not implemented even a single prettier "printer" 😄 So I am likely not understanding the scenario / context completely.

I guess I will learn by doing and be wiser once I have actually written some prettier "printer" code.

You can either close this issue, or keep it open if you want me to post links and examples to
my work here for farther discussion in the future. 

Cheers.

**Comment by j-f1** [comment] 2019-01-12 12:47
Feel free to continue to comment if you have questions/concerns, but I’m closing this for now since it’s not a bug/feature request.

**Closed by j-f1** 2019-01-12 12:47 UTC
Labels: type:question

**Comment by bd82** [comment] 2019-02-04 14:47
Hi again @j-f1 this is not a question but perhaps you would like to see a working example of what I discussed earlier (traversing the data structure without using FastPath).

https://github.com/bd82/toml-tools/blob/4a449cc6b54c5f74c6342e51e16c5e13f82bad8f/packages/prettier-plugin-toml/lib/printer.js#L147-L168
- "this.visit" would invoke the correct handler method for each node type.
- The different handlers invoke the prettier build commands to create and recursively combine
   the "Docs" objects.

This is a live working example that could be resolved by your suggestions in 
https://github.com/prettier/prettier/issues/5438#issuecomment-437666185
to extract the builder utils to a separate npm package.

My toml plugin should not depend on the whole prettier package, only a few utils that build a "Doc" object. It does not even use the FathPath...

Cheers.

**Comment by bd82** [comment] 2019-02-04 17:56
> How do you handle comments?

## Toml
In Toml Comments are only allowed in specific points in the grammar.
So they are explicitly parsed in the grammar instead of being collected or skipped by the Lexer.
- [example of comments parsing](https://github.com/bd82/toml-tools/blob/0f827ce7dd7805ca8234bfbd5830e80458bdeb7e/packages/parser/lib/parser.js#L42-L55)

So handling of comments is just like handling any other grammar constructs.
- [Printing of the rule with comments shown above](https://github.com/bd82/toml-tools/blob/master/packages/prettier-plugin-toml/lib/printer.js#L127-L145)

## Prettier-Java
In prettier-java (which uses the same parsing library and data structures) it would be more complicated as comments are allowed **everywhere** in Java. So an additional step
would be needed to attach the comments to the CST produced by the parser.
and a more **generic** comment printing concept would be needed as comments could appear as part of **any CST node**.
