### ISSUE TITLE
Format JSON.parse string literals

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier#7043] opened 2019-11-24 07:14 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEApAygeQHIDoAOAhgE4DOcAFAOTAA6I+xE+cxMAnvUvQG6EA2AVzj0AvlQCUAblpQMOAiXIADOgyYs2nZLwHCxyqSAA0IZjACW0UslAkmAdwAKJBDZSEeECwBMTIACNiQjAAazgYdCIwCygAc2QYYmFTAAsYAFt+AHVUi3hSaLh0N3yLHnz2ZHBSG1NY8jYnYLiMwmQAMwFyUwArUgAPACFgsIj0Qgy4ABlYuE7uuD7B9Fi4-jgARUEIeAX+HoYlVmqAwgC4fn9GWJhs3xhU5AAOAAZTRghybOD8asY4I0ePNTABHHbwZrMdwgQikAC0UDgcB8KP8xDg4IsGOahFa7SQXQOSxA5AyFkSyRJpDWG22u3mhMWphg53uPkeyAATCzghZ+GsAMIQDJtapQaAgkCCcgAFXO7iJhx4wgAklBUbB0GBiBZ8DAAIIa9AcDb7ciiURAA)
```sh
--parser babel
```

**Input:**
```jsx
JSON.parse('{"property":"value"}');
JSON.parse`{"property":"value"}`;
```

**Output:**
```jsx
JSON.parse('{"property":"value"}');
JSON.parse`{"property":"value"}`;

```

**Expected behavior:**
```jsx
JSON.parse('{ "property": "value" }');
JSON.parse`{ "property": "value" }`;

```

For more complex JavaScript objects, it can be faster and more reliable to use `JSON.parse` with an inline string rather than just using an object literal ([explanation](https://www.youtube.com/watch?v=ff4fgQxPaO0)). It would be useful if Prettier could format strings passed directly to `JSON.parse` as embedded JSON, so they look like what would happen if you loaded and parsed a separate JSON file formatted with Prettier. Note that template strings work with `JSON.parse` in JavaScript, but we'd have to handle edge cases when formatting template variables.

**Comment by thorn0** [comment] 2019-11-24 10:25
I suppose this issue can be considered a duplicate of #5908.

**Comment by nickmccurdy** [comment] 2019-11-24 12:02
Would that also cover automatic support for JSON when JSON.parse is used?

**Comment by thorn0** [comment] 2019-11-24 14:21
It definitely wouldn't be automatic. A special comment, an option or something else would be needed to trigger it. See #5588, #6626.

**Comment by thorn0** [comment] 2021-02-09 14:53
Closing in favor of #5588

**Closed by thorn0** 2021-02-09 14:53 UTC
Labels: area:multiparser, lang:javascript, status:needs discussion
