### ISSUE TITLE
CRLF Change to LF

### ISSUE THREAD

**Issue by ttib1299** [prettier/prettier#9677] opened 2020-11-14 17:29 UTC
**VScode extension Prettier - Code formatter 5.7.2**

```sh
# Options (if any):
endOfLine
```

**Input:**

```
// a.js file
// endOfLine CRLF
```

**Output:**

```
// a.js file
// endOfLine CRLF
```

**Expected behavior:**

```
// a.js file
// endOfLine LF
```
after formatter, 
I want to change file to LF, but it still is CRLF

I use VScode extension Prettier.
```
// settings.json
{
"editor.formatOnSave": true,
"prettier.semi": false,
"prettier.singleQuote": true,
"prettier.endOfLine": "lf",
"prettier.useEditorConfig": false
}
```

I expect it change to LF, after I save file.
All the other options are work, like 'semi', 'singleQuote'.
They all will format after I save file.
But option endOfLine is not work.

**Comment by kachkaev** [comment] 2020-11-14 17:40
Please use the issue template. If the problem is VSode only, the right repo is https://github.com/prettier/prettier-vscode

**Comment by ttib1299** [comment] 2020-11-15 16:35
The problem is in VScode.
The issue is already here.
[#1327](https://github.com/prettier/prettier-vscode/issues/1327)

**Comment by thorn0** [comment] 2020-11-15 16:51
@ttib1299 Can you reproduce the issue running Prettier from the command line?

**Comment by ttib1299** [comment] 2020-11-15 16:56
> @ttib1299 Can you reproduce the issue running Prettier from the command line?

It's work in prettier CLI, but not work in VScode Prettier extension

**Comment by thorn0** [comment] 2020-11-15 17:00
Closing since it's not an issue with Prettier itself.

**Closed by thorn0** 2020-11-15 17:00 UTC
