### ISSUE TITLE
line-break following `return` leads to incorrect conversion with regard to semicolon

### ISSUE THREAD

**Issue by jngbng** [prettier/prettier#13778] opened 2022-11-01 23:45 UTC
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwB0QdTyG6o2KBXKc1afJjE44oAKQDKADQAUASnzA2+AXCEily-NIA8AE1QA3AHwbNASXwlaMABaowAa3wAjCLoCep5doD0+47IA3GwAvmwc3Lz8gsJQADKo8DgkADZyChox6lCaWgCM+ADU+HkADEGhIAA0IBCYMHxQAM7IoCQ41ADuAArtCC0oqZ0k7i01zsmOquJWcAlQcMgUqU1w45MO05hkqFAA5sgwOJxrIHDoznC6uldxJPucJHtwAGK46CQwDfvIICScMAg1RANhg6BSAHU7PAmtswHBxP1EoZEu5fmAmmM0M04Hhusk9h8litTgArJoAD3Euz2KTgAEVOBB4MSUqsatscKscL9nCRLilgZgcLsYBDULpbMgABylDnUVYQ5KYX7CuDcgyLGoARyZ8HxdQGfyaAFoFlcrsCmLrUEx8U8iUhlmzTqt0KhDsdXTS6YzmYsnSSajB+eLJTZkAAmYPJVApGkAYRojrOTQArMDOKsACr8gbO9kgAwnMxQG6wcRgEX1ACCZfEMHcdNZqxCISAA)

```sh
--parser babel
```

**Input:**

```jsx
import React from "react"

function returnJSX() {
  return
    (<div>
     I am thick body
     </div>);
}

function returnLiteral() {
  return
    (1 + 10);
}
```

**Output:**

```jsx
import React from "react";

function returnJSX() {
  return;
  <div>I am thick body</div>;
}

function returnLiteral() {
  return;
  1 + 10;
}

```

**Expected behavior:**

```jsx
import React from "react";

function returnJSX() {
  return <div>I am thick body</div>;
}

function returnLiteral() {
  return 1 + 10;
}
```

The semantic of the program has changed in critical way..

**Comment by kachkaev** [comment] 2022-11-02 00:26
👋 @jngbng! Looks like this is expected behavior. You can try your example in https://astexplorer.net to find out how JavaScript return statements are parsed. A semicolon [is automatically inserted](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/return#automatic_semicolon_insertion) after `return` if the rest of the line is empty. So Prettier does the right thing: it sees two JavaScript statements and puts `;` in between. If you did not do so, you could believe that there was one statement instead of two. Removing newline would also be bad because in that case Prettier would transform your code and this is [out of scope](https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about).

**Closed by kachkaev** 2022-11-02 00:26 UTC
