### ISSUE TITLE
Bug: --no-semi adds ; before destructuring assignments

### ISSUE THREAD

**Issue by larsenwork** [prettier/prettier#4558] opened 2018-05-27 07:10 UTC
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtacA0ACGB3CHGACwCc44BdbAXmygFcBbAIzlIGcAdKETECAAcYAS2gdkoAIalSEPAAUZCCSikA3CCIAmfEC1JSwAazgwAyoKMioAc2QxSDLCBsd2MBYdtMpyAGZSADbu-ABWHAAeAEKGJmbmUkxwADI2cAHBoSBWnOzI+lIsAJ5B0HqCpDYwAOo6JMgAHAAM-JUQ7jWGggWVcO6k6hn85ACODCLkXlI+fkiBIS7uTCKZi-wcNrZBcACKDBDwa9kwRXXaDUgATPyOUiJBWwDCEEy+BVAYegzuACpFqgW7gAvsCgA)
```sh
--no-semi
```

**Input:**
```jsx
[one, two, three] = numbers

```

**Output:**
```jsx
;[one, two, three] = numbers

```

**Expected behavior:**
```jsx
[one, two, three] = numbers

```

**Comment by ikatyang** [comment] 2018-05-27 07:14
See https://prettier.io/docs/en/rationale.html#semicolons.

**Comment by ikatyang** [comment] 2018-05-27 07:14
Duplicate of #4316

**Closed by ikatyang** 2018-05-27 07:14 UTC
