### ISSUE TITLE
Prettier not formatting this line correctly

### ISSUE THREAD

**Issue by hesher** [prettier/prettier#2100] opened 2017-06-11 11:16 UTC
Prettier can't format this line. (Line width = 110)

```
import ActiveSitesTableComponent, {ActiveSitesStateProps} from '../../components/SitesTable/ActiveSitesTableComponent';
```
The result is a line that is too long.

**Comment by k15a** [comment] 2017-06-11 11:29
There is a similar issue with typescript type import.

**Comment by k15a** [comment] 2017-06-11 11:32
The issue is already fixed in #2096

**Closed by k15a** 2017-06-11 11:32 UTC
