### ISSUE TITLE
Unexpected closing tag "p" with vue parser, but only in very weird and specific cases

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [prettier/prettier#14947] opened 2023-06-17 19:20 UTC
only happens to the last `<p>` tag in an outer block, and only if the p tag has content.

**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlKgM5xgwCW0JUABMy6246lg+z26gBYBmQnnIATAGajJqAPRDuvHnK6klLOZWp0oiuZlwE4hEABoQELLWjlkoPACcHEAO4AFRwlso8OF3gBPW3MAIwc8MABrOBgAZTwMOAAZGig4ZCkcSlDwqJjYrAjUgHNkGAcAVzhzOAwQuDExBqS8KGKKvGK4ADEIBwwCWjbkEDwKmAgzEH4YDBwAdX4aeHJCsDhYr2WaADdlgJGwcmCQVMoHGDdw4oGM32yQACtyAA9Ykpw4AEUKiHg7rLVECFBznEY7KpTLAOVIweY0MQwfjIAAcAAZzNCIJR5uEsCNoXBzjt0uYAI6-eBXSzeUbkAC0aQaDSmDjgFJobKunVuSEyD0oGBoZUqQPIHzgAEEYOUaCFxnA3HAHCk0gCBRKfn90nz7kCYHgQvDEcikAAmczlPA0HAlADCEAwvJARIArFMKpQACqG7z8oEQuAASSgTVgsTAMKsktDsRgAU+6rgAF9k0A)

```sh
--parser vue
```

**Input:**

```vue
<template>
<section>
                <p>
                  <h3>asdfasdf</h3>
                </p>
            </section>
  </template>
```

**Output:**

```vue
SyntaxError: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (5:17)
  3 |                 <p>
  4 |                   <h3>asdfasdf</h3>
> 5 |                 </p>
    |                 ^^^^
  6 |             </section>
  7 |   </template>
```

**Expected behavior:**

document is formatted without error

**Comment by alexander-akait** [comment] 2023-06-17 19:36
Duplicate of https://github.com/prettier/prettier/issues/14946

**Closed by alexander-akait** 2023-06-17 19:36 UTC
Labels: type:duplicate

**Comment by SIGSTACKFAULT** [comment] 2023-06-18 00:20
oops
