### ISSUE TITLE
Less: Format adds additional semi-colon on each formatting iteration

### ISSUE THREAD

**Issue by NiklasPor** [prettier/prettier#10665] opened 2021-04-09 07:45 UTC
Less rulesets create some formatting issues with prettier. Details below. Ruleset example from the documentation: http://lesscss.org/functions/#list-functions-each

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAznAbnATgSxnznSQAJgAdKMsgEwEMoBzPc1LB3AWkZbwDc1WgHcuUfC3aceY3BJZCaZdAFcwYEqTIcu3NRq1KAvgJAAaEBAAORaOmSguuCCIAKXBA5QMANmIBPB0sAI1wGMABrOBgAZWsIyWZkGFxVOEs4AFsQuDo6PIAZJmZVBlYAMQhcLIYYIhZkEAZVGAgLEAALGCzfAHVOwhIEzVivQnwsQgCmsHRgkElMXBg3cOZa5AAzP0xLACt0AA8AIXComNiGLLhCyTht3YyQQ6PYpN84AEVVCHhH3x7EAJXDLJqfeYdawEWB9fB0GCdZAADgADJZoRBMH1wtYmtCSHgcB0AI6-eBrGzeZrobhQOB5PIdXBwMn4FlrcqbJA7QHPTBZfApNL8j7fckPHlPSwwBghOEIpFIABMMvC+F8SQAwhAstyQCQAKwdVSYAAqcu8vKBWHSAEkoAVYLEwARbABBR2xGABT4AzDGYxAA)

```sh
--parser less
```

**Input:**

```less
@severities: {
  danger: @var-danger;
  warning: @var-warning;
  success: @var-success;
};
```

**Output:**
> This will add a ` ;` at the end of this code snippet each time the file is formatted. If you have turned on format on save, you quickly get multiple instances of ` ;` at the end of the line.

```less
@severities: {
  danger: @var-danger;
  warning: @var-warning;
  success: @var-success;
}; ;

```

**Expected behavior:**
```less
@severities: {
  danger: @var-danger;
  warning: @var-warning;
  success: @var-success;
};
```

Thanks for your time 🚀

**Comment by thorn0** [comment] 2021-04-09 11:52
Duplicate of #2281

**Closed** 2021-04-09 11:54 UTC
Labels: type:duplicate
