### ISSUE TITLE
Space between the function name and the parenthesis?

### ISSUE THREAD

**Issue by george-norris-salesforce** [prettier/prettier#4888] opened 2018-07-24 21:25 UTC
What is the option to enforce a space between the function name and the parenthesis? Either there is not option, or it is impossible to find in the docs. Thanks! Prettier appears to enforce NO space between a function name and the parenthesis, but I'm not seeing a way to undo this option.

**Comment by bakkot** [comment] 2018-07-24 21:40
There's no option currently, as with most things; prettier [does not generally intend](https://prettier.io/docs/en/option-philosophy.html) to be a project with option for small style differences like this. There's more discussion in #3845.

I'm going to close this as a duplicate of that issue.

**Closed by bakkot** 2018-07-24 21:40 UTC

**Comment by j-f1** [comment] 2018-07-25 12:07
Duplicate of #3845
