### ISSUE TITLE
[LESS] extra space for pseudo elements inside :extend

### ISSUE THREAD

**Issue by airato** [prettier/prettier#8205] opened 2020-05-01 19:09 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbAMiTgA94oATAClQCMBDAJySfXhYEoBuAgL4gANCAgAHGAEtoAZ2ShWLCAHcACqwTyUTAG4Qp1ESAYsmYANZwYAZXHmpUAObIYLAK5xRACxgBbABsAdW8peFl7MDgbLTCpXTCAT2RwWXlRR1k4Fhg1Myc-JmR0JgCs0QArWXIAITNLaxsmPzgAGUc4YtLykCryG0cnALgARXcIeC6yrxB7FiyWFOG043EWRxggwxhvZAAOAAZRNYgsoLNxFLW4Bd1O0QBHcfg8iW0QJlkAWig4OGp-sYWHAnlJgXkmAUikgStNRFk-FJXB4ZrJBsMxhNOjDujMYEwGFtqDtkAAmURuJhSAKDADCED8hRSUGg9xA7iyABUCdpYT1dJ4AJI0BC2MDrSQAQRoNhgiWGUyyAgEQA)
```sh
--arrow-parens avoid
--parser less
--trailing-comma none
```

**Input:**
```less
.foo {
  &:extend(.bar:after);
}
```

**Output:**
```less
.foo {
  &:extend(.bar: after);
}

```

**Expected behavior:**:
```less
.foo {
  &:extend(.bar:after);
}
```

**Comment by fisker** [comment] 2020-05-01 19:21
This is duplicate of #8177 and  fixed  in #8178

**Closed by fisker** 2020-05-01 19:21 UTC
Labels: type:duplicate
