### ISSUE TITLE
HTML comments inside inline templates in Angular

### ISSUE THREAD

**Issue by walrus95** [prettier/prettier#5638] opened 2018-12-14 15:09 UTC
Hello,

I'm writing to report an issue where Prettier fails to output valid code that has the exact same behavior as before formatting.

I have a file with the following content:

`> type new.ts`

```
@Component({
    selector: 'app-thing',
    template: `
        <!-- button mat-menu-item
            id="my-button"
            (click)="myData()">
            My Dialog
        </button -->
    `,
})

export class MyComponent {}
```

When I format with Prettier, I get output which is not a valid HTML comment.

`> node .\node_modules\prettier\bin-prettier.js new.ts`

```
@Component({
  selector: "app-thing",
  template: `
     <!-- button mat-menu-item
            id="my-button"
            (click)="myData()">
            My Dialog
        </butto
  `
})
export class MyComponent {}
```

This is a problem in Angular applications. This code was taken from the codebase of an Angular application.

I am running the following:

```
> node .\node_modules\prettier\bin-prettier.js -v
1.15.3

> node -v
v8.12.0
```

**Comment by ikatyang** [comment] 2018-12-14 15:19
Hi, this is a Windows-specific issue caused by CRLF, which should be fixed by #5494. As a workaround, you could install the dev version from GitHub (`npm install prettier/prettier`) or place a `// prettier-ignore` in front of it:

```tsx
@Component({
    selector: 'app-thing',
    // prettier-ignore
    template: `
        <!-- button mat-menu-item
            id="my-button"
            (click)="myData()">
            My Dialog
        </button -->
    `,
})

export class MyComponent {}
```

**Closed by ikatyang** 2018-12-14 15:19 UTC
