### ISSUE TITLE
Commented out ternary else case next to JSX is duplicated instead of being properly formatted.

### ISSUE THREAD

**Issue by Mitsunee** [prettier/prettier#13685] opened 2022-10-19 10:01 UTC
Version: Prettier 2.7.1
Config:

```json
{
  "printWidth": 80,
  "tabWidth": 2,
  "semi": true,
  "singleQuote": false,
  "jsxSingleQuote": false,
  "trailingComma": "none",
  "bracketSameLine": true,
  "arrowParens": "avoid"
}
```

**Input:**

```jsx
  return (
    /*isClamped({ value: interval, max: startsAt }) ? */
    <Section className={styles.section} background>
      <span>
        {text}: {delta} ({date})
      </span>
      {icon && <img src={icon} alt="Icon" className={styles.icon} />}
    </Section> /* : null*/
  );
```

**Output:**

```jsx
  return (
    /*isClamped({ value: interval, max: startsAt }) ? */
    <Section className={styles.section} background>
      <span>
        {text}: {delta} ({date})
      </span>
      {icon && <img src={icon} alt="Icon" className={styles.icon} />}
    </Section> /* : null*/
   /*: null*/);
```

**Expected behavior:**

Commented out ternary is not duplicated.

**Actual behaviour:**

The `/*: null*/` comment is duplicated with every run, which causes non-formatted code that does not pass a `prettier -c .` check in CI. I have also recorded a video of the behaviour with repeated runs: https://cdn.discordapp.com/attachments/908052378685685801/1032230690760175727/2022-10-19_11-49-52.mp4

**Context:**

The file that this code snippet is from is for a temporary component that I adjust everytime I need it. This time I didn't need the `isClamped` condition, so I commented it out and added parenthesis around the JSX statement to prevent a semicolon from being autocompleted like: `return;`. I have prettier ran on every file as part of a nano-staged precommit hook and am checking `prettier -c .` in CI, which failed due to this comment duplication.

As a workaround I decided to try the following, which does not create the same duplication behaviour, so the issue seems to be specifically with `/* foobar */` style comments:

```jsx
      {icon && <img src={icon} alt="Icon" className={styles.icon} />}
    </Section> // : null
  );
```

**Comment by thorn0** [comment] 2022-10-19 10:46
Duplicate of #6995

**Closed** 2022-10-19 10:46 UTC
Labels: type:duplicate

**Comment by thorn0** [comment] 2022-10-19 10:47
Related:
- https://github.com/prettier/prettier/issues/9564#issuecomment-720876573
- https://github.com/prettier/prettier/issues/13142#issuecomment-1239479444
