### ISSUE TITLE
URL broken in CSS

### ISSUE THREAD

**Issue by aravindvnair99** [prettier/prettier#7053] opened 2019-11-25 20:49 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgWwA4QE4wAEArngDYAUA5ABYwzZID0TAZtDAM4B0A5hBF5k4AQ2zoekTEzCdOAflYjM6MgE8AvAHlsCANQBlEVE5IALAAYLAGgDMV6wDYHAditUAlAG4AOlAw4+ESklHQMzGwcPPyCwmIS3FIycorKqpoASiLCAO4iauYOfj4w9jbFMABMRVAlAIw1JQCsjTDO5bUwbh0lABytAJxWft4g1iAQ2DDo0JzIoCJ4eBA5AAqLCHMoIgBuEOgAJmMgAEZ4ImAA1nAwBtgX6FC8yDB4xHDjdJhkAOo06PBOPcwHADJsAegdgC1MhwHJjo9OHACKtzrxMCJkEoyEjxgArTgADwAQucrjcjJg4AAZR5wLHZXEgAmEgyPIRwACKxAg8AZOI+IHueCReFhsjm42weEeMB+hxgNGQ-SlyyRP3O2Fh0rgop29PGAEcefBUZMtiARJwALRQOBwA4O454ODG9Au1EidGYpDYplIlQvN6Czjs4Tc3n0pCvd7jGAiE7yg6K5BmOPnVTsgDCEEwGNhUGgBpAxCRABUE1sY4Kdu8AJJQR2wAxgGVTACCjYMMDUwn5SIAvgOgA)
```sh
--parser css
--single-quote
--tab-width 4
--use-tabs
```

**Input:**
```css
@import url('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700');
@import url(http://fonts.googleapis.com/css?family=Raleway:400,
	300,
	200,
	100,
	500,
	600,
	700,
	800,
	900
);
```

**Output:**
```css
@import url('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700');
@import url(
	http://fonts.googleapis.com/css?family=Raleway:400,
	300,
	200,
	100,
	500,
	600,
	700,
	800,
	900
);

```

**Expected behavior:**

```css
@import url('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700');
@import url(http://fonts.googleapis.com/css?family=Raleway:400,300,200,100,500,600,700,800,900);

```

**Comment by aravindvnair99** [comment] 2019-11-25 20:52
Just came across https://github.com/prettier/prettier/issues/2835 for v1.7 whereas, we are on v1.19.1 now. Duplicate?

**Comment by lydell** [comment] 2019-11-26 08:58
Duplicate of #2835

**Closed by lydell** 2019-11-26 08:58 UTC
