### ISSUE TITLE
In this example, the array literal is expanded, but its parent function call arguments should be expanded instead

### ISSUE THREAD

**Issue by roryokane** [prettier/prettier#1377] opened 2017-04-21 16:23 UTC
With this input:

```javascript
assert.deepEqual(Arrays.simd((a, b, c, d) => a * c + b * d, [0, 1, 2], [6, 3, 7], [3, 1, 7], [7, 0, 2]), [42, 1, 28]);
```

When formatted [with `printWidth` = 100][100], it looks good:

```javascript
assert.deepEqual(
  Arrays.simd((a, b, c, d) => a * c + b * d, [0, 1, 2], [6, 3, 7], [3, 1, 7], [7, 0, 2]),
  [42, 1, 28]
);
```

But [with `printWidth` = 110][110], it is harder to read:

```javascript
assert.deepEqual(Arrays.simd((a, b, c, d) => a * c + b * d, [0, 1, 2], [6, 3, 7], [3, 1, 7], [7, 0, 2]), [
  42,
  1,
  28
]);
```

When the `printWidth` is 110, Prettier should format the code as it did at the width of 100.

I’m not sure exactly how Prettier could tell that the 100-width version looks better, but it's related to not putting text with small width on its own line when it could be combined into another line. Maybe the heuristic could be as simple as “the fewer lines in the output, the better”.

It appears that when expansion is needed to make the code fit the width, Prettier only considers expanding the last and deepest AST node. If that’s true, the solution to this issue probably involves trying to expand not only the last and deepest AST node (`[42, 1, 28]`), but also each of its ancestors (`Arrays.simd(…)` and `assert.deepEqual(…)`), one at a time, and then choosing the best output according to the heuristic outlined above.

[100]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22assert.deepEqual(Arrays.simd((a%2C%20b%2C%20c%2C%20d)%20%3D%3E%20a%20*%20c%20%2B%20b%20*%20d%2C%20%5B0%2C%201%2C%202%5D%2C%20%5B6%2C%203%2C%207%5D%2C%20%5B3%2C%201%2C%207%5D%2C%20%5B7%2C%200%2C%202%5D)%2C%20%5B%5Cn%20%2042%2C%5Cn%20%201%2C%5Cn%20%2028%5Cn%5D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A100%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
[110]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22assert.deepEqual(Arrays.simd((a%2C%20b%2C%20c%2C%20d)%20%3D%3E%20a%20*%20c%20%2B%20b%20*%20d%2C%20%5B0%2C%201%2C%202%5D%2C%20%5B6%2C%203%2C%207%5D%2C%20%5B3%2C%201%2C%207%5D%2C%20%5B7%2C%200%2C%202%5D)%2C%20%5B%5Cn%20%2042%2C%5Cn%20%201%2C%5Cn%20%2028%5Cn%5D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A110%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by lemon79** [comment] 2017-04-21 21:52
i also ran into this bug in last issue, this is a big problem

**Comment by vjeux** [comment] 2017-04-21 23:03
@roryokane thanks for the report! So, we do expand the last argument when it's an array which is what you want in most cases. We found a good heuristic to apply when you --don't-- want this heuristic: if the previous argument is of the same type, then both are likely of equal meaning and therefore the last one shouldn't be expanded.

```js
call([1, 2, 3], [4, 5, 6])
```

should be

```js
call(
  [1, 2, 3],
  [4, 5, 6]
)
```

and not

```js
call([1, 2, 3], [
  4,
  5,
  6
])
```

In this case, this heuristic is super close, the issue is that there's a function call in between :( I'm not yet sure how to address this.

As for all your suggestions, prettier doesn't work like this. It has a very simple model where if all the children don't fit in one line, then it's going to group the parent. And do that recursively. If we implement your suggestions, you have a complexity that is exponential that can take an extraordinary amount of time to complete on some slightly degenerate cases.

@lemon79 could you give a concrete example when it happened for you?

**Comment by lemon79** [comment] 2017-04-22 01:23
@roryokane @vjeux if the array has one long element and several short elements, the model is going to print all elements on separate lines. for example, 

[
    "verylongitem1inanarray",
    "verylongitem2inanarray",
    "verylongitem3inanarray",
    b,
    c,
    d,
    e
  ]

but it might be easier to consider only not to break the second array in your example. i am thinking about adding an array length check in util before splitting.

**Comment by lemon79** [comment] 2017-04-22 02:20
@roryokane your bug is too hard

**Comment by lemon79** [comment] 2017-04-23 18:49
@roryokane @vjeux 
changing the fits and printDocToString functions in doc-printer can move the last array to the next line without breaking it, but the change causes massive test fails like the following:

    -export type FileMetaData = [
    -  /* id */ string,
    -  /* mtime */ number,
    -  /* visited */ 0 | 1,
    -  /* dependencies */ Array<string>
    -];
    +export type FileMetaData = [/* id */ string, /* mtime */ number, /* visited */ 0
    +    | 1, /* dependencies */ Array<string>];

i think the issue needs redefine some heuristics

**Comment by vjeux** [comment] 2017-05-22 01:23
I do not know of a good solution to fix this unfortunately, I'm going to go ahead and close this issue. If someone finds a good solution, please let me know :)

**Closed by vjeux** 2017-05-22 01:23 UTC
Labels: Needs discussion

**Comment by roryokane** [comment] 2018-02-06 17:36
I think I see a good solution. What if Prettier had the heuristic to try breaking only at two positions, and compare those two breaking points using the goodness heuristic? If you only compare two possible break points for each time you are too wide, you aren’t at risk of being exponentially slower. At worst, Prettier would be twice as slow, and since breaking does not take 100% of Prettier’s time it wouldn’t be that bad.

As for what two positions to compare, naturally one choice would be the closest parent expression to the text that makes the line too long. And for the other one, I suggest the highest-level expression that is not already broken. In the example above, the closest parent expression is the `[]` containing `42, 1, 28`, and the top-level unbroken expression is `assert.deepEqual`, which is also what should be broken ideally.

This heuristic would also work in this larger example, where the problematic code is within other code blocks:

~~~javascript
describe('math', () => {
  it('can calculate simd and other stuff', () => {
    assert.deepEqual([5, 10, 15].map(n => n * 1, [5, 10, 15]));
    assert.deepEqual(Arrays.simd((a, b, c, d) => a * c + b * d, [0, 1, 2], [6, 3, 7], [3, 1, 7], [7, 0, 2]), [42, 1, 28]);
    assert.deepEqual([5, 10, 15].map(n => n + 1, [6, 11, 16]));
  });
});
~~~

When Prettier considers breaking the `[42, 1, 28]` on the long line with `simd`, it would compare breaking that `[]` with `assert.deepEqual`, because the expression directly above `assert.deepEqual` is the `() => {}` of the `it`, and that `() => {}` is already broken. After comparing only those two options according to the number of lines they result in or some other heuristic, it could see that breaking `assert.deepEqual` makes better-looking code.

I admit, that code snippet with `simd` is the only time I have seen this problem. So, while you should reopen this issue, you don’t have to make resolving it a priority.
