### ISSUE TITLE
No line break for type annotations in variable declarations exceeding 80 characters

### ISSUE THREAD

**Issue by merlinnot** [prettier/prettier#6899] opened 2019-11-09 12:45 UTC
**Prettier 1.19.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBzOMCqUArmnACYCCRMAFhAE4CWAXgIYyPQASEANmQBEIYIgFsEMNJgC8mVmgCeUMJgAUASiSYACvQijGpADxCR42APasA2gF0AfDMfAAviAA0ICAAcO6ZKCs9HoA7tpBCGjIIKwAbhCMZB4gAEb0rGAA1ngAyt4ZjFDYyDD0RHCeNDCivADqNIzwaPlgcDmRjYyxjQrRYGhRnoWk9DC6rNiirMgAZqy8pJ4AVmgAHgBC6Vm5rOIAMoVws-OLICurOYXYvHAAikQQ8McLFSD59CPRMArecGhgTF8yW8TFgtUStGQAA4AAyeEEQUi1dLeaIgv5weixI6eACOD3guh8URQ8gAtFA4ORyMl6HB8Yw6eNJtMkHMXp5SAYSmVXmgrjd7o8jmyTq8YKwUuCyJCkAAmTylViMXhXADC+im0Sg0BxIBIcAAKpKSezTrFygBJKBkCQ5AGMXwUG05b43Z6kFwuIA)
```sh
--parser typescript
```

**Input:**
```ts
const getUnusedAuthorizationHoldDocuments = async (): Promise<DocumentData[]> => {}
```

**Output:**
```ts
const getUnusedAuthorizationHoldDocuments = async (): Promise<DocumentData[]> => {};
```

**Expected behavior:**
```ts
const getUnusedAuthorizationHoldDocuments = async (): Promise<
  DocumentData[]
> => {}
```

**Comment by merlinnot** [comment] 2019-11-09 12:46
More examples:

**Prettier 1.19.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzAlgJzgwkIAU581oBDAG1oE8BJAEwRlz2oCNa5TqMABZokmAIL581BgB4AOlEyYA1nAYRsmAMIR6cMB3QA6AKpoKaYwFFYuGA0UA+TAF5MAbQC6IADQgIAAcjKDRkUGopCAB3AUJQ5BBqADcIXBY-EG5pMDUYAGVA6jBcKABzZBh8AFc4fyEYAFtaAHUheyIisDh8hDR7XGT7BkSwNDD-Uot8GFJpMsbqZGw6C38AKzQADwAhHLz86ka4ABlSuGXVupBNrfzSsr4ARWqIeEvaNZAiygpEh0CRDA+FwwUygRBsBa6WEyAAHAAGfwQiAWFrSQKJCFECjJC7+ACOr3gcyCYRQ1DQAFooHA4GwMv5CESCPx5osPl8LI1cJUatd+uVnsSLkgVp9rjAeNCWLCkAAmfxVai4WgPXSNDkoKDQfEgaoWAAqPHJ4q+yVqTCgbFg+WBoJg4mt+QcfE5cAAvh6gA)
```sh
--parser typescript
```

**Input:**
```ts
const firestorePersonallyIdentifiablePaths: Array<
  keyof Collections.Users.Entity
> = []
```

**Output:**
```ts
const firestorePersonallyIdentifiablePaths: Array<keyof Collections.Users.Entity> = [];
```

**Expected behavior:**
```ts
const firestorePersonallyIdentifiablePaths: Array<
  keyof Collections.Users.Entity
> = []
```

**Comment by merlinnot** [comment] 2019-11-09 12:48
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wGUBVABUoHkAlAFQFEARAfQDUmAJASQGEAMkzYMAmpSakkeAILZsAQwCeAHgA6UPHn4QANnrhgYAS2hEAdBzgALE2ENFSMRfEtNYJmMoDaAcm8MOD8AXU0APjwAXjwaACMAKyMYCwA3RT0AVzgiAApdA2SzYitbe0dnVxyLBmUggEoAbhAAGhAIDFNzZFBFBQgAd0o+hCJkEEVUiBMAE1aQOKUwAGs4GFIMRTATKABzZBhsbLabGABbPQB1OzdNsDhSUa8TVK9lcbAiMbadojhcShKXZnRTIABmGT+bQSRDQACElqt1ooznBBDs4ODIXBobDSDtdoYAIqZCDwLF6KEgTbYP7YcaBHJgbAmTrzDAs2CXWYwGzIAAcAAY2hyIH9LkoMOMOTl-qlMW0AI6k+CAjpjFCKIgAWigcDgMwN82wcGVJhNgMUwNBSAhlJxID+ZxMByODqIBOJKsxtuxbRccW5M15yAATP6lCY9ATdGcQeMoNAFSBMn8GIo4hq7VTUtleFBDbBSMzWTBZAXnMpDBS-gBfWtAA)
```sh
--parser typescript
```

**Input:**
```ts
export const SUPPORTED_VEHICLE_TYPES: Array<
  Collections.VehiclesStates.Entity['type']
> = Object.values(Collections.VehiclesStates.Type);
```

**Output:**
```ts
export const SUPPORTED_VEHICLE_TYPES: Array<Collections.VehiclesStates.Entity["type"]> = Object.values(
  Collections.VehiclesStates.Type
);

```

**Expected behavior:**
```ts
export const SUPPORTED_VEHICLE_TYPES: Array<
  Collections.VehiclesStates.Entity['type']
> = Object.values(Collections.VehiclesStates.Type);
```

**Comment by thorn0** [comment] 2019-11-09 13:11
Duplicate of #6886

**Comment by merlinnot** [comment] 2019-11-09 13:22
@thorn0 Sorry for linking the first two to 1.19.0, 1.19.1 was not deployed yet. The behavior is the same, tested locally with 1.19.1. The last example links to 1.19.1.

**Comment by thorn0** [comment] 2019-11-09 13:25
Yep, these all are consequences of #6497. A better fix for #5684. And for that we need a solution for  #2482. Basically, it's complicated.

**Comment by Shinigami92** [comment] 2019-11-11 08:30
We have 23 files in our project that are affected by it :(

**Comment by brainkim** [comment] 2019-11-19 22:54
@Shinigami92 that’s more related to a change in the function composition stuff. See #6921

**Comment by thorn0** [comment] 2020-05-07 00:16
All the examples from this issue seem to be formatted as expected in 2.0. They should be added to the tests.

**Closed** 2020-05-11 08:49 UTC
Labels: lang:typescript, type:tests
