### ISSUE TITLE
not register prettier plugin installed by pnpm

### ISSUE THREAD

**Issue by tjx666** [prettier/prettier#13404] opened 2022-08-31 09:26 UTC
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/173645784-683a9a58-85e4-4ba4-bad7-219d5d751fad.png">

Repoduce steps:

1. `git clone git@github.com:tjx666/adobe-devtools.git`
2. `git reset --hard  77a25eadb2bfee5f3398437edd1b9d1248a82c03`
3. install dependencies by `pnpm install`
4. try format xml file `CSXS/manifest.xml`
5. try install dependencies by npm, no this issue

- MacOS: 12.4
- VSCode: 1.69.0-insider
- extension: v9.5.0
- Pnpm: 7.2.1

**Comment by tjx666** [comment] 2022-08-31 09:27
come from here https://github.com/prettier/prettier-vscode/issues?q=is%3Aissue+author%3Atjx666+is%3Aclosed

**Comment by fisker** [comment] 2022-08-31 09:59
Duplicate of #8056

**Closed by fisker** 2022-08-31 09:59 UTC
