### ISSUE TITLE
specify parser for HTML template literal

### ISSUE THREAD

**Issue by alexan** [prettier/prettier#6032] opened 2019-04-04 16:43 UTC
Is it possible to specify the used parser for html template Formatting?

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8OYLyYD0AVJgBIAqAsgDKbGEAGAPACYCWAbgHzDA4wAvoOaEOANW6MA3CAA0ICAAcY7dMlABDAE7aIAdwAKOhGmQhNnCO1byQAI22awAazgwAykufsoAc2QYbQBXOAUACxgAWwAbAHVw9hxvMDgPUySuJIBPczA0MwVfNDhtGEMnPyjNZAAzTRiShQArNAAPACEnV3cPTSi4Gl84OoamkFa2j18-GLgARWCIeFHGsJBvbRLtc3tNe2yY6DslbV8YOJsYcOQADgAGBVOIErinJXNTuG3OEYVtOAAR2C7ABFU0VRqSHqawUJSi7ECIXWaBmc0WyxG0LG6xg+0urGuyAATAogpp2DEZgBhCBRarmKDQP4gYIlCj7MzYtbCIA)
```sh
--parser babylon
```

**Input:**
```jsx
const test = /* HTML */`<div>{{test}}</diV>`;
```

**Output:**
```jsx
const test = /* HTML */ `
  <div>{{test}}</div>
`;

```

**Suggestion:**

**Input:**
```js
const foo = /* ANGULAR */`
  <div class="voluptatem architecto at">
    {{interpoation}}
  </div>
`;
```

**Output:**
```js
const foo = /* ANGULAR */`
  <div class="voluptatem architecto at">
    {{ interpoation }}
  </div>
`;
```

**Comment by lydell** [comment] 2019-04-04 17:12
Hi! Could you provide some more details? Why would you put Angular code in a template literal?

**Comment by icopp** [comment] 2019-04-04 18:54
The simplest way to create an AngularJS component is to embed the template:

```
angular.module('whatever').component('someComponent', {
    bindings: {
        value1: '<',
    },
    template: html`
        <p>This is value1: {{ $ctrl.value1 }}</p>
    `,
});
```

For obvious reasons, you want to have it formatted as an Angular template rather than plain HTML.

**Comment by lydell** [comment] 2019-04-04 19:04
We have some support for Angular components in TypeScript:

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAwhAtgB2gmACmAB0oACSq8gZzgBs4wYIAnJcgcgEMccBaeDRicANGUrxc9bvA4ADADwBXegD4qi+gEs1QmIoD0OtRPJHVpiuXnjrwgJ6MaHANpV5ZiUgAWEYeSk1uSQ9GwcrHAAJgDcEgC+5BJR2gBugeQARtxgANYA5qwQylBRHJn0ynAJZJ5QZAC6ZPEAlGRgMjQ01OQAKnDCmLj4sIHxZCCiIBA4MNrQNMig3KxFAO4ACisIiyjcqRDaUZMgmaw5uXAwAMo4OdpQ+cgwrFVTPjBY9ADqPtpCdzAcGuO3+aX+DmQ4C6JwedFYMA253yWG4yAAZtx6HQpgArGgADwAQuc8ldrtwsHAADIPOAYrE4kD4gnXB75RgARWUEHgDOxcCmd1Y8KhMAcOAGYFY2lmJxwMtg3yOMB8yAAHAAGIVFOjfc44KEKgZwVipelTSIAR2U2kiSO4KLRSExAqmdCw2mer0FIBo7K5PL5LsZvpg3EyyqiquQACYpi9uNodI8hqioVB8CdlHRehHdq66PF4kA)
```sh
--parser typescript
```

**Input:**
```tsx
@Component({
       selector: 'app-test',
  template: `<ul>   <li>test</li>
  </ul>
  `,
  styles: [   `
  
 :host {
   color: red;
 } 
 div { background: blue
 }
`

]
})
class     TestComponent {}

```

**Output:**
```tsx
@Component({
  selector: "app-test",
  template: `
    <ul>
      <li>test</li>
    </ul>
  `,
  styles: [
    `
      :host {
        color: red;
      }
      div {
        background: blue;
      }
    `
  ]
})
class TestComponent {}

```

But you’re talking about Angular<strong>JS</strong> – “the old one” – right? Unless I’m mistaken Prettier only support the newer Angular project.

**Comment by icopp** [comment] 2019-04-04 19:06
> But you’re talking about AngularJS – “the old one” – right? Unless I’m mistaken Prettier only support the newer Angular project.

Yes, but you can 'make do' for most purposes using the Angular formatter, and I think there will probably be a separate parser for AngularJS eventually, so the same use case applies to both.

**Comment by alexan** [comment] 2019-04-05 07:07
I did not talk about the old angularJS. There are several use cases where prettier can not rightly infere its angular code in the template string.
e.g. https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8C2AHAGwEN5MBeTAAwB4BXAgPk2eoIEsHhh4MBfX6gHp2DADpQWg+g0oBuceIACAYQj5oCGAApg45vuZo4BOGBgQATkkwByInjwBaHjBsAaPdjj5i8DxMwMAE8TNGsAbX1KTz0kAAsIDExdAMxIAktrCzgAE3kJXkw9HLYAN2TMACMiMABrAHMLCFooHOtKglo4PV5xaKhxAF1xXgBKcTBiNDQDTAAVOAxVdShNZM8XclsXGxioXqgQNxAIPBg2dGRQIgsmgHcABRuENGQQIlKINhyjkEqLGq1OAwADKeBqbCg9WQMAsXWOcRgOAIAHU4mweOCwHAQS8MWUMUE3mBpr9IUYLDAHgD6jgiMgAGZEAhGY4AKzQAA8AEIAurAkFEHBwAAykLgjOZrJAHM5IMh9RMAEVaBB4JKWXBjuCLBS3jAgnhFmALGwzr88KbYCjvjA4sgABwABm1TSMKIBeDelsWcAspQlx2yAEdaGxstSiLT6UgmZrjkYcGwYXCtSA0Arlar1bGpWmYERKjacnbkAAmY6wohsdhQ5Z0t5QDS-WhGOaF165zX8IA

https://github.com/storybooks/storybook/blob/e8cdeb6371e69ad8c83c743e9e99cf7ff31951dd/examples/angular-cli/src/stories/index.ts#L11

**Comment by lydell** [comment] 2019-04-05 16:53
Duplicate of #5786

**Closed by lydell** 2019-04-05 16:53 UTC
