### ISSUE TITLE
Prettier is not following Markdown Lint

### ISSUE THREAD

**Issue by qiansen1386** [prettier/prettier#4904] opened 2018-07-29 05:59 UTC
Good day Prettier team. 
I use prettier together with markdown lint in VS Code editor. The editor keep prompt me for violating `MD030/list-marker-space` and `MD009/no-trailing-spaces`()

I came across #4114 . What I have done right now is manually ignoring those rules. Though it is not a big issue, It does not seem ideal. I wonder is there a better way to configure it.

Thanks

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgNoA8C6mAMgJYDOMmJ8AtpqgDpQBMWehpFVtmzTAzGwLFylanDr8mAFiEdR3CZmlNMajJgC0APkwBlAK4AjTABtRqtay27DJ8xUuZBN-cbMWoAVjaZ5XcTovJgA2X38xHhCQABoQCAAHGBJoMmRQAEMAJyyIAHcABWyENJQMgDcIEgATWJAjLIywAGs4GD0EppIoAHNkGCyDODjusjgsmALGnpoM5AAzDNMxuIArMlwAIUaWtr0MmjhSKDgFpZWQTqyxrOQQWazm6vyoOoSs7pgAdRqYAAtkAAOAAMcXeEDGX0aCTu7zgN3KpziWTgAEcDCQUVMMjM5khFsthiAxjQSP1BkSyN0eqY4ABFAwQeBnQlxGAZIw-ar-ZDMNmNEjmXoAYQgNFmdyg0CRIAMYwAKhzSgSxgBfVVAA)
```sh
--parser markdown
```

**Input:**
```markdown
1. [x] List item 1
2. [x] List item 2
3. [x] List item 3
4. [x] List item 4
   1. -> Sub list
   2. -> Sub list
   3. -> Sub list
5. [ ] List item 5
6. [ ] List item 6
```

**Output:**
```markdown
1.  [x] List item 1
2.  [x] List item 2
3.  [x] List item 3
4.  [x] List item 4
    1.  -> Sub list
    2.  -> Sub list
    3.  -> Sub list
5.  [ ] List item 5
6.  [ ] List item 6

```

**Expected behavior:**
```
1. [x] List item 1
2. [x] List item 2
3. [x] List item 3
4. [x] List item 4
   1. -> Sub list
   2. -> Sub list
   3. -> Sub list
5. [ ] List item 5
6. [ ] List item 6
```

**Comment by ikatyang** [comment] 2018-07-29 06:36
As you mentioned above, it's tracked in #4114 and should be fixed by #4893. We'll soon release 1.14.

**Prettier pr-4893**
[Playground link](https://deploy-preview-4893--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBGAdAAgNoA8C6mAMgJYDOMmJ8AtpqgDpQBMWehpFVtmzTAzGwLFylanDr8mAFiEdR3CZmlNMajJgC0APkwBlAK4AjTABtRqtay27DJ8xUuZBN-cbMWoAVjaZ5XcTovJgA2X38xHhCQABoQCAAHGBJoMmRQAEMAJyyIAHcABWyENJQMgDcIEgATWJAjLIywAGs4GD0EppIoAHNkGCyDODjusjgsmALGnpoM5AAzDNMxuIArMlwAIUaWtr0MmjhSKDgFpZWQTqyxrOQQWazm6vyoOoSs7pgAdRqYAAtkAAOAAMcXeEDGX0aCTu7zgN3KpziWTgAEcDCQUVMMjM5khFsthiAxjQSP1BkSyN0eqY4ABFAwQeBnQlxGAZIw-ar-ZDMNmNEjmXoAYQgNFmdyg0CRIAMYwAKhzSgSxgBfVVAA)
```sh
--parser markdown
```

**Input:**
```markdown
1. [x] List item 1
2. [x] List item 2
3. [x] List item 3
4. [x] List item 4
   1. -> Sub list
   2. -> Sub list
   3. -> Sub list
5. [ ] List item 5
6. [ ] List item 6
```

**Output:**
```markdown
1. [x] List item 1
2. [x] List item 2
3. [x] List item 3
4. [x] List item 4
   1. -> Sub list
   2. -> Sub list
   3. -> Sub list
5. [ ] List item 5
6. [ ] List item 6

```

**Comment by ikatyang** [comment] 2018-07-29 06:36
Duplicate of #4114

**Closed by ikatyang** 2018-07-29 06:36 UTC

**Comment by qiansen1386** [comment] 2018-07-29 06:52
@ikatyang  Will it fix `MD009/no-trailing-spaces` also?

**Comment by ikatyang** [comment] 2018-07-29 07:02
Can you share an example? We should already remove unnecessary trailing spaces from the beginning.

**Comment by qiansen1386** [comment] 2018-07-29 17:01
@ikatyang Confirmed, I didn't manage to reproduce the `MD009/no-trailing-spaces` alert after formatting! 
:tada: Thanks a lot!
