### ISSUE TITLE
Request: Override rules in file

### ISSUE THREAD

**Issue by blainekasten** [prettier/prettier#1154] opened 2017-04-07 18:06 UTC
There is a strong argument against this. And honestly I don't really want this. But there is a bit of an interop issue with certain rules in different environments.

### Issue

Rule: `trailingComma: 'all'`

This rule works great when your code is fed through Babel, but fails when executed directly. example:

```js
const add = (...args) => args.reduce((a, b) => a + b, 0);
add(
  1,
  2,
  3,
)
```

### Environments

This specifically happens to me because I write es6 code for the client, which is transpiled through Babel.

And then I write es6-ish code for node, which is not transpiled.

So therefore, when my editor automatically prettifies the node code, it breaks.

### Solutions?

Easiest solution seems to be to have an eslint style comment in a file over-riding rules. Example:

```js
// prettier-rule trailingComma=es5
```

I'm curious your thoughts on this, or if you have a better idea of how I can use prettier in different environments like this.

**Comment by vjeux** [comment] 2017-04-07 18:11
We're having the same problem at fb.

**Comment by mbrookes** [comment] 2017-04-07 23:55
Dupe of #98? But glad this is getting some fresh exposure.

**Comment by mbrookes** [comment] 2017-04-07 23:57
Further discussion: https://github.com/prettier/prettier/issues/62

**Comment by lydell** [comment] 2017-04-08 10:29
I recently bumped into this too. I solved it by running prettier through ESLint using [eslint-plugin-prettier](https://github.com/not-an-aardvark/eslint-plugin-prettier).

.eslintrc.js:

```js
module.exports = {
  // ...
  rules: {
    // ...
    "prettier/prettier": ["error", { trailingComma: "es5" }],
  },
};
```

frontend/.eslintrc.js:

```js
const parentConfig = require("../.eslintrc");
const parentPrettierOptions = parentConfig.rules["prettier/prettier"][1];

module.exports = {
  // ...
  rules: {
    // ...
    "prettier/prettier": [
      "error",
      Object.assign({}, parentPrettierOptions, { trailingComma: "all" })
    ],
  },
};
```

So in case you need something _now_ the above is a potential solution :)

**Comment by vjeux** [comment] 2017-05-21 21:54
node 8 is going to be released in 1.5 week and supports trailing commas for function calls. I think that we should get people to upgrade when it's ready rather than add complexity inside of prettier.

**Closed by vjeux** 2017-05-21 21:54 UTC
Labels: Needs discussion

**Comment by mbrookes** [comment] 2017-05-21 23:52
@vjeux Not sure why this was closed. @blainekasten posted a specific example of why overrides are needed. Just because that particular issue is fixed doesn't remove the need for overrides in some form (beyond the paltry set of command line options that currently exist).

**Comment by vjeux** [comment] 2017-05-22 00:02
If you have another use case for overrides, please create a different issue, and we can try to figure out a solution. I'm interested in solving the problems people have, not implementing whatever solution they think would solve their problem :)

**Comment by mbrookes** [comment] 2017-05-22 10:44
NVM, looks like, there are multiple ops open (and closed) proposing something similar, making a strong case, and giving other use cases, so this one can stay closed.
