### ISSUE TITLE
Mixed line ending output

### ISSUE THREAD

**Issue by dasa** [prettier/prettier#6934] opened 2019-11-11 22:03 UTC
**Prettier 1.19.1 on Win 10**

**CRLF Input:**
```js
return featuresetUtils
  .constructFeatureSetFromUrl(serviceUrl, layer.spatialReference, fields, includeGeometry)
  .then(function() {
    return getFeatureByObjectId().then(function() {
      /*
      const filter2 = WhereClause.create(
      return rellayer.filter(filter2);
      */
    });
  });
```

**Mixed Output:**
```js
return featuresetUtils
  .constructFeatureSetFromUrl(
    serviceUrl,
    layer.spatialReference,
    fields,
    includeGeometry
  )
  .then(function() {
    return getFeatureByObjectId().then(function() {
      /*
      const filter2 = WhereClause.create(
      return rellayer.filter(filter2);
      */
    });
  });
```

These three lines end with LF

```
      /*
      const filter2 = WhereClause.create(
      return rellayer.filter(filter2);
```

**Expected behavior:**

The line endings all start as CRLF and should all be CRLF after formatting. It does work as expected if I pass `--print-width 200`.

**Comment by thorn0** [comment] 2019-11-12 07:15
Duplicate of #6501

**Closed by thorn0** 2019-11-12 07:15 UTC
