### ISSUE TITLE
Template string interpolation

### ISSUE THREAD

**Issue by xereda** [prettier/prettier#5949] opened 2019-03-07 17:56 UTC
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzAlgG3gCdMBeTAcj0LhIyNygHMA6NigbgB0ofIoMmAI4BXWgE8ymJkPwADYDy4wADrTTQAFNWJJMXEABJgO2gF8DASkyLeMZbgAmS+zCgBDALZwXFqGbkOEAAaEAgVGFx0ZFB3IiIIAHcABTiENGQQdwA3CCcQkAAjIncwAGs4GABlFVLGJmQYIjFQgAsYT3wAdVbceDRasDgq9L7cbL7xTLA0DNDGNFoYZJKmT3dkbHd8RdCAKzQADwAhEvLKqq84ABlGOE3t3ZADw6r6-DgARREIeAeduChWpERZETKFdyFcT4aAFFQMWBdJwwVrIAAcAAYgQlFl0SipMvC4KDsvdQkQ4KJcBSVu41hskFsAaFFp5cI1moCQGh3l8fn9GY8uTBIUjHCjkAAmUJNdwEeoAYQgnnWmSg0DJIBEiwAKpCMoKAWYzEA)
```sh
--parser babylon
```

**Input:**
```jsx
const filter = 'filter string...';

const query = gql`{
	person(filter: "${filter}") {
		id
		name
	}
}`;
```

**Output:**
```jsx
SyntaxError: Syntax Error: Unterminated string. (2:18)
  1 | {
> 2 | 	person(filter: "
    | 	                ^
```

**Expected behavior:**

Prettier also working with interpolated template string.

See: https://github.com/prettier/prettier-vscode/issues/742

**Comment by lydell** [comment] 2019-03-07 18:48
Hi! Yes, non-toplevel interpolations in GraphQL is not currently supported. Duplicate of #4404.

**Comment by lydell** [comment] 2019-03-07 18:49
Duplicate of #4404

**Closed by lydell** 2019-03-07 18:48 UTC
