### ISSUE TITLE
JavaScript: Needs two runs on a case where two long calls are chained

### ISSUE THREAD

**Issue by ziyadss** [prettier/prettier#11512] opened 2021-09-12 03:07 UTC
**Prettier 2.4.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBXADgEwEN4AVCbAJ0wF5MAKCuARwBpNG0BKGgPk2AA6UIZkwB3CgEt4AMUkAbOHQDkAOgD0+OADcAtERiFNxIzHIU0utJIC2uRaoBWaaMrYApAMoB5AHKqMKSgAc0kAMwBPOjNKLk4RUUxVGAALBDo6bmo+DgDDGGw0OgAmAAZSzicXKDpgTAxiQqRMZTRsMDA4NDQ3TANCZrqYimbhtABtRiZVeQgwQnk0ZPMASSgtAA8AXUwAX13OeKhEzCFdgG4QFhAIXBhJdGRQQgoKCDEABReENGQQBbEhAiv2uACMKIQwABrOAwTyEGxwAAykigcGQYQWaDgYIh0NhnlwkNRwWQMAo2BxIDgNlBcHwWnwSMIIWwhGCcBkEAoNmI9xCf0I2DMVxAKRgNnkAHUUtIukTOp4ftJJNppBE-mBuqLUdiKDAPhDgryMViqc4Np4SYoAIrYCDwU2LKlEixwCh-UGEOnyUW4IIwKWSfCpZAADlK139EGxUohuD+-q67u06OuTHt8ENt1+KEIljR9Ppoqm2EkjEN7JNSExzuu2JskjJFKp1hCtsz6JrZuuhlBQZDKWQxV7EIUJIAwhAbNXqWgAKyiwpwEje3O17HXbSUtZaWCeMBSO4AQXWnhgEUUTux+yAA)

```sh
--parser babel
```

**Input:**

```jsx
const updateTour = (req, res) => {

  writeFile('./dev-data/data/tours-simple.json', JSON.stringify(tours))
    .then(() => res.status(200).json({ status: 'success', data: { tour: tours[req.locals.tourIndex] }}))
    
};
```

**First Output:**

```jsx
const updateTour = (req, res) => {
  writeFile("./dev-data/data/tours-simple.json", JSON.stringify(tours)).then(
    () =>
      res
        .status(200)
        .json({
          status: "success",
          data: { tour: tours[req.locals.tourIndex] },
        })
  );
};

```

**Second Output:**

```jsx
const updateTour = (req, res) => {
  writeFile("./dev-data/data/tours-simple.json", JSON.stringify(tours)).then(
    () =>
      res.status(200).json({
        status: "success",
        data: { tour: tours[req.locals.tourIndex] },
      })
  );
};
```

**Expected behavior:**
Further runs should keep the same output

**Comment by thorn0** [comment] 2021-09-13 13:42
Duplicate of #2803

**Closed** 2021-09-13 13:42 UTC
Labels: type:bug, type:duplicate, lang:javascript, area:idempotency, area:object literals, area:arrow functions
