### ISSUE TITLE
Missing "browser" conditional export in "exports"

### ISSUE THREAD

**Issue by victoragnez** [prettier/prettier#15591] opened 2023-11-03 19:18 UTC
Importing from `"prettier"` fails when modern bundlers build for browser and use the `"exports"` pattern, because there's no `"browser"` condition - so it resolved to `"default"` instead.

Reproducible with esbuild version 0.19.5 and prettier version 3.0.3:

Run: `echo 'import "prettier";' | npx esbuild --bundle --platform=browser`

Output:
```
✘ [ERROR] Could not resolve "module"

    node_modules/prettier/index.mjs:1:57:
      1 │ import { createRequire as __prettierCreateRequire } from "module";
        ╵                                                          ~~~~

  The package "module" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "os"

    node_modules/prettier/index.mjs:13725:15:
      13725 │ import os from "os";
            ╵                ~~~~

  The package "os" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "--platform=node" to do that, which will remove this error.

...
```

**Comment by fisker** [comment] 2023-11-04 05:09
Duplicate of  #14766

**Closed** 2023-11-04 05:09 UTC
Labels: type:duplicate
