### ISSUE TITLE
options are limited, could the API options support more rules?

### ISSUE THREAD

**Issue by vicwang163** [prettier/prettier#3650] opened 2018-01-05 08:18 UTC
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any): http://eslint.org/docs/rules/space-before-function-paren
--spaceBeforeFunctionParen
```

**Input:**
```jsx
// code snippet
class Demo {
  test() {
    console.log(1)
  }
}
```

**Output:**
```jsx
// code snippet

class Demo {
  test() {
    console.log(1)
  }
}
```

**Expected behavior:**
```jsx
// code snippet

class Demo {
  test () {
    console.log(1)
  }
}
```

**Comment by vicwang163** [comment] 2018-01-05 08:20
according to this doc : https://prettier.io/docs/en/options.html,
I see limited option to set, I know this tool is awesome，but in my business, I want to use more rules to beautify my code.tks

**Comment by ikatyang** [comment] 2018-01-05 08:34
Duplicate of #1139, see https://github.com/prettier/prettier/issues/3503#issuecomment-352802184 and #40.

I think you probably want to use [`prettier-eslint`](https://github.com/prettier/prettier-eslint) to format your code with additional rules.

**Closed by ikatyang** 2018-01-05 08:34 UTC
