### ISSUE TITLE
Changing the single quotes to double if string has escaped symbol

### ISSUE THREAD

**Issue by acteralex** [prettier/prettier#7175] opened 2019-12-24 09:18 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAcgAk4AbMiTAYWxgB17C1MB1CAJzIBNCBCEABoQEAA4wAlumShsHDhADuABTkI0yENgBuECdyEgARh2xgA1nBgBlUWYlQA5shgcArnGEALGAFsyrF4S8Gh2YHDW6sES2sEAnppgaBrCDmhwHDDKpo6+2MgAZthk6cIAVmgAHgBCphZW1ti+cAAyDnCFxaUgFZXWDo5kcACKbhDwnSWeIHYc6RyaMHGicGhgHBLihqIbsKz6MF7IABwADMI7EOmspqKaO6sZ2h3CAI5j8NliGijYaAC0UDgcG4IMMHDg7wkEOy2Fy+SQRSmwnSvgkLnc0zQAyGo3GHSQrg8whg2CM+24h2QACYSaYJGQBtQIL48pooNAXiA3OkACpkn5I7raDwASSgoNg1nWmxgAEEJdYlkNJukAL5qoA)
```sh
--parser typescript
--single-quote
```

**Input:**
```tsx
const a = 'Hello Cat\'s World'!
```

**Output:**
```tsx
const a = "Hello Cat's World"!;

```

**Expected behavior:**
```tsx
const a = 'Hello Cat\'s World'!
```

**Comment by lydell** [comment] 2019-12-25 08:56
Duplicate of #973

**Closed by lydell** 2019-12-25 08:56 UTC
