### ISSUE TITLE
Flow comments

### ISSUE THREAD

**Issue by svipben** [prettier/prettier#1611] opened 2017-05-15 12:12 UTC
Hello,

as you know you can use flow type annotations in comments (https://flow.org/en/docs/types/comments/) like this:

```javascript
const text /*: string */ = 'yay';
const obj /*: Object */ = {};
```

But we have problem when it comes to this:
```javascript
(obj /*: any */).name = 'prettier';
```

This will be formatted to:
```javascript
obj /*: any */.name = 'prettier';
```

With ESlint integration to:
```javascript
obj.name = 'prettier';
```

**Correct behavior will be not to format such case, just let it be as it is.**

P.S. Tested without ESLint and it was formatted badly too.

**Comment by k15a** [comment] 2017-05-15 12:14
Duplicate of #719?

**Comment by svipben** [comment] 2017-05-15 12:14
@k15a Yes, sorry!

**Comment by vjeux** [comment] 2017-05-15 14:31
Yeah, this is something that needs to be fixed but I don't have the time to work on it anytime soon. It's not the easiest getting started task but if you want to help, that's something concrete to work on.

**Comment by k15a** [comment] 2017-05-18 21:40
I am closing this issue in favor of #719

**Closed by k15a** 2017-05-18 21:40 UTC
Labels: bug
