### ISSUE TITLE
CSS adds spaces/line breaks in @import url

### ISSUE THREAD

**Issue by kinkoazc** [prettier/prettier#5014] opened 2018-08-24 09:27 UTC
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgWwA4QE4wAEArngDYAUAFjDNgM5ID0TAZtDPQHQDmEEPMnACG2dN0iYmYevQD8rYZnRkAngF4AyhFJg4Aak3Co9fQAU8EJABYADLYA0AZnsOAbK4DsrgJz2AlADcIA4gENgw6ND0yKDCeJYA7mbxCDEowgBuEOgAJiEgAEZ4wmAA1nAwmtil6FA8yDB4xHChdfRwBBbCPJjCyIpkHaEAVvQAHgBCJeWVRphwADJ1cAPCQ60gNXgdeMjgsgXYeHUwAOp5MFTIAByOW5YdZyXY+8dwu5mroXhwAI7EdC-bq9fpIQbDEAdZSNZqbeh1QRwACKxAg8DWG1CMGEhQuuSuyAATNiSipEQBhCCYPr7KDQb4gYgdAAquPSELgAF8uUA)
```sh
--parser css
```

**Input:**
```css
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600,700,900);
```

**Output:**
```css
@import url(
  https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,
  300,
  600,
  700,
  900
);
```
or
```css
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:400, 300, 600, 700, 900);
```

**Expected behavior:**
```css
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600,700,900);
```

**Comment by kraklin** [comment] 2018-09-06 11:44
It looks like the bug was first introduced in version `1.13.0`. Version `1.12.1` looks like it is working well - no spaces after `,` but version `1.13.0` starts adding spaces.

**Comment by evilebottnawi** [comment] 2018-11-14 15:04
Problem in `postcss-values-parser`, package doesn't respect `url` spec and parse this as function with arguments

**Comment by crcarlo** [comment] 2019-02-26 19:25
I'm facing the same problem and the only way I could work around this issue is to wrap URLs in quotes.
```css
@import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600,700,900");
```
but still, as stated [here](https://www.w3.org/TR/CSS2/syndata.html#value-def-uri) this is regular CSS syntax and should therefore be supported

**Comment by sebastianhaberey** [comment] 2019-04-22 09:25
+1 stumbled across this today. Thanks @crcarlo for your workaround.

**Comment by sgehrman** [comment] 2019-05-26 20:48
Hit this today too. will add quotes.

**Comment by rhernandog** [comment] 2019-06-12 14:18
Indeed keeps happening up to know

**Comment by jacksteamdev** [comment] 2020-01-16 15:21
I wonder how many people have font problems because of this and don't know it.

**Comment by robert-j-webb** [comment] 2020-05-24 18:04
I'm going to see if I can fix this today. I'm thinking maybe just add a special case to avoid parsing the arguments to the url function?

It may be better even to enforce always having URL quotes, as a style decision. I understand that it's regular CSS syntax but in my opinion, it's weird syntax.

**Comment by robert-j-webb** [comment] 2020-05-24 18:13
No longer seeing this happening on master. We can close this out.

**Comment by robert-j-webb** [comment] 2020-05-24 18:18
Ach nevermind this is still happening, I was checking incorrectly.

**Comment by robert-j-webb** [comment] 2020-05-24 18:44
Digging into this further, the issue is postcss-values-parser is parsing the URL into separate functional groups, when really it should just leave the URL value alone.

**Comment by robert-j-webb** [comment] 2020-05-24 19:50
I created an issue for this in post-css-values parser. https://github.com/shellscape/postcss-values-parser/issues/117

However it may be better to fix it here. I found this issue only in loose mode, which is somewhat WAI

**Comment by robert-j-webb** [comment] 2020-05-24 21:22
I can't distinguish between: `url(fbglyph:cross-outline , fig-white);` and `url(url.com/Prettier+Sans&size=500,400,300,1000,600);` 

But this is quite an improvement, considering the URL mangling bug does cause prettier to break sass, sending out a PR now.

**Closed** 2020-05-29 13:09 UTC
Labels: lang:css/scss/less, type:bug
