### ISSUE TITLE
JSX - Ternary condition which renders a single JSXElement enforces useless braces

### ISSUE THREAD

**Issue by Aetherall** [prettier/prettier#3904] opened 2018-02-06 14:22 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEY4BtcDCEAtgA7QJYC8mpAThKWplQHy0NMB0kuArsShcoAQ2JwWVGgHIRYGAEt00zAB0omTAH5MAHgAqIgEa44XAnlyZgXW-UZoAvpgBuI-nCrBdAQXlKoZhs7TidMAHpWZ0j1TSQ9QxMzC3xrWy57JmjWEAAaEEZFdGRQEToGAHcABTKENGQQERcIBQATPMaMZAAzdzQ4fKM6OQBrOBgAZVI5BSgAc2QYOj4BkFaIMB6+1dn+uhgq4bniES3cfvyAKzQADwAhYbAxybE4ABlZuDOLgr4YUj+ACZvqtpnQ9g0jMYAJ64aAdeizGAAdTaMAAFsgAIwABhx+Xs-WRw1IDXocD2Li++TocAAjnwFLTDiJjqckL1zqt+sQFItltzZnNTABFPgQeAg-IwYyo1oY5CA6XDBS4IVEYgnBruXAdPj9RL1DnbRyOIA)
```sh
--print-width 100
--trailing-comma all
```

**Input:**
```jsx
const cellComponent = props => props.column.name === 'actions' 
  ? <Table.Cell {...props} value={<Actions {...props} />} />
  : <Table.Cell {...props} />
```

**Output:**
```jsx
const cellComponent = props =>
  props.column.name === "actions" ? (
    <Table.Cell {...props} value={<Actions {...props} />} />
  ) : (
    <Table.Cell {...props} />
  );

```

**Expected behavior:**
```jsx
const cellComponent = props => props.column.name === 'actions' 
  ? <Table.Cell {...props} value={<Actions {...props} />} />
  : <Table.Cell {...props} />
```

**Comment by lydell** [comment] 2018-02-06 16:14
Thanks for the issue! Prettier actually prints JSX ternaries differently on purpose, so this is the expected behavior.

This issue is a duplicate of #3001, which in turn links to #2208 and #2398.

**Closed by lydell** 2018-02-06 16:14 UTC
Labels: lang:javascript, type:feature

**Comment by j-f1** [comment] 2018-02-06 16:18
Duplicate of #3001

**Comment by lydell** [comment] 2018-02-06 16:56
@j-f1 How do you do that duplicate marking thing?

**Comment by j-f1** [comment] 2018-02-06 17:34
@lydell 

1. Post `Duplicate of #3001` as a comment (you can change `3001` to the appropriate issue number, but you can’t put a `.` at the end of the line)
2. Immediately delete your comment.

**Comment by Aetherall** [comment] 2018-02-06 21:20
Is there any way to desactivate this behaviour ?
I'm struggling in making prettier fix styling issue before eslint in vscode ...

**Comment by lydell** [comment] 2018-02-07 06:13
@Aetherall You can use `// prettier-ignore` comments, but we generally suggest turning off all ESLint rules that conflict with Prettier. See [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).

**Comment by Aetherall** [comment] 2018-02-07 09:43
@lydell I use eslint-config-prettier already...
Could not be possible to add an option in the .prettierrc so this specific behavior is ignored ?

My codebase massively relies on conditionnal rendering and my code is so ugly now... everything else is perfectly formatted :/

**Comment by lydell** [comment] 2018-02-07 10:11
Sorry, I don’t understand your problem, then :(

**Comment by Aetherall** [comment] 2018-02-07 10:37
This behavior happens on the playground. This means that it is not ESLint related.
I don't see why disabling all ESLint rules conflicting with Prettier ( so prettier operates freely I suppose ) should avoid prettier acting how it is supposed to...

I will be more likely to think that I can run eslint --fix after prettier so eslint can  correct prettier's unwanted behaviors

#### My problem is :

I got this code:
```jsx
const Loader = props => props.loading
  ? <LoaderIcon />
  : <Component {...props} />
```

And I want to keep it the same while using prettier
( and preferably don't havo to put `// prettier-ignore` comments each time i got a JSX ternary )

Is it possible to achieve ? 

Thanks for your time :)

**Comment by j-f1** [comment] 2018-02-07 10:40
There’s [`prettier-eslint`](https://github.com/prettier/prettier-eslint-cli), a tool that runs your code through an ESLint config of your choice after running Prettier, enabling you to choose and enforce your own style guide while still taking advantage of Prettier’s features.

**Comment by suchipi** [comment] 2018-02-07 20:20
I don't think there's an eslint rule that will undo the formatting in the way you want.

**Comment by Aetherall** [comment] 2018-02-11 12:32
Sorry to bring this up,
Seems that the only way to have nice JSX ternaries would be to add a new option in the formatter
"jsx-ternary": 'default' || 'no-parens'

Is this a feature we can hope to get ?
Thanks !

**Comment by j-f1** [comment] 2018-02-11 12:50
@Aetherall https://prettier.io/docs/option-philosophy.html

**Comment by Aetherall** [comment] 2018-02-11 13:29
I see
