### ISSUE TITLE
Prefer indenting/new line from "."

### ISSUE THREAD

**Issue by bitttttten** [prettier/prettier#9548] opened 2020-10-30 15:18 UTC
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHOYYAoDmcMAQgJ4AqcAzjAJIAmuAOiALakD68NHAlvSwCUgplAAEYgHQwIACQCGANziU0MAMLR4sXAHoARvKhH5VMQCdeWKHHpiAzGP0BXKGAAW1XYJAAaEBAYMLzQVMig8ubmEADuAAqRCGEo8gA2MfKkYf765vJgANZEAMoY+bxQ+Mgw5s5w-nCs+rb0tgAyRvjO8oQAYhDmrPIwwZXIIPLOMn4g7jCsqQDq7rzcZWBwxUmrvIqrpONgVNkgFVRw5jBxefhDyABmaef+AFZUaMR5hSXyrHBtFTgDye9RAbzQxQq+FScAAis4IPBgalniAyuZzuZxoZmqkZhhLLBFvwYO5kAAOAAM-gJEHOizyGHGBOoF2UMwAjgj4NdAskJlQALQ2Wy2GbmOBc3gS649O5IR4o0HnVi8aq1ZVQmHwxFAhUg-wweT6Yn0UnIABMhryvFSUM0rHlqCoAFYZs5zuRjclFajFHVaFBWrBimBLEEAIJB4owUgw5HnAC+iaAA)
```sh
--parser babel
```

**Input:**
```jsx
expect(getByTestId("my_test_id"))
  .toHaveTextContent(/bananas ripened 3 bunches/)
```

**Output:**
```jsx
expect(getByTestId("my_test_id")).toHaveTextContent(
  /bananas ripened 3 bunches/
);

```

**Proposal:**

It would be nice to prefer the new line to be entered in before the `.` and not after the open parenthesis. This makes it easier to scan files, and more consistent, since if I chain another function then this will be indented by the `.`.

**Comment by evilebottnawi** [comment] 2020-10-30 15:35
Please use search, it was answered a lot of time...

**Comment by thorn0** [comment] 2020-10-30 16:14
Duplicate of #9474 (and probably of other similar issues)

**Closed by thorn0** 2020-10-30 16:14 UTC
