### ISSUE TITLE
Extra/Unstable newline at end of file

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#880] opened 2017-03-04 07:18 UTC
```js
"";
;
```

[turns into](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5C%22%5C%22%3B%5Cn%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D) (two newlines at the end):

```js
"";


```

[turns into](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%5C%22%5C%22%3B%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D) (one newline at the end):

```js
"";

```

**Comment by duailibe** [comment] 2017-04-06 11:56
I can't reproduce this in master anymore, but this behavior still seems strange to me:

```javascript
f;
;

f;
```
```javascript
f;
f;

```

**Comment by vjeux** [comment] 2017-04-06 20:53
Indeed, it looks like it's now fixed in master. I'm going to close this task.

@duailibe while it's unfortunate that we don't respect the empty line, I'm not very concerned about this. I don't really care about having a great output with empty lines with `;` :p But, I do want to make sure that we are stable, meaning that if you run prettier twice, it doesn't print two different things.

**Closed by vjeux** 2017-04-06 20:53 UTC
Labels: bug, easy, help wanted
