### ISSUE TITLE
Allow opt-in breakline for constructor arguments

### ISSUE THREAD

**Issue by pushkine** [prettier/prettier#9336] opened 2020-10-06 06:58 UTC
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgCoAWAllAOY7AA6UOOlMADgE4TxjwAmOAZhBAExIcmGExKkA3NXoMArgCNURMDnnomgnOigBPKVBliAbung5UcODE0ixZfbXqQot2ewhMAFM1Zx2cLl4IIVtxABocOUVlVXUhbR0I5iITMwsrENFxAEoKAF9qPJAwkAgGGCJoTGRQdRYAdwAFdQRqlHRUevQdapL5JnQwAGsrAGUGQfFkUVk4ErgAW3kAjgCAGW1SWXRSOAAxDwXTCrJkEHRZGAhikAIYBdQAdWJ4TAmwOFHWogqjH50zmBsDcSJg4EwYI0BqQjshuB0wSUAFaYAAeACEBsMxugFnA1iQ4HCEXMQCjUaNxBYAIqyXzE1CIkATJhgphnNTLVAAWhgvWZdhgjyIHBgBGQAA4AAwlHxgx4DBhnZhwNlGIklACOdPgULKbXOmG5UEsqw4NyYcG1REtUJ2sKQ8MZpLBCyI0yYsxKmCpcFp9MdJJKMHQ8mFovFSH4wYGRCUZAAwhAFg6QKqAKw3WRgvChtpOplGWYASSgq1gozAYnKAEEy6MYDoLAywXk8kA)
```sh
--parser babel-ts
```

**Output:**
```tsx
class Thing {
  	protected foo2: string;
  	public bar2: any;
  	private leet2: string;
  	constructor(protected foo: string, public bar: any, private leet: string) {}
}
```

**Expected behavior:**
```tsx
class Thing {
  	protected foo2: string;
	public bar2: any;
	private leet2: string;
  	constructor(
		protected foo: string, 
		public bar: any, 
		private leet: string,
  	) {}
}
```
In typescript constructor arguments with a flag are assigned as properties in the compiled output, that's neat as it greatly reduces the amount of boilerplate in classes

The issue is that the usual way to declare class property types requires breaklines between each property, but prettier requires constructor arguments to join lines, making the use of that typescript feature somewhat confusing

I don't really know how the opt-in breaklining with objects works, and I suppose there is a reason it's not supported in arrays/functions, but I was hoping to suggest for it to be at least supported in constructors

**Comment by evilebottnawi** [comment] 2020-10-06 09:59
Duplicate of #5666

**Closed by evilebottnawi** 2020-10-06 09:59 UTC
