### ISSUE TITLE
better format template literals

### ISSUE THREAD

**Issue by MrCheater** [prettier/prettier#6192] opened 2019-06-07 09:42 UTC
**Prettier 1.18.0**

```
// Input
console.log(chalk.white(`Covered Lines below threshold: ${coverageSettings.lines}%. Actual: ${coverageSummary.total.lines.pct}%`))

// Output (option enabled)
console.log(
  chalk.white(
    `Covered Lines below threshold: ${coverageSettings.lines}%. Actual: ${
      coverageSummary.total.lines.pct
    }%`
  )
);

// Output (option disabled)
console.log(
  chalk.white(
    `Covered Lines below threshold: ${coverageSettings.lines}%. Actual: ${coverageSummary.total.lines.pct}%`
  )
);

```

**Comment by evilebottnawi** [comment] 2019-06-07 10:03
No options, it is new behavior for prettier, also please use issue tempalte otherwise your issue was closed thanks

**Comment by MrCheater** [comment] 2019-06-07 10:20
Please stop breaking my project code. Please add an option

**Comment by evilebottnawi** [comment] 2019-06-07 10:40
How it is break your projects? We don't generate invalid code. This behavior is better.

**Comment by MrCheater** [comment] 2019-06-07 10:47
Prettier breaking change conflicts with the "printWidth" option

**Comment by MrCheater** [comment] 2019-06-14 08:16
@vjeux @duailibe @ikatyang @azz

**Comment by merlinnot** [comment] 2019-06-14 08:48
That would be great to have it back. I can understand that for some projects the new behaviour might be better, but the old one yielded much better results for the ones that I'm working on. I do understand that Prettier aims to reduce the number of options as much as possible, but some of the changes made recently unfortunately make some people like Prettier a little less. It's a great tool, but we should try to be more inclusive. The changes introduced recently that I personally find imperfect are:

- This one, where template string literals are not being formatted to fit in 80 characters.
- Putting parameters of `test` in one line.

**Comment by evilebottnawi** [comment] 2019-06-14 10:09
Yes, i was wrong in some cases we provide very ugly output, i think we should fix it

Please provides example where we do this to fix it better

**Comment by SMotaal** [comment] 2019-06-14 11:17
> How it is break your projects? We don't generate invalid code. This behavior is better.

@evilebottnawi maybe valid but per #6222 semantically inaccurate, which I raise here wondering if potentially relating to the breaking changes discussed here.

**Comment by thorn0** [comment] 2019-06-15 17:32
#3368 is still open, so this issue is a kind of duplicate of it.

**Comment by j-f1** [comment] 2019-06-25 15:48
It seems like there isn’t really a good solution for breaking template expressions since they’re whitespace-sensitive. IMO in these cases, it’s better to have soft-wrapping in the IDE handle things, since the IDE can break the line wherever it wants to without altering the actual content of the file, a luxury Prettier doesn’t have.

**Comment by shamilovtim** [comment] 2019-07-20 18:28
@MrCheater the wrapping in your IDE should take care of this. there's no need to break for the braces. in fact if your brace isn't at exactly the printwidth limit then your code would still go past where you wanted it to stop anyways.

**Comment by fernandopasik** [comment] 2019-08-18 20:06
I have a case that breaks my code adding extra line breaks. The lines are not long enough to need the extra linebreaking.

input
```
class AppAbout extends LitElement {
  render() {
    return html`<h1>About</h1>`; 
  }
}
customElements.define('app-about', AppAbout);
```

output
```
class AppAbout extends LitElement {
  render() {
    return html`
      <h1>About</h1>
    `;
  }
}
customElements.define('app-about', AppAbout);
```

**Comment by Domvel** [comment] 2019-08-28 12:29
#6262 Faced again.

This actual behavior (one-liner):
```ts
const url = `${this.keycloakInstance.authServerUrl}/realms/${this.keycloakInstance.realm}/protocol/openid-connect/token`;
```

vs expected / wanted (prettier, ...not this lib... just looks "prettier"):
```ts
const url = `${
  this.keycloakInstance.authServerUrl
}/realms/${
  this.keycloakInstance.realm
}/protocol/openid-connect/token`;
```

My current "workaround": 
`// prettier-ignore`

And this example is not yet the best I have. There are many case where the line breaks on the variables are required for a clean code. Check the issue #6262 

Please 🙏 change this behavior. Or, if you still can not decide which one you want, add an option.

**Comment by Domvel** [comment] 2019-11-06 16:33
**bump** Faced again. Issue reanimation started... 

Current format:
```ts
//                                                                            |
console.log(
  `Foobar bar foooooo bar barrrr! Foo bar bar foo foo, bar foo ${Foobar.foo.bar.getFoobar()} foo bar foobarfoo foo bar foo foo bar.`
);
//                                                                            |
```

vs wanted format:
```ts
//                                                                            |
console.log(
  `Foobar bar foooooo bar barrrr! Foo bar bar foo foo, bar foo ${
    Foobar.foo.bar.getFoobar()
  } foo bar foobarfoo foo bar foo foo bar.`
);
//                                                                            |
```

Right, string can not be wrapped automatically. So, a string can overflow the line. 
But this is not the problem. The problem is that Prettier should do it better, beacuse it is possible to wrap the string. 

I prefer following format rule: Similar to all other nodes... handle it like an array or object. Prettier formats it in a line. If the line overflows the max-line-length break each item / property and in this case each template variable. `${\n...\n}`. If this is a matter of taste, add an option for this format behavior.

What do you think? What's the current state? Is my request ridiculous and does not deserve any feedback on it? Or is this a never ending story? / Frequently asked? If so, an option is the correct way.

**Comment by j-f1** [comment] 2019-11-07 14:42
What would you suggest doing in cases [like this](https://github.com/desktop/desktop/pull/8576/files#diff-58ff4e099b0cf4fe166a9a04fe4a704c)?

```jsx
throw new Error(
   `Desktop command line interface not currently supported on platform ${process.platform}`
)
```

**Comment by MrCheater** [comment] 2019-11-07 15:08
- print-width: 80

```js
throw new Error(
   `Desktop command line interface not currently supported on platform ${
      process.platform
   }`
)
```

- print-width: 100

```
throw new Error(
   `Desktop command line interface not currently supported on platform ${process.platform}`
)
```


- print-width: 60

Prettier warning "Line 2 exceeds the maximum line length of 60 (print-width)"

```js
throw new Error(
   `Desktop command line interface not currently supported on platform ${
      process.platform
   }`
)
```

**Comment by Domvel** [comment] 2019-11-07 15:12
@j-f1 As described in my last post. 

```ts
//                                                         Max line width here \/
//                                                                             |
throw new Error(
  `Desktop command line interface not currently supported on platform ${
    process.platform
  }`
)
//                                                                             |
throw new Error(`This is shorter and fit the line width ${process.platform}`
)
//                                                                             |
```

Rule description:
Prettier should format this literal template string like e.g. Array or other nodes.
1. Try to format it in one line. 
2. If it will overflow, format it by wrapping the outer node.
3. If it still overflow format it by multiline. Break on each expression. `${\n...\n}`. 
4. Format the expression regardless from the template string rules.

```ts
//                                                                             |
console.log(
  `This ${
    one
  } is an example ${
    two
  } how a template string ${
    three
  } should look like.`
);
//                                                                             |
```

**Comment by Domvel** [comment] 2019-11-07 15:43
Just more infos: In my previous post I wrote about "Prettier should format the template string like with all other nodes (e.g. Array). Here is the current behavior how Prettier formats Array.

```ts
//                                                                             |
myArray = [one, two, three, four, five, six, seven, eight, nine, ten, eleven];
//                                                                             |
myArray = [
  one,
  two,
  three,
  four,
  five,
  six,
  seven,
  eight,
  nine,
  ten,
  eleven,
  twelve
];
//                                                                             |
```
Template strings should not be treated differently. The difference is just a few strings between the items. The strings itself are like items. Wrapped on `${\n...\n}`.

**Comment by thorn0** [comment] 2019-11-07 17:01
> Looks very clean, looks "Prettier".

No, it doesn't.

**Comment by Domvel** [comment] 2019-11-07 17:26
@thorn0 Really? You prefer the right side?

![](https://user-images.githubusercontent.com/35452565/68323223-4d14fd80-00c5-11ea-95e3-d172927a5ead.png)

Interesting... Maybe only these examples looks ugly for you. But ok, this is your opinion. I have no problems with an options. Regardless of the Prettiers options philosophy. It's required if there is a 50/50% thinking about this. Option `wrapTemplateStringExpressions` or inverted `uglyFormatTemplateString` 😛 Joke. This is my opinion and it looks like I'm not alone here with that. The majority. We could start a poll. But maybe an option could be the right choice.

As I wrote, it's about separating the code from the string and not scolling it vertically. (See the screenshot above.) I respect different opinions and tastes. In this case I cannot understand the other side. Maybe we should consider an option for it? (But again take a look to the screenshot above. 😃 )

**Comment by thorn0** [comment] 2019-11-07 17:33
As I wrote:

> I would agree that Foobar.foo.bar.getFoobar() shouldn't probably be considered simple. The heuristic might need a little improvement here.

Overall, please see #3368. I'm going to close this issue in favor of that one.

**Closed by thorn0** 2019-11-07 17:33 UTC
Labels: lang:javascript, status:needs discussion
