### ISSUE TITLE
Error: unknown type: undefined in ambient TypeScript definition

### ISSUE THREAD

**Issue by screendriver** [prettier/prettier#2765] opened 2017-09-07 05:53 UTC
**Prettier Version:** 1.6.1

**Code**

In my project I have a `declarations.d.ts` file for libraries that don't have TypeScript type definitions. Unfortunately following type definitions does not work anymore with prettier:

```ts
declare module 'data.maybe' {
  const Maybe: {
    fromNullable: <T>(nullable: T | undefined | null) => Maybe<T>;
    Just: <T>(t: T) => Maybe<T>;
    of: <T>(t: T) => Maybe<T>;
    Nothing: () => Maybe<never>;
  };
  interface Maybe<T> {
    value: T;
    get: () => T;
    getOrElse: <T2>(fallback: T2) => T | T2;
    map: <T2>(fn: (t: T) => T2) => Maybe<T2>;
    chain: <T2>(fn: (t: T) => Maybe<T2>) => Maybe<T2>;
    isNothing: boolean;
    isJust: boolean;
  }
  export = Maybe;
}
```

**Expected behavior:**

Should format the file.

**Actual behavior:**

```sh
declarations.d.ts: Error: unknown type: undefined
    at genericPrintNoParens (/Users/me/development/project/node_modules/prettier/index.js:7845:13)
    at genericPrint (/Users/me/development/project/node_modules/prettier/index.js:5288:55)
    at comments$3.printComments.p (/Users/me/development/project/node_modules/prettier/index.js:9929:14)
    at Object.printComments (/Users/me/development/project/node_modules/prettier/index.js:1771:19)
    at printGenerically (/Users/me/development/project/node_modules/prettier/index.js:9927:24)
    at FastPath$1.map (/Users/me/development/project/node_modules/prettier/index.js:1979:19)
    at printTypeParameters (/Users/me/development/project/node_modules/prettier/index.js:8510:48)
    at genericPrintNoParens (/Users/me/development/project/node_modules/prettier/index.js:7445:14)
    at genericPrint (/Users/me/development/project/node_modules/prettier/index.js:5288:55)
    at comments$3.printComments.p (/Users/me/development/project/node_modules/prettier/index.js:9929:14)
```

**Comment by ikatyang** [comment] 2017-09-07 06:02
Hi, this is a duplicate of #2718 and had been fixed yesterday.

As a temporary workaround you can put `// prettier-ignore` on the previous line:

```diff
declare module 'data.maybe' {
  const Maybe: {
    fromNullable: <T>(nullable: T | undefined | null) => Maybe<T>;
    Just: <T>(t: T) => Maybe<T>;
    of: <T>(t: T) => Maybe<T>;
+    // prettier-ignore
    Nothing: () => Maybe<never>;
  };
  interface Maybe<T> {
    value: T;
    get: () => T;
    getOrElse: <T2>(fallback: T2) => T | T2;
    map: <T2>(fn: (t: T) => T2) => Maybe<T2>;
    chain: <T2>(fn: (t: T) => Maybe<T2>) => Maybe<T2>;
    isNothing: boolean;
    isJust: boolean;
  }
  export = Maybe;
}
```

or install the newest version from github: 

```sh
npm install prettier/prettier
```

**Closed by ikatyang** 2017-09-07 06:02 UTC

**Comment by screendriver** [comment] 2017-09-07 06:14
Oh, thank you 👍  I oversight that other issue.
