### ISSUE TITLE
pre tags in .vue files are formatted incorrectly

### ISSUE THREAD

**Issue by ZobairQ** [prettier/prettier#10404] opened 2021-02-24 14:30 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAAQWVVmpYBOcZAbgLQAWAlgOZs7dswAVgGcyYfMOEBeYiAwAjFgGZZJctQ2pIAE0bi8kmSGEBHHKtIarlYMDImArnDoBPAHSPnLsgF8fl60pUAHodODVrEPpw0hDMXAJwkAAaEAgsGA5oYWRQPDo6CAB3AAV8hByUPBwivBcc1Pk6PDAAazgYAGUsFo4oLmQYOidUuAU4bV1tABk8foc8LjgAMQg6DAJM-uQQPAcYCBSQAQwcAHVOeGEesDhOio5MpkeXHbBJI77hZxgS5q4NsgAGbVb6pEQADwAQs02h1OngMHBpn04MDQXBwcIIZ0+lwcHAAIoOCDwdE4MEgHp0b50HZMJxHeh9GBnDjaGBsZAADgADKl6BBvmdmlgdtFaUw0alHKS4H90pVdsIWFA4BMJkcGI4OAw-otAUgQRTMcYxhxBsNTcI8QTiXLyZSYHh5GyOVykAAmVJDPAcPj9ADCEAwhpAcGEAFYjg5vgAVF2VY2UhlwACSUF0sE6YDoHAyAEFM50YC4CY64H4gA)

This is probably a duplication of following known issue. 
Known issue : [vue templates - pre tags single quotes dont get changed to double quotes](https://github.com/prettier/prettier/issues/5398)

#### However the issue is still present.

```sh
--parser vue
```

**Input:**
```vue
<template>
           <pre v-highlightjs class="mb-3">
            <code class="sql">
                {{ query.query }}
            </code>
        </pre>
</template>
```

**Output:**
```vue
<template>
  <pre v-highlightjs class="mb-3">
            <code class="sql">
                {{ query.query }}
            </code>
        </pre>
</template>

```

**Expected behavior:**
```vue
<template>
  <pre v-highlightjs class="mb-3">
        <code class="sql">
            {{ query.query }}
        </code>
   </pre>
</template>
```

**Comment by fisker** [comment] 2021-02-24 14:34
Duplicate of #7393

**Closed** 2021-02-24 14:43 UTC
Labels: type:duplicate

**Comment by thorn0** [comment] 2021-02-24 16:31
This is a correct and expected behavior, not a duplicate of that issue. All whitespace characters should be preserved in text content inside `pre`.

**Comment by ZobairQ** [comment] 2021-02-25 07:02
> This is a correct and expected behavior, not a duplicate of that issue. All whitespace characters should be preserved in text content inside `pre`.

Thank you for the explanation. This does make sense, I don't know why I couldn't see it myself :D
