### ISSUE TITLE
comments in array literal changes index if undefined

### ISSUE THREAD

**Issue by pushkine** [prettier/prettier#8083] opened 2020-04-19 17:34 UTC
**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACSUDONUBMCGM+qAvKgNqoD0AVAAw01UA0AjNTa41QLojMgIABxgBLaJmSh8AJxkQA7gAVZCSSnwAbBfgCekgQCMZ+MAGs4MAMpDToqAHNkMGQFc4AgBYwAtpoDqnqLwmLZgcFZqwaIAbsG6yOCYBiD2mHAyMEomDj74yABmWukCAFaYAB4AQibmllb4PnAAMvZwhcUeIOUVVvYOmnAAiq4Q8B2aJSC2MukyiYb4hnCa-NMy9jD+orgwnsgAHHQCQvLp-iZCiadwczHtAgCOo-DZwuog+JgAtFBwcLgAWsZHBnqIQdl8Ll8kgipMuukfKJnG4Ef1BiMxu1YZ0BERDNtdvskAAmPEmUSafoAYQgPjyiVuAFY1q50gAVJbqOFTGLuACSUEBsCsYA2IgAgkKrDBdIMJukAL6KoA)
```sh
--parser babel
```

**Input:**
```jsx
 const data = [ /*0**/,1 /*1**/]
```

**Output:**
```jsx
const data = [, /*0**/ 1 /*1**/];

```

**Expected behavior:**
```jsx
 const data = [/*0**/,1 /*1**/]
```

**Comment by evilebottnawi** [comment] 2020-04-20 11:22
Duplicate of #1013

**Comment by thorn0** [comment] 2020-04-20 12:23
This is not a duplicate. This issue is not about holes in arrays, not about destructuring.

**Comment by thecodrr** [comment] 2020-04-20 18:45
This is actually correct behavior. In the parser, empty array elements have no properties; they are `null`. Prettier follows the AST and in the AST the first empty element has no comment (the comment has moved on to the next non-empty element as its `leadingComment`). Here's the [babel repl link](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAJgQygmBeGBtGB6AVABl12wBoBGHXMo7AXSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.9.0&externalPlugins=) if someone wants to verify.

**Comment by thorn0** [comment] 2020-04-20 18:55
@thecodrr Prettier doesn't use Babel comment attaching logic. Even if it used, it'd still be a bug because the comment is moved.

**Comment by thecodrr** [comment] 2020-04-20 18:59
Prettier follows the AST given by Babel. In the AST, the empty element is `null`. It has no properties, comments etc. So if it is a bug, **it's Babel's bug** (check the repl), not Prettier's.

It can be fixed on the Prettier side but it would be a hack not a proper fix.

**Comment by thorn0** [comment] 2020-04-20 19:03
Prettier doesn't care how parsers associate comments with nodes. It has its own algorithm for this. Also remember that Babel isn't the only JS parser Prettier uses.

**Comment by thecodrr** [comment] 2020-04-21 05:14
I am looking into this. Will make a PR if I can get it solved.

**Comment by thorn0** [comment] 2020-04-21 05:55
I'd recommend starting with another [comment-related bug](https://github.com/prettier/prettier/issues?q=is%3Aopen+label%3Aarea%3Acomments+label%3Alang%3Ajavascript+) to familiarize yourself with how Prettier handles comments because this issue is tricky (in the same way #1013 is). E.g. #7968 looks like a better entry point.

**Comment by thecodrr** [comment] 2020-04-21 18:36
@thorn0 I will look into that too. However, I have almost resolved it (stress on almost :smile:) 

I have a question. How can we add comments to the `precedingNode` if the its undefined? Because that is precisely where the bug is. Is there a way to replace a node or create a dummy node into which we can add comments then?

**Comment by thecodrr** [comment] 2020-04-21 19:04
evilebottnawi #1013 is the same exact bug, don't know why @thorn0 removed the duplicate tag. Although the usage is different, internally both the bugs occur due to the same reasons.

**Comment by thorn0** [comment] 2020-04-21 21:29
> Don't know if it is legal to edit the AST?

Prettier already mutates the AST. BTW, it's in the comment attaching phase that this happens: it adds the `comments` property to nodes and does other things. But it shouldn't. It's technical debt that has to be refactored, and we don't want to add to it. Mutation makes Prettier less useful in [scenarios](https://twitter.com/sebmck/status/1240443965737861120) where ASTs are reused. Now, Prettier doesn't have a public API like `prettier.formatAST(ast)`, but it's going to have it one day. It'd already have it if not for those mutations.

> This is why I think it's a Babel bug

If anything, it's a "bug" in [ESTree](https://github.com/estree/estree).

**Comment by thecodrr** [comment] 2020-04-21 21:45
So then what would be the best way to replace the `null` elements with dummies? We'd need to give positions to the node for it to be recognized as `preceding` or `following`.

**Comment by fisker** [comment] 2020-04-22 07:35
1. If we have token in ast, we can attach to token.

2. Replace hole to a fake Node that can attach comments.

**Comment by thorn0** [comment] 2020-04-22 07:52
@thecodrr We could try to use the fact that the comment attaching algorithm doesn't operate directly on the AST. It builds its sorted node lists calling the printer's callbacks along the way, so it's possible to slip it a synthetic node-like object without mutating the AST.

@fisker Please see my comment above (https://github.com/prettier/prettier/issues/8083#issuecomment-617424564) about AST mutation.

**Comment by thecodrr** [comment] 2020-04-22 09:00
@thorn0 on it.

**Comment by thecodrr** [comment] 2020-04-22 09:16
@thorn0 

So I was able to get the printer callback work for us but still stuck here:
```js
    addLeadingComment(precedingNode, comment);
```
In the above code, the `precedingNode` is the empty element hence `null`. How do I "slip it a synthetic node-like object" without AST mutation?

**Comment by thorn0** [comment] 2020-04-23 16:59
@thecodrr "printer callback" - I meant `getCommentChildNodes`. Sorry, can't help you further with this. And you're right that this is a duplicate.

**Comment by thorn0** [comment] 2020-04-23 16:59
Duplicate of #1013

**Closed by thorn0** 2020-04-23 16:59 UTC
Labels: area:comments, lang:javascript, type:bug
