### ISSUE TITLE
Can we avoid splitting template literals in these cases?

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#3423] opened 2017-12-06 10:34 UTC
**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBDTBeTAAwBUALASwGdNLSIBXVAEygHItKAHVcrASUwBzenErUAJMABmECADoARtgBOAX0IBuADpR0WBfiJkqNOoxbsa3XpgHDRE6bIDarJctYBdddt0ZMYIYkFNS0DMxsHNb8QiJimJIyED4gADQgEJww5NCUyKAqyhAA7gAKKgh5KNgAbhDkTGkg2JQwyFLYqJRw6QrK2GAA1hgAypwD5FCCyDDKIulMEGDtnd3pk93KMKX9ggC22CtdPSAAVpQAHgBC-UOj2HtwADKTcEdrGfQwnF8ATO8ncbKTbIEBKBQAT1Q0CanGUkxgAHUGjBSMgACwABnScIg3UR-U4oLhojgyhqb3SyjgAEd6ORqTtsPtDkgOsd0t09uQZnMTpRJoJ0ABFegQeAA9IwbAKZFMVHIX5S-rkHhTADCED2B1BUGglJA9G6xBlVXZ3VUqiAA)
```sh
--print-width 40
```

**Input:**
```jsx
let a = `This shouldn't split I guess ${foo.bar}`;
let b = `This shouldn't split I guess ${foo['bar']}`;
let c = `This shouldn't split I guess ${foo}`;
```

**Output:**
```jsx
let a = `This shouldn't split I guess ${
  foo.bar
}`;
let b = `This shouldn't split I guess ${
  foo["bar"]
}`;
let c = `This shouldn't split I guess ${foo}`;

```

**Expected behavior:**

To me it feels like it shouldn't split the above lines, and only do that if there is something more complicated than dot notations or single objects from arrays.

**Comment by duailibe** [comment] 2017-12-06 11:25
This is a duplicate of #3368. Let's keep the discussion over there.

Thanks!

**Closed by duailibe** 2017-12-06 11:25 UTC

**Comment by lipis** [comment] 2017-12-06 11:31
Oups!
