### ISSUE TITLE
[Glimmer] 🐛 Linebreak added around closing tag and text comming just after

### ISSUE THREAD

**Issue by bartocc** [prettier/prettier#8527] opened 2020-06-08 14:01 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQHwBmEEqA9FrngEbYBOIANCBJjAJbTrKh20QDuABToIuKbABt+2AJ5cmVWtjABrODADKOMGygBzZDFoBXOEwAWMALYSA6ubbwKYOBtGO2AN0czk4dPIguuhwtDCCSnpW2MgEkiFMAFboAB4AQkqq6hrYVnAAMrpwsfFmIMkpGrp6EnAAisYQ8CUSCSA4tCH0KDVsVnn0TJi0ujC2bAAmMObIABwADEN8IbZKmH7DcF2exUwAjo3wESxiINjoALRQcHATt4wgtHAHbE8R2FExSHGtZSFWbEMJj+1VqDSaxW+pSYMGwVHGUxmSAATDClGwJNUAMIQfpfEBbACsD2MIQAKnCxD82p5TABJKB3WAaMAjVgAQUZGhgMlqLRCAF8BUA)

```sh
--parser glimmer
```

**Input:**

```hbs
<span>foo</span>bar
```

**Output:**

```hbs
<span>
  foo
</span>
bar
```

**Expected behavior:**

```hbs
<span>foo</span>bar
```

Formatting with `--parser html` produces the expected output. See this [playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQHwBmEEqA9FrngEbYBOIANCBJjAJbTrKh20QDuABToIuKbABt+2AJ5cmVWtjABrODADKOMGygBzZDFoBXOEwAWMALYSA6ubbwKYOBtGO2AN0czk4dPIguuhwtDCCSnpW2MgEkiFMAFboAB4AQkqq6hrYVnAAMrpwsfFmIMkpGrp6EnAAisYQ8CUSCSA4tCH0KJY2jO20ujC2bAAmMObIABwADEyYfCG2Sph+C3BdnsVMAI6N8BEsYiDY6AC0UHBwo9f9tHB7bPcR2FExSHGtZSFWbIYm32qtQaTWKH1KTBg2CoI3GkyQACZIUo2BJqgBhCBWaJ+DYAVn6xhCABVoWJPm1PKYAJJQG6wDRgQasACCdI0MBktRaIQAvrygA)

When rendered, the browser displays `foo bar` while it should display `foobar`

**Comment by kangax** [comment] 2020-06-30 16:56
@dcyriller do you know if we're able to reuse some of html printer behavior in glimmer? is this a common thing? I think in this case we could mostly just use HTML semantics and take special care of things like adjacent mustache statements.

**Comment by dcyriller** [comment] 2020-06-30 17:29
This was my first idea and it would be awesome because most of the work to solve this issue would be done. But unfortunately html parser doesn’t support handlebars syntax (especially modifiers). So we can’t embed html printer in handlebars.

**Comment by kangax** [comment] 2020-07-14 15:44
I went down the rabbit hole of figuring out how this should work 😁 Found few things. HTML parser is quite different from the JSX one. HTML parser also has 3 whitespace modes (css, strict, ignore) which gives us 4 different outputs to compare to, yay.

Here's some sample input of various mixed content (first 4 in 1-line form, last 4 in indented form):
```html
<div>
<div>hello<span>world</span></div>
<div><span>hello</span>world</div>
<div><span><input type="text" /></span></div>
<div>just text</div>
<div>
  hello<span>world</span>
</div>
<div>
  <span>hello</span>world
</div>
<div>
  <span>
    <input type="text" />
  </span>
</div>
<div>
  just text
</div>
</div>
```
We get this output:

### JSX

```html
<div>
  <div>
    hello<span>world</span>
  </div>
  <div>
    <span>hello</span>world
  </div>
  <div>
    <span>
      <input type="text" />
    </span>
  </div>
  <div>just text</div>
  <div>
    hello<span>world</span>
  </div>
  <div>
    <span>hello</span>world
  </div>
  <div>
    <span>
      <input type="text" />
    </span>
  </div>
  <div>just text</div>
</div>;
```

### HTML (css)
Notable difference is that it doesn't try to format child tags *unless* they're already formatted.

```html
<div>
  <div>hello<span>world</span></div>
  <div><span>hello</span>world</div>
  <div>
    <span><input type="text" /></span>
  </div>
  <div>just text</div>
  <div>hello<span>world</span></div>
  <div><span>hello</span>world</div>
  <div>
    <span>
      <input type="text" />
    </span>
  </div>
  <div>
    just text
  </div>
</div>
```

### HTML (strict)
Mostly the same as "css" except all whitespace is significant.

```html
<div>
  <div>hello<span>world</span></div>
  <div><span>hello</span>world</div>
  <div
    ><span><input type="text" /></span
  ></div>
  <div>just text</div>
  <div> hello<span>world</span> </div>
  <div> <span>hello</span>world </div>
  <div>
    <span>
      <input type="text" />
    </span>
  </div>
  <div>
    just text
  </div>
</div>
```

### HTML (ignore)
This looks remarkably similar to JSX in that it breaks *all* nested tags except JSX does it in a safer way. Notice, e.g. mixed content (`hello<span>world</span>`) being preserved in JSX but not here.

```html
<div>
  <div>
    hello
    <span>world</span>
  </div>
  <div>
    <span>hello</span>
    world
  </div>
  <div>
    <span><input type="text" /></span>
  </div>
  <div>just text</div>
  <div>
    hello
    <span>world</span>
  </div>
  <div>
    <span>hello</span>
    world
  </div>
  <div>
    <span>
      <input type="text" />
    </span>
  </div>
  <div>
    just text
  </div>
</div>
```

Now the question is — what should glimmer do? 

There are few ways to go about it. We could just follow what JSX does. JSX printer looks like a good compromise between html-ignore-whitespace (that looks too lax / broken up) and html-default-css (that looks too squished in cases when lines are not already formatted).

We could follow (default, css) HTML implementation. I worry about cases where tags' default behavior is overwritten and it'd break formatting, the whole reason why Prettier has "strict" mode.

Another option is to try to completely follow HTML parser behavior, including support for css/strict/ignore flags. This would also be the hardest and longest way.

I quite like going the JSX route, at least for the MVP version — it'd provide consistent breaks while being conservative with the whitespace. Thoughts?

**Comment by kangax** [comment] 2020-07-14 16:11
Here's a [draft PR](https://github.com/prettier/prettier/pull/8758) that fixes most (all?) of whitespace issues but collapses all tags into 1 line as long as they fit. Probably not the formatting behavior we're looking for but it does result in a significantly more correct rendering.

```html
<div>
  <div>
    hello
    <span>world</span>
  </div>
  <div>
    <span>hello</span>
    world
  </div>
  <div><span><input type="text" /></span></div>
  <div>just text</div>
  <div>
    hello
    <span>world</span>
  </div>
  <div>
    <span>hello</span>
    world
  </div>
  <div><span><input type="text" /></span></div>
  <div>just text</div>
</div>
```

**Comment by thorn0** [comment] 2020-07-14 17:00
@kangax Formatting `hello<span>world</span>` to
```
    hello
    <span>world</span>
```
doesn't look like being conservative with the whitespace.

Did you read the [explanation](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting) of the `--html-whitespace-sensitivity` option? If in Glimmer, whitespace works the same way it does in "normal" HTML, then this option with its 3 values needs to be implemented for Glimmer too.

**Comment by kangax** [comment] 2020-07-14 17:27
@thorn0 JSX seems to strike a good balance between formatting and correctness; it breaks tags stuffed on one line, for example, without breaking whitespace (`<span>hello</span>world`). AFAIU, if we follow JSX behavior, we can avoid the complexity of having 3 flags.

I just noticed that my draft PR breaks `<span>hello</span>world` — is this what you meant? Yeah, that's no good, I'll look into it.

**Comment by thorn0** [comment] 2020-07-15 00:16
@kangax JSX has **completely** different rules for whitespace handling. They can't be used for HTML.

**Comment by boris-petrov** [comment] 2020-08-27 06:20
@kangax - my personal view is that Prettier is a code formatter and nothing else. In that sense it should *not* break code. That means when formatting JavaScript, to not output code that has a different meaning. Same for HTML - it shouldn't generate a result that has different semantics from the original. So the output I've given in the [other issue](https://github.com/prettier/prettier/issues/4908#issuecomment-680022321) is, for me, absolutely unacceptable.

I think the best way, obviously, is to support the same options as the `html` parser - namely `htmlWhitespaceSensitivity`. Of course, that's most likely a ton of work which none of you/us can invest, so for me the right way is to just choose one of the variants and hardcode it - namely `strict`. That preserves the semantics as best as possible and will not break people's code (which is a good thing if you format 1000 files and you don't have 100% test coverage with screenshots for everything to check for regressions). That way people can write whitespace-sensitive HTML and not worry that the formatter will break it by rearranging stuff.

**Comment by dcyriller** [comment] 2020-08-27 08:29
I like the idea of changing the default of handlebars printer from `htmlWhitespaceSensitivity: ignore` to `strict`. It should be a reasonable amount of work (compared to developing the `css` option). And it would make Prettier for handlebars much more usable. Also it shouldn’t make the development of a `css` mode harder.

**Comment by jede** [comment] 2020-09-08 09:25
I think one approach could be to respect `<!-- display: inline -->` until `css` mode is done? Right now it seems to be ignored. [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgCYCWAzgA4A2AhgJ5I4FRn1w7YB8AOlKoQG6sAWcMmQg5Bw0eJFih0qZNkKJM5fJVzF6pRtWa1+vZtQB6XqwBGFAE4gANCAgkYBaEWShrViAHcACtYQ3FAoyb2o3e3MrCjAAazgYAGUSGPoAc2QYKwBXOHs4AFtzODw8EoAZCig07Io0uAAxCCsCihhnauQQCmyYCDsQfhgCsgB1fgJ4Uhi4RMDJgh5Jqi6CNKhmuAH6IjgrGF9otNbkADMQ3fsAKyIADwAhaLiExIoCuHKmM4u8kBvbxLpMhwACK2Qg8G+ZEuIBSVl2NhQQxGAxIVnoMFGBDwMH4yAAHAAGexoiC7UbREhdNFwBE8Lb2ACO4Pgh0cQW6REwUDgJRKAyscGZBEFhzqJyQ52hv12BQImRyMqBoJZW0lP3sMAo5ixOLxSAATJrogRGNUAMIQAoSkC0gCsA2yuwAKtqglKYTxcgBJKBlWCJMDopwAQT9iRgVGBUN2AF9Y0A)

**Comment by mamiller93** [comment] 2020-12-04 15:49
Any updates to this? Or any workarounds other than not using the parser?

**Comment by kangax** [comment] 2020-12-07 21:07
@mamiller93 No workarounds that i'm aware of. This is still on my radar as that's one of the blockers for us to start using this internally at LinkedIn. I've been caught up with other work stuff and haven't had time to work on it.

**Comment by dcyriller** [comment] 2021-01-25 15:49
@kangax FYI I implemented the `--htmlWhitespaceSensitivity=strict` option for Handlebars in #9885. The formatting should be correct. But it can be improved.

**Comment by dcyriller** [comment] 2021-01-25 15:52
#9885 might close this issue? 🤔 

[Playground link for the PR](https://deploy-preview-9885--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQHwBmEEqA9FrngEbYBOIANCBJjAJbTrKh20QDuABToIuKbABt+2AJ5cmVWtjABrODADKOMGygBzZDFoBXOEzgBbKnAAmN2wBlce49j1wAYhFoXsMdvrIINjGMBCMIAAWMBYSAOqRbPAUYHAaoklsAG5JMkHoRmxgMBG66HC0MIJKer7IBJLlTABW6AAeAEJKquoa2BZwDrpw9Y1mIK1tGrp6EnAAisYQ8KMSTSA4tOX0KLNsFgP0TJi0ujBxbDYwkcgAHAAMx3zlcUqYQSdw21kjTACOS3g1RYYmC6AAtFA4LZbBFaHAAWx4dU3HUkA01uNyhY2IYTFiZnNFssRuixkwYNgqBcrjckAAmClKNgSGYAYQgB2wQS+AFYIsZygAVKliDHrLKmACSUHssA0YFOrAAgrKNDAZHNVuUAL46oA)

**Comment by thorn0** [comment] 2021-01-25 22:16
Okay, let's consider this fixed.

**Closed by thorn0** 2021-01-25 22:16 UTC
Labels: lang:handlebars, type:bug

**Comment by bartocc** [comment] 2021-01-27 08:49
thx for the work on this @dcyriller 👍
