### ISSUE TITLE
Non-idempotent output with chained function calls and tab-width 2 or less

### ISSUE THREAD

**Issue by midgleyc** [prettier/prettier#12562] opened 2022-03-31 09:01 UTC
**Prettier 2.6.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAE5wDOAlPsADpT746r4kxnpy0NPP4KlAHSUYAQxjpKJACwAGedWEArStBLB8cMmQhkAcuIC2cJPnogAbuIA2OACaS4AMXE5bcB5YA023frmAOQAstIw+AAOelaOOlEAFtBw+FDoxgBG8QDuODAJ+A5wqOLothHRELFFZEH4AL7UANwW-MwUUmRQTYzM9Yz1ID4gEJG40JTIoOIB2QAKMwiTKHbZ4gCek8MZZOJgANZwMADKJnAAMjhQcMgltpRw27sHR8eRe1cA5sic3MNwmS8RQc53EUE+6HEn1c+mMklw4OQIFKMAgQxACRgxlsAHUEnkqO8wHBjks8jhYjB1kiwJQtiArg8yDA5rtPnDbnYHsM1AAPY5fTwARXQEHgnPujxA7zITKRGXEWVs6OiVxgOMc+WQAA55MNKg8cbtIkjolQdFYbsMAI6i+Cs0bLZGUAC01y8XnRFFtOAorKhHKQd25IAexhwPy4UsogrgIrFNyDXKlEgyGocWqQACZhpx3PZwQBhCDGQMgKgAVnR0jgABVFctg1KrNwAJJQIqwY5gMg4MYAQQ7xypnglD3q9SAA)

```sh
--parser babel
```

**Input:**

```js
function foo(res) {
  if (true) {
    res.status(400).json({ errorName: "validateFailed", error: 'Must provider phone number with default provider' }); 
    return;
  }
}
```

**Output:**
(First run)

```js
function foo(res) {
  if (true) {
    res
      .status(400)
      .json({
        errorName: "validateFailed",
        error: "Must provider phone number with default provider",
      });
    return;
  }
}

```

**Expected behavior:**
(Second run, should also be first run)

```js
function foo(res) {
  if (true) {
    res.status(400).json({
      errorName: "validateFailed",
      error: "Must provider phone number with default provider",
    });
    return;
  }
}
```

**Comment by midgleyc** [comment] 2022-03-31 15:43
Looks like it, yes.

**Comment by kachkaev** [comment] 2022-03-31 17:10
Closing as duplicate of https://github.com/prettier/prettier/issues/2803

**Closed by kachkaev** 2022-03-31 17:10 UTC
