### ISSUE TITLE
Support for custom tagged template literal in styled-components

### ISSUE THREAD

**Issue by mrozilla** [prettier/prettier#2402] opened 2017-07-05 20:41 UTC
Kudos for the v1.5.0 release!

Following #2291 I noticed another place where prettier pretties a bit too aggressively for styled-components:

Before:
```javascript
export const Element = styled.element`
  ${props => props && media.lg`
    display: flex;
  `};
`;
```
After:
```javascript
export const Element = styled.element`
  ${props =>
    props &&
    media.lg`
    display: flex;
  `};
`;
```
The expected behaviour is to not to break the lines after ```=>``` and ```&&```. 

I'm assuming that this is mainly because anyone can create their own tagged template literal, e.g. as specified in https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md#media-templates

Looking at the discussion in #2337, is there anything we could do about this?

**Comment by vjeux** [comment] 2017-07-05 21:00
Yeah, we should make cond && `template` on the same line and if inside of an arrow function, make it in the same line as well.

A PR would be welcome.

**Comment by philpl** [comment] 2017-07-10 10:11
It'd be great to support this, but I'd like to add that this will be unsupported in the future once we introduce stable preprocessing :)

**Comment by j-f1** [comment] 2018-01-29 22:31
It looks like this is a duplicate.

Duplicate of #1872

**Closed by j-f1** 2018-01-29 22:31 UTC
Labels: help wanted
