### ISSUE TITLE
Prettier exceeds the maximum line length on single-import imports

### ISSUE THREAD

**Issue by sk22** [prettier/prettier#2564] opened 2017-07-30 15:27 UTC
Prettier changes the import statements that only import one thing to its one-line equivalent, which exceeds the maximum line length.

For example, this

```javascript
import {
  productsByCategory as productsByCategoryPropType
} from '../aggregatorsPropTypes'
```

becomes this:

```javascript
import { productsByCategory as productsByCategoryPropType } from '../aggregatorsPropTypes'
```

It should rather be opposite of that, in my opinion. Not exceeding the maximum line length should be prioritized.

**Comment by josephfrazier** [comment] 2017-07-30 17:33
I think this is a duplicate of https://github.com/prettier/prettier/issues/1954, which was closed with the following [comment](https://github.com/prettier/prettier/issues/1954#issuecomment-306067705):

> This is actually intended. We have a special case for import and require with single elements where we keep them in a single line. You don't get much more information when they are in two lines and they look worse with a series of imports. This was done due to common request from people using prettier.

**Closed by josephfrazier** 2017-07-30 17:33 UTC
