### ISSUE TITLE
markdown bug when converting underscores to asterisks

### ISSUE THREAD

**Issue by revelt** [prettier/prettier#4362] opened 2018-04-24 04:18 UTC
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBlCBbOACAzlAQwGs4B9MA3HAMwEsAnXGAOmwBUALBbDCeneAA8W7LlDyYcvfq07dS-AgBsAtABM4y0tgJQ1ErDz4C4w5gB0oIADQgIABxi1ouZKAL16EAO4AFDwiuKAQAbhC0ajYgAEb0BGAkMKj28bRQAObIMPQArnC2aVT0ML5x6RgEyNTKVLYAVriCAEJxCXBJBFgAMmlwVTX5ICmMcPTIIBX0RGo+Vrb29GkwAOoRMBzIABwADPNeVMtx9uPK3gQAnq62-ACOOQxwpQTllUjVSrUgVBi0WbmDuDS6SUcAAijkIPB+h9BjACNFVmp1sgAEy2bIEWhKIEAYUwFXGUGgfVsOSobHhQXeVAAvjSgA)
```sh
--parser markdown
--prose-wrap always
```

**Input:**
```markdown
Some snake_case first. Then more text. Then some more. Then _real-deal_ and some more text.

```

**Output:**
```markdown
Some snake*case first. Then more text. Then some more. Then \_real-deal* and
some more text.

```

**Expected behavior:**
This is how Prettier introduced an error on my flagship npm library's readme. Basically, before "assumed" starting point of the underscored chunk of text is accepted, we should check, is there a whitespace character (trimm-able to nothing or index zero, being start of the string). Because if not, if there's a word to the left, algorithm should bail. Especially (or at least) in cases where *the end* of the range is followed by whitespace character.

Thank you everybody for your support and time.

**Comment by ikatyang** [comment] 2018-04-24 04:25
This is caused by [remark mis-parsing](http://astexplorer.net/#/gist/1ed8b17e50a0806b002351a9c9142965/fdbcca9bb05302657f3440d7dd755dbd7f0dcced).

Closing as duplicate of #4064.

**Comment by ikatyang** [comment] 2018-04-24 04:25
Duplicate of #4064

**Closed by ikatyang** 2018-04-24 04:25 UTC

**Comment by revelt** [comment] 2018-04-24 04:29
Oops! Sorry for duplicate. I'll raise this with remark. Thanks!

**Comment by ikatyang** [comment] 2018-04-24 04:36
Actually, I already raised an issue there --> remarkjs/remark#306.

I should mark this as duplicate of #3837 instead.

**Comment by ikatyang** [comment] 2018-04-24 04:37
Duplicate of #3837

**Comment by revelt** [comment] 2018-04-24 04:38
Thanks again. You're so quick!
