### ISSUE TITLE
Typescript generic formatting with width limit wraps

### ISSUE THREAD

**Issue by kwonoj** [prettier/prettier#5579] opened 2018-11-30 18:14 UTC
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbAhgSygBEAbEgUVgCcBPABQkKwF5MB3fGACwgFcYAFAG1MAcjAl8AWhi4ARiThSqcACZxsABxj5oozAF0ANJgB05uAA94VKLhJE4mhOqhh8cNAEpMuNJgBBKipcGgAeDCpCAHMAPgBuECMQCG1dKDRkUFxgiDY6HIRMlHs2UMzkuRCwAGs4GABlTVx3KGjkGCpeOGSuGGwSAHUuTk9msDgGos58ADdOGmRwNAqQQjQ4Khg6EOi8ZAAzew3kgCs0SwAharrG3Gw4ABlCOEPjnpBzywaYxQBFXgQeBvEgnEDNKgbKhLGA0ZxoMBRbRJcFUCAbQYhTRLTQqKGzV7JFQAR14+BUO1we1wILBG2w+A6XQ+aF+cABQNeSCOoI+sjkg3wqm4yAATMlOgRJG0AMIQbD7FBQaCEkC8DYAFXkxR5YNxTEFwq4yAAjAAGM0AX0tQA)
```sh
# Options (if any):
--print-width 100
```

**Input:**
```ts
const mainDllEntryPoint = without([ 'cli-table-redemption' ], ...externalDependencies) as Array<string>;
```

**Output:**
```ts
const mainDllEntryPoint = without(["cli-table-redemption"], ...externalDependencies) as Array<
  string
>;
```

**Expected behavior:**

Given example line is hitting width limit (100) in generic param, specifically
```
as Array<string>;
            ^ //where 100 widh limit
```

between generic param token `<` and `>`. It is expected to line wraps, but formatted output is somewhat verbose as

```
as Array<
  string
>;
```

which splits generic param token as each newlines. I am not sure if there's way to configure to consider whole type including generic as chunk to be wrapped into, i.e 

```
without([ 'cli-table-redemption' ], ...externalDependencies) 
  as Array<string>;
```

or any other way else.

**Comment by j-f1** [comment] 2018-11-30 19:12
Duplicate of #5554

**Closed** 2018-12-04 09:03 UTC
Labels: lang:typescript, type:duplicate
