### ISSUE TITLE
[bug 1.4.1] semicolon insertion before ArrayExpression and others

### ISSUE THREAD

**Issue by Andarist** [prettier/prettier#1935] opened 2017-06-03 08:58 UTC
`--no-semi` affects this

`[]` produces `;[]`
`({})` produces `;({})`
`<div/>` produces `;<div/>`

Possibly other expressions are affected too. 

The weird part is that by going back in git's history to the `v1.4.0` or even before that still produces the same result. However those cases didnt parse like this on `v1.4.0` nor on `v1.3.1`.

You can checkout what prettier have changed for our codebase when upgrading to `v1.4.0` (ive ran prettier on all files) [here](https://github.com/redux-saga/redux-saga/commit/35c9ea129a520f36408298943c06c2dcd7ad3776). State before that upgrade is also full-prettier on version `v1.3.1`.

After an attempt to upgrade to `v1.4.1` those [2 lines](https://github.com/redux-saga/redux-saga/blob/35c9ea129a520f36408298943c06c2dcd7ad3776/src/internal/io.js#L83-L85) got affected by the 'bug' described, I didnt commit it yet though.

I could have some stale npm packages in my `node_modules` before (didnt `rm -rf node_modules` after upgrade or before), maybe that was the case? Dunno how to verify that though

Nevertheless the behaviour is rly weird and I guess it should be fixed. Can help with that if u give a green light to it ;)

**Comment by Andarist** [comment] 2017-06-03 11:06
so I've diagnosed the 'issue' and it seems this is inserted intentionally to [prevent issues with automatic semicolon insertion](https://github.com/prettier/prettier/blob/f56f9e5e8fb38f4d30c02984539cd0d28dcf6aab/src/printer.js#L4530). Dunno why this was not acting like this before v1.4.1 for me.

However that being said - it shouldnt be inserted automatically, only when the problem really might occur. For example eslint recognized those different situations correctly, it wont have problem with allowing `[]`, however it will warn when something like this is written:
```js
someCall()
[a] = obj
```
and the possible fix for the problem is to put semi at the end of the **previous** line like this
```js
someCall();
[a] = obj
```

I think this looks way more naturally and we should print like this, gonna dig into the code to see if I can make that happen.

**Comment by azz** [comment] 2017-06-03 11:24
Having the semicolon at the start of the line is more common with semi-colon-less development. It makes it obvious that the semi-colon is there for a semantic reason.

https://standardjs.com/rules.html#semicolons

The reason we always print the semi-colon at the start, even if it isn't strictly required, is that it makes it easier to move lines of code around the file without accidentally introducing ASI issues.

Closing this as prettier is working as intended.

**Closed by azz** 2017-06-03 11:24 UTC

**Comment by Andarist** [comment] 2017-06-03 11:33
@azz 
Hm, i understand the reasoning, guess its ok to prefer semi at the start. However would prefer to add them only if strictly required. This looks really odd:
```js
  if (is.array(fn)) {
    ;[context, fn] = fn
  } else if (fn.fn) {
    ;({ context, fn } = fn)
  }
```

> it makes it easier to move lines of code around the file without accidentally introducing ASI issues.

this argument is OTOH not that much appealing as prettier would just prevent ASI when formatting, its an automated process after all

also this conflicts with [`no-extra-semi`](http://eslint.org/docs/rules/no-extra-semi)

**Comment by lydell** [comment] 2017-06-07 08:39
This has already been discussed numerous times.

- https://github.com/prettier/prettier/issues/736#issuecomment-291934981
- #1388 
- #1566 
- #1433
