### ISSUE TITLE
Suggestion: Unify colour formats within CSS/Styled Components

### ISSUE THREAD

**Issue by nathggns** [prettier/prettier#3523] opened 2017-12-18 17:39 UTC
Is it possible for prettier to update different colour formats to make them more consistent within CSS & Style Components? 

So that:

```
color: black;
border-color: #fff;
background-color: #F6F6F6;
```

Can become

```
color: #000000;
border-color: #ffffff;
background-color: #f6f6f6;
```

**Comment by josephfrazier** [comment] 2017-12-18 18:41
I think this is a duplicate of https://github.com/prettier/prettier/issues/2139

**Comment by duailibe** [comment] 2017-12-31 14:27
Yeah, from https://github.com/prettier/prettier/issues/2139#issuecomment-309568760:

> I agree that normalizing 3 vs 6 seems out of scope and likely going to create a lot of drama for something that doesn't really matter. Another thing that people would likely want is to replace hex values with named colors when they exist. I think that both are better implemented as lint rules with autofix.

**Closed by duailibe** 2017-12-31 14:27 UTC
