### ISSUE TITLE
await with nullish coalescing  should not be wrapped inside parenthesis

### ISSUE THREAD

**Issue by villesau** [prettier/prettier#7703] opened 2020-03-03 11:37 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzKmC8mAhmgJ5RiYAURAlAQHybAA6emHATnDAK6d4imAPzDiAdyIBLLAAVOEALZS0cAHTc0EADYA3OFQCMAJgDMtNgF82bXFVpqYACwQ1GmSFC3b12iAHMaWloQABoQCAAHGCl0ZFAiTgVxWUSENGQQIl0IKQATMJAAI04iMABrHgBlSLKpKH9kGE5eOHCnGEVtAHUnGTg0WrA4KvSZKV0ZUkywNAzw+tVOGHkif0UiZGwibVVwgCs0AA8AIVKK6qJFOAAZergtnb2QQ6Oq+v8fAEVeCHhH3ZtEC1ThLTJFIhFUh+KCFSKceowbr5ZzIAAcAAZwvCIKpuqVIpl4QM4Jx9IUAI6-eDyKIZFAkAC0UDgcDybMK3CpUm4q3WmyQ20B4VUyiaLSBaA+32pD0FTyBMEhyLyqKQxnCzWk2g+AGElBtMlBoA9wrxVAAVSH0oWqSyWIA)
```sh
--parser babylon
```

**Input:**
```jsx
const fn = async (a) => {
    return a ?? await Promise.resolve(123)
}

fn().then(a => console.log(a))
```

**Output:**
```jsx
const fn = async a => {
  return a ?? (await Promise.resolve(123));
};

fn().then(a => console.log(a));

```

**Expected behavior:**

```jsx
const fn = async a => {
  return a ?? await Promise.resolve(123);
};

fn().then(a => console.log(a));

```

The reasoning for this is that it would be consistent on how Prettier currently treats ternaries & `await`, and personally I find it more readable without parnthesis:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzKmC8mAhmgJ5RiYAURAlAQHybAA6emHATnDAK6d4imAPzFMSYgHciASywAFThAC2MtHAB03NBAA2ANzhUAjACYAzLTYBfNm1xVaGmAAsENRpkhQduzbogAcxpaWhAAGhAIAAcYGXRkUCJOJUl5ZIQ0ZBAifQgZABMIkAAjTiIwAGseAGVoipkoQOQYTl44SJcYZV0AdRc5ODR6sDgazLkZfTlSbLA0LMjG9U4YRSJA5SJkbCJddUiAKzQADwAhcqraomU4ABlGuB29g5Bjk5rGwL8ARV4IeDPfYdED1TgrbIlIglUgBKDFaKcRowXqFVzIAAcAAZIoiIOpeuVotlEUM4JxDMUAI7-eCKGJZFAkAC0UDgcAKHOK3BpMm46022yQu2BkXUqhabRBaC+v1pT2FLxBMGhqIK6KQpkirVkui+AGEVFtslBoE9Irx1AAVaGMkXqazWIA

**Comment by sosukesuzuki** [comment] 2020-03-03 12:20
This happens with all binary operators, not only null coalescing.

**Comment by villesau** [comment] 2020-03-03 12:53
@sosukesuzuki Thanks for clarification. Then it would make sense to unify the behaviour with ternary for all of the binary operators?

**Comment by sosukesuzuki** [comment] 2020-03-03 14:18
@villesau Personally, yes.
How do you think? cc: @evilebottnawi @thorn0

**Comment by thorn0** [comment] 2020-03-03 14:56
I think the current behavior is fine.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABAXnag7qgSxnQA90B+dAT3SXQC8BuAHSg2zMr0OJrqdbtSFarRz4iDFlFYAjLOJ7CA1NRAAaEBAAOMAtADOyUKgBOpiLgAKZhEZSoAbhAIATDSFmnUYANZwYAGVtHwIoAHNkGFMAVzhNAAsYAFsAGwB1BKI4AxCwOEC7IgJHIipkcAMjTTCDOFMYK29w5NRkADNUVLrNACsDEgAhbz8AwNRkuAAZMLgOrp6QfpJAsPDUuABFGIh4ee74kBDTOtMK2VRZOFSPbVMwmHS3GATkAA4ABk07iDr0720FTuOXqjjmmgAjjt4E0dPY0AYALRQOBwVxojymOBQghYpqoFptJCdA6aOrJAhRWKHAxrDbbXZzYkLQ4wS5PVwvZAAJk00UIqTWAGEIMlWhUoNBwSAYnUACqXewkxaOOIASSg6NggTA910AEFNYEYFQNvs6gBfC1AA)

**Output:**
```jsx
a = (await x) ? y : z;
a = x ? await y : z;
a = x ? y : await z;

b = (await x) + y;

```

See https://github.com/prettier/prettier/issues/3089, https://github.com/prettier/prettier/issues/6339

**Comment by thorn0** [comment] 2020-03-03 14:56
Duplicate of #3089

**Closed by thorn0** 2020-03-03 14:56 UTC
Labels: lang:javascript, type:bug
