### ISSUE TITLE
How to apply jsxBracketSameLine to Vue.js HTML?

### ISSUE THREAD

**Issue by mrichman** [prettier/prettier#8193] opened 2020-04-30 12:12 UTC
Prettier formats my .vue HTML with a closing bracket on its own line:

<img width="293" alt="image" src="https://user-images.githubusercontent.com/11228/80708792-3a9ae000-8aba-11ea-98ea-9d586f94051b.png">

I'd like the equivalent of `jsxBracketSameLine`, where it will put the `>` of a multi-line HTML element at the end of the last line instead of being alone on the next line.

**Comment by thorn0** [comment] 2020-05-01 15:23
Duplicate of #5377

**Closed by thorn0** 2020-05-01 15:23 UTC
