### ISSUE TITLE
Parentheses removed around ?? operator causing Flow error

### ISSUE THREAD

**Issue by olegbl** [prettier/prettier#6762] opened 2019-10-30 19:07 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBLNBBAGwIBEBDAT0wF4AdKTTACjgDcEYA6XAfVKO4AmFbq3aYA-OMwAzPmjgBKTAB9ldBszawAyjFIAnTtigZSsTAB4qmIeV0GjJveYBkL9Q0yjYAUSgCuJzMsAD5rWz8A41NYBQBuEAAaEAgABxhsdGRQA30IAHcABQMENGQQUhYIbAEkkAAjfVIwAGs4GG1U5uMAc2QYfQBXOGSACxgAWwIAdVHseDQusDhtUvnsFnnycrA0MuTouENCpp6J0mRZAnlkgCs0AA8AISbW9u1SCbgAGWM4S7kIxA9we2l6BDgAEVBhB4ADrkCuvp5PpyvVSPU4AQ6ql9MYYNMajBRsgABwABmSuIg8mmTVS5VxcBRbDqAEcYfATmkyihSGgALRQOBwASiur6OAc7CSk6kM4XJBXG4geQTbD9IZAtDgqGc-5KwHJPT1QkCYnIABMxqa2AIvQAwhAJudylBoP9koN5AAVDG85VwAC+QaAA)

**Input:**
```jsx
const isAllDay =
  (event.is_all_day_event ?? false) ||
  (eventStart.instant <= dayStart.instant &&
    eventEnd.instant >= dayEnd.instant);
```

**Output:**
```jsx
const isAllDay =
  event.is_all_day_event ??
  false ||
  (eventStart.instant <= dayStart.instant &&
    eventEnd.instant >= dayEnd.instant);
```

**Expected behavior:**
```jsx
const isAllDay =
  (event.is_all_day_event ?? false) ||
  (eventStart.instant <= dayStart.instant &&
    eventEnd.instant >= dayEnd.instant);
```

This conversion introduces a Flow error:
```
Unexpected token ||. Parentheses are required to combine ?? with && or || expressions.
  96|
  97|   const isAllDay =
  98|     event.is_all_day_event ??
  99|     false ||
 100|     (eventStart.instant <= dayStart.instant &&
 101|       eventEnd.instant >= dayEnd.instant);
 102| 
```

**Comment by olegbl** [comment] 2019-10-30 19:16
Probably the same thing as https://github.com/prettier/prettier/issues/6403 which was closed but not actually fixed. e.g. [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAZhCACA-L7AIwEMAnASmwB8qjiAvEAGhAgAcYBLaAZ2VDKkIAdwAKZBHxTEAbhE4ATZiEKliYANZwYAZTbrOUAObIYpAK5wWACxgBbADYB1a53g99YODslvOMtwBPZHAePhZDHjhSGFE1IztiZHRiByiWACseAA8AITVNbR1iOzgAGUM4ZNT0kCzsnUMjBzgARXMIeGq0qxB9UijSEJJCOAdlNlJDGCdFGGtkAA4ABhZJiCinNTYQybhBmSqWAEcO+Dj2KRBiHgBaKDg4BSflUjhTzje44gSkpBSeiwonZOKYLL0eE0Wu1OlV-jVejBiIRZgp5sgAEwsMzETgOJoAYQgdkSISg0COIHMUQAKsipACogBfJlAA)

**Comment by thorn0** [comment] 2019-10-30 19:47
Fixed, but not released yet.

Duplicate of #6403

**Closed by thorn0** 2019-10-30 19:47 UTC

**Comment by thorn0** [comment] 2019-10-30 19:51
The release 1.19 is going to happen pretty soon. But if this issue blocks you, you can install Prettier directly from GitHub.

In your `package.json`, replace
```json
"prettier": "^1.18.2"
```
with
```json
"prettier": "prettier/prettier"
```
