### ISSUE TITLE
Request: making verbose JSX ternaries opt in or opt out.

### ISSUE THREAD

**Issue by drcmda** [prettier/prettier#4139] opened 2018-03-12 16:12 UTC
I'd like to formally request making the change to how jsx ternaries are presented optional. 

We thought it's a bug at first and after some browsing i found what looks like the cause: https://github.com/prettier/prettier/issues/2208

So this is a snapshot before

![screen shot 2018-03-12 at 16 10 44](https://user-images.githubusercontent.com/2223602/37291893-f7049f9a-260f-11e8-9998-f199fccbee01.png)

And that happens when prettier is through with it:

![screen shot 2018-03-12 at 16 10 51](https://user-images.githubusercontent.com/2223602/37291902-fa1c4084-260f-11e8-9bea-9c48d58dde2f.png)

It was easy to read and glance over before and that's how prettier handles all other non-jsx ternaries. I sincerely think that vim being unable to refactor it is too weak a reason. It's actually the first time i can think of that prettier has produced code that's harder to read and looks machine formatted.

For us this is a major change that came out of the blue, prettier auto-formatting was switched off because it would cause heavy changes for small commits, and on a personal note, it's the weirdest feeling to format by hand again. 😞

**Comment by lydell** [comment] 2018-03-12 17:16
- Most editors (not just Vim) has keyboard shortcuts for moving lines.
- There are more reasons listed here: https://prettier.io/docs/en/rationale.html#jsx
- Have you actually tried this for a while? To me, this looked really bad when I upgraded Prettier. Then I got used to it.


> For us this is a major change that came out of the blue

Yes it is a somewhat major change. That's why we do these detailed change logs: https://prettier.io/blog/2017/08/29/1.6.0.html#jsx

If you just upgrade a package _any_ change comes out of the blue, doesn't it?

**Comment by drcmda** [comment] 2018-03-12 17:24
I read through the reasons, and i fully understand that some people may want this, but i wouldn't be accepted in our codebase. We have only recently updated prettier and it would cause massive formatting now. Personally i think it also looks not so appealing and makes parsing the code harder. If i had the option, i'd switch it off for certain, for the sole reason alone that i don't want ternaries to look different just because jsx is involved. I also find the previous style quite elegant.

If it's possible, a small flag would go a long way in making this a win for everyone.

**Comment by Pyrolistical** [comment] 2018-05-02 19:29
This is the main blocker for me to use prettier.

The reason why I format ternaries likes this:
```
x
  ? a
  : b
```

is it makes it easier to read when it gets nested (which should be avoid in general first of all):
```
z
  ? x
    ? a
    : b
  : y
    ? c
    : d
```

compare the last example in https://github.com/prettier/prettier/issues/2208#issuecomment-312313051:
```
z ?
  x ?
    a
  :
    b
  : y ?
    c
  :
    d
```
i don't even know how to strawman it properly lol

**Comment by suchipi** [comment] 2018-05-02 19:39
I'm going to close this issue since the current formatting is the result of significant community demand and it would be a regression to change it at this point.

**Closed by suchipi** 2018-05-02 19:39 UTC
Labels: lang:jsx, type:option request
