### ISSUE TITLE
Prettier throws on MDX files with object attribute in tag

### ISSUE THREAD

**Issue by supersnager** [prettier/prettier#7731] opened 2020-03-09 08:42 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIDOMAngDZwC8wwAFnJgObUxIA6IAzAAwAOAHmwF8BAPhZRUAeizZhIADQgI3GJmj5koAIYAnbRADuABR0J1KTdgiZ08kACNtmsAGs4MAMrcnmKPWQxtAFc4BSYAWxIAdWpMeHwvMDh3U1icWKJkcHx1BR98OG0YQ0d6MM1kADNNEnyFACt8XgAhRxc3d00wuAAZHzhK6tqQBt53H3oyAEVAiHgBmpCQL2187Uyw9F5bbm0fGEjrGGpkAA5OBR2IfMjHbkyduFXsfoUARxn4YqUzEE18AFooHA4OgQbZtHB3pgIcVNKVykgqgsFPkwph-EFFvhxlMPv1EYNFjBNHYDugjsgAEwKAKaTAkcYAYQgYTKmSg0BeIEC+QAKiSzEihthggBJKCg2DuMC7ZQAQQl7mIZHm+SEQA)
```sh
--parser mdx
```

**Input:**
```mdx
<div style={{height:"30px"}}>
</div>
```

**Output:**
```mdx
SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (2:1)
  1 | <div style={{height:"30px"}}>
> 2 | </div>
    | ^
```

**Expected behavior:**
It should work :)

**Comment by thorn0** [comment] 2020-03-10 09:43
Duplicate of #6943

**Closed by thorn0** 2020-03-10 09:43 UTC

**Comment by thorn0** [comment] 2020-03-10 09:44
This has been fixed, but not yet released.

To use the fixed version, it's possible to install it directly from GitHub: `npm install prettier/prettier#next`

**Comment by supersnager** [comment] 2020-03-21 06:39
Thank you. Do you know when this fix will be in stable version?

**Comment by j-f1** [comment] 2020-03-21 23:38
It looks like this is part of v2, which is out now.
