### ISSUE TITLE
Template literals aren't moved to the next line when they obviously should

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#5269] opened 2018-10-15 10:31 UTC
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQBtoDmAMoSVMaZeWRdVbQzU-QHLoC2c2AvNgAb5yeQsKGCCoieMkyAzjEwBLcnwDcAHSgYc45nX2N6ewweM02nHtgDk0uyPtiHzofKXlrGqJu3YIV4EkzIxDTUJMIizgkfkcpF3inJMSJN2UCPmwAXx8sPwCg8OCwkojigiiY9RA4mVr6kTTyauyQABoQCAAHGEVoWWRQLEwIAHcABSwEAZR0VAhFABN2kAAjTHQwAGs4GABlLs305AUAVzgO5Vk4TBhxjYJ2dGQAM3Rca46AK1kADwAhDbbXZ7DhwIjKOCvd6fECHTDXTDINboVYAT0EKy67hgAHUljAABbIAAcAAYOtiINdcRsusjsXBEagoR1MHAAI6nRTs+7oR7PJBvD4XEDXdiKE6Yc4dWTpXBwACKpwg8GhIo6MFR+MWROQACZNRtFLh0gBhCDsJ7IqDQVkgU7XAAqqJmwuuWSyQA)
```sh
--parser babylon
```

**Input:**
```jsx
var longLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongName = `long long long long long long long long string`;
var longLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongName = 'long long long long long long long long string';

var o = { longLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongName: `long long long long long long long long string` }
var o = { longLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongName: "long long long long long long long long string" }
```

**Output:**
```jsx
var longLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongName = `long long long long long long long long string`;
var longLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongName =
  "long long long long long long long long string";

var o = {
  longLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongName: `long long long long long long long long string`
};
var o = {
  longLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongName:
    "long long long long long long long long string"
};

```

**Expected behavior:**

Template literal strings and usual strings should be formatted in the same manner.

**Comment by lydell** [comment] 2018-10-15 10:38
Duplicate of #2889

**Closed by lydell** 2018-10-15 10:38 UTC
