### ISSUE TITLE
can not format when code contains chinese function name.

### ISSUE THREAD

**Issue by yangyile1990** [prettier/prettier#16707] opened 2024-09-29 18:51 UTC
Before use prettier my code is this:
```
<template>
  <div
    class="welcome-message"
    v-on:click="go即刻跳转到网站首页"
    v-on:mouseenter="set设置显示版本号"
    v-on:mouseleave="set设置隐藏版本号"
  >
    欢迎来到首页
  </div>
</template>
```

while after use "format": "prettier --write src" my code is:
```
<template>
  <div
    class="welcome-message"
    v-on:click="go即刻跳转到网站首页;"
    v-on:mouseenter="set设置显示版本号;"
    v-on:mouseleave="set设置隐藏版本号;"
  >
    欢迎来到首页
  </div>
</template>
```

so it is wrong to add ";" at the end of the function name.
this make my produre can not work.
so please help me to fix it.

now my code is this and it can avoid this problem when use format:
```
<div
    class="welcome-message"
    v-on:click="() => Go即刻跳转到网站首页()"
    v-on:mouseenter="() => Set设置显示版本号()"
    v-on:mouseleave="() => Set设置隐藏版本号()"
>
```

**Comment by yangyile1990** [comment] 2024-09-29 18:57
I know it is better to program not use chinese. while as you see, my english is very not good. so I have to write chinese function name in my code. maybe I can use pinyin but it is not easy to read. so could you please help me to fix this problem.

even I set `"semi": false` while not work.
```
{
  "$schema": "https://json.schemastore.org/prettierrc",
  "semi": false,
  "tabWidth": 4,
  "singleQuote": true,
  "printWidth": 120,
  "bracketSameLine": false,
  "trailingComma": "all"
}
```

please help me. thank you.

**Comment by fisker** [comment] 2024-09-29 19:58
Duplicate of #13647

**Closed** 2024-09-29 19:58 UTC
Labels: type:duplicate

**Comment by yangyile1990** [comment] 2024-09-30 17:02
ok. thankyou.
