### ISSUE TITLE
Emoji anywhere in file messes up line comments when using flow parser

### ISSUE THREAD

**Issue by betaorbust** [prettier/prettier#5128] opened 2018-09-21 19:38 UTC
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8OYLyYDkgvBuBpO4QDpQD01mAEnAE5yYCGLmaEAtq5Dz6w0VWtgAWbLAHcAlgBt5mAOZwskRWwAOaOABNRdWVHaYWbRQE8uMJmyirM0tpYB07kABoQELTFnoyKAcTBDSAAocCGjIIGwAbhCyel4gAEZ2YADWagDKWmxgxsrItgCucN7Gukww4XbKPGzIAGYWut4AVmgAHgBCmTkwuWx8ADLGcK3tlSAFTDWxLfJhqVpMxjAA6skw4sgAHAAM3usQult2WrHrcDXxU94sAI5lsiz1bI3NSG3yHSBdDxZKUmBVvGhivI4ABFMoQeCg8EgGBsNI7PR7ZAAJm8tjYCmKAGFeE1YlBoI8QGVdAAVNExX4zAC+zKAA)
```sh
--parser flow
--single-quote
```

**Input:**
```jsx
const test = '💖'
// Here are some comments
// that will get collapsed
// in a really strange way...
```

**Output:**
```jsx
const test = '💖'; // Here are some comments // that will get collapsed // in a really strange way...

```

**Expected behavior:**
Line comments stay as line comments.

This behavior can be seen independent of where you put the emoji. Comment, node, etc.

**Comment by ikatyang** [comment] 2018-09-22 01:36
This looks like the same root cause as #2091, let's track the issue there.

**Comment by ikatyang** [comment] 2018-09-22 01:36
Duplicate of #2091

**Closed by ikatyang** 2018-09-22 01:36 UTC

**Comment by betaorbust** [comment] 2018-09-22 02:08
Perhaps #2091 should be renamed to indicate it’s not just from comments but from any emoji use.

**Comment by ikatyang** [comment] 2018-09-22 02:10
Renamed.
