### ISSUE TITLE
unique symbol should not become keyof symbol

### ISSUE THREAD

**Issue by ForbesLindesay** [prettier/prettier#4013] opened 2018-02-21 01:06 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAkigGcYiBXAS1QGUBPAWwCMJMkCKoqBHCwkk1aYA3CAA0ICAAcYVaCWSg8uCAHcACngSKU2AG4QaEkNjLIAZtkwk4k5rmxgA1nBi1pTqlADmyGLj8kqgQYJbWtpLetrgwGo4+jNjhNnYgAFYkAB4AQo4ubrTYjHAAMt5wKZFSFDDStQBMVWmeuDHIIDD00nAkYLhUsibSA7AA6jQwABbIABwADJIjELZjjtIdI71wuPqVkvh8VPjx2InJSFapkraMVP6BaSTePphwAIoUEPDNkjDYzAmqGmyAaf0cVEwLwAwhBGEkOlBoPsQBRbAAVAG6K62AC+uKAA)
```sh
--parser typescript
```

**Input:**
```tsx
declare const cuidSymbol: unique symbol;
```

**Output:**
```tsx
declare const cuidSymbol: keyof symbol;

```

**Expected behavior:**

```tsx
declare const cuidSymbol: unique symbol;
```

**Comment by ikatyang** [comment] 2018-02-21 01:27
Hi, this is a duplicate of #3577, and it's fixed in #3967.

---

**Prettier pr-3967**
[Playground link](https://deploy-preview-3967--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAkigGcYiBXAS1QGUBPAWwCMJMkCKoqBHCwkk1aYA3CAA0ICAAcYVaCWSg8uCAHcACngSKU2AG4QaEkNjLIAZtkwk4k5rmxgA1nBi1pTqlADmyGLj8kqgQYJbWtpLetrgwGo4+jNjhNnYgAFYkAB4AQo4ubrTYjHAAMt5wKZFSFDDStQBMVWmeuDHIIDD00nAkYLhUsibSA7AA6jQwABbIABwADJIjELZjjtIdI71wuPqVkvh8VPjx2InJSFapkraMVP6BaSTePphwAIoUEPDNkjDYzAmqGmyAaf0cVEwLwAwhBGEkOlBoPsQBRbAAVAG6K62AC+uKAA)
```sh
--parser typescript
```

**Input:**
```tsx
declare const cuidSymbol: unique symbol;
```

**Output:**
```tsx
declare const cuidSymbol: unique symbol;

```

**Closed by ikatyang** 2018-02-21 01:27 UTC
