### ISSUE TITLE
JSDoc comments not included by `proseWrap`

### ISSUE THREAD

**Issue by jajaperson** [prettier/prettier#5698] opened 2018-12-30 03:52 UTC
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AUQA8BDAWwAcAbOXAEQjAFdyF4ATXAMWajBgBLaDnyiCAQVwAzPgOF4YAC1IxcAJzgxm6qAGdcpXFFYAjOOtwcLggG5wu09RHK5ldQVErMYAGlymAJ5WEJ4A5rjkqkoGetrS0gB0uAAqSoIGGYa41NAR1npg6oKUQtC4ENLZsvxliipqHBBwelAA5GqapNTUwU2RzGBKieKoOHDElBDqajXy5RMUNHCMLGywDry1CgAUxACUuMCiGlo6eHsA1ABM+6gAzLgAtLgAjADcOAC+OCC+IBBSgo9MhQKR1M4AO4ABXBCBBKFItlCHD+IFM6lIYAA1loAMqULHhZAwdTMOD-JQwcjUADq6XgekJYDgePhgiEtg5gWQ4D0IP+nj0Fhg0MxYSiyGk3WF-wAVnpiAAhTE4-EUOAAGU8cClMopIAVxDx4VoAEVmBB4HrqLKQIT1ML1LzTKQgrkoGjKMVYLTBBxlMgABwABn+3ogwtpmMovO6kNIgQFIE0AEdmIJNGLSBLSDa7cLyIISWSDXpTXALVbdUhpbaDTA3X6A0pkNd-qTSIJqOEAMIuSUoFoAVjRzGFKTdCLrwq+XyAA)
```sh
# Options (if any):
--trailingComma="es5"
--prose-wrap
```

**Input:**
```js
/**
 * Example Documented Function
 *
 * A function that returns a number derived from the input, by doing maths stuff. This is a long description of a function that doesn't really do much.
 */
export function exampleDocumentedFunction(x) {
  return (x+2)/3 - 1;
}

```

**Output:**
```js
/**
 * Example Documented Function
 *
 * A function that returns a number derived from the input, by doing maths stuff. This is a long description of a function that doesn't really do much.
 */
export function exampleDocumentedFunction(x) {
  return (x + 2) / 3 - 1;
}

```

**Expected behavior:**
Wraps the function description according to the `--prose-wrap` option.

**Comment by j-f1** [comment] 2018-12-30 04:01
This is a duplicate of #5659 and #265.

**Closed** 2018-12-30 04:02 UTC
Labels: lang:javascript, type:duplicate
