### ISSUE TITLE
--use-tabs will sometimes replace tabs by spaces

### ISSUE THREAD

**Issue by thobas-dnvgl** [prettier/prettier#10202] opened 2021-02-01 11:42 UTC
I inherited from a codebase using tabs, but there is one file were one tab character gets turned to 2 spaces every time I run the latest version of prettier (and the previous ones too, so not a regression). ESLint is then complaining about spaces used for indentation.

This is a reduced test case: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAUQFtiBLQvYAHSmZkilJmwFcwYOABQBKJq3btSvDHGxCWbGJJgA3YoToATYoOxI8QgGZ04hLWIC8APnFKV7TtzzU45YgHM3eS3jqkAZQgwOg0aekJjADp1Ql44EQllZJUAfjsHFKyYAE9ZAwByOWwcAoAaJMzMznhYAyFKrKqYAB5SDGIoa3CGPGItLWw3Um8AdzoYAAs8Kbg8LQhaOig+obwoCHwNQghRuC0oloB6ds7rRub2EQr7JuSAXwusgyheQkIAbif7m5V7kS+SkeUGBIDKIAgGBgdGgpGQoGI2BKowACoiEHCUBpRsQcnDwQAjbDEMAAazgMACHRCUA8yB48XBcGoBP2Wn2ABlOh5eJ44AAxHC0GDQ2nIEDEXiCMEgSYwaiEADqkwmbmpcACGImdFUExy4rA5BlyxGuBRxI8tGQRg0I3BACtSGgAELEskUgLEVwc5Zwa22uAOp0BZYeQhwACKvE2fqQNsIdpAHWwpvFBOIrMIMow2GWMEV2imyAAHAAGcE5iAjRXEjDinNuOSqP3ggCO0fg5shmIlpAAtFA4Pt9jKhu26ENzZ4rXGA+CRtQ6PS+IGQKRQ+GozHl4yQDAMwWtEWkAAmcE8CKhgDCixnqFIAFYZbwRgAVDOYhmr1TxACSUHZWAAjAXMoQAQQAgJcnDf0Ezge57iAA

For the record this is the file, already well formatted:
```typescript
export class Email {
	constructor() {
		super({
			validator: (field) => {
				const messages = isSocialEmail(f.value)
					? {
							type: 'error',
							content: (
								<span>Email addresses with the domain are not allowed.</span>
							),
						}
					: null;
			},
		});
	}
}
```

If you run prettier with `--use-tabs` on it, the source shouldn't be changed and yet, the last tab chacrater on line 11 will turn to 2 spaces.

**Comment by thorn0** [comment] 2021-02-01 13:32
Duplicate of #5811

**Closed** 2021-02-01 13:32 UTC
Labels: type:duplicate
