### ISSUE TITLE
printWidth always break line if method chains >= 3

### ISSUE THREAD

**Issue by wvq** [prettier/prettier#7803] opened 2020-03-20 10:02 UTC
The printWidth option is not work, it's always break line.
**Input:**
```javascript
    a.b().c().d()
```

**Output:**
```javascript
    a.b()
      .c()
      .d()
```

**Expected behavior:**
```javascript
    a.b().c().d()
```

**Comment by thorn0** [comment] 2020-03-20 10:59
This is fixed by https://github.com/prettier/prettier/pull/6685 , but not yet released.

**Comment by thorn0** [comment] 2020-03-20 10:59
Duplicate of #3107

**Closed by thorn0** 2020-03-20 10:59 UTC
