### ISSUE TITLE
Markdown: Broken escape chars parsing

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier#4064] opened 2018-02-27 14:46 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBidqAEBZAggDQB1CB9AFQElsBRAeQFUzMSAKGASwFs4AnAZwC0cAB4wA9JwCGwgR24QArjACUJEABoQEAA4dofZKEk8eEAO4AFYwgMpJANwjsAJhpCS+MZADNJAGz44TQAjHkkwAGs4GABlbXD2KABzZBgeBSCQZwgwH39AzUTAnhgLMKSpPIDMgCs+YQAhMMjomMluABlEuCqCrSVtJQAmXsz4-l5kECkeCOyzKDdtHkSYAHUXGAALZAAOAAZNZYhAtbDtKeW4YvsezR44AEcFdgeyyQrJUc1AznZU9KZPiJJJ+OAARQUEHg3xAMEkwQ2zm2yCGmjSknYfhBAGEIJxKigoNA7iAFIEyAjbL5qgBfWlAA)
```sh
--parser markdown
```

**Input:**
```markdown
#### MAX\_TIMEOUT _(timers-ext/max-timeout)_
```

**Output:**
```markdown
#### MAX_TIMEOUT _(timers-ext/max-timeout)_
```

Interestingly, if we invoke second pass, then it gets further changed to:

```markdown
#### MAX*TIMEOUT *(timers-ext/max-timeout)\_
```

**Expected behavior:**

Output should remain unchanged:
```markdown
#### MAX\_TIMEOUT _(timers-ext/max-timeout)_
```

Or if asterisks are preferred it should be:
```markdown
#### MAX\_TIMEOUT *(timers-ext/max-timeout)*
```

Additionally second pass should not change outcome further

**Comment by ikatyang** [comment] 2018-02-27 16:54
Looks like there's already an issue to track it, closing as duplicate of #3837.

(FYI, the [first output is valid](http://spec.commonmark.org/dingus/?text=%23%23%23%23%20MAX%5C_TIMEOUT%20_(timers-ext%2Fmax-timeout)_%0A%0A%23%23%23%23%20MAX_TIMEOUT%20_(timers-ext%2Fmax-timeout)_), but [remark mis-parsed the second input](http://astexplorer.net/#/gist/e1a4ef53cdba7f50ff848a07cf3e6be6/17c4d388139faff3c4bcaae2f9b9a0e1b7b6e762).)

**Closed by ikatyang** 2018-02-27 16:54 UTC
Labels: lang:markdown, priority:high, scope:dependency, type:bug
