### ISSUE TITLE
(JSX)BracketSameLine not working properly since 2.3.0 in Typescript (Angular)

### ISSUE THREAD

**Issue by FilipMarkovski** [prettier/prettier#15844] opened 2023-12-25 10:34 UTC
Basically the working version is 2.2.1. As long as I don't update to newer versions, I won't have this issue.

So this issue is for Typescript projects (Angular in my case) from v2.3.0 onwards.

I have tried with jsxBracketSameLine in versions <v2.4.0, and with bracketSameLine >=v2.4.0 and it doesn't solve this issue.

I get that Prettier is an "opinionated code formatter", but then what is the purpose of "bracketSameLine" if it doesn't work?

**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgFkBPASQx3zgHVUYALAGWgHMA5XAWzgCkArgGcYAMQiZyQoQLgAlOAAcJMQsAA6UQoWwQIACgCUSQiMzo2AGk0BfTZrgAPZZlVgANrmmFxEQqm5FdzheWCESCio8AnomVihOHn5hMQkpGXklFTVNbV0DQxytbRLS7QB6csIAFQB5ABFak0w4GAFMLVxOsDbcd0IANz7ZQkYsOFyy7Ra2jsIAcjH3dwh5ydK7KBsQSxAIRRhUaCFkUFxMTAgAdwAFc4QTlD6r3FIT3YAjTHwAa1aAZSSzHQcGQMEwsk+3zAfxg-0U+AsYIhcF2QhCqGRkJATkUWACCBgfWqWCg51QcEeeHc6LRFmCAEUBBB4MhqbSQAArISOf70uBMlmgpDs1EgACOzPgN0uikeIC8AFooHA4AATdU7EDg3CodwWADCEG43FwyAVyy1Qn5AEEYODUB8BNKsMCVWy+hzGDBuO5aIwGJSEQR-g8GKgBgxSObUGwoBJQbsBrJKBrYP8wOYDjaoGr-jBSMEPTSxYpLujaN9FOay5SsANE2goOjXDLcGxTcWOQjMC3zQW8UJM6gDlqy+gYPQ1UxkAAOAAMuxaktQLTbHbNIs9YqJHynM6QACZdsI4NVcB8qdvdiEPuqNWrmF02AJ23BxJhTfakU9nRAQDYNhAA)

```sh
--parser typescript
--html-whitespace-sensitivity ignore
--bracket-same-line
```

**Input:**

```tsx
interface MyInterfaceWithLongNameJustForIssueReport {
  foo(): string,
}

export class Foo implements MyInterfaceWithLongNameJustForIssueReport {
  foo() {
            // TODO: return an actual value here
        return 'hello'
      }
}
```

**Output (this is how it is in my project):**

```tsx
interface MyInterfaceWithLongNameJustForIssueReport {
  foo(): string;
}

export class Foo implements MyInterfaceWithLongNameJustForIssueReport
{
  foo() {
    // TODO: return an actual value here
    return "hello";
  }
}

```

**Expected behavior:**

```tsx
interface MyInterfaceWithLongNameJustForIssueReport {
  foo(): string;
}

export class Foo implements MyInterfaceWithLongNameJustForIssueReport { // <---- opening bracket is on the same line
  foo() {
    // TODO: return an actual value here
    return "hello";
  }
}

**Comment by so1ve** [comment] 2023-12-26 14:34
https://github.com/prettier/prettier/issues/15219

**Comment by fisker** [comment] 2024-01-03 03:09
Duplicate of #15219

**Closed** 2024-01-03 03:09 UTC
Labels: type:duplicate
