### ISSUE TITLE
printWidth does not work for the class of the Vue file

### ISSUE THREAD

**Issue by LinsRock** [prettier/prettier#11880] opened 2021-11-30 02:49 UTC
Why printWidth does not work for the class of the Vue file?

**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG5mkUVj4DObAvMSHmDAFoARgFcYMaGQBOcfDHpwyAMxxwAHmRqY2AsAnhSyAKxFt5SgJ679cQwHcBSkThxl4awXti2yUCAJEoKlscGihFVTxaKABzAT9wsiE4yDofZPj-GSw4AjIwESk2CCkBLAgwg2UIArYkCDFQ8IEABh4SckoAelo6DtQuzFwCOA7SVDYwKRosGDJ8WO4QGDZ20hpsErngYKUwuABhCE3w2ABfZSljsgByOhE4G4BuJkZwtXKpOd28Z2+4PbhI4nfQACmApGIMCgeAwcCQtwAKnAzAAROAYCA3ZhvM4ASle4y6k2mszGUAmMAsqnmeEWPEmHB4ZEmEByVHJAzM1NGpBAABoQGz5NA2MhQHgpFc7AAFSUIMUoPA4Ox4CxiwVCKR8ADWcBgAGVYXAADL7ZBKZVsOCa7VgPWGrB8MIxZAwKQPQUYoRwKjBKgmukxER4GJwABiJQwBHksWQvDEEAFIAAFjAMDgAOoprQop16A0KrT0LQWeNgDjJsLWr4y7UxaMWq02kBGNhqA0u1QARREEHgTZw1sFTqKtnj9zgyaw01gmZoVBgKeQAA4VyOrtbM9qsPGZyjbGlkwBHPvwOtsxW8HThX2+5MyU80GR10ONpCWoct60YGhuj3fl2cC9v2U5IO6nrLHgQjzouy5IAATIK7p4DQTQxMC74gCiACsyamHAiLQYqn7DiAk4AJJBPoBpTDMMAAIJBAaVKqIO1pnGcQA)

**options:**
```json
{
  "arrowParens": "always",
  "bracketSameLine": false,
  "bracketSpacing": true,
  "embeddedLanguageFormatting": "auto",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxSingleQuote": false,
  "printWidth": 88,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false
}
```

**Input:**

```vue
<template>
  <div 
    class="act-button relative flex items-center justify-center w-full text-center no-underline leading-none bg-cover bg-no-repeat cursor-pointer focus:outline-0">
  </div>
</template>

<script lang="ts">
import {defineComponent} from 'vue';
  
export default defineComponent({
	name: 'TestDemo'    
})
  
</script>

<style lang="scss" scoped>

</style>

```

**Output:**

```vue
<template>
  <div
    class="act-button relative flex items-center justify-center w-full text-center no-underline leading-none bg-cover bg-no-repeat cursor-pointer focus:outline-0"
  ></div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'TestDemo',
});
</script>

<style lang="scss" scoped></style>
```

**Expected behavior:**

**Comment by fisker** [comment] 2021-11-30 04:52
Duplicate of #7863

**Closed** 2021-11-30 04:53 UTC
Labels: type:duplicate
