### ISSUE TITLE
Variable declaration: Nested destructuring breaks also the right side of the assignment

### ISSUE THREAD

**Issue by jsnajdr** [prettier/prettier#4674] opened 2018-06-12 11:06 UTC
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAExMEMnYBGAvpqQLyYAOAPjQI4DcAOlCADQgRUwCW6yULgBOwiAHcACiIRpkIXADcIvACYcQhYbjABrODADKVHbygBzZDGEBXOJzNo4wmJO3mAtrmQAzXABsnTgArNAAPACFtPQNDXA84ABkzOF8AoJATYSdheUJcQgBPf2gNKmEzGAB1NRgAC2QADgAGTnKIJyrtKnlyuBzFVM5hOHobXhG3XE9vJD9A+xAnD14rW0W0M3N-OABFGwh4NIXOGAKa1XrkACZT7V5-LYBhCA8veShoIZAbJwAVApyObpODEYhAA)

**Input:**
```jsx
const { a: { b } } = p || q;
```

**Output:**
```jsx
const {
  a: { b }
} =
  p || q;
```

**Expected behavior:**
```jsx
const {
  a: { b }
} = p || q;
```

The `ObjectPattern` is printed as a group with `shouldBreak` and that break propagates to all the parents. That causes a break also of the `line` token that's immediately after the `=` operator -- it's not protected with its own `group`.

If one doesn't use a binaryish expression as RHS, i.e., simple identifier (`p`) or function call (`fun(p, q)`), the RHS is on the same line as the `=` operator, as expected.

**Comment by duailibe** [comment] 2018-06-20 00:32
Duplicate of #4645

**Closed by duailibe** 2018-06-20 00:32 UTC
Labels: lang:javascript, type:bug
