### ISSUE TITLE
why doctype is removed

### ISSUE THREAD

**Issue by Jiang-Xuan** [prettier/prettier#13214] opened 2022-08-03 06:34 UTC
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEwmGBPABzgAIALGAWwBsA+Y4gHSlUwEsA3ersKgQwGd+AXgYgEMAE55RXYjSb1UpAIw1gwejFYwqJLgF99qAPQr5URW070eA4aIBGETNJDnZHruq5OXng-pMJlZ0wRw0IAA0IBAEWtD8yKC8EhIQAO4ACikIiSi8VOm8eInRDhK8YADWcDAAyrwUcAAyrFBwyABmBfxwZRXVtXUElW0A5siSAK59YhQOcJiYi828UGNTvGNwAGIQEhS8MFrryCC8UzAQUSDk1ADqpNpw-CNgcHW52hzaeGf8klYuBubV6EhgmQqY0OXR6swAVvwAB51ca6ACKUwg8FhVF60RGEjBZzGVFYFCaEhuBAkbRg91YmBgpGQAA4AAwEtK9e4VAhnGkvOASdgdaIARyx8EhsTy534AFp2otFjcJHBJax1ZCtjCkN08bNehRWJMJDNovw0XBMdiOvq4dEYLwHAymSykAAmJ0VVhk9YAYQgFN4ZxeAFYblNegAVF15A34kDsGYASSgy1gdTAtLiAEEM3V8LpcUnEUiAEIDGr1RotNr2xNwQxAA)

```sh
--parser glimmer
--html-whitespace-sensitivity strict
```

**Input:**

```hbs
<!doctype html>  
<div     class="entry"    >
  <h1>{{  title    }}</h1>
  <div   class="body">
            {{   body         }}
</div> </div>
```

**Output:**

```hbs
<div class="entry">
  <h1>{{title}}</h1>
  <div class="body">
    {{body}}
  </div>
</div>
```

**Expected behavior:**

```hbs
<!DOCTYPE html>
<div class="entry">
  <h1>{{title}}</h1>
  <div class="body">
    {{body}}
  </div>
</div>
```

**Comment by fisker** [comment] 2022-08-03 07:39
Duplicate of #11223

**Closed** 2022-08-03 07:39 UTC
