### ISSUE TITLE
JSX Tagged Template Literals

### ISSUE THREAD

**Issue by derek-duncan** [prettier/prettier#1325] opened 2017-04-18 16:21 UTC
Using a library like [zeit/styled-jsx](https://github.com/zeit/styled-jsx), tagged template literals in JSX have inconsistent formatting with prettier.

In:
![1__nvim_____python_](https://cloud.githubusercontent.com/assets/2983822/25141309/c9c23180-2428-11e7-88f4-237b49cbfb8f.png)

Out:
![1__nvim_____python_](https://cloud.githubusercontent.com/assets/2983822/25141323/d9c51ea8-2428-11e7-8059-270549743322.png)

Preferably, it could end up like this:
![1__nvim_____python_](https://cloud.githubusercontent.com/assets/2983822/25141403/123a7710-2429-11e7-84ba-b33f3318806b.png)

**Comment by kjbekkelund** [comment] 2017-04-18 17:31
Lots of talk about this topic in https://github.com/prettier/prettier/issues/1014

**Comment by bakkot** [comment] 2017-04-18 18:31
Can you link to a reproduction on https://prettier.github.io/prettier/ ? This looks like old behavior which has since been improved.

That said, your proposed formatting changes the content of the template literal itself, which is out of scope for prettier.

**Comment by vjeux** [comment] 2017-04-18 18:33
In prettier 1.0, both the first and last examples are left untouched :)

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%3E%5Cn%20%20%3Cstyle%20jsx%3E%7B%60%5Cn%5Ctdiv%20%7B%5Cn%20%20%20%20%20%20display%3A%20flex%3B%5Cn%20%20%20%20%7D%5Cn%20%20%60%7D%3C%2Fstyle%3E%5Cn%20%20%3Cstyle%20jsx%3E%5Cn%20%20%20%20%7B%60%5Cn%5Ct%20%20div%20%7B%5Cn%20%20%20%20%20%20%20%20display%3A%20flex%3B%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%60%7D%5Cn%20%20%3C%2Fstyle%3E%5Cn%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Closed by vjeux** 2017-04-18 18:33 UTC

**Comment by derek-duncan** [comment] 2017-04-18 18:58
@vjeux 💙 prettier. thanks for your hard work!
