### ISSUE TITLE
Unstable html-in-js format

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#7928] opened 2020-04-01 09:33 UTC
**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mAFAJSEB8mA9AFSYASAKgLIAymt1mABgDwBCALRDMAQ0wiqgkZgBGkoRR4BuADpQxxOo1YcuvGaIlTMR+YuWkVIADQgIABxgBLdMlBiATl4gB3AAVvBDRkEDEAGz8xAE9Q+zkvMTAAazgYAGVHZJcoAHNkGC8AVzh7AAsYAFsIgHVyl3g0bLA4DJDGlwA3RpiwsDR4kFy0OC8YAKS8qrFkbEjR+wArNAAPACEk1PSMsSq4Nly4OYWykBXVjNy8iLgARWKIeBOIxZBsr1GvMLkxOTgInZ3l5cjBai4ACYwcrIAAcAAZ7I5fKNaklHGFkXAvl1jvYAI6PeCTJyhFBiNBCKBwOAQ2lArxwQkuRmTMTTWZIeavM6jKouQolXnXW4PJ7HLmnewwP7gqEwpAAJmlSRcEWuAGEIFUZmFsQBWIHFUZMP5k7lvLqlACSUDpsAyYBBzgAgnaMjAYrcXqMAL6+oA)
```sh
--parser babel
```

**Input:**
```jsx
const foo = () => /* HTML */ `<!-- a --> <!-- b -->`;
a(/* HTML */ `<!-- a --> <!-- b -->`);
```

**Output:**
```jsx
const foo = () =>
  /* HTML */ `<!-- a -->
    <!-- b -->`;
a(
  /* HTML */ `<!-- a -->
    <!-- b -->`
);

```

**Second Output:**
```jsx
const foo = () => /* HTML */ `<!-- a -->
  <!-- b -->`;
a(/* HTML */ `<!-- a -->
  <!-- b -->`);

```

**Expected behavior:**

Stable output.

----

I found this when trying to fix [this file](https://github.com/prettier/prettier/blob/70da4fa630bbe21e1e7baa21984dd050cf1b3934/tests_config/run_spec.js#L41) second format, and have located the problem, here

https://github.com/prettier/prettier/blob/70da4fa630bbe21e1e7baa21984dd050cf1b3934/src/language-js/printer-estree.js#L1177-L1181 and https://github.com/prettier/prettier/blob/70da4fa630bbe21e1e7baa21984dd050cf1b3934/src/language-js/printer-estree.js#L875 , we detect if the `TemplateLiteral` is inline, but this `TemplateLiteral` will format by another parser, hard to know if it will break, seems we even can't know if it will parse by another parser. I was not able to fix it.

**Comment by thorn0** [comment] 2020-04-01 10:22
duplicate of https://github.com/prettier/prettier/issues/6150 ?

**Comment by evilebottnawi** [comment] 2020-04-01 10:29
@thorn0 I think it, let's put it example in #6150 issue

**Comment by thorn0** [comment] 2020-04-01 10:39
Duplicate of #6150

**Closed by thorn0** 2020-04-01 10:39 UTC
Labels: area:idempotency, lang:javascript, type:bug
