### ISSUE TITLE
Abbreviation-Definition gets reformatted (unwanted)

### ISSUE THREAD

**Issue by Barry1** [prettier/prettier#13181] opened 2022-07-27 11:12 UTC
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAWQJZWwWwFd90B3CAJwGtcBzdOADwEN8AHAGzgB0peAVABbYAzulHpm6eIxhlsMQegCCAIVUAlAGoA6XrwBUAbTWatAXSQqoDFuy4qARo4pwAbtmYxs0EABoQCDZvaBFkUGYKCghSAAVIhDCUZg5SZgBPMICXZjAqOBgAZVY4ABlcOGQAMxSROGyKXPyitly6ZBgKQnqQOHxHOAATQaHS5ihaQmZaOAAxSnwvbwnkEGZCGAh-EEEYfA4AdWF4EVawOELEhWwPGHTVsBEskFw6ihhYxtpF6tqegCsRIxCnQuABFQgQeC-Dh1AKtChvVaLaiDGJQbZsCi4GAHbCDRTIAAcAAZ4dE6gdGmxVli4G83JUAgBHSHwT5BJJrEQAWigcCGQ22rlZ2Fcn2mPyQNVhPTq+GwHS6ctBcAhUMq0r+ARgzEceIJgmQACYdY1sBw6ABhCD4KW9EQAVm2hDq-D1SRlcJAbm6AEkoCNYIUwNjgspA4U7lwYXUAL5xoA)

```sh
--parser markdown
```

**Input:**

```markdown
# Minimum working example

This is a text with ABBRV.

*[ABBRV]: An example Abbreviation
```

**Output:**

```markdown
# Minimum working example

This is a text with ABBRV.

\*[ABBRV]: An example Abbreviation

```

**Expected behavior:**
**Input=Output:**

```markdown
# Minimum working example

**Comment by thorn0** [comment] 2022-07-29 08:59
Duplicate of #5686

**Closed** 2022-07-29 08:59 UTC

**Comment by Barry1** [comment] 2022-07-29 18:26
> Duplicate of #5686

Sorry for sending a double - haven't found before.
