### ISSUE TITLE
 error  Delete `·`  prettier/prettier

### ISSUE THREAD

**Issue by jedrekdomanski** [prettier/prettier#6328] opened 2019-07-24 00:07 UTC
I've just installed a fresh nuxt.js app with prettier and eslint and added a new plugin to extend axios. Inside `plugins/axios.js`

```
export default function ({ $axios, redirect }) {
  $axios.onRequest((config) => {
    // console.log('Making request to ' + config.url)
  })
}

```
I am getting this error.
![image](https://user-images.githubusercontent.com/5911945/61755405-a62b8080-adb7-11e9-9c97-fc45a5e30c0d.png)

This is very bad.

**Comment by evilebottnawi** [comment] 2019-07-24 10:22
Please use issue template, i can't reproduce this (https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9jyowYBLaPACmDwBJS1mBnADR5scAoxEM8AXwCUeYAB0oeLj34A6aACU4AR3Jw+MVq0hRijAOZyAvAD55SlSoD0LvGb4RKcdZQiWrADkALKkANaMUJbCegZGeDAQeEF4ANQe0BaW6uTYlDJO0oVQUkogAiAQGEzQfMigpNjYEADuAApNCPUopABuEIwEFSAARtikYOFwMADKGJNRlsgw2AaVABYwALaUAOobjPB8C2Bws91HjH1HAJ7I4Hz1lVF8cLjtE5bbpMhklG9KgArPhoABCEymM1mpG2cAAMlE4H9SAC4MDQbMlj4AIrkCDwFFoyoLbBvbAPUakUZwSgjDDYKIwPZDGAbZAADgADCSWm89hMMA8GYZ3n1kZV9AS4J9qj0QKQ+ABaKBwUSiEYifTiGVfH5EwEgN7bRgrNboo3YuB46UGi0waksghs5AAJkqq1IjEoSwAwhBtvqUFBoBKQOQ3gAVak9f5vKRSIA),

Also `This is very bad.` is not helpful message to search problem, i am closing issue.

**Closed by evilebottnawi** 2019-07-24 10:22 UTC
