### ISSUE TITLE
Formatting intersection type of TypeScript

### ISSUE THREAD

**Issue by xiaoxiangmoe** [prettier/prettier#6449] opened 2019-09-04 02:57 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdWBPADnABFgGwFcBnAMSKjBgEtpcBedXXAMlwAoOBDAJwHMAjElxQiAWwBGcXgBpcffgCYRYqTICUjAHyiJ03huZtOPAcNwkYvGlH7zFKy9dv8tDXVZt2NAbnToMNh4hKQUVLTQSozGAD6mihZqBg4CTsmaOnrqhnEJ5iJerqnKhS4+WUU+-lAgsiAQWJFQJMigfLwQAO4ACnwIrSjcAG4QNAAmdSCSvNxgANZwMADKWHOuyNZEcPUAFjDiBADquzTwJGtgcMsDZzTDZxjI4CSt9bYkMjA9s-zi3MgAGbcAifeoAKxIAA8AEKzBZLZbccRwAAytjgQJBYJAkKhy1cBDgAEUiBB4FjQTsQGteJ9eM9JNxJBgCNAplhvDAjhMYLtkAAOAAM9U5EE+R1mWGenLg9OGmPqAEcyfAfo1BiBuCQALRQOBwcaGqa8OAqmimn7cP4ApDAqn1T7iGibXjbR2EkmqzF27HUmDMnnjPnIJT1azcGgEVwAYQg4n+zyg0EVIFIcAAKszBvbPgBfPNAA)
```sh
# Options (if any):
--single-quote
```

**Input:**
```ts
type plusFunction =
  & ((arg1: number, arg2: number) => number)
  & ((arg1: string, arg2: string) => string);

type plusFunction2 =
  | ((arg1: number, arg2: number) => number)
  | ((arg1: string, arg2: string) => string);
```

**Output:**
```ts
type plusFunction = ((arg1: number, arg2: number) => number) &
  ((arg1: string, arg2: string) => string);

type plusFunction2 =
  | ((arg1: number, arg2: number) => number)
  | ((arg1: string, arg2: string) => string);
```

**Expected behavior:**

```ts
type plusFunction =
  & ((arg1: number, arg2: number) => number)
  & ((arg1: string, arg2: string) => string);

type plusFunction2 =
  | ((arg1: number, arg2: number) => number)
  | ((arg1: string, arg2: string) => string);
```

**Comment by lydell** [comment] 2019-09-04 05:17
Duplicate of #3986

**Closed by lydell** 2019-09-04 05:17 UTC
