### ISSUE TITLE
Sass @forward configuration not formatting

### ISSUE THREAD

**Issue by wegry** [prettier/prettier#8001] opened 2020-04-09 14:58 UTC
**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZhATgdwIZYAmABAOQBGEEMAzjFngA4D0NYNNzl1dDjpxHAEsYAC2IAKADpQAJJSJwsAWgaEhAVxpJiABgA0M4sXnZCS1XnVblAGwDmOg0eMmF5lWs01lNALZOhlAAlADcIPogEIwwQtA0yKAEWBA4AAoECAkoeLb4AJ4JkeQMYADWcDAAyox4YEJQ9sj0GnCRojB+tgDqoiJwNLVgcFVZIkIAbiL5yOAcESANNEowaQz2fnjI6LnLkQBWNAAeAEKlFdV4fnAAMg1w27ttIIdHVQ32tnAAihrUD0gdrY9iBalhllhZmx5pFGFgGjBukJCGJkAAOAyglLLbp8WZwgZKCYPSIARz+8DW0WyIDwPigcDg5kICywcHJQjZazwGy2gKekWWfiEzSwrUFHy+v3+j2BzxgeHISJRomQACZIvQ8EJbB8AMIQPybWYDACsCy0cAAKorskCQRNWgBJKDmWBVMDwmIAQVdVRg+S+suWAF8Q0A)
```sh
--parser scss
```

**Input:**
```scss
@forward 'bootstrap/scss/bootstrap' with (
$border-radius: 0,
  $border-radius-lg: 0,
    $border-radius-sm: 0,
);
```

**Output:**
```scss
@forward 'bootstrap/scss/bootstrap' with (
$border-radius: 0,
  $border-radius-lg: 0,
    $border-radius-sm: 0,
);

```

**Expected behavior:**

Dart Sass added modules in 1.23, and we've been working them into our project recently. We would expect these to format like maps, even though they're not really maps.

**Comment by evilebottnawi** [comment] 2020-04-09 15:00
Please use search before post an issue, duplicate of #7019

**Comment by wegry** [comment] 2020-04-09 15:01
My apologies. That is much more thorough.

**Closed by evilebottnawi** 2020-04-09 15:00 UTC
