### ISSUE TITLE
Long string with interpolation wraps strangely

### ISSUE THREAD

**Issue by vjpr** [prettier/prettier#2725] opened 2017-08-31 21:14 UTC
v: 1.6.1

Before:

```js
const polyfill = `https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.${this.props.locale}`
```

After:

```js
const polyfill = `https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.${this
  .props.locale}`
```

---

I'm not sure what would be best...but maybe if we kept the whole identifier together like so:

```js
const polyfill = `https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.${
  this.props.locale}`
```

or

```js
const polyfill = `https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.${
  this.props.locale
}`
```

or just leave it...

```js
const polyfill = `https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.${this.props.locale}`
```

**Comment by azz** [comment] 2017-08-31 23:21
Thanks for the report, this is a known issue, closing as duplicate of #1893

**Closed** 2017-08-31 23:21 UTC
