### ISSUE TITLE
Unquoted HTML attribute with trailing slash causes parser error

### ISSUE THREAD

**Issue by meyer** [prettier/prettier#8501] opened 2020-06-05 01:57 UTC
Attempting to parse this string:

```html
<a href=/hello>link text</a>
```

results in a parser error:

```
SyntaxError: Unexpected closing tag "a". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:22)
```

[Here’s a link to an example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhgAgBYCc4BmAvAPTZwA2FEAfAO4R2ono0gA0IEADjAJbQAzslDpcuRgAUxCYSnQU66AJ7DOAI1zowAazgwAyt218oAc2QxcAVzidsMALYUA6tj7xBxsHAOyPfABuHsrI4IJqIKaCcLgwklpmjujIBAoxnABWggAeAEJauvoG6I5wADKmcKnpdiDZOQamZhRwAIrWEPA1FBkgxrgxuGEOzhz9uKYwLnwAJjDYyAAcAAyc3BIxLlrcYRtwQ4HVnACOnfAJPHIg6IIAtFBwcLPP4-hnfPgJ6EkpSGm9OoxRx8Sw2IHNVodLrVf61TgwdDqGbzRZIABMCK0fAozQAwhBHMkwgcAKzjawxAAqSLkAL6gVsAEkoC9YAYwJNeABBVkGGDKVo9GIAXxFQA).

Removing the initial slash makes the error go away.

Every HTML parser I used with this string—parse5, htmlparser2, even the Svelte parser!—all handled the unquoted attribute just fine, but angular-html-parser does not.

Unquoted attributes are allowed in HTML and render just fine. I suspect that they’re not allowed in Angular code, though, which means that it’s probably not something that would be fixed in angular-html-parser directly.

The only solution that I can think of here (very much off the top of my head) would be to use a dedicated fault-tolerant and spec-compliant HTML parser for HTML, and use `angular-html-parser` only for Angular-specific HTML.

**Comment by thorn0** [comment] 2020-06-05 07:00
Hi. This is a known issue. Hopefully, Angular will fix it soon.

**Comment by thorn0** [comment] 2020-06-05 07:00
Duplicate of #8210

**Closed by thorn0** 2020-06-05 07:00 UTC
