### ISSUE TITLE
[Markdown] $ is escaped as \$ if encountered once

### ISSUE THREAD

**Issue by Pavek** [prettier/prettier#6213] opened 2019-06-11 15:12 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAFAhgcywJ3QBwAsACAdwEsYSASARgBZiBbcgG1fOgDoAdKPjNkx4iZSjQbM2HbsQBCAVxjFyAM2YQccYtQAmEduhwBnYtGJVtx9E20cocLk5AAaEBHwxOUY8lBGcCFIMLR9kEHQANwhyXVcQACM8MABrOBgAZXx0MHIoTGQYHAU4N0IYJlYAdUJKOGNssDgMhGNKckjKAE9wsGNfNzzjOBwYVDxMJnRkVXRWYbcAK2MADzlktMybOAAZPLgZuYWQZZWMvMxWOABFBQh4Q-nSkGyTEfCpnBT9Uih4-BweRgVViVGQtAADBC3ACIMMqiJwnNSOgugMQABHO7wcYeXwodDGAC0DjgujJ8S0WPIWnGWCmj2OwxYhWKzza+Sut3uByQsyebiK6DYFwAwhAmAyUFBoAc3AphgAVdAJfH84YAXw1QA)
```sh
--parser markdown
--print-width 100
--prose-wrap always
```

**Input:**
```markdown
Pagagraph with $14 million.

Pagagraph with $14 million. But if more $dollars on the same line...
```

**Output:**
```markdown
Pagagraph with \$14 million.

Pagagraph with $14 million. But if more $dollars on the same line...

```

**Expected behavior:**

No escaping of dollar sign is expected:

```markdown
Pagagraph with $14 million.

Pagagraph with $14 million. But if more $dollars on the same line...
```

**Comment by lydell** [comment] 2019-06-11 17:14
https://github.com/prettier/prettier/issues/5425#issuecomment-437383807

> Since we now support math syntax (`$ inline_math $`), we need to escape `$` to avoid unexpected parsing.

But it does seem a bit excessive to me. Maybe we can do this better.

**Comment by barlock** [comment] 2019-07-08 18:23
Uncertain if this is related or a new issue. `remark` [escapes](https://github.com/remarkjs/remark/blob/d4a8121b0d2f7c07fee49b1201cbe593d9e9cd47/packages/remark-stringify/lib/escape.js#L261) with `\\` and prettier seems to only recognize one `\`. Running `remark` and prettier back to back causes `\` to grow indefinitely.

**Comment by millette** [comment] 2019-08-19 20:37
If we know we're not using math syntax, can this behavior be disabled?

**Comment by felixfbecker** [comment] 2019-12-04 22:09
This is bad when the markdown target (e.g. static site generator) doesn't support math syntax so will render literal `\$` into the HTML.

**Comment by jescalan** [comment] 2020-04-02 16:20
I am also getting a blackslash rendered into the html output, which as far as I see it is a major bug in prettier's markdown formatting. I would be happy to put in a PR to help fix/remove this given some sort of direction or signoff from a maintainer. @ikatyang - any thoughts here?

**Comment by ikatyang** [comment] 2020-04-03 05:23
@jescalan

> I am also getting a blackslash rendered into the html output, which as far as I see it is a major bug in prettier's markdown formatting.

The behavior you mentioned sounds like a bug, but [the escaped dollar sign should not be rendered into the html output according to the CommonMark spec](https://spec.commonmark.org/0.29/#backslash-escapes). Since this issue (#6213) is about code style while yours sounds like a formatting bug, could you open a new issue with steps to reproduce?

**Comment by Pavek** [comment] 2020-04-04 10:06
@ikatyang I'm not sure what do you mean by "this issue is about code style "?

This issue is exactly about formatting: if author writes `$14 million` in Markdown, then end user sees `\$14 million` in HTML.

**Comment by ikatyang** [comment] 2020-04-04 10:16
@Pavek

> This issue is exactly about formatting: if author writes `$14 million` in Markdown, then end user sees `\$14 million` in HTML.

It looks like the Markdown renderer you used is not [spec-compliant](https://spec.commonmark.org/0.29/#backslash-escapes), I'm not sure what should we do in this case.

**Comment by lydell** [comment] 2020-04-04 10:34
Maybe we can avoid printing a `\` before `$` if the `$` occurs in a situation where it is impossible or low risk it will be interpreted as inline math?

But we don’t want to end up in a situtation where this edit:

```diff
-A gift of $14 million
+A gift of $14 million from John and $20 million from Jane
```

... suddenly results in accidental inline math that could have been avoided if Prettier had printed `\$14` in the first place. I don’t know the rules for inline math, though.

**Comment by Pavek** [comment] 2020-04-04 15:06
@ikatyang 
> It looks like the Markdown renderer you used is not spec-compliant, I'm not sure what should we do in this case.

True, To be precise this is [bug in Marked prior to version 0.4.0](https://marked.js.org/demo/?text=Marked%20-%20Markdown%20Parser%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0A%5C%2412%20million&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.3.19). My plan for this issue is to upgrade renderer.

But I argue that his behavior violates Prettier correctness rule:
> The first requirement of Prettier is to output **valid code** that has the **exact same behavior as before formatting**. Please report any code where Prettier fails to follow these correctness rules — that's a bug which needs to be fixed!

In this case Prettier indeed outputs a valid code (both `$1` and `\$1` are valid according to spec), but behavior (end user experience) is **not the same**. Due to 3rd-party bug of course, but anyway.

**Comment by ikatyang** [comment] 2020-04-05 15:19
> I don’t know the rules for inline math, though.

I don't know either. That's the trickiest part, there is no formal definition for the math syntax in markdown. As far as I can tell, its definition is simply _"content between dollar signs"_, the rest detail is up to implementers, which we followed the rules from `remark-math` at the moment.

But it seems [`remark-math` has switched](https://github.com/remarkjs/remark-math/pull/35) to use [rules from pandoc](https://pandoc.org/MANUAL.html#math) last year:

> Anything between two `$` characters will be treated as TeX math. The opening `$` must have a non-space character immediately to its right, while the closing `$` must have a non-space character immediately to its left, and must not be followed immediately by a digit. Thus, `$20,000 and $30,000` won’t parse as math. If for some reason you need to enclose text in literal `$` characters, backslash-escape them and they won’t be treated as math delimiters.

Given that this new rule won't be that easy to be triggered, we should be able to avoid those unnecessary backslashes if we apply the same rule here.

**Comment by kristojorg** [comment] 2020-04-07 22:07
I am also seeing prettier escape `"*"` to `"\*". Is this related?

**Comment by fisker** [comment] 2020-04-07 22:46
I think this is getting worse  when updating remark-math `$10 - $20` also escaped(not escaped before)
https://github.com/prettier/prettier/pull/7938/files , let's try remove the escape, and handle broken math syntax later.

**Comment by leerob** [comment] 2020-04-12 15:18
I'm seeing this as well. Are there any workarounds for the time being? I don't want to disable the entire file (MDX in my case).

**Comment by leon-do** [comment] 2020-04-30 03:32
any workarounds?

**Comment by samjulien** [comment] 2020-05-21 00:35
I'm having this same issue using MDX in Gatsby.

**Comment by minimaldesign** [comment] 2020-06-20 23:51
> I am also seeing prettier escape `"*"` to `"\*"`. Is this related?

I'm also seeing this in a markdown file where I'm trying to bold some stuff… I can't imagine I'm the only one? 🤔  Not sure if I should open another issue or…? I there's an open issue or solution out there, can you point me in the right direction? I haven't found it.

**Comment by lydell** [comment] 2020-06-21 18:14
@minimaldesign Does `\*` cause any issues for you? If so, what markdown tooling are you using?

**Comment by minimaldesign** [comment] 2020-06-21 20:27
> @minimaldesign Does `\*` cause any issues for you? If so, what markdown tooling are you using?

Well, the first issue is that it's not standard markdown format, so it creates potential compatibility issues down the line.
Second issue: I'm putting together a blog using 11ty… If I try to make something `**bold**` it's rendered just like that (with the `**...***` instead of bold.
Lastly, I don't want to get a bunch of unnecessary unrelated diffs when I update some old blog posts…

Thanks!

**Comment by lydell** [comment] 2020-06-22 07:04
@minimaldesign What do you mean it’s not standard markdown? It’s supported in the original markdown implementation (https://daringfireball.net/projects/markdown/dingus) and in the CommonMark Spec: https://spec.commonmark.org/0.29/#backslash-escapes

**Comment by minimaldesign** [comment] 2020-06-23 02:34
I mean it in the dictionary sense: normal, usual, typical, common, ordinary, customary, conventional, etc.

John Gruber:

> The overriding design goal for Markdown’s formatting syntax is to make it as readable as possible. The idea is that a Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions.

I don't think it's right to add unnecessary `\` all  over the place.

Maybe it's only important to me? But as I also mentioned initially, there are also tech ramifications like broken output and misleading diffs.

Thanks!

**Comment by lydell** [comment] 2020-06-23 06:02
I personally like `\*` – makes it ultra clear that it was intended to be a star, and isn’t broken emphasis.

> there are also tech ramifications like broken output

Where?

**Comment by minimaldesign** [comment] 2020-06-23 16:38
> I personally like `\*` – makes it ultra clear that it was intended to be a star, and isn’t broken emphasis.

Hmm, maybe I wasn't clear enough. I write:

```
Some **bold** text
```

And Prettier changes it to:

```
Some **bold\*\* text
```

I had to turn off Prettier on that page…

**Comment by thorn0** [comment] 2020-06-23 16:50
@minimaldesign If Prettier indeed breaks your code, please open a new issue with a proper bug report. To do that, reproduce the problem on [Prettier's Playground](https://prettier.io/playground) and click the <kbd>Report issue</kbd> button there.

**Comment by josephmarkus** [comment] 2020-07-02 13:07
Is there a way to disable syntax interpolation through config?

These are the only workaround I found:
- add prettier-ignore where dollar sign is used
- disable prettier for a particular Markdown file
- disable prettier for all Markdown files

None of which are ideal.

**Comment by flikteoh** [comment] 2020-07-14 05:16
Hi,

Has there been any concluded outcome of this issue?

Would definitely agree with options to disable math syntax through Prettier.

We're getting plenty of \$ in mdx while we still wish to be using Prettier on our files.

**Comment by muescha** [comment] 2020-07-14 13:26
is the `math` only disabled if there are more supporters? - here is my one:

+1

**Comment by josephmarkus** [comment] 2020-07-14 13:48
+1 @muescha

**Closed** 2020-11-15 17:03 UTC
Labels: lang:markdown, type:bug

**Comment by jescalan** [comment] 2020-11-16 00:22
🙏🏼 thank you so much for getting this fixed!
