### ISSUE TITLE
[RFC] Configuration for whitespace following `!`

### ISSUE THREAD

**Issue by GrahamCampbell** [prettier/prettier#3450] opened 2017-12-10 16:35 UTC
How do people feel about adding configuration to control if `!foo` was kept as is, or fixed to `! foo`?

For example:

```js
if (!greeting) {
  //
}
```

being fixed to:

```js
if (! greeting) {
  //
}
```

I'm asking to see if such a PR already existed, or if there is a demand for it, so that one could be created, by myself, or someone else.

**Comment by duailibe** [comment] 2017-12-10 17:29
I don't think I've seen this style at all. Why do you need this kind of formatting? Is it common?

**Comment by hawkrives** [comment] 2017-12-10 17:34
I've seen this in a fair amount of PHP code but not in any JavaScript, myself.

**Comment by lydell** [comment] 2017-12-10 17:54
Regardless of the popularity, we have to close this for the same reasons as #1139.

**Closed by lydell** 2017-12-10 17:54 UTC

**Comment by GrahamCampbell** [comment] 2017-12-10 17:56
That's a shame. For a tool like this to actually gain traction, it'll need to embrace configuration, otherwise there will just be 100 other tools with people that are pissed at this. This is why PHP-CS-Fixer is leading the way for PHP.

**Comment by duailibe** [comment] 2017-12-10 18:30
@GrahamCampbell I'm sorry but we don't actually believe we should have too many options. The point of Prettier is have a tool to format your code so you don't have to worry about that anymore. So ideally we wouldn't have any options and we'd always print the code the same.

But the community is already very used to styling in a code in some many different ways so we included options only to allow large number of people to use Prettier who wouldn't otherwise. I'm afraid this option doesn't fall into this bucket.

**Comment by lydell** [comment] 2017-12-10 18:53
We should write down our option philosophy in the docs, and perhaps even link to it in the issue template.

**Comment by duailibe** [comment] 2017-12-10 19:00
I'll send a PR

**Comment by GrahamCampbell** [comment] 2017-12-10 19:12
OK, makes sense. I think it will take a long time before the community will be aligned on standards. :/

**Comment by JosephSilber** [comment] 2017-12-10 19:21
@lydell unlike the parenthesis issue, which is just a style preference (I like the space, but it doesn't really matter. Can live without it), the space after the `!` is an important visual one.

Without a space, the `!` can easily be missed. This is the main thing that has been bothering me since we started using prettier: reading code became more difficult. We find that many times when reading code, your eyes simply gloss over the `!`, not realizing that the condition is being negated.

So while I agree that Prettier should avoid bike-shedding and not introduce merely-cosmetic options, I believe this is a more important one to consider.

**Comment by lydell** [comment] 2017-12-10 20:14
@JosephSilber I understand. However, in this case it could just as easily be argued that the space makes it less clear what is negated.

```js
if (! enabled && loggedIn) {
}
```

Oh well. Let’s not start a long debate here now.

If you look through the issue tracker, adding an option for this would open the flood gates for a bunch of other options to be added. More options means:

- More maintenance (less time working on bugs and all other things that need to be done).
- More combinations that could go wrong.
- More decisions to make for users.

Prettier does three things:

- Helps you write code in your editor, through editor integrations.
- Enforces a common code style in projects.
- Avoids arguing about what code style to use.

The last point is really important. Instead of endless debates, teams can simply decide to use Prettier. But if there’s tons of options, the problem is just moved. Then people would argue about which Prettier options to use. From that point of view, more options is worse. Some of the options in Prettier are there for historical reasons; if Prettier had been born today I’m sure it would have had a few less options.
