### ISSUE TITLE
Convert prop={"xxx"} to prop="xxx"

### ISSUE THREAD

**Issue by fabb** [prettier/prettier#10559] opened 2021-03-17 08:04 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT77VwzrWcAPHRwA3fAAdqECQF52IUQEMS6OGxABffAHoAfB00gANCBm5oAZ2Sgl1aQHcACnYTWUKh0oCe10wCNqJTAAa14AZQlgnCgAc2QYajVTOABbfzg6OkyAGSU49CVYuAAxGlSlGFw45BAldBgIExAACxhUkgoWnHhLKLA4cLcesR7vWrBLPxAYyzhqGCcg2IrkVBU50wArSwAPACEg0IilVLgcmLg1jbhtvfCY2JI4AEV0CHhrkk2QKOo56i1fxKDIkZpSGIwCg4OgwFrIACMACYAAymKQQOYUIISWpSOAA0RXUwAR3e8CWMncdUsAFooHBMplmjwyTgeEsiqskOtvrcQHNUjgvj9LI9nm8PlckIlkiAYCDobD4UgACymRJKHAkR4AYQgqW5IAJAFZmug5gAVEHuXk-URqACSUGysHCYGoOAkMAAgi7wjBvM8RXBNJogA)

```sh
--parser babel
--print-width 120
--tab-width 4
--no-semi
--single-quote
```

**Input:**

```jsx
function HelloWorld() {
  return <div prop={"value"} />
}
```

**Output:**

```jsx
function HelloWorld() {
    return <div prop={'value'} />
}

```

**Expected behavior:**

This would be semantically equivalent and nicer to read:

```jsx
function HelloWorld() {
  return <div prop="value" />
}
```

**Comment by thorn0** [comment] 2021-03-17 13:06
Duplicate of #3303

**Closed** 2021-03-17 13:07 UTC
Labels: type:duplicate
