### ISSUE TITLE
Inconsistency breaking assignments

### ISSUE THREAD

**Issue by bakkot** [prettier/prettier#2482] opened 2017-07-14 20:46 UTC
For example,

```js
aParticularlyLongAndObnoxiousNameForIllustrativePurposes = 
  anotherVeryLongNameForIllustrativePurposes;
```

[formats as](https://prettier.io/playground/#%7B%22content%22%3A%22aParticularlyLongAndObnoxiousNameForIllustrativePurposes%20%3D%20%5Cn%20%20anotherVeryLongNameForIllustrativePurposes%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

```js
aParticularlyLongAndObnoxiousNameForIllustrativePurposes = anotherVeryLongNameForIllustrativePurposes;
```

Similarly there is no break after the `=` in

```js
aParticularlyLongAndObnoxiousNameForIllustrativePurposes =
  'a very long string for illustrative purposes'.length;
```
or
```js
aParticularlyLongAndObnoxiousNameForIllustrativePurposes =
  anotherVeryLongNameForIllustrativePurposes();
```
although there *is* in
```js
aParticularlyLongAndObnoxiousNameForIllustrativePurposes =
  anotherVeryLongNameForIllustrativePurposes.length;
```
and
```js
aParticularlyLongAndObnoxiousNameForIllustrativePurposes =
  anotherVeryLongNameForIllustrativePurposes + 1;
```

I'd expect every one of these to break after the `=`, since otherwise line length exceeds 80 characters. (Though I thought it used to... is this an intentional, or a regression?)

[Here's a link](https://prettier.io/playground/#%7B%22content%22%3A%22aParticularlyLongAndObnoxiousNameForIllustrativePurposes%20%3D%20%5Cn%20%20anotherVeryLongNameForIllustrativePurposes%3B%5Cn%5CnaParticularlyLongAndObnoxiousNameForIllustrativePurposes%20%3D%5Cn%20%20'a%20very%20long%20string%20for%20illustrative%20purposes'.length%3B%5Cn%5CnaParticularlyLongAndObnoxiousNameForIllustrativePurposes%20%3D%5Cn%20%20anotherVeryLongNameForIllustrativePurposes.length%3B%5Cn%5CnaParticularlyLongAndObnoxiousNameForIllustrativePurposes%20%3D%5Cn%20%20anotherVeryLongNameForIllustrativePurposes()%3B%5Cn%5CnaParticularlyLongAndObnoxiousNameForIllustrativePurposes%20%3D%5Cn%20%20anotherVeryLongNameForIllustrativePurposes%20%2B%201%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) containing all of these cases.

This also applies to variable declarations.

**Comment by azz** [comment] 2017-07-16 05:56
Another one, from #2322

```ts
export const listAuthorizedSitesForDefaultHandler: ListAuthorizedSitesForHandler = aListAuthorizedSitesForResponse;
```

**Comment by bakkot** [comment] 2017-07-16 18:28
#1419 is yet another instance of this, I think.

**Comment by bakkot** [comment] 2017-07-16 18:34
And #2184.

**Comment by bakkot** [comment] 2017-07-17 17:53
Also #2485.

**Comment by bakkot** [comment] 2017-07-24 17:46
This issue is pretty much a duplicate of #1966; we should probably pick one place to consolidate.

**Comment by azz** [comment] 2017-07-25 01:37
Lets keep this one open as it has more links

**Comment by bakkot** [comment] 2017-07-26 17:10
Towards actually fixing this - I think something like `fill` might be the right thing to do? (Assuming I am remembering how `fill` works.) As in, `fill(group(left, '='), right)`.

The desired behavior would be:

- If it's impossible to fit the first atom (i.e. non-breakable component) of the RHS on the same line as LHS + `=`, break after the `=` *before* breaking the RHS.
- If the RHS breaks but the above does not hold, don't break after the `=`.
- If the LHS + `=` does not fit on one line, break the LHS if possible, and otherwise just allow the line length to be exceeded. Do not break immediately before the `=` under any circumstances.

I think this handles most of the cases in this thread correctly, except the OP's case in #2184.

Possibly there are some cases where you wouldn't want to use `fill` and instead just allow breaking after the `=`, like `x = a.b`.

**Comment by vjeux** [comment] 2017-07-26 17:12
@bakkot interesting! Would you mind trying to code it up and see how it feels? If you can solve it, that would be awesome. It's one of the biggest remaining issue with prettier that I don't really know how to solve :)

**Comment by bakkot** [comment] 2017-07-26 17:28
Update: `fill` doesn't do the thing I thought it did. Ah well.

Still, I think the above rules are the right thing to do. Is there an easy way to get the first unbreakable component of a doc and figure out if it would fit on the current line? I'm guessing probably not...

**Comment by bakkot** [comment] 2017-09-26 07:04
At least some of these cases also apply to object properties; see #2889.

**Comment by pbarbiero** [comment] 2017-09-26 19:19
Is this part of this issue? https://prettier.io/playground/#%7B%22content%22%3A%22export%20const%20portalUrl%20%3D%20%60https%3A%2F%2F%24%7Bconfig.object.property%7D%3A%24%7Bconfig.object2.property%7D%60%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D

**Comment by duailibe** [comment] 2017-09-26 19:31
@pbarbiero I think this error is the same as #1893

**Comment by bakkot** [comment] 2017-10-31 21:18
Thinking about this more - I think what's needed is a way to say that `a = b` can always break after `=`, but  `b` breaking should not automatically cause `a = b` to break, and I guess also that it's better to break `b` than `a = b`. This is kind of like #3014, but not quite.

**Comment by EthanRutherford** [comment] 2017-11-14 20:00
Personally for `a = b`, I think you should almost never break `a = b` unless you can also break `b`.. Though it may depend on the length of `a`.

for example, I find this to be a pretty useless change:

```js
let string = 'something';
if (someCondition) {
    string = 'some really long string that goes over the line width limit and breaks up the line';
}
```
=>
```js
let string = 'something';
if (someCondition) {
    string =
        'some really long string that goes over the line width limit and breaks up the line';
}
```

The shortness of `a` makes putting `b` on the next line look awkward and imbalanced. And as said earlier, this happens all the time in object property initialization and json files as well.

**Comment by RenaldasK** [comment] 2018-07-06 10:58
We have the same issue, and it is breaking our pre-commit hook that auto-formats the files and then runs tslint, and then tslint reports errors. To get around this for now we are using `// tslint:disable-next-line:max-line-length` to suppress the error on the offending lines. Would be very nice to see some fix.

**Comment by lydell** [comment] 2018-07-06 19:06
@RenaldasK We recommend using [tslint-config-prettier](https://github.com/alexjoverm/tslint-config-prettier) to turn off all rules that conflict with Prettier.

**Comment by eamodio** [comment] 2018-07-10 20:43
Here is another case imo:

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGYQQ7AA6UOOARugE4AUAlMWRSTJFJjDgLZwAmAS3TkAvDn7p4mAHSoEAcxgALHAFIcAJhwB+CVLiYA2svSo8AXRkK4MACqC+jHEhx1J0k2bw4AtDgBGKxt7RzhnAGp9T1NzYNsHJwYmAHotGQAGAG4KVnIcAF8yIqgQABoQCAAHGEFoTGRQWhoIAHcABVoEBpR0ADcIQX5ykEoadDAAa1sAZSqJwSgFZBgaAFc4CsXMOBoYdvGFHnRkPDMdioArTAAPACFxqdn0PgAZRbhT882QeZodmjIEAwACeVUMYBoghqIyqLR2AHVxlUgXDDLs+p8KjQ4ABHNaCHEHdBHE5IM6oC4gHY8QQrdY-TCLBTyACKawg8C+lJ+q3QglQzIAwhAeMcgVBoFiQGsdnZ0JQehSqXDFjAEUMVMgApoMhUYAqNfwtUgACwFApAA)
```sh
--parser typescript
--print-width 120
--tab-width 4
```

**Input:**
```tsx
class foo {
  bar() {
  	const median = dates.length % 2 ? dates[half].getTime() : (dates[half - 1].getTime() + dates[half].getTime()) / 2.0;    
  }
}

```

**Output:**
```tsx
class foo {
    bar() {
        const median =
            dates.length % 2 ? dates[half].getTime() : (dates[half - 1].getTime() + dates[half].getTime()) / 2.0;
    }
}

```

**Expected behavior:**
```jsx
class foo {
    bar() {
        const median = dates.length % 2
            ? dates[half].getTime() 
            : (dates[half - 1].getTime() + dates[half].getTime()) / 2.0;
    }
}
```

**Comment by ljharb** [comment] 2018-07-10 20:46
In general, I think any linebreak after an `=` or `=>` should be a last resort - and that any other formatting, if possible, would be preferred.

**Comment by eamodio** [comment] 2018-07-10 22:17
The same thing seems to happen with `:` when used in a object literal too

**Comment by ljharb** [comment] 2018-07-10 22:24
It also happens in a jsx arrow function, something like [this](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4B0oAEB0AwgDaZgDWAvMAM4QC2cMAFplAOYAy0XBGgD4CjFu069+cAE4AKAIYAjMABoC6OADN1XDgEoAvvgD0QkKpAQADjEzR6yUApkyIAdwAKLhI5QLsCEx0CxAlGQVqVgBla0jJZBgZAFc4S056WRhPCK4mBWQtBTJMywAregAPACEIqJhohRYeTjhC4tKQOJlMmWQw5QBPMmhQ6zdMgHUI637xuF7sNssZOABHZMxVnIU8gqQikrSQTKZMRJTj+kkyOABFZIh4dqPLGGVJ4PZkACY3iMwFG4JGY+X6UGgyxAyUyABVlH5Dp1xpwYJ90N8kABWAAchkMQA) where i'd instead expect:
```jsx
<div
  onClick={somethingLong => somethingLonger(
    abc,
    def,
    ghi
  )}
/>;

```

**Comment by bradennapier** [comment] 2019-01-29 17:38
sooooo is this broken forever? lol it makes projects unusable with prettier.  i have print width to 80 and eslint max-len is at 100 and its not breaking a row that is 150 characters long...

**Comment by bakkot** [comment] 2019-01-29 17:42
@bradennapier if you have a proposal for a consistent way of fixing it, I think everyone would be interested!

**Comment by FredyC** [comment] 2019-11-01 08:00
The solution in https://github.com/prettier/prettier/issues/2482#issuecomment-318120270 sounds like it would fix most of the cases, so why not go with that and figure the rare cases later? It's kinda ridiculous of having this issue for 2 years now and waiting for the "brilliant" solution when at least "average" already exists?

**Comment by lydell** [comment] 2019-11-01 16:38
@FredyC Hi!

> It's kinda ridiculous of having this issue for 2 years now and waiting for the "brilliant" solution when at least "average" one already exists.

Why do you say this? Have we said something like that?

This issue is still open because it’s a difficult problem and nobody has done the work trying to fix it yet (other than posting suggestions in this thread). Prettier is run by volunteers, so people work on whatever they feel like.

A PR that improves the situation would be very much appreciated, even if it does not cover all cases.

**Comment by FredyC** [comment] 2019-11-01 19:22
@lydell I am sorry, I don't mean any disrespect. Prettier is an amazing tool and this is the first issue I had with it. I am maintaining couple of OS libraries myself so I know well how ungrateful "job" it can be. Even if I had some time to spare for helping out here, I would have no idea where to start as I am unfamiliar with how the whole thing works.

> it’s a difficult problem and nobody has done the work trying to fix it yet

Based on the comment above it felt like it has a fairly straightforward solution. Apologies, if it's not the case.

**Comment by bakkot** [comment] 2019-11-01 19:43
FWIW, as the person who sketched that solution, I don't think it would be straightforward. I think it might be feasible, but it'd be a fair bit of work, and I haven't even thought about it hard enough to confirm it's possible at all.

**Comment by lydell** [comment] 2019-11-02 19:08
Adding the example from #6783:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wQDcBLbCAWwRgAVqATANQEMAbAVziKTwBRKJWpQ6sDjz54AvHnZEiFAOZQAPMNHQJMKbyIA+ABQAdKHjzBzly+wwUAqgCUAMgIDkAensUPAGhs8AF9AizxyKlp6ACFFOH0+cwBKAG4QfxAIDBgKaCJkUHZsagB3BmKEApR2MggKZgyQACNsdjAAazgYAGUMdoooFWQYbF5MgAsYGk4AdQmKeCJ+sDgeqsWKShgAT2RwJSbBojhcJnYVGnZkADMuE8yAKyI0GLbO7p72OldBuFv7nAni8eoMVJw4ABFbgQeAAzgPED9bAnbD7XYYPhgbAUHJNDA42CzBowCbIAAcAAZMgSICdZm0MPsCXxTmR-pkAI4w+BMbLVECKAC0UDgcGY4qa2Dg3KocHOl2uSDuCKBIBONAoIzGauUQwh0Nh-2VgMyMHYzWJzFJyAATGa2hROGCAMK0K77KDQDkgbgnAAqFuqKpOwWCQA)
```sh
--parser typescript
```

**Input:**
```tsx
export const enviromentProdValues: EnvironmentValues = assign<EnvironmentValues>(
  {
    apiURL: '/api',
  },
  enviromentBaseValues
);
```

**Output:**
```tsx
export const enviromentProdValues: EnvironmentValues = assign<
  EnvironmentValues
>(
  {
    apiURL: "/api"
  },
  enviromentBaseValues
);

```

**Comment by dschinkel** [comment] 2020-07-28 16:35
What fixed this for me was I had to set **printWidth** to the **same width as my default hard wrap width in my IDE**. 

Example, this was wrapping and I hated that:
```
export function countriesReceived(countries: Array<Country>): CountryActionType {
  return {
    type: ActionTypes.COUNTRIES_RECEIVED,
    countries: countries,
  };
}
```

was wrapping the function param:
```
export function countriesReceived(
  countries: Array<Country>
): CountryActionType {
  return {
    type: ActionTypes.COUNTRIES_RECEIVED,
    countries: countries,
  };
}
```

WebStorm was set to hard wrap at 120.  So I had to make sure prettier's matched that so they were in sync.

**Comment by campbebj** [comment] 2020-08-05 17:12
Is this issue just being ignored?

**Comment by evilebottnawi** [comment] 2020-08-05 17:24
@camacho Nobody send a PR with good fix

**Comment by brodybits** [comment] 2021-01-14 23:40
While trying a few potential solutions that have all proven to be breaking changes I found a few more cases for investigation and comparison:

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAllAJgmHAcwwHcsYALDAQwGc6sioBbAjAMgwFcoaAnAJ4YIABzj8aMCPyQAdPgAUBhMNwA2A9YIAy0IgEE8AeQBGUCAA8sEbnQByNNgDEZASXXq7MSYQBucIrc-KIQdHB0GAC8GACEABQKGLQWVBIAahK6+o4u7p7evlgBQSFhEZwcSRiCcDBGEGn8mUJ6UES5cK78Hl50PlLFgcGh4XQKAJQA3AoK6Nh4BMRkFNSmOALCXLybIuK+MnTySipYapr82m2GJuZWNnad3b2FgyUj5ZEAPl9xiVDJGipSgZLLXJ75PoDfzDMpjSrVWr1YGg1o5JxdSGvGGlUYRSazKDzCCmABWcDAMBWVAwcEsAww6n0GAA1nBBKg-DQvHBjsBaMp+KoNFpsu0jLgzBZrLYHBjngV+kV3nCIkgMHIQEDGiDmmD0XkeoroUNcZ9NRgAL6E+ZQCLwXAYeD8PhCEQA6BwRk4OAKABmWH4-QwAH4MPFwpA8KGnZRA471X7bELKBMMImsH6qDbMHb+nBHc7XcJ+HAk-wWFIHf7A8GwxGKdBHWGqPH0xgk8EqGmM1nKNUwzRBcKLld9BKpfdZRCjVDlbC8eMAe3tU0WmKOvKsUq3gvPjMoCAADQgMSEaB0ZCgAT8CCkQUIS8obmkGiCS8n0ySMBsmAAZVEGgwGIZAfG4OATzgFhTALfBcB0IEiG4GgiExCsqxA59uGkY8QEoGAWHUAB1ON4DoQCwDgP9HwoYoKEEZBwAYXCcHCIVFEkIhK2QP1uXCE9SToSwACFv1-P8MR0H0eL4iCQEEyw-2IdQ4AARW4Ro4Bk9R+JAQCgwkRjTBoGD1Fw0R+BwGAiKwXAqGQAAOAAGE8LPKIjJFERiLIiCQAlwgBHDT4A4sQny1OgAFo7QLAtcNLILA0CTjuKQXidLk8IWCwUD+HAk9GHaFT1M07TdJgEybLsyhkAAJhPAYsHUYgAGEIBYVKQAiABWXC7DgAAVEyn3S3S-HAtxFlgP8wEs0RkVwP8YEEFSyrgS1LSAA)
```sh
--parser babel
```

**Input:**
```jsx
// indenting with assignment & unary operator:
aParticularlyLongAndObnoxiousNameForIllustrativePurposes = !(
  anotherVeryLongNameForIllustrativePurposes &&
  yetAnotherVeryLongNameForIllustrativePurposes
);

// indenting with binary & unary operators:
aParticularlyLongAndObnoxiousNameForIllustrativePurposes || !(
  anotherVeryLongNameForIllustrativePurposes &&
  yetAnotherVeryLongNameForIllustrativePurposes
)

// object with extra long key/value:
{ aParticularlyLongAndObnoxiousNameForIllustrativePurposes: "anotherVeryLongNameForIllustrativePurposes" }

// nested ternary on one line
first ? (second ? third : fourth) : fifth

// nested ternary reformatted
first ? (second ? third : fourth) : fifth
  ? aParticularlyLongAndObnoxiousNameForIllustrativePurposes
  : anotherVeryLongNameForIllustrativePurposes;

```

**Output:**
```jsx
// indenting with assignment & unary operator:
aParticularlyLongAndObnoxiousNameForIllustrativePurposes = !(
  anotherVeryLongNameForIllustrativePurposes &&
  yetAnotherVeryLongNameForIllustrativePurposes
);

// indenting with binary & unary operators:
aParticularlyLongAndObnoxiousNameForIllustrativePurposes ||
  !(
    anotherVeryLongNameForIllustrativePurposes &&
    yetAnotherVeryLongNameForIllustrativePurposes
  );

// object with extra long key/value:
{
  aParticularlyLongAndObnoxiousNameForIllustrativePurposes: "anotherVeryLongNameForIllustrativePurposes";
}

// nested ternary on one line
first ? (second ? third : fourth) : fifth;

// nested ternary reformatted
first
  ? second
    ? third
    : fourth
  : fifth
  ? aParticularlyLongAndObnoxiousNameForIllustrativePurposes
  : anotherVeryLongNameForIllustrativePurposes;

```

Some observations:

- there is an extra level of indenting in the binary operator vs assignment statement
- maximum line size is not respected in case of an object with extra long key/value pair
- a nested ternary can be completely reformatted in case another ternary with long values is added to the end

**Comment by brodybits** [comment] 2021-01-26 20:28
I found something else that doesn't look right, wonder if it may be another manifestation:

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbCHNez3f9ZQDmAjABQCUAdOgXXcQEyVUDOEAtnDABYCWxSgB0oI2vQmSp0InABO5auOkrMxecwoiQAGhAQADjD7RWyUAEM5ciAHcAClYRmUF1LYsBPM3oBGcizAAa24AZQNAgSJkGDkAVzg9OA5fOAATNPSAGQtiOItZADEIOQ4LGGNiZBALOJgIXRAeGA5UAHV+eFYIsDhQ5z5jADdBz2qwVh8QAVZ5GHsAojLkADM3Wb0AK1YADwAhAOCwiy4sgThV9cSQbZ3QqNQ4AEU4iHhL1A2QCLlZuWrfBZUqhGgY5AIYG0+GleMgABwABj0YIgszaAQM1TBcD+QwuegAjq94AtDC4aqwALRQODpdKNORwIl8RkLArLJBrT7XWYcPgxeI8h7PYkXTlXPQwIFQmE8ZCMSUBPioKIAYU4HJAOIArI04rMACpAlxcr5DBIASSgmVgoTA4KMAEFraEYJ5Hh9ZgBfL1AA)
```sh
--parser babel
```

**Input:**
```jsx
looooooooooooooooooooooooooooooooooooooooooooooooong1().looooooooooooooooooooooooooooooooong2().something()

looooooooooooooooooooooooooooooooooooooooooooooooooooooooonger1().looooooooooooooooooooooooooooooooooooooonger2()

```

**Output:**
```jsx
looooooooooooooooooooooooooooooooooooooooooooooooong1()
  .looooooooooooooooooooooooooooooooong2()
  .something();

looooooooooooooooooooooooooooooooooooooooooooooooooooooooonger1().looooooooooooooooooooooooooooooooooooooonger2();

```

**Comment by attilacsanyi** [comment] 2021-03-17 12:00
Not sure guys, but I am the only one who still **see these issues** in the collected test cases [above](https://github.com/prettier/prettier/issues/2482#issue-243108118)?

**Comment by thorn0** [comment] 2021-03-17 12:46
@attilacsanyi "Closed" doesn't mean "released". Use the latest code from the `main` branch for testing: `npm install prettier/prettier`.

**Comment by attilacsanyi** [comment] 2021-03-17 15:18
Thnaks @thorn0 do you see which release will be in? Thx

**Comment by thorn0** [comment] 2021-03-17 15:29
2.3

**Comment by attilacsanyi** [comment] 2021-05-10 11:28
I found at least 3 cases which still having issues, I hope these can be also fixed. Appreciate for your help.

Sample code below can be found in the [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAchGGBGATnAIYDWAzhgBZzEA6UcAHgA4SF5gA2JFVAGWgBzIVFEixE8VKkBhCAFt2TWAEEMLeFAAmgyQZmHpJhcugIYAIQzBGGDPYwABAKIAzd3DAwAFAEondGxcAmJyKloGKAcKOG5vGABlJTgYagBLcQBFAFc6AE8ABRJCEkUAEiQMAHl8OMIANxJ8BIAeJPjElMU4NR8M6AA+DABeDHSMigA6OISfADEMwgpk1MnxCunWDNY4XydYgHcMmDBqAFkSVl8AsaHDhwnMmdWOOC2dvYOYp7+5xK+YRpHppTLiEplRRJGAkeD+AA0jz+7gy3HghAAqro4KimDoAkjfn8HDopjAsj5sRTuHJqCRxHACYjkU8KGRdr4AIws4kk2FkODUtG+SavVKuBK9WAw8KVQJ8hwKv68v6Ka6+CgSqWWACSOnuGCYRwwnXma16-Qp0E12rg0pg+v8yow-gA3E5HpAoKtCLkfBwfiSXLqoAArQEXNQAFQA+gARXVqAQ1ADiCZjahdf2CODwRFIlBodDgrNYuVaGTAGB0cJI1Qo9OIOguEB08Rm0doCggCVWSXBBTMKks8YyJG4EGE8brbUbpSZrfb3BmFwKCxIjQguUIpzgS-iQyJwfLlerZInU4ASrjqlcYGPL8Ib+42l24D2+8lB8OLLBH5Owi-qoMAPHy-i2AAvp6UDQVAjAgAiIAQKw1o+sgoClIQEBHJCCAUMgIATkcJAFARSFECQYCCskrBUVkwjIDAfpwEh9r4Ey7Y6AIDLCLkJDAgsHDqjAFLiIRJC5DAECISA1AwIo3AAOqZPAFB0WAcCdD6pwZI0pwFIRYD8LJWQNDARRlMI6rIO4E5xEhYYUMwVhlNRILlHAAhZHAtn2axIBOcwSQMQkeS4L5SB2SuAV0SsdCETABR7BQYC7qhsmsLusBKRkOjpMgAAcAAMSFZRAcRKWUrCEVlcANI0vlIQAjrkEWWShBEoHwAC0TBMkysnEK1yxwJZAk2VF-lIXEigZExLEzaFcDhfAfkxUhsL4Ll+XUMgABMm1lGiDFmJNID1QArLJuRxNGLRddFDkgI0+Shu2MppbsMBqLoMIFAk61xJBkFAA).

```
// Not breaks here
export class LongLongLongLongLongLongLongComponentA extends LongLongLongLongLongLongLongComponentB {
  
  @Effect()
  // Not breaks here
  selectSomethingQueryParam$: Observable<SelectSomeAction> = this.selectFirstSomething$.pipe(
    switchMap(() =>
      this.store$.pipe(
        select(getSomethingParamState),
        filterUndefined(),
        distinctUntilChanged(),
        skip(1),
        takeUntil(this.someElementStream$)
      )
    ),
    map(someElementId => new SelectSomeAction(someElementId))
  );
  
    constructor(
      @Inject(MAT_DIALOG_DATA)
      // Not breaks here
      public data: sharedModels.TheCoolestShinyComponentDialogData<sharedModels.MyFavouriteModel>,
      public dialogRef: MatDialogRef<TheCoolestShinyComponentDialogComponent>
    ) {}
  
}



```

**Comment by brodybits** [comment] 2021-05-10 13:05
@attilacsanyi your playground is for outdated Prettier version. I recommend you paste it into a brand new playground which should target Prettier 2.3.0 and raise a brand new issue. The playground also has convenience buttons to copy the markdown and to raise a new issue.

Here is what I got on 2.3.0:

**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAchGGBGATnAIYDWAzhgBZzEA6UcAHgA4SF5gA2JFVAGWgBzIVFEixE8VKkBhCAFt2TWAEEMLeFAAmgyQZmHpJhcugIYAIQzBGGDPYwABAKIAzd3DAwAFAEondGxcAmJyKloGKAcKOG5vGABlJTgYagBLcQBFAFc6AE8ABRJCEkUAEiQMAHl8OMIANxJ8BIAeJPjElMU4NR8M6AA+DABeDHSMigA6OISfADEMwgpk1MnxCunWDNY4XydYgHcMmDBqAFkSVl8AsaHDhwnMmdWOOC2dvYOYp7+5xK+YRpHppTLiEplRRJGAkeD+AA0jz+7gy3HghAAqro4KimDoAkjfn8HDopjAsj5sRTuHJqCRxHACYjkU8KGRdr4AIws4kk2FkODUtG+SavVKuBK9WAw8KVQJ8hwKv68v6Ka6+CgSqWWACSOnuGCYRwwnXma16-Qp0E12rg0pg+v8yow-gA3E5HpAoKtCLkfBwfiSXLqoAArQEXNQAFQA+gARXVqAQ1ADiCZjahdf2CRFIlAwR0IIhodDgrNYuVaGTAGB0cJI1Qo9OIOguEB08Rm0doCggCVWSXBBTMKks8YyJG4EGE8YbbWbpSZ7c73BmFwKCxIjQguUIpzgK-iQyJwcr1drZKnM4ASrjqlcYBPr8I7+42j24H2B8lh6OLLAz7TsI-6qDADx8v4tgAL6elAsFQCACIgBArDWj6yCgKUxZHJCCAUMgIBTkcJAFARyFECQYCCskrBUVkwjIDAfpwMh9r4EynY6AIDLCLkJDAgsHDqjAFLiIRJC5DAEBISA1AwIo3AAOqZPAFB0WAcCdD6pwZI0pwFIRYD8LJWQNDARRlMI6rIO4U5xMhYYUMwVhlNRILlHAAhZHAtn2axIBOcwSQMQkeS4L5SB2WuAV0SsdCETABR7BQYD7mhsmsPusBKRkOjpMgAAcAAMyFZRAcRKWUrCEVlcANI0vnIQAjrkEWWahBEoHwAC0TBMkysnEK1yxwJZAk2VF-nIXEigZExLEzaFcDhfAfkxchsL4Ll+XUMgABMm1lGiDFmJNID1QArLJuRxNGLRddFDkgI0+Shp2MppbsMBqLoMIFAk61xNB0FAA)

```sh
--parser typescript
```

**Input:**

```tsx
// Not breaks here
export class LongLongLongLongLongLongLongComponentA extends LongLongLongLongLongLongLongComponentB {
  
  @Effect()
  // Not breaks here
  selectSomethingQueryParam$: Observable<SelectSomeAction> = this.selectFirstSomething$.pipe(
    switchMap(() =>
      this.store$.pipe(
        select(getSomethingParamState),
        filterUndefined(),
        distinctUntilChanged(),
        skip(1),
        takeUntil(this.someElementStream$)
      )
    ),
    map(someElementId => new SelectSomeAction(someElementId))
  );
  
    constructor(
      @Inject(MAT_DIALOG_DATA)
      // breaks wrong here
      public data: sharedModels.TheCoolestShinyComponentDialogData<sharedModels.MyFavouriteModel>,
      public dialogRef: MatDialogRef<TheCoolestShinyComponentDialogComponent>
    ) {}
  
}

```

**Output:**

```tsx
// Not breaks here
export class LongLongLongLongLongLongLongComponentA extends LongLongLongLongLongLongLongComponentB {
  @Effect()
  // Not breaks here
  selectSomethingQueryParam$: Observable<SelectSomeAction> = this.selectFirstSomething$.pipe(
    switchMap(() =>
      this.store$.pipe(
        select(getSomethingParamState),
        filterUndefined(),
        distinctUntilChanged(),
        skip(1),
        takeUntil(this.someElementStream$)
      )
    ),
    map((someElementId) => new SelectSomeAction(someElementId))
  );

  constructor(
    @Inject(MAT_DIALOG_DATA)
    public // breaks wrong here
    data: sharedModels.TheCoolestShinyComponentDialogData<sharedModels.MyFavouriteModel>,
    public dialogRef: MatDialogRef<TheCoolestShinyComponentDialogComponent>
  ) {}
}

```

**Comment by thorn0** [comment] 2022-08-22 13:24
@attilacsanyi Those are 3 separate problems that have little to do with the original issue. Could you please open separate isolated issues for them, so that we could close this one? (Tip: use the Report Issue button on the [playground](https://prettier.io/playground/) to create issues.)

**Comment by attilacsanyi** [comment] 2022-08-22 16:18
Sure will do thanks for commenting 👌

**Comment by thorn0** [comment] 2022-08-29 13:01
The original problem had been solved in https://github.com/prettier/prettier/pull/10222
Let's not reopen this issue for new problems related to assignments. They should be processed in new separate issues.

**Closed by thorn0** 2022-08-29 13:01 UTC
Labels: type:bug, help wanted, lang:javascript, difficulty:hard
