### ISSUE TITLE
Respect case sensitivity in for components in MDX

### ISSUE THREAD

**Issue by frmlnd** [prettier/prettier#7548] opened 2020-02-05 17:26 UTC
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: Node.js API
- Runtime: Node.js v12.14.0
- Operating System: macOS, etc.

**Steps to reproduce:**
[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiVACAQgQwM4CWYGArnjgOZwA6UtAPAOIBOBAJgHy0Yb0BKEAO5coPHvQDCEADYY8AWwC8wAEwBfDPLbKALBukVlANjUix5jAGUI8uBkiwEMDAVEwAFgTz2ZeAA44UAB03GL0APRS0ma84QLCDOEs7BwgADQgEH4wBNB4yKA4zMxCAApFCPkoOABuEOzpIABGzDhgANZwMJYBYK4UyDDMJHAZ7jDy0gDqnvD+bXCWlQQ5NSsAnsjgePkZrnhwzDClrRTyOMgAZjjSBxkAVngAHlitHV2WOLYAMq5wVzc7iBHk9LP1pHAAIokCDwAG3UYgALMA7MLZaJ6NPysWBTdgeZAADgADBlsRADlNWn4tti4Kiav8MgBHGHwE5ZKogfAAWigcDgbEFjWYcFZBFFJ0o53hQIO8gIg2GiMIUAoEOhsP+SGuCIyMBwTTxbAJSBU+taBGk-Sk8hlKCg0CZIDIcAAKoaqrqgTURgBJKBC2CWMCsbIAQUDlhg6whsrgajUQA)

`--parser mdx`

**Expected behavior:**
Prettier would examine markup/components in a case-sensitive manner so components that with `lower [name]` that match html elements do not get parsed as html elements.

**Actual behavior:**
When I include a React component `<Col>` in my MDX file, prettier gives me a `SyntaxError: Void elements do not have end tags "Col"`. This happens because <col /> is a legitimate element in HTML, and prettier is checking elements in a case-insensitive manner.

**Comment by thorn0** [comment] 2020-02-27 00:31
This has been fixed by #6949, but not yet released.

**Comment by thorn0** [comment] 2020-02-27 00:32
Duplicate of #6943

**Closed by thorn0** 2020-02-27 00:31 UTC
Labels: lang:mdx, type:bug
