### ISSUE TITLE
Use two spaces at the end of sentences in prose

### ISSUE THREAD

**Issue by vermiculus** [prettier/prettier#11963] opened 2021-12-12 16:58 UTC
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAJOAnOACAlgZ23wgFsd8BDEgBwBsd4APGAOm2wDkJ5sYALTDgpZeAdwhFqFMHEIUYvAdgQATbBABm2Wriiy22ACp8CAHSgVatCKMJwVuGBAyEn2CwDdcAc3k4Arvi63kQI8FAyALQARhT49qEkFLC4YPgANNgazsqMVHRw6ebmAAZl5gCykTgY-lCuSpAkSVBq2RiiwiqR8bAIMtgAFNl1arrY3taxtJFJ1ACUmaImYHx4+ObJeH0Y0jC4HjhN1Lj0agAyBNRZdWD70NvYgBgEUrveu9R8+CxwtICYBCxilAAJIKAjYaIQUa8CRVOCAqDmYbOToYbq9cIDABkEGo9wstGwAEEAEoAcXmQPYAAUMBBYtFaABPbYwOkqfwyNTydQYCFwdo4ACiSTS2EOLlwDwATABGFjyoEVCCHLIorow9xwZjKVrqLQY-rw9gAdUca2E3n8ZFgmSw1Dg8gRJoEUGJ5PWWt8+0OmRIKpwsTAAGtUWp7Y74CpmZr8DBhApNKE+hF4UDjDgPMJcBRGTgnobU9VWn9PRRsFgrbRhLlqFh8EEHvweUkYKtZLqVIRNOZCzJvuwibRiJk4BKWa8KO8KJ8IVDWsIWfAMCRdH5CH2O3FsKJfrQEWUSiB0iBcfj8MhQMI6aJqcIEBeUJZOkyLyforsQ3AYABlKhwS49GQDRLHid9P2Db8fykMBgmQNl-EKEA4BIaJ7BUexzmSK0pzgAAxZxW32KBvGQEAKH8JxjxAPgYBIWgXUcWQYLgH8H0cA5HCZMi0jfEBdHiDAYFpKckmA0CkIAK3wRgf2CegAEV-G4OBxOHJDXkEsikgwYMVBsKBqLrXQYDNFR+GQAAOAAGE86wgeITQ+Mi61kTBDmogBHZT4FpXFH3I-BIj0ex7GorBvNwLARO8MSkBA9ST3iVd4NqJCghIxSfNU+KJJPeNojMiykGlfLdlOYIAGFSDi5D8AAVmowI4EMXNHwSsCQA8RDgVaMIfzADBcDxIlWh-GAmXoNT4gAXxmoA)

```sh
--parser markdown
```

**Input:**

````markdown
Here is some sample text.  Note there are two spaces at the end of lines.  This
allows editors to navigate using sentence-based semantics, for example,

```
M-e runs the command forward-sentence (found in global-map), which is
an interactive compiled Lisp function in ‘paragraphs.el’.

It is bound to M-e.

(forward-sentence &optional ARG)

  Probably introduced at or before Emacs version 21.1.

Move forward to next end of sentence.  With argument, repeat.
When ARG is negative, move backward repeatedly to start of sentence.

The variable ‘sentence-end’ is a regular expression that matches ends of
sentences.  Also, every paragraph boundary terminates sentences as well.
```
````

**Output:**

````markdown
Here is some sample text. Note there are two spaces at the end of lines. This
allows editors to navigate using sentence-based semantics, for example,

```
M-e runs the command forward-sentence (found in global-map), which is
an interactive compiled Lisp function in ‘paragraphs.el’.

It is bound to M-e.

(forward-sentence &optional ARG)

  Probably introduced at or before Emacs version 21.1.

Move forward to next end of sentence.  With argument, repeat.
When ARG is negative, move backward repeatedly to start of sentence.

The variable ‘sentence-end’ is a regular expression that matches ends of
sentences.  Also, every paragraph boundary terminates sentences as well.
```

````

**Expected behavior:**

I expected my sentences to continue having two spaces at the end.

**Comment by kachkaev** [comment] 2021-12-13 02:36
Duplicate of https://github.com/prettier/prettier/issues/9810

**Closed** 2021-12-13 02:36 UTC
Labels: type:duplicate

**Comment by vermiculus** [comment] 2021-12-15 14:57
Ah, thank you! I was searching for the wrong phrase 😄
