### ISSUE TITLE
TypeScript: SyntaxError: Unexpected token (1:12) when defining type of `this`

### ISSUE THREAD

**Issue by balupton** [prettier/prettier#5515] opened 2018-11-21 04:55 UTC
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqAFDABY4DOS+AbhDgCYCU+wAOlPl-gPQ-4BbAIYBrOPgroATuIAGZSrPyV8mdBSEAjADbicnBRQkwhUBkO3RxGLLmgcAviAA0ICAAc7UCslBCpUhAA7gAK-gg+KEJ0jC4gmlJCYGIwAMruSfoA5sgwUuhwrqQwAtoA6uTwFBlgcKkROLg0jQCeyOAUPq76FHBSMCGJWcLIqBa9rgBWFAAeAEKJyXBpQgJwADL6cKPjhSDTM6nZugCK6BDwO9oTIBlSvVLtmlotllBx7lL6MGWMZMgADgADK5PhBemVEu52p84A8aNtXDIAI7oHAyQZCYZCK43XoCHC5fJ7CjHOBnC7bJBja57EyaX4Mf5IABMrjyQhw2myAGEIAIRigoFY4uo4AAVLSRGm9BwOIA)
```sh
--parser babylon
```

**Input:**
```jsx
function f(this: void) {
    // make sure `this` is unusable in this standalone function
}
```

**Output:**
```jsx
SyntaxError: Unexpected token (1:12)
> 1 | function f(this: void) {
    |            ^
  2 |     // make sure `this` is unusable in this standalone function
  3 | }
```

**Expected behavior:**
No error, as this is valid typescript syntax:
https://www.typescriptlang.org/docs/handbook/functions.html

/ref https://github.com/prettier/prettier/issues/5514

**Comment by ikatyang** [comment] 2018-11-21 05:14
Duplicate of #5514

**Closed by ikatyang** 2018-11-21 05:14 UTC
