### ISSUE TITLE
May mix tabs and spaces for ternary expressions

### ISSUE THREAD

**Issue by PinkChampagne17** [prettier/prettier#15490] opened 2023-10-05 10:37 UTC
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEFMF5MCMmA-JsADpTkwBmEEShANJdQEYCGATowEwtQAvpkbBBIJiAgAHGAEtoAZ2ShuXCAHcACtwTKUHVBo4BPZZLZcOYANYYAyhwC2cADJyocZDUOK4Fq1sHaWsPAHNkGC4AV38QPyc5SJi4xXD0AEVoiHhvXziAK0UAD3t0uCycryQfVD9JAEds+C11aX0QDkUAWk84ABMBiRAojjlUcIBhCCcnDmRO1FRhtKgw9ABBGCi5NmiWuC53Tzy6uIALGCdUAHVzuXhFELA4ez0HuQA3B5MFsEVzCBPrEAJJQQawexgLhyWQbcH2GAmdCneogaTqPw3KzSBYYuB+LifLySDyEmCtDhhOaouIhLiEhacNhwZaSDEeGA3OT9GDnZAADgADJIuHAmnIxZTqfMavlJDAOGxubz+Uh+CBon4ACpK-RRWKSOBOFn9Qb9VwcNbRKlwABiEC4c224QWHH2EBAgkEQA)

```sh
--parser babel
--use-tabs
```

**Input:**

```jsx
let o = 1 ? {
	foo: 1,
	bar: 2,
} : {}
```

**Output:**

At the 5th line of output mix a tab and two spaces.

```jsx
let o = 1
	? {
			foo: 1,
			bar: 2,
	  }
	: {};

```

**Expected behavior:**
No idea yet, but tabs and spaces should not be mixed for consistency and [a common ESLint rule](https://eslint.org/docs/latest/rules/no-mixed-spaces-and-tabs).

**Comment by sosukesuzuki** [comment] 2023-10-07 07:15
Duplicate of https://github.com/prettier/prettier/issues/4199 and see https://github.com/prettier/prettier/issues/4199#issuecomment-389533517

**Closed by sosukesuzuki** 2023-10-07 07:15 UTC
