### ISSUE TITLE
0️⃣ Line-wrapping object properties causes JS to be tab-delimited

### ISSUE THREAD

**Issue by Sawtaytoes** [prettier/prettier#10553] opened 2021-03-16 22:28 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEA3AhgGwEsATXGQ6AFQE8AHONTAXk2AB0pNMBhACQEEAcgHEAokkwByPkLGSANBy4BlAKoAhALIBJShMlqtuhRwC+HEPJARa5dMlC4ATk4gB3AArOEaZCAJuuNS+VgBGTrhgANZwMMq0kYRQAObIME4ArnBWcAC2oXDExIUAMrgpGbjJcABiEE65ZOQpfrgZMBCWIAAWMLn4AOrdhPBoCWBwyj4jhNgj1H5gaCEgSWhwTjAeEcmNyABmBOtWAFZoAB7qEdGxyri5cCVJcAdH2SBn58pJyfhwAIoZCDwV74Y4gBJOdZOPyhXAFfBdWhOJIwAYkGDdZAABisyIg6wGEVofmRDA22BeVgAjkD4NsbL4ULg0ABaKBwQqFLpOOC0wi87ZVPZIQ5g97rXKENKZCU-P6A4EvUVvKwweHo4iY5AAJjVEUIRBS3AguRFIAYAFYuhl1pR4UyxeDsFltFBirBlGAUbZ+O7lDBqH9QetTKYgA)

```sh
# Options (if any):
--print-width 0
```

**Input:**

```jsx
const validationTypes = {
  CHANGE: "CHANGE",
  SUBMIT: "SUBMIT",
}
```

**Output:**

```jsx
const validationTypes = {
  CHANGE:
    "CHANGE",
  SUBMIT:
    "SUBMIT",
};
```

**Expected behavior:**
```jsx
const validationTypes = {
  CHANGE: (
    "CHANGE"
  ),
  SUBMIT: (
    "SUBMIT"
  ),
};
```

When breaking lines, I would expect to use parens to make a clear distinction between the beginning and ending of segments of code. JavaScript isn't tab-delimited, so there's no way for you to know where long bits of tabbed code starts and ends.

Not being able to find your way around a codebase because we're tab-delimiting instead of using parens makes the code harder to read.

**Comment by thorn0** [comment] 2021-03-17 00:09
Duplicate of #3593

**Closed** 2021-03-17 00:09 UTC
Labels: type:duplicate
