### ISSUE TITLE
React Component body text wrapping results in line length violation

### ISSUE THREAD

**Issue by Cielquan** [prettier/prettier#11147] opened 2021-07-03 15:50 UTC
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaIFs4BqAhgE4CWRARgDZyYC8mAOiAMp50AqcAHjCwG4mUADycSRKGgB8wzJnb5MAEwCuuXAE9M8PpjJQdACzqRcAB2gIslCMu0B3I2TBHsRiKurLMlOgA5-TFdSIjB4EjRMamgAcx0IHTgMYzI0JExgHHxicipaAF8AOmERAHpxSRlhEAAaEAhzGDJ0ZFBSEggHAAVSBDRkECJqByJNAfrKCTAAazgYVnMwg1jkGBJVOHq4XD9lZThlABlJWNUiWLgAMQgSXCIYZqhVlCJVGAg6kCMYXGoAdWc8DQSzAcFY-TIzQAblDNIMwGgJiADGg4CQYN0JLF7sgAGbDNH1ABWaB4ACFpnMFkR8EcDHB8YStiBSTxWCtaABFVQQeBM6hEkBLSLowaUKhwahfczkWD-MjKGBGZCBeqyiBo-4ScyDWXJdHQxn1ACOvPgWMaA1eaAAtFA4IdDl8SHAzWRXViLrikATBSy0bgyGsNgHOXAeXzGb7mfUYFQFUqVUgAExxiRkagrADCeB9IGSAFYvqo0ZwqNa-ULoZsAJJQA6wVhgchNACCDdYME0tAFaIKBSAA)

```sh
--parser babel
--print-width 88
```

**Input:**

```jsx
const someVariable = "Some Text";
<Trans>
  Some dummy text in the component body which should be 88 characters long to test this: {someVariable}.
</Trans>

```

**Output:**

```jsx
const someVariable = "Some Text";
<Trans>
  Some dummy text in the component body which should be 88 characters long to test this:{" "}
  {someVariable}.
</Trans>;

```

**Expected behavior:**
This is my expected output:

```jsx
const someVariable = "Some Text";
<Trans>
  Some dummy text in the component body which should be 88 characters long to test{" "}
  this: {someVariable}.
</Trans>;

```
The issue is that `{" "}` seems to be added after determination of the set line length and where to break the line. I would expect that the break-point should be `line-length - 5` so the resulting reformatted line does not violate the line length setting it tried to achive.

**Comment by lydell** [comment] 2021-07-05 17:30
Duplicate of #2553

**Closed by lydell** 2021-07-05 17:30 UTC
