### ISSUE TITLE
Allow extensionless files to be detected by prettier -w .

### ISSUE THREAD

**Issue by Ragnoroct** [prettier/prettier#13499] opened 2022-09-20 20:32 UTC
**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: CLI
- Runtime: Node.js v16.15.0
- Operating System: Linux
- Prettier plugins (if any): 

Note: Even if prettier were to scan files without extensions it would need a way to determine the parser to use. I noticed that `javascript` is the default parser but can't be specified explicitly in the config.

**Expected behavior:**
Files listed in `overrides.files` array should be picked up by prettier.

**Actual behavior:**
Files without extensions are ignore even if explicitly included by config.

**Steps to reproduce:**
```bash
#!/usr/bin/env bash
set -e

tmp_dir="$(mktemp -d)"
cd "$tmp_dir" || exit
printf "> reproducing prettier/prettier issue #13499 in %s\n" "$PWD"

printf "> creating .prettierrc.yaml config\n"
cat << EOF > .prettierrc.yaml
overrides:
  - files:
      - "with_ext.js"
      - "without_ext"
    options:
      tabWidth: 4
EOF

printf "> creating with_ext.js test file\n"
cat << EOF > with_ext.js
// with_ext.js
if (true) {
  console.log("should be 4 tabs (fixed)")
}
EOF

printf "> creating without_ext test file\n"
cat << EOF > without_ext
// without_ext
if (true) {
  console.log("should be 4 tabs (NOT fixed)")
}
EOF

printf "> installing prettier with npm\n"
npm install prettier@2.7.1

printf "\n> before prettier -w\n"
cat without_ext with_ext.js

printf "\n> running prettier -w .\n"
./node_modules/.bin/prettier -w .

printf "\n> after prettier -w\n"
cat without_ext with_ext.js

printf "\n> removing %s\n" "$tmp_dir"
cd - || exit
rm "$tmp_dir/without_ext"
rm "$tmp_dir/with_ext.js"
rm "$tmp_dir/package-lock.json"
rm "$tmp_dir/package.json"
rm "$tmp_dir/.prettierrc.yaml"
rm -rf "$tmp_dir/node_modules"
rm -r "$tmp_dir"

```

**Comment by thorn0** [comment] 2022-09-22 21:31
Duplicate of #11141

**Closed** 2022-09-22 21:31 UTC
Labels: type:duplicate
