### ISSUE TITLE
With IIFE and `semi: false`, re-running produces different output

### ISSUE THREAD

**Issue by Conduitry** [prettier/prettier#2944] opened 2017-09-30 18:42 UTC
**Prettier 1.7.2**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22import%20something%20from%20%27something%27%5Cn%5Cn(()%20%3D%3E%20%7B%5Cn%20%20something()%5Cn%7D)()%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Atrue%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Afalse%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--no-semi
```

**Input:**
```jsx
import something from 'something'

(() => {
  something()
})()

```

**Output:**
```jsx
import something from "something"

;(() => {
  something()
})()

```

**Second Output:**
```jsx
import something from "something"
;(() => {
  something()
})()

```

**Expected behavior:**

The second invocation of Prettier should return the same as the first invocation.

**Comment by Conduitry** [comment] 2017-09-30 20:47
This also happens with other statements that must begin with an open parenthesis, such as object destructuring without variable declaration.

[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22let%20a%5Cn%5Cn(%7Ba%7D%20%3D%20b)%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Atrue%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Afalse%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Comment by azz** [comment] 2017-10-01 03:07
Closing as a duplicate of #1510

**Closed by azz** 2017-10-01 03:07 UTC
Labels: bug
