### ISSUE TITLE
Ugly positioning of logical operators

### ISSUE THREAD

**Issue by ackvf** [prettier/prettier#5932] opened 2019-03-01 14:52 UTC
Positioning logical operators and brackets at the end of lines makes the code pretty unreadable, since each logical operator is at different position and blocks start ad hoc without context. One then needs to scan the whole code to understand dependencies and the flow.

Before:
![image](https://user-images.githubusercontent.com/2313018/53645056-55fd2780-3c38-11e9-8857-450668bc4acc.png)

![image](https://user-images.githubusercontent.com/2313018/53644967-2817e300-3c38-11e9-9f94-4e09520b3d03.png)
Here in this example the code is structured quite well. It is apparent from the use of brackets that there are two blocks `A` and `B` as well as their relationship. Moreover, it is clear that block A consists of a logical chain.

After:
![image](https://user-images.githubusercontent.com/2313018/53645332-f6ebe280-3c38-11e9-8bb4-9d30e17dbe00.png)

![image](https://user-images.githubusercontent.com/2313018/53645324-eb98b700-3c38-11e9-967f-f0e0d1b08652.png)
This code turns everything on its head. It looks like a sequence of some statements, that start looking like an **Array**. Block `B` starts out of nowhere and it is **absolutely necessary** to scan the code and find that there are actualy two blocks, because it looks as a single block of code. Logical operators of the first blocks's chain are scattered through the code and hard to find.

**Input:**
```jsx
            {
              ( comments[0]
                && comments[0].type === CommentTypeEnum.STATUS_MESSAGE
                && comments[0].text === RequestStateEnum.OPEN
              ) || <InfoMessage date={createdAt} text={t('request.userSubmittedReq')} />
            }
```

**Output:**
```jsx
            {(comments[0] &&
              comments[0].type === CommentTypeEnum.STATUS_MESSAGE &&
              comments[0].text === RequestStateEnum.OPEN) || (
              <InfoMessage date={createdAt} text={t('request.userSubmittedReq')} />
            )}
```

**Comment by kachkaev** [comment] 2019-03-01 14:59
Duplicate of https://github.com/prettier/prettier/issues/3806

**Comment by lydell** [comment] 2019-03-01 19:53
Duplicate of #3806

**Comment by lydell** [comment] 2019-03-01 19:54
Duplicate of #3806

**Closed by lydell** 2019-03-01 19:53 UTC
