### ISSUE TITLE
Markdown italicized links ending changed to "\_"

### ISSUE THREAD

**Issue by whyboris** [prettier/prettier#14141] opened 2023-01-08 18:45 UTC
**Prettier 2.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAFO8BOACAygSygHM4cAKARgE4B2AVgEoA6bAfQG0BBKfAWwEMANtgAy+AEal+MfNAC6ZADwALGDAAOAZyQB6HQiYB3fAGt86uABN8-JhExEdxszu58hrMZMzTZUVmTiEBAmDAB8DKxMADpQ6Fh4hCTk1PTMbFw8AsJeUjLyZKoa2noGzuZWNnYOTqb4rlkeuT75-oHBoZExUCAANCAQ6q2ayKD8mJgQhqjjCCMoQob8AJ4j-eI+YCYYuPy8cGJQcMgAZkKacOub2zC46vxgScgwmACulyBwvJKWllYi-GIr34JAAYvYBGongtXjAIH0QKpeIIAOrKfDwTT3MBwXBzDH4ABuGOWyHAmjWIEIF0wMFQPiIAlO5w+ACtNAAPAjEQRwACKrwg8GZggu-XumBpZIEmBMlimPXFmEIMBR+EsMGUyAAHAAGJUQC4onzqMnqTBwGmE479ACOgvg9MG8xA-E0AFojlYrAiLfb8Bb6SCmUgzqKPhdePhnm8I0leZw1MrxLC4OhMIdjqGWf1NPH+Q6s2GxSAYPxxGqNVqkAAmfovfj4QRJADCEF4Ic+mjoCNeFwAKuX5sWPoT3gBJKB-WC4MDKobcSy4GDLXkii4AXw3QA)

```sh
prettier --write .
```

**Input:**

```md
Peter Singer (1975). _[Animal Liberation](<https://en.wikipedia.org/wiki/Animal_Liberation_(book)>)_.
Peter Singer (1975). _[Animal Liberation](https://en.wikipedia.org/wiki/Animal_Liberation_(book))_.
```

**Output:**

```md
Peter Singer (1975). _[Animal Liberation](<https://en.wikipedia.org/wiki/Animal_Liberation_(book)>)\_.
Peter Singer (1975). _[Animal Liberation](https://en.wikipedia.org/wiki/Animal_Liberation_(book))\_.
```

Notice the `\` before the closing `_` -- should just be `_` instead of `\_`

Problem persists even when I remove the `<` & `>` around the link.

**Expected behavior:**

_no change to input_

```md
Peter Singer (1975). _[Animal Liberation](<https://en.wikipedia.org/wiki/Animal_Liberation_(book)>)_.
````

**Comment by thorn0** [comment] 2023-01-12 17:08
Duplicate of #6112

**Closed** 2023-01-12 17:08 UTC
Labels: type:duplicate
