### ISSUE TITLE
Tab width should not affect text alignment after the bullet points in Markdown lists

### ISSUE THREAD

**Issue by borekb** [prettier/prettier#5019] opened 2018-08-26 13:45 UTC
This is a nested list as given in [CommonMark tutorial](https://commonmark.org/help/tutorial/10-nestedLists.html):

```
* Item
    1. First Subitem
    2. Second Subitem
* Item
    - Subitem
    - Subitem
* Item
```

It is formatted like this with `--tab-width=4` (four is a [safer value](https://babelmark.github.io/?text=*+Item%0A++++1.+First+Subitem%0A++++2.+Second+Subitem%0A*+Item%0A++++-+Subitem%0A++++-+Subitem%0A*+Item) than [two](https://babelmark.github.io/?text=*+Item%0A++1.+First+Subitem%0A++2.+Second+Subitem%0A*+Item%0A++-+Subitem%0A++-+Subitem%0A*+Item)):

```
-   Item
    1. First Subitem
    2. Second Subitem
-   Item
    -   Subitem
    -   Subitem
-   Item
```

([Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqABASXgWwDpTpHoCMAdOgGICWATgM4zoDKArgEbW4HHoBMFZnEhQAJiw5c4+KBmzSexALQTO3QstVSZc3CAA0ICAAcY1aPWSgAhrVoQA7gAVbCSymsA3CNVEGQ7LTWYADWcDDMxsHUUADmyDC0rHCGMfRwtDBOQbE41sgAZtYANumGAFb0AB4AQkGh4czWOHAAMjFwhSVlIFEMGcggebQhoo5Q-sa0MTAA6r4wABbIABwADIZTEOmzQcaDU3DptJ6dhrRwAI6sdHDZ1rn5SEWlKSDpONQJSW-0MbHFOAARVYEHgXVehhg1nY81ES2QABYoUFqMV-gBhCA4PKDKDQM4gVjpAAqMPcL3SAF8qUA))

I expected this output (just `*` replaced with `-`):

```
- Item
    1. First Subitem
    2. Second Subitem
- Item
    - Subitem
    - Subitem
- Item
```

Reasoning:

- It's the natural form in which nested lists are written.
- I believe it would be less work for Prettier.
- It is similarly easy to look at. There will be personal preferences here but I don't think Prettier generally worries about _beautification_ too much, as long as the code is "correct" (whatever that means in Markdown), reasonably formatted and consistent with common practices.
- It feels illogical to me to apply `--tab-width` both before and after the bullet, also, there is an internal inconsistency when setting tab width greater than 5 as you can see in [`--tab-width=5`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqABASXgWwDpTpHoCMAdOgGICWATgM4zoDKArgEbW4HHoBMFZnEhQAJiw5c4+KBmzSexALQTO3QstVSZc3CAA0ICAAcY1aPWSgAhrVoQA7gAVbCSymsA3CNVEGQ7LTWYADWcDDMxsHUUADmyDC0rHCGMfRwtDBOQbE41sgAZtYANumGAFb0AB4AQkGh4czWOHAAMjFwhSVlIFEMGcggebQhoo5Q-sa0MTAA6r4wABbIABwADIZTEOmzQcaDU3DptJ6dhrRwAI6sdHDZ1rn5SEWlKSDpONQJSW-0MbHFOAARVYEHgXVehhg1nY81ES2QAFYoUFqMV-gBhCA4PKDKDQM4gVjpAAqMPcL3SAF8qUA) vs. [`--tab-width=6`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqABASXgWwDpTpHoCMAdOgGICWATgM4zoDKArgEbW4HHoBMFZnEhQAJiw5c4+KBmzSexALQTO3QstVSZc3CAA0ICAAcY1aPWSgAhrVoQA7gAVbCSymsA3CNVEGQ7LTWYADWcDDMxsHUUADmyDC0rHCGMfRwtDBOQbE41sgAZtYANumGAFb0AB4AQkGh4czWOHAAMjFwhSVlIFEMGcggebQhoo5Q-sa0MTAA6r4wABbIABwADIZTEOmzQcaDU3DptJ6dhrRwAI6sdHDZ1rn5SEWlKSDpONQJSW-0MbHFOAARVYEHgXVehhg1nY81ES2QADYoUFqMV-gBhCA4PKDKDQM4gVjpAAqMPcL3SAF8qUA).
- As a small bonus, the new formatting would be compatible with markdownlint.

I know that nested lists are one of the trickiest parts of Markdown so maybe I'm missing some non-obvious reason why list texts are aligned the way they are. If that was a purely aesthetic decision, I wanted to create this issue as a counter-argument as I believe simplicity and consistency are generally preferred in Prettier over attempts at beautification.

(As a side note, I ran Prettier over hundreds of Markdown files in our repo and it did a _great_ job overall, better than I expected. That is admirable with virtually zero config options. 👍)

**Comment by kachkaev** [comment] 2018-08-26 14:33
@borekb you can make tab width = 2 in your markdown files while everything else uses 4:

```js
{
  "tabWidth": 2,
  "overrides": [
    {
      "files": "*.md",
      "options": {
        "tabWidth": 4
      }
    }
  ]
}
```

Forcing markdown tab width to be 2 will create unnecesssry diffs for those who have been usfing 4 already.

**Comment by borekb** [comment] 2018-08-26 14:49
@kachkaev sorry, I'm probably missing your point. We already have Markdown files with 4-space indentation in our repo but running them through Prettier adds additional spaces _after_ the bullet symbols (`-`) which is the issue reported in the original post.

**Comment by kachkaev** [comment] 2018-08-26 15:10
Ah I see now. I thought you wanted to have four spaces everywhere, but use two in markdown files.

**Comment by ikatyang** [comment] 2018-08-27 09:45
They're siblings not key/values, what would you expect the output for the following case:

```md
* Multiline content
  Multiline content

    1. First Subitem
    2. Second Subitem

  Multiline content
  Multiline content

1. Multiline content
   Multiline content

    - Subitem
    - Subitem

   Multiline content
   Multiline content
```

IMO, the only possible output would be to align every items in the list.

I think the issue here is that

- unordered list shouldn't always be marked as aligned (ref: #4893), we should have a better way to detect it, and
- the inconsistent behavior for `--tab-width=5` and `--tab-width=6`, we currently just ignore the alignment that'll cause invalid output (to become indented codeblock), and the valid max alignments for ordered list and unordered list are different.

**Comment by anishmittal2020** [comment] 2018-10-26 05:54
Any activity on this?

**Comment by tjconcept** [comment] 2018-10-28 14:49
@anishmittal2020 I guess you're free to submit a pull request.

**Comment by borekb** [comment] 2019-03-02 16:04
I'm setting up Markdown formatting & linting for a project after a while and have the following observations related to this:

I tried going with the default 2-space indentation but it really doesn't work well in practice, for example, when I have this unordered nested list:

```md
- Item
  - nested
```

and just change the top-level to ordered list:

```md
1. Item
  - nested
```

it breaks (I would have to also add one space before the nested bullet).

Four spaces are much easier to work with in an editor but also unfortunately, lead to a bad formatting by Prettier due to this issue. The example above would be formatted as:

```md
-   Item
    -   nested
```

which is a bit ugly and also makes markdownlint unhappy.

I don't think this has a good solution until Prettier's behavior is changed so for now, we'll have to omit it from our workflow around Markdown files.

**Comment by ryul1206** [comment] 2019-06-16 12:51
Hello, I have the same problem with @borekb.
My Vscode is ver.1.35.1 and Prettier is ver.1.9.0.

![prettier-formatting](https://user-images.githubusercontent.com/19263912/59564266-a2516380-907f-11e9-9543-059306a318ef.gif)

**Comment by Stanzilla** [comment] 2019-12-09 11:48
Is there a good workaround for this?

**Comment by trusktr** [comment] 2021-03-06 00:54
This is a bit annoying: I never write markdown by hand the way Prettier does, and I've never seen anyone else do it by hand that way, and I've never had any issues formatting markdown by hand _not_ using the style Prettier uses.

**Comment by glen-84** [comment] 2021-03-14 14:05
@ikatyang,

Are you able to fix this? It's the only thing preventing us from using Prettier for Markdown. 😞

I could try updating `isAligned` to handle unordered lists similarly to ordered lists, but I really don't understand the logic, like:

```md
11. 123
12. 123
```

... being considered "aligned", but:

```md
1. 123
2. 123
```

... not.

Also, there appear to be bugs with ordered lists as well, even with 2-space indentation:

```md
1. a
    1. b
    2.     c
```

`->`

```md
1.  a
    1.  b
    2.      c
```

... why the spaces in front of `a` and `b`? Why is there 4-space indentation?

**Comment by thorn0** [comment] 2021-03-15 00:00
I've closed #10508 in favor of this issue. Please see the discussion there too.

**Comment by thorn0** [comment] 2021-03-15 00:16
I think what probably can be done here to make everyone happy is to avoid adding the spaces after the marker if 

- the first child of the list item is a paragraph, and
- this paragraph fits on one line

If we can prove this is safe and won't break anything, then let's do it.

**Comment by noahbrenner** [comment] 2021-03-15 04:47
Here are a few things I gathered from the spec:

- There may be 1--4 spaces between the list marker and its content (see the **Basic case** list item in [this section](https://spec.commonmark.org/0.29/#list-items)). No specific size in that range is recommended and it is not explicitly correlated with indent size.
- All of the examples showing correct formatting for nested lists use 1 space after the marker, even though they use different amounts of indentation up to the list markers themselves. You can see these starting at [Example 264](https://spec.commonmark.org/0.29/#example-264) (2 space). Also see 266 (4 space), 267 (3 space), 268 & 269 (nested on one line), and 270 (list containing headings as the first child of list items).
- [Example 256](https://spec.commonmark.org/0.29/#example-256) Demonstrates that indentation within a list item is measured from the first non-space character after the list marker, regardless of the number of spaces between the list marker and that first non-space character.

From what I can see, it's not *incorrect* to add more than one space after the list marker (as Prettier currently does for 3-4 space indents), but it *is* a break from the most common convention within their docs (and what I've seen anecdotally) of using one space. The current behavior also conflates indentation with the spacing after the list marker, which the spec does not imply, to my understanding. I'm in support of consistently using exactly one space between a list marker and its first child, regardless of `--tab-width`, with only 2 exceptions:
- Empty list items, which should have no trailing spaces.
- List items that start with an indented code block, as shown in [Example 243](https://spec.commonmark.org/0.29/#example-243). But actually, this *isn't* an exception -- the code block should be indented 5 spaces: 1 to separate the list marker from its content and 4 to represent the indented code block.

**Comment by polarathene** [comment] 2021-03-15 05:08
> Also let's stop bringing up `tabWidth > 4`. It isn't used in practice, so no point in discussing it.

The point of that being brought up is Prettier reduces content alignment padding to the minimum (eg 1 space), this expected output could apply to the earlier tab width sizes as well.

As stated in the issue I raised (and demonstrated), there is no benefit to the padding incrementing as Prettier does, and was likely an accidental side-effect from the PR that added the tab-width support in the first place. Or a misunderstanding of not handling indentation and alignment differently.

Markdown:

```markdown
2050. Unrealistic list item size (2050th item). Github is rendering at 1st list level as number, but due to `padding-left` CSS has clipped the 4th digit out of the elements bounds (overflowing).

---

-  2 space padding

      2050. Unrealistic list item size (2050th item). The following list item below is recognized as list item up to additional padding of 3, regardless of length as at 4 spaces it will be considered indented code block. This is a long line that wraps flow onto mult-line content but otherwise has no effect on below content. This list item is child content for the `2 space padding` list item above, it is a list that has been defined, but has excess padding (beyond the two spaces after `-` that defines the start of the content column where the value `2 space padding` begins or rather is aligned to).

               This excess padding for content can be up to 3 spaces from the list items content root (min alignment), exceeding that naturally defines an indented code block as per content receiving 4 spaces of indentation.

            This is the minimum position for the 2nd level, whilst the prior paragraph was the maximum before becoming an indented code block. The text column for this minimum position is dependent on the list item declaration the content belongs to. If the `2050.` list declaration was shorted to `250.` or reset from `1.`, the content column position is shifted/affected.

            If this line were to remove a space prior to `If`, it would become an indented code block, belonging as content to the `2 space padding` list item. Likewise, if the padding after the list item declaration `-` is increased, it shifts the content column to align child content against.

            Add an additional padding space to `2050.` and notice this min aligned content will become an indented code block due to now belonging to `2 space padding` list item.

            Adjust the list number from `2050.` to `250.` and witness that the `This excess padding..` content will become an indented code block. You'd need to prepend a space to pad the list number declaration, shifting the content column for it's children, or remove a padding space from the `This excess padding..` line.

            Thus these lines of content are not purely indentation. They are indentation to the list item + alignment padding to where the content column starts.

            Padding a value to try shift the content column to align with tab width is the wrong approach as this becomes inconsistent with ordered lists when the number of digits increases. Formatting of numbered lists is correct, and has variable mix of indentation + alignment padding to accommodate.

      2050. Repeated `2050.` number value. Github doesn't enumerate from 1, but will enumerate from the base number of the ordered list. Results in 2051st value in roman numerals.

            Content at min alignment.  Aligned to the list item, which itself was padded (`-  ` 3 characters, + 3 spaces of padding from this content column to match the first `2050.` list item declaration alignment, then the content starts 6 additional spaces in, accounting for the `2050. ` characters which defines this list items content alignment at 12 spaces in.

               Content at max padding (+3 spaces)

                (1 more space beyond that causes an indented code block)

      5. this is the last nested list item, the `5` will become `2052` in roman numerals.
-   Original list resumes
- Despite padding for the value being different at 3 and 1 spaces.
```

Rendered on Github:

2050. Unrealistic list item size (2050th item). Github is rendering at 1st list level as number, but due to `padding-left` CSS has clipped the 4th digit out of the elements bounds (overflowing).

---

-  2 space padding

      2050. Unrealistic list item size (2050th item). The following list item below is recognized as list item up to additional padding of 3, regardless of length as at 4 spaces it will be considered indented code block. This is a long line that wraps flow onto mult-line content but otherwise has no effect on below content. This list item is child content for the `2 space padding` list item above, it is a list that has been defined, but has excess padding (beyond the two spaces after `-` that defines the start of the content column where the value `2 space padding` begins or rather is aligned to).

               This excess padding for content can be up to 3 spaces from the list items content root (min alignment), exceeding that naturally defines an indented code block as per content receiving 4 spaces of indentation.

            This is the minimum position for the 2nd level, whilst the prior paragraph was the maximum before becoming an indented code block. The text column for this minimum position is dependent on the list item declaration the content belongs to. If the `2050.` list declaration was shorted to `250.` or reset from `1.`, the content column position is shifted/affected.

            If this line were to remove a space prior to `If`, it would become an indented code block, belonging as content to the `2 space padding` list item. Likewise, if the padding after the list item declaration `-` is increased, it shifts the content column to align child content against.

            Add an additional padding space to `2050.` and notice this min aligned content will become an indented code block due to now belonging to `2 space padding` list item.

            Adjust the list number from `2050.` to `250.` and witness that the `This excess padding..` content will become an indented code block. You'd need to prepend a space to pad the list number declaration, shifting the content column for it's children, or remove a padding space from the `This excess padding..` line.

            Thus these lines of content are not purely indentation. They are indentation to the list item + alignment padding to where the content column starts.

            Padding a value to try shift the content column to align with tab width is the wrong approach as this becomes inconsistent with ordered lists when the number of digits increases. Formatting of numbered lists is correct, and has variable mix of indentation + alignment padding to accommodate.

      2050. Repeated `2050.` number value. Github doesn't enumerate from 1, but will enumerate from the base number of the ordered list. Results in 2051st value in roman numerals.

            Content at min alignment.  Aligned to the list item, which itself was padded (`-  ` 3 characters, + 3 spaces of padding from this content column to match the first `2050.` list item declaration alignment, then the content starts 6 additional spaces in, accounting for the `2050. ` characters which defines this list items content alignment at 12 spaces in.

               Content at max padding (+3 spaces)

                (1 more space beyond that causes an indented code block)

      5. this is the last nested list item, the `5` will become `2052` in roman numerals.
-   Original list resumes
- Despite padding for the value being different at 3 and 1 spaces.

**Comment by polarathene** [comment] 2021-03-15 05:09
Another shorter example:

```markdown
- A

  999. A
    hello
  2. B
  world
  3. C
  
  - B
  
    content
  - C
    - D
```

Prettier output:

```markdown
-   A

    999. A
         hello
    1000. B
          world
    1001. C

    -   B

        content

    -   C
        -   D
```

**Comment by polarathene** [comment] 2021-03-15 05:28
> Here are a few things I gathered from the spec

For what it's worth, probably most users needing 4 space indents when it's not a preference is due to markdown parsers that aren't using CommonMark. The spec differs AFAIK, as the maintainer of Python Markdown would cite the markdown spec as not supporting 2 space indents, and refusing to accommodate users despite how common and preferred it is to use two space indentation.

**Comment by JosephTLyons** [comment] 2021-07-14 17:33
Came across this bug today, any updates on a fix?

**Comment by harveyr** [comment] 2021-09-09 15:21
I _love_ Prettier for JS/TS/JSON, and I want to propose it to my team for Markdown! But I don't feel I can until this is resolved. Subscribed and hoping for a fix. Thank you!

**Comment by haoadoresorange** [comment] 2022-02-23 02:27
This should be closed since it's not a bug and I find the current behaviour the best compromise right now. See #3990 for context.

**Comment by polarathene** [comment] 2022-02-23 04:23
> This should be closed since it's not a bug

**Disagree** :-1: 

What benefit do unordered lists receive when you have a tab width of 4, to receive unnecessary content padding?

What is wrong with an option to explicitly opt-out?

> See #3990 for context.

Are you referring to the [referenced comment about indenting for the benefit of ordered (numbered) lists](https://github.com/prettier/prettier/issues/3459#issuecomment-366382620)?:

> _Overall, I think it'd be more reasonable to offset both numeric and bullet-point lists by four characters. This way the markdown's source looks clean, GItHub's and GitLab's previews are happy and text indentation in editors is guaranteed to work._

**EDIT:** Watched the animated example in the PR you linked,  which illustrates the intent to align/pad list content due to ordered lists. Note that another issue points out that it's [padding is tailored around double-digit ordered lists](https://github.com/prettier/prettier/issues/4281) (but it's actually the tab width).

---

I raised an issue that was closed/locked as a duplicate to this one, it clearly illustrates that [the current Prettier functionality differs at larger tab widths](https://github.com/prettier/prettier/issues/10508#issuecomment-798997051). There is no need / benefit to increase padding with the tab-width, and then collapse it down to 1 at larger pad widths..?

The padding should be optional, especially when it makes no difference to the rendered result.

Some extra snippets from my linked issue:

> - Content after the list `-` is being indented by `<tab-width> - 1`, it should instead remain as a single space.
> - At `--tab-width 6` and above this will result in the padding always being the expected single space.

---

Using the [playground example that the PR you cited addresses](https://github.com/prettier/prettier/issues/3459), when padding is increased to 6+, and you swap one of the nested code blocks to a nested list item instead; you'll notice that the list item collapses to a single space, while the code block is aligned to that to preserve any leading white-space.

If you reduce the tab width to 4, the list items will all pad the content unnecessarily, the only benefit would be for alignment/diff with ordered lists (the other benefit discussed in the issue/PR you mentioned). [Which as shown earlier in this thread](https://github.com/prettier/prettier/issues/5019#issuecomment-799094562), isn't necessarily consistent for an ordered list anyway. The PR only applies it for ordered lists when tab width is 2, for other tab widths (3, 4, 5) it applies the padding logic to any list including unordered (_on the off chance you make a change to an ordered list to reduce diff noise.._).

**Comment by JosephTLyons** [comment] 2022-02-23 04:46
> This should be closed since it's not a bug and I find the current behaviour the best compromise right now. See #3990 for context.

Whether its bug or not, the current functionality makes very little sense at all.

**Comment by haoadoresorange** [comment] 2022-02-24 00:25
> What is wrong with an option to explicitly opt-out?

Optionally opting-out has never been the philo of prettier I think, since it is _opinionated_, that means between respecting tabWidth and not respecting we gotta choose one.

In that regards, even though I agree that it's a little bit ugly adding 4 spaces after the bullet points, it makes indenting in vscode _way_ less painful. So if I have to chose one, respecting when `tadWidth=4` is a good tradeoff to me, thus I said it's the best compromise.

With `tabWidth=6` it's not _a little bit_ ugly anymore, so that might be reconsidered :-??

**Comment by polarathene** [comment] 2022-02-24 01:17
> Optionally opting-out has never been the philo of prettier I think, since it is _opinionated_, that means between respecting tabWidth and not respecting we gotta choose one.

Prettier offers config options, it's generally opinionated but there are situations where it allows a bit of flexibility.

I rarely if ever have had any UX problems thinking "gee, indenting my list item content sure is frustrating!" (_and this is without Prettier involved_). Yet I often write markdown lists where Prettier wants to pad content for no valid reason (_removing that padding afterwards is frustating, otherwise just putting up with it and accepting the wasted valuable horizontal space lost, or avoiding Prettier entirely on markdown.._).

I'm not quite sure why the indenting list content is even relevant if I'm wanting Prettier to format an entire markdown document (_CI for contributions to docs on github_).. Especially since it doesn't care at the larger tab widths, and happily keeps the padding at a sensible 1 space from the marker column.

If I want editor DX, I would expect the editor to understand the language syntax for context and when the scope transitions from indentation to alignment/padding.

---

Indentation of the list marker remains consistent to the tab width regardless, after that it's 1 space from the marker needed for the list item content to be aligned to. I understand the concern with multi-line list item content with editor indentation (and avoiding any padding/alignment by matching tabwidth for indentation alone..

The Prettier logic is only justified AFAIK for when you indent a list into another within an editor, and **expect Prettier to fix the editor failing to indent a markdown list appropriately**:

![indent_example](https://user-images.githubusercontent.com/8341033/38464357-2b7766b0-3b3f-11e8-882f-b667d541da9d.gif)

I don't consider that tradeoff worth it to enforce when the majority of markdown documents won't run into that situation. Sounds like something you'd opt-in for (_a niche workaround for an editor bug that didn't indent a list in a pre-existing document correctly_), but I'd be just as happy with an opt-out, as would all the other supporters of this issue (greater than that of the one that Prettier addressed and enforced on everyone else unaffected).

**Comment by saidelike** [comment] 2023-02-07 16:01
I have the same "extra space after bullet point" problem with vscode 1.74.1 and prettier 9.10.4.

Are we all using vscode for people having the problem? It seems the same problem is for another extension in vscode which is this one https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-remark (have a look at the gif on top of the link). So it makes me wonder if the problem is due to vscode on top of prettier.

Anyway, it should be possible to disable that in prettier using a config parameter, if the author wants to keep it for specifications reasons, but it is really annoying for people not wanting this. The specification can be stupid sometimes so worth having flexibility please!

We are many users not able to use prettier for markdown because of that simple bug :(

**Comment by noahbrenner** [comment] 2023-02-08 07:10
I don't think this relates to vscode. I use prettier either directly via the CLI command in a git hook or with a vim plugin. The behavior is from prettier, so it doesn't matter what integration you use for it.

**Comment by mawkler** [comment] 2023-02-21 07:51
I've also suddenly started getting four character indent on bulleted lists. I'm on version 2.8.4.

**Comment by Jaeiya** [comment] 2023-02-21 21:33
I just recently started using a larger tab width (4) for my code and stumbled into this bug.

**Comment by ChristopherHaws** [comment] 2023-04-11 22:28
This issue also affects `.mdx` files. I want my `.mdx` files to use 4 spaces as the tab width but I want bullet points to be normal but prettier adds indentations to the bulleted list. Switching the tab width to 2 would make the file look different from all our other code.

**Comment by ryanewtaylor** [comment] 2023-08-21 18:19
I just stumbled into this bug myself. We are migrating from Bitbucket Server which supports CommonMark to Bitbucket Cloud which uses [Python-Markdown](https://python-markdown.github.io). Our sub list items were rendering incorrectly after the migration because [Python-Markdown requires four spaces](https://python-markdown.github.io/#differences) to create nested list items and we had just been using two.

I figured we could use prettier to reformat this for us cleanly so I modified my prettier configuration like so

```json
{
  "overrides": [
    {
      "files": "*.md",
      "options": { "tabWidth": 4 }
    }
  ]
}
```

This results in the following

```markdown
<!-- Before Prettier -->
- item
  - sub
  - sub
- item
  - sub
  - sub
```

```markdown
<!-- After Prettier -->
-   item
    -   sub
    -   sub
-   item
    -   sub
    -   sub
```

As others have noted there is extra padding between the bullet and the content that is unexpected. This does not seem to happen with order listed of when unordered sub list items are part of an ordered list..

```markdown
<!-- Before Prettier -->
1. item
   - sub
   - sub
2. item
   - sub
   - sub
```

```markdown
<!-- After Prettier -->
1. item
    - sub
    - sub
2. item

    - sub
    - sub
```

Note also that the extra line introduced after `2. item` despite the input specifying a tight list.

**Comment by zhenyulin** [comment] 2023-08-24 14:53
Having the same issue here, and suspect this might be due to SmartTabs feature in Prettier, so wondering if there's an option to turn that off?

**Comment by MartenBE** [comment] 2023-10-07 21:07
Is there any update on this? Top hit websites for markdown show the requested formatting (4 indent spaces, single space between marker and list item) as examples. E.g.

- https://www.markdownguide.org/basic-syntax/#unordered-lists
- https://commonmark.org/help/tutorial/10-nestedLists.html

It is weird that prettier deviates from these examples. It also really fights with markdownlint ( https://github.com/DavidAnson/markdownlint/blob/main/doc/Prettier.md )

**Comment by TomasLudvik** [comment] 2023-10-20 13:32
I have created a fix for this issue at https://github.com/prettier/prettier/pull/15526

**Comment by GitMurf** [comment] 2024-08-02 00:05
Really hoping this gets fixed soon. Took me forever to figure out what the problem was! Looks like a PR is close to being approved here: #15526

**Closed** 2024-09-27 11:58 UTC
Labels: type:bug, help wanted, lang:markdown

**Comment by marcospgp** [comment] 2024-12-15 19:32
This issue is closed but I am still able to reproduce it in vscode

prettier formats markdown from

```md
- one
- two
```

to

```md
-   one
-   two
```

if the tab width setting is set to 4 instead of the default of 2.

on latest version of prettier vscode extension

<img width="934" alt="image" src="https://github.com/user-attachments/assets/f76d26b6-e319-410a-8ce8-e2da33ef11be" />

**Comment by Nerixyz** [comment] 2024-12-15 19:44
> This issue is closed but I am still able to reproduce it in vscode

The VSCode extension doesn't use the 3.x version: https://github.com/prettier/prettier-vscode/issues/3142 - you need to install a version of prettier in your workspace locally.
