### ISSUE TITLE
Inline styles in html are not formatted

### ISSUE THREAD

**Issue by avalanche1** [prettier/prettier#6905] opened 2019-11-09 18:30 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6UqAEvgLIAy5u3AQQDKQgLxMQUCAFoAVgGdyNQtNx0B8oROZRy5VACMIAEwCeOvXtTEGbOHToRyAdwgAnOsfSoAQgCUGcnxKAEtFMPIOHgBWch8IELo4NwAHOgBDeAA6VAB6GxZLfWMQgDdCovIQ43EQARSUiQqi+RhTJNqS+TT00yRyADMkgA8AbmbK9LoQgHMoaRD4Gnl+sAR4N3HdSr1KOFnqfoBGAAYT0sotnb0U9OMSqBn+k6zouBor8gN0sABrGbcEAArlBjNJII43P0SjQAb0tiwmtsigw8iVShZ9LkjGYdHkotwGCAADQgCApGAhaDyZCgdJuQHOYj0hA0lDpUoJYwkkAGNw-X5wGBCW5gEKPZAwNxAuCk6j0ADqoXg3R+cCErMWZUWpmQ4HkNNJ4vkyRgxH5Mxo6WQAymJtJCmGPn5fyFQnSNDg3HFcBtdtlIEdQnFMySAEUgRB4H66PaQLc3Ca3Hr5XQeSk3OKYArqjBKMgABwnUkZiAmhX8lJ6jNwJOlX2kgCOkfg5vJbJA6Xk0igcDgxn7PLccGbIWH5vSlutSFtsYDJpoIUl0vnIfDLd9M-9pJg6QMOeMeeQACYd-zEiHcBAaFa9VJezygSb8Hu2bO46UZQBJUHrIRgTMKQEUEhDaJIYxNABfSCgA)

**Input:**
```html
<!DOCTYPE html>
<HTML CLASS="no-js mY-ClAsS">
  <body>
    <div
      id="App"
      style="display: flex;
        align-items: center;
        height: 100vh;
        padding: 0.5em;
  background-color: dimgray;

"
      ></div>
  </body>
</HTML>
```

**Output:**
```html
<!DOCTYPE html>
<html class="no-js mY-ClAsS">
  <body>
    <div
      id="App"
      style="display: flex;
        align-items: center;
        height: 100vh;
        padding: 0.5em;
  background-color: dimgray;

"
    ></div>
  </body>
</html>
```

**Expected behavior:**
```html
<!DOCTYPE html>
<html class="no-js mY-ClAsS">
  <body>
    <div
      id="App"
      style="display: flex;
        align-items: center;
        height: 100vh;
        padding: 0.5em;
       background-color: dimgray;"
    ></div>
  </body>
</html>
```

**Comment by thorn0** [comment] 2019-11-09 18:39
Duplicate of #5479

**Closed by thorn0** 2019-11-09 18:39 UTC
