### ISSUE TITLE
[bug] wrongly added scss trailing commas

### ISSUE THREAD

**Issue by wenfangdu** [prettier/prettier#10146] opened 2021-01-27 01:11 UTC
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAzgBwIZjgJ3SQAIAKAHSmOIEYSAGAGkuoCYHmriBmDl4gCx8uAehHEArCQmYAHp2pja9EjXpyFxJTSm0Z8-ktYrixjZQCUAbkohGICJhgBLaOmShs+fBADuABS8EdxRsABtfbABPd3sAI3xcAGs4GABlHDBnKABzZBh8AFc4ezgAWzi4ABMq6oAZbFzC7By4ADEIfDLsGBdc5BBsQpgIOxAACxgysIB1ced4LFw4NOCF5wA3BaiBsHRYkGz0Ahh-RJzu5AAzcOP7ACt0WQAhRLAU9OwyuDrsuGvbiUQI9ZGlsjkwnAAIqFCDwAFhO4gHCEAgDdB7A6YfDZGAzZxVGDjZAADiYyJ8xxmiUwA2xcGO+A2-3sAEdYfAzo4QoN0ABaKBwarVMb4ODs5xis4tS5IG6IoHHMrOfJFRXgyEwuH-OWA+wwbBxfGE4lIVj6xLOMLggDCEDKspADIkY0KxwAKoaQvKkRtigBJKC1WBpMA4pwAQSDaRgUUhCOOAF9E0A)
```sh
--parser scss
```

**Input:**
```scss
$spacers: (
  1: 0,
  2: 0,
  3: 0,
  4: 0,
  // 5: 5px,
  // 10: 10px,
  // 15: 15px,
  // 20: 20px,
);

```

**Output:**
```scss
$spacers: (
  1: 0,
  2: 0,
  3: 0,
  4: 0,
  // 5: 5px,
  // 10: 10px,
  // 15: 15px,
  // 20: 20px,,
);

```

**Expected behavior:**
```scss
$spacers: (
  1: 0,
  2: 0,
  3: 0,
  4: 0,
  // 5: 5px,
  // 10: 10px,
  // 15: 15px,
  // 20: 20px,
);
```

**Comment by thorn0** [comment] 2021-01-27 01:16
Duplicate of #7752

**Closed** 2021-01-27 01:17 UTC
Labels: type:duplicate
