### ISSUE TITLE
Unstable output of some chained calls

### ISSUE THREAD

**Issue by mhofman** [prettier/prettier#8695] opened 2020-07-01 22:00 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAAgMwDYQDuAOlJFAM4wYCyAngGIQQBCAhgE4AqAFgJZQA5nQDCePgmoBeDAFcoAEzg4BcBQG5SpclQwBbCGADWAeRwYZACg5w2eJBjZQ6ASgsA+DDbuaopJRRgHHwARnCWAOT0TKyc7ABevAKCAEpwAI6ycFQRADQYlm5SnsCkGBh4cNQ2AA4QHDC+5ZXUQbbw0czsHAlJQmmZ2Y1aUOUBQaHhEQJ8MHkFRSVl5RizkbX1MBQYhDwIGDB7GDEY3Rhg4pKr2-JsAG5sfHhsIZXzhR4YpaMr5TrUcA4HHqFgwUDghAwAFEgfVIiFgUYEBEXE1fvpDKYcJZOrFuPwhKJLrAXAA6AzGACSehqlT0kjYMD40EsH2KX2W6IOPGBkMBwI4aN+AF9UZyVm1GXBcd1egTUhkslRCkKVnAAB41OBgGDWOB1BpkmAQAAS9zgLDgCAAMmwqCI7JUFAB1WY8Szi34Rfn1Uk4EJ+5ghTgAfWD8VJFwksBDtweTxeb1ynpWwB9HHy6Zo2QobEEcAcEQRECRUAiwpTYp+5VFaNrpHrUBAuRAEBqTOgFGQoE4vIACpwEF2UHZCGw6F2Wwi2MYqgBlGoz5LIGAcLItngwPR4Z38eAURdgOBzoezPh3WZ0ZDgCiTkACCiAmB9jh5vRsZA4OyPlsAKwo6osK+s4wHObD0taqift+cB-gBc7JJUACKsgQPA0F4D+ICLhwj4cNewZhHgzbYcEsCugohzIAAHAADC2NTAo+zqvjU16MdkgJ3HAJGZGhcAvm2w4gHaAC04JqGoJE2JkfA2C+b4fkgX6YbBICPnofArmuakUIhcAofxGFYTALwUVRSAAEwtqujziEIIgQHo77XtkACsJGyI+XAvMOKlYXcWSUookhzhM7YAIKKHOMB0JUxlwMKwpAA)
```sh
--parser babel
```

**Input:**
```jsx
// @flow
const MyFooBarThingyClient = undefined;

const mockOf = (real: any) => real;

describe('MyFooBarBazThingRequest', () => {
  let report;
  let createMyFooBarBazThingRequest;

  describe('init', () => {
    it('reports when the Foo Bar client is unavailable', () => {
      const error = new Error('broken');
      mockOf(MyFooBarThingyClient).mockImplementation(() => {
        throw error;
      });
      createMyFooBarBazThingRequest();
      expect(report).toHaveBeenLastCalledWith(
        'error.fb.foobar_baz.client_unavailable',
        {error, errorMessage: 'broken'}
      );
    });
  });
});

```

**Output:**
```jsx
// @flow
const MyFooBarThingyClient = undefined;

const mockOf = (real: any) => real;

describe("MyFooBarBazThingRequest", () => {
  let report;
  let createMyFooBarBazThingRequest;

  describe("init", () => {
    it("reports when the Foo Bar client is unavailable", () => {
      const error = new Error("broken");
      mockOf(MyFooBarThingyClient).mockImplementation(() => {
        throw error;
      });
      createMyFooBarBazThingRequest();
      expect(
        report
      ).toHaveBeenLastCalledWith("error.fb.foobar_baz.client_unavailable", {
        error,
        errorMessage: "broken",
      });
    });
  });
});

```

**Second Output:**
```jsx
// @flow
const MyFooBarThingyClient = undefined;

const mockOf = (real: any) => real;

describe("MyFooBarBazThingRequest", () => {
  let report;
  let createMyFooBarBazThingRequest;

  describe("init", () => {
    it("reports when the Foo Bar client is unavailable", () => {
      const error = new Error("broken");
      mockOf(MyFooBarThingyClient).mockImplementation(() => {
        throw error;
      });
      createMyFooBarBazThingRequest();
      expect(report).toHaveBeenLastCalledWith(
        "error.fb.foobar_baz.client_unavailable",
        {
          error,
          errorMessage: "broken",
        }
      );
    });
  });
});

```

**Expected behavior:**
Stable output

**Comment by fisker** [comment] 2020-07-02 09:45
Minimal 

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHOYYAoBOcGE+MAlAHQwQASAhgG5wBCcCAMnQM4wDCdAGwFwAJgHUAljAAWuADpQABIoDkcfPhIUAZgCMdECLrr4A+sYBeFMAIkIYpgK5RGdCQLq7hKgDQLlwOqa+D6KQSQAsnBcXHQA5nBIqrqaANYIKgC+CmQA3CA+IBAYMBLQXMigJpoA7gAKJggVKII1dACeFYUpdGDpMADKGL0SUHHIMPiOcIXSMAC2AmLSUtHDYHADTVISDFLtyOAxBSCjXOowdfjx83TI2oLnhQBWXGjM131wg3TzcOyjOD3R4zECvNADUZxYQARUcEHgwIETxAw3w53wh2MujgAhOGHwoxgkhEMmQAA4AAyFAkQc5ia4YQ4E6LqJgnACO8PgV2KzRA3AAtFA2CJRCdCFyJIQrjc7kgHsjQed5hIJlNlVDYdygQqQYUYJ4SWSkAAmA3XdxQ3gQea3Q7RACsJ0c5wAKp5moqUQxpgBJKBi2ADMCEkoAQUDAxg7WESPOmUyQA)
```sh
--parser babel
```

**Input:**
```jsx
expect(report).toHaveBeenLastCalledWith(
  'error.fb.foobar_baz.client_unavailable',
  {error, errorMessage: 'broken'}
);
```

**Output:**
```jsx
expect(
  report
).toHaveBeenLastCalledWith("error.fb.foobar_baz.client_unavailable", {
  error,
  errorMessage: "broken",
});

```

**Second Output:**
```jsx
expect(report).toHaveBeenLastCalledWith(
  "error.fb.foobar_baz.client_unavailable",
  {
    error,
    errorMessage: "broken",
  }
);

```

**Comment by thorn0** [comment] 2020-07-02 09:48
Duplicate of #2803

**Closed by thorn0** 2020-07-02 09:48 UTC
Labels: lang:javascript, type:bug
