### ISSUE TITLE
Consider disabling the rule that removes 'unnecessary' brackets in basic operator expressions, or make it optional.

### ISSUE THREAD

**Issue by dvberzon** [prettier/prettier#7154] opened 2019-12-18 11:38 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEMIwIYA2AwhBpgLyYBmAlgB5wAmmA1JgBQC20MAFgQE9MAKkwBGAEwBKANwgANCAgAHGDXTJQeAE7aIAdwAKOhGmQg8ANwg1GCkACNteMAGs4MAMrKXNKAHNkGG0AVzhFXhhOAgB1Xhp4NB8wOE9TBJpLBIFzMDQzRT80OG0YQ2d-TjxkKkJixQArNDoAIWc3D088TjgAGT84GrrwkCa6Tz9-AjgARRDcQaRagnqQH21i7XMHPAc4AntlbT8YGNs+ZAAOAAZFI9I4GOdlcyO4TctBxQBHefhylRmFB4NAAWigcCYTHs2jgvxosPKeEq1SWw0UxU4NCCoRGaEm0zmCyGKxG+AcZ0YFyQEkUwTwNAIkxInCq5ig0C+IBCxQAKrsgctVpYwgBJKCMBBeMDHVQAQQlnhgAmmJOKAF91UA)
```sh
--parser babel
```

**Input:**
```jsx
const totalCost = fixed + (monthly * 12);
```

**Output:**
```jsx
const totalCost = fixed + monthly * 12;

```

**Expected behavior:**

Maintain the parentheses for readability.

There are many expressions that rely on knowledge of explicit operator precedence. While technically they are unambiguous, we have recently proven in a code readability experiment that adding parenthesis improves readability.

The example above was included in our experiment that A/B tested code snippets on developers, and directly measured how easily they read the code. The data showed that by adding parentheses, there was a statistically significant improvement in speed of reading the code and accuracy in understanding it.

The findings are available here:

https://howreadable.netlify.com/results/#operator-precedence

The rule appears to be based on https://eslint.org/docs/rules/no-extra-parens. I have separately requested that rule to be amended based on the results.

**Comment by evilebottnawi** [comment] 2019-12-18 11:48
Duplicate of https://github.com/prettier/prettier/issues/187

**Comment by thorn0** [comment] 2019-12-18 11:49
What if this improves readability only in simple expressions like this, but worsens it in complex expressions that already have a lot of parens?

**Closed by evilebottnawi** 2019-12-18 11:48 UTC

**Comment by dvberzon** [comment] 2019-12-18 12:02
@thorn0 

https://prettier.io/docs/en/comparison.html

Prettier tries not to be opinionated about code quality, so fixing the readability of complex expressions is outside the remit. I've opened a PR on the underlying es-lint rule, but I believe that the safest thing for prettier to do would be to maintain the parentheses added by the developer.

**Comment by dvberzon** [comment] 2019-12-18 12:07
@evilebottnawi 
I don't agree that this is a duplicate of #187 

That refers to the es-lint rule for https://eslint.org/docs/rules/no-mixed-operators.
This is about https://eslint.org/docs/rules/no-extra-parens

The two are related, but the discussion on the original issue diverged from the issue as stated

**Comment by evilebottnawi** [comment] 2019-12-18 12:13
We recommend disable all stylistics eslint rules, you can use https://github.com/prettier/eslint-config-prettier, we don't want change current output

**Comment by thorn0** [comment] 2019-12-18 12:14
You have it backwards. Prettier is an **opinionated** code formatter. Also it has nothing to do with ESLint and its rules. Not sure why you keep mentioning ESLint.

Prettier deals with the syntactic structure of the code, and parentheses just like whitespace aren't part of it. In [some cases](https://prettier.io/docs/en/rationale.html#multi-line-objects), Prettier does use the original formatting, but in general it tries to avoid resorting to that as much as possible. It's highly unlikely that we add more such exceptions.

**Comment by cecilemuller** [comment] 2019-12-18 16:39
Rule `no-mixed-operator` isn't about style, it's about catching unintentionally assuming the wrong precedence order, the same way semicolons at the end can be technically optional but still preferred for being explicit.

If you want to remove parenthesis, at least remove them only within the same precedence level.

**Comment by dvberzon** [comment] 2019-12-19 08:04
@thorn0 

I apologise for the references to ESlint. I can't find any documentation in prettier for the list of rules that are applied, so I took my queue from #187 which mentions no-mixed-operators. If this is actually a prettier rule then I apologise, I wasn't able to find it.

My understanding of prettier's philosophy was to be opinionated about style decisions - decisions which do not affect the quality of the code - and to NOT make any changes based on code quality. I took this from the documentation: https://prettier.io/docs/en/comparison.html (a link which by the way has many references to ESlint!)

The point I'm trying to make is that by removing parentheses, prettier is unintentionally affecting the quality of the code. Our results show that expressions which rely on operator precedence are more readable with parentheses.

https://howreadable.netlify.com/results/#operator-precedence

I agree that in these cases, the parentheses don't affect the syntactical structure of the code - much like whitespace. However, prettier would never consider removing line breaks and putting all the code on one line. it would massively reduce the code's readability (whilst still being syntactically correct). I'm asking for similar consideration with parentheses.

**Comment by thorn0** [comment] 2019-12-19 10:50
> I can't find any documentation in prettier for the list of rules that are applied

That's because Prettier is not a linter, so it doesn't have the notion of a rule. It's an AST printer that doesn't use the original styling except in a few cases where ignoring that original styling turned out to be too controversial.

> However, prettier would never consider removing line breaks and putting all the code on one line.

Oh, it would:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUAdKuAE+ARgIYBOANAcSQF4WGNPOOaYCOArgB4CUv1QVEK5eICiAgAHGAEtoAZ2ShyZCAHcACuQRKUJAG4RZAE3EgiZEmADWcGAGUp12VADmyGGU5wJACxgAWwAbAHU-WXgFZzA4B11I2QNIgE9kcAUlCVcFODIYTSs3QJJkVBJg3IkAKwVuACErW3sHEkC4ABlXODKKqpBa7gdXN2C4AEVOCHheyt8QZzJcsnTSIjhg8ykyVxhQ0xg-ZAAOAAYJbYhc0KspdO24ZYMeiS5puELpPRASBQBaKBwOAmYHmMhwLiycGFEjFUpIcpzCS5QKyTzeeYKEZjSbvWb9GAkIj7EyHZAAJgkXhIsmCIwAwhBAiV0lBoC8QJxcgAVIl6RH9Aw+ACSUBBsAcYB2MgAgmKHDAUmN8XAAL6qoA)

**Input:**
```jsx
foo(

  bar,
  baz,                 ((qux))
  
  
)
```

**Output:**
```jsx
foo(bar, baz, qux);

```

**Comment by dvberzon** [comment] 2019-12-19 11:09
@thorn0 

My use of the word `never` was ill-advised. There must however be some criteria under which prettier makes formatting decisions. For example, it doesn't change the following code:

```
const a = 1;
const b = 2;
```

Even though you could remove some whitespace:

```
const a = 1; const b = 2;
```

[playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTARgG4AdKSKDTAI30wCZiQAaECABxgEt1lRsAJ0EQA7gAUhCNMhDYAbhG4ATViBqDsYANZwYAZQ5buUAObIYggK5w2ACxgBbADYB1O93hojYOPume3PKeAJ6yYGgybCZocIIw4pqmjtjIAGbYzrFsAFZoAB4AQpo6evrYjnAAMiZw6ZnZIHn5+iamznAAilYQ8PVZtiBGgrGCsjTYNHDOahyCJjCuKjB2yAAcAAxscxCxrpocsnNwo-J1bACOPfCJnDIo2GgAtFBwcMrvaoJwV9zfidhkqkkBkBmxYo5uBZrIM0G0Ot1enUQQ1BjBJktlCtkAw2JZsNxnG0AMIQRwpWRQaDnEBWWIAFUm91BjXkNgAklAPrB9GB5lwAIJc-QwEIdfqxAC+kqAA)

My guess is it doesn't remove the new line above because it would be detrimental to readability (there may be other considerations, but syntactically it is the same).

My point is that removing the parentheses is also detrimental to readability and my recommendation is that prettier reconsiders its opinion on this matter in the light of empirical evidence.

**Comment by thorn0** [comment] 2019-12-19 11:21
Prettier disregards whitespace and then regenerates it when needed. Sometimes the input and the output happen to be identical, so it looks like 'Prettier kept that whitespace', but it's not exactly what happened. Same with parens. They are not 'kept' or 'removed'.

**Comment by dvberzon** [comment] 2019-12-19 11:28
@thorn0 

Fair enough. But there are situations that you linked to where the original formatting is maintained (or more correctly put back) so it would also be possible for parentheses.

I'm merely suggesting, based on the data, that it would be a good idea to add this case as one of those exceptions.

If prettier's aim is to autoformat code without reducing the code quality, then it should maintain parentheses in expressions involving operator precedence.

**Comment by thorn0** [comment] 2019-12-19 12:02
Thanks for your unusual and valuable input. However, we are really reluctant to extend that list of exceptional cases where Prettier looks at the original formatting. It's even planned to add an option to ignore the input formatting completely.

Readability is not the only constituent of Prettier's value proposition. What about the goal of avoiding style debates within teams? Keeping the original formatting is a way away from this goal. With Prettier, such readability issues aren't the developer's responsibility anymore. The team simply agrees to delegate those formatting matters to Prettier and focuses on more interesting things. This comes with certain trade-offs, sure, but some say it's worth it.
