### ISSUE TITLE
Poor indenting on long class declarations

### ISSUE THREAD

**Issue by francium** [prettier/prettier#7563] opened 2020-02-08 14:50 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgGUIBbOASQx3zgHVUYALAQQCU5cAbbgTwAy0AOYA5XBULAAOlEKFsqONwAmrJIQDOMTOmEBuWQF9Zs9PFoFCrKBBZZqFvAUYsOXXoJHjJMuQqVVACENbV0oA2NTKDBuXE1NawAjMPwYADE0iEw+AFlcKFxhLEywGGy+KVl5SCgwgFcy7IAKAEoq-3kAei7CWwgAB2rCEyhR2TgADwHsmEJcFJ00wlj4xPcefiEIgGE4hJ84UvKc-MLizGOKwin4KBV1xcw0q9OCopKsnMJUMgHuOAUWCJUgURxYZwMJhsTibLwRQ4AGmstnsmHBlihblhnm2YgkRD88gGugAbrh4AFlGpDP4SahyZTFNSgrThgN6kluKgwIQVBBQXAWHo2h15N1ev0hv5RqMQIiQIMYKhoJpkKBcJhMBAAO4ABU1CDVKFwpIgqBU8pASWeYAA1kLiAN8HpkDp6nAFcwYGRuPRmEw4JpnQRiEamAymHxkOAElb0JosDA9c9hGRcMg8NxEwqAFaaSZBW0OmDEAkCdBwTM8HMgfOTYh6AEARXqdirSCztedmETmBjMD4AyDYF0AxgVvpsEYKhYyAAnAAGBUkiCJ+jPAYxklBrCkqsKgCObfgKcGxpA8QAtFA4HAVPerZg4MfUM+U0V09Xs56QImyKgbqYB6CqaE2cCtu2361jACwznOSAAEwKksqDcrs5Bfigti3la9SJgAKgsxpdr+pIetQD6wMQo6oOONgqMQg4AtBcBGEYQA)
```sh
--parser typescript
--print-width 90
```

**Input:**
```tsx
interface SomeInterfaceWithAReallyLongName {
  fieldA: string;
}

interface AnotherInterfaceWithAReallyLongName {
  fieldB: string;
}

class AbstractFactoryManagerFactory {
  constructor() {
    // noop
  }
}

export abstract class AReallyLongClassNameFactoryManagerFactory extends AbstractFactoryManagerFactory implements SomeInterfaceWithAReallyLongName, AnotherInterfaceWithAReallyLongName {
  private fieldA;
  private fieldB;

  public doSomething() {
    // noop
  }
}

```

**Output:**
```tsx
interface SomeInterfaceWithAReallyLongName {
  fieldA: string;
}

interface AnotherInterfaceWithAReallyLongName {
  fieldB: string;
}

class AbstractFactoryManagerFactory {
  constructor() {
    // noop
  }
}

export abstract class AReallyLongClassNameFactoryManagerFactory
  extends AbstractFactoryManagerFactory
  implements SomeInterfaceWithAReallyLongName, AnotherInterfaceWithAReallyLongName {
  private fieldA;
  private fieldB;

  public doSomething() {
    // noop
  }
}

```

**Expected behavior:**

The class declaration has wrapped onto new line, but is vertically aligned with class fields making it difficult to distinguish the first field from the class declaration at a glance.

Ideally the declaration wrapping should be double indented (or, imo, aligned with the `class` or `abstract` keyword of the declaration on the previous line) and (or) when wrapping a new line should be insert after the declaration,
```tsx
export abstract class AReallyLongClassNameFactoryManagerFactory 
       extends AbstractFactoryManagerFactory 
       implements SomeInterfaceWithAReallyLongName, AnotherInterfaceWithAReallyLongName {
  private fieldA; // ideally a new line before this, but I've seen https://prettier.io/docs/en/rationale.html#empty-lines
  private fieldB;

  public doSomething() {
    // noop
  }
}
```

**Comment by evilebottnawi** [comment] 2020-02-10 10:39
Duplicate of #5156 ?

**Comment by francium** [comment] 2020-02-11 01:53
Similar but concern here is the back of differentiation between end of class declaration and start of class body

**Comment by thorn0** [comment] 2020-05-21 16:26
Closing in favor of #8340. I like the solution proposed there.

**Closed by thorn0** 2020-05-21 16:26 UTC
Labels: lang:typescript, status:needs discussion
