### ISSUE TITLE
Add CLI option for formatting every supported file type

### ISSUE THREAD

**Issue by kripod** [prettier/prettier#4907] opened 2018-07-29 12:33 UTC
**Environments:**
- Prettier Version: 1.14.0
- Running Prettier via: CLI

**Idea:**
As Prettier adds support for more and more file types, I think it would be reasonable to add an option for formatting every known file type inside a directory.

**Comment by hawkrives** [comment] 2018-07-29 15:49
Wha ya out using the `**/*` glob? Since prettier ignores files that it doesn't know how to process, and also ignores SCM and node_modules folders?

**Comment by kripod** [comment] 2018-07-29 15:53
@hawkrives Unfortunately, it emits messages like the following:

```
[error] No parser could be inferred for file: .git\objects\f2\e15f8c1f53bc37841640661a47158b304be5b6
[error] No parser could be inferred for file: yarn.lock
```

**Comment by ikatyang** [comment] 2018-08-02 14:03
This looks like a duplicate of #2691, which proposed to format every supported file type by default.

**Closed** 2018-08-16 14:27 UTC
Labels: status:awaiting response
