### ISSUE TITLE
Proposal: Move to async api

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#7799] opened 2020-03-20 02:50 UTC
# Motivation

1. > Node.js has supported ES modules stably since 13.2.0. Because Node.js doesn't provide any way that loads ES modules synchronously from CJS, ESLint cannot load configs/plugins that are written as ES modules. And migrating to asynchronous API opens up doors to support those.

Quote from https://github.com/eslint/rfcs/tree/master/designs/2019-move-to-async-api#eslint-class-replacing-cliengine , we will face the same issue in our project.

2. I tried to add `less.js` parser, it should be better working on `.less` file, but it's only async, [there is no sync version](https://github.com/less/less.js/issues/3448), can't make it work with prettier.

**Comment by thorn0** [comment] 2020-05-06 18:29
Duplicate of #4459

**Closed by thorn0** 2020-05-06 18:29 UTC
Labels: area:api, status:needs discussion
