### ISSUE TITLE
Improve handling of long template literals

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier#2527] opened 2017-07-21 11:08 UTC
It'll be good if long template literal is moved to next line, if it exceeds printWidth, and moving it fixes the issue.

e.g. following (assuming printWidth=100) is left untouched
```javascript
const message = `Booking failed. startTime ${boardingTime} is in the past; current time ${currentTime}`;
````
While it could be reformatted to:
```javascript
const message =
  `Booking failed. startTime ${boardingTime} is in the past; current time ${currentTime}`;
````

Interestingly it's what happens if we split literal into two, e.g. following:
```javascript
const message = `Booking failed. startTime ${boardingTime} is in the past;` + ` current time ${currentTime}`;
```
Resolves to:
```javascript
const message =
  `Booking failed. startTime ${boardingTime} is in the past;` + ` current time ${currentTime}`;
```
And in such form it hardly makes sense to keep `` `+` `` split, but trying to remove them, moves literal again into one line, so again we have issue of line exceeding print width

--- 
In general it might be nice if pretter splits even longer literals with `` `+` `` so they can fit `printWidth` (but that might be hidden behind option)

**Comment by bakkot** [comment] 2017-07-21 17:55
I think this is #2482.

---

I don't think we want to do

> In general it might be nice if pretter splits even longer literals with `+` so they can fit printWidth(but that might be hidden behind option)

- prettier generally does not change the AST, and I think that's a good policy. It wouldn't work for tagged template literals in any case.

**Comment by medikoo** [comment] 2017-07-22 07:58
>prettier generally does not change the AST, and I think that's a good policy

Sounds sane. I agree

**Comment by aboyton** [comment] 2017-07-23 23:03
While not automatically splitting makes sense (as we don't want to change the AST), this issue of long lines has come up before (say in #1894 and #1966).

**Comment by medikoo** [comment] 2017-07-24 08:04
If you're convinced that fixing #1966 will fix this issue, please close it (I'm not that certain as it involves template literals, and they additionally come with some special handling afaik)

**Comment by azz** [comment] 2017-07-24 11:43
This is indeed a duplicate of #1966.

**Closed by azz** 2017-07-24 11:43 UTC
