### ISSUE TITLE
Black style of disabling formatter is arguably more flexible

### ISSUE THREAD

**Issue by mangelozzi** [prettier/prettier#12083] opened 2022-01-14 10:40 UTC
With the python `Black` formatter, one uses `# fmt: off` to start disabling the formatter, then `# fmt: on`. Simply, flexible.

At the moment I there is no way to neat way to disable a block of code, e.g.:

```
    // fmt: off
    get accept() { return this.getAttribute("accept"); }
    set accept(value) { this.setAttribute("accept", value); }

    get size() { return this.getAttribute("size") || DEFAULT_MAX_SIZE; }
    set size(value) { this.setAttribute("size", value); }
   
    get authUrl() { return this.getAttribute("authUrl"); }
    set authUrl(value) { this.setAttribute("authUrl", value); }
    // fmt: on
```

Or:
```
    // fmt: off
    const textWidgets   = container.querySelectorAll('input:not([type="radio"]):not([type="checkbox"]), textarea');
    const selectWidgets = container.querySelectorAll('select');
    const otherWidgets  = container.querySelectorAll('input[type="radio"], input[type="checkbox"]');
    const webComponents = container.querySelectorAll('wc-uploader');
    // fmt: on
```

I see there is a similar feature in prettier, but it only works at the top level. Is this not an austere restriction that could be removed?

**Comment by fisker** [comment] 2022-01-14 10:48
Duplicate of #5287

**Closed** 2022-01-14 10:49 UTC
Labels: type:duplicate
