### ISSUE TITLE
Import assertion with function named `assert`

### ISSUE THREAD

**Issue by dan-lee** [prettier/prettier#12676] opened 2022-04-21 12:46 UTC
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgEMBnYuPfAMxwnXwHIoIATOJEsvegHSgG4O5GAAoYAT0xwIlfAHdUUZhFkAaBgDkIchUtn0AlCBUgImGKmjFkoQjhqyACrYRWUhADazCYq8YBGOIRgANZwMADKhOhwADIKcMiUHmT+gSFh4ZhBCgDmyDA4AK5wxnDofnDMrMwxhFA5hYQ5cABiuOiEMOb1yCCEhTAQRiAAFjDo7gDqI6jwxFlgcOEus6gAbrNivWCkwwqcMA6BOR2JySUgAFbEAB7hue5wAIqFEPBn7ikgWTicvX6ECruYaYHAKGCTVDMGAjZAADgADMZQRAyJNApheqC4Jw1gljABHV7wI6mVx9YgAWigcEqlWGODgRNQjKOTVOSCSnwuZHQqA+X2ID2exISnPOxhggMh0NhSAATJLAqh3LkAMK0DkgHEAVmGhTIABVAa4uV81sUAJKKBARMBgswAQUU4XEjwFcAAvp6gA)

```sh
--parser babel
--no-semi
```

**Input:**

```jsx
import assert from 'node:assert'
;assert(typeof window, 'No window')
```

**Output:**

```jsx
import assert from "node:assert"
assert(typeof window, "No window")
```

**Expected behavior:**

Prettier should insert a semicolon in the right place

---

With [import assertions](https://github.com/tc39/proposal-import-assertions) on the horizon the input code below is not possible but needs a semicolon to be distinguished from a function call to  node.js' `assert`.
Admittedly it is an edge case and there are multiple workarounds, but the behavior of prettier is still wrong and produces invalid JS.

**Comment by dan-lee** [comment] 2022-04-21 17:33
Oh seems to be my bad, my editor reported the following:

<img width="243" alt="image" src="https://user-images.githubusercontent.com/571589/164517896-e95daa48-ed40-43fd-b3dd-c535120216c4.png">

I am sorry if this is actually valid syntax.

**Comment by kachkaev** [comment] 2022-04-21 18:51
I guess it’s to do with the relatively new [assert syntax](https://v8.dev/features/import-assertions):

```ts
import json from './foo.json' assert { type: 'json' }
```

vs

```js
import json from './foo.json'
assert("hello")
```

We should check the language spec. I would expect that Automatic Semicolon Insertion (ASI) would place `;` at the end of the first line, but maybe it is allowed to span the import statement over multiple lines. In the latter case we will need to go for:

```js
import json from './foo.json'
;assert("hello")
```

It's like with:

```js
hello()
;[1,2].map(console.log)
```

to avoid confusion with `hello()[1,2].map(console.log)`.

**Comment by Josh-Cena** [comment] 2022-04-23 15:04
FYI, according to [the spec draft](https://tc39.es/proposal-import-assertions/), line terminators are forbidden between `FromClause` and `AssertClause`, because that would be disastrous for backward compatibility.

**Comment by kachkaev** [comment] 2022-04-24 15:12
Yeah it makes sense to not allow the new line before `assert`.

@dan-lee what tool is it on [your screenshot](https://github.com/prettier/prettier/issues/12676#issuecomment-1105500980)? It’d be nice to check with those folks before closing this issue.

**Comment by dan-lee** [comment] 2022-04-24 17:48
> @dan-lee what tool is it on [your screenshot](https://github.com/prettier/prettier/issues/12676#issuecomment-1105500980)? It’d be nice to check with those folks before closing this issue.

It's WebStorm (or PhpStorm respectively in my case)

**Comment by fisker** [comment] 2022-04-25 10:23
Closing this since it's not a bug https://github.com/prettier/prettier/issues/12676#issuecomment-1107517412

**Closed by fisker** 2022-04-25 10:23 UTC
Labels: status:needs discussion, status:awaiting response, lang:javascript
