### ISSUE TITLE
Angular: @let syntax

### ISSUE THREAD

**Issue by qmonmert** [prettier/prettier#16468] opened 2024-07-11 20:19 UTC
Angular 18.1 introduces `let syntax` 

https://blog.angular.dev/introducing-let-in-angular-686f9f383f0f

Can you support this? 🙂

Thanks

![image](https://github.com/user-attachments/assets/11729d9f-b778-4dc9-a404-4c86230d03f9)

**Comment by fisker** [comment] 2024-07-12 03:43
Duplicate of #16296

**Closed** 2024-07-12 03:43 UTC
Labels: type:duplicate
