### ISSUE TITLE
Formatting long chains of typescript union and insersection types are not consistent

### ISSUE THREAD

**Issue by manfreed** [prettier/prettier#10237] opened 2021-02-03 13:14 UTC
Prettier cleverly formats long lines of union types as this example shows:
```
type Type =
  | SubType1
  | SubType2
  | SubType3
```

Notice how the expression starts with the operator before the first item (`| B`). Typescript allows this syntax and this makes it possible to have a nicely formatted type definition.

Similarly, Typescript allows type definitions to start with the intersection operator (ampersand), so the following should be possible.

```
type Type =
  & SubType1
  & SubType2
  & SubType3
```

The problem is that prettier does not format these type definitions as above. Instead, it places the first item right in the first line, and puts the operator at the end of the line:

```
type Type = SubType1 &
  SubType2 &
  SubType3
```

I'd like to suggest making the formatting rules for union types to apply for intersection types.

**Comment by thorn0** [comment] 2021-02-03 20:23
Duplicate of #3986

**Closed** 2021-02-03 20:24 UTC
Labels: type:duplicate
