### ISSUE TITLE
Have Prettier work on markdown files that used tabs

### ISSUE THREAD

**Issue by nikitavoloboev** [prettier/prettier#5080] opened 2018-09-10 19:27 UTC
I have a markdown document that has a bunch of dashed points with some points nested.

Prettier breaks on formatting this file and produces [completely wrong document](http://bit.ly/2O1Pfed).

I don't know what I am doing wrong but perhaps its because I used tabs to create those nested points.

Is there anything I can do to fix this? I would love to see Prettier support this because now I can't use Prettier at all for auto formatting my markdown.

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAZQK4FtcCGATgJ4A6UAtOgNoCycMBAugBS6MED0HTAdLgAmASgpkY1GgCU4AMzhEEYOG17dF8xVGUCRFSZgAWxAJZQA5mwDOxomfNcbpi7tFRxkgKIA3BSRiG9ugAkugA1lAQAO7WtvZccL6kAfaUwZQR0a5iErR0JOgA4iYwABLYAEaxzg64JJTmJYaV2e659AUAgkQwJmAANnBW1XYWPPXEvQNDrR55BQCaENgAKpUqrE6jtfUkyzDrs+356CuK-f0QI-F1lDDnl0eSJ8VWMMObcWO3jW9WT-N0AB1CBEMKyS4xT41caUKKg8GQgE0M4EMBhezXMb3NEYlxCYQgAA0IAgAAdetArMhQMQiNEAArEBDUlAEbwQEyCYkgCpEXGMTBktH2ZD3bBwElmKwKGAM-nmQjIWQEfoykkAKysAA8AEL89GCggcAAyZjgytV6pAwqIMqIyBAhDBgmiUB5ZNGMCBXICyAAHAAGEmeiAyoH8smOz1DBS+HmKACO2BMinlBEVBEtaslIBluBMYqIEpJVnsgwAitgIPBs9amBUfYI-UgAEwknEmfr2ADCEHwWZQkSgFpJ2BlKwIFVZKpzAF850A)
```sh
--parser markdown
```

**Input:**
```markdown
# Summary
- [Meta](meta/meta.md)
	- [Reference](meta/reference.md)
- [Sharing](sharing/sharing.md)
	- [Everything I know](sharing/everything-I-know.md)
	- [My GitHub](sharing/my-github.md)
	- [My Articles](sharing/my-articles.md)
	- [My YouTube](sharing/my-youtube.md)
	- [My Trello](sharing/my-trello.md)
	- [My Gists](sharing/my-gists.md)
	- [My Workflow](sharing/my-workflow.md)
	- [Tracking](sharing/tracking.md)
```

**Output:**
```markdown
# Summary

- [Meta](meta/meta.md) - [Reference](meta/reference.md)
- [Sharing](sharing/sharing.md) - [Everything I know](sharing/everything-I-know.md) - [My GitHub](sharing/my-github.md) - [My Articles](sharing/my-articles.md) - [My YouTube](sharing/my-youtube.md) - [My Trello](sharing/my-trello.md) - [My Gists](sharing/my-gists.md) - [My Workflow](sharing/my-workflow.md) - [Tracking](sharing/tracking.md)

```

**Comment by duailibe** [comment] 2018-09-10 20:07
Thanks for the report! This is a known issue, it's a bug in the Markdown parser we use.

See #3223

**Comment by duailibe** [comment] 2018-09-10 20:07
Duplicate of #3223

**Closed by duailibe** 2018-09-10 20:07 UTC
Labels: lang:markdown
