### ISSUE TITLE
Chai indentation is broken

### ISSUE THREAD

**Issue by ValentinH** [prettier/prettier#2590] opened 2017-08-04 15:47 UTC
Using [chai-http](https://github.com/chaijs/chai-http), we should write our code like this:
```js
chai.request(app)
  .get('/protected')
  .auth('user', 'pass')
````

Though, Prettier formats it too:
```js
chai.request(app).get("/protected").auth("user", "pass");
```

[Example](https://prettier.io/playground/#%7B%22content%22%3A%22chai.request(app)%5Cn%20%20.get('%2Fprotected')%5Cn%20%20.auth('user'%2C%20'pass')%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

Is this a behavior done on purpose or not? Is there any workaround?

Thanks by advance 🙂

**Comment by azz** [comment] 2017-08-05 07:23
It is intended behaviour. The only workaround is to use `// prettier-ignore`.

Closing as a duplicate of #1565, where there is some discussion about this.

**Closed by azz** 2017-08-05 07:23 UTC
