### ISSUE TITLE
.prettierrc is not used when using stdio

### ISSUE THREAD

**Issue by epeli** [prettier/prettier#2697] opened 2017-08-29 12:49 UTC
When using file as an argument

    prettier file.js

the options from `.prettierrc` is read but if the file is piped to the prettier

    cat file.js | prettier

prettier only uses it's defaults.

This is problematic for neoformat (Vim plugin) because it [uses stdio](https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/javascript.vim#L42) when formatting with prettier.

EDIT: Using prettier 1.6.0

**Comment by azz** [comment] 2017-08-29 12:51
Hi - thanks for the report. This is a duplicate of #2689 which has been fixed.

**Closed by azz** 2017-08-29 12:51 UTC
