### ISSUE TITLE
--print-width does not work anymore on JS comments

### ISSUE THREAD

**Issue by pronebird** [prettier/prettier#4850] opened 2018-07-16 09:36 UTC
I can confirm that `printWidth` is ignored even when using the `.prettierrc.yml`:

```
printWidth: 80
```

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJwmOAZ0IDo4APOMABQEMYALDASygxwQBM4Ods8CxbBFYxCGGBAkM4GQgFcARgFpF8qJwA2siADMMAUW1gYeNgAk4mrDxIYAKg2biOAc3mbafCriKFm0BgUprQm4oyyWPRMktKytFhYGGoa2gA0GADuTmBMznEYusw4hDAY+GDyOBxQBOX6RdpZzIwYJAlJwQj+0CQAOrXQpRgAtvS5RBgAvPz4fmSUNNEkYzC5ABSo6wDatMoAXgAMygCcGAC6ANQAlH197YmozNcA3CBpIBBYMAFQhMigLx4TJ0Gr-FC0ABuIk47xAihwoQA1nAYABlKJgViuZCmeRwD6sQg8GDURGuMbIXS0TTEj4AK0I5AAQoiwCj0bQRnAADKsOBUml0kBREo8ZDw2iKACemmgcNwogA6sxOIxkAAOQ4fXAQYlKxFYCW+Yk4SECj4cACO8mKcDJtAptEFtIJIGJI2YuJw+I+-igrm0AEV5BB4C7hTApSq1QxkAAmD4hZiabEAYQgI0pKCg0AtIHkxPsUvB1NdAF9y0A)
```sh
--parser babylon --print-width 80
```

**Input:**
```jsx
// process.execPath in renderer process points to the sub-bundle of Electron Helper. This regular expression extracts the path to the app bundle, which is the first occurrence of file with .app extension.
const matches = process.execPath.match(/([a-z0-9 ]+)\.app/i);
```

**Output:**
```jsx
// process.execPath in renderer process points to the sub-bundle of Electron Helper. This regular expression extracts the path to the app bundle, which is the first occurrence of file with .app extension.
const matches = process.execPath.match(/([a-z0-9 ]+)\.app/i);

```

**Expected behavior:**
To wrap the comment

**Comment by lydell** [comment] 2018-07-16 10:05
Duplicate of #265

**Closed by lydell** 2018-07-16 10:05 UTC
