### ISSUE TITLE
Markdown; Tabs not getting preserved

### ISSUE THREAD

**Issue by anishmittal2020** [prettier/prettier#5104] opened 2018-09-18 10:37 UTC
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAdQBYEMboCeEArumLlOgCYToDuAljNuswPwDaAegIwC66ADToeAJn4AdKJJgYAEhADOBAOLMANrgBG6JXABOAN0PTZGAMIaSKw+gBmEA+gAOuA7g0a4G1wYgA5h4AtsGMUAFmcugASqTwBlEYAAr+AFZwYDBO0iBCIBAuMIzQSsig7v70ye4IZSi4RhCM1Hkg2h5gANZwMADKbmDhAcgwBiRw+eH6BjCpuAHBuMj2nvr5aUoAHgBCnT39uMFwADLhcCtrkyBuBjPIIEsGXbT0UG0uBuEwmC0syAAOAAM+U+yjgmA8LgenzgMxMbQMcAAjiRGEj5otlkhVhp1iB9GFRuNrkpht4AIokCDwS5464wHS-aj-JBifJjXCMDTDCwQULYkBQaAXfI2OAAFR09TGEwAvnKgA)
```sh
--parser markdown
--use-tabs
```

**Input:**
```markdown
- What you can do with it?[^1] , [^2]
	- Host Gitlab server
	- Cluster for parallel programming
	- Router
	- Projector

```

**Output:**
```markdown
- What you can do with it?[^1] , [^2] - Host Gitlab server - Cluster for parallel programming - Router - Projector

```

**Expected behavior:**
```markdown
- What you can do with it?[^1] , [^2]
  - Host Gitlab server
  - Cluster for parallel programming
  - Router
  - Projector

```
Issues: Tabs used for indenting list are not preserved.

---

Also, please explain where tabs can be used in Markdown according to Prettier.

**Comment by ikatyang** [comment] 2018-09-18 12:58
Hi, this is a known issue that the parser we used can't parse tab-indented lists correctly, see #3223 for more info.

**Comment by ikatyang** [comment] 2018-09-18 12:58
Duplicate of ##3223

**Closed by ikatyang** 2018-09-18 12:58 UTC
