### ISSUE TITLE
`formatWithCursor` hangs/takes several seconds on text HTML input

### ISSUE THREAD

**Issue by abose** [prettier/prettier#13387] opened 2022-08-28 09:43 UTC
Hi all,

 I was integrating prettier as a default extension in [brackets editor](brackets.io). using `formatWithCursor` API to prettify code leads to hangs and general slowness.
 Prettier is [hosted in web worker](https://github.com/phcode-dev/phoenix/blob/main/src/extensions/default/Phoenix-prettier/worker/prettier-helper.js) inside brackets. `formatWithCursor` API is causing large delays and hangs in most large html files, but normal `format` api works just fine.

* Attached zip project with samples files that causing hangs.  [pretty.zip](https://github.com/prettier/prettier/files/9439400/pretty.zip)
* Also see this [URL](https://phcode.site/p/5b1e59a0/default%20project/prettier.html)  in dev tools to see a quick simple use case that hangs for several seconds in beautify API.

## questions
* I could not find the use of `formatWithCursor` in [vscode extension code](https://github.com/prettier/prettier-vscode). How does the vscode extension handle cursor movement without using the API.
* Is `formatWithCursor` recommended for usage within editors as i am seeing several seconds of delay to prettify code in not so large attached sample files.

Any help would be much appreciated. 

**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: Browser API
- Runtime: Chrome v83, web worker
- Operating System: Linux
- Prettier plugins (if any): parser-html.js

**Steps to reproduce:**
* Extract the contents of [pretty.zip](https://github.com/prettier/prettier/files/9439400/pretty.zip)
* open `index.html` in any editor and see debugger. observe that the main thread hangs for several seconds on calling `formatWithCursor`.

**Expected behavior:**
* Gets result with cursor

**Actual behavior:**
* hangs browser

Thanks,
Arun

**Comment by thorn0** [comment] 2022-08-28 18:31
Unfortunately, `formatWithCursor` has known performance issues. See https://github.com/prettier/prettier/issues/4801

VS Code somehow manages the cursor itself, so formatter extensions don't need to care about it.

**Comment by thorn0** [comment] 2022-08-28 18:31
Duplicate of #4801

**Closed** 2022-08-28 18:31 UTC
Labels: type:editor support, type:duplicate, type:perf

**Comment by abose** [comment] 2022-08-29 03:21
Thanks for the quick reply @thorn0 . looks like there are no quick solutions. I tried using our own diffs but the performance on large files were not acceptable too.

Vscode repo should have some answers on how they do it so well without the performance penalty of diffs. Maybe they are using the parse tree path im guessing. Will update if I find anything.

**Comment by thorn0** [comment] 2022-08-29 07:17
You might want to try the solution proposed in https://github.com/prettier/prettier/pull/6164
