### ISSUE TITLE
typscript generic type specification formatting goes uglier then input

### ISSUE THREAD

**Issue by luckylooke** [prettier/prettier#6783] opened 2019-11-02 10:46 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wQDcBLbCAWwRgAVqATANQEMAbAVziKTwBRKJWpQ6sDjz54AvHnZEiFAOZQAPMNHQJMKbyIA+ABQAdKHjzBzly+wwUAqgCUAMgIDkAensUPAGhs8AF9AizxyKlp6ACFFOH0+cwBKAG4QfxAIDBgKaCJkUHZsagB3BmKEApR2MggKZgyQACNsdjAAazgYAGUMdoooFWQYbF5MgAsYGk4AdQmKeCJ+sDgeqsWKShgAT2RwJSbBojhcJnYVGnZkADMuE8yAKyI0GLbO7p72OldBuFv7nAni8eoMVJw4ABFbgQeAAzgPED9bAnbD7ZrsZpwThNDDYQYwWYNGATZAADgADJk8RATrM2hh9ni+KcyP9MgBHGHwJjZaogRQAWigcDgzDFTWwcC5VDg50u1yQdwRQJAJxoFBGY1VyiGEOhsP+SsBmRgmKJzBJyAATKa2hROGCAMK0K77KDQdkgbgnAAqmOqypOwWCQA)
```sh
--parser babel
```

**Input:**
```jsx
export const enviromentProdValues: EnvironmentValues = assign<EnvironmentValues>(
  {
    apiURL: '/api',
  },
  enviromentBaseValues
);
```

**Output:**
```jsx
export const enviromentProdValues: EnvironmentValues =
  assign <
  EnvironmentValues >
  ({
    apiURL: "/api"
  },
  enviromentBaseValues);

```

**Expected behavior:**

same as input

**Comment by lydell** [comment] 2019-11-02 10:48
Hi!

Use the `typescript` parser for TypeScript.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wQDcBLbCAWwRgAVqATANQEMAbAVziKTwBRKJWpQ6sDjz54AvHnZEiFAOZQAPMNHQJMKbyIA+ABQAdKHjzBzly+wwUAqgCUAMgIDkAensUPAGhs8AF9AizxyKlp6ACFFOH0+cwBKAG4QfxAIDBgKaCJkUHZsagB3BmKEApR2MggKZgyQACNsdjAAazgYAGUMdoooFWQYbF5MgAsYGk4AdQmKeCJ+sDgeqsWKShgAT2RwJSbBojhcJnYVGnZkADMuE8yAKyI0GLbO7p72OldBuFv7nAni8eoMVJw4ABFbgQeAAzgPED9bAnbD7XYYPhgbAUHJNDA42CzBowCbIAAcAAZMgSICdZm0MPsCXxTmR-pkAI4w+BMbLVECKAC0UDgcGY4qa2Dg3KocHOl2uSDuCKBIBONAoIzGauUQwh0Nh-2VgMyMHYzWJzFJyAATGa2hROGCAMK0K77KDQDkgbgnAAqFuqKpOwWCQA)
```sh
--parser typescript
```

**Input:**
```tsx
export const enviromentProdValues: EnvironmentValues = assign<EnvironmentValues>(
  {
    apiURL: '/api',
  },
  enviromentBaseValues
);
```

**Output:**
```tsx
export const enviromentProdValues: EnvironmentValues = assign<
  EnvironmentValues
>(
  {
    apiURL: "/api"
  },
  enviromentBaseValues
);

```

It’s still a bit ugly, but that’s tracked in #2482

**Comment by thorn0** [comment] 2019-11-02 14:51
@luckylooke When you specify `"parser": "babel"` in the configuration, Prettier ignores file extensions and parses all files as JS. We'd really like to understand why people end up with such erroneous configuration as we want to improve the configuration story in future releases. What was your motivation to add `parser` to your config?

**Comment by luckylooke** [comment] 2019-11-02 19:07
@thorn0 sorry I did not realize that I should modify parser in playground, I saw similar result (I thought that the same) and so I had example to show... but in reality my result in project is pretty much same as @lydell posted. My project is generated by Vue CLI and actually it finishes with parser set to: @typescript-eslint/parser which I did not find in playground options.

I am not sure if this is covered by #2482 but if so.. you can close this issue... thank you :)

**Comment by lydell** [comment] 2019-11-02 19:09
Duplicate of #2482.

**Comment by lydell** [comment] 2019-11-02 19:09
Duplicate of #2482

**Closed** 2019-11-02 19:10 UTC
Labels: lang:typescript, type:duplicate

**Comment by lydell** [comment] 2019-11-02 19:12
@luckylooke FYI `parser: "@typescript-eslint/parser"` is for ESLint, not for Prettier. But it sounds like you didn’t set `parser: "babel"` in a/your Prettier config then, so that’s good. Also, I added your example to #2482.

**Comment by luckylooke** [comment] 2019-11-02 19:48
@lydell aaah.. true :D Sorry.. then I am not sure which parser is used.. it is probably introduced by `@vue/prettier` config which is one of configs my config is extending.

```
module.exports = {
  ...
  extends: [
    "plugin:vue/recommended",
    "@vue/prettier",
    "@vue/typescript",
    "plugin:sonarjs/recommended",
  ],
  ...
};
```
