### ISSUE TITLE
Objects in ternary operator cause mixing of spaces and tabs

### ISSUE THREAD

**Issue by saarmae** [prettier/prettier#4874] opened 2018-07-23 12:16 UTC
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATCBzTAXk0imwEsZzpMB+TYAHSkZgGs4BPJTANwEMANgFc4ARgA0zAL6YeTFuy48BIuACYpUaQG4QEkBAAOVdMlD8ATpYgB3AApWEaZCH68I5bPpAAjS-xgHDAAykaB5FB4yDCWogaRaHCWMPYBeAC2-MgAZkJJBgBWaAAeAEIBQXCh-BlwADKRcLn5cAbhlkmWrr78vpyC0D5GlpEwAOpeMAAWyAAcAAztNknjAUauI3BdvM0GlnAAjsLkB2n8mdlIeYIFIEkZ5DFxbfeReIJwAIrCEPDP8RAMD6k2wM2QABYDLF+ORBO8AMIQDJZVxCQQ+YRJAAqfRcSFigNwYBat1e-AwpKS0mkQA)
```sh
--single-quote
--tab-width 4
--trailing-comma all
--use-tabs
```

**Input:**
```jsx
const dog = condition ? {
	key: value1,
} : {
	key: value2,
};
```

**Output:**
```jsx
const dog = condition
	? {
			key: value1,
	  }
	: {
			key: value2,
	  };

```

**Expected behavior:**
Anything that does not mix spaces and tabs.

**Comment by ikatyang** [comment] 2018-07-23 13:35
Duplicate of #4199, see https://github.com/prettier/prettier/issues/4199#issuecomment-389533517:

> Tabs-only is not aligned, which is why someone raised #2771.
>
> ```js
> const dog = condition
> 	? {
> 			key: value1,
> 		}
> 	: {
> 			key: value2,
> 		};
> ```

**Comment by ikatyang** [comment] 2018-07-23 13:35
Duplicate of #4199

**Closed by ikatyang** 2018-07-23 13:35 UTC

**Comment by j-f1** [comment] 2018-07-23 13:56
Perhaps we should format this the way it was in the original, though. The current style requires an extra line and the input generally looks prettier to me.
