### ISSUE TITLE
Deterministic Output

### ISSUE THREAD

**Issue by thechriswalker** [prettier/prettier#7794] opened 2020-03-19 11:50 UTC
I haven't found a way of doing this, nor an issue regarding it - so I may be in the minority here. I love the idea of prettier, and have always loved `go fmt` for the same reasons - but the Golang tool takes it a step further and I am looking for a tool to emulate this in the JS ecosystem.

The idea is that for a given source AST, **irrespective of source formatting**, we get a given output. Currently prettier allows the source formatting to inform the output formatting.

I kinda want this to completely eliminate any author style on the resultant code, but have prettier enforce all style decisions.

The simplest example I can think of is the following, where the 2 declarations _could_ each fit on a single line, but prettier does not force the first one to be a one-liner.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArARkwF5NgAdKTTAQyUwMoF9LLIoNt8AmEs2+gSYBuVlBAAaEBAAOMAJbpkoGgCdVEAO4AFNQjTIQNAG4R5AE0kgcqmmADWcGAGUZd+VADmyGKoCucFIAFjAAtgA2AOpB8vBobmBwzvqx8saxAJ6GYGgGUh5ocKow2raeoTTIAGY04YVSeGgAHgBCtg5OzjShcAAyHnDVtfUgjU3OHp7hcACKfhDwQ3WBIG6qhaqGODQ4cOFWMqoeMJEWMEHIABwADFKHEIWRtjKGh3AbxoNSAI7z8KWyAwoGhoAC0UDgcHMUKsqjgv3kcNKNHKlSQNWWUkKoXkPn8KzQk2mcwWg3RwxWMB2p3M52Q3Ckvho8nCkwAwhBQhVDFBoF8QH5CgAVHZAjEjYwBACSUGhsGcYCOcgAgrLnDAMtMloUmEwgA)
```sh
--parser babel
```

**Input:**
```jsx
const obj1 = {
  a: 1
}

const obj2 = { a: 1};
```

**Output:**
```jsx
const obj1 = {
  a: 1
};

const obj2 = { a: 1 };
```

**Example deterministic behavior:**
```jsx
const obj1 = { a: 1 };
const obj2 = { a: 1 };
```

**Comment by evilebottnawi** [comment] 2020-03-19 11:52
It is expected, because we repsect user input in some cases, you need the `--pure` option. Duplicate of #2068

**Closed by evilebottnawi** 2020-03-19 11:52 UTC
