### ISSUE TITLE
Styled component with prettier-ignore and JS expression has broken formatting

### ISSUE THREAD

**Issue by jsnajdr** [prettier/prettier#9123] opened 2020-09-01 06:56 UTC
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgCgEEBKAAwB0oACKgelqoAcAnOGGASzmYFoOBzKBFaUaAAQC2eDgEMq+GYqXKlxKsErkYALz5RccAB5IqAEmD4WERqjUBeAHzyrNgHQdUAYQgTGOeFQA-FQA5ACMIVQmIQAMIcQAvgDcolQJlKQpUCAANCDWnNCoyKAyzMwQAO4ACmUIxSgyWJUyGMV5AEbMMmAA1mwAyow9HFD8yDDMAK5weXASHXgGuAAyMmNTMvxwAGLCEjLso+ONUzAQuSAAFjASWADqVxzwqMNgcAP1zxwAbs8YyHAqHaIFGqG4MGq3X4B2QADMmuC8gArVCGABC3T6gxkUhWozg8MRsxAqMMA2OOAAilMIPAiVgkSBhsxwcxAR0ZIssJcWKMYPcOLgYFdkAAOGJ5Kzg+7dRiAlhwNk-Ql5ACOtPgUOsDRAMlQPCgcDweEurA1HFYUK2sKQCMZJPBEg4E2mjspcBpdMJduJeRgXMFwtFSAATP7uhwsMdvBJbSAlQBWS5TcEAFS5DXtTJ+MwAkvoEDABmBmBxGDBCPoBpgcAzwQkEkA)
```sh
--parser babel
```

**Input:**
```jsx
styled(A)`
  // prettier-ignore
  @media (aaaaaaaaaaaaa) {
	z-index: ${(props) => (props.isComplete ? '1' : '0')};
  }
`;

```

**Output:**
```jsx
styled(A)`
  // prettier-ignore
  @media (aaaaaaaaaaaaa) {
	z-index: ${(props) =>
    props.isComplete ? "1" : "0"};
  }
`;

```

**Expected behavior:**
The `z-index` value should be formatted in one line, and not broken into two lines. There's enough space on the line. I.e., the input string is already formatted correctly.

The printer gets confused by the string literal triggered by the `prettier-ignore` in the doc:
```
"@media (aaaaaaaaaaaaa) {\n\tz-index: "
```
It doesn't see the `\n` character and doesn't detect it as a line break. If the `@media` and `z-index` were on one line, the arrow function indeed woudn't fit onto one line with them. That's why Prettier breaks it.

This used to work better in 2.0.5 and looks like a recent regression. I suspect #8097 by @thecodrr.

**Comment by evilebottnawi** [comment] 2020-09-01 10:10
Duplicate of #4355

**Comment by thorn0** [comment] 2020-09-01 11:16
I don't think this is a duplicate. #4355 doesn't involve `prettier-ignore`.

**Comment by evilebottnawi** [comment] 2020-09-01 11:17
@thorn0 it is expected, `prettier-ignore` inside CSS so it is affected only on `CSS`, you can write:
```
styled(A)`
  @media (aaaaaaaaaaaaa) {
	z-index: ${ // **prettier-ignore**
   (props) => (props.isComplete ? '1' : '0')};
  }
`;
```

**Comment by thorn0** [comment] 2020-09-01 11:23
As far as I can tell, the OP doesn't expect `prettier-ignore` to affect the JS expression. The issue is that this expression shouldn't be wrapped because it fits `printWidth`, not because of `prettier-ignore`.

**Comment by jsnajdr** [comment] 2020-09-01 11:27
I don't mind the JS being formatted despite `prettier-ignore` in the CSS, but the line breaks are done incorrectly. Prettier doesn't see the `\n` in the unformatted CSS literal, and calculates the line width incorrectly. The JS expression is broken into two lines, although it would fit on one line. It's all described in the bug report.

The bug is a regression from 2.0.5, therefore it's unlikely to be a duplicate of another issue from 2018.

**Comment by evilebottnawi** [comment] 2020-09-01 11:29
@jsnajdr @thorn0 same behavior on previously version, @jsnajdr why you think it is regression?

**Comment by thorn0** [comment] 2020-09-01 11:31
@evilebottnawi Here's the output of 2.0.5 (`npx prettier@2.0.5 --parser babel`):
```
styled(A)`
  // prettier-ignore
  @media (aaaaaaaaaaaaa) {
        z-index: ${(props) => (props.isComplete ? "1" : "0")};
  }
`;
```

**Comment by evilebottnawi** [comment] 2020-09-01 11:32
@thorn0 hm, something with npx cache, sorry

**Comment by evilebottnawi** [comment] 2020-09-01 11:32
Looks we remove parens too :thinking:

**Comment by thorn0** [comment] 2020-09-01 12:09
The parens are added only if the body is on the same line with the parameters. 2.0.5 works this way too. Might be intended.

**Comment by jsnajdr** [comment] 2020-09-01 12:47
Seems to me the regression happened in #8595 (@fisker). Before that PR, the strings were broken up with `replaceNewlinesWithLiterallines`, making the newlines visible to the printer. After the PR, that code disappeared.

Relevant parts of the doc are:

Before (2.0.5):
```
"`",
literalline,
breakParent,
"  // prettier-ignore",
literalline,
breakParent,
"  @media (aaaaaaaaaaaaa) {",
literalline,
breakParent,
"\tz-index: ",
```

After (2.1.1):
```
"`",
indent([
  hardline,
  breakParent,
  "// prettier-ignore",
  hardline,
  breakParent,
  "@media (aaaaaaaaaaaaa) {\n\tz-index: ",
```

**Comment by thorn0** [comment] 2020-09-01 17:07
I guess https://github.com/prettier/prettier/issues/9096 is caused by the same reason.

**Comment by evilebottnawi** [comment] 2020-09-01 17:15
@thorn0 Yes, i think it is same problem

**Closed** 2020-09-04 04:12 UTC
Labels: area:multiparser, lang:css/scss/less, lang:javascript, type:bug
