### ISSUE TITLE
Prettier incorrectly adds spaces around plus sign in css urls

### ISSUE THREAD

**Issue by remcohaszing** [prettier/prettier#7906] opened 2020-03-30 11:42 UTC
**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgWwA4QE4wAEArngDYAUAFjDNgM5ID0TAZtDPQHQDmEEPMnACG2dN0iYmYevQD8rYZnRkAngF4AchBgQA1AGVhUegEoA3CAA0ICNhjpo9ZKGF48EAO4AFNwmcowmSewqrONgBGeMJgANZwMAbYMehQPMgweMRwNjSYZADqVOjw9MlgcAb+JegAbiWqyOCy1iCp9HAE3tE8mMLIimQdNgBW9AAeAELRcQlGmHAAMqlwA0HDIGPjBqmCcACKxDqrSIMbyXgdeE0y4SDYeKkwBegAJjBUyAAcAAw2DxAOgVotgmg84FdaqsbABHI7wbp2AIgYT0AC0UDgcFe2NaeDgcPQ+O6wl6-VO6xyIA6ygyWSp9F2QkOxzWQypMGEERe70+SAATDZMsIVLsAMIQTB9JoQgCsrWIHQAKlyAmcqbVsgBJKA42AGMCPewAQV1BhgqiEbI6AF8bUA)
```sh
--parser css
```

**Input:**
```css
@import url(https://fonts.googleapis.com/css?family=Noto+Sans);
```

**Output:**
```css
@import url(https://fonts.googleapis.com/css?family=Noto + Sans);

```

**Expected behavior:**

Prettier doesn’t enclose the plus sign in a url with spaces.

**Workaround**:

Enclose the url content with quotes

```css
@import url('https://fonts.googleapis.com/css?family=Noto+Sans&display=swap');
```

**Comment by evilebottnawi** [comment] 2020-03-31 11:06
@thorn0 Duplicate, https://github.com/prettier/prettier/issues/5654 and https://github.com/prettier/prettier/issues/2835 - same problems, in theory we can union them

**Comment by thorn0** [comment] 2020-03-31 14:56
Duplicate of #2835

**Closed by thorn0** 2020-03-31 14:56 UTC
Labels: lang:css/scss/less, type:bug
