### ISSUE TITLE
breaks CSS in JS ${Cls}:not() -> ${Cls}:not ()

### ISSUE THREAD

**Issue by brandonkal** [prettier/prettier#6259] opened 2019-06-30 03:45 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wHFsIBXDPAXjxIE8AbOAEwDo2BLANwAMAOlDx4AtgENsAc25QkeAAwBuYcNEc5GSvmDrR4qbPlLVIvAF815gCTAAyjBbsAklG0wLSKBBgAKJAAzbmwSAFowAAtuZjYASjw9c1FJGTkFFX0rKH0AMjwAPjxvXz8OOy0dAHVsCQwLOJL-OwAhHRhoBsT9UR4iDGYJRgVA1jQzUWyhKBAAGhAIDBhuaCJkUCkKAHcABSkENZQJXghuNjmQACNasABrOBh7DAkwOWlkGGxKOHnImDFmFVovB+i84PYDtxlrwoYxkOAiGt5nIiHBcDtatJJMhAhJmKj5gArIhoFo3e6PCRiOAAGTkcBxeIJIGJaHsb1YAEVKL4GUEmT8QM9Qmj4U4MHAiGBsNwlhcMDLYFUzjBIsgAByKeYKiComp1eEKyVo3gM+YARx58Axi0OIAkRDCUDg7HYF2wcEtITgGIkWIkjPxgtRYm4Hy+wY5cG5vMDzJgEkuyrYquQACZ5p8JDE3gBhCBibEoHzOi6UVEAFUTh1xQYsFiAA)
```sh
--parser typescript
```
I am using Typescript but this does not matter here.

**Input:**
```tsx
export const Group = styled.div`
  margin: 0;

  .input {
    margin: 0;
  }

  ${StyledInput}:not(:first-child) {
    margin: 0;
  }

  & > :not(.${inputWrap}):not(${Button}) {
    display: flex;
  }
`

```

**Output:**
```tsx
export const Group = styled.div`
  margin: 0;

  .input {
    margin: 0;
  }

  ${StyledInput}:not (:first-child) {
    margin: 0;
  }

  & > :not(.${inputWrap}):not(${Button}) {
    display: flex;
  }
`;

```
**Expected behavior:**
No space should be inserted after not as this breaks the CSS.

Updated with minimal reproduction. It appears that having a child selector is required. Oddly, the space is not always inserted as you can see in the last declaration.

**Comment by dcecile** [comment] 2019-07-15 14:56
Same thing here, but mine is a space inserted before an attribute selector. The added space changes the behaviour of the selector, breaking the CSS.

**Input:**

```ts
const yesFrame = (
    ...args: Interpolation<ThemedStyledProps<{}, Theme>>[]
) => css`
    ${ChatRoot}[data-frame="yes"] & {
        ${css({}, ...args)}
    }
`
```

**Output:**

```ts
const yesFrame = (
    ...args: Interpolation<ThemedStyledProps<{}, Theme>>[]
) => css`
    ${ChatRoot} [data-frame="yes"] & {
        ${css({}, ...args)}
    }
`
```

**Comment by evilebottnawi** [comment] 2019-07-15 15:02
Problem in `postcss-selector-parser`

**Comment by modernserf** [comment] 2019-07-22 19:59
I am having a similar issue which I imagine has the same root cause: 

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOjFVQAMAdKAAkoDNoYBaVASwC84lKA3AQwCcAFAwZ1YAZTZxUDACTAW7AL4BKANwUS6qBRAAaEBAAOMZtFTJQ-PhADuABX4JzKHlwjNcekACM+PMADWcDBihv7MUADmyDB8AK5w+gAWMAC2WADqSczwqGFgcGJOOcxcORjI4MReEahwfDB2fpGpPMg0PFh1+gBWqAAeAEJ+gcFiPKlwADIRcO2d3SB9-RJROACKcRDw812JIGF8dXyV3jze2NBehnwRMBkeMEnIABwADPo3EHUZfoaVNyk9S4c30AEctvAmkZnCAeNIoHA8HgvHw4BDmGimjwWm0kB09vo6qlmDF4vsWGs4JttnN8Qt9jBzg9cE9kAAmfSxHjMLARSIAYQgqValSg0FBIDidQAKudnAS6opFEA)

**Input:**
```js
styled.css`
  font-size: var(--fontSizes-${size});
`;
```
**Output**
```js
styled.css`
  font-size: var(--fontSizes- ${size});
`;
```

**Comment by fisker** [comment] 2019-11-04 10:10
minimum reproduction

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOlwEsA3AAwB0oACagEmDgA8AHAJwF8koIYAKJADMibdAFowACyJZcASmrAqtWgHpV1VJIgBXWdR4xqAQ1y5NLY2DgnB8NtW69l1Di4bN2HANpS4YAGs8AF1FFzUNLV19QxMzCysbACM4QQg2G28XNxpqAFtjNgBzIigkagAGAG58UpYdI2AcshAAGhAIFhgiaFRkUEK2CAB3AAVChD6UYxIIIlw2kCS2KyCYAGVLMFKi5Bg2HTh2yRg8rAB1aXhULbh1yaJukkeMZHBUPvbS1Dg2GFGVkUCshBMYsD92gArVBMABCK0CcA2xjycAAMqU4CCwRCQNCmOsdjgAIo6XhYoQ4o4gSyiX5vTAsOCoMBsIhdRbsUowc7zGCSZAADgq7XYEB+5xWLDe7GZvxIWPaAEcyfAAZ0piBjKgxFA4Hg8IsMiqRHAAcYgcZseDqT88kQ9gdbUS4KTyY7Du0YMYkrzcPzkABWL0rGQ7ADCEDywJQPD1ix0PwAKj6pvtDhwOEA

**Comment by thorn0** [comment] 2020-04-23 16:28
fixed by https://github.com/prettier/prettier/pull/7883
https://github.com/prettier/prettier/issues/6259#issuecomment-513931664 is a manifestation of https://github.com/prettier/prettier/issues/5465

**Closed by thorn0** 2020-04-23 16:28 UTC
Labels: lang:css/scss/less, scope:dependency, type:bug
