### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by priyanka-surana** [prettier/prettier#14815] opened 2023-05-13 07:47 UTC
**Environments:**

- Prettier Version: 2.8.8
- Running Prettier via: CLI
- Runtime: Node.js v18.15.0
- Operating System: Linux
- Prettier plugins (if any): None

**Steps to reproduce:**

```
## 1. Conda env file
name: nfcore2.8
channels:
    - defaults
    - conda-forge
    - bioconda
dependencies:
    - nf-core=2.8.0
    - nextflow
    - yamllint
    - prettier
    - black

## 2. Create conda env -- base conda is using miniconda
conda env create -f nf-core-2.8.yml

## 3. Clone repository
git clone git@github.com:sanger-tol/blobtoolkit.git
cd blobtoolkit
git checkout view

## 4. Load conda env and run command
conda activate nfcore2.8
prettier -l .
prettier -w .
prettier -version
prettier
```

**Expected behavior:**

When run with `-l .`, prettier checks the files and lists those with formatting errors.

**Actual behavior:**

All the commands listed above give the same error:

```
/lustre/scratch123/tol/teams/tolit/users/ps22/homeDir/miniconda3/envs/nfcore2.8/lib/node_modules/prettier/node_modules/camelcase/index.js:3
const UPPERCASE = /[\p{Lu}]/u;
                  ^^^^^^^^^^^

SyntaxError: Invalid regular expression: /[\p{Lu}]/: Invalid property name in character class
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/lustre/scratch123/tol/teams/tolit/users/ps22/homeDir/miniconda3/envs/nfcore2.8/lib/node_modules/prettier/src/cli/options/parse-cli-arguments.js:2:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

Node.js v18.15.0
```

**Comment by kachkaev** [comment] 2023-05-13 08:39
👋 @priyanka-surana! Not sure if this is an issue with Prettier – I can’t reproduce it in the playground.

**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE3MFUAK+AogEoDCAggMpE6YC8dA9ANoA6bADsADICuAXwC6TPgG4QAGhAROMAJbpkoAIYAnNRADu+dQjTIQKgDZaVATwPSARmpVgA1nBhUVAWzg95UOMgBmJmhwNnaOzlSc9t4A5sgwanzBIHBu1nAAJukZPCpQ0Xwq0XAAYhBqbiowCnmGKnwwEFIgABYwbsYA6s3y8GiRYHBU+j3yAG495oZgaFYg3kFqMPh20RX+gUkAVmgAHlQxxnAAinwQ8OvGQdKRaguG1ippxk2cat4wHfLpMM3IABwABmumiCHTsnEMrzgC1GvmkAEdTvBlrIDCgVGgALQ+DIZJpqOCI+QE5aFNZIAKXJJBNzyOIJakHOAUKpvaz1OD4OBqLw+C5XEBoJknM6+CkbaQwR6fb6-JAAJkldnkxhiZAgbnJyTQAFYmnwggAVR5oykC0aJACSUCysCoYDecgoNqoMHMh35cAEAiAA)

```sh
--parser babel
```

**Input:**

```jsx
const    UPPERCASE    =    /[\p{Lu}]/u;
```

**Output:**

```jsx
const UPPERCASE = /[\p{Lu}]/u;

```

Perhaps, `nfcore2.8` depends on an old version of Prettier.

**Comment by kachkaev** [comment] 2023-05-13 08:42
👋 @priyanka-surana! Have you tried reporting this to `nfcore`?

**Comment by priyanka-surana** [comment] 2023-05-13 10:17
I did report to nf-core. I think the issue actually comes from Node.js. When I downgrade the nodejs version to 14.20.1, it gets fixed. Have you seen Node.js incompatibility before?

**Comment by kachkaev** [comment] 2023-05-13 11:21
Please share a reproduction involving Prettier only. e.g.:

```sh
node --version
# a.b.c
npx prettier@2.8.8 [some arguments]
# works
```

```sh
node --version
# d.e.f
npx prettier@2.8.8 [same arguments]
# crashes
```

**Comment by priyanka-surana** [comment] 2023-05-13 12:21
I created `conda` env with just `prettier` and `nodejs`. 

**Prettier with Node.js v14**
```
## prettier_nodejs14.yml
name: prettier_nodejs14
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - prettier
    - nodejs=14.20.1

## Activate conda env and run
conda activate prettier_nodejs14
prettier -l .

## This works
```

**Prettier with Node.js v18**
```
## prettier_nodejs18.yml
name: prettier_nodejs18
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - prettier
    - nodejs=18.15.0

## Activate conda env and run
conda activate prettier_nodejs18
prettier -l .

## This crashes
/lustre/scratch123/tol/teams/tolit/users/ps22/homeDir/miniconda3/envs/prettier_nodejs18/lib/node_modules/prettier/node_modules/camelcase/index.js:3
const UPPERCASE = /[\p{Lu}]/u;
                  ^^^^^^^^^^^

SyntaxError: Invalid regular expression: /[\p{Lu}]/: Invalid property name in character class
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/lustre/scratch123/tol/teams/tolit/users/ps22/homeDir/miniconda3/envs/prettier_nodejs18/lib/node_modules/prettier/src/cli/options/parse-cli-arguments.js:2:19)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

Node.js v18.15.0
```

**Comment by kachkaev** [comment] 2023-05-13 14:02
Is it possible to reproduce the problem without conda? Sorry, but so far it is hard to see if the problem is within Prettier core or the way it is being used by other software.

**Comment by priyanka-surana** [comment] 2023-05-14 10:00
You are correct. Using the docker image this error does not occur. I used [prettier image](https://hub.docker.com/r/tmknom/prettier), tried the command `prettier -l .` and it works.

```
singularity exec docker://tmknom/prettier prettier --version
# 2.8.8

singularity exec docker://tmknom/prettier nodejs --version
# v18.12.1
```

This seems a conda problem. Unfortunately I still do not know how to resolve this in conda.  Any suggestions much appreciated.

**Comment by kachkaev** [comment] 2023-05-14 23:28
Might be worth trying to reach Anaconda community for help. Let’s close this issue as you cannot reproduce it with bare-bone Prettier core, but if you have any further thoughts, feel free to share them below!

**Closed by kachkaev** 2023-05-14 23:28 UTC

**Comment by hoodmane** [comment] 2023-05-22 18:27
@priyanka-surana did you report this anywhere else? Would you mind cross referencing the other bug reports? I am seeing this issue too.

**Comment by priyanka-surana** [comment] 2023-05-23 09:49
@hoodmane I posted this on nf-core, but did not get any response.
https://nfcore.slack.com/archives/CE6PELWR4/p1683181800978319

**Comment by hoodmane** [comment] 2023-05-24 14:46
@katietz
