### ISSUE TITLE
[HTML][Angular]Support angular html similar to jsxBracketSameLine

### ISSUE THREAD

**Issue by yinshuxun** [prettier/prettier#6018] opened 2019-03-31 06:54 UTC
**Prettier 1.16.4**
```sh
{
        "files": [
          "*.html"
        ],
        "options": {
          "htmlWhitespaceSensitivity": "ignore",
          "parser": "angular",
        }
      }
```

**Input:**
```angular component html
<aui-menu-item *ngFor="let item of list" (click)="xxx"> {{ xxxx }}</aui-menu-item>
```

**Output:**
```
<aui-menu-item
              *ngFor="let item of list"
              (click)="xxx"
            >
              {{ xxx }}
            </aui-menu-item>
```

**Expected behavior:**
```
<aui-menu-item
              *ngFor="let item of list"
              (click)="xxx">
              {{ xxx }}
            </aui-menu-item>
```

**Comment by lydell** [comment] 2019-03-31 08:16
Duplicate of #5377

**Closed by lydell** 2019-03-31 08:16 UTC
