### ISSUE TITLE
Prettier breaks @page:first pdf styles on html pages

### ISSUE THREAD

**Issue by angfal** [prettier/prettier#10026] opened 2021-01-08 15:07 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq19zrlcAhgCady5VDTgweVGDAAOAWjgBHAK4BLAG4BeJiFzR4sWfgCe0uNvKRYCGFpDwAHjAD07OgG4LlHgCcAzmI0AVXwAMVkADm0nQWFfGCM6OBihAAFpHgBzOHJgFiF88hofDJUoJHIAFnDpe3IABkrq2rq3PPyAXxY21PSspAAzFT8YHO78ou8SsvqZqpr61qgCzqXhJziEpJZUF14BbYAjCD4jTh2jk7OXWkYWEAAaEAhpGBVoX2RQH28IAHdiHwID4oHh0X48IwfR4Hbw8MAAazEAGV0mBShlkDBvEo4I84DQDnA+HwiQAZHhQDJKTJwEIQbxFKTo5AgHhKGAQB4gVwAdUoKngvlRcCRQIF6gFRhZYF8UJApX83hgxFhGSKyH6oP8jwAVr57AAhWEI5E8USk0pwDVa3EgPX2JHoxIARSUEHg1ro2pA6T8cG8LNcXOk3lKMB5Kj4MEoyHCdUeIYg-h5sOkLJDcEVaitj2U7rgKuewNZvlkUDgRKJXO8ilUNZVmXVAxtj38NBUmOxtt8Trgrvznu94gOEajMaQACZHlieCo6OjdDQmyBMwBWLlKfz4HgHYGar22tQ4gCSUBJsCRYFDLwAgmekfFEoO4O12kA)

**Input:**

```jsx
@page:first {
  margin: 0 0 48px 0;
}
```

**Output:**

```jsx
@page: first {
  margin: 0 0 48px 0;
}
```

**Expected behavior:**

There is no blank between `@page:` and `first`
```jsx
@page:first {
  margin: 0 0 48px 0;
}
```

**Comment by thorn0** [comment] 2021-01-08 16:36
Duplicate of #7859

**Closed by thorn0** 2021-01-08 16:36 UTC
