### ISSUE TITLE
Prettier does not work in hidden directories

### ISSUE THREAD

**Issue by s-ayush2903** [prettier/prettier#10657] opened 2021-04-06 12:42 UTC
Prettier does not seem to work in hidden directories. We're using prettier coupled with spotless, with this prettier specific config:
```kts
    format("xml") {
      target("**/*.xml")
      prettier(mapOf("prettier" to "2.0.5", "@prettier/plugin-xml" to "0.13.0"))
        .config(mapOf("parser" to "xml", "tabWidth" to 4))
    }
``` 
Concerned code section hyperlink: [here](https://github.com/s-ayush2903/android-fhir/blob/as/spotless-for-entire-project/buildSrc/src/main/kotlin/SpotlessConfig.kt#L38-L42)
Okay so let me explain the scenario. The scene is as follows: 
* We're working on an android codebase developing an application, and as per our directory tree, we have a set of hidden dirs and folders, in which lies the `.idea` folder of ours, and we have a bunch of XML files(most of which are ignored in vcs) but we do check in some of those XML files to vcs out of which is the concerned file: `jarRepositories.xml`(path relative to project: `.idea/jarRepositories.xml`). 
* So when I apply spotless(implicitly prettier on XMLs) on the project, the prettier reformats the concerned file incorrectly(i.e., disregards the configuration defined in its declaration), the interesting fact is that when I move the same (incorrectly formatted code patch) to a file/dir that is not hidden in the project tree, prettier formats it as expected(i.e., follows the configuration defined in its declaration). An example of incorrectly formatted code patch is linked [here](https://github.com/s-ayush2903/android-fhir/blob/as/spotless-for-entire-project/.idea/jarRepositories.xml#L50-L53). 
* Yeah, I know that I can simply copy-paste that correctly formatted section to the concerned file but don't want to do it. I've tried hardcoding the path to that specific file(to force prettier for that specific file)in prettier config(the spotless config of which I wrote above), but astonishingly, that also doesn't seem to work. 
 

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeATnADhAzgPgB0oM4BbCeAWkx1wEsYJ0BPIqAAi+9QixnrQOUAIZk4AXkIh6AE2kcAbiIA2AV0nSyIxQgUB6dtx58BQ0eKkgLcBcvWaQ23VANHjHXv0GvOH-8Y2VmroKtLEAZFKqhpWABYwMFi4SPr6eLgAdLjQIjAsWHCZzADm+pCwCDD6tHiMzPRwuPq4oslxlLjhflEchhE8NeSUcDTYdUys7qhDdPggADQgpj64yKAi6OgQAO4ACpsIayiqOyIsa0sARugiYADWcDAAylh39FAlyDDoGkvkVzgslkQIAMiJPmoRCU4AAxZjaRIfL4nNRMRYgBJkFQAdTijCabzAcGeR0Y9EUjBYyHAuEuMiguDg6Bge1uJW0yAAZqomUsAFa4AAeACFbg8ns8xHBQR84NzeXABcLnsiVHAAIpqEYKlR8kBvdBM9A0q4iQEqDFYdAfGA4uQwOLIAAcAAYlta8HAcbcsDTrU1mboMQBHbXwNl8Y4gES4KhQOBAoEYzBh+iYNnQzlIHl6pUgJlkejfX75hifdVanU5xVLH4iegqZEAYQgZGzICaAFYMWomQAVc3HXP6xQaACSUBBsGeYBt-AAglPnvl1br9TBzfbZI7kAAWAC+B6AA)

**Input:**

```jsx
    <remote-repository>
      <option name="id" value="maven" />
      <option name="name" value="maven" />
      <option name="url"
            value="https://oss.sonatype.org/content/repositories/snapshots"/>
    </remote-repository>
```

**Output(when patch is in `.idea/jarRepositories.xml`)**

```jsx  
    <remote-repository>
      <option name="id" value="maven" />
      <option name="name" value="maven" />
      <option
                name="url"
                value="https://oss.sonatype.org/content/repositories/snapshots"
            />
    </remote-repository>
``` 

**Output(when patch is in a _not hidden_ file e.g.,`strings.xml`)**
```jsx 
    <remote-repository>
        <option name="id" value="maven" />
        <option name="name" value="maven" />
        <option
            name="url"
            value="https://oss.sonatype.org/content/repositories/snapshots"
        />
    </remote-repository>
 ```

**Expected behavior(in `.idea/jarRepositories.xml`):**
```jsx
    <remote-repository>
        <option name="id" value="maven" />
        <option name="name" value="maven" />
        <option
            name="url"
            value="https://oss.sonatype.org/content/repositories/snapshots"
        />
    </remote-repository>
```
PS: I've mentioned about a small patch of code only, but the prettier ignores the entire dir & file for formatting thereby incorrectly formatting the entire file. See the file [here](https://github.com/google/android-fhir/blob/master/.idea/jarRepositories.xml) for reference. Also, it is very important to bring in light that in the Pull Request we introduced and configured `prettier` for enforcing formatting rules on XMLs(see https://github.com/google/android-fhir/pull/334), the aforementioned file, i.e., [`.idea/jarRepositories.xml`](https://github.com/google/android-fhir/blob/master/.idea/jarRepositories.xml) was untouched.

Take a look as per your convenience : )

**Comment by thorn0** [comment] 2021-04-06 13:03
Please provide a minimal reproduction abstracted from all the 3rd party tools (spotless, idea, etc). It should clearly demonstrate what Prettier does wrong without a need for the maintainers to know anything about those tools. If you can't do this, I suppose the issue isn't on the Prettier's side and has more to do with the tools themselves.

**Comment by s-ayush2903** [comment] 2021-04-06 13:40
Thanks for pointing this out, the problem could be in spotless also(and may not be in prettier), and prettier was easy to fall in grey area as there was a single file in a hidden dir and was XML too :sweat_smile:(if there were any kt/kts files then I would've thought the same for spotless). Maybe I should check with spotless as they(spotless) are responsible for exposing file/dir(s) to the formatters. I'll discuss with senior devs involved in the project and proceed on it. 

Apologies if this ticket turns out to be useless : (

**Comment by thorn0** [comment] 2021-04-06 13:57
I'm going to close the issue for now, but I'll reopen it if you manage to come up with a minimal (Prettier-only) reproduction.

**Closed by thorn0** 2021-04-06 13:57 UTC
