### ISSUE TITLE
Typescript: Issue with single line type / interface with --no-semi and --trailing-comma none

### ISSUE THREAD

**Issue by kaw2k** [prettier/prettier#1941] opened 2017-06-03 13:23 UTC
**Input**
```tsx
// Using semis as delimiters
type Name = { one: string; two: string }

// Using commas as delimiters
interface Test { one: string, two: string }
```

**Output**
```tsx
// Using semis as delimiters
type Name = { one: string two: string }

// Using commas as delimiters
interface Test { one: string two: string }
```
TS is fine without delimiters when they are not inlined but is throwing errors when they are inlined without delimiters. 

**Expected**
Not sure how it should behave with the interplay between `--no-semi` and `--trailing-comma none`. Probably treat it as a normal object and use commas?

```tsx
// Using semis as delimiters
type Name = { one: string, two: string }

// Using commas as delimiters
interface Test { one: string, two: string }
```

**Comment by azz** [comment] 2017-06-03 13:54
Hi, thanks for the report.

This is a duplicate of #1930, which has been fixed and will be in the next patch.

**Closed by azz** 2017-06-03 13:54 UTC

**Comment by kaw2k** [comment] 2017-06-03 17:57
Awesome! Thanks @azz!
