### ISSUE TITLE
Leave one-line functions alone

### ISSUE THREAD

**Issue by RyanZim** [prettier/prettier#4125] opened 2018-03-09 19:44 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaAWBDAJgFYA2TAXkwAoATPGPASgoD5MwAnATwAcYIAdJzj04ACTy4qAHRC5CpWYwEBXHnXi16TATQCWAczgYZIHHAAeSgNwgANCAh896ZKDwcOEAO4AFDwhoyCB4ADbeeFxBDpIwyABmYWhwDgBGHHhgANZwMADKPJl6UAbIMBwqKSA0EGAJSVXFyRwwvhkGALZ49aHJDgBWaBYAQhnZuXl4HXAAMsVwPX2OKjA8KwSLVYUczcGpeKlcodD2IDwcxTAA6no0MDjIABwADA7nEMlXGTzB58ZwHAAbgsHBw4ABHFR6MFtPCdbpIRK9KrJDp6MoVFHFAyhOAARRUEHgmwcDFSNzuDyQBFJGT0oWxAGEIB0usEoNAQSAVMkACoHIKIhoAX2FQA)
```sh
--arrow-parens always
```

**Input:**
```jsx
const sha256 = (data) => crypto.createHash("sha256").update(data).digest("hex");
```

**Output:**
```jsx
const sha256 = (data) =>
  crypto
    .createHash("sha256")
    .update(data)
    .digest("hex");

```

**Expected behavior:**

The input was perfectly fine as it stood; it was a nice one-liner, exactly 80 characters long. Breaking it into multiple lines just makes it less clear. Is there a specific reason prettier behaves this way?

**Comment by merlinnot** [comment] 2018-03-09 19:47
IMO the current output is much more clean, I wouldn't like it to be changed. It seems as a step backwards to me.

**Comment by davidmdm** [comment] 2018-03-12 22:34
maybe in that case. But i have similar cases like when using express-validation:

    req.checkBody('id').isInt().optional();
    req.checkBody('name').notEmpty().optional();

that is hardly more than 50 characters, but because it is three methods chained it inserts line feeds.
I don't need these 2 lines to span 8 lines and have indentation.
This should at the very least become an option, as it is the only thing stopping me from committing to using prettier consistently.

**Comment by pvdlg** [comment] 2018-03-13 16:06
Maybe that could be something similar to what Prettier does for `Array`s and `Object`s:
- If the user inline them and the line is shorter than `printWidth` => keep inlined
- If the user write them on multiple lines => keep on multiple line
- If the user inline them and the line is longer than `printWidth` => break into multiple line

See [playground example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA6gSwDZ4YBGcGA1nAA4wY5R52kAUAhgM4ZsAWEATvLwwwuLKBgAcABgCUAHSiQobGtz4wAkvUYB5IgCsMAXgzBKvCJQCMGJBgDkZi9YBuLPAFc4dgDQZHlACYbe38g1w8vAF8Abnl5dGx8QhJyKhpoDABbdzwYHEo8UgYoZjhnBFoAM04efjhBYRYaKTkFaGUatQBZHLyAGR19IxN5DD9zK2CHCZc3Tx9R8Ysg22nljHD5+Ri4qATcAmJSInMKMTos3vzCjGK4DlYOPGgAc3qhETEW+UUO56gXpo7roDMZTDMpv5ZhEfEtApCJmE5l5fP4AMwIiwYzZRaIgbwgCx5drIUAsXjmADuAAVyQg2MgQCxnBAcAATfFM5TISpuNhwAknFhgCgwADKlGFdBeyBgvE8BLZEDAPL5ApAdH5-GpvBYL0yLFVeH5BL0bAAHgAhXUiuDiliZOADEpGk2E9wwSgegKu9WS3haxlEFhEACe-05ZjoMFwbOEyCkBMc-KwusojLM93q5U5vDgAEd3Dg8zq9QbfQT+ZkcLL5eq2NLCgBFdwQeAVkAwEOx+NIAIEuUsfDSgDCEEy5ZQUGgcE57n5ABUQwykLzjXBIpEgA) with objects (to clarify what I mean).

**Comment by davidmdm** [comment] 2018-03-13 17:55
@pvdlg 
I think that your idea is fair and is the expected behaviour @RyanZim  was expecting. 
If that is easy to implement I would go along with that. 
However I think this is what @merlinnot  was objecting to though. 
I would suggest the behaviour you specified with maybe an added flag for maxFnChainBeforeBreak
So if somebody wants it to break by default even if width is less than printWidth than they could have it that way too.

**Comment by pvdlg** [comment] 2018-03-13 18:00
My understanding is that @merlinnot objection is about Prettier forcing to not break in multiple lines.

The behavior I suggest would let the user choose for cases that fit in `printWidth`. If you break in multiple lines, Prettier keep it that way, if you write on one line, Prettier keep it that way if it fits in `printWidth`.

I don't think `maxFnChainBeforeBreak` option would be a good idea as adding new lines should be based on `printWidth` like everything else in Prettier.

**Comment by davidmdm** [comment] 2018-03-13 18:17
fair enough.

**Comment by RyanZim** [comment] 2018-03-13 22:38
Adding an option `maxFnChainBeforeBreak` is a terrible idea IMO.

@pvdlg's solution is interesting; but I'm not sure if I like the idea of adding yet another case where prettier looks at the existing code to figure out how to format. The whole point of prettier is to _not_ care about how the code was written.

TBH, the current behavior isn't the end of the world; I just find it a bit irritating.

**Comment by SimenB** [comment] 2018-03-14 08:46
FWIW I agree with the first comment - I find it more readable split up over multiple lines.

I'll also add, like the post above me, that more respecting user input would be a regression in mye eyes. If it's added, please consider adding https://github.com/prettier/prettier/issues/2068 so I can turn it off.

**Comment by davidmdm** [comment] 2018-03-14 12:42
Maxfnchain was just an idea so that as you guys want, you don't have to respect user input and prettier behaves deterministically.

As long as the line contains less than or equal to the max function calls And is less than print-width you keep it on one line. Else break each function call on to its own line.

This way people can configure prettier to behave how they want and prettier doesn't need to respect user line feeds. 

Somebody could configure it to one and prettier would know to always break function calls into their own line. 

I fail to see how it isn't a good compromise to all of our issues. 

I strongly dislike having my file increase 30 percent in length when all my lines are under the print-width.

**Comment by elado** [comment] 2018-03-28 19:27
another example where line breaks make code less pretty:

input

```js
const x = moment().add(1, 'day').valueOf()
```

output

```js
const x = moment()
  .add(1, "day")
  .valueOf();
```

the original code seems more readable.

Can chained methods be treated like objects and preserve original like breaks where it was intended?

**Comment by lydell** [comment] 2018-03-28 19:53
@elado The solution is to use [date-fns](https://date-fns.org/v1.29.0/docs/addDays):

```js
import addDays from "date-fns/add_days";
const x = addDays(new Date(), 1).getTime();
```

(Please don't take this comment too seriously.)

**Comment by mrchief** [comment] 2018-04-11 18:52
Its not just chained methods, one liners such as these should be left alone:

```
<div
  className={cx(this.props.className, 'react-dropdown-tree-select')}
  ref={node => { this.node = node }}
>
```

Currently it breaks down to 

```
<div
  className={cx(this.props.className, 'react-dropdown-tree-select')}
  ref={node => {
    this.node = node
  }}
>
```

One should not have to read 3 lines to read 1 line of code. Having it as an option is a good compromise but I prefer the maxLen idea.

**Comment by j-f1** [comment] 2018-04-11 18:58
@mrchief You can keep that as a one-liner by removing the `{}` around the arrow function body (`ref={node => this.node = node}`).

**Comment by mrchief** [comment] 2018-04-11 19:15
@j-f1 When I do that, I get eslint's no-return-assign error. And the parenthesis appear magically (eslint-cally maybe?) `{node => (this.node = node)}`

Maybe there is a eslint setting I can tweak?

**Comment by mrchief** [comment] 2018-04-11 19:52
It's a vicious cycle! :sob:

**Comment by mrchief** [comment] 2018-04-11 19:55
`no-return-assign` should not be disabled, especially for react apps. It's one of those must have rules that prevent you from shooting yourself in the foot. 

So prettier shouldn't:

 - add parens to one liners 
 - or not wrap one liners unless it exceeds maxLen (or printWidth)

**Comment by lydell** [comment] 2018-04-11 20:03
> no-return-assign should not be disabled, especially for react apps. It's one of those must have rules that prevent you from shooting yourself in the foot.

Do you have an example? Just curious.

**Comment by suchipi** [comment] 2018-04-11 20:07
FYI @mrchief I don't think we are going to change prettier's wrapping behavior here

**Comment by suchipi** [comment] 2018-04-11 20:07
>no-return-assign should not be disabled, especially for react apps. It's one of those must have rules that prevent you from shooting yourself in the foot.

I'm curious too- since prettier puts parens around assignment expressions, this is pretty hard to do on accident.

**Comment by mrchief** [comment] 2018-04-11 20:16
> Do you have an example? Just curious.

Are you talking in the context of assigning refs or just in general? In the context of refs, it is harmless - but then, the rule has no way of determining that, does it? Outside of refs, its bad in general because it can mask subtle errors (assignment vs comparison is classic example, one liners during array reduce  is another and so on)

> I don't think we are going to change prettier's wrapping behavior here

That is disappointing to hear. Care to explain why?

> I'm curious too- since prettier puts parens around assignment expressions, this is pretty hard to do on accident.

There is no issue with putting parens. Its just that putting parents introduces `no-return-assign` error which brings up back to the main issue - i.e wrapping up one liners and why @j-f1 [solution](https://github.com/prettier/prettier/issues/4125#issuecomment-380560188) is not a feasible solution.

**Comment by lydell** [comment] 2018-04-11 20:30
> Are you talking in the context of assigning refs or just in general?

Any code sample whatsoever would be nice. Perhaps involving React since you mentioned it. Always on the lookout for new helpful ESLint rules.

**Comment by mrchief** [comment] 2018-04-11 21:04
Off the top of my head, some are:


```
const a = (x) => x = 'something'
// vs
const a = (x) => x === 'something'

// assignment vs comparison
```

```
handleChange = (data, selectedValue) => this.props.onChange(data.map(k => ({ ...k, someBooleanProp: k.value = selectedValue }))

render () {
  return <SomeComp onChange={this.handleChange} {...this.props} />
}

// assignment vs comparison
```

```
arr.reduce((x, k) => x[k]=<something>, {}) 

// vs

arr.reduce((x, k) => (x[k]=<something>, x), {}) 

// in the first one, empty object is returned
```

And I've seen more weird ones too but can't remember them now. 

Like I said, these look subtle and may go unnoticed in a larger codebase (without the eslint rule).

**Comment by j-f1** [comment] 2018-04-11 21:10
Fortunately, Prettier wraps all of these in parens:

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTACgA8BKfAPk2P0wHI0IBbOGACwEsoBzOgHSgB6QZgBuaAZCgYctEuTxUaeFfUYt2XXgIHCcaNB25QWsMWkyQmAB2wAnDoygC22KABMANnADCrnnBy7tgw2AA0mGhw3mDw7gBq2J4ArnAKVJpoAHTWdhDW2dB+btxwhMGhWUzY1oQA1pREwJhZrXUR6nAAQhAQ3m4ACnnWSJh1WaJJqbRRMXGJKYEAvqSrOlB2CO5wdrQAZslQsRzQROTAApiYmzDJdlCYADwAysy+zNaYRf6leMCZWX8Xl8PzgS0wwFaWQBuXyaHBggoAiW6z02AMRhMCCw4ksH3sjmgAnsdiym3cyTAZRIETq6WoAG06gBdPCPTqaHiIiLAFaYVEicTrElkuAUqmEGljekkJms9lvTncbnUUg8vkCzBcTDsQJ7Dh2GTQOAROA2GAATy+ACMAFZwWJaiw3O5QMUCEBhED5GAnaTIUAkiAAdwG9gQaGQIGwoggHHcnujGGQeySUS91rs2DAdVYz1sYC0yBgdlSXvcEDAKbTJpAXCidhgQ2w3Gq1c86ZAtrQxC6WZzeewLAAMlw4O3OxBkjBrNOAEwT2u2Q07KPW7DWi2eaCJ3JcGAAdXj7GQAA4AAxe2FRA9Z6xR3JwBuicdezYAR2SBrgzdb2EXXpREwHDFqWtaGDw3gAIrJBA8AASAoTWke7gnkgc5eiW2AcJ4Wg+MwbYoFAxqJskUQACobpGSCph2YJLEAA)

**Input:**
```jsx
const a = (x) => x = 'something'
// vs
const a = (x) => x === 'something'

// assignment vs comparison
handleChange = (data, selectedValue) => this.props.onChange(data.map(k => ({ ...k, someBooleanProp: k.value = selectedValue })))

render = function () {
  return <SomeComp onChange={this.handleChange} {...this.props} />
}

// assignment vs comparison
arr.reduce((x, k) => x[k]=<something/>, {}) 

// vs

arr.reduce((x, k) => (x[k]=<something/>, x), {}) 

// in the first one, empty object is returned

```

**Output:**
```jsx
const a = x => (x = "something");
// vs
const a = x => x === "something";

// assignment vs comparison
handleChange = (data, selectedValue) =>
  this.props.onChange(
    data.map(k => ({ ...k, someBooleanProp: (k.value = selectedValue) }))
  );

render = function() {
  return <SomeComp onChange={this.handleChange} {...this.props} />;
};

// assignment vs comparison
arr.reduce((x, k) => (x[k] = <something />), {});

// vs

arr.reduce((x, k) => ((x[k] = <something />), x), {});

// in the first one, empty object is returned

```

**Comment by mrchief** [comment] 2018-04-12 01:10
@j-f1 Please see my earlier [comment](https://github.com/prettier/prettier/issues/4125#issuecomment-380581940).

**Comment by mrchief** [comment] 2018-04-12 02:35
Also, here's one example of where prettier's auto-parens masks potential errors:

```
<input onFocus={
    this.someProp = true
  }
  ... 
/>
```
after prettier

```
<input onFocus={(this.someProp = true)}
   ... 
/>
```

Without auto-parens, linters/parsers will scream on this mistake. 

This probably should its own issue.

**Comment by j-f1** [comment] 2018-04-12 10:47
> Without auto-parens, linters/parsers will scream on this mistake.

With the parens, it makes it more obvious to the user that something unexpected is happening.

**Comment by mrchief** [comment] 2018-04-12 12:27
> With the parens, it makes it more obvious to the user that something unexpected is happening.

Seriously?

**Comment by jaufgang** [comment] 2018-05-18 21:01
Redirecting this issue thread back towards one-line functions...

I would suggest that there is more to the question of what might constitute a "short, readable" function chain than merely how many methods there are in a chain, or how many characters are in the line

for example, you might want to allow

```js
obj.foo(1).foo(2).foo(3);
```
to stay on one line, but
```js
somePromise.then((val)=>doSomething(val)).catch((err)=>handleError(err))
```
would be much more readable if it were broken up into different lines, even though the first sample has 3 calls in the chain but the second one only has 2. 

The obvious difference is that the arguments passed to the functions in the first example are arrow functions, while the arguments to the second example are arrow functions.

So perhaps the decision of whether to allow chained function calls on a single line should be based on the types of arguments passed to those functions.  The rule could be something like:

- If all of the functions in the chain are passed, say 1 or 2  simple parameters (string, number, variable name) and the chain is less than the wrapping width, always print on one line 

- If any of the functions in the chain are passed an arrow function or an object literal, or more than 2 params, or if the total width is more than the wrapping width, then put each chained call on a new line.

This rule would provide readable output consistently, and would not depend on the original formatting in any way.

**Comment by slimlime** [comment] 2018-07-18 02:20
Definitely wouldn't want all the function calls on a single line.
Also has the added benefit of clearer granular commits on source control.

```ts
const sha256 = (data) =>
  crypto
    .createHash("sha256")
    .update(data)
    .digest("hex");
```
```ts
handleChange = (data, selectedValue) => this.props
  .onChange(
    data
      .map(k => {
        return k;
      }
    )
  )

```

**Comment by imdadahad** [comment] 2018-09-24 23:34
Is there a way to disable this?

**Comment by lydell** [comment] 2018-09-25 05:17
@imdadahad Currently, the only way is to use `// prettier-ignore comments`. You might be interested in this PR: #4765

**Comment by i-schuetz** [comment] 2019-01-06 16:35
Also for unit tests.

This looks better:

```
  it("Description", () => {
    expect(() => { foo() }).toThrow()
    expect(() => { bar() }).toThrow()
    expect(() => { baz() }).toThrow()
  })
```
Than the formatted output:

```

  it("Throws error parsing invalid plain time rule value", () => {
    expect(() => {
      foo()
    }).toThrow()
    expect(() => {
      bar()
    }).toThrow()
    expect(() => {
      baz()
    }).toThrow()
  })
```
Especially when there are a lot of such blocks. The file becomes very long and harder to read.

**Comment by Sm00g15** [comment] 2019-01-15 03:55
will we see disabling of this based on length anytime soon?

**Comment by odahcam** [comment] 2019-01-25 22:39
I have an oneliner arrow func smaller than printWidth that keeps being breaked in various lines just because of a `html` lit-html call inside of it.

**Comment by j-f1** [comment] 2019-01-27 12:53
That’s a different issue. Can you open an issue @odahcam?

**Comment by odahcam** [comment] 2019-01-27 23:09
Sure.

**Comment by damianobarbati** [comment] 2019-02-19 14:34
Any news on this?

**Comment by AntonioRecaldeRusso** [comment] 2019-02-20 00:50
Please allow us to disable this

```javascript
const clean => f({ data });
```
is turned into this

```javascript
const clean => f({
  data,
});
```

There is no need to overdo it

**Comment by mrchief** [comment] 2019-02-20 02:03
@AntonioRecaldeRusso Prettier doesn't do that - it's probably eslint or something else

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEYA2cCGUmAvJgBQCUJAfJgGZnCYAm+M+mAvhQNwgA0ICAAcYAS3TJQ+AE4yIAdwAKshGmQh8ANwhjmAkACMZ+MAGs4MAMrDTYqAHNkMGQFc4ggBYwAtjgDqnmLwaLZgcFZqwWJawQCeGmBo6oL2aHAyMEomDj74yHT4OOmCAFZoAB4AQibmllb4PnAAMvZwBUUlIOUVVvYOeACKrhDwHcUeILYy6TIahviGcTjQBsIy9jD+ejCeyAAcAAyC6xDp-ibCGutws1rtgjJwAI6uYk-Z+Ln5SIUTgukfGJnG5Jmh+kMRmNfp1JuxDNtmLtkAAmQQufBiHD9ADCEB8eQ0UGgDxArnSABVFuoYRNOJwgA)

![image](https://user-images.githubusercontent.com/781818/53060834-c57d5500-3489-11e9-867a-11d55e1489ef.png)

**Comment by koolamusic** [comment] 2019-03-12 09:48
Any news on this ?

**Comment by lydell** [comment] 2019-03-12 10:04
There's been some discussion going on in #4765

**Comment by nileio** [comment] 2019-08-07 09:37
i am super annoyed with this multi-line formatting thing ! I do not want to see 6 lines for 6  params simple js function .. this is crazy and makes my code 100 times longer than it should. Anyone know any solution to this ??

**Comment by odahcam** [comment] 2019-08-07 12:09
The solution is simpler than it looks: don't use Prettier.

**Comment by phaux** [comment] 2019-08-07 17:03
Not putting void functions in braces also triggers [`no-void-expression` lint](https://palantir.github.io/tslint/rules/no-void-expression/), which is useful, because it makes it explicit that a particular function returns void.

Using braces makes function take at least 3 lines.

**Comment by Fxlr8** [comment] 2019-09-17 14:54
OMG! Dear Prettier developers, is this really that hard to make a setting that leaves arrays and functions the same way user typed them? There are tons of similar issues that are ignored for years. I quit using Prettier.

**Comment by MattixNow** [comment] 2019-12-08 10:45
waw
```js
    let plateformOk =
        db
            .get(`plateforms`)
            .find({ name: body.plateform })
            .value() == undefined
```

**Comment by 0x01001** [comment] 2019-12-15 09:45
still break line func zzz i love prettier but i'm sorry..

**Comment by PhuHoaframgia** [comment] 2020-02-20 02:42
is this updated?
i am still following this

**Comment by thorn0** [comment] 2020-02-20 08:05
Fixed by https://github.com/prettier/prettier/pull/6685 and will be released soon.

**Closed by thorn0** 2020-02-20 08:05 UTC
Labels: lang:javascript
