### ISSUE TITLE
ts: Ugly line breaks with nested generics

### ISSUE THREAD

**Issue by ursmeili** [prettier/prettier#10952] opened 2021-05-26 12:29 UTC
package.json:
```
"prettier": "2.3.0"
```

.prettierrc.json:
```
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "singleQuote": true,
  "semi": true,
  "bracketSpacing": true,
  "printWidth": 80
}
```

before formatting:
```
export const VP_USER_AUDIT_CLIENT = new InjectionToken<BehaviorSubject<IUserAuditClient>>('VP_USER_AUDIT_CLIENT');
```

after formatting:
```
export const VP_USER_AUDIT_CLIENT = new InjectionToken<
  BehaviorSubject<IUserAuditClient>
>('VP_USER_AUDIT_CLIENT');
```

can that be improved?

**Comment by thorn0** [comment] 2021-05-26 15:26
What did you expect the output to be?

**Comment by ursmeili** [comment] 2021-05-26 17:24
I wouldn't expect prettier to insert any line breaks. There are no braces,
no dot, not even a space anywhere. I wouldn't count pointy braces as
"braces" in the context of this statement.

In short, it is now clearly less readable than it was before.

Georgii Dolzhykov ***@***.***> schrieb am Mi., 26. Mai 2021,
17:26:

**Comment by thorn0** [comment] 2021-05-26 17:47
This is very subjective. To me this looks much better than if the line was broken after `=`. Not breaking the line at all is clearly not option as the line is long. Sorry, but I'm going to close this issue. This works as intended.

**Closed by thorn0** 2021-05-26 17:47 UTC

**Comment by rsimoes** [comment] 2021-06-01 18:21
@ursmeili You note in your prettierrc that you have a very restrictive line length of 80 characters. The result you reported is expected given that.
