### ISSUE TITLE
Prettier cli command turns empty custom elements into void elements. 

### ISSUE THREAD

**Issue by michaeljota** [prettier/prettier#5372] opened 2018-11-07 17:28 UTC
**Environments:**
- Prettier Version: 1.15.1
- Running Prettier via: CLI
- Runtime: Node 8.12.0
- Operating System: Windows 10

**Steps to reproduce:**

```
prettier --write "my-element.component.html"
```
Input:
```html
<my-element></my-element>
```

**Expected behavior:**

The output should be the same as the input.

**Actual behavior:**
```html
<my-element />
```

Notice that this only happens from CLI, and does not happen if using the playground, nor the vscode extension.

**Comment by duailibe** [comment] 2018-11-07 17:34
@michaeljota What is "an angular file" ?

**Comment by michaeljota** [comment] 2018-11-07 17:38
Sure. I update it to `my-element.component.html`. This should be infer to `angular` parser, but even if I pass explicitly the parser as `html` or `angular` the behavior is the same.

**Comment by duailibe** [comment] 2018-11-07 17:47
Can't reproduce it:

```shell
$ ./bin/prettier.js foo.html
<my-element></my-element>
```

**Comment by spitfjre** [comment] 2018-11-07 17:55
If you use the json or json5 parser, you could reproduce that output. But with the html or angular parser everything works fine.

**Comment by duailibe** [comment] 2018-11-07 18:01
@spitfjre Thanks, I'm aware, this is being parsed as JSX. You can reproduce it with `flow`, `babylon` or `typescript` as well.

**Comment by michaeljota** [comment] 2018-11-07 18:16
What can I do to workaround this?

**Comment by duailibe** [comment] 2018-11-07 18:20
@michaeljota Can you try to reproduce this in a "clean" environment?

Something like:

```
mkdir tmp
cd tmp
yarn init -y
yarn add prettier
echo '<my-component></my-component>' > foo.component.html
prettier foo.component.html
```

**Comment by michaeljota** [comment] 2018-11-07 18:48
@duailibe I've try, and it works as expected. Sorry. Also, I was using `npx` to run prettier, but I trying installing globally and also works.

**Comment by michaeljota** [comment] 2018-11-07 18:50
However, using it as a npm script, `"format": "prettier \"**/*.component.html\""` seems to ignore the config file. Is this expected?

**Comment by duailibe** [comment] 2018-11-07 18:58
@michaeljota Doesn't really matter how you run it.. the config file it uses the first `.prettierconfig` found in a parent folder. It's never supposed to ignore the config file.

As I see it, there are two options:
- You're either running a different version of Prettier (not 1.15). Can you run it with `--version` to make sure you're running Prettier 1.15?
- There's a config file with `parser: "babylon"` (or maybe `flow`, `typescript`) somewhere in the tree. If you run `prettier --find-config-path path/to/your/file.component.html` you can see what config file it's using. If you could share it as well that'd be good!

**Comment by michaeljota** [comment] 2018-11-07 19:11
- Prettier version
With npx:
```
$> npx prettier -v
1.5.1
```
Without npx: 
```
$> prettier -v
1.15.1
```
- Prettier config

```
$> npx prettier --find-config-path "src\app\app.component.html"
Ignored unknown option: --find-config-path

Usage: prettier [opts] [filename ...]
// Options list omitted
```
```
$> prettier --find-config-path "src\app\app.component.html"
.prettierrc
```

**Comment by duailibe** [comment] 2018-11-07 19:17
> ```
> $> npx prettier -v
> 1.5.1
> ```

I think that settles it then :-)

That version obviously doesn't support HTML, and that is before we started throwing errors when a file isn't supported by Prettier (which would happen if you had Prettier 1.14)

I'm closing this since there's nothing we need to do in this case :-)

Let me know if something was not addressed

**Closed by duailibe** 2018-11-07 19:17 UTC
