### ISSUE TITLE
Issue with formatting in EJS

### ISSUE THREAD

**Issue by Ayush-Chugh-2006** [prettier/prettier#11069] opened 2021-06-13 16:43 UTC
Prettier is not formatting EJS with include statements

![Annotation 2021-06-13 221310](https://user-images.githubusercontent.com/69336518/121815531-97446480-cc94-11eb-8819-35eec193856f.png)

Issue is in VScode latest version

**Comment by fisker** [comment] 2021-06-13 16:48
Duplicate of  #8676

**Closed** 2021-06-13 16:51 UTC
Labels: type:duplicate, type:question
