### ISSUE TITLE
Unnecessary comma in arrow function without curly as argument when trailing comma = all

### ISSUE THREAD

**Issue by frontsideair** [prettier/prettier#1490] opened 2017-05-03 08:58 UTC
```javascript
// test case
const remediations = threat._threatRemediations.map(remediation => (
  makeRemediationID(remediation, remediation)
))

// generated, notice the trailing comma
const remediations = threat._threatRemediations.map(remediation =>
  makeRemediationID(remediation, remediation),
)

// if function body is wrapped with curly braces
const remediations = threat._threatRemediations.map(remediation => {
  return makeRemediationID(remediation, remediation)
})

// generated, no trailing comma
const remediations = threat._threatRemediations.map(remediation => {
  return makeRemediationID(remediation, remediation)
})
```

I don't know if that's the desired result, but it seems like it's not. [Live test case](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20case%201%5Cnconst%20remediations%20%3D%20threat._threatRemediations.map(remediation%20%3D%3E%20(%5Cn%20%20makeRemediationID(remediation%2C%20remediation)%5Cn))%5Cn%5Cn%2F%2F%20case%202%5Cnconst%20remediations%20%3D%20threat._threatRemediations.map(remediation%20%3D%3E%20%7B%5Cn%20%20return%20makeRemediationID(remediation%2C%20remediation)%5Cn%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A100%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

PS: If the code looks silly, it's because I trimmed it a bit.

**Comment by vjeux** [comment] 2017-05-03 15:51
It's because there should be a `;`, but you enabled the no-semi option so it isn't printed.

**Comment by vjeux** [comment] 2017-05-03 17:03
I'm going to close this since it is the intended behavior.

**Closed by vjeux** 2017-05-03 17:03 UTC

**Comment by frontsideair** [comment] 2017-05-03 18:17
Ah, makes sense. Still, I'd be expecting the comma if the arrow function wasn't broken up into two lines; like this:
```javascriot
const remediations = threat._threatRemediations.map(
  remediation =>makeRemediationID(remediation, remediation),
)
```

Still, thanks for clarification.
