### ISSUE TITLE
[advice] maybe we can use `line.trim().length` rather than `line.length` to measure the print-width.

### ISSUE THREAD

**Issue by xialvjun** [prettier/prettier#4658] opened 2018-06-08 16:46 UTC
**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMGAGn2HwGEItoECBffAMxwfwHIdTyPANwAdKGLgAPbHnwATOOxIBXADYEwqkgGdt+AOqo5Aczgw9U+FDl76jKM2pj8+ftbg4AFAEonUFy78MMo4-p7OAS4APHKoAG4AfBGR0ST4JABGYAC8IiAAjABMAMx5+GAZ2rkgJQAsZZkk1UWlIEn+KantnV3JKVEk3T0DQ50jfZHjHWNpmTl5LWUVVXl1DRlNCyV5o-2zWc3bIOWV1WvHjYetu5ETAVEA9IN30U83928v+I-P0-2ff0mAJ632BwzBYwhH1iiT63lEHRYYiR4igIAoIAgmBgqGg2mQoBIOC4AHcAApEhD4lAkOIQIzokAZHBkADWZgAypgyKgoMZkDAcMo4BjedoPDAySzjOgSMglKpxRiAFbaSQAIRZYHZMA5JHQcAAMry4PKSIqRSBuThxThkEzMgBPVTQRmYHC8mCGOQwAAWyAAbAAGDHuiDi-QszD291wW1xU0Y-gAR2UqH4UpIMrlSAVSpA4vQqAFQst2l5xlUcAAisoIPAS8KMTBMt6-chas2WahVBW7LL7VAmIzlOKACqZal5y1yCBgM0WjE6GAL8UsFhAA)
```sh
--parser babylon
--print-width 60
--single-quote
--tab-width 4
```

**Input:**
```jsx
import React, { Component } from 'react';

export default class Widgets extends Component {
  render() {
    return (
      <div>
        <a abc="123" cbs="234" aba="123">
        <a>
        <a>
        <a>
        <a>
        <a>
        <a>
        <a abc="123" cbs="234" aba="123">
        <a abc="123" cbs="234" aba="123">
        
        </a>
        </a>
        </a>
        </a>
        </a>
        </a>
        </a>
        </a>
        </a>
      </div>
    );
  }
}


```

**Output:**
```jsx
import React, { Component } from 'react';

export default class Widgets extends Component {
    render() {
        return (
            <div>
                <a abc="123" cbs="234" aba="123">
                    <a>
                        <a>
                            <a>
                                <a>
                                    <a>
                                        <a>
                                            <a
                                                abc="123"
                                                cbs="234"
                                                aba="123"
                                            >
                                                <a
                                                    abc="123"
                                                    cbs="234"
                                                    aba="123"
                                                />
                                            </a>
                                        </a>
                                    </a>
                                </a>
                            </a>
                        </a>
                    </a>
                </a>
            </div>
        );
    }
}

```

**Expected behavior:**

```jsx
// Is it necessary to format code:
                                            <a abc="123" cbs="234" aba="123">
// to
                                            <a
                                                abc="123"
                                                cbs="234"
                                                aba="123"
                                            >

// no, it should just be
                                            <a abc="123" cbs="234" aba="123">
// because `line.trim().length < print_width`
```

**is it necassary just because it has exceeded the `print-width`?**
I don't think so.

Whether to break line should be according `line.trim().length` rather than `line.length`.

My attention should be focused on my code rather than those new lines.

**Comment by j-f1** [comment] 2018-06-08 17:05
Thanks for reporting this! Someone opened an issue about this before, so please follow along there instead.

Duplicate of #4093

**Comment by j-f1** [comment] 2018-06-08 17:05
Duplicate of #4093

**Closed by j-f1** 2018-06-08 17:05 UTC
Labels: type:duplicate
