### ISSUE TITLE
TypeScript 3.8: `import type` & private class fields

### ISSUE THREAD

**Issue by herberthobregon** [prettier/prettier#7326] opened 2020-01-14 16:23 UTC
The new `import type` dosen't work

**Prettier 1.19.1**
> SyntaxError: '=' expected. (11:13)

**Input:**
```typescript
class P{ #private = 1 }
import type {MatchKeysAndValues} from "mongodb";
          let      ugly =  1123
```

**Expected behavior:**

**Output:**
```typescript
// typescript
class P{ 
    #private = 1
}
import type { MatchKeysAndValues } from 'mongodb';
let ugly = 1123
```
also private props should work en `JS ES2020`

**Comment by thorn0** [comment] 2020-01-14 17:17
Duplicate of #7263

**Closed by thorn0** 2020-01-14 17:17 UTC
Labels: lang:typescript
