### ISSUE TITLE
Template literals with long interpolated values format oddly

### ISSUE THREAD

**Issue by josephfarina** [prettier/prettier#5589] opened 2018-12-04 04:26 UTC
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAtgIYDWcAyhIXDABY5QDmAFAJT7AA6U+fXMAUJj5IUAM4iwAJzjF4ASSgAbRnACiyuDVj4AvPnb6AfJx58+smOmm8AqgBUFAGQB0MufE3aEMAGLS1AASMITKLAAG5hZ8ADwAJjgAbvgAJMAADsTSxITiruLUcM7QTHDSAIIwMNI4AEbo8AC+elwgAIxtosrE4uJ6AOTEALRgPX34I1AQ9OWj4+KTw9Oz0sszdHNjveID+PHyIzbKeulZOXmuxCub0iXMVTX1jXBNxtExfGAMyvH4EKh8LN8HAtDpBLxPrEAPSJJLvSF8CJsADc0QETTRUCaIAANCAIBlcNBxMhQNlAgB3AAK2QQpJQxCSEBw8TxIDqOTA5BgFCyYEYTGQNXQcHxdFCygA6gx4OJ+ZR6ThcEllQBPZDgPrsxjicowak5JgkZCoYjKPX4gBW4gAHgAhLk8ii5YpqU3my0gG22iiCrQARXQMzgHotYpA5z10k1dWIdTVymg7IytVgUtZ9GQAA4AAz41MQPVSnIZTWpuDRpKh-GyACO6BwskNxGNxDDXr1hBwwukovx4n9cCDIY7EZg8Yz8SzSAATPiasQcKpmABhagmlDTKA1kDoPUOeMMs3hppNIA)
```sh
--parser babylon
```

**Input:**
```jsx
function makeSomething() {
   				 const createInlineElement = () => {
    return UTIL.createElementFromHtml(`
      <div ${params.someLongerAttribute}="1" class='a-class a-nother-class a-nother-nother-class' data-url=${params.anotherLongAttribute}>
        child of the element
      </div>
    `);
  	};
}
```

**Output:**
```jsx
function makeSomething() {
  const createInlineElement = () => {
    return UTIL.createElementFromHtml(`
      <div ${
        params.someLongerAttribute
      }="1" class='a-class a-nother-class a-nother-nother-class' data-url=${
      params.anotherLongAttribute
    }>
        child of the element
      </div>
    `);
  };
}

```

**Expected behavior:**

Sorry if I am reporting this incorrectly, but came across something that I think is a formatting bug.

Not sure exactly how it should look, but I think the output is pretty ugly as it is and makes it look 
 sort of broken.

**Comment by ikatyang** [comment] 2018-12-04 08:14
This looks like a duplicate of #3368, let's track the issue there.

For this HTML-specific use case, formatting it as HTML (`/* HTML */`) should be better I think:

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAtgIYDWcAyhIXDABY5QDmAFAJT7AA6U+fXMAUJj5IUAM4iwAJzjF4ASSgAbRnACiyuDVj4AvPnb6AfJx58+smOmm8AqgBUFAGQB0MufE3aEMAGLS1AASMITKLAD0AFT4QQ4Ass74UREABuYWfAA8ACY4AG74ACTAAA7E0sSE4q7i1HDO0Exw0gCCMDDSOABG6PAAvnpcIACMw6LKxOLiegDkxAC0YJPT+ItQEPQtSyviawsbW9IHm3Tby1Pis-g58os2ynol5ZXVrsSHZ9KNzO2dPX04P1jBlMnwwAxlDl8BBUPgtvg4FodIJeGCshE8vkQWi+Kk2ABuDICfpEqD9EAAGhAEFKuGg4mQoAqgQA7gAFCoIRkoYj5CA4HJUkDdSpgcgwCjlMCMJjITroODUuihZQAdQY8HE0so3JwuHy+oAnshwNNhYxxC0YOzKkwSMhUMRlFbqQArcQADwAQmKJRQqg01I7na6QB7PRRZVoAIroTZwEMupUgF5W6Sm7rEbpG5TQYWlLqwNWC+jIAAcAAZqYWIFa1ZVSqbC3B0-lE9TZABHdA4WS24j24hJsNWwg4eXSRXU8TRuBxhMjlMwbMlnJlpAAJmpnWIOFUzAAwtQHSgNlAOyB0FaHNmeU7k-1+kA)
```sh
--parser babylon
```

**Input:**
```jsx
function makeSomething() {
   				 const createInlineElement = () => {
    return UTIL.createElementFromHtml(/* HTML */`
      <div ${params.someLongerAttribute}="1" class='a-class a-nother-class a-nother-nother-class' data-url=${params.anotherLongAttribute}>
        child of the element
      </div>
    `);
  	};
}
```

**Output:**
```jsx
function makeSomething() {
  const createInlineElement = () => {
    return UTIL.createElementFromHtml(/* HTML */ `
      <div
        ${params.someLongerAttribute}="1"
        class="a-class a-nother-class a-nother-nother-class"
        data-url=${params.anotherLongAttribute}
      >
        child of the element
      </div>
    `);
  };
}

```

**Comment by ikatyang** [comment] 2018-12-04 08:14
Duplicate of #3368

**Closed by ikatyang** 2018-12-04 08:14 UTC
