### ISSUE TITLE
Flow parser fails to parse comments inside import

### ISSUE THREAD

**Issue by mitermayer** [prettier/prettier#2588] opened 2017-08-03 17:36 UTC
When using the flow parser (`prettier --parser flow foo.js`) with the bellow contents:

``` javascript
import(/* webpackChunkName : "bar" */ 'some/path');
```

returns the following stack trace:

``` javascript
a.js: Error: Comment "webpackChunkName : "bar"" was not printed. Please report this error!
    at astComments.forEach.comment (/home/miter/tmp/playground/node_modules/prettier/index.js:13684:13)
    at Array.forEach (native)
    at ensureAllCommentsPrinted (/home/miter/tmp/playground/node_modules/prettier/index.js:13682:15)
    at formatWithCursor (/home/miter/tmp/playground/node_modules/prettier/index.js:13720:3)
    at Object.formatWithCursor (/home/miter/tmp/playground/node_modules/prettier/index.js:13942:12)
    at format (/home/miter/tmp/playground/node_modules/prettier/bin/prettier.js:5524:19)
    at filename (/home/miter/tmp/playground/node_modules/prettier/bin/prettier.js:5637:16)
    at patterns.forEach.pattern (/home/miter/tmp/playground/node_modules/prettier/bin/prettier.js:5703:7)
    at Array.forEach (native)
    at eachFilename (/home/miter/tmp/playground/node_modules/prettier/bin/prettier.js:5698:12)
```

**note**
Using the default parser (`prettier foo.js`) does not create any error

This issue was found by: https://github.com/prettier/vim-prettier/issues/31

**Comment by existentialism** [comment] 2017-08-03 17:40
This is a duplicate of https://github.com/prettier/prettier/issues/2555.

**Closed by existentialism** 2017-08-03 17:40 UTC
