### ISSUE TITLE
Add CLI option to only format known file types

### ISSUE THREAD

**Issue by toshi38** [prettier/prettier#8803] opened 2020-07-20 19:17 UTC
**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: CLI
- Runtime: Node v10.19.0
- Operating System: Linux/Windows (Tested both)

**Steps to reproduce:**

Run `prettier --write .prettierignore`

**Expected behavior:**
Prettier ignores this file as it does not how to format it.  (Note that running `prettier --write .` works however that's not an option if using lint-staged or similar when you want to only run prettier on the files that are changed and staged not all files in the repo.  (`lint-staged` is a plugin that passes a list of files to the tool specified as suggested in the documentation: https://prettier.io/docs/en/precommit.html)

**Actual behavior:**
```bash
$ git commit -m "Update .prettierignore"
husky > pre-commit (node v10.19.0)
✔ Preparing...
⚠ Running tasks...
  ❯ Running tasks for *
    ✖ prettier --write [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up... 

✖ prettier --write:
[error] No parser could be inferred for file: .prettierignore
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Similar issues:**
I did a search and found the following issues, but they are locked and the answer does not apply when using a tool like lint-staged (you can not use `prettier --write .` which is the suggested work around/reason for resolving).
https://github.com/prettier/prettier/issues/6101
https://github.com/prettier/prettier/issues/4907
https://github.com/prettier/prettier/issues/2691

**Comment by kachkaev** [comment] 2020-07-20 19:44
Here is how this can be solved without any changes to Prettier:

* [`.prettierignore`](https://github.com/kachkaev/njt/blob/8ff7c1bbf6bafff90e44122f304c6915ca0c6555/.prettierignore)
* [`package.json` → `"lint-staged"`](https://github.com/kachkaev/njt/blob/8ff7c1bbf6bafff90e44122f304c6915ca0c6555/package.json#L32-L38)

The idea is in ignoring files with all extensions and then 'un-ignoring' those extensions that are supported by Prettier. Doing so not only simplifies the configuration of pre-commit hooks, but also package.json scripts and editor integration.

**Comment by toshi38** [comment] 2020-07-21 06:00
Thanks for the quick response!

So then the official suggested way to support this is to ignore everything, then _un-ignore_ only the extensions supported by Prettier?

I still find it a bit surprising/unexpected that `prettier --write .` (with an unsupported located in `.`) gives different behaviour then `prettier --write <some-unsupported file>` 

A couple of quick questions:
- Is there a list of files types that are currently supported?
- Any recommendations from a maintenance perspective as new file types are supported by Prettier?
    _I guess that these files would only need to be updated anytime you change the prettier requirement since it's pinned exactly._
- If this is the recommended way of supporting lint-staged would Prettier be open to a PR in the documentation suggesting this to make it clearer?

**Comment by thorn0** [comment] 2020-07-21 07:24
Duplicate of #8136

**Closed by thorn0** 2020-07-21 07:24 UTC
