### ISSUE TITLE
Request: Extend formatting from html`` and css`` to this.html`` and this.css``

### ISSUE THREAD

**Issue by timonson** [prettier/prettier#8672] opened 2020-06-30 06:27 UTC
Now that `prettier` has implemented formatting for html and css code inside JavaScript/TypeScript [tag functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_templates) I would like to request to expand this behavior to the same syntax but with a `this.` in front of `html` and `css` respectively. Several frameworks use class methods for their `html` and `css` functions.

#### Actual Behavior

```typescript
html`
<div>
  <p>text</p>
</div>
`
```

#### Requested Feature

```typescript
this.html`
<div>
  <p>text</p>
</div>
`
```

What do you think? Thank you!

**Comment by fisker** [comment] 2020-06-30 07:05
Duplicate of  https://github.com/prettier/prettier/issues/7573.  Can you copy your request into #7573?

**Closed by fisker** 2020-06-30 07:05 UTC
