### ISSUE TITLE
Typescript Range Formatting Indentation

### ISSUE THREAD

**Issue by ericjohney** [prettier/prettier#7148] opened 2019-12-17 23:50 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt8xLSBnevAFTnv2AB0o88NsAlgDdS8PBABGAKzwBePMDwD6rdkjwxs5OHgC+3XSAA0ICBhgDo9ZKFLZsEAO4AFOwmspSQiAILGQEtikYADWcDAAyhjBAlAA5sia2iYAFjAAtpQA6ikC8PTRYHAR7nnCeQCeyOCM-rH0cLjOQXHppMhklA0mUvRoAEJBoeERpOlwADKxcB2kXXA9fRGxcZRwAIrkEPCz8ybR2A3Y1TAVGGxggub+-LEwWb4wKcgAHAAM+w4NWUEY1fxsRpCGYmACOW3gzTMHhADAAtFA4HAiH4TNg4OCBOjmqRWu0kJ1uiAGukBIktAtiSs1pttjMCXMiTBSBIHgQnsgAEwmTSkASUFYAYQg6Ta1Sg0BBIHIDWYLI8hMpQm0AEkoERYBFLgJzABBdURU5rXZEoLxOAAUXVyAArABONGkc2GuwwLl23S6IA)
```sh
--parser typescript
--range-end 59
--range-start 29
```

**Input:**
```tsx
export default class Test {
  private obj = { isTest: true }
}
```

**Output:**
```tsx
export default class Test {
                 private obj = { isTest: true };
               }
```

**Expected behavior:**
```tsx
export default class Test {
  private obj = { isTest: true };
}
```

It appears formatting with a range inside a class will start indenting from the start of the class keyword, and not the indentation level of the line containing the class keyword. This is different output behavior than formatting without the range

**Comment by calvinalvin** [comment] 2019-12-17 23:52
+1 bump

**Comment by lydell** [comment] 2019-12-18 07:13
Duplicate of #4926?

**Comment by evilebottnawi** [comment] 2019-12-18 14:56
@lydell partial

**Comment by thorn0** [comment] 2020-05-25 16:10
Closing in favor of #4926

**Closed by thorn0** 2020-05-25 16:10 UTC
Labels: area:ranges, type:bug
