### ISSUE TITLE
add prettier --init

### ISSUE THREAD

**Issue by izelnakri** [prettier/prettier#5940] opened 2019-03-05 12:21 UTC
I've just read this thread and I cant write to that thread anymore, please disable this bot behavior, it is counter-productive: https://github.com/prettier/prettier/issues/394

prettier currently ships with a cli when one runs `npm install -g prettier`. If you are already shipping a cli please also provide a way to initiate it, it is completely reasonable and expected behavior:

`prettier --init` -> creates .prettierrc file if it doesnt exist.

please check eslint cli for similar possible enchancements.

**Comment by j-f1** [comment] 2019-03-05 13:16
I don’t think this is a necessary feature. Prettier works just fine without a config file (like in this project).

**Comment by j-f1** [comment] 2019-03-05 13:17
Also, is #394 the issue you meant to refer to?

**Comment by duailibe** [comment] 2019-03-11 13:37
I think you meant #3944, and that thread is already pretty clear about why we didn't add then and we're not going to add now.

Duplicate of #3944

**Comment by duailibe** [comment] 2019-03-11 13:37
Duplicate of #3944

**Closed by duailibe** 2019-03-11 13:37 UTC
