### ISSUE TITLE
<!-- prettier-ignore --> in a html file does not work

### ISSUE THREAD

**Issue by HummingMind** [prettier/prettier#16829] opened 2024-11-08 01:07 UTC
Given the code below in an HTML file, prettier errors out:
```
<!doctype html>
<!-- prettier-ignore -->
<html<!--htmlAttrs-->>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--headTags-->
    <!--preload-links-->
  </head>
  <!-- prettier-ignore -->
  <body<!--bodyAttrs-->>
    <!--bodyTagsOpen-->
    <div id="app"><!--app-html--></div>
    <script type="module" async src="/node/entry-client.js"></script>
    <!--bodyTags-->
  </body>
</html>
```
Doesn't like these two lines:
`<html<!--htmlAttrs-->>`
`<body<!--bodyAttrs-->>`

Error:

`["ERROR" - 7:05:04 PM] Opening tag "html" not terminated. (3:1)`

This is in VSCode. Latest version of the extension, and the package.

**Comment by rijenkii** [comment] 2024-11-08 04:59
The HTML is invalid. It is forbidden to have comments *inside* the start tag:
https://html.spec.whatwg.org/multipage/syntax.html#start-tags

Prettier cannot even parse the file to ignore parts of it.

**Comment by kachkaev** [comment] 2024-11-08 11:12
@rijenkii, correct. Closing as intended behavior.

**Closed by kachkaev** 2024-11-08 11:12 UTC

**Comment by HummingMind** [comment] 2024-11-08 15:30
> @rijenkii, correct. Closing as intended behavior.

@kachkaev the report was on `<!-- prettier-ignore -->` not skipping/ignoring the next line. I know the spec is not valid, that's why I explicitly wanted to ignore those lines.

**Comment by rijenkii** [comment] 2024-11-08 16:45
Prettier parser cannot understand the file you are feeding it. To ignore parts of the file, prettier needs to first understand what is in it.

And it should not understand the file you are trying to pass, as it is really invalid. Try feeding it to the [validator.w3.org](https://validator.w3.org/#validate_by_input) (the HTML validator made by the creators of HTML), it will scream at you as well:
![image](https://github.com/user-attachments/assets/98e35306-157d-4a93-81d6-68e283020734)

**Comment by HummingMind** [comment] 2024-11-08 17:42
@rijenkii 
So it can't skip the (next) line that is marked to be skipped, during parsing? If that is the case, and the enttier file needs to be parsed first, then yeah, I get why it wouldn't work.

Thank you for the clarification. 🍻
