### ISSUE TITLE
Weird behavior for empty yaml properties?

### ISSUE THREAD

**Issue by selbekk** [prettier/prettier#4982] opened 2018-08-15 07:49 UTC
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBXAznATlAhgWziQAJ8BPAVUxwLgB0oAHXddAdwiwBMkHqA3bCXIA6AdhGR8IADQgIjGAEto6ZKFxYsENgAVNCNSlz8ISrrJAAjLLjABrODADKzMEqgBzZDCyo4ch7UMLq2nvi4yABmuAA2mHIAVugAHgBCtg5OzrQAMh5w0XEJIMxY1MggZASxloxYHjAA6uYwABbIABwADHL1EJhNtoyV9XDillhwAI6oSlOhuOGRSDHxASCY+Eo+fhvoHp6xcACKqBDwRetyMLhWLVztyABMN7ZKsYcAwhD4EZVQaCFOQYOAAFTuRjWmAAvjCgA)
```sh
--parser yaml
```

**Input:**
```yaml
username: myUsername
password:
server: my.server.com
```

**Output:**
```yaml
username: myUsername
? password
server: my.server.com

```

**Expected behavior:**
I'd expect it to do nothing - I'm not sure what this question mark is and why an empty property can't be left alone?

This might be me just not understanding YAML's syntax, of course, but there isn't a lot of docs out there.

**Comment by ikatyang** [comment] 2018-08-15 07:54
It's the syntax for explicit keys.

Duplicate of #4971 and should be fixed by #4972.

**Comment by ikatyang** [comment] 2018-08-15 07:54
Duplicate of #4971

**Closed by ikatyang** 2018-08-15 07:54 UTC

**Comment by selbekk** [comment] 2018-08-15 07:58
Oh thanks!
