### ISSUE TITLE
Removing parentheses around comma separated values breaks the code

### ISSUE THREAD

**Issue by yumauri** [prettier/prettier#11578] opened 2021-09-25 22:08 UTC
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzKmC8mAFAJQEB8xAHmfpUQAwA0mNAOlCEyBAA4wBLdMlABDAE7iIAdwAKEhGmQhRAG2miAnku4AjcaLABrODADKogLZwAMgKhxk2NWjh6Dx02d6H7Ac2QYcQBXNxA4S104ABNomJtRKD9g0T84ADEIcUtRGEEk5VFgmAguEAALGEtVAHVygXg0HzA4M0UGgQA3Bs1lMDQdEHtXcRhZAz8cpxcwgCs0KjN-VTgARWCIeGnVV24fcRHlXVEo1TLecXsYGoFomHLkAA5mEAuIVxqDXmULuBHOxzcACOG3g4z4ShQojQAFoHDEYmVxHAQQJkeNUlMkM4dmFXJYBIEQnjlmtQY5sTNuDATjc7g8kAAmakGASqfwAYQglix4TQAFYysFXAAVE6QnG7ECdUIASSgcVgZjAl34AEEFWYYJoVttXABffVAA)

```sh
--parser babel
```

**Input:**

```jsx
const fn = () => (x) => (0, x)

```

**Output:**

```jsx
const fn = () => (x) => 0, x;

```

**Expected behavior:**

Parentheses stays as they are.

**Comment by fisker** [comment] 2021-09-27 03:05
I think this is duplicate of #10955

**Closed** 2021-09-27 03:21 UTC
Labels: status:has pr

**Comment by yumauri** [comment] 2021-09-27 05:34
Thank you! Didn't find that one.
