### ISSUE TITLE
Prettier v3 leaves empty lines when chaining methods

### ISSUE THREAD

**Issue by tsvetkovda** [prettier/prettier#15437] opened 2023-09-20 14:09 UTC
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAjAGgAQCYcDMOUArgDZkC6AOlLQHQBmAlmfAE4AUAQhBGXACGUAJS0GAW0EAHTiIDctEJhARpMZtADOyUIPbsIAdwAK+hDpSCyRwQE8dKgEbtBYANZwYAZUES4ADLMUHDIjNZacM6uHl7e0m7BAObIMOwkUSCREsyp6ZlayQIAiiQQ8GERmQBWWgAe3kVwpeWhSOFkkSoAjmXwJobSliCCWgC0IXAAJtPKIGmCrMkAwhASUsgjFHOFUEkCAIIwacxOJP1w7EEhlZ2ZABYwEmQA6vfM8FoJYHDeFh-MABuHzsmzAWkcIEBGQAklAZrBvGB2Mx1Ad4d4YHYBLcuiBpIZIi9XNJNgS4JF2IDQipgpSYANBEkNu0qioEuxKZsnIInHAyHMCcEYC9mFMYPdkAAOAAMKnYcF6zAVjOZglxmRgvNF4slSHwIBIkQAKrzLB08XAJHypjMpgFhEkSEy4AAxCDsKTHZKbQTnCAgAC+gaAA)

```sh
--parser babel
```

**Input:**

```jsx
[1, 2, 3, null]

.filter(Boolean)

.map();

```

**Output:**

```jsx
[1, 2, 3, null]

  .filter(Boolean)

  .map();

```

**Expected behavior:**
```jsx
[1, 2, 3, null].filter(Boolean).map();

```

**Comment by auvred** [comment] 2023-09-20 16:28
Judging by the tests, that's the intended behavior, isn't it?

https://github.com/prettier/prettier/blob/6bff776efd0951b7812818d02d1cae3fda184737/tests/format/js/preserve-line/__snapshots__/jsfmt.spec.js.snap#L531-L592

**Comment by sosukesuzuki** [comment] 2023-09-22 12:58
@auvred Thank you! You are right.

**Comment by sosukesuzuki** [comment] 2023-09-22 12:59
This is a intended behaviour so we close this as a not plannnig.

**Comment by tsvetkovda** [comment] 2023-10-02 16:27
Thank you for your help!

**Closed** 2023-10-04 14:57 UTC
Labels: type:bug, lang:javascript
