### ISSUE TITLE
(markdown): Wrong escaping instead of leaving it italic

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#5148] opened 2018-09-26 19:47 UTC
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB9AYgJwgWwAQDmAhjAM4BGAnngBYwwAOSA9MwDYRhFs0SkxIAHAAZRqcQUxEGNAI5s8AE06lUAHSggANCAgMYAS2ilkoIpmwB3AArmEJlEQBuEA4u0hyUsAGs4MAGUGIjADKAJkGEwAVzgdMNI4TBhrKQIcImQAM25EnQArUgAPACFvP0CiHDgAGTC4bNy4kGDMRMxkEAzMH2VLTR0GTDCYAHU3GBpkEUHsRNGpBk6huHanBp1MOFlogy3UonTMpBy2PJBEnANImObSMII2OABFaIh4RrPmmCJyccVJsgAEw6KJEAxsB4AYVwGU6UGgGxA0USABVfg5TokAL7YoA)
```sh
--parser markdown
```

**Input:**
```markdown
_From gatsby http://localhost:8000___graphql docs_

```

**Output:**
```markdown
\_From gatsby http://localhost:8000___graphql docs\_

```

**Expected behavior:**

Unchanged (I guess)

**Comment by lipis** [comment] 2018-09-26 20:04
Source https://github.com/gatsbyjs/gatsby-starter-default/pull/91 (I edited the README manually in that PR)

**Comment by ikatyang** [comment] 2018-09-27 01:46
Looks like the same root cause as #3837, let's track it there.

**Comment by ikatyang** [comment] 2018-09-27 01:46
Duplicate of #3837

**Closed by ikatyang** 2018-09-27 01:46 UTC
Labels: lang:markdown, type:bug
