### ISSUE TITLE
TypeScript: Extra parens on functions in a union can remove too many parens

### ISSUE THREAD

**Issue by orta** [prettier/prettier#6634] opened 2019-10-09 18:16 UTC
When running prettier across all of definitely typed we spotted a parse error in prettier when running over it a second time (for good luck)

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAFjGAHAZyXQHMBLGLAVwCMA6SAW1QBE4AzMqCuAGwE8AKvzxwAJqw5ceA4aIk1eEGqnYAGAKxwAhgCYAjGACcYmjXEAOAOxGaauEbXbta-VYDM7-ffZWwT7Rp9VBgROAJUAHc4GjxtMABrAFptAgI4GAIkxm1udnCYVC4xOAAPOjE6TIBiABlvKwAdKGaSsF5tACc4DChtRnC4sB6AdRihhIBBNIyCAFlcsnyCGAxgZoxNjC54TvZ4noB5PBgyaAI15o2tzfQMFggEAgByVaY8Ml44a5u8Wl4yGAAAraSgAfiQGBWnS4JAwAB8MDQIBAvrkEb0qLxeBiABT4zhfPoDSHQ2EAGgwOTyBUhY1i8SmM0yCxpKwAlBgALwAPihMBhUBI7PZAG4flsJbdMA9wlBXhh3p9vlAbps-opASDKCwlvlurAgRACBQzlAIfzBXDEVAsTjEfjcYSEP04KSBRSqYtljA6eNGdN0izvQVObzLbCRRikSi0VBxaq1VKMHcRhBOgkCMmNQDgaCsCMKFgIFQYABRUoC7Qgg0EC1koUY23YvFO5XEt0RoWU6lLWkYekTQOzVl9jncvkN4XR5GonTxiUAX2ai5A5JAEBOZoIyFAXU6EEiNaeyBA2gAbhAyGI1yAaJ1GRkAMpDWHIAVUODrnCMXgjLA8AQQxwE+TymueFD8KeYBpLeXDpJ0MBAg+JA5Mg+y8Ok64AFYEKUABCD6JM+rq1FwcDodomFfiAuGlE+sJfAAilQEDwJR1HrnEnQIaeoSiAQYAwict54IKMCFmIlDIBYahcQe6QjA+eCnmJ4RwJ054UeuACOrHwMhm47igqRJFAcDiOIt7dHpZDdMh2iodoHFYSA6SMGQ76dJ+64mkKzH6RRSAYa5MCBJJ0lILo65Vp8sIAMIQIwaEoFA0DaSAVDpIIgTGSFcCLouQA)
```sh
--parser typescript
```

**Input:**
```tsx
// https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f05ea21c9dbbed879b0e90aa0173310ef7c0aab1/types/webpack-assets-manifest/index.d.ts#L107

declare namespace WebpackAssetsManifest {
    interface Options {

      // Doens't compile
      publicPath?: string | boolean | null | (((filename: string, manifest: WebpackAssetsManifest) => string));
      
      // Doesn't compile
      publicPathDifferentPosition?: string | null | (((filename: string, manifest: WebpackAssetsManifest) => string)) |  boolean;
      
      // Works
      publicPathWithoutExtraParens?: string | null | ((filename: string, manifest: WebpackAssetsManifest) => string) |  boolean;
    }
}
```

**Output:**
```tsx
// https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f05ea21c9dbbed879b0e90aa0173310ef7c0aab1/types/webpack-assets-manifest/index.d.ts#L107

declare namespace WebpackAssetsManifest {
  interface Options {
    // Doens't compile
    publicPath?:
      | string
      | boolean
      | null
      | (filename: string, manifest: WebpackAssetsManifest) => string;

    // Doesn't compile
    publicPathDifferentPosition?:
      | string
      | null
      | (filename: string, manifest: WebpackAssetsManifest) => string
      | boolean;

    // Works
    publicPathWithoutExtraParens?:
      | string
      | null
      | ((filename: string, manifest: WebpackAssetsManifest) => string)
      | boolean;
  }
}

```

**Expected behavior:**

It should always keep params: `((filename: string, manifest: WebpackAssetsManifest) => string)`

**Comment by thorn0** [comment] 2019-10-09 20:09
Duplicate of #6603

**Closed** 2019-10-09 20:10 UTC
Labels: type:duplicate

**Comment by thorn0** [comment] 2019-10-09 20:29
> running prettier across all of definitely typed

That's something I've been wanting to do. So is this the only issue you've found?

**Comment by orta** [comment] 2019-10-10 19:48
I got pretty far, but called it due to some complications around deploys and bumping TS versions to ensure consistent support for the syntax which prettier uses. There's a longer explanation in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35672 👍

**Comment by thorn0** [comment] 2019-10-10 19:54
If needed, consider opening an issue to discuss adding workarounds for those syntax issues. E.g. we can probably parse the comments like `// TypeScript Version: 2.3` and conditionally disable that syntax for union types.

**Comment by thorn0** [comment] 2019-10-10 20:17
It's not that recent though. At least it [works](https://www.typescriptlang.org/play/index.html?ts=2.4.1#code/C4TwDgpgBAHlC8UA+UDkBDVy0CNUG4BYAKCA) in 2.4.1.
