### ISSUE TITLE
Broken MDX formatting with proseWrap (and unstable prettification)

### ISSUE THREAD

**Issue by benjie** [prettier/prettier#13586] opened 2022-10-06 13:03 UTC
When prettier formats MDX it can break just before a tag, putting the tag as the first entry in the next line. In MDX this makes the line into a new paragraph, which prettier recognizes, so if you re-format the output it will turn it into a new paragraph.

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGATAZgCwFYBsA7ABwCcABBjgSRVXkWZVg7c9Y3SzU-T1xzYAeGAEMA5uQD0APnIB3CACcAJgGcFy9SAA0ICAAcYAS2hrkoUUqUR5ABSsJzKUQBt5ogJ7m9AIyWiYADWcDAAyqIAtnAAMsZQcMgAZm5qcH4BwaFhBoHx4sgwSgCu6SBwkb5wKirVMaJQ4sUScABiypGiMCaNyCCixTAQuiAAFjCRrgDqo8bwarlgcGFOc8YAbnOefWBqPiDxaUowdgHincmpZQBWagAeYfmucACKxRDwl65perlKR31Iio7iMDEp4jApsYVDBRshiAAGX42NJTAIGPpuDzeEYAR3e8FOhmc-TUAFoEtVqiMlHB8cZaacJBckClvmU0pFjIUShynq8CYlWVc9GJfFCYXCkOhRQFjK58gBhCCRFnlNS4EbFNIAFVEvmcbJ+IHWpQAklBarAwmBwUYAIKWsIwTzPL5pAC+HqAA)

```sh
--parser mdx
--prose-wrap always
```

**Input:**

```mdx
123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 <tag /> words words
```

**Output:**

```mdx
123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789
<tag /> words words

```

**Second Output:**

```mdx
123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789

<tag /> words words

```

**Expected behavior:**

Output should be:

```mdx
123456789 123456789 123456789 123456789 123456789 123456789 123456789
123456789 <tag /> words words

```

Prettier should refuse to break before an HTML tag or JSX component in MDX (unless it's at the start of a line).

**Comment by fisker** [comment] 2022-10-06 13:09
Looks similar to #12649

**Comment by thorn0** [comment] 2022-10-09 19:51
Duplicate of #12649

**Closed** 2022-10-09 19:51 UTC
Labels: type:duplicate
