### ISSUE TITLE
Empty line between two comment lines/blocks is not being preserved in typescript

### ISSUE THREAD

**Issue by ChristopherHaws** [prettier/prettier#15260] opened 2023-08-17 18:56 UTC
**Prettier 3.0.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEAOMCW0SmwAOlJpgPRWYDCEAtowlgDb5RzmU24HQAjMRgAnAK5wANOR7VaDZq0wcucvnkJQATCInS56gFT0mLWGkwAjNhDABrTEarqq-LQGY9kmVGOmlC2tbBycXCnl3aAAWbwMI4xNFcxhLGztHZ1coqABWON9EgJS0kMzw3jdNaAA2AvIAXwBuECkQHLRkUABDUVEIAHcABV6ETpRugDcIfAATVpArUW6HOBgAZW6WABlOOGQAM262NGlF5dWNnBXOAHNkMR8QU8Z8B-02tDu2OABFcQg8EOx1ObQAVmgAB7rb5-AFApBHE5nACO8LgQ36OHGIG6aAAtFw4LNiQsxN18KpbslusgQFBoPtPrCAIIwMT4KzieBDOCiXZcYHItoACxgjDYAHURfh4GhrmA4OsxrL8JNZQBPOlgNCdNqTSQASSgJNg6zAonweBZJvWMA1PyFoJAOH6p0lyxwdNdcFOokmTJAnD9MEx3VujFpiJBZ2uoj9dPtOF9FqtMAWrs4MElcxgIuQAA4AAxtURwNH4MthiNRpHOmDdKw52Z55DaNriU4AFUb4zrZzgjCsxJJs223Sgt3E4bgADEIKJI+y7nTutyIAsIZCAEIXexrTY7PZOuANBpAA)

```sh
--parser typescript
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```tsx
const option: {
  // Comment line
  //option1: true,

  // Comment line
  //option2: true,
  
  /* Comments block */
  //option3: true,

  /* Comments block */
  //option4: true,
  
  /** Comments block */
  //option5: true,

  /** Comments block */
  //option6: true,
};
```

**Output:**

```tsx
const option: {
  // Comment line
  //option1: true,
  // Comment line
  //option2: true,
  /* Comments block */
  //option3: true,
  /* Comments block */
  //option4: true,
  /** Comments block */
  //option5: true,
  /** Comments block */
  //option6: true,
};

```

**Expected behavior:**
[Per the docs, empty lines should be preserved](https://prettier.io/docs/en/rationale.html#empty-lines)

```tsx
const option: {
  // Comment line
  //option1: true,

  // Comment line
  //option2: true,
  
  /* Comments block */
  //option3: true,

  /* Comments block */
  //option4: true,
  
  /** Comments block */
  //option5: true,

  /** Comments block */
  //option6: true,
};
```

**Comment by kachkaev** [comment] 2023-08-17 23:59
Duplicate of https://github.com/prettier/prettier/issues/15223 (PR welcome 🙏)

**Closed by kachkaev** 2023-08-17 23:59 UTC
