### ISSUE TITLE
Support custom html tags

### ISSUE THREAD

**Issue by hoodmane** [prettier/prettier#14469] opened 2023-03-07 14:16 UTC
Similar to https://github.com/prettier/prettier/issues/4260 except instead of 
```js
my_template_tag`
	blah
`;
```
I would like
```html
<my-custom-html-element>

</my-custom-html-element>
```
For instance, suppose I have a custom config html element whose body is toml. Toml is whitespace sensitive. Ideally it would be formatted as toml, but failing that it at least needs to be left alone. Currently I use a fork of prettier with `isScriptLikeTag` patched to recognize my custom element, but it would be nice to have an API for this. For comparison, prismjs defines an `addInlined` function that can be used to define what parser should be used for custom html elements:
https://github.com/PrismJS/prism/blob/master/components/prism-markup.js#L93-L104
an API similar to this would be very helpful.

**Comment by kachkaev** [comment] 2023-03-09 23:28
Hi @hoodmane! Could you please use the [issue template](https://github.com/prettier/prettier/tree/main/.github/ISSUE_TEMPLATE)?

**Comment by hoodmane** [comment] 2023-03-13 21:35
### Input 

Suppose I have a custom DOM element `<my-config>` whose body is toml, so my html looks like:
```html
<!doctype html>
<html lang="en">
    <head>
        <script defer src="index.js"></script>
    </head>

    <body>
<my-config>
[dependencies]
asn1 = { version = "0.13.0", default-features = false }
pem = "1.1"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
</my-config>
    </body>
</html>
```
and maybe `index.js` looks like:
```
const config = toml.parse(document.querySelector("my-config").innerHTML);
doSomethingWithConfig(config);
```

### What prettier does 
Prettier formats it like this:
```html
    <my-config>
      [dependencies] asn1 = { version = "0.13.0", default-features = false } pem
      = "1.1" [features] extension-module = ["pyo3/extension-module"] default =
      ["extension-module"]
    </my-config>
```
which is not valid toml anymore so `toml.parse` raises an error now.

### What would be nice

Some way to have a prettier plugin that can tell Prettier either that
(a) <my-config> is whitespace / newline sensitive and shouldn't be formatted or even better
(b) to apply a toml formatter to the contents of `<my-config>`.
In particular I want this to be possible without forking prettier (as I am currently doing) or copy-pasting the entire HTML formatting code into my plugin (if you do this it is possible in a plugin but I want to reuse the existing logic not copy paste it).

What my desired output looks like is:

```html
<!doctype html>
<html lang="en">
  <head>
    <script defer src="index.js"></script>
  </head>
  <body>
    <my-config>
      [dependencies]
      asn1 = { version = "0.13.0", default-features = false }
      pem = "1.1"

      [features]
      extension-module = ["pyo3/extension-module"]
      default = ["extension-module"]
    </my-config>
  </body>
</html>
```

**Comment by kachkaev** [comment] 2023-03-14 11:20
This is a rather task-specific request, so I am going to close it. Whitespace handling inside HTML tags is predetermined – Prettier uses [`html-styles`](https://www.npmjs.com/package/html-styles) package to decide how to approach each tag. Making whitespace handling configurable would conflict with the HTML spec and also go against Prettier’s [Option philosophy](https://prettier.io/docs/en/option-philosophy.html).

If you do want `my-config` to not collapse whitespace, you can wrap it with `<pre>`:

**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEwmGBPABzgAIALGAWwBsA+AHSlXOuKoEMoBzAXjpAT70oxEcVQAjCJjxDUBAE5waqCngC0kKADMAlpyEBtTHCJRjUMDrgBnALoM21qAEZi3YsGIA3OPOs7oN2I+AAYAOmcAZjCQvgAaYmMtNgBXKhg1LTg2GBTFayDkqmsSAF8GIgogvmcIvgYGAyycvJt7KDgAD3gof2g1Cik0kncDPgI8CEiAei6evqgBoao4Pnak1PSgsf5uhAWlzGG1hlRp1Q1oXX0zhSUGUTFpyWlZaeZaEDiQCAIYAN6yFAbHk8ggAHcAAog-bIEBsKjgth4axfEDieRsMAAazgMAAymwKHAADI6DrIIolb4YrG4gkELHkzjIGDyFJwb5wCjiOCYYyYEkcTgpNicOAAMQg8goOX+XDhqRgEDRHwA6qQdPBrIywHB8fstTovFq8HCwNZUd9ySV5DBIZjOLLKQjqSAAFbWTr45krACKKQg8BdxU5IEZfl8cI+aIU5Jgap0mBgpGQAA4Qt8FBASmrMQQ4XdbT40QBHQPwB2-VEoRxqDp8vloxTlnSKB1i51IKlhkoUHSs9m931wACCMDZOnEKUrvjJFO7ruHXH9FbgIbdMDY4kTydTSAATN82WwdFRmQBhCAULv8awAVjRKRKABVtzWe98vByAJJmBAEmA8g6H8o5mPi+ArBucClKUQA)

```sh
--parser html
```

**Input:**

```html
<!doctype html>
<html lang="en">
    <body>
<pre><my-config>
[dependencies]
asn1 = { version = "0.13.0", default-features = false }
pem = "1.1"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
</my-config></pre>
    </body>
</html>
```

**Output:**

```html
<!DOCTYPE html>
<html lang="en">
  <body>
    <pre><my-config>
[dependencies]
asn1 = { version = "0.13.0", default-features = false }
pem = "1.1"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
</my-config></pre>
  </body>
</html>

```

Note that Prettier won’t add leading spaces because that would change the contents of your tag and thus violate the [correctness principle](https://prettier.io/docs/en/rationale.html#correctness). 

If this behavior is not sufficient, feel free to patch a local copy a Prettier to meet the needs of your project. You can use [`patch-package`](https://www.npmjs.com/package/patch-package) if your dependency manager does not support patch creation out of the box.

---

Please follow the [issue template](https://github.com/prettier/prettier/tree/main/.github/ISSUE_TEMPLATE) in the future. The first issue comment needs to contain a link to Playground from which we can reproduce the behavior.

**Closed by kachkaev** 2023-03-14 11:20 UTC

**Comment by fisker** [comment] 2023-03-14 11:32
Another problem to support this, we can't parse it at-all [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEwmGBPABzgAIALGAWwBsA+AHSlXOuKoEMoBzAXjpAT70oxYkzhtMQkSNQBnMACcAlgRjFMcAGZwFxWQrC8QSqBoAeAOgBWswagD085aqmj7pcZIYyARhEx4rjIUeAC0kFCaSpxB0gDaGkSmCGBKcLIAut7SImyyUACMxNzEwMQAbjqyStDFxHwADBYFAMwWDXwANOpabACuVDCh2mwwfQrpdZpsVLIkAL7ZOUQUdXwFzXwMS-EjYxOZOyJwZvBQ1dChFP4DJCVxfAR4EC32J2cXUFc3VHB8WcIcj1pgM1Pc+Kg2KFmFRQjA2JxQlQlABrOD0EAAnIOELhaBRGLZBx+AJCBwwmggTogCCqGrnZCgNgKBQQADuAAVmQhZMgQDM2Ww8LzqT4FGwwGiYABlNgUOAAGRMcGQ01mcFF4slcBlBAlJk4yBgCj6Gv4FB8cEwGkwCo4nD6CLgADEIAoKKMYAa+f0YBAqSAYQB1UhKeCyPVgODSnlhpTlMN4PlgWQi4znHQwDnizge1UzObUmxmaUG34ART6EHg+fV1L1CjmCj5MIDBGUsCDSkwMFIyAAHA166y5kHxQQ+e30jpKgGAI5V+DZ2m8lB5UJQOBWq0BiYLpQTbMIvNINWFkBzChKI0ms3VLi-ACCMGNSh8fSXOiVm9r5-vnArRcVVPAszXhHwux7PskAAJmpY02CUZEuAAYQgCgT34WQAFYAz6OYABU2B8VczzNcpTQASWSWBpUUFQYEfUxpXwX5fzgeZ5iAA) unless we use [`getTagContentType`](https://github.com/prettier/prettier/blob/0894348de8170e9819c18da0fe856d5a67520ddf/src/language-html/parser-html.js#LL418C7-L418C24)

**Comment by kachkaev** [comment] 2023-03-14 11:33
I did not think about using inline comments, but that can potentially work (although not without downsides). Feel free to reopen this issue now or wait for this feature request from more people 🙂

**Comment by hoodmane** [comment] 2023-03-14 11:55
Thanks @kachkaev for the quick response. Did you mean to add a `not-planned` tag instead of `intended`?

I'm sorry for not writing a more detailed request, if others want I can try to write a better feature request. I think the reasons for / against are basically the same as the reasons for/against #4260. Well except that #4260 seems more popular.

Forking prettier to add this behavior suits my personal needs reasonably well.

**Comment by alexander-akait** [comment] 2023-03-14 12:12
@fisker Do we have an issue for support them? Because I am thinking we should consider it and provide how to do it better

**Comment by fisker** [comment] 2023-03-14 12:34
No, we only support standard html. My example is not valid html.

**Comment by alexander-akait** [comment] 2023-03-14 13:04
@fisker What do you think about open an issue/feature request for this?

**Comment by fisker** [comment] 2023-03-14 16:12
I don't know, is this `<my-config>` a custom element or something requires a framework?

**Comment by hoodmane** [comment] 2023-03-14 16:38
`<my-config>` is a custom element. My actual use case is for [pyscript](pyscript.net) which defines a `py-config` tag whose body is toml config data and `py-script` whose body is Python code (which is also whitespace sensitive and needs to be protected from whitespace changes other than indentation).

For pyscript we are currently using a fork with the following patch on top of 3.0.0-alpha.6:
```patch
--- a/src/language-html/utils/index.js
+++ b/src/language-html/utils/index.js
@@ -106,7 +106,9 @@ function isTextLikeNode(node) {
 function isScriptLikeTag(node) {
   return (
     node.type === "element" &&
-    (node.fullName === "script" ||
+    (node.fullName === "py-script" ||
+      node.fullName === "py-config" ||
+      node.fullName === "script" ||
       node.fullName === "style" ||
       node.fullName === "svg:style" ||
       (isUnknownNamespace(node) &&
```
This works perfectly fine for our use case and I suspect it won't be a big deal to rebase it onto future releases. But I thought there could be other people that would benefit from a plugin API for things like this.
