### ISSUE TITLE
Prettier is adding new lines to template strings

### ISSUE THREAD

**Issue by rtorr** [prettier/prettier#1088] opened 2017-03-24 22:31 UTC
before

```javascript
const q = `
query GetLocaleString($lang: String) {
  locale(lang: $lang) { 
  }
}`;
```

after

```javascript
const q = `

query GetLocaleString($lang: String) {

  locale(lang: $lang) { 

  }

}`;

```

prettier version 0.22.0

**Comment by lydell** [comment] 2017-03-25 08:28
Hi!

I couldn’t reproduce this in the online version: https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20q%20%3D%20%60%5Cnquery%20GetLocaleString(%24lang%3A%20String)%20%7B%5Cn%20%20locale(lang%3A%20%24lang)%20%7B%20%5Cn%20%20%7D%5Cn%7D%60%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by rtorr** [comment] 2017-03-25 11:14
I'll see if I can set up a test report with exact settings

**Comment by vjeux** [comment] 2017-03-25 15:07
I'm curious, are you using windows or have some non standard line endings by chance?

**Comment by rtorr** [comment] 2017-03-26 23:47
@vjeux I actually was using windows at the time, however, I thought  coworker was running into this issue (osx).

**Comment by jlongster** [comment] 2017-03-27 21:50
@rtorr I can't repro either... If you could dig into it a little bit more and figure out why it works on the online demo, what would be great. Also just paste the code into a separate file and run prettier on it.

**Comment by rtorr** [comment] 2017-03-31 00:07
Ughh, I looked into this, and I could not see anything different as far as characters go. I dont use Windows often. 

When I specifically tell vscode to use
`"files.eol": "\n"`
the problem seems to go away. So there must be something, but none of my dectective work showed what it was.

**Comment by rtorr** [comment] 2017-03-31 00:09
![image](https://cloud.githubusercontent.com/assets/297045/24531135/904272ba-156b-11e7-9974-f47721023e3e.png)

this is what the file who had problems looked like
![pasted_image_at_2017_03_30_04_57_pm](https://cloud.githubusercontent.com/assets/297045/24531141/98c81002-156b-11e7-9af8-521bbb944711.png)

**Comment by vjeux** [comment] 2017-03-31 00:12
i'll look into windows line endings and template literals, maybe we don't handle those properly

**Comment by vjeux** [comment] 2017-04-06 16:44
@rtorr sorry it's been a while. The file you mentioned that had problem has two [LF] which means that it already has two new lines. If this is the input, then it's normal that the output look like this. If it's the output, do you happen to have the input still?

**Comment by vjeux** [comment] 2017-04-07 18:30
I'm going to close it as I can't reproduce. @rtorr could you upload a file that triggers this issue if you can make it reproduce?

**Closed by vjeux** 2017-04-07 18:30 UTC
Labels: Needs More Information

**Comment by mcdemarco** [comment] 2017-04-14 18:28
I accidentally reproduced this in Emacs (that's what the screenshots seem to be from) 24.2.1 on Win7, with prettier-js.el and prettier installed with yarn.  I was able to work around it by changing these lines in the prettier config for emacs:

`          (coding-system-for-read 'utf-8)`   
`          (coding-system-for-write 'utf-8)`

I set both to dos instead of utf-8 and that seems to have solved the problem for me (since the whole codebase uses dos line endings), but I don't have a general solution.
