### ISSUE TITLE
graphql: should wrap big list of implemented interfaces

### ISSUE THREAD

**Issue by B2o5T** [prettier/prettier#14966] opened 2023-06-22 18:32 UTC
**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACACgVwBtCAlOAR3zgGcZsBLAWw0LkYRmuwDkIATHADJsAQWrV6AcygBDAEatswgMKEI1eYpURG7WEuwBVDHxkxNQoybMXlOvXWEAZeXEIWDTiGADWH4WQyYOYKlmQY6vQwEABOaLwCBgDK+HLUYDH0cv5GUPQAZrGMZNQQ+DFgcF5gNqHYwAA6UA0whRBI2ACSsE0AviAANCAQGDD00NTIoDIxMRAA7rgzCJMoMoTzMmiTQ3IxQT5wMEky7E70UHDI+evUcLv7vkdJGEEXksgwMVRDbHJwfAEfBcUEk+BkkjgADEimYxqDkCAZPhooMQAALGCMQgAdXRURor0qSRWUXoADcomhEWBxGiLncYjBcPtJIwZNdbvcQAAragADyS71YAEV8BB4JzCHchq8YozEZJ9hh0eRCGiMJlYDj6HwYOjkAAOAAMsrmdxxysRmpocBi5KuQ0oErgLJGqyR1AAtJcAQC0TEKPh6IGWRD2VKZSA7ox6J9vtyJKDWCIYF8sijXXbzpdI4nhXAxS680MQjq9QakAAmUv7eiEd52XQclA0ACsaPwdwAKvJVjdpdzyVRugJYEkMvRRiIoHwkuhWHner0gA)

```sh
--parser graphql
```

**Input:**

```graphql
type PullRequest implements Node & Assignable & Closable & Comment & Updatable & UpdatableComment & Labelable & Lockable & Reactable & RepositoryNode & Subscribable & UniformResourceLocatable {
	foo: Int
}
```

**Output:**

```graphql
type PullRequest implements Node & Assignable & Closable & Comment & Updatable & UpdatableComment & Labelable & Lockable & Reactable & RepositoryNode & Subscribable & UniformResourceLocatable {
  foo: Int
}

```

**Expected behavior:**

**Comment by kachkaev** [comment] 2023-06-26 16:51
I believe that it’s a duplicate of https://github.com/prettier/prettier/issues/9206. Let’s track the issue there unless I have missed something!

**Closed by kachkaev** 2023-06-26 16:51 UTC
