### ISSUE TITLE
javascript ternary condition insert extra spaces

### ISSUE THREAD

**Issue by DavidBabel** [prettier/prettier#815] opened 2017-02-27 09:32 UTC
With a config : `"prettier.tabWidth": 2` i got this : 

![prettier](https://cloud.githubusercontent.com/assets/5599375/23355879/01d7f2c6-fcd8-11e6-9a5a-4657a4e33eac.gif)

resulting in 6 spaces for 2 tab indentations.

**Comment by jlongster** [comment] 2017-02-27 14:54
I think this was done purposefully. @yamafaktory didn't you work on this? The point was to line up the brackets.

**Comment by yamafaktory** [comment] 2017-02-27 15:03
@jlongster It was no me as far as I recall.

**Comment by jlongster** [comment] 2017-02-27 21:45
We did it purposefully for Flow intersection & union types here: https://github.com/prettier/prettier/pull/650 Are you sure that didn't affect the above code as well?

**Comment by yamafaktory** [comment] 2017-02-27 21:50
Oh sorry, you're right didn't think about that one. But I guess this checking `parent.type === "UnionTypeAnnotation"` should not interfere.

**Comment by yamafaktory** [comment] 2017-02-27 22:02
Actually setting https://github.com/yamafaktory/prettier/blob/master/src/printer.js#L894 and https://github.com/yamafaktory/prettier/blob/master/src/printer.js#L897 to `0` instead, solves it in the aforementioned issue.

**Comment by yamafaktory** [comment] 2017-02-27 22:03
But of course this breaks the other tests.

**Comment by rhengles** [comment] 2017-02-27 22:06
This _is_ intentional - one indenting level for the ternary, and another indenting level for the object literal. I think the default behaviour shouldn't be changed.

**Comment by yamafaktory** [comment] 2017-02-27 22:07
Of course, was just playing with it. Something else is interacting, but not the logic implemented for union types.

**Comment by yamafaktory** [comment] 2017-02-27 22:32
Ok, I think I got it. We need to have a new checking for `parentIsConditionalExpression` as, in this case, the indentation is already provided. Moreover, the lines I've mentioned are wrong: this should use `options.tabWidth` not directly `2`. I will create a PR.

**Comment by rhengles** [comment] 2017-02-27 22:42
@yamafaktory The indent is fixed at `2` spaces to align exactly with the ternary operators - so if you use `tabWidth: 4`, for example, the result is this:

```javascript
foo = someCondition
    ? {
          key1: 'value1',
          key2: 'value1'
      }
    : {
          key1: 'value2',
          key2: 'value2'
      };
```

**Comment by yamafaktory** [comment] 2017-02-27 22:49
@rhengles Yeah you're right, this is clearly set like you said as I can see so far in the tests. So in the end, this is not an issue but totally intended to be as it is. I was starting to mix everything in my mind !

**Comment by jlongster** [comment] 2017-02-28 16:19
Closing as it was intended. If enough people don't like this we can talk about it more, so please forward them here and we can re-open :)

**Closed by jlongster** 2017-02-28 16:19 UTC
Labels: Needs discussion
