### ISSUE TITLE
AngularJS HTML formatting incorrect

### ISSUE THREAD

**Issue by MikaelEdebro** [prettier/prettier#5449] opened 2018-11-12 13:08 UTC
I'm testing out the new HTML formatting on a AngularJS project at work. But unfortunately it messes up the code. I'm running the latest version of the VSCode plugin.

I'll attach a GIF and the problematic markup for testing:
[Imgur](https://i.imgur.com/Dl7i8OK.gifv)

Code:
```html
<div class="row">
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsSendReportName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).reportsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsSendReportName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).reportsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{"statisticsTimeFor" | i18n}} {{"statisticsLatest" | i18n}} {{"statisticsSendReportName" | i18n}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).latestReportTime}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsEventName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).eventsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsEventName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).eventsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsPollName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).pollsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsPollName'|i18n}}  {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).pollsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsPollStatusName' | i18n}} <span class="glyphicon glyphicon-info-sign" uib-tooltip="{{'statisticsPollStatusTooltip' | i18n }}" tooltip-placement="right"></span></b>
        <p>{{dataStatisticsMap.get(timeUnit).pollIntervalStatusOk ? 'yes' : 'no' | i18n }}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsValidationErrorName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).validationErrorsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsValidationErrorName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).validationErrorsCount}}</p>
    </div>
</div>
```

When running the code on prettier.io > Try it out, I'm getting:

```html
SyntaxError: Unexpected token (3:40)
  1 | <div class="row">
  2 |     <div class="col-xs-4 col-md-2">
> 3 |         <b>{{'statisticsSendReportName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
    |                                        ^
  4 |         <p>{{dataStatisticsMap.get(timeUnit).reportsCount}}</p>
  5 |     </div>
  6 |     <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
```

**Comment by ikatyang** [comment] 2018-11-12 13:17
There's a <kbd>Show options</kbd> on the bottom left, you have to specify the `--parser angular`.

<details>
<summary>playground</summary>

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOiAE4QDu1AfJVLu7hjvsWVeBAIBaAB4khAFnyChAW3RCATM1Yc1nAEZNgwAOQkYRGJgOYwJAMoJ0AJTgAHCDRgA5IrLi6APpgCMADigAXyDcHWoDIxNjcwAZIzgDalwvXD9AkLDgYw8AVShMGBDUAHotVXV2VHttYHQjIgtDY1NzAFkiewA6AHM4GAAKHLh8woBKLpoHJxgSAGEIAFdYYpKaiqqSrGwWNg4uPEJSCmpIYTFJaWF5JWSoHqESAAsGfghsOBpsTDh6KwI4GB4OgVHtKqgtDp9M1omZLNY7I5nG4PN50sFQuEQJEWjESPF4EkQCk0gEMVlhqMYFZIFB6jQAJ6rcpg9TVWr1QxNKKtEgdbp9QaUgrUwHQekMiZTJGzBbLIpBUrrVmlba7NQHHjHfhnUTiKS6m7KEDqyqaWoRGG8gAqmA8ADEnMlUujMlicbC4gkiSTXZjgJaeXirHTETMUXBnaSMoqyqbwTUdJzGla8fzev0hnaRiKJsRCTAw85bR5VsqNVscPHONstXxTjILgaZEbQWbzVCPbyAKIfWARtFkt0B7GpuEExIwKN+inZqnM6saxN1Brc3Fw9OCrN5XNdOB92VLFax8v7Ss7DY17hHesCc76q5yBTG3D3R4vehvD5fH5-OAAoE4BBE1Lw1SE9C7PFewQVx3E8Hwh39QN1y9Atp0Q2cd0KGlxSIRkF1A-Zl2TNdPT5ToMyFOcRRwuk8MlPcD3mI8FSVatVSrS9NRvE47z1S5DWfNszQhWpoSDOEAAVBAIAcEJjLJkLIicfRdDCdGFQoCNZJcOVXMd2gordNJgCZHAIAhmPlMt2PPdjax4nVGwfQTbmJN9nleah3k+b5fn+QFgWE8FwPElCSGkiy5JnRTRwk1DJ3QhSNOo7CxTo-DYxZdt2STfT4vIgVMxM2iJTMmSrOPNiuLsriHN4XjdSbR9WxAnT9lCyCpJktdFhIAdfQw1ASHsIg2Ec6gegIBl7CeMxoFwKaZrm2khEwKAADMIEeTAeigZJFkwDQhBgCBBGMex+E7AyIp65o+utM6CAu3RBsCXAQmSU7zswewhHsYgwDgDxYH4GhdqeKcTVKEaxqYUpspE4j8vCzditS0yunMggAElYF8ogCF6kgAHkAGtcAAflwXQGUSV6kBpqAIFetT3psmq1Tq68Gqc+8BJbIS2pyzqboANUJzBOUwaBuxoOgaGi9SRy6hLVOjckUqw1i40Iqpka5G60ao7WJmwSXpdl+WnEqnXT02LmVXq7UG355triF18Hk8z9vO-Py-wAoLhZE0WColggpaiK2FaV5KVZulSobezXsgx0r6O0nKDZTArje3HM0tpMqunNyPLagOWFdtjmVVqqAOJ2EAABoQAgexjGgEhkFAPC6HoSS8IQbuUCIbAIClluQA0GgiDAMn+gsUawHWnpkBgGhFjgVvIdkAgAHU5sJZe4BDEhChwQoGWQcAyCn9aSE+GBJNnnpZCIZANsJx-W4AKxIEQAAhWe89F5wViOtOAn9v7bxAP-EQFhV4AgAIqLAgPAaBllYGjRoI-GgN8xo9EWMQfBrd7Dg1gPvKWMAnjIH8AABjIXQR++9Z72BvuQxIvkoGtymAAR0OlMF+RA34fyQF-LBrdH6yEwOvTesDz73BQWgjB4iYGt0MBoKh6AaHIEUBo2emBI73AWLId+N9mZQB4SAPqcBrREA0CPCRj8QhAA)
```sh
--parser angular
```

**Input:**
```html
<div class="row">
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsSendReportName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).reportsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsSendReportName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).reportsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{"statisticsTimeFor" | i18n}} {{"statisticsLatest" | i18n}} {{"statisticsSendReportName" | i18n}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).latestReportTime}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsEventName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).eventsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsEventName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).eventsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsPollName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).pollsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsPollName'|i18n}}  {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).pollsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsPollStatusName' | i18n}} <span class="glyphicon glyphicon-info-sign" uib-tooltip="{{'statisticsPollStatusTooltip' | i18n }}" tooltip-placement="right"></span></b>
        <p>{{dataStatisticsMap.get(timeUnit).pollIntervalStatusOk ? 'yes' : 'no' | i18n }}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsValidationErrorName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).validationErrorsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsValidationErrorName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).validationErrorsCount}}</p>
    </div>
</div>
```

**Output:**
```html
<div class="row">
  <div class="col-xs-4 col-md-2">
    <b
      >{{ "statisticsSendReportName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnit }}</b
    >
    <p>{{ dataStatisticsMap.get(timeUnit).reportsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
    <b
      >{{ "statisticsSendReportName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnitSecondary }}</b
    >
    <p>{{ dataStatisticsMap.get(timeUnitSecondary).reportsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2">
    <b
      >{{ "statisticsTimeFor" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ "statisticsSendReportName" | i18n }}</b
    >
    <p>{{ dataStatisticsMap.get(timeUnit).latestReportTime }}</p>
  </div>
  <div class="col-xs-4 col-md-2">
    <b
      >{{ "statisticsEventName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnit }}</b
    >
    <p>{{ dataStatisticsMap.get(timeUnit).eventsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
    <b
      >{{ "statisticsEventName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnitSecondary }}</b
    >
    <p>{{ dataStatisticsMap.get(timeUnitSecondary).eventsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2">
    <b
      >{{ "statisticsPollName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnit }}</b
    >
    <p>{{ dataStatisticsMap.get(timeUnit).pollsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
    <b
      >{{ "statisticsPollName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnitSecondary }}</b
    >
    <p>{{ dataStatisticsMap.get(timeUnitSecondary).pollsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2">
    <b
      >{{ "statisticsPollStatusName" | i18n }}
      <span
        class="glyphicon glyphicon-info-sign"
        uib-tooltip="{{'statisticsPollStatusTooltip' | i18n }}"
        tooltip-placement="right"
      ></span
    ></b>
    <p>
      {{
        dataStatisticsMap.get(timeUnit).pollIntervalStatusOk
          ? "yes"
          : ("no" | i18n)
      }}
    </p>
  </div>
  <div class="col-xs-4 col-md-2">
    <b
      >{{ "statisticsValidationErrorName" | i18n }}
      {{ "statisticsLatest" | i18n }} {{ timeUnit }}</b
    >
    <p>{{ dataStatisticsMap.get(timeUnit).validationErrorsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
    <b
      >{{ "statisticsValidationErrorName" | i18n }}
      {{ "statisticsLatest" | i18n }} {{ timeUnitSecondary }}</b
    >
    <p>{{ dataStatisticsMap.get(timeUnitSecondary).validationErrorsCount }}</p>
  </div>
</div>

```

</details>

---

> But unfortunately it messes up the code.

What did you mean "_mess up_"? what's your expected behavior?

**Comment by MikaelEdebro** [comment] 2018-11-13 10:03
Ok great! When using parser = angular, the playground got the same result as VS Code plugin.

But what I mean by "mess up". This is the way it formats the <b> tags:
```html
<b
      >{{ "statisticsEventName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnit }}</b
    >
```

**Comment by ikatyang** [comment] 2018-11-13 10:05
What's your expected output?

**Comment by MikaelEdebro** [comment] 2018-11-13 10:12
I would expect it not to break the html tags in multiple lines. That only makes sense if there are multiple attributes?!?

I would expect something like this:

```html
<div class="col-xs-4 col-md-2">
    <b>
        {{"statisticsTimeFor" | i18n}} {{"statisticsLatest" | i18n}} 
        {{"statisticsSendReportName" | i18n}}
    </b>
    <p>{{dataStatisticsMap.get(timeUnit).latestReportTime}}</p>
</div>
```

Hope I'm not coming off too critical. I really think Prettier is an awesome tool, and it's great that you have included HTML in it's arsenal. But in this particular case, the formatting seems a bit off. :)

**Comment by ikatyang** [comment] 2018-11-13 10:20
You may want to take a look at [whitespace-sensitive formatting](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting), that's why we cannot add whitespaces there as it'll break your code, but if you don't care about those whitespaces, just use `--html-whitespace-sensitivity ignore`.

(There're actually some ignorable whitespaces we didn't take into account, which is tracked in #5439.)

<details>
<summary>playground with <code>--html-whitespace-sensitivity ignore</code></summary>


**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOiAE4QDu1AfJVLu7hjvsWVeBAIBaAB4khAFnyChAW3RCATM1Yc1nAEZNgwAOQkYRGJgOYwJAMoJ0AJTgAHCDRgA5IrLi6APpgCMADigAXyDcHWoDIxNjcwAZIzgDalwvXD9AkLDgYw8AVShMGBDUAHotVXV2VHttYHQjIgtDY1NzAFkiewA6AHM4GAAKHLh8woBKLpoHJxgSAGEIAFdYYpKaiqqSrGwWNg4uPEJSCmpIYTFJaWF5JWSoHqESAAsGfghsOBpsTDh6KwI4GB4OgVHtKqgtDp9M1omZLNY7I5nG4PN50sFQuEQJEWjESPF4EkQCk0gEMVlhqMYFZIFB6jQAJ6rcpg9TVWr1QxNKKtEgdbp9QaUgrUwHQekMiZTJGzBbLIpBUrrVmlba7NQHHjHfhnUTiKS6m7KEDqyqaWoRGG8gAqmA8ADEnMlUujMlicbC4gkiSTXZjgJaeXirHTETMUXBnaSMoqyqbwTUdJzGla8fzev0hnaRiKJsRCTAw85bR5VsqNVscPHONstXxTjILgaZEbQWbzVCPbyAKIfWARtFkt0B7GpuEExIwKN+inZqnM6saxN1Brc3Fw9OCrN5XNdOB92VLFax8v7Ss7DY17hHesCc76q5yBTG3D3R4vehvD5fH5-OAAoE4BBE1Lw1SE9C7PFewQVx3E8Hwh39QN1y9Atp0Q2cd0KGlxSIRkF1A-Zl2TNdPT5ToMyFOcRRwuk8MlPcD3mI8FSVatVSrS9NRvE47z1S5DWfNszQhWpoSDOEAAVBAIAcEJjLJkLIicfRdDCdGFQoCNZJcOVXMd2gordNJgCZHAIAhmPlMt2PPdjax4nVGwfQTbmJN9nleah3k+b5fn+QFgWE8FwPElCSGkiy5JnRTRwk1DJ3QhSNOo7CxTo-DYxZdt2STfT4vIgVMxM2iJTMmSrOPNiuLsriHN4XjdSbR9WxAnT9lCyCpJktdFhIAdfQw1ASHsIg2Ec6gegIBl7CeMxoFwKaZrm2khEwKAADMIEeTAeigZJFkwDQhBgCBBGMex+E7AyIp65o+utM6CAu3RBsCXAQmSU7zswewhHsYgwDgDxYH4GhdqeKcTVKEaxqYUpspE4j8vCzditS0yunMggAElYF8ogCF6kgAHkAGtcAAflwXQGUSV6kBpqAIFetT3psmq1Tq68Gqc+8BJbIS2pyzqboANUJzBOUwaBuxoOgaGi9SRy6hLVOjckUqw1i40Iqpka5G60ao7WJmwSXpdl+WnEqnXT02LmVXq7UG355triF18Hk8z9vO-Py-wAoLhZE0WColggpaiK2FaV5KVZulSobezXsgx0r6O0nKDZTArje3HM0tpMqunNyPLagOWFdtjmVVqqAOJ2EAABoQAgexjGgEhkFAPC6HoSS8IQbuUCIbAIClluQA0GgiDAMn+gsUawHWnpkBgGhFjgVvIdkAgAHU5sJZe4BDEhChwQoGWQEBduZqYp-WkhPhgSTZ56WQiGQDbCef1uACsSAiAAEKz3novOCsR1pwG-r-beIBAEiAsKvAEABFRYEB4CwMsvA0aNBn40BvmNHoixiCENbvYcGsB95SxgE8ZA-gAAMFC6DP33rPewN9KGJF8jA1uUwACOh0phvyIB-L+SAf44Nbs-WQmB16b3gefe4aCMFYMkXA1uhgNA0PQHQ5AigtGz0wJHe4CxZCfxvszKAfCQB9TgNaIgGgR5SOfiEIAA)
```sh
--html-whitespace-sensitivity ignore
--parser angular
```

**Input:**
```html
<div class="row">
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsSendReportName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).reportsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsSendReportName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).reportsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{"statisticsTimeFor" | i18n}} {{"statisticsLatest" | i18n}} {{"statisticsSendReportName" | i18n}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).latestReportTime}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsEventName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).eventsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsEventName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).eventsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsPollName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).pollsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsPollName'|i18n}}  {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).pollsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsPollStatusName' | i18n}} <span class="glyphicon glyphicon-info-sign" uib-tooltip="{{'statisticsPollStatusTooltip' | i18n }}" tooltip-placement="right"></span></b>
        <p>{{dataStatisticsMap.get(timeUnit).pollIntervalStatusOk ? 'yes' : 'no' | i18n }}</p>
    </div>
    <div class="col-xs-4 col-md-2">
        <b>{{'statisticsValidationErrorName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnit}}</b>
        <p>{{dataStatisticsMap.get(timeUnit).validationErrorsCount}}</p>
    </div>
    <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
        <b>{{'statisticsValidationErrorName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
        <p>{{dataStatisticsMap.get(timeUnitSecondary).validationErrorsCount}}</p>
    </div>
</div>
```

**Output:**
```html
<div class="row">
  <div class="col-xs-4 col-md-2">
    <b>
      {{ "statisticsSendReportName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnit }}
    </b>
    <p>{{ dataStatisticsMap.get(timeUnit).reportsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
    <b>
      {{ "statisticsSendReportName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnitSecondary }}
    </b>
    <p>{{ dataStatisticsMap.get(timeUnitSecondary).reportsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2">
    <b>
      {{ "statisticsTimeFor" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ "statisticsSendReportName" | i18n }}
    </b>
    <p>{{ dataStatisticsMap.get(timeUnit).latestReportTime }}</p>
  </div>
  <div class="col-xs-4 col-md-2">
    <b>
      {{ "statisticsEventName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnit }}
    </b>
    <p>{{ dataStatisticsMap.get(timeUnit).eventsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
    <b>
      {{ "statisticsEventName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnitSecondary }}
    </b>
    <p>{{ dataStatisticsMap.get(timeUnitSecondary).eventsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2">
    <b>
      {{ "statisticsPollName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnit }}
    </b>
    <p>{{ dataStatisticsMap.get(timeUnit).pollsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
    <b>
      {{ "statisticsPollName" | i18n }} {{ "statisticsLatest" | i18n }}
      {{ timeUnitSecondary }}
    </b>
    <p>{{ dataStatisticsMap.get(timeUnitSecondary).pollsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2">
    <b>
      {{ "statisticsPollStatusName" | i18n }}
      <span
        class="glyphicon glyphicon-info-sign"
        uib-tooltip="{{'statisticsPollStatusTooltip' | i18n }}"
        tooltip-placement="right"
      ></span>
    </b>
    <p>
      {{
        dataStatisticsMap.get(timeUnit).pollIntervalStatusOk
          ? "yes"
          : ("no" | i18n)
      }}
    </p>
  </div>
  <div class="col-xs-4 col-md-2">
    <b>
      {{ "statisticsValidationErrorName" | i18n }}
      {{ "statisticsLatest" | i18n }} {{ timeUnit }}
    </b>
    <p>{{ dataStatisticsMap.get(timeUnit).validationErrorsCount }}</p>
  </div>
  <div class="col-xs-4 col-md-2" ng-show="overviewSelected">
    <b>
      {{ "statisticsValidationErrorName" | i18n }}
      {{ "statisticsLatest" | i18n }} {{ timeUnitSecondary }}
    </b>
    <p>{{ dataStatisticsMap.get(timeUnitSecondary).validationErrorsCount }}</p>
  </div>
</div>

```


</details>

**Comment by JLHwung** [comment] 2018-11-14 03:08
The `angular` parser works good with AngularJS templates, I suggest the issue be closed.

BTW should we document on https://prettier.io/blog/2018/11/07/1.15.0.html that AngularJS template should be parsed with `angular` parser? One should probably specify `--parser angular` given Angular JS template have no naming convention.

**Comment by ikatyang** [comment] 2018-11-14 03:29
I did mention it in the [blog post](https://prettier.io/blog/2018/11/07/1.15.0.html#automatic-parser-inference), the issue here is probably same as https://github.com/prettier/prettier/issues/5462#issuecomment-438349590, where Angular did strip whitespaces (insensitive) in some cases.

Unrelated: @JLHwung Would you mind to take look at #5368 (the regression there seems caused by [upgrading cjk-regex from v1 to v2](https://github.com/ikatyang/cjk-regex/pull/68))? I did a quick fix in #5402 but I'm not quite sure if it's the proper fix given that I'm not too familiar with unicode. Thanks!

**Comment by thorn0** [comment] 2018-11-14 15:05
Unlike Angular, AngularJS doesn't strip any white spaces.

**Comment by JLHwung** [comment] 2018-11-14 15:33
> I did mention it in the blog post, the issue here is probably same as #5462 (comment), where Angular did strip whitespaces (insensitive) in some cases.

By stressing `AngularJS` versus `Angular`, I mean they are different framework, though they have similar name and `Angular` evolves from `AngularJS`. As it is shown on #5466, they are different framework with slight different grammar.

@ikatyang On the fix in #5402, you did a great job! I have reviewed the code change and do find some rare cases and it should addressed in #5480.

**Comment by MikaelEdebro** [comment] 2018-11-15 06:55
I don't know anything about the implementation details, and the 1000 issues that you probably have to face to support every edge case.

But as a user, I would rather prefer that `print-width` is disregarded if there are uncertanties about how to handle whitespace. In my opinion print-width is not as important for readability in HTML as in JS.

For example, that this:
```html
<div class="col-xs-4 col-md-2" ng-show="overviewSelected">
    <b>{{'statisticsSendReportName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}</b>
    <p>{{dataStatisticsMap.get(timeUnitSecondary).reportsCount}}</p>
</div>
```

Would become:
```html
<div class="col-xs-4 col-md-2" ng-show="overviewSelected">
    <b>
        {{'statisticsSendReportName'|i18n}} {{"statisticsLatest" | i18n}} {{timeUnitSecondary}}
     </b>
    <p>{{dataStatisticsMap.get(timeUnitSecondary).reportsCount}}</p>
</div>
```

**Comment by thorn0** [comment] 2020-05-06 00:22
I don't see anything that needs discussion or fixing in this issue.
`--html-whitespace-sensitivity ignore` does what the OP wanted.

**Closed by thorn0** 2020-05-06 00:22 UTC
Labels: lang:angular, lang:html, lang:vue, status:needs discussion
