### ISSUE TITLE
Prettier fails to format HTML with <pre> tags placed inside <p> tags

### ISSUE THREAD

**Issue by leonzalion** [prettier/prettier#12610] opened 2022-04-07 02:44 UTC
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgwJzpyAEzlQHp09tzMQAaECdGAS2gGdlQBDHHCAdwAKPBBxRcANvy4BPDvQBGOLmADWcGAGUuAWzgAZZlDjIAZpLZxFytRs3oVRgObIYOAK5WQcHQriFiQn0uKCd3Lic4ADEIHB0uGBZQ5BAudxgIOhAACxgdCQB1bOZ4NgcwOE1REuYANxKZFLA2eRAjSxwYQWUneLMLLwArNgAPTWcJOABFdwh4folLegccDpTc-KyKIxgC5kIYbOQADgAGZb5LAuV0FIo4DtqTegBHWfhuxjFUtgBaY38-iyeDezDw3QifSQ5kWXksOmYrg8cIm03eJmhA3oMC4Cj2ByOSAATNjlMwJM4AMIQHRQ7xsACsWXclgAKrixDCliBap4AJJQYiwTRgHDMJgAQUFmhgMkmC0sAF9FUA)

```sh
--parser html
```

**Input:**

```html
<p><pre>code</pre></p>
```

**Output:**

```html
SyntaxError: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:19)
> 1 | <p><pre>code</pre></p>
    |                   ^^^^
```

**Expected behavior:**
No compiler error is thrown.

**Comment by fisker** [comment] 2022-04-07 02:55
Duplicate of #11907

**Closed** 2022-04-07 02:56 UTC
