### ISSUE TITLE
Prettier changing variable case in .less files (mis-parsed as at-rules)

### ISSUE THREAD

**Issue by slashwhatever** [prettier/prettier#6473] opened 2019-09-12 09:37 UTC
IDE: VSCode using Prettier extension

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACAOlAAgGwIYBOA5nACoCWOcAyuQF5ypKoDMADGwA4AeA3JlgC2cACbkAroIpVaDJqgBMANi58BAZ0F4cOaTXqNmC9j37YYlOAHE8nZgEZVZoaIlTLNu6nsBWUwPxiMg9bIycBACMIAhE4AgAxSioCI38oEAAaEAhOC2h1ZFBCAggAdwAFQgQClDwANwhyEUyQCII8MABrOBhqTg7yKCJkGAJxOCyACxhBHAB1SfJ4dX6wGmql8jqlgE9kcHUCrMH1OJhy9qItZAAzbVOsgCt1bgAhdq6e6jxhABlBuC3e4TEDPbi0IZUACK4gg8CBOAeIH6BFOBH2VEOLU4BEGMDmTRgk2QAA42FkcRBTnN2px9ji4Gi6oCsgBHWHwC45GogPDqAC0UDgolELQIcHZ5HFFzwVzwCKRp0E5BGYxB6kGRGhHMBSDuiJBMDwEQJIiJyAUWVGeEomoAwhBBNcUFBoCyQOJTqRjTV9acAL7+oA)
```sh
--parser less
```

**Input:**
```less
 
@largeTileSize : 300px;
@mediumTileSize : 260px;
@smallTileSize : 230px;
@tileGap: 10px;
@mediumTileGap: 15px;
@largeTileGap: 20px;
@borderFiller: 2px;

```

**Output:**
```less
@largetilesize : 300px;
@mediumtilesize : 260px;
@smalltilesize : 230px;
@tileGap: 10px;
@mediumTileGap: 15px;
@largeTileGap: 20px;
@borderFiller: 2px;

```

Before formatting: http://snpy.in/9ZaVE1

After formatting: http://snpy.in/RkGnaX

**Expected behaviour:**
Variable names shouldn't have their case changed. Especially, as it seems here, arbitrarily.

**Comment by slashwhatever** [comment] 2019-09-19 14:25
done

**Comment by lydell** [comment] 2019-09-19 16:01
It looks like our Less parser thinks that if there's a space before the colon, the thing is not a variable declaration, but an at-rule (I checked the AST). And the names of at-rules are lowercased.

As a workaround, you can remove the spaces before the colons and fix the casing. And be careful not to use extra spaces when writing variables in the future. Then they should stay that way, even after running Prettier.

According to http://lesscss.org/less-preview/ a space before the colon is valid, so our parser has a bug.

```less
@largeTileSize : 300px;

a {
  font-size: @largeTileSize;
}
```
⬇️
```css
a {
  font-size: 300px;
}
```

**Comment by uuykay** [comment] 2019-09-21 14:07
Noticed this as well while I'm customising Semantic UI's LESS files and I found this. For me I've added the semantic folder as part of the ignore rules:
semantic/**
but would love a proper solution.

**Comment by evilebottnawi** [comment] 2019-10-24 16:01
Duplicate of #4090

**Closed by evilebottnawi** 2019-10-24 16:01 UTC
Labels: lang:css/scss/less, scope:dependency, type:bug
