### ISSUE TITLE
Option to indicate the parser in a template literal other than HTML

### ISSUE THREAD

**Issue by kuba-orlik** [prettier/prettier#13738] opened 2022-10-26 17:15 UTC
**Prettier 2.7.1**
[[Playground link](https://prettier.io/playground/#.....)](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgMIGVebqqYAGAdALYCeYANgIYDOjwktEATkh3ACYC+JEABoQEAA4wAltEbJQ9DhwgB3AAqKEclPVor6VOaIBGHemADWcGLnoU4AGSlQ4yAGa7GcE2cvXc4ubOAObIMBwArt4gcBTGfLx8DvRQwRH0wXAAYpwU9DDSqcgg9BEwECIgABYwFLQA6lVS8IyBYHC4Ws1SAG7NVMVgzJXOXhwwambBee6e0QBWjAAeuCG0cACKERDws7ReooEcY8XG9PG0leIczjD1UrwwVcgAHAAMh8pe9WbixddwMY9VyiACO23gkwk2hKjAAtC4+HxKjxwVIeJMMjMkB59tEvBQpGFIvi1psIa4cXNRDBzvdHs8kAAmGlmKS0ELYCAUbExRgAVkqES8ABVztpcQcQD0ogBJKCJWC4MA3SQAQQVuBgVHWey8-H4QA)

**Input:**

```jsx
/* CSS */ `.myclass{color:red}`
```

**Output:**

```jsx
/* CSS */ `.myclass{color:red}`
```

**Expected behavior:**

```jsx
/* CSS */ `.myclass{
    color: red;
}`
```

It would be cool if we could indicate the language that's contained within a template literal. Only HTML got that treatment, but I've stumbled upon numerous cases when this would be helpful - gluing together CSS, JS and HTML strings.

**Comment by kuba-orlik** [comment] 2022-10-26 17:17
Current workaround is to wrap it in an HTML tag:

```
/* HTML */ `<style>.myclass{color:red}</style>`
```

and then removing the `<style>` tags... but that's so ugly!

**Comment by bakkot** [comment] 2022-11-02 03:03
See https://github.com/prettier/prettier/issues/4424

**Comment by thorn0** [comment] 2022-11-06 15:52
Duplicate of #5588

**Closed** 2022-11-06 15:52 UTC
Labels: type:duplicate
