### ISSUE TITLE
Prettier removes the # in markdown headers

### ISSUE THREAD

**Issue by LuckyRabbitFeet** [prettier/prettier#7727] opened 2020-03-07 12:38 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAYVQHShzHHVEAGhAgAcYBLaAZ2VAEMAnViAdwAU2FGUzAG4QaAEzIgARq2ZgA1nBgBlSnJpQA5shisArnHIALGAFsANgHUjNePTVg4y-rZpDbAT2Th6jchvo4VhhuWU1TZmQAM2ZzQPIAK3oADwAhWQUlZWZTOAAZDTho2PiQJOTlDU1zOABFPQh4YrjDEDVWQNZvCNZ5MS4oSUpWDRhLcRgjZAAOAAZyYYhAy1lKb2G4TqEi8gBHBvhQqgEQZnoAWig4ODEbyVY4fZoH0OZwyKQYlvJA0xodfStehVGr1RpFT4lVowZhScZiSbIABM5F0zBo5iqmAgpgi3ig0B2ID0gQAKrCBF9SkIDABJKC3WDKMAjagAQQZyhgHhqzUCAF9+UA)

If the last word in the title is #, then it will be deleted.

for example：
**Input:**
```md
# C#
```
**Output:**
```md
# C
```

And I tried using escape but it didn't work.
**Input:**
```md
# C\#
```
**Output:**
```md
# C\
```

I did not find the relevant settings in the documentation.

I know this line can be ignored by using `/* prettier-ignore */`, but I don't think it's a good idea.

Am I missing something, or is it designed like that?

**Comment by thorn0** [comment] 2020-03-07 12:55
Duplicate of https://github.com/prettier/prettier/issues/6177

**Closed by thorn0** 2020-03-07 12:55 UTC
