### ISSUE TITLE
.prettierignore doesnt allow dot character

### ISSUE THREAD

**Issue by avalanche1** [prettier/prettier#4425] opened 2018-05-05 15:56 UTC
```
/usr/local/bin/prettier --write .prettierignore

[error] .prettierignore: SyntaxError: Unexpected token (3:9)
[error]   1 | yarn.lock
[error]   2 | client/main.html
[error] > 3 | imports/.flowconfig
[error]     |         ^

Process finished with exit code 2
```

**Comment by ikatyang** [comment] 2018-05-05 15:58
We do not support formatting a `.ignore` file, I guess you meant to use `--ignore-path`..

**Comment by avalanche1** [comment] 2018-05-05 16:03
Actually I'm useing prettier with webstorm filewatcher - maybe because of that prettier tries to format everyting?

**Comment by ikatyang** [comment] 2018-05-05 16:11
Yeah, it looks like the case.

Closing as duplicate of #4405.

**Comment by ikatyang** [comment] 2018-05-05 16:11
Duplicate of #4405

**Closed by ikatyang** 2018-05-05 16:11 UTC
