### ISSUE TITLE
[Javascript][Typscript] print long template literals similar to long strings

### ISSUE THREAD

**Issue by zieka** [prettier/prettier#3872] opened 2018-02-01 22:24 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACKEYEsxwYwAWh8AtgA4A2AhvBtbvAE63UYDOtAnpxtCKkutcoSZRCAHSiQonGFwhiAMtADmAZRgtcUdRgC8GABRRRcJFx171ASiMA+DMBkYMchRjGdu6wsYABgAkwOZiAL4ANEK4-HEYtBgAbnAsPIwaRHBUdAxMrOxC9BhwAB4EcAAm-CSE5LRluOQAruQYlLqwGADuuFUkiVBVGHqx-GC0nGTEJQnQhMQtwyzVQyMAZhAsMBlgs2xgrJyBANxuGKswLSxQ3nC+tP7nUBEyMuilZZRwR7ZChB6xAg1DIORo9HEzDSRRgEG8EFSRHhdSw5UUEjgH0wnGauDoLGRGGBPUS1i6BgSs2GoJGJmmhAARnBqBAenYZJ5FOxOBBNMo4Gp9NoKUZTOFLOTbA5DM5XHcPNAvD4-AEMAByGIkBIJJKpdKZfRSo0kErlSo1AHeRrNNodLqKPoDYjrUZ3bUTKYzOb8BbE5ZVVYjWjDDBbHZ7A60I5pfghkbLJgAaxmYNykIw-hg-EoLUUgmYvp6d0x6pe7iuNzuEowAGp7o9njIIiAoiAIJQ8ErkKBaCwWGyAAp9hCcZAgdg9XhjttTGDIDY8uBtxmHFMwTSUaO2ZA6FrLkBVCBgBdLtt6aY7QdsdQNU-UaZtgBWnDKACE13ANxYVHo4LuWH3NsIDzXMYAAJnvR8QC3FhL3HXYfk4MBdE7VsYIdAB1foSGQABGAAWAAGNtOggaZMLYShx06B40lSdDVgARxaXBVmvJ47yQRcHwPaZyFwACgJAXF9FBABFFocH-JA9wPGBaEZbDnWQAi2x0Wh8VsABhZQuJAbBJHQlppgAFUUsdZMAuAIgiIA)
```sh
--arrow-parens always
--jsx-bracket-same-line
--parser typescript
--print-width 140
--single-quote
--tab-width 4
--use-tabs
```

**Input:**
```tsx
// notice the template literal says on the same line 
const someLongString = (name: string) => {
  const message = `${name}, this is a very long template literal that exceeds the maximum print width and in this case that is one hundred and forty characters`;
  return message;
}

// expecting the whole template literal to move to the next line
// similar to how a string is handled (see below)
const alsoSomeLongString = (name: string) => {
  const message = ', this is a very long string that exceeds the maximum print width and in this case that is one hundred and forty characters and unlike the template gets put on its own line';
  return name + message;
}
```

**Output:**
```tsx
// notice the template literal says on the same line
const someLongString = (name: string) => {
	const message = `${name}, this is a very long template literal that exceeds the maximum print width and in this case that is one hundred and forty characters`;
	return message;
};

// expecting the whole template literal to move to the next line
// similar to how a string is handled (see below)
const alsoSomeLongString = (name: string) => {
	const message =
		', this is a very long string that exceeds the maximum print width and in this case that is one hundred and forty characters and unlike the template gets put on its own line';
	return name + message;
};

```

**Expected behavior:**
I would expect when handling template literals that exceed the print width that the whole template literal (even if it is multiple lines) would be shifted to start on its own line similar to how long strings are handled.

**Comment by bakkot** [comment] 2018-02-02 00:18
This is maybe a duplicate of #2482.

**Comment by azz** [comment] 2018-02-04 01:19
Indeed. Closing as a duplicate of #2482.

**Closed by azz** 2018-02-04 01:19 UTC
Labels: lang:javascript, lang:typescript, type:bug
