### ISSUE TITLE
Removal of parentheses in a Vue directive that uses type casting destroys syntax highlighting in vs code!

### ISSUE THREAD

**Issue by Luanovic** [prettier/prettier#15201] opened 2023-08-02 16:45 UTC
Without parentheses: 
![image](https://github.com/prettier/prettier/assets/115368073/f4c3879a-0d33-419e-b8b1-4c39acc52bea)

With Parenthesis, disabling prettier: 
![image](https://github.com/prettier/prettier/assets/115368073/1dee115e-8dde-4938-88e2-accfdabb40d5)

**Comment by kachkaev** [comment] 2023-08-02 17:48
👋 @Luanovic! Can you please follow the issue template? It’s important that all reports about formatting include text and playground links, not screenshots:
https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md?plain=1

**Comment by auvred** [comment] 2023-08-03 15:52
Hi, this is a valid Vue syntax: [Vue SFC Playground](https://play.vuejs.org/#eNp9Uc1KxDAQfpWQk8K6ZdlbaQWVPSj4g+4xl9CObdc0Ccl0bSl9dyetW10oe0ky8/3MN6Tnd9aujw3wmCc+c5VF5gEby5TURSo4esFvhc6M9shyiZKlrB+EFho7C+y524crZVJ3QifRZEECKhBqqyQCVYwl5YbFQX8TDjK+Gs2k/7W4pjF9P00YhiQqN8uyc9WSKInmwXxF+Sn6Z1WsD95oWrIProJnpraVAvdqsaLVBI/ZiARMKmW+n8YeugZWp35WQva10D/4NvQEf3PgwR0p1YyhdAXgBO8+XqCl9wzWJm8UsS+A7+CNakLGiXbf6Jxi/+ONaR9raxxWutj7XYug/WmpEDQwh5EvOP30w4XV/+Ju19tRJ/TAhx+tKLVV)

The issue with highlighting is most likely related to Volar. You can read more about this here: https://github.com/vuejs/language-tools/issues/520, https://github.com/vuejs/language-tools/issues/112

The prettier is responsible only for formatting, not for highlighting the code :)

**Comment by fisker** [comment] 2023-08-03 18:19
Duplicate of #19157

**Closed** 2023-08-03 18:19 UTC
Labels: type:duplicate, status:awaiting response

**Comment by kachkaev** [comment] 2023-08-03 23:23
@fisker which issue issue number is this? I can’t seem to find #19157

**Comment by auvred** [comment] 2023-08-03 23:59
@kachkaev I guess this one https://github.com/prettier/prettier/issues/15197

**Comment by fisker** [comment] 2023-08-04 00:22
Thank you @auvred
