### ISSUE TITLE
[Style] Put the semicolon on a separate line at the end when formatting TypeScript union type.

### ISSUE THREAD

**Issue by xyzingh** [prettier/prettier#9789] opened 2020-11-29 07:33 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwDkIATOAGQEsBrOAFWNIF4AdKPXvAHzwBRADZwAtghisSAOhoQwAQxEVq3PgOFjJsGXHmKVAZQCuAIyhwYGvoNESp+2QCUJEeGri3e9nU7ZZADU6XFMVLx8tB11pQIBVKAYoCAB3KEiePgBubm50LFwCNjwAaThCVJxKY0JYJTRSuihKPC4s3zxa+sbmylkAQXMAZxhsJTAYcsrqqMFumAamlsGoQmmq7Eo5rrrF3pWB4Y3ZjrwAenO8WRudhaW+2WYAC2w0k627vYeV5mxTOAfbZnebfA79P7rCqbYGaUE9ZYQthAr4Ix76ADyADMUSDdmiVolqFjmnBKLi4fj9ojZIk6ABHAEUuxUn79RLJNJQZmde7g4JKbA8rR8mlBCB0cnQ06U0WPADqzzoYmF8OpCroMGeqtZ-IAmnQ4CIpTNPmdclAQAAaEAQDAwOjQYbIUCCt6pAAKgoQzpQKlSSkIzpt5nGYCYMGMGAmzQA5sgxgCbRJzGTqJQaEooLHwrG4AAxHDiJQwB3Z5AgJSmGAQa0gZ4wcQiRWauDDaNgODGH2augAN01hArYGGwZAzWGcFwHvGseLyCxKknNoAVsM0AAhMMR4xKST0KwLpdwVfr4xxsQARVMHjgR5Ey5A0ewk+wFaIJGGYGwdHtdYwP6wPKkpasgAAcAAMNoARAk7yuMGAVgBbZTn2d42oyt4znavqVsMAC0VhkmSdbYHAjKhHAM5KHOSj3o+k7iHQCb-CeIDDBecDXre9FsYs5jAZQoFIAALDaYxKMqcYAMIQOI84oG2ACsdamJOzBKCMvE2n2AIAJItFIxjfr+MADC0xhEGIvEAL42UAA)

**Input:**

```ts
export type NodeLikeType =
    | ElementType.LocalNode
    | ElementType.LocalSubnet
    | ElementType.RemoteNode
    | ElementType.VirtualNode
    | ElementType.UnknownNode
    ;
```

**Output:**

```ts
export type NodeLikeType =
    | ElementType.LocalNode
    | ElementType.LocalSubnet
    | ElementType.RemoteNode
    | ElementType.VirtualNode
    | ElementType.UnknownNode;
```

**Expected behavior:**

Put the semicolon on a separate line at the end.

This is a very common style, and when executing `git diff`, the last line can be avoided from changing.

E.g. [TypeScript compiler types](https://github.com/microsoft/TypeScript/blob/master/src/compiler/types.ts#L532).

**Comment by thorn0** [comment] 2020-11-29 08:52
Duplicate of #9370

**Closed by thorn0** 2020-11-29 08:52 UTC
