### ISSUE TITLE
Prettier v1.11.1 is mixing spaces and tabs for alignment

### ISSUE THREAD

**Issue by kiruh** [prettier/prettier#4199] opened 2018-03-24 17:52 UTC
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAhgAsBXKAa3wDMcJ18AdEHOAExIA8BaYs8pgNwMoGbHnzB8YFgEN4AGQgBzJXBz4AvtVr0mLdtwA2y1TkHDRuApOlw5cAMoxccADT4ZmTIYCeAWVRWVkM4AHcZFndILAgAZzhNbTpGZjZOcygLGPF9EjA1JN0QADoAelz8nFjSjOFIKFiCVFiAETgAN3wAXkIcEjghKHrG-GMlACU0jm7e-sHhghJ4xRU1AEEoVjb2gBUICENYmcxafNjY4oR24oA5AHkWgFEAfUebgDV8AEIunqZ4RpMfAAMmB+Ga20GdWgI0aLhmSzgK1MGy2HT2B1iwgYMAA-FJZPAnC4ABTYmA4nEVNSucmUmBjSYGOkU1n46LYeIkzzefyBYJhCJwEm2ezItQkgCU7l4FElkpZ9KQUjonOFPN8ASCIXCLBJsvI8pZCsyMGVoqJzj11Jw7g1fO1gr1BvlUKgcA4YgIrDgVBkJEMBDhLEGIFcIAgmBgqBhyFAEVooQACkKGsgQDJ2hBAmGM41kH7Dm4QAAjHAyMDkOAwByYCuoKBKZAwPrF1gQMAFmRF8MN+J4JPlpToGRdnsgABWsQ4ACFy5Xqw4ZOgkQ24GP4uGICQYJgdwAmDfFutVNTpksyEs+YxQXMnBswADqgWIyAAHAAGcMnOJwR-lzB0xOOB+3addwxYABHEhUBYQcZGHUckELTcQHidBUGbVtw1iBslBCABFEgIHgI9wxgS9n1YV8kAAFnI8tUEMPCAGE6BHdMoGgcCQERHZL1iLD+g0DQgA)
```sh
# Options
--use-tabs
--tab-width 4
```

**Input:**
```js
const store = useLoggerAndDevTools
	? createStore(
			reducer,
			logRedux
				? compose(applyMiddleware(createLogger(), thunk))
				: compose(applyMiddleware(thunk))
>		)
	: createStore(reducer, applyMiddleware(thunk));
```

**Output:**
```js
const store = useLoggerAndDevTools
	? createStore(
			reducer,
			logRedux
				? compose(applyMiddleware(createLogger(), thunk))
				: compose(applyMiddleware(thunk))
>	  )
	: createStore(reducer, applyMiddleware(thunk));
```
**Expected behaviour** (as it were in **v1.10.2**):
```js
const store = useLoggerAndDevTools
	? createStore(
			reducer,
			logRedux
				? compose(applyMiddleware(createLogger(), thunk))
				: compose(applyMiddleware(thunk))
>		)
	: createStore(reducer, applyMiddleware(thunk));
```

v1.11.1 is mixing tabs and spaces as shown in output. ESLint is throwing an exception [no-mixed-spaces-and-tabs](https://eslint.org/docs/rules/no-mixed-spaces-and-tabs).

Is it a bug? If not maybe there should be an option for mixing spaces and tabs for alignment.

**Comment by lydell** [comment] 2018-03-24 19:52
As far as I know, it is on purpose. I think essentially the same discussion is currently going on in #4198.

Since you mention ESLint … if that's your only issue the solution is easy. We recommend turning off all conflicting ESLint rules: https://prettier.io/docs/en/eslint.html#turn-off-eslint-s-formatting-rules

**Comment by kiruh** [comment] 2018-03-24 21:19
@lydell I know that it's possible to disable ESLint formatting rules, but mixed spaces and tabs just don't look very good (for me).

I've heard:
> Use tabs for indentation, spaces for alignment.

But maybe it should be optional. Because for me 2 tabs look more readable than 1 tab and 2 spaces. Even if it's not aligned.

In #4198 the main discussion is about nested tabs.

**Comment by lydell** [comment] 2018-03-25 10:29
> I know that it's possible to disable ESLint formatting rules, but mixed spaces and tabs just don't look very good (for me).

Pro-tip: Actually say so from the beginning then! Thanks :)

**Comment by thorn0** [comment] 2018-03-26 15:54
@kiruh How does this indentation look to you (let's pretend that those spaces are tabs)?
```ts
const store = useLoggerAndDevTools
    ? createStore(
        reducer,
        logRedux
            ? compose(applyMiddleware(createLogger(), thunk))
            : compose(applyMiddleware(thunk))
    )
    : createStore(reducer, applyMiddleware(thunk));
```

**Comment by kiruh** [comment] 2018-03-27 06:14
> How does this indentation look to you (let's pretend that those spaces are tabs)?
@thorn0 It looks good.

**Comment by alexgv99** [comment] 2018-04-04 17:54
You have to change the eslint rule so it support smart-tabs:
`		"no-mixed-spaces-and-tabs": ["warn", "smart-tabs"],`

**Comment by kiruh** [comment] 2018-04-05 06:12
> I know that it's possible to disable ESLint formatting rules, but mixed spaces and tabs just don't look very good (for me).

> But maybe it should be optional. Because for me 2 tabs look more readable than 1 tab and 2 spaces. Even if it's not aligned.

**Comment by suchipi** [comment] 2018-04-05 07:59
Sorry; thanks for the clarification.

I don't have a horse in this race since I don't use tabs. I'll let those with informed opinions discuss this.

**Comment by teameh** [comment] 2018-04-25 10:05
I don't care either about the default. But I expect `"no-mixed-spaces-and-tabs": ["error"],` to result in no `smart-tabs` when using `eslint-config-prettier`. Currently that is not the case, I keep getting spaces.

**Comment by lydell** [comment] 2018-04-25 11:37
@teameh Please open an issue in [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) if there’s something it could do better :)

**Comment by j-f1** [comment] 2018-04-25 11:38
@teameh Prettier’s use of mixed spaces and tabs is not configurable. `eslint-config-prettier` is designed to disable conflicting rules, not to alter Prettier’s behavior. We recommend removing all formatting-related rules from your ESLint config.

**Comment by kiruh** [comment] 2018-04-25 13:51
> Prettier’s use of mixed spaces and tabs is not configurable.
@j-f1 Should it become configurable in future?

**Comment by j-f1** [comment] 2018-04-25 15:41
@kiruh Not right now — see [our option philosophy](https://prettier.io/docs/en/option-philosophy.html).

**Comment by thorn0** [comment] 2018-04-26 09:55
I wonder if there exists a tab user who would oppose to a spaceless formatting like this: 
 1) https://github.com/prettier/prettier/issues/4199#issuecomment-376216586
 2) https://github.com/prettier/prettier/issues/4198#issuecomment-375903278

If there is no any, what is needed here is not configurability then.

**Comment by duailibe** [comment] 2018-05-16 12:08
@jankalfus Sorry that's an issue. Unfortunately saying it "doesn't feel right" adds nothing to the discussion.

If you want to help, we'll take suggestions on how to improve this (no options), with real code examples. Or PRs.

@thorn0 Are you interested in opening a PR with your suggestion?

**Comment by jankalfus** [comment] 2018-05-16 13:29
@duailibe Sorry for not being specific. I guess my question would be: Why has this even been introduced? What is the reasoning behind it?

I simply don't understand why someone would want to mix tabs and spaces. Generally, if spaces are used, then it's because it is required that the code looks the same on all people's monitors. If tabs are used, then everybody can use whatever tab size they prefer. If I change tab size on my machine, the code will look broken with mixed spaces.

**Comment by duailibe** [comment] 2018-05-16 13:53
@jankalfus Because prettier aligns everything after `?` (in the OP that would be `createStore` aligned with the closing `)`).

**Comment by jankalfus** [comment] 2018-05-16 14:06
@duailibe I gave you an explanation. Taking a single sentence out of context doesn't make the rest of my post irrelevant.

**Comment by ikatyang** [comment] 2018-05-16 14:13
> If tabs are used, then everybody can use whatever tab size they prefer.

The question is, tabs-only is not aligned, which is why someone raised #2771.

```js
const store = useLoggerAndDevTools
	? createStore(
			reducer,
			logRedux
				? compose(applyMiddleware(createLogger(), thunk))
				: compose(applyMiddleware(thunk))
		) // <------------
	: createStore(reducer, applyMiddleware(thunk));
```

> If I change tab size on my machine, the code will look broken with mixed spaces.

What do you mean `broken`? There shouldn't be any visual difference with or without `--use-tabs`.

**Comment by jankalfus** [comment] 2018-05-16 14:46
Scratch everything I said. You're right, it doesn't get broken with mixed tabs and spaces, I just realized it. Sorry!

**Comment by suchipi** [comment] 2018-05-24 01:49
I'm going to close this as intended behavior. The arguments against doing this seem to be based on personal preference. However, if someone has a bad experience in their editor because of this and can explain why, I would be open to reconsidering.

**Closed by suchipi** 2018-05-24 01:49 UTC
Labels: lang:javascript, status:needs discussion
