### ISSUE TITLE
prettier doesn't know what to do with numeric object keys

### ISSUE THREAD

**Issue by kaiyoma** [prettier/prettier#7796] opened 2020-03-19 18:13 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mwAOlJpgIxKYDk0ctANGRbQEy020wDuEzVpgDM3GAAsATnEYsoAXwDcZEExAQADjACW6ZKACGkyRF4AFIwjTIQBgG4RtAE1UgARpINgA1nBgBlDS9tKABzZBhJAFc4NXEYAFsAGwB1cW14NCCwOH8rDO07DIBPGzA0azUQtDhJGDNPUISDZGwDJJq1ACs0AA8AIU8fP38DBLgAGRC4VvbOkB7e-xDQpLgARSiIeFmO2JAgyRrJGzcDNzgk1w1JEJgU5wlkAA4ABjUbiBqUzw0bG7gxzsMzUAEctvAGpprCgDGgALRQGROOAuNTScHaaQNAxNFpINp7NQ1BLaCLRfZoFZrTbbGYEub7GDnB5OJ5IdhqSIGbRJFYAYQgCWaNigDFcURqABVzjDCfM7DEAJJQFGwfxgW5aACCqv8MGKa12NXk8iAA)
```sh
--parser babel
```

**Input:**
```jsx
const foo = {
  1: 'one',
  '2': 'two',
  3: 'three',
};

```

**Output:**
```jsx
const foo = {
  1: "one",
  "2": "two",
  3: "three"
};

```

**Expected behavior:**
You can see that changing the `quote-props` setting does nothing to the output, but it should. Even when picking `as-needed` or `consistent`, the behavior is always `preserve`.

**Comment by thorn0** [comment] 2020-03-19 18:26
duplicate of https://github.com/prettier/prettier/issues/6064

**Closed by thorn0** 2020-03-19 18:26 UTC
