### ISSUE TITLE
Try block

### ISSUE THREAD

**Issue by koriroys** [prettier/prettier#2048] opened 2017-06-08 11:37 UTC
Was having trouble getting a file to parse. Here is a reduced test case:

```
try {
  func(00);
}
```
which gives me this output:

```## Prettier CLI Error Output:

stdin: SyntaxError: Invalid number (2:8)
      1 | try {
    > 2 |   func(00);
        |        ^
      3 | }
      4 | 
    
## Prettier CLI Return Code:

    2
```

Without the try block though, gives me no issues:
```
func(00);
```

Any idea what's going on here?

**Comment by k15a** [comment] 2017-06-08 11:47
This is working with a [catch block](https://prettier.github.io/prettier/#%7B%22content%22%3A%22try%20%7B%5Cn%20%20func(00)%3B%5Cn%7D%20catch%20(e)%20%7B%5Cn%20%20%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D). Might be a bad error message.

**Comment by koriroys** [comment] 2017-06-08 11:54
Yeah, think it might be a bad error message. Here is some [more weirdness](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20wat%5Cntry%20%7B%5Cn%20%20func(00)%3B%5Cn%7D%20catch%20(e)%20%7B%5Cn%20%20%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by koriroys** [comment] 2017-06-08 11:57
Also, why wouldn't it have an error message with the second case I posted, without the try/catch?

**Comment by k15a** [comment] 2017-06-08 12:10
After some consideration, I think this is because we are using non-strict mode of Babel. With strict mode enabled you'll get an error for both examples because octal numbers are not allowed. I don't know why Babel has a wrong error message for the first example because AFAIK the problem isn't the octal number but the missing catch block.

The missing comment is indeed an issue. I am not aware that this error is already tracked or fixed.

**Comment by azz** [comment] 2017-07-16 08:01
Going to close this as the comment issue (https://github.com/prettier/prettier/issues/2048#issuecomment-307081349) appears to be fixed, and the syntax is invalid, so we're correct to error.

The misleading error message should be raised with babylon.

**Closed by azz** 2017-07-16 08:01 UTC
Labels: dependency
