### ISSUE TITLE
TypeScript `as` regression (2.0.3)

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#7957] opened 2020-04-05 22:51 UTC
**Prettier 2.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT7AA6U++ATnDOvbdbXYcQDQ2dcRu-PvgC++AIYBnfADEA8vJqiQ3EBAAOuaFOSgJ9ehADuABQMJdKCQBtjEgJ661AI3oSwAayYBlDR5woAHNkGHp0ODUACxgAWxsAdSiceCl-MDgfSxScADcUh2RwKWcQQKk4ehhTdyDYiWRUWwq1ACspAA8AIXcvXwlYuAAZQLhG5siQdo6fQKCbOABFdAh4cZsWkH96CvoimAcNOCkwehwtVS2z2AScABMYKOQADgAGNQ0jCoT3DSLP46VXJjNQARxW8BqmisIGkAFooHA4HdkZdGOCcIwahI6g0kE0NpMKrEcKFwkS5gtlqsxviJmoYBIXLcHk8kAAmBnuHA2OYAYQgsXqRWOAFZLugKgAVJlWAmbXIRACSUBRsB8p3OMAAgqqfAcFusKqJREA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```ts
function foo() {
  return {
    foo,
    foo,    
  } as FOO
}
```

**Output:**

```ts
function foo() {
  return (
    {
      foo,
      foo,
    } as FOO
  );
}
```

**Expected behavior:**

same as input
```ts
function foo() {
  return {
    foo,
    foo,    
  } as FOO
}
```

**Comment by sosukesuzuki** [comment] 2020-04-05 23:16
I think we should revert #7869 and implement a handler for `TSAsExpression` that is different from the one for `BinaryExpression`.

**Comment by thorn0** [comment] 2020-04-05 23:58
The problem arises only if the first operand is an object literal, right? So we rather need to handle this situation as a special case.

**Comment by domoritz** [comment] 2020-04-06 03:03
Here are a few more examples where I am seeing this regression in my codebase in case it's helpful. 
<img width="387" alt="Screen Shot 2020-04-05 at 20 02 03" src="https://user-images.githubusercontent.com/589034/78519466-5390c980-7778-11ea-9a12-cc885e5dc05c.png">
<img width="714" alt="Screen Shot 2020-04-05 at 20 01 08" src="https://user-images.githubusercontent.com/589034/78519437-33610a80-7778-11ea-9d34-c955df2286d3.png">
<img width="849" alt="Screen Shot 2020-04-05 at 20 01 24" src="https://user-images.githubusercontent.com/589034/78519453-3bb94580-7778-11ea-874c-ee5eb8874f6c.png">
<img width="806" alt="Screen Shot 2020-04-05 at 20 01 34" src="https://user-images.githubusercontent.com/589034/78519459-4247bd00-7778-11ea-8fc1-47cc2e4105f0.png">

**Comment by domoritz** [comment] 2020-04-06 03:04
Duplicate of #7956?

**Comment by thorn0** [comment] 2020-04-06 07:44
@domoritz Could you please paste your examples as code not as screenshots so that we could use them for testing?

**Closed** 2020-04-06 10:52 UTC
Labels: lang:typescript, type:bug

**Comment by domoritz** [comment] 2020-04-06 15:52
I thought screenshots show the changes well. I merely posted them so you can confirm that these are all "the first operand is an object literal". Let me know which code snippets you want (they are all taken from https://github.com/vega/vega-lite running 2.0.3 vs 2.0.2).

**Comment by thorn0** [comment] 2020-04-06 18:23
@domoritz We've already solved this situation. Vega-Lite looks like a good codebase to test new versions of Prettier for regressions before releasing. I've made a note of it.

**Comment by domoritz** [comment] 2020-04-06 18:41
Great! typescript-eslint is also using Vega-Lite as a test case: https://github.com/typescript-eslint/typescript-eslint/blob/master/tests/performance/fixtures/lint-real-repo/Dockerfile#L7
