### ISSUE TITLE
Blank line before semicolon followed by self invoked function.

### ISSUE THREAD

**Issue by andreolvr** [prettier/prettier#4493] opened 2018-05-17 01:57 UTC
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAHAhjAC0wF5MAnOARwFcBLCgCgHI9CmBKAHSkig0wBmaEuSp1GTIR27cA3AwbsSAPkzBumTAHot3AL7sQAGhARsMWumShcZMhADuABVsI0yELgBuEWgBNjEAAjMlwwAGs4GABlPDBaKABzZBgyajgTBLQ4MhgnUMSAW1xkAVwAG2yTACs0AA8AIVCIqOjcQrgAGQS4UoqqkDwybLIPINwggE9y6EDsMgSYAHV-QmQADgAGE3mIbKXQ7A95uBGvXpMKGno4fNwikqQyyoyQbMLaPpeTNATE8rgAEVqBB4Ck0q8YBMVn41kgAEwmVK4WjlP4AYQghWKHig0AuIGo2QAKhN3E9+nA9HogA)
```sh
--no-semi
--single-quote
```

**Input:**
```jsx
const path = require('path')
const fs = require('fs')

;(() => {
  //
})
```

**Output:**
```jsx
const path = require('path')
const fs = require('fs')
;() => {
  //
}

```

**Expected behavior:**
I would expect to be able to put blank lines before semicolons followed by self invoked functions when using --no-semi. It's really sad that i have to keep my self invoking function right after my requires without being able to organize the code with blank lines.

**Comment by ikatyang** [comment] 2018-05-17 04:20
Hi, this is a duplicate of #1510, see https://github.com/prettier/prettier/issues/1510#issuecomment-299496344 for more info.

**Closed by ikatyang** 2018-05-17 04:20 UTC
