### ISSUE TITLE
MDX: Prettier breaks on `import` word

### ISSUE THREAD

**Issue by B2o5T** [prettier/prettier#11795] opened 2021-11-09 14:50 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKBLAJkgAgGcwALOAWwENUK4AnAc2ykaxmxgBs5CBlMpSoE6TFmyhE8cAEZV6AfS5UZcLv0HURDZqyzpUWLABVy9OAXkWYAdwgEbVAJ5ECTiAFcCYKlAIeia1JsVwAHKjAAaypGXiMoVBFfDyouLicCbApQiHoYAjgI0gIYJ1C4fUzs3Py4ADcGJxhg1gIAM3oICkticrBsNuw4XHaILlwGeIBiGYIAWWTUqpy8ohAAGhAIUI5oNaRQeU6bAAUrSWQQVMcXDZAZegjIuBg+cP7WZBh6DzhNylUuAmuAAMr5GClYgAxXLUGAcT4oKgeGAQO6kGAULgAdWC8CI7zgfAQUg4dU4TkuYCIa02LECeROj0Y1GQbVSgU2ACsiAAPABCjyiLz4VDoIJYcDZHL+IB5vL44h4AEUPBB4NKuJyQOF6AzLhRcLy7qF6CwYNi8M1kAAOAAMm1NEEC2MeoUuprgDIadwAjmr4EztvsrkRUFA4MNhndzP7sOYmTFWUh2VrZYEKNgvj900q4Kr1VKUzLNjAVJbcNakAAmUuPbBccQAYS6yZAXoArHcAnBjCp9qntXVfgBJKATWACM07ACC474pR4msCAF8V0A)

```sh
--parser mdx
```

**Input:**

```mdx
---
id: schema-merging
title: Schema merging
sidebar_label: Schema merging
---

There are two ways you can use this package:

- manually import each type
- import everything from a specified folder

### Manual imports
```

**Output:**

```mdx
SyntaxError: Unexpected token (1:24)
> 1 | import everything from a specified folde
    |                        ^
```

**Expected behavior:**

**Comment by thorn0** [comment] 2021-12-10 15:59
Duplicate of #6950

**Closed** 2021-12-10 16:00 UTC
Labels: type:bug, type:duplicate, lang:mdx
