### ISSUE TITLE
[markdown] * is incorrectly formatted as _ or \*

### ISSUE THREAD

**Issue by hyuuko** [prettier/prettier#8880] opened 2020-08-01 05:44 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqAhgA1ZgOlfdVAI20zDJABoQIAHGAS2gGdlR0AnTiAdwAUuCNinQAbXugCebGsU7owAazgwAynUWMoAc2QxOAVzg0AFjAC2YgOqnG8FprBw1w+4wBu9qcnAtZINoscJww-Ao6FujIAGbiwTQAViwAHgBCCsqqaugWcAAy2nCx8SYgySlq2jpicACKhhDwJWIJIJqcwZy+UZxKACZ8UNTtnNow1oz9MKbIABwADDR0PMHWCnS+K3BdHsU0AI6N8OH0IiDoLAC0UHBw-fcjnHBHjM-h6JHRSHGtZcEWRj6Iz-aq1BpNYo-Uo0GDoYiTaazJAAJlhCkYYmqAGEIBYor4dgBWEaGYIAFXhIl+bQ8xgAklAHrA1GAxgwAIJMtQwKS1FrBAC+gqAA)
```sh
--parser markdown
```

**Input:**
```markdown
*a`*`

a*b`*`c`*`
```

**Output:**
```markdown
_a`_`

a*b`*`c`\*`

```

**Expected behavior:**
```markdown
\*a`*`

a\*b`*`c`*`

```

**Comment by evilebottnawi** [comment] 2020-08-01 12:17
Not sure it is right expected behavior, we can't change AST, and change characters on escaped

**Comment by Hyuuko** [comment] 2020-08-01 12:47
Another example: [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABAKnQIwAaZ5gF4gA0IEADjAJbQDOyoqATqxAO4AKbCTKVABtOqAJ5MKOVqjABrODADKVWbSgBzZDFYBXOBQAWMALZCA6odrwGqsHCX9rtAG7WxycA0kh1DOKww3DIaJqjIAGbC-hQAVgwAHgBCMvKKSqgmcAAy6nCR0QYg8QlK6hpCcACKuhDwBUIxIKqs-qyeYaxyACZcUOTNrOow5rTdMIbIABwADBRUHP7mMlSeC3BtLvkUAI618MHUAmgMALRQcHDdVwOscHu0d8GooeFIUY1F-ia02npf5UqNTq+XehQoMFQOFG40mSAATBCZLQhOUAMIQExhTwbACsA10-gAKlCBB8mi59ABJKDXWBKMBDGgAQVpShgYkqDX8AF8eUA)

**Input:**
```markdown
a * b`*`c`*`
```
GitHub renders it as:
a * b`*`c`*`
So I think the expected behavior should be:
```markdown
a \* b`*`c`*`
```
**Prettier's Output:**
```markdown
a _ b`_`c`\*`
```
GitHub renders it as:
a _ b`_`c`\*`

Perhaps the AST generated by Prettier was wrong?

**Comment by evilebottnawi** [comment] 2020-08-05 14:28
I think it is fixed in master, but we need to add tests

**Comment by thorn0** [comment] 2020-11-18 12:12
Duplicate of #7695

**Closed by thorn0** 2020-11-18 12:12 UTC
Labels: lang:markdown, status:needs investigation
