### ISSUE TITLE
prettier incorrectly reports an extraneous closing tag which is correct

### ISSUE THREAD

**Issue by JonathanDCohen** [prettier/prettier#7640] opened 2020-02-19 22:22 UTC
**Prettier 1.19.1**
```json
    "printWidth": 120,
    "bracketSpacing": false,
    "trailingComma": "es5"
```
In the below input, outline-cloud-instructions is a Polymer element
**Input:**
```html
<outline-cloud-instructions-view title="[[localize('manual-server-assign-firewall')]]" thumbnail-path="images/gcp-thumbnail-2.png" image-path="images/gcp-screenshot-2.png"" localize="[[localize]]">
  <ol>
    <li inner-h-t-m-l="[[localize('gcp-firewall-assign-0', 'openLink', '<a href=https://console.cloud.google.com/compute/instances>', 'closeLink', '<iron-icon icon=open-in-new></iron-icon></a>')]]"></li>
    <li>[[localize('gcp-firewall-assign-1')]]</li>
    <li>[[localize('gcp-firewall-assign-2')]]</li>
    <li>[[localize('gcp-firewall-assign-3')]]</li>
    <li>[[localize('gcp-firewall-assign-4')]]</li>
  </ol>
</outline-cloud-instructions-view>
```

**Output:**
```
[error] ui_components/outline-manual-server-entry.html: SyntaxError: Unexpected closing tag "outline-cloud-instructions-view". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (206:15)
[error]   204 |                   <li>[[localize('gcp-firewall-assign-4')]]</li>
[error]   205 |                 </ol>
[error] > 206 |               </outline-cloud-instructions-view>
[error]       |               ^
[error]   207 |             </div>
[error]   208 |           </iron-collapse>
[error]   209 |         </div>
```

**Expected behavior:**

No error

**Comment by JonathanDCohen** [comment] 2020-02-19 22:25
A similar false error happened in a different file:

```html
        <p>
          <div>[[localize('server-unreachable-description')]]</div>
          <span hidden$="{{isServerManaged}}">[[localize('server-unreachable-managed-description')]]</span>
          <span hidden$="{{!isServerManaged}}">[[localize('server-unreachable-manual-description')]]</span>
        </p>
```

led to the same error that the </p> tag is extraneous

**Comment by thorn0** [comment] 2020-02-20 13:36
1. Your first snippet has an extra quote mark after `image-path`. The error is confusing, but is caused by invalid markup.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeCBXGAbAllOAWjG0wBND8BnGAJwzBl2isIDdc4B3AAlwFsAhgHMiAB0EwAFgF4AOiAEi4VAPTCwYwlTC04CKlIgxCAJgB0YqMIUKAfHKipVmHPiIlylKDXqNmPuycXHYgADQgEGJMLMiggrS0EFwACgkGyCCCbBC4ZOEgAEa0gmAA1nAwAMoSYPjCyHQYcBFSMPzYAOpSuPBUtXBVBr24HDAAnplgVFQF1HC0MCklwkLIAGaC2FQtIABWVAAeAEIl5ZVVgvxwADLuG1s7EQeHVfXYcACKGMZwD9u7CS0Ha0TJtDoFMS0fAwTp5aTIAAcAAYIlCIDtOiUxJkoSoFmw-hEAI4-eDLKKzFCCVgEOBkekFPSk3B6ZYiNZITYAiI7fi4Rr0XZUd5fMl-LmPXYwQSFOFkBFIUwROiCXB4awAYQg-E5ICg0CJIAwOwAKrKqdyniA2M0AJJQBmwKq6XDRACCjqqEw+-x2AF9-UA)
```sh
--parser html
```

**Input:**
```html
<outline-cloud-instructions-view image-path="images/gcp-screenshot-2.png"">
</outline-cloud-instructions-view>
```

**Output:**
```html
SyntaxError: Unexpected closing tag "outline-cloud-instructions-view". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (2:1)
  1 | <outline-cloud-instructions-view image-path="images/gcp-screenshot-2.png"">
> 2 | </outline-cloud-instructions-view>
    | ^
```

----

2. The second one works as expected. In HTML, `div` can't be nested inside `p`, that's why the opening tag of `div` closes `p`. The error message itself explains this; "SyntaxError: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (5:9)".

**Closed by thorn0** 2020-02-20 13:36 UTC
Labels: lang:html, type:bug
