### ISSUE TITLE
Support for liquid template tags?

### ISSUE THREAD

**Issue by bchiang7** [prettier/prettier#4056] opened 2018-02-26 22:58 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwCkACOAPeUAmAzhgDogBGAhoXAHQwDuAlgOZkZoC+JUP6G5ADYQwAawyRYCGB25QAPPiYA3CYOqEAvGUl4YZAHzyA9EuUGQAGhAQADjCbRCyUJQBObiAwAK7hM5RKZQgmfCsQahhkADNKQRprcjdKMTgYAGVbFKYoFmQYNwBXOGt8ERi4hJAcmjcYb2SWAFtKCviSkAArQmwAIWTUjMomuAAZHLg2qohCmFtZgCYpjqy3WuQKSnIAT2EocNs3HJgAdVCYAAtkAA4ABmtDiBoT5NsNw7ha5UnrNzgAR0KTD+DUozVaSFi7WsNCaTHyRQ6hByLEEcAAioUIPBltYYFszvhLsgFnjkkxBCiAMIQJotDZQaA-ECFGgAFS2AShNE4nCAA)

**Input:**
```jsx
{% extends "base.twig" %}

{% block content %}
<div class="content"></div>
```

**Output:**
```jsx
SyntaxError: Unexpected token (1:2)
> 1 | {% extends "base.twig" %}
    |  ^
  2 | 
  3 | {% block content %}
  4 | <div class="content"></div>
```

**Expected behavior:**
Currently, in any twig or html files where liquid tags are being used, prettier removes the space between tags like so:
```
{% extends "base.twig" %} {% block content %}
<div class="content"></div>
```

One way I've found to prevent prettier from removing the line break is to add an html comment between the two tags such as `<!-- hi -->`, but then these comments create syntax errors.

It looks like the prettier playground does not recognize liquid tags (i.e. `{% something %}`) and that's why the new lines are being removed. Are there any plans to support these tags in the future? Thanks in advance!

**Comment by j-f1** [comment] 2018-02-26 23:24
If you’re trying to format HTML, please be aware that we don’t yet support it: #1882.

It also looks like this is a duplicate of #3695.

**Comment by j-f1** [comment] 2018-02-26 23:24
duplicate of #3695

**Closed** 2018-02-26 23:24 UTC
Labels: type:duplicate
