### ISSUE TITLE
TypeScript: comment lost within  generic TSX component

### ISSUE THREAD

**Issue by sbusch** [prettier/prettier#6712] opened 2019-10-25 05:40 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAwhAtgB2gmVAFQD4AdKAekoAJMssCLKSBuCijbPKA48qrQAyEAM4wakBkyglUlejwJsOULrnyx+lAFQ0AhgBtREGobESdLeYs0wVUEABoQEHDACW0UclD6ATv4QAO4ACgEIPij6AG4QHgAmziAARv76YADWcDAAyjgZHlAA5sgw-gCucC4AFjBYhgDqNR7wogVgcLmRrR4xrQCeyOCiPi5FonD+MKHpxVj6yABmRpMuAFaiAB4AQulZObn6jEJFcMur1SCbW7lFxYZwAIoVEPAXxlcF-pP+wzADHBwURgfwedzJHBg2CNRIwGrIAAcAAYXFCxHBGukcMMocCpjFzi4AI6veCzNxRED6UQAWl4cASjOS-jgpI8rNm+nmiyQK0+LkmWA8ZUqV1E90eLze5z5lxcMH0KVhCXhyAATAr0h5DPd6AthlB8MkKpMiEqovzJgBfa1AA)
```sh
--parser typescript
```

**Input:**
```tsx
<Component<T>
// Comment
/>;

<Component<T>
// Lost comment
></Component>;

<Component<T>/* also lost */></Component>;
```

**Output:**
```tsx
<Component<T> />;
// Comment

<Component<T>></Component>;

<Component<T>></Component>;
```

**Expected behavior:**

I expect the comments to be retained.

One could argue on the new position of the comments, but according to the placement of the other comment, it *could* be:

```tsx
<Component<T> />;
// Comment

<Component<T>></Component>;
// Lost comment

<Component<T>></Component>;
/* also lost */
```

**Comment by lydell** [comment] 2019-10-25 06:07
We have code that is supposed to throw an error if a comment isn’t printed, but not even that seems to have worked in this case. :(

**Comment by lydell** [comment] 2019-10-25 06:09
We have code that is supposed to throw an error if a comment isn’t printed, but not even that seems to have worked in this case. :(

**Comment by thorn0** [comment] 2019-10-25 06:21
Duplicate of #6012

**Closed by thorn0** 2019-10-25 06:21 UTC
Labels: area:comments, lang:typescript, type:bug

**Comment by sbusch** [comment] 2019-10-25 11:29
Sorry for the noise, I even posted a comment to #6012 on May.

@thorn0 the issue you're referencing is closed although the bug is still present (Playground)

**Comment by thorn0** [comment] 2019-10-25 11:36
The fix hasn't been released yet. It'll be part of [1.19](https://github.com/prettier/prettier/milestone/32), which is going to happen pretty soon.

However, if it blocks you, you can install Prettier directly from GitHub.

In your `package.json`, replace
```
"prettier": "^1.18.2"
```
with
```
"prettier": "prettier/prettier"
```
