### ISSUE TITLE
Spaces get inserted to align braces even when using tabs

### ISSUE THREAD

**Issue by eamodio** [prettier/prettier#4670] opened 2018-06-11 21:50 UTC
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAEYCGATgJT7AA6U++VcM6VzlV+AhAF4B+TABM4qHFDiimLFgH58POfKT1V85RQBe6gOSUd+zfgC+AbiZmQAGhAQADrmgBnZKGpUIAdwAK1AjuKBQAbhA4onYgZFQUYADW7ADKjvFSAObIMFTocPZSrnBUMH5xGQC2FMioFAA2RfYAVq4AHgBCcYkpFBVwADJScDX1jSBpVEVUyDEUZACeddDRjlRSMADqkTAAFsgAHAAM9qsQRRtxjjOrcFOhw-ZsAI7oOGxlFJXVSLUN+SBFCo4bK5f6uTJ1OAARXQEHgIz+9hgcy2ol2yAATEi4jg6pkAMIQCpVGZQaAPEDoIoAFTmwRyeTMZiAA)
```sh
--parser babylon
--use-tabs
```

**Input:**
```jsx
function foo(bar) {
  return bar !== undefined
    ? bar
    : {
      baz: 'baz'
    };
}
```

**Output:**
```jsx
function foo(bar) {
	return bar !== undefined
		? bar
		: {
				baz: "baz"
		  };
}
```

**Expected behavior:**
```jsx
function foo(bar) {
	return bar !== undefined
		? bar
		: {
				baz: "baz"
		};
}
```

Notice the 2 spaces not there before the 2nd to last `}`

**Comment by j-f1** [comment] 2018-06-12 00:11
Thanks for reporting this! Someone opened an issue about this before, so please follow along there instead.

Duplicate of #4199.

**Comment by j-f1** [comment] 2018-06-12 00:11
Duplicate of #4199

**Closed by j-f1** 2018-06-12 00:11 UTC
Labels: lang:javascript, type:duplicate
