### ISSUE TITLE
JSDoc typecasting paranthesis removed in typescript parser

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [prettier/prettier#9620] opened 2020-11-08 21:46 UTC
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mAFAEYCGATgJSEB8mwAOlJpgJbbED0AVL5gACMAJ4AHOI14BfTL25kq1AHQUAXrUpwYAV0pQW0liAA0ICGJjt0yUFUoQA7gAUqCNMhDkAbhHYATUxBSSnIwAGttAGUxMPYoAHNkGEodODM4AFtSOH9-XIAZckSdcgS4ADEISkzyGCtEzwhsbCCACxhMgBsAdTb2eDRYsDgo9wH2bwGRTzA0DzN4tDhKGGdQhNrkbHIu5bMAKzQADwAhUIjo8ky4Avi4ZNT0kCPjqPiErrgARR0IeEeaTMsUoy0onlEEjQYEo7EsQTEsNgPQCMDayAAHAAGYEOZY9UJiTyIuBg7wPMwARz+8HWFg8KBJZIpIC01PYWnWZS2SB2e2ey0y7G2u32IDQHy+v3+D15oueMHIpBR-jRyAATGYUuR2F0PgBhCCZHkgUkAViCOmWABUlQy+WLvGkAJJQfKwKIwuEwACCbqioi+Iv50mkQA)

**Input:**

```js
const foo = (bar) => {
  if(/** @type {*} */(bar).baz) return
}
```

**Output:**

```jsx
const foo = bar => {
  if (/** @type {*} */ bar.baz) return
}
```

**Expected behavior:**

It should preserve the paranthesis behing jsdoc typecasting. Like this:
```js
const foo = bar => {
  if (/** @type {*} */(bar).baz) return
}
```
Otherwise, it destroys the purpose of JSDoc typecasting. The Parentheses are required.

I've seen that there was some PR that would solve this. But as you can see it's still like that :(

Not sure whether it's something to be fixed in `typescript-eslint / typescript-eslint`?
Or is there a config that I overlooked? 

Thank you!

**Comment by thorn0** [comment] 2020-11-08 23:00
Duplicate of #8171

**Closed by thorn0** 2020-11-08 23:00 UTC
