### ISSUE TITLE
Prettier fails on "valid" invalid HTML

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier#10469] opened 2021-03-06 00:32 UTC
This code runs fine in a browser console:

```js
document.body.insertAdjacentHTML('beforeend', `
<div
  attr="asdf"
  // slash here
>
</div>
`)
```

But prettier has an error:

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4B0oAEBAhjDAE4C8uIxAzugGY35ED0bBdANvQBYE+ccnHwA+fKjZZsYkABoQEAA4xM0OslDFy5CAHcACjoSaUxbvuIBPTYoBG5YmADWcGAGVlzzFADmyBQArnCKcAC29nDo6NEAMsT+QcR+cABiEOThpGr+yLRBMBAKIHww4dwA6nyY8HTeYHAeprU4tdb5YHR2IL50wjCGTn7ZyIwW-YoAVnQAHgBCTq7uHsThcHG+cGMToSAzsx6+ftxwAIpBEPA73JMg3uT95PllFSXK5L4wlZjoMHzIAAcAAZFB8IP1Kk5lPkPnAnthtooAI6XeBDFRmWh0AC0UDg0WiJREqMwIiGKVGSHGtz2-XCmEC5BCijox1OFyu22pu0UMGI9h+fwBSAATHynJhuMcAMIQcJUkDwgCsJSC-QAKgKzDS7tgQgBJKCxWAeMCfVQAQWNHhg1lON36AF8nUA)

**Input:**

```jsx
<div
  attr="asdf"
  // slash here
>
</div>
```

**Output:**

```
SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (5:1)
  3 |   // slash here
  4 | >
> 5 | </div>
    | ^^^^^^
```

**Expected behavior:**

Should it pass? It works in native HTML, so perhaps it should work in Prettier. There are other forms of "wrong" (but parseable in browser) HTML that Prettier _does_ accept, [for example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4B0oAEBAhjDAE4C8uIxAzugGY34B8+RqADu1BjqxAAaEBC4xM0OslDFy5CAHcACnITSUxADaLiAT2kiARuWJgA1nBgBlLmcxQA5sgoBXOCLgBbI3HTo-ABliJ1diRzgAMQhyL1IJJ2RaVxgIYRAACxgvLQB1DMx4OjswOGt1QpxCvSSwOkMQBzo4chhlU0c45EZtZpEAKzoADwAhUwsra2IvOECHOG7ejxBBoesHRy04AEVXCHhFrT6QO3Jm8iSsnPSucgcYXMx0GAzkAA4ABhFbiGbc0y4SVucHO2AWIgAjnt4O0xBpaHQALRQOB+PzpchwKGYTHtcJdJA9I7LZpeTAucjuER0DZbXb7BaEpYiGDEIyPZ6vJAAJhZpkwWg2AGEIF4CSAQQBWdKuZoAFTZGiJx2w7gAklAArBrGA7uIAIKa6wwPRbQ7NAC+FqAA).

**Comment by fisker** [comment] 2021-03-06 00:48
Is there any html code that browser can't parse ?

**Comment by trusktr** [comment] 2021-03-06 01:15
Oh.. Right.. it never fails. :smile:

When there are `/` inside the attribute area before closing, elements turn out fine. F.e. in console this works:

```js
document.body.insertAdjacentHTML('beforeend', `
<div
  attr="asdf"
  //
>
test
</div>
`)
```

**Comment by thorn0** [comment] 2021-03-06 07:01
Duplicate of #8210

**Closed** 2021-03-06 07:02 UTC
Labels: type:duplicate
