### ISSUE TITLE
New Git Ingore Logic Not Taking All Ignores Files Into Account

### ISSUE THREAD

**Issue by joealden** [prettier/prettier#15133] opened 2023-07-20 15:31 UTC
**Environments:**

- Prettier Version: 3.0.0
- Running Prettier via: CLI
- Runtime: Node.js v16
- Operating System: Linux
- Prettier plugins (if any): None

**Steps to reproduce:**

- Create a top level `.gitignore` file (on the same level as the prettier config/ignore)
- Create a directory that contains a file/directory to ignore, then add this to a new `.gitignore` file in this directory.
- Run prettier format.

**Expected behavior:**

Prettier takes these nested/local `.gitignore` files into account correctly (noting that contents are relative to the directory).

I've run into this because I have a monorepo where each workspace is responisble for it's own `.gitignore`, but as I believe prettier only supports a single ignore file, I've had to define ignores for prettier in the single top level file. It'd be nice if I didn't have to still do this after v3, as for me, I don't want any files I ignore for git (which supports local ignore files) to be formatted.

**Actual behavior:**

Prettier doesn't take these local `.gitignore` files into account (or does but maybe not correctly), so removing prettier specific ignores after the 3.0.0 release meant that files that are ignored by git are still getting formatted.

**Comment by TyIsI** [comment] 2023-07-31 22:04
I'll add that it gets worse. But I'm creating an issue for that.

**Comment by kachkaev** [comment] 2023-11-24 22:51
I guess this issue is a duplicate of https://github.com/prettier/prettier/issues/4081, let’s track it there.

**Closed by kachkaev** 2023-11-24 22:51 UTC
