### ISSUE TITLE
Prettier errors on comment

### ISSUE THREAD

**Issue by oof2win2** [prettier/prettier#14412] opened 2023-02-25 09:01 UTC
**Environments:**

- Prettier Version: 2.8.4, 3.0.0-alpha.4
- Running Prettier via: CLI
- Runtime: Node v16, v18
- Operating System: Linux
- Prettier plugins (if any): None

**Steps to reproduce:**
Run `yarn prettier --no-config --write src/` with the following code in `src/test.ts`
```ts
const diffTakenActions = () => {
  for (const [_, actionId] of actions) {
    if (!prevReportId && !newReportId) continue; // if the action wasn't taken before or after, skip it
    else {}
  }};
         
export default diffTakenActions
```

**Expected behavior:**
It will be fine
**Actual behavior:**

Prettier throws an error:
```
src/test.ts
[error] src/test.ts: Error: Comment "if the action wasn't taken before or after, skip it" was not printed. Please report this error!
[error]     at ensureAllCommentsPrinted (file:///home/fagc/a/node_modules/prettier/index.mjs:16410:13)
[error]     at coreFormat (file:///home/fagc/a/node_modules/prettier/index.mjs:17075:3)
[error]     at async formatWithCursor (file:///home/fagc/a/node_modules/prettier/index.mjs:17252:14)
[error]     at async formatFiles (file:///home/fagc/a/node_modules/prettier/internal/cli.mjs:7953:18)
[error]     at async main (file:///home/fagc/a/node_modules/prettier/internal/cli.mjs:8153:5)
[error]     at async Module.run (file:///home/fagc/a/node_modules/prettier/internal/cli.mjs:8099:5)
error Command failed with exit code 2.
```
**Act

**Comment by oof2win2** [comment] 2023-02-25 09:04
Possibly linked with #14142, though that has apparently been marked as fixed

**Comment by fisker** [comment] 2023-02-26 23:43
Duplicate of #12655

**Closed** 2023-02-26 23:43 UTC
Labels: type:duplicate
