### ISSUE TITLE
Ignoring Unsupported Files (Programattically).

### ISSUE THREAD

**Issue by jspears** [prettier/prettier#8351] opened 2020-05-19 16:59 UTC
Is there a way to configure prettier to exclude processing file types it doesn't understand?   I know about prettierignore, however I need a more programattic approach to ignoring code.   I maintain a build tool called [mrbuilder](https://mr-builder.github.io) which is like a universal configurator for JS/TS applications.   I would like to make prettier just work without any extra configuration based on the plugins that are installed. 

However mrbuilder supports some file types such stylus that prettier does not, which is fine, if I could do something like

```js
conf.overrides.push({
            excludeFiles: ["*.styl"],
  });
```

That'd be great, but alas this causes errors. 

 Perhaps a *null* parser that just
passes through?   

Any guidance is appreciated.

**Comment by thorn0** [comment] 2020-05-21 16:01
You have at least two options for now:
- Handle the errors (`try ... catch`), there in nothing wrong with that.
- Use [`prettier.getSupportInfo`](https://prettier.io/docs/en/api.html#prettiergetsupportinfo) to get the list of supported languages and file names and extensions associated with them.

**Comment by thorn0** [comment] 2020-06-04 20:00
@jspears You wrote "programmatically", but I looked at https://github.com/mr-builder/mrbuilder/blob/master/plugins/plugin-prettier/src/prettier.config.js, and turns out you mean Prettier's configuration file, not API. Which makes this a duplicate of https://github.com/prettier/prettier/issues/4708.

**Comment by thorn0** [comment] 2020-06-04 20:01
Duplicate of #4708

**Closed by thorn0** 2020-06-04 20:00 UTC
Labels: area:api, area:ignore, type:enhancement
