### ISSUE TITLE
Offer an option for YAML indent option

### ISSUE THREAD

**Issue by myermian** [prettier/prettier#9355] opened 2020-10-08 18:35 UTC
I came across issue #4723 wherein the community decided on the indentation style for yaml mappings. It seems that the community voted to indent sequences, which is how the tool currently works. I recently started implementing prettier in my repositories, but this is causing a problem.

Microsoft's documentation examples are all based on "do not indent".

Example: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script#use-parameters-in-pipelines

```yml
parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - vs2017-win2016
  - ubuntu-latest
  - ubuntu-16.04
  - macOS-latest
  - macOS-10.14

trigger: none

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}
```

<hr>

I'm now stuck with a dilemma. Do I keep prettier "as-is", which will format all of my yml files, as well as yml code blocks in my markdown files or do I utilize prettierignore to ignore the Azure Pipeline yml files, and any markdown files related to Azure Pipelines?

One of my repositories houses over 100 yml files (Azure Pipeline YAML templates), as well as markdown files which document and give examples of those pipeline files. On top of that, I have a lot of repositories that contain an `azure-pipelines.yml` and `azurepipelines-coverage.yml` file.

I realize that Prettier is _very opionionated about code formatting_, but is this a possible option that can be added?

**Comment by lydell** [comment] 2020-10-08 20:15
Hi!

This is Wikipedia’s definition of “dilemma”:

> A dilemma is a problem offering two possibilities, neither of which is unambiguously acceptable or preferable.

I can see that you have two possibilities – to format or not to format, that is the question – but you didn’t mention the pros and cons of each choice? To me it sounds like you’re into the concept of having automatic formatting, so running Prettier on all those files is the clear winner. Without more details it’s hard for us to give any advice. What exactly is the problem you have?

**Comment by myermian** [comment] 2020-10-08 22:34
Well, leaving aside if I used the word 'dilemma' properly, I will say that yes, I see two options:

- Use prettier as-is, which will reformat all of my YAML pipeline files, as well as all of my markdown files which contain YML code blocks. I would gain other auto-formatting rules that come with prettier.
- Set up my prettierignore file to ignore YAML pipeline (*.yml) and markdown files (*.md), keeping YAML sequence indentation in tact. If I go onto Azure DevOps and generate a YAML file the files are generated this way. This would keep my YAML pipeline files consistent across those environments, but I lose other formatting options since prettier is no longer applied.

My ultimate preference it the best of both worlds... to use prettier, but to have an option for YAML sequence indentation rules.

**Comment by lydell** [comment] 2020-10-09 06:16
I don’t see how the indent option is going to help you? You’ll still have cases where Prettier changes the generated yaml files because of other little formatting differences.

**Comment by myermian** [comment] 2020-10-09 11:36
> I don’t see how the indent option is going to help you? You’ll still have cases where Prettier changes the generated yaml files because of other little formatting differences.

I thought my examples were clear, so I'm not sure what else to add to them.

**Comment by lydell** [comment] 2020-10-09 13:04
Ok. Since the [option philosophy](https://prettier.io/docs/en/option-philosophy.html) states that the bar for new options is very high, I’ll close this then if we don’t have a super clear reason for it.

**Closed by lydell** 2020-10-09 13:04 UTC

**Comment by LEI** [comment] 2020-11-17 08:20
Stumbled up this after enabling YAML linting, is it possible to implement a `consistent` indentation mode for sequences like in [yamllint](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.indentation) for example?

**Comment by lydell** [comment] 2020-11-17 10:29
@LEI Our advice is to turn off all conflicting rules in linters (see https://prettier.io/docs/en/integrating-with-linters.html – doesn’t mention YAML but it applies there too), rather than Prettier endlessly chasing compatibility: Why spend CPU time linting something that Prettier handles anyway?

**Comment by LEI** [comment] 2020-11-17 12:57
I am confused about what should be turned off while using Prettier via ESLint like in the configuration below, where the [yml plugin](https://www.npmjs.com/package/eslint-plugin-yml) mainly provides the parser and has no block sequence identation rule:

```
extends:
- plugin:yml/recommended
- plugin:prettier/recommended
rules:
  prettier/prettier:
  - warn
  - tabWidth: 2
```

I was wondering [where to look](https://github.com/prettier/prettier/tree/master/src/language-yaml) to alter this behavior and if it is possible to consider a change at all? Thanks for your time!

**Comment by lydell** [comment] 2020-11-17 14:36
@LEI These seem to be the rules of that plugin: https://ota-meshi.github.io/eslint-plugin-yml/rules/

**Comment by LEI** [comment] 2020-11-17 15:32
@lydell Thanks for the answer, but the plugin rule `yml/indent` is not included in the recommended configuration.

Enabling it (here as a warning) doesn't affect the Prettier rule at all:

```
  extends:
  - plugin:yml/recommended
  - plugin:prettier/recommended
  rules:
    yml/indent: warn
```

```
   2:1  error    Insert `··`                                          prettier/prettier
   2:1  warning  Expected indentation of 2 spaces but found 0 spaces  yml/indent
```

**Comment by LEI** [comment] 2020-11-17 19:16
The `yml` plugin is not reporting errors caused by Prettier, I am trying to customize or disable the `prettier/prettier` rule instead of changing of  YAML code style. I will try to understand how it works or I will find another way, thank you.

**Comment by lydell** [comment] 2020-11-17 20:15
I see, I must have misunderstood you. It’s not possible to what you’re trying to do, other than by switching to https://github.com/prettier/prettier-eslint.
