### ISSUE TITLE
Noooooo my .git is dead! / Ignore dotfiles?

### ISSUE THREAD

**Issue by testerez** [prettier/prettier#2882] opened 2017-09-23 06:25 UTC
I was just trying prettier to see the result on my codebase. I should have been more cautious but I scrapped my `.git` directory. All my local branches are probably lost forever!

You should consider adding a check to prevent altering any file with `.git` in the path.

😢

**Comment by testerez** [comment] 2017-09-23 06:48
Actually, it seems like it was just my `.git/HEAD` that was scrapped. Fixed it and I can see my branches again 😅 
Still I think that securing `.git` directory would be a good idea.

**Comment by lydell** [comment] 2017-09-23 07:33
I don't understand what happened, and what you're proposing that Prettier should do?

**Comment by testerez** [comment] 2017-09-23 13:11
Ok, here is how to reproduce my issue:

```
mkdir test
cd test
git init
npx prettier --write "**/*"
git status
```
Result: `fatal: Not a git repository (or any of the parent directories): .git`

What I suggest is that prettier ignore any file in a `.git` directory.

**Comment by azz** [comment] 2017-09-23 13:19
What about other version control systems such as mercurial (`.hg/`) and subversion (`.svn/`)? Maybe ignore dot-directories and dotfiles by default?

Alternatively we could remove the default parser and rely entirely on extension or `--parser` option, this way `.git/HEAD` will not match a parser and won't be modified, this might solve a more general case.

But you probably shouldn't be running prettier on a glob without extension(s).

**Comment by lydell** [comment] 2017-09-23 13:23
@testerez Thanks for the steps to reproduce!

For reference, here are the modifications in a fresh git repo:

.git/HEAD
```diff
-ref: refs/heads/master
+ref: refs / heads / master;
```

.git/config:
```diff
-[core]
-	repositoryformatversion = 0
-	filemode = true
-	bare = false
-	logallrefupdates = true
+[core];
+repositoryformatversion = 0;
+filemode = true;
+bare = false;
+logallrefupdates = true;
```

**Comment by testerez** [comment] 2017-09-23 13:28
@azz I tried this command after reading this in the doc: "Prettier automatically infers the parser from the input file path"
You're probably right that I shouldn't have run it that way but I think that it can be pretty common mistake.

Thanks for the diff @lydell

**Comment by lydell** [comment] 2017-09-23 13:31
> Prettier automatically infers the parser from the input file path

Yeah, that could be considered a bit misleading since Prettier falls back to treating everything as JS if it can't infer the type of the file.

**Comment by ikatyang** [comment] 2018-06-17 07:14
This should be fixed by #4528.

**Closed by ikatyang** 2018-06-17 07:14 UTC
Labels: status:needs discussion
