### ISSUE TITLE
prettier-1.11.1.tgz is being published on npm

### ISSUE THREAD

**Issue by ankurk91** [prettier/prettier#4209] opened 2018-03-27 05:18 UTC
Hi,

You can check that a **.tgz** file is also being published on npm
see
https://unpkg.com/prettier@1.11.1/

Here is how to keep unwanted files out of package
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by lydell** [comment] 2018-03-27 05:46
Thanks! We're already aware of this issue: #4179

(tgz is a pretty unique search keyword here)

**Comment by lydell** [comment] 2018-03-27 05:46
Duplicate of #4179

**Closed by lydell** 2018-03-27 05:46 UTC
