### ISSUE TITLE
Proposal: Pretty format multiple css values in row align.

### ISSUE THREAD

**Issue by twoco** [prettier/prettier#8462] opened 2020-05-31 22:06 UTC
**Prettier 2.0.5**

Format multiple values of a css attribute in clean aligned rows.

**Input:**

```css
.some-class {
  box-shadow: 
    0 0 10px 0 black, 
    0 0 0 1px white,
    0 5px 20px -5px rgba(0, 0, 0, 0.3);
}
```

(Also expected.)

**Output:**

```css
.some-class {
  box-shadow: 0 0 10px 0 black, 0 0 0 1px white,
    0 5px 20px -5px rgba(0, 0, 0, 0.3);
}
```

**Expected behavior:**

```css
.some-class {
  box-shadow: 
    0 0 10px 0 black, 
    0 0 0 1px white,
    0 5px 20px -5px rgba(0, 0, 0, 0.3);
}
```

(scss)

**Comment by thorn0** [comment] 2020-05-31 22:26
Duplicate of #6024

**Comment by thorn0** [comment] 2020-05-31 22:26
Related: https://github.com/prettier/prettier/issues/7039

**Closed by thorn0** 2020-05-31 22:26 UTC
