### ISSUE TITLE
How to add space within interpolation expressions?

### ISSUE THREAD

**Issue by SilencerWeb** [prettier/prettier#4232] opened 2018-03-31 01:14 UTC
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAQgVxjaACaAYQBsBLMAawF5gBDMGU6ACgHIwzK4ATVgSgC+APgAicAGa1MxGKgD0WHNCEgANCAgAHRtADOyULQBORiAHcACsYT6UtYmdoBPfetq6YyScV1x1AIyN6CjgYAGVNelIoAHNkGCNMPxBuCDAve191aN8jGAsgmIBbWgyfZIArXQAPdCCucNoiuAAZaLgyrI1sTWwAJk7kyKNc5BBxYnM1EE0jaJgAdVJuGAALZAAOAAZ1WYhfBaDNMdm4XIA3DvUjOABHTFIbgtpi0qRvLt8i0njE5N1ojFiHAAIqYCDwX5JdQwWj+JYrdZIPowoKkMixQgQIolMb2YjTTC+AAqcNsHzgAgEQA)

**Options:**
```sh
{
  "printWidth": 100,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "all",
  "bracketSpacing": true,
  "arrowParens": "always",
  "parser": "flow"
}
```

**Input:**
```jsx
<Button onClick={action('clicked')}>Default</Button>
```

**Output:**
```jsx
<Button onClick={action('clicked')}>Default</Button>
```

**Expected behavior:**
```jsx
<Button onClick={ action('clicked') }>Default</Button>
```

**Comment by lydell** [comment] 2018-04-02 09:26
Hi! This question has been answered here: #1871

**Comment by lydell** [comment] 2018-04-02 09:26
Duplicate of #1871

**Closed by lydell** 2018-04-02 09:26 UTC
