### ISSUE TITLE
The single quotes configuration is used but does not take effect in the script tag

### ISSUE THREAD

**Issue by WangWinston** [prettier/prettier#14074] opened 2022-12-28 13:28 UTC
**Prettier 2.8.1**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote=true
```

**Input:**

```vue
<script lang="ts">
const str = "hello world"
</script>
```

**Output:**

```vue
<script lang="ts">
const str = 'hello world'
</script>
```

**Expected behavior:**
```vue
<script lang='ts'>
const str = 'hello world'
</script>
```

**Comment by fisker** [comment] 2022-12-28 13:33
Duplicate of  #5828

**Closed** 2022-12-28 13:33 UTC
Labels: type:duplicate
