### ISSUE TITLE
Hello everyone , I use prettier with create-react-app ,when I save it ....it auto add {" "}  ... How to config cancel {" "}

### ISSUE THREAD

**Issue by luandevpro** [prettier/prettier#5036] opened 2018-08-31 10:56 UTC
```jsx
class App extends Component {
	render() {
		console.log(this.props.data);
		return (
			<AutoSizer>
				{" "}
				{({ width, height }) => {
					return (
						<div>
							{" "}
							{width} - {height}{" "}
						</div>
					);
				}}{" "}
			</AutoSizer>
		);
	}
}
```

**Comment by lydell** [comment] 2018-08-31 11:00
Duplicate of #5035.

Feel free to add a comment if something is unclear!

**Closed by lydell** 2018-08-31 11:00 UTC
