### ISSUE TITLE
Export internal plugins printers

### ISSUE THREAD

**Issue by hosseinmd** [prettier/prettier#10259] opened 2021-02-05 10:51 UTC
Related: https://github.com/hosseinmd/prettier-plugin-jsdoc/issues/58

we need to override print functions

**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: >=2.2
- Runtime: Node.js v14
- Operating System:  macOS

**Steps to reproduce:**

**Expected behavior:**

export printers like parsers

**Actual behavior:**

**Comment by thorn0** [comment] 2021-02-05 11:15
See https://github.com/prettier/prettier/issues/8195
Is that what you are looking for?

**Comment by hosseinmd** [comment] 2021-02-05 11:50
Yes, but this question https://github.com/prettier/prettier/issues/8195#issuecomment-623174473 should be answered.

Is it right way?
Is there any other way to do that?

**Comment by thorn0** [comment] 2021-02-05 12:01
Which question? I answered that comment.

**Comment by fisker** [comment] 2021-02-05 12:02
I was looking for the right way too, when I wrote plugin.

**Comment by fisker** [comment] 2021-02-05 12:03
So, it's the right way.

**Comment by thorn0** [comment] 2021-02-05 12:49
All the plugins including internal ones are accessible via `options.plugins`. Parsers live in separate modules because of code splitting, not because it's a special API for overriding them. It's better to access parsers via `options.plugins` too because otherwise if multiple plugins override the same parser, there will be a conflict.

> So, it's the right way.

As long as we consider monkeypatching a right thing to do.

**Comment by thorn0** [comment] 2021-02-05 13:03
Closing in favor of #4424 (an issue where a non-monkeypatching API for extending printers is discussed).

**Closed by thorn0** 2021-02-05 13:03 UTC

**Comment by hosseinmd** [comment] 2021-02-07 19:08
I have a custom printer like this

```js
const estree2: Printer = {
  // @ts-ignore
  preprocess(ast, options) {
    const jsPlugin = options.plugins.find(
      (plugin: any) =>
        plugin.printers &&
        plugin.printers.estree,
    ) as prettier.Plugin;

    const estree = jsPlugin.printers?.estree;

    Object.assign(estree2, {
      ...estree,
      // @ts-ignore
      preprocess: estree2.preprocess,
    });

    console.log({ estree2 });

    // @ts-ignore
    return estree.preprocess(ast, options);
  },
};
```
Not work.

**Comment by hosseinmd** [comment] 2021-02-07 19:09
prettier retuning undefined

**Comment by thorn0** [comment] 2021-02-07 20:16
Just checked, and it works for me. What I did:

**test-plugin.js**
```js
const ast = {
  type: "Program",
  body: [
    {
      type: "ExpressionStatement",
      expression: { type: "Identifier", name: "a" },
    },
  ],
};

const estree2 = {
  preprocess(ast, options) {
    const estree = options.plugins.find(
      (plugin) => plugin.printers && plugin.printers.estree
    ).printers.estree;

    Object.assign(estree2, { ...estree, preprocess: estree2.preprocess });

    // console.log({ estree2 });

    return estree.preprocess(ast, options);
  },
};

module.exports = {
  parsers: { foo: { parse: () => ast, astFormat: "estree2" } },
  printers: { estree2 },
};
```

```console
$ dprettier test.js --parser foo --plugin test-plugin.js
a;
```


You're doing something differently.

**Comment by hosseinmd** [comment] 2021-02-07 21:15
I tested your code doesn't print anything.

**Comment by hosseinmd** [comment] 2021-02-07 21:16
this is my printer:
```js
const parsers = {
  // JS - Babel
  get babel() {
    const parser = parserBabel.parsers.babel;
    return { ...parser, astFormat: "estree2", parse: getParser(parser.parse) };
  },
}
```

**Comment by thorn0** [comment] 2021-02-07 21:21
Are you saying that if you do these steps, Prettier terminates with no output?
* create an empty folder
* `yarn add prettier` in that folder
* create `test-plugin.js` in that folder, with the content from https://github.com/prettier/prettier/issues/10259#issuecomment-774753194
* run `prettier test-plugin.js.js --parser foo --plugin test-plugin.js`

Just tested it again on both Windows and Linux using the exact steps above. Prints `a;` for me.

**Comment by hosseinmd** [comment] 2021-02-07 21:31
Maybe that is because project, could you test this in [prettier-plugin-jsdoc](https://github.com/hosseinmd/prettier-plugin-jsdoc)

**Comment by thorn0** [comment] 2021-02-07 21:36
I'm not sure what exactly you're asking me to do. What are the steps?

**Comment by hosseinmd** [comment] 2021-02-07 21:43
Please get a clone, run yarn then yarn test.
In index.ts file you could add your printer, I tested code there but not work.

**Comment by thorn0** [comment] 2021-02-07 21:48
What exactly did you do in `index.ts`?

**Comment by hosseinmd** [comment] 2021-02-07 21:55
on index.ts we was overrided js parsers with cusstom parser

**Comment by hosseinmd** [comment] 2021-02-07 21:56
Now we need to override printers too.

**Comment by thorn0** [comment] 2021-02-07 21:59
Sorry, you make me guess too much. I might be able to help you if you write three things: exact reproducible steps, actual behavior, expected behavior.

For example:

> Please get a clone, run yarn then yarn test.

👍 These are good reproducible steps.

> In index.ts file you could add your printer,

👎 This is not a reproducible step.

> I tested code there but not work.

👎 This is a bad description for actual behavior / expected behavior. How exactly you tested it? What it printed? What did you expect it to print?

**Comment by thorn0** [comment] 2021-02-07 23:09
Okay, I think you might like this. See the code below.

💀⚠ **Disclaimer:** this is only a hack, not a proper use of the public API. It can be broken by any release of Prettier and should only be used for experiments. The Prettier team doesn't recommend doing this. Plugins that do this will be removed from the "community plugins" section of the docs.

```ts
  babel: {
    astFormat: "estree",
    preprocess(this: any, text: string, options: any) {
      const originalParser = options.plugins.find(
        (plugin: any) => plugin.parsers?.babel,
      ).parsers.babel;

      this.preprocess = undefined;
      Object.assign(this, originalParser);
      options.locStart = this.locStart;
      options.locEnd = this.locEnd;

      this.parse = getParser(this.parse);

      const originalPrinter = options.plugins.find(
        (plugin: any) => plugin.printers?.estree,
      ).printers.estree;

      const originalEmbed = originalPrinter.embed;
      originalPrinter.embed = (
        path: FastPath,
        print: (path: FastPath) => Doc,
        textToDoc: (text: string, options: any) => Doc,
        options: any,
      ) => {
        const node = path.getValue();
        if (node.type === "VariableDeclaration") {
          return "// oops, this statement was deleted";
        }
        return originalEmbed?.(path, print, textToDoc, options);
      };
      
      return this.preprocess?.(text, options) ?? text;
    },
  },
```
