### ISSUE TITLE
Please change newline rule for Promises or introduce option to respect them

### ISSUE THREAD

**Issue by thardy** [prettier/prettier#9627] opened 2020-11-09 18:39 UTC
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflG-58MIRxNADooOAB3ADEaAFsAZSd7HDA4YOYOACFDU2jqGIARQxhDBlyYgBUATwAHVMjbACULAH1CBoBBN18-fGCAhAYGACNsuDLNDx4APk9unp6AoODyQzosnNjNYdHxtwBubzn5-DYYdGoofAAFaggYoNS2TQgSRwYodDJ9o-cjvpEoIMnp8YJMZl5Lj1+DBIFBnrplhBmAwFAArGz6Qz+OCaGAKb6Q6HuA6EyGLEJhKKxBLUJIpNKZHaxQrFUqxKq1YL1JqtDpdSF+f4DbYbPITXjgo7zcmI1brMabEUKsUEqU9U7nS43O4PYJPF5vD5fEnzYmHUneFwgcQgCDVXDQTTIUCGai3cJXV0IJ0oYzhQyVJ02obUQxgADWHDi1TDOC4yBg1HQZhAcBiQzgdDomYAMoYuOhDOkykVOMxkCBDOgYBBrcIYDESBRAvBNDGUgk4ThcEkYJUK2BNEGQHHTNQYDcizFDMgjCYU6jNAAPDKhiNRwwxOA5uNwWfGUw2xdLuJx5i6ACK6Ag8H385tMeoY4rIwzJDr1WocZgFBwdACyAABwAAwPrcpgUKG1QVp+OKJHuNoAI7XvA2rVD6laaAAtGEmaZnWbDITgbCTsw053oeICmPcCZJim2hcJeKF7kgc6UcUQy-v+QjIAATDaiaGDoZ4AMJ3ORKA4gArHWNhwOUhhDD6bEpvYyYAJJQNmsBxGAX72u0WlxH2ugUXALguEAA)
```sh
--parser babel
```

**Input:**
```jsx
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  this.newFormService.getBaseFormData(FormType.FORM_HRA)
    .then((baseForms) => {
        this.loadBaseForms(baseForms);

        return Promise.resolve(null);
    })
    .then((result) => {
    	console.log('just a test');
  	});
  
  this.newFormService.getBaseFormData(FormType.FORM_HRA)
    .then((baseForms) => {
        this.loadBaseForms(baseForms);

        return Promise.resolve(null);
    });

  

}
```
* location of "then" is consistent in location and appearance (always), which enhances discoverability and readability

**Output:**
```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver,
}) {
  this.newFormService
    .getBaseFormData(FormType.FORM_HRA)
    .then((baseForms) => {
      this.loadBaseForms(baseForms);

      return Promise.resolve(null);
    })
    .then((result) => {
      console.log("just a test");
    });

  this.newFormService.getBaseFormData(FormType.FORM_HRA).then((baseForms) => {
    this.loadBaseForms(baseForms);

    return Promise.resolve(null);
  });
}

```
* location of "then" changes based on random factors (like line length or whether there is a second then) - decreases discoverability and requires more interpretation from viewer

**Expected behavior:**
I expect an improvement in discoverability and readability, not a reduction in both.  Code location and appearance directly affects speed of recognition in the viewer.  For the exact same reason it's important for a UX to use consistent patterns of placement, color, and location, it's important for code not to "move around" based on scenario.  Changing locations for the exact same mechanisms creates cognitive friction.  Less lines does NOT always equal greater discoverability.

I think you guys are getting lost trying to make this newline thing work as a universal rule.  Forget a universal newline rule.  I'm not complaining about all the other newline scenarios, just Promises.  If need be, make this a custom rule for Promises only - only applicable to promises and then, catch, etc.  The code in the input is more readable than the code in the ouput - isn't that all that matters?  If you don't agree, then let's put it to a vote or create an option for it because I think the current "opinion" is wrong in the specific case of Promises and newlines.

**Comment by thorn0** [comment] 2020-11-09 21:29
Duplicate of #5931

**Closed by thorn0** 2020-11-09 21:29 UTC
