### ISSUE TITLE
prettier-ignore works only for a single line

### ISSUE THREAD

**Issue by aderchox** [prettier/prettier#14958] opened 2023-06-20 13:22 UTC
(I tried searching the existing issues first, but I couldn't find anything in the first few pages of the results.)

I'd like to recommend making `// prettier-ignore-start` and `// prettier-ignore-end` work for non-markdown files too. Currently this is the escape hatch:
```ts
// prettier-ignore
{
    // put-the-code-here
}
```
However, the code will have to be OK with the block scope added.
There's also a [question](https://stackoverflow.com/q/66259151/9868445) about this on Stackoverflow with already more than 60 upvotes.

**Comment by kachkaev** [comment] 2023-06-26 16:54
👋 @aderchox! I guess that this issue is a duplicate of https://github.com/prettier/prettier/issues/5287 – feel free too submit a PR or contribute to the discussion.

**Closed as not planned by kachkaev** 2023-06-26 16:54 UTC
Labels: type:duplicate, locked-due-to-inactivity
