### ISSUE TITLE
Keeps long lines with TS 'as' typing formating

### ISSUE THREAD

**Issue by whitecolor** [prettier/prettier#8822] opened 2020-07-23 18:52 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKcAeAHCAnGAAkigGciAbCAQwBMBhASxkblIBlqoBzAOWoC2bACLUY1QgF5CAdzwBrAHRU6TFm049+Q0qPGFqpQjACe2OBABmhAcpoNmrDlz6CRY6iAA0ICNhbQpMig1Hh4EDIACqEIQSjUFDLUJkE+AEZ41GDycDAAythZjDzIMHgArnA+ABYwAhQA6tXMbIVgcHmxjgBuzCbI4KSpIMWkcASRmdwCnkiWCWM+AFakmABCmdm5eW7sxXDI8xSLICuYecXcFHAAiuUQ8IcLVSCFeGN4A6bmpGB4jP5vK9-rAGoxaDBqsgABwABh82HCYwamWwA0RbHG3QOPgAjvd4JM-HEQIYALQYOC0KlAvBwfGMOmTajTWZHE5jASMUoVF6kS7XO4PA5zZ4+cRpMEQqFIABM4syjAol3oEAEMwGbAArEDymMACrUNJxdkvbqVACSUGpsDyfwBMAAgta8qZrk9jnAAL5eoA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```ts
export const loadCitiesLangNamesData = wrk.loadCitiesLangNamesData as typeof m.loadCitiesLangNamesData
```

**Output:**

```ts
export const loadCitiesLangNamesData = wrk.loadCitiesLangNamesData as typeof m.loadCitiesLangNamesData
```

**Expected behavior:**

Should make lines not longer then 80

**Comment by thorn0** [comment] 2020-07-23 18:57
Duplicate of #6443

**Closed by thorn0** 2020-07-23 18:57 UTC
