### ISSUE TITLE
JSON: Don't put values on a separate line from the key

### ISSUE THREAD

**Issue by revelt** [prettier/prettier#4211] opened 2018-03-27 12:13 UTC
> Prettier v1.11.1

As you know, `package.json` by default is processed by both `prettier` and `npm`. The difference in how both treat the **keys with long values** currently leads to limbo states.

To recreate, create an empty library and `npm init`. In `package.json` put a long line:

```json
"scripts": {
    "test": "echo \"very very very very very very very very very very very very very very very very very very very very very long line\" && exit 1"
  },
```

Run prettier - it will break `"test"` and its long value **into two separate lines**.
Now install another library - npm will put `"test"` key and its value **back onto one line**.

## One more argument against this key/value breaking into separate rows

Virtually all JSON-writing [libraries](https://github.com/sindresorhus/write-json-file) will put keys and their values on the same line, irrespectively of value's length. This means, any custom JSON processing tools will behave the same. Which means, they will _always_ introduce inconsistencies with current `prettier` output and any workflows using them will require `prettier` to be ran again to maintain the line separation.

All this hassle is not worth the benefit, and I'd argue putting long values on new rows don't improve the legibility anyway - from my experience, 90% of the long values extend beyond code editor's max-line length marker even _after being put onto new line_.

## Proposed solution

We should stop breaking long key/value pairs into two lines when processing `package.json`.

**Comment by evilebottnawi** [comment] 2018-03-27 12:18
I think we should ignore `package.json` and `package-lock.json` by default, because npm change `package.json` when you run commands which change `package.json`.

**Comment by revelt** [comment] 2018-03-27 12:19
exactly

**Comment by ikatyang** [comment] 2018-03-27 12:21
I guess this one should be a duplicate of #3671.

**Comment by revelt** [comment] 2018-03-27 12:28
I can't find the exact location in the codebase, but where we process JSON there should be a conditional check is it `package.json` before applying the key splitting during value length checks.

**Comment by lipis** [comment] 2018-03-27 14:27
This is not a duplicate.. `package.json` here serves as an example and the idea is to not split the key/values in general in `*.json` files.

**Comment by suchipi** [comment] 2018-03-27 16:32
I agree with @lipis, we shouldn't ever do this for JSON.

**Comment by MisterAJ** [comment] 2018-07-16 16:54
This is a troublesome issue for me.

**Comment by hawkrives** [comment] 2018-07-16 20:23
@MisterAJ As of recent prettier versions, this should be fixed, for package.json at least.

**Comment by MisterAJ** [comment] 2018-07-16 22:16
It's not doing it the package.json, but it is doing it everywhere else.

**Closed** 2018-07-17 21:09 UTC
Labels: lang:json, status:has pr
