### ISSUE TITLE
Glimmer / Handlebars formatter does not insert EOF newline

### ISSUE THREAD

**Issue by MichalBryxi** [prettier/prettier#13542] opened 2022-09-27 13:41 UTC
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UABMcMDhAObEEjpw6V0C+LRpqA9JrniABoQEAA4wAltADOyUAEMATgogB3AAqKEMlHJwq5ATxlCARgrlgA1nBgBlOVjgAZcVDjIAZrqlxT5qza2IhauVMgwCgCuviBwWCZwACaJSU5yUFSRclRwAGIQClhyMBIZyCBykTAQgvTYOADq6OLwUsFgcLZaLeIAbi0G5WBSxiCuPgowauZURZ7eMQBWUgAetqE4cACKkRDw8zg+QsEKE+VUOOJYjgq1IgquMA3iiTDoyAAcAAzHyj4N5hE5XucAmvXcQgAjrt4NNRNoKlIALRuJJJWoKODQ8SY6bZOZILyHGI+LDicJREkbbYw9yEhZCGByEzPV7vJAAJkZ5nElwyAGEINc5OVQQBWWqRHwAFWZ2iJRxAvWiAEkoClYLYwA8xABBdW2GAGTYHHxsIA)

```sh
--parser glimmer
```

**Input:**

```hbs
<html>
  {{log "hello"}}
  </html>
```

**Output:**

```hbs
<html>
  {{log "hello"}}
</html>
```

**Expected behavior:**
```hbs
<html>
  {{log "hello"}}
</html>

```

- Notice the EOF newline.
- As per [rationale](https://prettier.io/docs/en/rationale.html) document:
> Empty lines at the start and end of blocks (and whole files) are removed. (Files **always end with a single newline**, though.)

This issue seems to be specific for the **glimmer** parser. Randomly checking in **babel** and **json5** I can get the EOF newline correctly:

![Screenshot 2022-09-27 at 15 32 40](https://user-images.githubusercontent.com/847473/192542771-1644c46d-26ac-4a5b-9132-ac4d9169dc36.png)

**Comment by thorn0** [comment] 2022-09-27 14:20
Duplicate of #10420

**Closed** 2022-09-27 14:20 UTC
Labels: type:duplicate
