### ISSUE TITLE
<object> tag with typescript parser causes error

### ISSUE THREAD

**Issue by charlescook** [prettier/prettier#2115] opened 2017-06-12 18:14 UTC
This code is ok with the babylon parser but fails with 'Error: unknown type: "Keyword"' with the typescript parser:

```
class MyComponent extends React.Component {
  render() {
    return (
<object data="test.pdf" type="application/pdf" />
    );
  }
}
```

**Comment by k15a** [comment] 2017-06-12 18:49
I think this is a duplicate of https://github.com/prettier/prettier/issues/2049 and thus fixed on master.

**Closed** 2017-06-12 18:49 UTC
