### ISSUE TITLE
ternary operator > lambda > ternary fails to parse himself after formatting

### ISSUE THREAD

**Issue by deddu** [prettier/prettier#2194] opened 2017-06-19 14:17 UTC
The following nested ternary
```js
let icecream = what == "cone"
  ? p => !!p ? `here's your ${p} cone` : `just the empty cone for you`
  : p => `here's your ${p} ${what}`;
```

gets formatted to 

```js
let icecream = what == "cone"
  ? p => (!!p ? `here's your ${p} cone` : `just the empty cone for you`)
  : p => `here's your ${p} ${what}`;

```

which consequently fails a subsequent parsing with
` SyntaxError: Invalid left-hand side in arrow function parameters (2:11)`;

(using prettier 1.44)

**Comment by hawkrives** [comment] 2017-06-19 14:42
[online reproduction](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20round%201%5Cnlet%20icecream%20%3D%20what%20%3D%3D%20%5C%22cone%5C%22%5Cn%20%20%3F%20p%20%3D%3E%20!!p%20%3F%20%60here's%20your%20%24%7Bp%7D%20cone%60%20%3A%20%60just%20the%20empty%20cone%20for%20you%60%5Cn%20%20%3A%20p%20%3D%3E%20%60here's%20your%20%24%7Bp%7D%20%24%7Bwhat%7D%60%3B%5Cn%5Cn%2F%2F%20round%202%5Cnlet%20icecream%20%3D%20what%20%3D%3D%20%5C%22cone%5C%22%5Cn%20%20%3F%20p%20%3D%3E%20(!!p%20%3F%20%60here's%20your%20%24%7Bp%7D%20cone%60%20%3A%20%60just%20the%20empty%20cone%20for%20you%60)%5Cn%20%20%3A%20p%20%3D%3E%20%60here's%20your%20%24%7Bp%7D%20%24%7Bwhat%7D%60%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

Thanks for reporting, @deddu!

**Comment by vjeux** [comment] 2017-06-19 16:25
@k15a fyi, if prettier generates a piece of code that doesn't parse or produces an output with a different meaning, this should be flagged as high pri. It should not happen, ever :)

**Comment by vjeux** [comment] 2017-06-19 16:27
This looks like an issue with babylon, flow parser handles it fine. cc @hzoo

**Comment by hzoo** [comment] 2017-06-19 16:47
Looks related to issues regarding https://github.com/babel/babylon/issues/58

**Comment by vjeux** [comment] 2017-06-19 16:51
@hzoo looks like it indeed, and there's already a PR for it! You are on fire :)

**Comment by josephfrazier** [comment] 2017-07-05 21:31
This was fixed in https://github.com/babel/babylon/commit/a9a55fbd3fcb0dcd83758549dfd2c4fa3d0dcaa2, but then reverted in https://github.com/babel/babylon/commit/88298536c5a407d81359df97428d656b43ee3c46. https://github.com/babel/babylon/pull/596 has the next iteration of the fix.

**Comment by nicolo-ribaudo** [comment] 2017-10-01 20:09
That pr was released in babylon v.7.0.0-beta.27!

**Comment by lydell** [comment] 2017-10-01 20:25
@nicolo-ribaudo Thanks for the heads-up? Would you be interested in making a PR bumping the babylon version and adding a test case? :)

**Comment by nicolo-ribaudo** [comment] 2017-10-02 04:55
Sure, I can do that this evening (CET)

**Comment by existentialism** [comment] 2017-10-02 13:58
I have a PR ready for this, but the latest Babylon version can't be bumped in Prettier b/c we split the TS/Flow types. I have an update ready for this but waiting for an upstream change in `typescript-eslint-parser` to land.

**Closed** 2017-10-15 22:09 UTC
Labels: lang:javascript, priority:high, scope:dependency, type:bug
