### ISSUE TITLE
es6 import/export Do not wrap

### ISSUE THREAD

**Issue by vnpp** [prettier/prettier#13055] opened 2022-06-28 20:01 UTC
hi prettier

I don't want to break the imported element

```
import {
  ChangeDetectorRef,
  Component,
  ContentChild,
  ElementRef,
  EventEmitter,
  HostBinding,
  Input,
  OnInit,
  Optional,
  Output,
  Self,
  ViewChild,
} from '@angular/core';
```
Because I don't need to care about import
I can use import optimize

I wish to provide a configuration, become like this

```import { ChangeDetectorRef, Component, ContentChild, ElementRef, EventEmitter, HostBinding, Input, OnInit, Optional, Output, Self, ViewChild, } from '@angular/core';```

thank you very much

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#.....)

the webstorm configuration, would conflict with it
![image](https://user-images.githubusercontent.com/88667017/176274037-77ca313d-4021-4e9f-8b70-b30ee22b8f60.png)

**Comment by alexander-akait** [comment] 2022-07-01 03:51
Duplicate of https://github.com/prettier/prettier/issues/5995

**Closed by alexander-akait** 2022-07-01 03:51 UTC
