### ISSUE TITLE
Prettier removes desired parentheses.

### ISSUE THREAD

**Issue by mjf-acqyrexchange** [prettier/prettier#10165] opened 2021-01-27 22:39 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT746oP58BmfAHp8AFnwsA1PgCsk-AEMScajD5sQADx2bJAbg4BfEABoQEAA65oAZ2ShF1ahADuABScJ7KZa8UAnvbmAEbUimAA1nAwAMqWEThQAObIMNTocOZwALYhcHR0BQAyiinoislwAGI0OYowuCnIIIroMBBmIAAWMDkkFN048LYJYHCx3sM4AG7DAS1gtsEgSbaqMO7hyfXIqMrr5gBWtloAQuFRMbGKOXDFSXB7B1kgJ1qxSckqAIroEPBniRDiAEtR1tQWiFFPkSF1LNQkjAKDg6DBusgABwABnMCIg6wo4UsLQRcAhMye5gAjv94FsrD5WrYALRQOAFApdahwWk4HlbSq7JD7YGvdY5HBpDLir6-OlPEUvcwwGEotEYpAAJhV4RwJC+AGEIDlhSBybIuuh1gAVGE+UUgmaZACSUCKsFiYER1gAgu7YjAAiogesjEYgA)
```sh
--parser babel
```

**Input:**
```jsx
function HelloWorld() {
  if( ( 3 / 4 ) + 5 ) alert( "xxx" );
}
```

**Output:**
```jsx
function HelloWorld() {
  if (3 / 4 + 5) alert("xxx");
}

```

**Expected behavior:**
```jsx
function HelloWorld() {
   if ( ( 3 / 4 ) + 5 ) alert( "xxx" );
}
```
I realize inner parens (surrounding the "3 / 4") aren't necessary, but some coding stds require them. Is there an option for this?

Thanks. Great extension, btw.

**Comment by thorn0** [comment] 2021-01-27 23:03
Duplicate of #187

**Comment by thorn0** [comment] 2021-01-27 23:04
There is an open PR that tries to fix this: https://github.com/prettier/prettier/pull/9026

**Closed** 2021-01-27 23:03 UTC
Labels: type:duplicate
