### ISSUE TITLE
Blank line should not be removed before semicolon

### ISSUE THREAD

**Issue by jaydenseric** [prettier/prettier#4194] opened 2018-03-23 03:52 UTC
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEAzCEA6UhA3ANr4gBGAhgE4UC6AdLrQKLVgAWAFAJbwAtpgC8APkyQoAZwjomqCAHN+QgJRrCIADQgIABxh9o05KDq0IAdwAKdBKZTUAbhD4ATHSGrSYybNSo0nC6lLScANYYAMr6nHxQSsgwtACuISDuEGD+gcG6CcG0MDbhSoLUuUEZAFbSAB4AQuFgUTDR1IJwADIJcFX5eqkw+sMATAMZcbRFyFTUlACeilBe+rQJMADqHjBcyAAcAAy66xDBW+H6c+twRc79urRwAI6pfM+l1OWVSAHVumCgj4k0BCSU6AAiqkIPBQSAYAsdu49sgxroUtQ+KhwQBhCCCCpzKDQR4gVLBAAqC0c-2CAF96UA)
```sh
--no-semi
```

**Input:**
```jsx
let foo

;["bar"].forEach(item => console.log(item))

```

**Output:**
```jsx
let foo
;["bar"].forEach(item => console.log(item))

```

**Expected behavior:**
```jsx
let foo

;["bar"].forEach(item => console.log(item))

```

**Comment by lydell** [comment] 2018-03-23 06:15
Good catch! This looks like a duplicate of #1510, though.

**Comment by lydell** [comment] 2018-03-23 06:15
Duplicate of #1510

**Closed by lydell** 2018-03-23 06:15 UTC
