### ISSUE TITLE
When useTabs is enabled, some expressions using ternary operators indented aggresively

### ISSUE THREAD

**Issue by dustinsoftware** [prettier/prettier#3270] opened 2017-11-15 01:20 UTC
This doesn't seem to be as big of an issue when `useTabs` is disabled. Unsure if this is by design or a bug.

**Prettier 1.8.2 with useTabs**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAkrBATOPDAQwwBsBLGGMuDGCCDAM2ICcB+AHSkigGcY9ABYUoAcwwBeDHzxUK0HlxgcMAbQC6ymEg08Mho4eAZocPQDc4bAJ5l24uAFEAHgAc2cfv0VQMANQkUBAwwjYAMo4uHl4+fhgAvgA0BsZGpjAA7hBWNvbRbp7evtCBwaHhbFFsTkVxpf4paekYmcJeFhjWdg61McXxZUHEIWGRhbElCc3+RpoA3MpQ6BgAssQA1t4YALYQXhj8CMcYAEZwYMQArqfjXgDk-MEYcFNDUDx8giJikjJyBRKT6qDTaEF6UgAHyh+hBKhUpnMeV6k0GjXKo0qE369WmZVmCJgiPoORRBVx7wxIzGVRqdSpM1S8OJMHanXJfQZ6ISNOx1TRDSZOhUi2WqwAUrchOMSGw2MRbF9oD8wn8AEzSOEk5HdfJcgZC4YVe70w34prMknZXJ61GUnnGrGmwUWpJWtkiDl2inco3+Pkuh3+908RYgZIgCDuGB+fjIUDEQTIVhkY6Rs4KsDbGAAZXcxDAf2QMDY1zgkbwEDAKeIaYrIDExzYMAACgrxLtiLX65GAFb8VwAISzOdzxF2cAiYjgPfTUeuMHci-Vc4bBbYzeQIDOxDO9mgEZAnjEMAA6hQ8GFkAAOAAMkc8EGOZ4V7hLZYbXgAjtcKF522ITtuyQVN52OXYKA-ctI18CRaAARWuUJZ1Aut5xgPcLyvYRkHVSNS2IChKAkABhCBdi7bc6zII9bjgAAVPd4yQUty0SRIgA)
```sh
--trailing-comma all
--use-tabs
```

**Input:**
```jsx
const thing = condition
	? []
	: [
		{ one: verylargeExpression + anotherLargeExpression },
		{ two: verylargeExpression + anotherLargeExpression },
		{ three: verylargeExpression + anotherLargeExpression },
	];

const thing2 = [
	{ one: verylargeExpression + anotherLargeExpression },
	{ two: verylargeExpression + anotherLargeExpression },
	{ three: verylargeExpression + anotherLargeExpression },
];
```

**Output:**
```jsx
// Intended a little too far?
const thing = condition
	? []
	: [
			{ one: verylargeExpression + anotherLargeExpression },
			{ two: verylargeExpression + anotherLargeExpression },
			{ three: verylargeExpression + anotherLargeExpression },
		];

// Seems fine
const thing2 = [
	{ one: verylargeExpression + anotherLargeExpression },
	{ two: verylargeExpression + anotherLargeExpression },
	{ three: verylargeExpression + anotherLargeExpression },
];

```

**Expected behavior:**
The indentation is not as drastic (see input)

**Comment by ikatyang** [comment] 2017-11-15 12:31
Looks like a duplicate of #2771, closing in favor of that.

**Closed by ikatyang** 2017-11-15 12:31 UTC
