### ISSUE TITLE
Long interpolated strings are not split into multiple lines.

### ISSUE THREAD

**Issue by avalanche1** [prettier/prettier#7099] opened 2019-12-05 11:00 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzArgG3wGUALCAdxgEMBzAQQAUBJXAJ30wF5MADAEmBVWNNADpSFavWZt8AXwFCRogCZVqAYXVwaEVgE85AekXCxDVhBqsqAWw0QVcOTwDcIADQgIABxgBLdGRQIUtyBiEENGQQKgA3CH8VTxAAIxswAGs4GCIfKjB-KBpkGFZcOC8SGFt8AHUSf3g0fLA4Iiim-zim-RiwNGivIrQ4VhgLWlsqZGwqfFGvACs0AA8AIQzs3Ls4ABkiuFn5xZAV1aIimnw4AEVcCHhjhcqQfNZR1hjUqlS4fBSPlYRRgdSSMBIyAAHAAGLxAiCjOo2HwxIFwT5xI5eACOD3gFl80RQVDQAFooHA4E5kl5WHA8f56ZMaNNnqdRrZ-KVyq80FcbvdHkckHMXl5qKkwSoIcgAEwSmz+fBXBy2NkoKDQbEgXCjAAqv2JYtOcQqTCgTlgRDAwL8dEtRBg+hu7OcciAA)
```sh
--parser babel
```

**Input:**
```jsx
const fullShowtagAPIurl = `${args.ShowtagAPIurl}${args.dataCategory}/${args.ProgramCode}`;
```

**Output:**
```jsx
const fullShowtagAPIurl = `${args.ShowtagAPIurl}${args.dataCategory}/${args.ProgramCode}`;

```

**Expected behavior:**
Long interpolated strings to be split into multiple lines.
Also, it could produce smth like:
```jsx
const fullShowtagAPIurl = 
  `${args.ShowtagAPIurl}${args.dataCategory}/${args.ProgramCode}`;
```
Although I'd prefer a solution with string-splitting.

**Comment by thorn0** [comment] 2020-11-10 11:22
Duplicate of #5994

**Closed by thorn0** 2020-11-10 11:22 UTC
Labels: area:template literals, lang:javascript, status:needs discussion
