### ISSUE TITLE
Inline comments after opening brace are wrapped to the next line

### ISSUE THREAD

**Issue by SteveMellross** [prettier/prettier#7213] opened 2020-01-02 05:19 UTC
This is mainly frustrating when trying to add short comments to nested properties of an object/type. It works fine for leaf properties, but gets wrapped for ones with an opening brace. This results in either either inconsistent comments, or having to add all comments on the line above, reducing the effective vertical space (which I find much more precious than horizontal space).

I also run into this occasionally on `if` statements.

Note: I don't add comments to every line like this in my code. This is just to illustrate the inconsistency. 😅

**Prettier 1.19.1** (default options)
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTYAHSk0wEMlMBGAGkwHoHMBhCAW3YS3ICMIArjxJleVYI2ZtO3CvyGZeIspjBVqk1hy6w5grEtKYAviWMBuEiQCWAM0wAKGACcBcAJSFN0nT3lZIKAATaxhraGVnOBgBZ1IAVnNvbVk+fUx4s0w4ABs0OC8mLRldNIVc-Mjo2NIANiSin1T-TFqzEhBaEAgABzD0ZFByZ2cIAHcABWGENGQQcgA3CGsgzpBeZ3IwAGtogGUeresoAHNkFzcugAsYdhyAdSvQuDRDsDg9mdDrBdCATzmYDQsy6x3yzhgE02J3Y5GQtnIeTgXQAVmhsAAhTY7fbkLgAGWOcHhiPyqPRe2OJxycAAigIIPASUiuodnOC5rw+Lk1j1nMcYPcVjArsgABwABlZo3y902PTmfJecGcC2JXQAjgz4FDerMUOQ0ABaKBwOBBc1rKJa6xRKHkGFwpAIlkgfLsaznVzIt1Umn0xnE52kn0wPhCoIi5AAJi6LnI1hyVJ8TpAUGg6pAAnyABU+PqXWSQAs3ABJYLcPZgfl9ACCwT2MD+NOZ+WMxiAA)

**Input:**
```jsx
const x = {
  a: 1, // Comment about a
  b: { // Comment about b
    c: 1 // Comment about b
  }
};

if (true) { // Comment about condition
  return 5; // Comment about 5
} else { // Comment about else
  return 6; // Comment about 6
}
```

**Output:**
```jsx
const x = {
  a: 1, // Comment about a
  b: {
    // Comment about b
    c: 1 // Comment about b
  }
};

if (true) {
  // Comment about condition
  return 5; // Comment about 5
} else {
  // Comment about else
  return 6; // Comment about 6
}
```

**Expected behavior:**
The comments after `{` should not be moved to the next line.

**Comment by thorn0** [comment] 2020-01-08 16:02
Duplicate of #7155

**Closed by thorn0** 2020-01-08 16:02 UTC
