### ISSUE TITLE
Line-splitting

### ISSUE THREAD

**Issue by houshuang** [prettier/prettier#1044] opened 2017-03-19 12:19 UTC
In my previous code (formatted with 0.18.0) I had

```
 ActivityData.update({ _id: id, type: 'list', activityId, groupId }, {
   $set: { value }
 });
```

with 0.22.0, this gets changed to:

```
ActivityData.update(
  { _id: id, type: "list", activityId, groupId },
  {
    $set: { value }
  }
);
```

which seems unnecessarily verbose. It would be better to do:

```
ActivityData.update(
  { _id: id, type: "list", activityId, groupId },
  { $set: { value } }
);
```

and indeed, if I manually change it to this, Prettier leaves it alone - so I guess it interprets my code in the first example as me wanting to explicitly split the object.

Interestingly, version 0.0.8, embedded in the original blog post, takes the expanded version (example 2 above) and turns it into the compact (example 3 above).

It's not a big issue, given that by manually changing the code, Prettier keeps it compact, but I had to do a bit of manual clean-up upon upgrading Prettier version to keep my code looking nice.

**Comment by vjeux** [comment] 2017-03-19 19:11
Yeah, this is unfortunate. One of the biggest cause of this is the fact that we are still iterating on the printer so we make you go through different ways of formatting which impact the object rule. We're trying to get to a stable version of prettier as soon as possible so this will stop being an issue in the future.

**Comment by jlongster** [comment] 2017-03-20 16:45
@vjeux The core reason here is because we keep objects expanded if they were originally expanded. It causes a lot of these little surprising behaviors. We're telling the user the prettier will take care of all the formatting but also forcing them to think about newlines in objects so it feels inconsistent.

I know most people think it's worth it, but we should probably talk about this behavior explicitly in the rationale document so we can point people to it.

I think we should close this issue because this is by design, unfortunately. I doubt we'll remove the behavior that keeps objects expanded if they were originally expanded, so it's a tradeoff we made.

**Closed by jlongster** 2017-03-20 16:45 UTC
Labels: Needs discussion
