### ISSUE TITLE
An empty line followed by a line prefixed with semicolon is not preserved

### ISSUE THREAD

**Issue by dplusic** [prettier/prettier#4511] opened 2018-05-19 15:49 UTC
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTARgB0pSBuACkoEp8A+TYAXxttJABoQIAHGAJbpkobACcxEAO4AFcQjTIQ2AG4QBAEy4gARmOxgA1nBgBlXgYFQA5shhiArnG5W0cMTBn7rAW2zIAM2wAGzduACs0AA8AIX0jE1NsHzgAGSs4QJCwkAsxNzElHWwdAE9g6G1eMSsYAHVNGAALZAAOAAZuaog3Ov1eJWq4ApVM7jE4AEcHAQmvbF9-JCDQ5xA3HwEs1e40K2tguABFBwh4bZyYEoaNZuQAJm57bAFg-YBhCB8-JShoMZADjcABUSopltk4MxmEA)
```sh
--no-semi
```

**Input:**
```jsx
const a = 1

;(() => {})()

```

**Output:**
```jsx
const a = 1
;(() => {})()

```

**Expected behavior:**
The empty line should be preserved like this:
```jsx
const a = 1

;(() => {})()

```

**Comment by ikatyang** [comment] 2018-05-19 15:50
Hi, this is a duplicate of #1510, see https://github.com/prettier/prettier/issues/1510#issuecomment-299496344 for more info.

**Comment by ikatyang** [comment] 2018-05-19 15:51
Duplicate of #1510

**Closed by ikatyang** 2018-05-19 15:50 UTC
