### ISSUE TITLE
1.7.0 breaks styled components using react-native

### ISSUE THREAD

**Issue by iRoachie** [prettier/prettier#2897] opened 2017-09-25 21:49 UTC
New version of prettier breaks styled components in react native. 

In react-native mixed cased in styled is the default way to write property names. e.g. `marginBottom`. Using prettier now produces code that is wrong.

**Prettier 1.7.0**

**Input:**
```jsx
const Header = styled.View`
  backgroundColor: ${Theme.toolbar};
  padding: 16px;
  paddingTop: 0;
`
```

**Output:**
```jsx
const Header = styled.View`
  backgroundcolor: ${Theme.toolbar};
  padding: 16px;
  paddingtop: 0;
`
```

**Expected behavior:**
Code should not be affected.

**Comment by suchipi** [comment] 2017-09-25 21:51
Possibly a dupe of https://github.com/prettier/prettier/issues/2850, not sure if styled components treats React Native differently

**Comment by iRoachie** [comment] 2017-09-25 22:19
I'm not sure if it does, `maxWidth` isn't valid css, but it's valid property for the style object in react native.

**Comment by lydell** [comment] 2017-09-26 05:14
@iRoachie In #2850 we learned (from the creator of styled-components!) that v1 of styled-components _accidentally_ allowed writing property names in camel-case.

> In react-native mixed cased in styled is the default way to write property names.

I've used neither react-native nor styled-components. Can you link to docs explaining this?

**Comment by iRoachie** [comment] 2017-09-26 11:50
@lydell I’ve been using v2 of styled components. I’m just wondering if there’s a way to turn off the lowercasing functionality.

In react native styles are defined through the Stylesheet object. https://facebook.github.io/react-native/docs/style.html

**Comment by hawkrives** [comment] 2017-09-26 12:29
@iRoachie I believe that styled-components uses https://github.com/styled-components/css-to-react-native to handle react native, which would mean that it still expects you to write normal, hyphenated, CSS properties.

**Comment by iRoachie** [comment] 2017-09-26 12:53
What i’m trying to say is that camel case properties in styled components are working as expected in react native even down to latest release of styled-components. The properties are just passed directly to the underlying style object. 

The issue I have with prettier lowercasing everything. This is a specialized behavior of prettier, and so should be able to toggle it on or off by a flag. I don’t mind making a PR for a flag to enable or disable the feature.

**Comment by lydell** [comment] 2017-09-26 13:33
@mxstbr Can you help with the confusion here?

- What is the recommended way to write styled-components CSS for react native?
- Are camel-cased property names intentionally supported in the latest version of styled-components for react native?

**Comment by mxstbr** [comment] 2017-09-26 13:41
More or less a simplified version of what styled-components (specifically the [`css-to-react-native`](http://github.com/styled-components/css-to-react-native) package) does for ReactNative is this:

```JS
// Take this CSS string...
const Styled.View`
  border-color: blue;
`

// ...and turn it into an object to be passed to StyleSheet.create
StyleSheet.create({
  borderColor: blue,
})
```

As you can see, we also camelCase all dash-cased properties since that's what ReactNative expects. Now, we don't have a list of all valid or invalid properties or something like that, we just take whatever the user passes us and we convert it to an object.

This means when you write an invalid property, we also pass it through:

```JS
// Take this CSS string...
const Styled.View`
  complete-bullshit: blue;
`

// ...and turn it into an object to be passed to StyleSheet.create
StyleSheet.create({
  completeBullshit: blue,
}) 
```

As you can see, this is what leads to this behavior of camelCase working in ReactNative. Since we just take whatever the user gives us and convert it to an object camelCase also "works":

```JS
// Take this CSS string...
const Styled.View`
  borderColor: blue;
`

// ...and turn it into an object to be passed to StyleSheet.create
StyleSheet.create({
  borderColor: blue,
}) 
```

This is not because we want people to use it that way though, necessarily. I'm open to discussing about deprecating this by checking for camelCased properties and not passing them through, but that feels slightly weird because why do camelCased properties have a special case/behavior? :confused:

I'm unsure what the right way to go here is, but this should hopefully shed some light on why this works. /cc @jacobp100 @philpl @geelen

**Comment by iRoachie** [comment] 2017-09-26 15:01
Ahh thanks for the explanation @mxstbr. I am definitely leaning on the side of specialized behaviour for camelCase, especially in react-native. Styled components provides an easy upgrade path for css.

```js
// How css is defined 
div.content {
  background-color: pink;
}

// Styled component with exact syntax
const Content = styled.div`
  background-color: pink;
`
```

I don't see why the experience can't be the same for react native.

```js
// How style is defined in react native
const styles = Stylesheet.create({
  content: {
    backgroundColor: 'pink'
  }
})

// Styled component but syntax has to change??
const Content = styled.View`
  background-color: pink
`
```

**Comment by philpl** [comment] 2017-09-26 18:21
@mxstbr We definitely don’t want to allow this explicitly for parity. It is difficult for prettier to start adding rules based on what specific, unsupported thing everyone is doing, since it only wants to cater for a specific way of writing things :wink:

So as far as camel cases SC goes, try not to use it! It’s from our side unsupported but does work due to how we transform styles. Since it’s unsupported t might break in the future :)

**Comment by iRoachie** [comment] 2017-09-26 18:45
@philpl It's not catering for a specific way of writing things. Camel case **is the default way to write styles in react native**

It's like asking everyone that writes css to start using camel case for everything. However, I doubt you'd see it as "catering for a specific way of writing" then.

Similar library glamorous, react native styles as normal camelCase. https://github.com/robinpowered/glamorous-native

**Comment by lydell** [comment] 2017-09-26 19:11
@iRoachie If there was a codemod that could automatically convert all your camelCase properties into dash case, would you still feel so strongly about it?

**Comment by mxstbr** [comment] 2017-09-26 19:14
> Similar library glamorous, react native styles as normal camelCase. 

The important difference being: you write styles with objects, not strings, so you don't have any options. :wink:

**Comment by iRoachie** [comment] 2017-09-26 19:21
As I said previously it's not really about my particular use case (I've already manually changed mine over). Not sure why this gets so much lash back. The same great experience for someone moving from css to styled-components should be experienced by someone moving from Stylesheet.create to styled-components.

**Comment by lydell** [comment] 2017-09-26 19:24
@iRoachie Writing a pretty-printer is hard. We just want to make sure the problems fully before jumping into implementation to avoid accidental complexity :)

**Comment by iRoachie** [comment] 2017-09-26 19:28
@lydell outside of the complexity of it, does the point I'm making sound reasonable to you?

**Comment by lydell** [comment] 2017-09-26 19:32
I don't know.

**Comment by duailibe** [comment] 2017-09-26 19:41
> The same great experience for someone moving from css to styled-components should be experienced by someone moving from Stylesheet.create to styled-components.

Yeah I can see the point but we need to understand that in one case they're both strings (CSS or styled-components) and the other you're changing an object to a string. They're fundamentally different which makes it difficult to reason about how it should pretty print.

**Comment by suchipi** [comment] 2017-09-26 20:14
I'm going to close this based on @philpl and @mxstbr's comments:

>So as far as camel cases SC goes, try not to use it! It’s from our side unsupported but does work due to how we transform styles. Since it’s unsupported t might break in the future :) - @philpl 

>This is not because we want people to use it that way though, necessarily. I'm open to discussing about deprecating this by checking for camelCased properties and not passing them through, but that feels slightly weird because why do camelCased properties have a special case/behavior? 😕 - @mxstbr 

Styled components expects a css string, and prettier is treating it like a css string. Support for camelcased properties in css string in styled components was unintentional.

**Closed by suchipi** 2017-09-26 20:14 UTC
Labels: CSS, Needs discussion, Needs More Information

**Comment by smooJitter** [comment] 2017-10-21 15:45
I really just don't understand why this is so difficult to understand.  We just want Prettier to stop changing my camelCase String literals. That's that.  @iRoachie, how did you change yours over.

**Comment by iRoachie** [comment] 2017-10-21 16:07
@smooJitter Ha, I’ve fought battles here and on the styled-components repo. Some things you have to give in. The majority of users are react web not react native, so it’s streamlined for it and css. I just did a global search and replace for the property names and changed them over.
