### ISSUE TITLE
Dependency issue with remark-parse and remark-math

### ISSUE THREAD

**Issue by rainbowtux** [prettier/prettier#9601] opened 2020-11-04 17:46 UTC
When installing prettier as pre-commit hook, I get a dependency error with remark-parse and remark-math. See message below and eresolve-report.txt attached. If you need any more information to reproduce the error, please let me know.

My operating system: openSUSE TW, but issue also happened on a colleague's laptop running Manjaro.

An unexpected error has occurred: CalledProcessError: command: ('/home/evdvelde/.cache/pre-commit/repos5bkvdni/node_env-default/bin/node', '/home/evdvelde/.cache/pre-commit/repos5bkvdni/node_env-default/bin/npm', 'install')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR! 
    npm ERR! While resolving: prettier@2.1.2
    npm ERR! Found: remark-parse@8.0.3
    npm ERR! node_modules/remark-parse
    npm ERR!   remark-parse@"8.0.3" from the root project
    npm ERR! 
    npm ERR! Could not resolve dependency:
    npm ERR! peer remark-parse@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0" from remark-math@1.0.6
    npm ERR! node_modules/remark-math
    npm ERR!   remark-math@"1.0.6" from the root project
    npm ERR! 
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --force, or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
    npm ERR! 
    npm ERR! See /home/evdvelde/.npm/eresolve-report.txt for a full report.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/evdvelde/.npm/_logs/2020-11-04T17_24_20_993Z-debug.log

[eresolve-report.txt](https://github.com/prettier/prettier/files/5489584/eresolve-report.txt)

**Comment by thorn0** [comment] 2020-11-05 01:14
Duplicate of #9459

**Closed by thorn0** 2020-11-05 01:14 UTC
