### ISSUE TITLE
formatting does not work if it ends with a function call

### ISSUE THREAD

**Issue by nilsbuehrer** [prettier/prettier#7961] opened 2020-04-06 10:19 UTC
**Prettier 2.0.3**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "bracketSpacing": false,
  "singleQuote": true,
  "trailingComma": "es5"
```

**Input:**

```jsx
// works as expected
something.veeeeeery.looooooooooooooooooooooooooong = some.other.rather.long.chain;

// does not work if it ends with a function call
something.veeeeeery.looooooooooooooooooooooooooong = some.other.rather.long.chain.functionCall();
```

**Output:**

```jsx
// works as expected
something.veeeeeery.looooooooooooooooooooooooooong =
  some.other.rather.long.chain;

// does not work if it ends with a function call
something.veeeeeery.looooooooooooooooooooooooooong = some.other.rather.long.chain.functionCall();
```

**Expected behavior:**
```jsx
// should break after '=' and before function call.
something.veeeeeery.looooooooooooooooooooooooooong =
  some.other.rather.long.chain.functionCall();
```

**Comment by thorn0** [comment] 2020-04-06 10:36
Probably a duplicate of https://github.com/prettier/prettier/issues/2482

**Closed** 2021-02-16 19:25 UTC
Labels: area:member chains, lang:javascript, type:bug
