### ISSUE TITLE
Error printing comment "::"

### ISSUE THREAD

**Issue by sgrove** [prettier/prettier#7748] opened 2020-03-10 19:30 UTC
Reporting this as requested:

```
src/components/CourseEditor.bs.js[error] src/components/CourseEditor.bs.js: Error: Comment "::" was not printed. Please report this error!
[error]     at /Users/s/.fnm/node-versions/v13.6.0/installation/lib/node_modules/prettier/bin-prettier.js:13229:13
[error]     at Array.forEach (<anonymous>)
[error]     at ensureAllCommentsPrinted (/Users/s/.fnm/node-versions/v13.6.0/installation/lib/node_modules/prettier/bin-prettier.js:13227:15)
[error]     at coreFormat (/Users/s/.fnm/node-versions/v13.6.0/installation/lib/node_modules/prettier/bin-prettier.js:13276:3)
[error]     at format (/Users/s/.fnm/node-versions/v13.6.0/installation/lib/node_modules/prettier/bin-prettier.js:13516:73)
[error]     at formatWithCursor (/Users/s/.fnm/node-versions/v13.6.0/installation/lib/node_modules/prettier/bin-prettier.js:13532:12)
[error]     at Object.formatWithCursor (/Users/s/.fnm/node-versions/v13.6.0/installation/lib/node_modules/prettier/bin-prettier.js:44213:15)
[error]     at format$1 (/Users/s/.fnm/node-versions/v13.6.0/installation/lib/node_modules/prettier/bin-prettier.js:45598:19)
[error]     at /Users/s/.fnm/node-versions/v13.6.0/installation/lib/node_modules/prettier/bin-prettier.js:45792:16
[error]     at /Users/s/.fnm/node-versions/v13.6.0/installation/lib/node_modules/prettier/bin-prettier.js:45731:14
s:egghead-static>
```

It failed while trying to format this JS file: https://gist.github.com/sgrove/c3228faad2801079b189e818bf18c57b

**Comment by j-f1** [comment] 2020-03-10 20:07
Minimal reproduction:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPAFAegFQAIlK7aYDaAugJQDcIANCBAA4wCW0AzsqAIYBOvEAO4AFPgk4puANwgsAJnRAAjXtzABrODADKjNSygBzZDF4BXOPQAWMALYAbAOpWW8dnrBxt41yymuAT2Rwdk56A3Y4XhhhVUNbbmQAM257SPoAK3ZUACFVDS1tbls4ABkDOGTU9JAs1G0DQ3s4AEUzCHgqtMsQPV5I3mClbiU4e0VGXgMYR3kYK2QADgAGekmISMdVRmDJuAGpSvoAR3b4WKYJEG52AFooODg5J8VeOFOWN9jueMSkFO69EithYJnMPXYjWabQ6lX+1R6MBGszk82QACZ6KZuCx7I0AMIQWwJYJQaBHEBmSIAFRGEgBNSkFgAklBnrBtGApswAIJs7QwALNLqRAC+oqAA)
```sh
--parser babel
```

**Input:**
```jsx
x(/* :: */[]);
```

In the meantime, there should be no issues if you use the `typescript` parser instead of the `babel`.

**Comment by thorn0** [comment] 2020-05-12 14:20
Duplicate of #6102

**Closed by thorn0** 2020-05-12 14:20 UTC
Labels: area:comments, area:flow comment types, lang:javascript, type:bug
