### ISSUE TITLE
Strip extra whitespace when formatting style/script blocks in Vue SFC

### ISSUE THREAD

**Issue by DanielHeckrath** [prettier/prettier#3750] opened 2018-01-16 10:31 UTC
Currently any extra whitespace between attributes in style and script blocks is preserved. In my opinion those attributes should be formatted the same way as for example attributes on JSX elements.

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wAExxANgIZQDmAvADogzoMB8qA9JrgS3VHxhgBPUnD4kJhCtXohM6ZiGLiJAWwgATAK6i+fXlAkA6PIWCFV5LFRxQAtDAh4khAEwAGPAA8A3AF8BTmFRFhAAGhAnGBxodGRQKywIAHcABSsEOJRyADcIHA1wkHJ0GGQAM3JSdDgIgCMscjAAazgYAGU8JtsqZBgsLVqQDQgwCqqaiNsarBhUxqpLceqhgCt0LwAhRpa29vJVOAAZWzhlycitGDwr13OhrqwZ5BAcwaK8XFgAdQKYAAtkAAOdwRT4QGrfRp4F6fOAzHJnCJYOAARy0OBR83Ii3I9wiNVUOD6AyG6B6ogAiloIPB8YxyHVfhoAchXBF+uQcKQegBhCCqJYoKDQJEgLQ1AAqjKylRWfj8QA)
```sh
--parser vue
```

**Input:**
```vue
<script     lang="ts"></script>

<style
        lang="scss"  
     module

>
    .p { margin-top: 20px;}
</style>
```

**Output:**
```vue
<script     lang="ts">
</script>

<style
        lang="scss"  
     module

>
.p {
  margin-top: 20px;
}
</style>

```

**Expected behavior:**
```vue
<script lang="ts">
</script>

<style lang="scss" module>
.p {
    margin-top: 20px;
}
</style>
```

**Comment by j-f1** [comment] 2018-01-16 11:13
We’re currently working on an HTML printer, but we haven’t finished yet, so we currently just format the contents of `<script>` and `<style>` tags in Vue component files.

Duplicate of #1882.

**Closed by j-f1** 2018-01-16 11:13 UTC

**Comment by j-f1** [comment] 2018-01-16 11:16
Duplicate of #1882.
