### ISSUE TITLE
Object destructuring is unexpectedly broken into multiple lines

### ISSUE THREAD

**Issue by simoneb** [prettier/prettier#6922] opened 2019-11-11 10:10 UTC
**Prettier 1.19.1**

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAExMBMCGM+ANJhoQK5qYC+mAvJvgO74CWWATnAI4VwYAdLjgAbOPAAUAHSiZMAAwD0+MJAqwlAEmCr1sAJK4aS3BDAUAtghhptwGAE8ADnBM6zF67AByVgEZwnDQKxLLyOABu+KJsBPAAykQwVEiYkgCUDAB8mDCc-LSyGQDcIMQgEM4wbOjIoPicnBDMAAqNCGjIIPiREHHlIP6cqgDWEgnOqmxQAObI+fwVABYwlqIA6sscAlNgcAmdHGyRHI7dYGhdFTNoQTCtI7OW+MgAZjF3FQBWaAAeACERmBxjAEvhrAAZGZwd6fOA-f4JGazcQARQoEHgcNEXxAU04d043X8+ECokGzk4MxgGziMGWyAAHAAGCpUiB3DYjZzdKkCIKRWEVPhYuCPKpdFD4NAAWigcDgIlwg24fDY3Ee+GeryQH1xCJAd0sbAWBUNaBR6Mx2L18IqRH8dNwDOQACYHSM2LE5gBhCCWF7dGIUipUOAAFTJUv1eMi-AMUBEsASYGp1QAgkmko5xDi7jQaEA)

```json
{
  "trailingComma": "es5"
}
```

**Input:**
```js
      const { data, status } = await request.delete(
        `/account/${accountId}/documents/${type}/${documentNumber}`,
        { validateStatus: () => true }
      );
```

**Output:**
```js
      const {
        data,
        status,
      } = await request.delete(
        `/account/${accountId}/documents/${type}/${documentNumber}`,
        { validateStatus: () => true }
      );
```

**Expected behavior:**

In 1.18.2, the code was unchanged, which is what I would expect

**Comment by glen-84** [comment] 2020-10-22 16:53
Duplicate of #5939 (?).

**Comment by thorn0** [comment] 2020-10-22 18:00
Not a duplicate, that issue is about improving the heuristic for formatting nested destructuring (I'll update the title there to make it more clear). This one is a bug, most probably related to #2482.

**Comment by seiyab** [comment] 2023-11-23 08:00
Current version looks to work file.
https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAExMBMCGM+ANJhoQK5qYC+mAvJvgO74CWWATnAI4VwYAdLjgAbOPAAUAHSiZMAAwD0+MJAqwlAEmCr1sAJK4aS3BDAUAtghhptwGAE8ADnBM6zF67AByVgEZwnDQKxLLyOABu+KJsBPAAykQwVEiYkgCUDAB8mDCc-LSyGQDcIMQgEM4wbOjIoPicnBDMAAqNCGjIIPiREHHlIP6cqgDWEgnOqmxQAObI+fwVABYwlqIA6sscAlNgcAmdHGyRHI7dYGhdFTNoQTCtI7OW+MgAZjF3FQBWaAAeACERmBxjAEvhrAAZGZwd6fOA-f4JGazcQARQoEHgcNEXxAU04d043X8+ECokGzk4MxgGziMGWyAAHAAGCpUiB3DYjZzdKkCIKRWEVPhYuCPKpdFD4NAAWigcDgIlwg24fDY3Ee+GeryQH1xCJAd0sbAWBUNaBR6Mx2L18IqRH8dNwDOQACYHSM2LE5gBhCCWF7dGIUipUOAAFTJUv1eMi-AMUBEsASYGp1QAgkmko5xDi7jQaEA

**Closed** 2023-11-23 14:09 UTC
Labels: type:bug, lang:javascript, area:destructuring
