### ISSUE TITLE
styled-components properties casing

### ISSUE THREAD

**Issue by iddan** [prettier/prettier#3527] opened 2017-12-19 13:59 UTC
**Prettier 1.9.2**
```json
// Options
{
    "printWidth": 80,
    "tabWidth": 4,
    "useTabs": false,
    "semi": false,
    "singleQuote": true,
    "trailingComma": "all",
    "bracketSpacing": true,
    "jsxBracketSameLine": false
}
```

**Input:**
```jsx
export const Separator = styled.View`
    height: 1px;
    margin-horizontal: 21px;
    backgroundColor: #dadada;
`
```

**Output:**
```jsx
export const Separator = styled.View`
    height: 1px;
    margin-horizontal: 21px;
    backgroundcolor: #dadada;
`
```

**Expected behavior:**
To keep casing of property

**Comment by ikatyang** [comment] 2017-12-19 14:10
Duplicate of #2850 or #2897, see https://github.com/prettier/prettier/issues/2850#issuecomment-330256538 from `styled-components` team:

> we just (for some reason I can't recall) supported camelCase pre v2, though it was never documented and more of an **unintended sideeffect** of some of our hacky code. (which is gone with v2)

**Closed by ikatyang** 2017-12-19 14:10 UTC

**Comment by iddan** [comment] 2017-12-19 15:11
Thank you, The thing is it still works and my team made mistakes and now to fix them is complicated. Are you aware of a linting rule or command that I can find all these syntax errors?

**Comment by ikatyang** [comment] 2017-12-19 15:25
I guess you could modify this line to [dashify](https://www.npmjs.com/package/dashify) the prop.

https://github.com/prettier/prettier/blob/8b8268096fe43ac889ab69bce6320bc6f87ebbd3/src/printer-postcss.js#L84
