### ISSUE TITLE
Unnecessary braces around await when using `as` type cast in TypeScript

### ISSUE THREAD

**Issue by borekb** [prettier/prettier#6339] opened 2019-07-29 13:29 UTC
**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaXAEzgFsIAKASl2AB0pddUB3VUmAnBhgAFvUIAnADbMMuAMoQacACqYADnADc7AL4gANCAjqy0dMlCoJEiNwAK1hBZSoAbhFKVDIAEYTUMABrIXl1QNIoAHNkGAlCOCMRGBopAHURfjh0cLA4eWd+Ujd+TGRwdAsjSPQ4CRh7AKiaVGR8VClaowArdAAPACEA4NDUZQAZSLg2jq6QXr75SKipOABFQgh4Gc7EkHCJWolymA1ssAlSUx91S9g0rxgRZAAOAAYjW4hatID1ctu2TqbmmRgAjpt4I0TC40OgALRQOBwajeIwSOAQ0gYxqoZqtJDtXZGWo0UixeJ7dDLVYbLbTQmzPYwVC+B6UJ7IABMRjifCkywAwkoWuUoNBQSBCLUVKyXETarpdEA)
```sh
--parser typescript
```

**Input:**
```tsx
async function demo() {
  await fetch(url) as SomeType;
}
```

**Output:**
```tsx
async function demo() {
  (await fetch(url)) as SomeType;
}

```

**Expected behavior:**

The braces are not necessary. The input is easier to read and correct.

**Related:**

#3089 feels quite similar.

**Comment by bakkot** [comment] 2019-08-01 18:20
I find the output much easier to read, personally.

**Comment by thorn0** [comment] 2020-03-03 14:58
Duplicate of #3089

**Closed by thorn0** 2020-03-03 14:58 UTC
Labels: lang:typescript
