### ISSUE TITLE
ESLint inline comments should not be moved to the next line

### ISSUE THREAD

**Issue by pronebird** [prettier/prettier#4613] opened 2018-05-31 12:46 UTC
For instance:

```
declare class ClipboardData { // eslint-disable-line no-unused-vars
  setData(type: string, data: string): void;
  getData(type: string): string;
}
```

becomes this:

```
declare class ClipboardData {
  // eslint-disable-line no-unused-vars
  setData(type: string, data: string): void;
  getData(type: string): string;
}
```

which breaks ESLint and now it reports an error.

Workaround is to use `// eslint-disable-next-line` comments instead.

**Comment by azz** [comment] 2018-05-31 12:49
Duplicate of #1267

You should use `// eslint-disable-next-line` instead.

**Closed by azz** 2018-05-31 12:49 UTC

**Comment by j-f1** [comment] 2018-05-31 13:06
Duplicate of #1267
