### ISSUE TITLE
Prettier looks the whole file instead the <script> and <style> tag in SFC Vue file

### ISSUE THREAD

**Issue by le2kbqoahhkv68** [prettier/prettier#9295] opened 2020-09-29 14:16 UTC
**Environments:**

- Prettier Version: 2.0.5
- Running Prettier via: WebStorm
- Runtime: Node 14.11.0
- Operating System: macos

**Steps to reproduce:**

I just use the keyboard shortcut to throw the prettier across the file. Cmd + Opt + Shift + P

.vue file

```
<template>
   ...
</template>

<script lang='ts'>
   ...
</script>

<style lang='scss'>
   ...
</style>

<docs>
## Using the component

### Basic usage

  <MyComponent
    defaultProp="vue"
    objectProp={[
      {label: 'Vue', key: 'vue'},
      {label: 'React', key: 'react'},
    ]
  }>
  </MyComponent>
</docs>
```

**Expected behavior:**

Within a SFC .vue file which includes usual <template>, <script> and <style> blocks, and also a <docs> block used for Docusaurus, I would like to prettify the whole file or just the <script> block EXCLUDING the < docs> block. Why? The docusaurus <docs> documentation is wrote in React and there are some differences with Vue.

**Actual behavior:**

It prettifies the whole file and throw format errors from the <docs> block because React syntax is different than Vue's for example with the properties (React doesn't use quotes).

**Comment by evilebottnawi** [comment] 2020-09-29 15:49
Please use the issue template, otherwise we will close this

**Comment by le2kbqoahhkv68** [comment] 2020-09-29 15:59
> Please use the issue template, otherwise we will close this

Thanks @evilebottnawi. I think that a piece of code, example, is just what I forgot. I copied the issue template thought. Please tell me if it's still something wrong.

**Comment by fisker** [comment] 2020-09-29 16:37
Can you try v2.1 I think the problem is fixed https://prettier.io/blog/2020/08/24/2.1.0.html#improve-parsing-for-custom-blocks-8153httpsgithubcomprettierprettierpull8153-by-sosukesuzukihttpsgithubcomsosukesuzuki

If you v2.1 result is still not what you want, please use [playground](https://prettier.io/playground/) to post the current and expected result.

**Comment by le2kbqoahhkv68** [comment] 2020-09-29 19:11
> Can you try v2.1? I think the problem is fixed https://prettier.io/blog/2020/08/24/2.1.0.html#improve-parsing-for-custom-blocks-8153httpsgithubcomprettierprettierpull8153-by-sosukesuzukihttpsgithubcomsosukesuzuki
> 
> If you think v2.1 result is still not what you want, please use [playground](https://prettier.io/playground/) to post the current and expected result.

Thanks! It looks good.

I just want the opposite. I want to exclude the docs block (custom as you said) to be prettied, because it pretties the whole document. Maybe your solution works. 

Let me try it. Thanks in advance!

**Comment by le2kbqoahhkv68** [comment] 2020-09-30 09:07
Hello,

**thanks** @fisker, updating to 2.1 works ;). I didn't have to set lang for excluded blocks.

**Closed** 2020-09-30 09:07 UTC
