### ISSUE TITLE
MDX inline functions 

### ISSUE THREAD

**Issue by moretti** [prettier/prettier#7107] opened 2019-12-06 14:43 UTC
**Prettier 1.19.1**

The following MDX generates a syntax error:

```.mdx
<Playground>
  {() => {
const A = 1;
const B = 2;

    return (
      <div />
    );
}}
</Playground>
```

```
SyntaxError: Unexpected closing tag "Playground". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:1)
> 1 | <Playground>
    | ^
  2 |   {() => {
  3 | const A = 1;
  4 | const B = 2;
```

([Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeACgGwIYE8DmAThAK5QAmAfADpQAEdwAFAJR0C8ljtkUAzjDoBBDnQCMAbh7QBdAEKiATFKi0GDQnBglC9JmvUNU5AJYA3OgHoa9dSxUBfB7VSWseIqQqUQAGhAQAA4wJjLIoNiExADu6JEIfMgg2GYQJuR+IABGhNhgANZaAMqBeSZQ+MgwhCRw-gAWMAC2mADq9SbwfKVgcEUJneaduElgfIn+5XxwhDDoufhN2MgAZtiY0-4AVnwAHnK5BcXYTXAAMuVwq+ubIDu7ReX4mHAAiiQQ8NcbdSClhNNCEkmuRdplAoRyjBWukYPVkAAOAAM-ghEGmrVygSSELggLMV38AEcPvB5kFEihsHwALRQOBwciMzKaEkmTTzbCLZZINY-fzTJomKo1X58J4vd6fK68m6-GDYLIw8hw5CKfzVbAmTBPADCECaSySUGghJAJGmABVFZS+bczLUAJIUBAwIpgSHBIQUIowXAvb7TJxAA))

---

Adding a space or a tab at line 5 seems to be a temporary workaround:

```
<Playground>
  {() => {
const A = 1;
const B = 2;
 // -> empty line with space here
    return (
      <div />
    );
}}
</Playground>
```

([Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeACgGwIYE8DmAThAK5QAmAfADpQAEdwAFAJR0C8ljtkUAzjDoBBDnQCMAbh7QBdAEKiATFPq0GDQnBglC9JmvUNU5AJYA3OgHoa9dSxUBfB7VSWseIqQqUQAGhAQAA4wJjLIoNiExADu6JEIfMgg2GYQJuR+IABGhNhgANZaAMqBeSZQ+MgwhCRw-gAWMAC2mADq9SbwfKVgcEUJneaduElgfIn+5XxwhDDoufhN2MgAZtiY0-4AVnwAHnK5BcXYTXAAMuVwq+ubIDu7ReX4mHAAiiQQ8NcbdSClhNNCEkmuRdplAoRyjBWukYPVkAAOAAM-ghEGmrVygSSELggLMV38AEcPvB5kFEihsHwALRQOBwciMzKaEkmTTzbCLZZINY-fzTJomKo1X58J4vd6fK68m6-GDYLIw8hw5CKfzVbAmTBPADCECaSySUGghJAJGmABVFZS+bczLUAJIUBAwIpgSHBIQUIowXAvb7TJxAA))

**Comment by thorn0** [comment] 2019-12-07 14:27
Duplicate of #7041

**Closed by thorn0** 2019-12-07 14:27 UTC
