### ISSUE TITLE
JSX exceeds line length when a line has whitespace at the end

### ISSUE THREAD

**Issue by ayush000** [prettier/prettier#7124] opened 2019-12-10 10:50 UTC
Using **Prettier 1.19.1**

JSX exceeds line length. Print width in below example is set as 80 chars

Expected:
```jsx
return (
  <div>
    <div>
      {/* 77 chars */}
      A quick brown fox jumps over the lazy dogs A quick brown fox jumps over
      th{" "} <span />
    </div>
  </div>
);
```

Actual
```jsx
return (
  <div>
    <div>
      {/* 85 chars */}
      A quick brown fox jumps over the lazy dogs A quick brown fox jumps over th{" "}
      <span />
    </div>
  </div>
);

```

**Comment by thorn0** [comment] 2019-12-10 10:59
Can't reproduce. Please use the [Playground](https://prettier.io/playground/) to report issues.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOMCuqoAIAUAOnrgDwAmAlgG4B8xujZVdDTjwA9AFS4DsfXGAAWAQ1QBnXN04BfNuwCCuAI6ZKYANa4ARqggB3PADMIAD1wArTAFsADlIjU4qXDGFxcAG1EAvAJ645BAA5lLKahraeoYm5la2DrhOLgpM7sCEILhZsmQSdqJ4nPQkjKScLKXllTSlAJQA3CAANCAQdjCU0BLIoOL6BgAK4gi9KKLUEJTkrSB6oloYAMqFYJRQIcgwqJhwbcIwNl4A6sKU8AWLcMtjFzQX-sjgEr1tGxIuMEOooiE2omQxlEXk+bUsEjMACFfksYMtRDY4AAZDZwIEgsEgCFmZYbEJeOAARUwEHgGNB+xAhUkLmeOlEOjgXjmdlQGxgJxm7mQAA4AAxtNkQT4nX52Z5suCfVDOOZqMlwH4dcYgUQSAC0UDgcHIurm6Ei6B+fwBFKxnxslG2uypEnxhJJivNVJgjK55B5SAATG0dqJKF58QBhCA2M0oKDQdFtTCfAAqjPGwMpbWoewAklA9bBlmB2Z1FNnljB-ISXbJZEA)
```sh
--parser babel
```

**Input:**
```jsx
return (
  <div>
    <div>
      {/* 77 chars */}
      A quick brown fox jumps over the lazy dogs A quick brown fox jumps over
      th{" "} <span />
    </div>
  </div>
);
```

**Output:**
```jsx
return (
  <div>
    <div>
      {/* 77 chars */}A quick brown fox jumps over the lazy dogs A quick brown
      fox jumps over th <span />
    </div>
  </div>
);

```

**Comment by thorn0** [comment] 2019-12-10 11:03
Duplicate of #2553

**Closed by thorn0** 2019-12-10 11:03 UTC
Labels: lang:jsx, status:awaiting response
