### ISSUE TITLE
SCSS/CSS one liners

### ISSUE THREAD

**Issue by Sensanaty** [prettier/prettier#8649] opened 2020-06-27 22:55 UTC
Is there a way for me to disable this check on my SCSS/CSS?

![image](https://user-images.githubusercontent.com/24919018/85933650-cb831180-b8d9-11ea-8442-9ee97f5c234e.png)

Prettier will reformat this into separate lines, like so:

```css
.letter-l {
    grid-area: letterL;
}

.box-link {
    grid-area: linkL;
}
```

Which in my opinion doesn't look as nice and takes up an unnecessary amount of space and clutters the code quite a bit for simple, one-off declarations

**Comment by evilebottnawi** [comment] 2020-06-29 12:00
No options, duplicate of https://github.com/prettier/prettier/issues/5948 and we don't want to change it

**Closed by evilebottnawi** 2020-06-29 12:00 UTC
