### ISSUE TITLE
Markdown: Link text converted to lower-case

### ISSUE THREAD

**Issue by IvanGoncharov** [prettier/prettier#3835] opened 2018-01-28 20:24 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAjAXVQFTgZxgAI8APGTACgAsYYAHJAeiblIEMBbegGzgDpInAJQgANCAj0YAS2j5kodgCdlEAO4AFFQgUp2ANwgyAJuJDtCyAGbse+OBIBGy9mADWcGAGV6bmVAA5sgwygCujiAmEGA2dg4SAQ7KMJqugZzscfaRAFb4pABCrh5e3lxwADIBcNkJkmEMjQBMdZF+ysnIIJnK7tHqUOb0ygEwAOqmMNTIABwADBIjEA7jrvTdIwRwyga1EspwAI5hModp7BlZSLY5Eg6cMiHhkfgBgXwAimEQ8G0SMHYTkmJmmyGaANcMh47wAwhBOJlulBoPsQGEHDggXpbg4AL54oA)
```sh
--parser markdown
```

**Input:**
```markdown
[1][Test Text](http://example.com)
```

**Output:**
```markdown
[1][test text](http://example.com)

```

**Expected behavior:**
```markdown
[1][Test Text](http://example.com)
```

**Comment by lydell** [comment] 2018-01-28 20:38
Hi! I’m curious, what do those examples even mean? I’ve seen `[link test](href)` and `[link text][ref]` but not the combination of those.

**Comment by IvanGoncharov** [comment] 2018-01-28 21:07
@lydell `[1]` is literal part and the whole sample rendered as:
[1][Test Text](http://example.com)

Real-life use case from here: https://github.com/facebook/graphql/blob/master/rfcs/Subscriptions.md
![image](https://user-images.githubusercontent.com/8336157/35487035-b7a477b4-047f-11e8-98f6-afc78faf136d.png)

**Comment by lydell** [comment] 2018-01-28 21:15
Thanks! As a workaround, I believe you can add a `\` at the beginning: `\[1][Test Text](http://example.com)`.

I _think_ what’s happening is that Prettier thinks that `[1][Test Text]` is the link (where it is valid to lowercase the ref) and that it is followed by some text in parentheses. I don’t know which is correct according to the CommonMark spec, though. Hopefully @ikatyang knows :)

**Comment by IvanGoncharov** [comment] 2018-01-28 21:21
> I don’t know which is correct according to the CommonMark spec, though.

@lydell It's looks like `CommonMark` have the exact same behavior as GFM:
http://spec.commonmark.org/dingus/?text=%5B1%5D%5BTest%20Text%5D(http%3A%2F%2Fexample.com)

**Comment by ikatyang** [comment] 2018-01-29 00:53
This is caused by [remark mis-parsing](http://astexplorer.net/#/gist/548c2642132c8284e88b3291726ee408/12afe19b65f87354e8116230fb04c7907ad30423), opened remarkjs/remark#324.

**Comment by rekmarks** [comment] 2021-05-04 22:17
This is fixed by `remark` as of October 13, 2020, however it's coupled with a major release of all `remark` packages used by Prettier. Updating those packages seems like a job for someone pretty intimately familiar with `unified`, `remark`, and possibly `micromark`.

**Comment by TrevorBurnham** [comment] 2021-11-17 16:13
I've created an issue to track the task of upgrading Prettier to `remark-parse@9`: https://github.com/prettier/prettier/issues/11828

**Closed** 2022-12-15 06:51 UTC
Labels: type:bug, priority:high, scope:dependency, lang:markdown
