### ISSUE TITLE
Allow Range Ignore for Javascript

### ISSUE THREAD

**Issue by mseefeldt** [prettier/prettier#7737] opened 2020-03-09 14:31 UTC
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: WebStorm
- Runtime: Node.js
- Operating System: Linux

This is a feature request.

For Markdown a range ignore already exists.

I propose to add a similar handling for Javascript code.
In the definitions of routes in express applications a lot of routes
are defined and the files become rather lengthy with the current
way Javascript code is formatted.
The same applies to definitions of maps and arrays which can get lengthy as well.

If there would be a way to have prettier ignore a range, the code
can become shorter. Agreed, this is not readable, but you have a better
overview about all routes on the screen.

**Steps to reproduce:**

**Expected behavior:**

    // prettier-ignore-start
    appApplication.post(
      `${APIRouteDefinitions.pathForRoute( APIDefinitions.routes.getPendingChangesForThreshold)}`,
      (req, res) => {
        validateRequest(req, res, APIDefinitions.routes.getPendingChangesForThreshold, req.body);
      }
    );
    appApplication.post(
      `${APIRouteDefinitions.pathForRoute( APIDefinitions.routes.getPendingChangesForThreshold)}`,
      (req, res) => {
        validateRequest(req, res, APIDefinitions.routes.getPendingChangesForThreshold, req.body);
      }
    );
    // prettier-ignore-end

**Actual behavior:**

    appApplication.post(
      `${APIRouteDefinitions.pathForRoute(
        APIDefinitions.routes.getPendingChangesForThreshold
      )}`,
      (req, res) => {
        validateRequest(
          req,
          res,
          APIDefinitions.routes.getPendingChangesForThreshold,
          req.body
        );
      }
    );
    appApplication.post(
      `${APIRouteDefinitions.pathForRoute(
        APIDefinitions.routes.getPendingChangesForThreshold
      )}`,
      (req, res) => {
        validateRequest(
          req,
          res,
          APIDefinitions.routes.getPendingChangesForThreshold,
          req.body
        );
      }
    );

**Comment by thorn0** [comment] 2020-03-10 09:41
Duplicate of #5287

**Closed by thorn0** 2020-03-10 09:41 UTC
