### ISSUE TITLE
(js) ignoring print width for arguments of function used as second argument, the first being an arrow-function

### ISSUE THREAD

**Issue by nitwhiz** [prettier/prettier#4245] opened 2018-04-02 16:50 UTC
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA7gJ2gcwB0oBnCAWzgHU8p8AVACwEs6AKNgSgwF4A+DMGIYM6DADpJxAL4AaDGUoAxAK5QwMZtDaK4MFnQwBqBRTjiAbnBwBPcQBsC4kjBUAzNxgBUGchBzmjnQOTla2IcEu7p4+UR7iMBDi5ACGANbmzDDJ-nCcnADcxMRiWP5prESkZjQETJVsbmoaWlBcgsKimJLiMvK6quqa2rr6lcamlJbWdkH4zq4e3r65EfNz0+EbcTEKi24JSakZ4lk5AflFUCWYZTgVdMQc3PwdUCJiPX2TcIMtI2YxoYTLpNrMnDtln4AmtYWFwZF9hMdodkulMtloXlOFwriBZCAIAAHYakZCgFI4PBYAAKlIQJGQIBSFggzAAJvjmS5kG4UvYSHACQAjHApMAZGAAZSJ4sqyBgOBUQpA7IgYF5-MFBNYgpwMBpYvwqU1ApVACsSAAPABCYoleilKUoABlWHBTdrCSoYESfQAmT0q2U4PVM4UpYU2IJcok4VgwKgc-TIAAcAAYCXGIIKaCkiUy43A9VYuQEAI4qZgBQ0pY0pIMEwXkZgKpUqkiVexwACKKgg8EbIBgkaT7JTSH9BMVKWY9kqAGEKCaUFBoB6CSpBfRI4ykHyzdJpEA)

**Input:**
```jsx
// wrong
someWrongThing(() => {
  // ...
}, someFunction(something + some.very.long.stuff * more.long.long.very.long.stuff * stuff.to.make.it.more));

// working
someWrongThing(function() {
  // ...
}, someFunction(something + some.very.long.stuff * more.long.long.very.long.stuff * stuff.to.make.it.more));

// working
(() => {
  // ...
}, someFunction(something + some.very.long.stuff * more.long.long.very.long.stuff + stuff.to.make.it.more))();

```

**Output:**
```jsx
// wrong
someWrongThing(() => {
  // ...
}, someFunction(something + some.very.long.stuff * more.long.long.very.long.stuff * stuff.to.make.it.more));

// working
someWrongThing(function() {
  // ...
}, someFunction(
  something +
    some.very.long.stuff *
      more.long.long.very.long.stuff *
      stuff.to.make.it.more
));

// working
(() => {
  // ...
},
someFunction(
  something +
    some.very.long.stuff * more.long.long.very.long.stuff +
    stuff.to.make.it.more
))();

```

**Expected behavior:**
A linebreak in the argument for the anonymous arrow-function.

**Comment by wKich** [comment] 2019-05-28 07:20
Still have same issue for 1.17
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAIwAoAdKTIgOgA9jiBKfAPk2OAF8GAaTANzgAnAJ7EANtADmDKnBoAHQXDRoAltCoB3VTAAWAYWxixaYtigATXtkGSArgFsEaBg3IMA3OXKQoGHPhEZBTUdIwsmMCYSjB2ghRRHJgcvAIi4lIycorKahraeobGpuZWOLaOzq7uHiDcIBDyMOp+yKA2ghCaAAo2zsgg2HwQqhZ1IISC2GAA1nAwAMry06pQksgwgnZw9bowDmIA6ro6ystgcAvOOqp8OsIDYCrjq2hCMN1Tkg7YyABmRje9QAVmgaAAhKazeYLbBOAAyqzg-0BOxAoJoC1WkjEcAAinYIPAUSY0ctBG9BAMYMJ5MowIJVE1xopVjBDqM9MgAMwABnqiggb0OU3kAxylIE4wAjoT4J9GmgBtg0ABaKBwOAWLXjJSy1RKT7Yb6-JAA0n1N4OVQbLZotRrXEEonIs2o+owbCEDkWLlIABMHqmqjE2P0EAcPwGUGgyPqdjeABUvUq3aSOBwgA)

**Comment by thorn0** [comment] 2019-05-28 10:49
duplicate of #2456

**Comment by thorn0** [comment] 2020-05-06 18:18
Duplicate of #2456

**Closed by thorn0** 2020-05-06 18:18 UTC
Labels: lang:javascript, type:bug
