### ISSUE TITLE
comment in array destructuring

### ISSUE THREAD

**Issue by artola** [prettier/prettier#14242] opened 2023-01-27 08:11 UTC
The comment is incorrectly moved to another element.

**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtTAzASwCcNMAaTAegCpM05IoATTay8zGAC2KYF1MAXhwBGCgCYKAZj4BuADpQQZEBAAOMAumSgAhkSIQA7gAV9CNMhC6ANkd0BPSyoBGRXWADWcGAGVdALZwADIEUHDIeLb0ru5ePr5qHmEA5sgwRACucCpwAS5wTEyFwbpQKZm6KXAAYhBEAbowmuVWupkwEMogXDABNgDqPPBoSWBwvhYEmgBu0w5WYGjOIGH0RDAm7imNkdE5IABWaAAevqk2cACKmRDwezYxIEkkcERWLroFNt1qRGEwAYEJjcZAADgADCo-hB6AN3GorH84OsZhEVABHW7wLbqSwoXRoAC04UKhW6RDgWOIcC2VV2SCijwO9ACBHSWRZFzgAEFmv8XB1aW9QuEHk80NybncIoz9ioYF8gSCuMhJCAMroCDZUgBhCABBkgFEAVm6mXoABUvvimU8ZtkAJLMBB+MD-DQ85i+GAOS7iuAAX0DQA)

```sh
--parser babel
```

**Input:**

```jsx
const [ first , /* second */ , third] = [1, 2, 3];

```

**Output:**

```jsx
const [first /* second */, , third] = [1, 2, 3];

```

**Expected behavior:**

```jsx
const [first, /* second */, third] = [1, 2, 3];

```

**Comment by fisker** [comment] 2023-01-29 22:22
Duplicate of #1013

**Closed** 2023-01-29 22:22 UTC
Labels: type:duplicate
