### ISSUE TITLE
markdown: lists with non-default indent size increases padding between list syntax and value

### ISSUE THREAD

**Issue by polarathene** [prettier/prettier#10508] opened 2021-03-12 00:50 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAQQDpXf9DAIVwMPQGFcMARXEAGhAgAcYBLaAZ2VAEMATgIgB3AAqCEPFHwA2IvgE8eTAEYC+YANZwYAZRab2UAObIYAgK5wmcALaq4AEyfOAMn1OW+JuADEIATs+GA5TZBA+SxgIRhAACxg7WQB1ePZ4LkMwOD0pDPYANwzFCLAuFRBjLjgBGDENE2DkADM5GqYAKy4ADyINbV09Pjs4N2M4VvabEG6evWMTWTgARUsIeCnZDpBDARqBCOCBLSdRKDiWAWMYFPYnGHjkAA4ABiYriBqUjRYIq7gB0KkyYAEd1vAGqxpJEuKgoHBnM44gI4OD2KiGj5mkg2tsZjU7OxzFYCYtlmsNpNcdMmDA+Ko7g8nkgACx0jTsWSLCgQOw4kCAgCscUsNQAKgzpHidoVrABJKCuWB6MDXNiYJV6GCKZZbGoAXwNQA)

```sh
--parser markdown
--tab-width 4
```

**Input:**

```markdown
- A
    - B
    - C
- D

```

**Output:**

```markdown
-   A
    -   B
    -   C
-   D

```

**Expected behavior:**

Content after the list `-` is being indented by `<tab-width> - 1`, it should instead remain as a single space?

**Comment by polarathene** [comment] 2021-03-12 01:19
Introduced [in this PR](https://github.com/prettier/prettier/pull/3694/files#diff-751b7c98ecb8b8f58f17f22b778c467270f4d0a4fd6b72a262c71a8a243888b6R335), which clamps the padding to avoid triggering indented code syntax.

At `--tab-width 6` and above this will result in the padding always being the expected single space.

Assuming something to do with either:

https://github.com/prettier/prettier/blob/1ce6b8dc3d3a21155bd95cb56824fe8e720837b7/src/language-markdown/printer-markdown.js#L295-L335

or:

https://github.com/prettier/prettier/blob/1ce6b8dc3d3a21155bd95cb56824fe8e720837b7/src/language-markdown/printer-markdown.js#L464-L497

**Comment by thorn0** [comment] 2021-03-14 11:16
I need to research this deeper, but I'm almost sure this behavior is intended.

What if a list item has more than one line of content?

```markdown
-   A
    -   B1
        B2
    -   C
-   D
```
vs
```markdown
- A
    - B1
        B2
    - C
- D
```

**Comment by polarathene** [comment] 2021-03-14 12:05
IIRC, you match the content for mult-line to where the content would start in the single-line.

You can add blank lines with that content (with no space indentation, but that causes a Prettier formatting bug as well documented in another issue), but there's no need to match indentation width, as that is specifically for indentation width of list item declaration `-`.

For the same reason that the existing formatting code already caps the white-space padding at 3 to avoid content being formatted into a code fence/block accidentally. As mentioned, when tab width is 6 spaces, you'll find it's always collapsed to 1 space anyway. There isn't any value in the added white space after the `-` as far as I now, it should only ever need to be 1, even if you want to introduce a separate list within that multi-line content:

```markdown
- A
    - B1
      B2
          - BA (4 spaces from the content indentation, 10 total)
    - C
- D
```

**Comment by thorn0** [comment] 2021-03-14 12:18
> that is specifically for indentation width of list item declaration

Why do you think so? Lists are just another kind of block content. Indenting only them without indenting other blocks doesn't sound good.

**Comment by polarathene** [comment] 2021-03-14 13:12
> Indenting only them without indenting other blocks doesn't sound good.

Uhhh, there's a difference between alignment and indentation. The list is being indented (along with any indentation prior in scope), the lists content is being aligned, it has a different context/scope. Indentation of content from that point makes a difference. (**EDIT:** Made a slight mistake with my previous example and I see what you meant, the example below should better communicate my intent vs the invalid one from earlier)

You can indent a list declaration by however much, and it won't become a code block:

```markdown
- A1
    - A2
        - B1
          Proper content alignment

              4 space indent from content alignment

          More normal content

              - B2 (6 space indent from B1 `-`, aka 4 space content indent)

            - B3 (4 space indent from B1 `-`)
              - C1

          Additional normal content

          - B4 (Used at content root, only 2 spaces of indent from B1)

    - A3 (resume original list)
    -     A4 (padding of 4 spaces from `-` on this same line)
```

- A1
    - A2
        - B1
          Proper content alignment

              4 space indent from content alignment

          More normal content

              - B2 (6 space indent from B1 `-`, aka 4 space content indent)

            - B3 (4 space indent from B1 `-`)
              - C1

          Additional normal content

          - B4 (Used at content root, only 2 spaces of indent from B1)

    - A3 (resume original list)
    -     A4 (padding of 4 spaces from `-` on this same line)

But content 4 spaces of indentation from the content alignment column will switch to a code block as per markdown syntax.

This doesn't matter what that padding value is, so long as the content aligns to it. Keeping it at 1 space is fine due to that. And as mentioned, from 6 onward it collapses down to 1 to avoid the problem shown in `A4` above, or `B2` if aligning indentation to the content column of `B1`

My previous comment example wasn't proper, hopefully the revised one with Github rendering makes more sense? Prettier aims to be consistent with it's formatting, but is already biasing the white-space behaviour from a certain tab width to always be at 1 (and for good reason to not continue to extend it). Hopefully the above explains why it should be `indentation` + alignment` not `indentation + indentation`.

If I did miss anything or misunderstand, fair enough let me know :sweat_smile:

**Comment by thorn0** [comment] 2021-03-14 13:40
My point is that if I have this content:
```
lorem

- foo
- bar

ipsum
```
and want to move it inside a list item. It shouldn't turn into this just because it's in a list item now:
```
lorem

  - foo
  - bar

ipsum
```
Your answer boils down to "no, it should", but for what reason? Because "You can indent a list declaration by however much, and it won't become a code block"? Sorry, I can't see how this justifies different indentation/alignment of sibling blocks. Besides, it's not the case:

    - list?

**Comment by polarathene** [comment] 2021-03-14 20:52
> Sorry, I can't see how this justifies different indentation/alignment of sibling blocks. Besides, it's not the case:

I didn't mean to convey that, sorry? Yes the example above does cover that mixed indentation, but it was for showing what happens. What this issue asks for is that the space after `-` remains consistent for content at 1 space, regardless of `--tab-width`, which should only affect indentation of lists from the content (Like `A1`, `A2`, `B1`).


The two big code block lines in `B1` content should be avoided by not repeating the `--tab-width` from the content, this is better illustrated in `A4` as it's padding reaches 4 spaces causing the content to implicitly become a code block.

`B4` is correct way to start a new list within the list item content (`-` is aligned to the start of the content), whereas `B3` would technically be the continuation of `B1` list into sublist (not sure how to say it, similar to `A2` is to `A1` in regards to relation and indentation.

Perhaps we're miscommunicating here?

**Comment by thorn0** [comment] 2021-03-14 22:26
> --tab-width, which should only affect indentation of lists from the content

I can't agree with this. I see how the current behavior is consistent and how what you ask for isn't. And it's still not clear for me whether you're claiming that the current behavior breaks something. Please clarify this part.

> Perhaps we're miscommunicating here?

Very possible as I'm talking about things I know little about. Sorry about that. I mostly contribute to other parts of Prettier. I promise to take another look at this later, after reading through the spec.

**Comment by polarathene** [comment] 2021-03-14 23:06
> I see how the current behavior is consistent and how what you ask for isn't.

```markdown
- A
- B
    - C
    - D
        - DA

          Content
          - SublistA
              - SublistB
              - SublistC

          Content

              inline code block

          Content
        - DB
    - E
```

- A
- B
    - C
    - D
        - DA

          Content
          - SublistA
              - SublistB
              - SublistC

          Content

              inline code block

          Content
        - DB
    - E

Prettier output for `--tab-width` of 4:

```markdown
-   A
-   B

    -   C
    -   D

        -   DA

            Content

            -   SublistA
                -   SublistB
                -   SublistC

            Content

                inline code block

            Content

        -   DB

    -   E
```

With Github Markdown rendering (which is rather lenient at parsing and working around mistakes mind you):

-   A
-   B

    -   C
    -   D

        -   DA

            Content

            -   SublistA
                -   SublistB
                -   SublistC

            Content

                inline code block

            Content

        -   DB

    -   E

Looks the same, the added padding for content made no difference.

---

Now with `--tab-width 6`:

```markdown
- A
- B

     - C
     - D

          - DA

               Content

               - SublistA
                    - SublistB
                    - SublistC

               Content

                   inline code block

               Content

          - DB

     - E
```

- A
- B

     - C
     - D

          - DA

               Content

               - SublistA
                    - SublistB
                    - SublistC

               Content

                   inline code block

               Content

          - DB

     - E

Padding between `-` and the following content is now 1, although the multi-line content for a list item is being indented at 5 spaces (white-space - 1). Increasing `--tab-width` from here on has no effect on output what so ever. Not to indentation or padding, it ceases. You'll note that against `--tab-width` of 5, the indentation is the same, only the padding has changed

---

Here's `--tab-width` 5:

```markdown
-     A
-     B

      -     C
      -     D

           -     DA

                 Content

                 -     SublistA
                      -     SublistB
                      -     SublistC

                 Content

                     inline code block

                 Content

            -     DB

      -     E
```

Rendered on github:

-     A
-     B

      -     C
      -     D

           -     DA

                 Content

                 -     SublistA
                      -     SublistB
                      -     SublistC

                 Content

                     inline code block

                 Content

            -     DB

      -     E

And again, but this time we'll manually push it to `--tab-width` 6 as if it was consistently applying the same logic of increasing `--tab-width` (no padding collapse and no capping at width of 5 for indentation and content):

-      A
-      B

       -      C
       -      D

             -      DA

                    Content

                    -      SublistA
                          -      SublistB
                          -      SublistC

                    Content

                        inline code block

                    Content

              -      DB

       -      E

Not a huge difference from 5 on github, as we can see, since it's just considering it two list items with indented code blocks. Obviously there isn't much point in increasing the padding after `-` beyond 1 space, it's not providing any meaningful value AFAIK? And would break once it's considered as indented code block.

So why is there a special case for Prettier to output 2 and 3 space padding? Why not remain consistent throughout with 1 space padding? Indentation and alignment (padding) are different things, as we can see above. That even gets thrown out of whack at `--tab-width` 6.

This is no different to how tabs are used in programming languages, where you are only using them for indentation. Some spaces can follow those to pad for alignment such as a functions parameters, you would not add additional hard tabs for that alignment, even if they perfectly fit into the tab units for alignment on your machine. Since many favor tabs inputting a unit of fixed spaces instead now, this seems to be overlooked and thought of as the same thing?

**Comment by polarathene** [comment] 2021-03-14 23:14
> And it's still not clear for me whether you're claiming that the current behavior breaks something. Please clarify this part.

I don't think it's breaking anything, the related bug about inserting new lines, as can be seen above can cause breakage IIRC (I gave a similar detailed example on that reported issue thread).

I just didn't understand why values after `-` were being padded like shown above. I always use 1 space padding, and shouldn't need to think about needing that to be more than that. It adds no value.

I only require indentation of 4 spaces to make more strict markdown parsers happy like the Python Markdown parser that MkDocs uses (and maintainers refuse to support 2 spaces citing it as against the official spec).

As I think most are quite happily using 2 space indentation elsewhere, they always have 1 space padding. Personally when `--tab-width` setting was supported for lists, I think this was **accidentally introduced as a side effect**?

The [original bug report](https://github.com/prettier/prettier/issues/3679) that the PR was for, was regarding Bitbucket's markdown parser also wanting 4 space indentation, but you can see **in their example that the padding remains at 1 space**.

**Comment by thorn0** [comment] 2021-03-14 23:59
Anyway, this issue is a duplicate. Closing it in favor of #5019.

**Comment by thorn0** [comment] 2021-03-15 00:00
Duplicate of #5019

**Closed** 2021-03-15 00:00 UTC
Labels: lang:markdown, status:needs investigation, type:duplicate
