### ISSUE TITLE
JSDoc typedef parentheses are removed if the open parenthesis is on the line after the typedef

### ISSUE THREAD

**Issue by rsimha** [prettier/prettier#6120] opened 2019-05-14 21:12 UTC
**Prettier 1.17.1**

**Before:**
```
foo = /**@type {!Foo}*/
  (bar);
```

**After:**
```
foo /**@type {!Foo}*/ = bar;
```

Playground link [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA6gJ2gcwB0oAzCCDAXg1QCpaABGATwAc4NgBCAMXIF9aqYhgwAKAEYBDHAEoA3MXQYAwhBw44YGMTIVqdRi3adeAoaMkyFu8lRr0mbDtz4RBmMSIzS5iqCAANCAQrDAAltAAzsigMngA7gAKMggxKFIAbhDhACZBIBI4UmAA1nAwAMqsJeFQ+MgwOACucMEAFjAAtgA2WO3h8FE1YHCVaYPhmYPMyOBRMcF1UXA4MEnF+F1SyCRSPSvBAFZRAB4AQsVlFZVSXXAAMnVwu-uHICenlXX4PXAAis0IPBXgc2iAajgVjg5tIJMwetACqwcHUYFg8jB2sgABwABmCKIgK1wUlYcxRcGhmRewQAjkD4BtQukQFIogBaKBwOC5XkFTQM8KaDZSLY7JB7MHBFZdcKNFrgqI-P6A4EvSVvcEwKQSDG5LHIABMwSaUnCPR+ai62zmUGgtJAzRWABVdekpSt+PwgA)

Related to #4799

**Comment by sosukesuzuki** [comment] 2020-03-10 15:39
Fixed by #7709

**Closed by sosukesuzuki** 2020-03-10 15:39 UTC
Labels: area:comments, lang:javascript, type:bug

**Comment by sk-** [comment] 2020-04-05 15:20
@sosukesuzuki when can we expect this PR to be released? The first line of the PR description says:

> Sorry, this is not related to 2.0

**Comment by sosukesuzuki** [comment] 2020-04-05 15:30
@sk- #7709 has already released.

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAEBeTB6AKgIAEYBPABzk2AEIAxDAXwLwB0pNMAKAIwEMATgEoA3CAA0ICBRgBLaAGdkoIYIgB3AApCEylPwA2G-mWVTeg-mADWcGAGUK1uVADmyGIICucKQAsYAFtDAHV-OXhFZzA4Bz1IuQA3SLJkcEVzEFdFOEEYLSs3IP5kVCNcqQArRQAPACErW3sHfiC4ABlXODKKvxAa2odXN0M4AEVvCHhew0qQZ0FcwXSBXjhDSQXBVxhQuQATGH9kAA4ABikKdVzQqwp067hlpJ6pAEcp+EKZfRB+RQAWigcDgBzBW0EcE+cihhX4xVKSHKc36uSCck8PjRIzGk2mPWRfSkMH4vH2RxOSAATCSrHJDCMAMIQIIldLPACsW28uQAKmT9Cj5klfABJKDg2AOMA7WQAQUlDnIY1muSYTCAA)
**Input:**
```js
foo = /**@type {!Foo}*/
  (bar);
```
**Output:**
```js
foo = /**@type {!Foo}*/ (bar);
```

> Sorry, this is not related to 2.0

means that the PR was not on the 2.0 milestone at first.

**Comment by sk-** [comment] 2020-04-05 16:00
Then I found another issue related to this change. 

The following code, gets formatted incorrectly:

```ts
const accountsRef = 
      /** @typedef {FirebaseFirestore.CollectionReference<AccountModel>} */
      (itemRef.collection('accounts'));
```

See [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDMkCusaASnAGaYC8AOlJvQwPQBUzmAAjAJ4AOcAJuUzAAYgEsATnABG2NHHFSMEKQDoAwhAA2WuGBhjopMnClQwcADwBBPBEIwAshEFaAfAF9MzRrQYMACjF4AFtjVUgdPQNoAIByXAIiOIBKFIBuEAAaEAgeGKg0ZFBsCQkIAHcABVKEIpRsLQrsLiKc6QlcAGs4GABlHlwxKABzZBgJfDgcgAsYEK0AdRnguDRBiz664LEAN2CuZHA0NpBh+QkYKs6RkOxkMkb5HIArNAAPACFOsB7+7BCcAAMsM4A8ntMQG93n1hiNdABFfAQeDgrTPECDCQXI6yaRwLTZTESYYwRZifgwGbIAAcAAYcjxyvJFp0eEcmWtTLswTkAI7I+DXPL1EByAC0UDgAgERKkAskcGu2Fu9yQj3RkPkITE40mWrhiMFYPVEJyMGw0nJlOpSAATObOmItHDNCE7kc1gBWIn4eQAFUt9Q1GN2UwAklBBLA+mASflrFG+txdGj5B4PEA)

**Comment by sk-** [comment] 2020-04-05 16:21
@sosukesuzuki Should I open another issue? Or will this one be reopened?

**Comment by thorn0** [comment] 2020-04-05 16:24
@sk- It's `@type`, not `@typedef`. See [the Prettier 2.0 blog post](https://prettier.io/blog/2020/03/21/2.0.0.html#ultimate-fix-for-closure-style-type-casts-7791httpsgithubcomprettierprettierpull7791-by-thorn0httpsgithubcomthorn0-7011httpsgithubcomprettierprettierpull7011-by-evilebottnawihttpsgithubcomevilebottnawi).

**Comment by sk-** [comment] 2020-04-05 16:39
@thorn0 thanks for spotting my issue. For some reason typescript was accepting both.

**Comment by thorn0** [comment] 2020-04-05 16:48
It shouldn't treat both as the same, at least I can't reproduce that: [TS Playground](https://www.typescriptlang.org/play?useJavaScript=true#code/MYewdgzgLgBAnjAvDA9AKjTAAlOAHAUwBMCAzGAb2gCcBLMAcwF8Y0UYAKADwEoBuIA)
