### ISSUE TITLE
Error when tag <pre> in <p>

### ISSUE THREAD

**Issue by Bekmirzo1** [prettier/prettier#15294] opened 2023-08-26 04:42 UTC
Code:
```
<p>
    Text:
    <pre>Code</pre>
</p>
```
Prettier shows error ' Unexpected closing tag "p"'

**Prettier 3.0.2**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet
```

**Output:**

```jsx
// code snippet
```

**Expected behavior:**

**Comment by so1ve** [comment] 2023-08-26 09:35
You can't put anything except text inside `<p>`. Your code has a syntax error.

**Comment by auvred** [comment] 2023-08-26 09:53
Duplicate of https://github.com/prettier/prettier/issues/11907

**Comment by kachkaev** [comment] 2023-08-26 16:18
I’m unable to reproduce an issue in your playground link:

**Prettier 3.0.2**
[Playground link](https://prettier.io/playground/#.....)

```sh
--parser babel
```

**Input:**

```jsx
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  if(!greeting){return null};

     // TODO: Don't use random in render
  let num = Math.floor (Math.random() * 1E+7).toString().replace(/\.\d+/ig, "")

  return <div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}>

    <strong>{ greeting.slice( 0, 1 ).toUpperCase() + greeting.slice(1).toLowerCase() }</strong>
    {greeting.endsWith(",") ? " " : <span style={{color: '\grey'}}>", "</span> }
    <em>
	{ greeted }
	</em>
    { (silent)
      ? "."
      : "!"}

    </div>;

}
```

**Output:**

```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver,
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}

```

Can you please update issue description? It is likely that we’re dealing with a duplicate of https://github.com/prettier/prettier/issues/11907, but let’s wait for @Bekmirzo1 just in case to confirm.

**Comment by so1ve** [comment] 2023-08-26 16:34
@kachkaev He is not following the issue template.

[Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgDpQAQF4AqcAHjEroXhgE5yYDCEAJnKgPTr05SdYgANCAjoYAS2gBnZKACGtWhADuABQUIZKOQBtlcgJ4zhAI1pywAazgwAynIC2cADLiocZADNdUuKfNWNrboFm4A5sgwtACufiC+DuKRMXFS4TpwAIrREPBePnEAVlKktulZOXlI3jq+wgCOlXCqSuhaIHJSALTucGwsQiBRcuI64cwODnLIHTo6g2lQYRkAgjBR4ibR8KpwtK7u+bVxABYwDjoA6ifi8FIhYHC2mrfiAG63BjNgUsYgb7EAJJQNiwWxgWjiMQrEG2GAGDJHOogbgQXyXczoGbcOC+WhvDzCNx4mAtORhKZIuIhWh4mZnC6DbhuGCXcQsGAnZAADgADMJ6I1xPQyRTptUCsIYHITGyOVykAAmYTRXxEGVaGrIuAOEx9frOORLaLkuAAMQgtCm63CMzk2wgIAAvk6gA)

**Comment by oscarhermoso** [comment] 2023-08-29 08:46
@Bekmirzo1 Use `<kbd>` or `<code>` for inline code styling, or if you want block level styling, move the `<pre>` below the closing `</p>` tag

See:

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd#basic_example
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code#examples
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre#basic_example

**Closed** 2023-09-10 00:12 UTC
Labels: status:awaiting response
