### ISSUE TITLE
some less variables accidentally lowercased

### ISSUE THREAD

**Issue by scott-ho** [prettier/prettier#4090] opened 2018-03-02 07:53 UTC
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABMBDANggJhgJwGEIsICkACAYjDoG4AdKdbPQksggFTgA8YlKrQbNWOKPgIBJKAAcArjE7lhADgCsmtQBYmLTBKkAlDFADmcXgJUUaOgOwAjAAy4AjPvHsCAZQCW5lAAzgCCYDD+AG5wtsIuLgCcuGAO+swA9BmUZADucASYwXC4APxihj4BQWER0Vb8gsIAZq1elZKEALTVIV3hkTFd1k00rc1eClD+yqTkQjQYDhiJGGD0IAA0IBBykdDByKCEBBC5AAqECIcoGFEQ-rhbIBjBMMjN2MXbTgRrANZwGC+ORrfwWZAwAgKODbXAQMAfL6wkDg4oEGDnP7mAC2GCRWG+IAAVsE+AAhP5gQHAjA4uAAGXBcAJRIgSkUMAATKyUaCCOjkCAcMFDts5ARwTAAOqPGAAC2Qahc4tOxWlfzkQolcHRMWeBDgAEcFP5DViMLj8UhPoSUcUcf5IdD7eDzDgAIoKCDwXnbGAYJyy3AK5Bc-1-fxYN0kHF4oVQaAs7YKYrcQM3W3FAC+2aAA)

**Input:**
```less
@calendarColor: #ccc;
@calendarColorText : #ccc;
@calendarInputColor: #858584;
@calendarRangeTextColor: #47b0d1;
@calendarSignsActiveColor: #009dc7;

// lowercased?
@calendar-Signs-Active-Text : #fff;
@unitColor : #a7a9ac;
```

**Output:**
```less
@calendarColor: #ccc;
@calendarcolortext : #ccc;
@calendarInputColor: #858584;
@calendarRangeTextColor: #47b0d1;
@calendarSignsActiveColor: #009dc7;

// lowercased?
@calendar-signs-active-text : #fff;
@unitcolor : #a7a9ac;
```

**Expected behavior:**
Output should be exact the same as input.

**Comment by evilebottnawi** [comment] 2018-03-02 09:32
@scott-ho Thanks for issue :+1:

**Comment by evilebottnawi** [comment] 2018-03-02 10:24
Problem in parser https://github.com/shellscape/postcss-less/issues/92

**Comment by evilebottnawi** [comment] 2018-03-02 11:04
@scott-ho PR welcome to parser :+1:

**Comment by evilebottnawi** [comment] 2018-03-07 15:41
Oh, duplicate https://github.com/prettier/prettier/issues/2925. Thanks for issue!

**Comment by j-f1** [comment] 2018-03-07 19:07
Duplicate of #2925

**Comment by evilebottnawi** [comment] 2018-03-08 12:47
@scott-ho yep it is one problem in `postcss-less`, because it is parse as `at-rule` (example `@media`)

**Comment by suchipi** [comment] 2018-03-08 17:43
@evilebottnawi even though the cause is the same, since the symptom is different, I think it would be easier for users to understand if we kept both issues open and closed both once the bug in the parser is resolved.

**Comment by evilebottnawi** [comment] 2018-03-09 12:01
@suchipi :+1:

**Comment by scott-ho** [comment] 2018-03-22 10:56
@evilebottnawi Just now, I find out that not only less parser but scss parser might has the same problem.

see the image:
![image](https://user-images.githubusercontent.com/35443789/37766150-03411aec-2e01-11e8-9f4a-df52f926df58.png)

`node.name` is `"calendarColorText"`, being not end with `:`, then it's lowercased by prettier.

One thing needed to be mentioned is that, 
![image](https://user-images.githubusercontent.com/35443789/37766422-da8dfeac-2e01-11e8-81e1-eac15d24cfc6.png)

my less file is **parsed by scss-parser** based on logic pointed in the image.

---

even though I explicitly specify less parser for my less file. Same problem.

**Comment by scott-ho** [comment] 2018-03-22 10:57
The key problem is the space before colon.

**Comment by evilebottnawi** [comment] 2018-03-22 11:04
@scott-ho if you file have `less` extension it is always parses `postcss-less`

**Comment by scott-ho** [comment] 2018-03-22 11:08
The version of prettier I installed is `1.11.1`. @evilebottnawi do you see the second image attached? The **test logic** will result in going for scss-parser

**Comment by scott-ho** [comment] 2018-03-22 11:10
And see my style config in `.prettierrc`. 
![image](https://user-images.githubusercontent.com/35443789/37767296-9d283db8-2e04-11e8-98d0-7b3a2a69b3f5.png)

parser option is specified as `css`

**Comment by evilebottnawi** [comment] 2018-03-22 11:11
@scott-ho remove `parser` option

**Comment by scott-ho** [comment] 2018-03-22 11:12
without parser option, it would be the same. Do you agree?

**Comment by evilebottnawi** [comment] 2018-03-22 11:13
@scott-ho without `parser` option, `opts.parser` have right value for each file type, i.e. for `less` - `postcss-less`, for `css/scss` - `postcss-scss`

**Comment by scott-ho** [comment] 2018-03-22 11:16
@evilebottnawi sorry, my mistake. It will flow to less-parser. The less-parser is still the problem.

**Comment by evilebottnawi** [comment] 2018-03-22 11:20
@scott-ho you can send PR to `postcss-less`

**Comment by Ludevik** [comment] 2019-01-09 12:48
Stumbled upon this today. Simplest [testcase](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAKnAzjABE3AYgDFSBuAHShABoQIAHGAS2i2VAEMAnbiAdwAKPBOxScAbhGYATWiABG3TmADWcGAGUGK5lADmyGNwCucOgAsYAWwA2AdQvN4WHWDibRz5hOcBPZHAsdjo9LDhuGEFlfWtOZAAzTltwugArLAAPACFlNQ1NTms4ABk9OETk1JAMzM09fVs4AEUTCHhKlPMQHW5w7kCm4PkGbj0Ye1kYC2QADgAGOlGIcPtlBkDR7AiJCrpuOABHE2YD6M5Y+KQkrrpw62YjU26sBqbW9orrqu6YTgVJjJpsgAEx0YycZi2BoAYQg1jigSg0D2IBM4XQ-zEN3CAF9cUA). Space after variable name causes that the variable name is lowercased.

**Comment by kelchm** [comment] 2019-01-31 18:24
Am I mistaken in saying that this has already been [fixed](https://github.com/shellscape/postcss-less/pull/101) in `postcss-less`, but the `postcss-less` dependency for `prettier` has not been updated?

**Closed** 2019-11-08 15:34 UTC
Labels: lang:css/scss/less, priority:high, scope:dependency, type:bug
