### ISSUE TITLE
styled-components selection formatting issue

### ISSUE THREAD

**Issue by lekterable** [prettier/prettier#7082] opened 2019-12-02 14:40 UTC
A quite specific case, because you have to use `export const ...` syntax and try to format the css parameters inside of a template literal of a given styled-component, but this is also very annoying when using [precise-commits](https://github.com/nrwl/precise-commits) to format just the changed lines, as because of this bug 9 spaces of indentation are added instead of 2 whenever you change a single css property.

**Prettier 1.19.1**

**Input:**
```jsx
export const Button = styled.button`
color: blue;
`;
```

**Output (when formatting the selection or running `precise-commits`):**
```jsx
export const Button = styled.button`
         color: blue;
`;
```

**Output (while formatting the whole file or the whole component - works as expected):**
```jsx
export const Button = styled.button`
  color: blue;
`;
```

**Expected behavior:**
```jsx
export const Button = styled.button`
  color: blue;
`;
```

**Comment by thorn0** [comment] 2019-12-02 14:44
May be a duplicate of https://github.com/prettier/prettier/issues/4926, but I'm not sure.

**Comment by evilebottnawi** [comment] 2019-12-02 14:46
Yes, it is bug https://github.com/prettier/prettier/issues/4926

**Comment by thorn0** [comment] 2019-12-02 14:49
Duplicate of #4926

**Closed by thorn0** 2019-12-02 14:49 UTC
Labels: area:ranges, lang:javascript
