### ISSUE TITLE
[Feature Request] Class constructor arguments on new lines

### ISSUE THREAD

**Issue by alshdavid** [prettier/prettier#11040] opened 2021-06-08 01:53 UTC
Class constructors serve as a place for dependency injection, and thus functionally act like the "import statements" for the current class.

Prettier currently wants to inline arguments in the constructor, converting a class like this:

```typescript
class Foo {
  constructor(
    private readonly _a: IA,
    private readonly _b: IB,
    private readonly _c: IC,
   ) {}
}
```

Into :
```typescript
class Foo {
  constructor(private readonly _a: IA, private readonly _b: IB, private readonly _c: IC) ​{}
}
```

This can cause significant readability issues as it's difficult to understand the imports at a glance.

An analogy for this would be the effect on readability putting import statements inline:
```typescript
import { A } from './a'; import { B } from './b'; import { C } from './c';
```

My current solution is to set the max line width to something tiny, but this has other side effects.

**Comment by thorn0** [comment] 2021-06-08 13:14
Duplicate of #5666

**Closed** 2021-06-08 13:14 UTC
Labels: type:duplicate
