### ISSUE TITLE
Space inserted incorrectly in CSS variable in template literal (Emotion)

### ISSUE THREAD

**Issue by seaneking** [prettier/prettier#8196] opened 2020-05-01 02:20 UTC
Bit of a niche one, but I'm using Emotion and trying to construct a css variable name based on props. Prettier is inserting a space in the string, breaking the variable name.

**Input:**

```jsx
css`
  font-size: var(--scale-${large ? 2 : 1});
`
```

**Output:**

```jsx
css`
  font-size: var(--scale- ${large ? 2 : 1});
`
```

**Expected behavior:**

Space not added to variable, output remained unchanged.

**Comment by evilebottnawi** [comment] 2020-05-01 11:31
Please use the issue template in future and playgound

**Comment by thorn0** [comment] 2020-05-01 11:52
Duplicate of #5465

**Closed by thorn0** 2020-05-01 11:52 UTC
Labels: area:multiparser, lang:css/scss/less, type:bug

**Comment by seaneking** [comment] 2020-05-01 20:57
I did use the issue template? And sorry, thought the playground wasn’t worth it because it was literally one line.

**Comment by thorn0** [comment] 2020-05-01 23:33
Issues submitted via the playground have a link back to it, so that it's possible to see the reproduce live. We need to communicate that better somehow (ideas are welcome here: https://github.com/prettier/prettier/pull/7974).

**Comment by seaneking** [comment] 2020-05-01 23:38
Gotcha. Yeah in the issue template it sounded like the playground was just to save on typing the `output`
