### ISSUE TITLE
Hello everyone , I use prettier with create-react-app ,when I save it ....it auto add {" "}  

### ISSUE THREAD

**Issue by luandevpro** [prettier/prettier#5035] opened 2018-08-31 10:23 UTC
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--single-quote
```

**Input:**
```jsx
// code snippet
```

**Output:**
```jsx
// code snippet
```

**Expected behavior:**

**Comment by lydell** [comment] 2018-08-31 10:51
Hi! This is discussed over at #4223.

**Comment by lydell** [comment] 2018-08-31 10:51
Duplicate of #4223

**Closed by lydell** 2018-08-31 10:51 UTC
