### ISSUE TITLE
prettier --write doesn't fix all issues on first run

### ISSUE THREAD

**Issue by mderazon** [prettier/prettier#3345] opened 2017-11-29 10:27 UTC
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAVgZwwMwgCcMoIYBLSsAQ0ugxhoCMAdKAEgAoATCMAK4BbBDACUAOiJwaPAJ5d8AqGHpQMXMRmDsMejN1YgJTZgBkKUANZHJMsAAtFy1RQabtu-d+4wHFHEkwABsKMCtnFTUNLR11bwS9IQwAXgMuPwDJOhgiLgByCh58sQBuL0SfAokhAGEAZQAhAH0eIhoAcw64IgAaDBqGlshYGksekokwHBwCmAgAB3z+-IAGBYAPEvL4yv1DY1MLa1spOCEIADc4WuCaGa4jGldrgBUWWx29qszAiVkeLd7rMni84O82CAyhVvgcTCwcPU4K5oKcAUCHkZ-Dw4J8YXsDgBiIwYADUGGS5KMzQAjKdpBdrhiQSBsbiofjKtIYAIiOp8DRgjg4F9KgBfaG7DAS0V6dC4AjEDDMCAQKyWDoYaQARwEcBwMAwggNEBEJFMMLhR0sVjpUIk9icSiibnUHjiBIy-j+ITCEWdKLdsU5iWSaV83uyMFyBSK2xDCStLGOtvp5yuNzumJAz0obw+UNlsK9WX+PEBWZZuYo+chku++0exiERR4wXBLCRgbR5eZTbZeKlnqMxJAZIp4+pdskDIzfaxRXZYgT3m5vP5guFRe8Mphu6gMPleEI5tVwUoC0t1Us8A67TUAFoRFABA+wtBJr7wpFAzFPEPG3yCQbzgO86FdJ8EFfd91AEYIaigt8RjfWBQPvV1JhwUIcVeCAunbTQi33fd2HQDAFk6OAMEsKh2CwABFPUiAUANondGEaJgABBMBICIHhXUI9gSKgMjnj4gSGGfARqKgWioFY11ZKoHiJME4MpQYpiFCA8TiEkqBMOwuBVP0wSPUqRYEB6JAMCAqyoAmXoEywxciFsoDXJxZYExoOShHqBY4DgHhbIAZlWVY90lMV2FIgAqXR4uwRiejkDBTP4pSFmCAQOksJLUHYUoNEU9wOA0nwJHwKAJC8kzeLMhg0jKt1FnEf89jInEBTgw12tdHAE0uGgSAG6A8HDB0NngKAeC4CyG3RStGjgE8TP88DoFsgUhTgZyAMSasmUrDzjrgHzDoSBybLsiQbqIS6Gz0er3Lu+qnuevyKACoKQvCyKDueo0IGCO4FhwChmHbWzcj1IHnrga5YA8r8rHyBMxX6drJQTNc+UYb0HWeJ0XDYyrnrI8aoCGq7vBGkg9Ky5r0l+etnoZ6j4CESaMCZgzqsseb8iQBx7gKcdqZwOrjJIckSnjA86f0Khzmlx0f3Jzrgf0TnVbDVnI23DnRowB7Ui585BbmrgpfuoLHKIdmdYwTnXot-Xrfmu3XudnWHokZghdthY1HV5GYH6VqNDgCmXe8Ch8A0ABCV7gNmEXvqEOgQpKOP48SRONE9sWcD7O3zuZMR84LvYi5DsOplB8HIeh2PtdrnW0-qgBVBYG8G-5-MC4KeCjsmlPY5XO72Nl6mMrhfeNmfns92cTuBAeJv+MEq+XleEn3A-xRXeOxQwOA9o74-9DInAHAgAB3PmwVPzvOfba5ggASW53nPdbqEKAHQM4SHyJLUOg9K6Vj9jfV2ptXoAFF2zPhgLzT+l9f5qy9lvGmMs3KwJvp7Zam8K67xgfvFe98n7z0XIvWWkg2SaHwTiAAIk-KAuDpZZxHiFXG09a5kUgGDGgEMqLkAcD0WmcDvBIJQaIaWvd+4V2Hn9MeBAJ7uBrjIvQGCf5-zOIyTMpDIHb2gcCQhOi54LzkecBRliD5HxvrFARewXErzgBIBY0gI6sLWjQPqQlXH6CcS7euJd7jl1MXg8xMxq4YGoY-WhOJ6EEJKpfYUGBrF0KXm-aUDjQnSh2IeTA-MlL1VdgEKGFBQgwDkDCN2D8knGQttHVJOJtF6HxuoeqUwHjAHIhASGagPLLEYIsUZ-R2z4BgJMjAj8ih+FGfkoiRZObZJxK0zRbp6qdK1HAHkBNemJOYdMWYAyFhDKoK6M6zAcCgwEPAMZ8wFi2QfAATk+e8qZa1ZkYA+V8-oCyeBLIScZCQwK-AeEKWKHYYouBaTStXYpolUBYBoCNHAYAiAUFDoqEg1wiDUEFMEdK0gcCXJpjWXECltkYG-nJGAAAFSiU9vC+lEAACTgBQDoDhDQtWaBy2A3LeX8o8A+DAAAmAArKsIswoYCir5TAAoABZMYUBWF0BoLUUQPRmihANJlAyYzhVKp5Sq-5GAAAsMq-aKuVeK-Ipg-FMBqQAdXaAsIKj1+jmqdYackMr3kOoOYGgoZBKD4DCFtLVByxjBC7GoM1oQuWWv5eOAA7PahV4aM2qvyDGy+PALDMHaMxVNFB01iqDRgGkqwwphotbWgoRruKNWZoZf1aaRUFvHA25tEb8g9QCeeRoqp1TAIAGLECEFWmtVryQNoABxDoLQUHAPN5BQBoC2MA07q3BB4MmjCPbq19trdaqVYUABs67W35GzpYCdaoNQnnneexdmbg2hrhXFWlLoGD4CFb2ltKq2X6G6QQZoMbzw9AAEr6j6iCA8MBWAwAWXNJ+wEoCO0DRgAA-PMoWOHLD4f7bZVYB0MMYb4IIVBEh6PCFEMguxsAiMYGY4x7jrH5GwCmGBgjVGaPoZgLxgTKp5CcYkzAQOEB5CCYveBzNVG4riH-UraOIG4PwCIEhnAKGuBQGaFh-oJn6OX3M80KTch86cxM+SvqFsTNYc465ywGAqNFnrhZ-gl8MAADJAsp0c8h88GAAA+kWNBhcMxFgAfKQVo-ngjV2XFdOLzm0h+bAJfIs0GTO2aCyFrgycssRei7F5oTnEvJds-E4jRWFPpVshVmAmn2DR0dRuoo-RJG1v6AEDVGxA32dNpfKiaRZMSG6DANjqDGhyG-vNIoft66Tb2eEnAI2xt5Mm3VOp7Yag0FG-2tIA2l12U2PkfeGSaXAwOwaOQx3LuZou-2+WN2iLCQA91g5arLARr6xSIHBbxskEmxbGbc2FuiCWytrga2fNJy4Jt6+CdUctigHtgRT2jueOxwRtIRPPvXa2D9qAYoQC9BAFLZAoB7gwGQLtYUtPy3PCsAcwKzwNTIDhvtEA9GWebkF5YYURKmXtA6NnEXe1ae4A2I0do4Rud7rgMcOAcu2d08eQsR5UrteC4okQCXyAQDMBYC96ANOQDeJvB6xZDhkAruo3bogQy4BetEfzog8MQA6gEBQaQUvOiy6QKzwXwoWy+-95DYB7ZGLkC1xH0XtPTCO5Bc7pAUr0-tBqRqWoppw8gDII5W3AhhQQhwEbsUYogA)
```sh
# Options (if any):
--single-quote
```
I am running [this code](https://pastebin.com/gYvqe9eJ) in prettier:
```
$ prettier --single-quote --list-different myfile.js
```
Getting
> myfile.js 112ms

(As expected since the code is not prettified)

The I run
```
$ prettier --single-quote --write myfile.js
```
And then again
```
$ prettier --single-quote --list-different myfile.js
```
And I am still getting report that the code is not prettified.

After the second time I run `--write` the code is not showing any differences anymore and seems to be prettified

Here is the diff between the result of the first `--write` run and the second one:
```
$ diff myfile.js myfile-first-run.js
112,117c112,119
<     return slide.show().css({
<       position: 'absolute',
<       top: -9999,
<       left: -9999,
<       width: slide.width()
<     });
---
>     return slide
>       .show()
>       .css({
>         position: 'absolute',
>         top: -9999,
>         left: -9999,
>         width: slide.width()
>       });
```

**Comment by azz** [comment] 2017-11-29 11:08
This is a known instability bug with Prettier.  Closing as a duplicate of #2803

**Closed by azz** 2017-11-29 11:08 UTC
