### ISSUE TITLE
Should lists have break lines everywhere?

### ISSUE THREAD

**Issue by leobastiani** [prettier/prettier#10105] opened 2021-01-22 14:38 UTC
I'm sorry for any duplicate, but I could not find anything related.
I actually think that lists shouldn't break line for each element, instead it could check if the next element overpass print-width option and then break on it. This example explains what I think that prettier makes something less pretty than the before.

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaIFs4AyAlhpgLyYDaAOlJpgIwA0mATCwMwsAsLArCwBsLAOwsAHCwCcLBgAZZzRu0ZdGvRgNqNhjMY0mMZbBWyWsVrNaw2sBbXa32tDrYxzm0AuiCYgIAA4wROjIoACGAE6READuAApRCGjIIOEANrHhAJ4pfgBGkeFgANZwMADKAcVEUADmyDCRAK5wfnC4+XAAJt09BOH1zeF1cABiEJG44TDB9anhzTAQviAAFjC46QDqa0TwaNVgcBXJ+0QAbvvZqWBoeSC1aHCRMPFFddPIAGYZz34AKzQAA8AEJFUrlCrhfDEKBwH5-NogIHAiq1OrpOAARWaEHgiPS-xA1Uiz0iqXy4S66VWAUitRg2yI3Rga2Q4gUJJiz22RQCqXpcHJFwRfgAjnj4O9AikUOE0ABaeE9HqrSJwSVEDXvEZfJC-InI564IiNFrGjFY3H4hEGpF+GDU5ms9lIdggJrhIjpDEAYTw+pAwr4q2azwAKtS5YbiRdWgBJKB9WAVMAMoIAQWTFRg2SxhOeAF8i0A)

Before:
```javascript
// few lines of code
const someList = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
]
```

After:
```javascript
// lots of lines of code
const someList = [
  1,
  /* ...lines of numbers between 2-29... */
  30,
];
```

**Comment by thorn0** [comment] 2021-01-22 15:37
duplicate of #4210

**Closed by thorn0** 2021-01-22 15:37 UTC
