### ISSUE TITLE
How can I solve this problem：CssSyntaxError: <css input>:5:12: Unknown word

### ISSUE THREAD

**Issue by birdycn** [prettier/prettier#10825] opened 2021-05-06 05:00 UTC
index.less：
```
.@{ant-prefix}-form-item-label > label {
            height: unset;
}
```

Unable to use formatting：
```
["ERROR" - 下午12:23:32] Error formatting document.
CssSyntaxError: <css input>:5:12: Unknown word
    at Input.error (\node_modules\postcss\lib\input.es6:108:16)
```

**Comment by fisker** [comment] 2021-05-06 06:53
Duplicate of #10826

**Closed by fisker** 2021-05-06 06:53 UTC
