### ISSUE TITLE
Brackets omitted for multi line arrow function with JSX

### ISSUE THREAD

**Issue by matej-prokop** [prettier/prettier#2399] opened 2017-07-05 09:53 UTC
```
const SvgIcon = ({ icon, onHoverIcon, alt }) => (
	<div className="svg-icon-wrapper">
		<Image className="non-hovered-icon" src={icon} alt={alt} />
		<Image className="on-hover-icon" src={onHoverIcon} alt={alt} />
	</div>
);
```
Becomes
```
const SvgIcon = ({ icon, onHoverIcon, alt }) =>
	<div className="svg-icon-wrapper">
		<Image className="non-hovered-icon" src={icon} alt={alt} />
		<Image className="on-hover-icon" src={onHoverIcon} alt={alt} />
	</div>;
```

I believe that brackets surrounding body of arrow function show be in output.

**Comment by SimenB** [comment] 2017-07-05 10:04
#2398

**Comment by azz** [comment] 2017-07-05 11:24
Thanks for the report. Closing as a duplicate of #2208, with PR #2398 WIP as @SimenB mentioned.

**Closed by azz** 2017-07-05 11:24 UTC
