### ISSUE TITLE
a method chain is output too long

### ISSUE THREAD

**Issue by brodybits** [prettier/prettier#10398] opened 2021-02-23 17:51 UTC
based on <https://github.com/prettier/prettier/issues/2482#issuecomment-767807626>:

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbCHNez3f8EZQDmAjABQCUAOlAAR0B06hrb7+JATFbSADQgIABxgBLaAGdkoAIYAneRADuABQUJpKWamWyAntMEAjebLABrODADKw82JLIY8gK5xBcALbG4AEz9-ABlZEldZYjgAMQh5L1kYcSdtVxgIARAACxgvVAB1TLF4SXswOBtNIrEANyL9ZHBJIxBHSTh5GFUzYnjkADMdNsEAK0kADwAhM0trG1kvOCDHOH7BjxBRsZtHYlQ4AEVXCHhV1CGQe3k2+QbjWV9UDOF5Rxg8sT8YTOQADgAGQTPCBtPJmYQNZ5wa7VFaCACOR3gXREWhAskkAFooHB-P4MvI4AixASuhFekgBmd1m0vGJnG5qTs9odjisKWtBDB7u9Pt8kFxOWYxKgdgBhCBeckgKEAVgyrjaABV7lpKedqu4AJJQQKwGxgF6iACCOpsMH0e1ObQAvtagA)

```sh
--parser babel
```

**Input:**

```jsx
looooooooooooooooooooooooooooooooooooooooooooooooooooooooong1()
  .loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong2()

```

**Output:**

```jsx
looooooooooooooooooooooooooooooooooooooooooooooooooooooooong1().loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong2();

```

**Expected behavior:**

I think this one should be on separate lines, like this for example:

```js
looooooooooooooooooooooooooooooooooooooooooooooooooooooooong1()
  .loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong2()
```

**Comment by fisker** [comment] 2021-02-23 17:54
I agree we should break it, but this code is really not a real world case...

**Comment by thorn0** [comment] 2021-02-23 18:22
Duplicate of #2548

**Closed** 2021-02-23 18:22 UTC
Labels: type:duplicate
