### ISSUE TITLE
Multi-line concatted strings being double indented

### ISSUE THREAD

**Issue by geuis** [prettier/prettier#2235] opened 2017-06-22 21:49 UTC
I have some function calls that are structured like this:

```
exec(
  'One line\n' + 
  'Two lines\n' +
  'Three lines' + 
  'Four lines more'
);
```

Prettier formats them like this:

```
exec(
  'One line\n' + 
    'Two lines\n' +
    'Three lines' + 
    'Four lines more'
);
```

Are there any specific settings where I can change this behavior?

**Comment by azz** [comment] 2017-06-23 09:00
This is by design. See here: https://github.com/prettier/prettier/issues/2209#issuecomment-309929479

There is no setting to change this behavior.

**Comment by geuis** [comment] 2017-06-23 18:27
I see this as either a bug or poor style choice. Vertical alignment is important for readability. No reason I can imagine to forcefully indent the extra lines.

**Comment by simonkberg** [comment] 2017-06-25 12:22
> No reason I can imagine to forcefully indent the extra lines.

I hadn't seen this formatting before i started using prettier, but I've come to appreciate it a lot. In your example it makes it clear that this is one argument that is a multi-line concatenated string, as opposed to four strings as separate arguments. It (imo) gets completely unreadable if there are any trailing arguments after the string in the example.

There's no extra indention as long as the intention is unambiguous. [example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22var%20lisum%20%3D%20'Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetur%20adipiscing%20elit.%20Maecenas%20gravida%20'%2B%5Cn%20%20%20%20'interdum%20mattis.%20Praesent%20ultrices%2C%20ipsum%20et%20eleifend%20gravida%2C%20purus%20nisi%20'%2B%5Cn%20%20%20%20'dictum%20risus%2C%20ut%20lobortis%20risus%20sapien%20nec%20quam.%20Nulla%20facilisi.%20Mauris%20'%2B%5Cn%20%20%20%20'pretium%20tortor%20ut%20augue%20pulvinar%20euismod.%20Proin%20vel%20arcu%20euismod'%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by vjeux** [comment] 2017-06-27 17:31
This is actually intended as @simonkberg mentioned. I'm going to close this issue, thanks for reporting it!

**Closed by vjeux** 2017-06-27 17:31 UTC

**Comment by geuis** [comment] 2017-06-28 04:52
I don't see why this issue is being closed. That formatting rule is fine for an argument followed by a new one on a new line. The same doesn't apply to string concatenations.

**Comment by taylorham** [comment] 2017-07-26 19:23
I also think this is an odd style choice and worth leaving open to discussion. If the object is to be clear about concatenations vs other arguments, then why not use leading `+`s?

```js
exec(
  'One line\n'
  + 'Two lines\n'
  + 'Three lines\n'
  + 'Four lines'
)
```

This seems far more intuitive to me; preserving indentation while also being starkly clear about concatenation, without muddling a possible extra argument after the string.

**Comment by aboyton** [comment] 2017-07-27 00:37
The reason it intents it is to make it clearer when you have multiple arguments to a function.

```js
exec(
  'One line\n' + 
  'Two lines\n',
  'Three lines' + 
  'Four lines more'
);
```
compared to
```js
exec(
  'One line\n' + 
    'Two lines\n',
  'Three lines' + 
    'Four lines more'
);
```

**Comment by taylorham** [comment] 2017-07-27 00:48
I understand that reasoning, but I still believe a leading `+` would solve the issue much more elegantly/efficiently.

I've personally never seen anyone hand-write code with indented string concats, but the leading `+` is a very common occurrence.

Just wondering if there's ever been discussion about this (double indentation vs leading `+`), and if not, to see if we can talk it through and come to a... *ahem*... **prettier** solution.
