### ISSUE TITLE
Typescript: Trailing comma on final parameter missing when `...` used with object destructuring

### ISSUE THREAD

**Issue by alantreadway** [prettier/prettier#4402] opened 2018-04-30 18:36 UTC
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAMwFcowYBLaPeAZxgDFy0Yjs4AKAHSjz2G9684ANwQwAcgEMAtnDwBePAB4A5AFkA8gBEAkvQCaKgD4qtAUQAyZgCpmVAPjzrtewwBoBgkWIDKEVmBwAIIASuIKhJIA1nDYAHTksLFQcDBxrAA27ACUHjx4AL4RwAV5vHEVbJDYACY0SHwFANoAutzZDWaisHyeAPR9eFoQeDQQsngY2BCBNDSJAObcBdwgbiAQGBTQNMigktjTAO4ACgcIuyiSwhDkNWsgAEbYkmAxMD4Yr4vIMNhEcHWiRosRgJxeC2kkmQBEkGRB6wAVjQ0AAhF5vVI+GRwCyJOAwuEIkBfbAg7DIEAwACeGDgNDA2HIWweU0SMAA6ncYAALZAADgADOsphAQRyXhhKVN6bFRA82ABHIjkNjgySQ6FIWHwwEgEHSci-f56+ZQBYZOAARSIEHghN16xgkkeXJqvOQACYnS9yBlFgBhcZQylwjIPIgg6wuy46kEFApAA)
```sh
--parser typescript
--trailing-comma all
```

**Input:**
```tsx
export function testFixture(
  {
    eventName = <'MODIFY'|'DELETE'> 'MODIFY',
    eventSourceARN = faker.internet.url(),
  } = {},
  ...records: {}[]
): Event {
  // Do some processing
}

```

**Output:**
```tsx
export function testFixture(
  {
    eventName = <"MODIFY" | "DELETE">"MODIFY",
    eventSourceARN = faker.internet.url(),
  } = {},
  ...records: {}[]
): Event {
  // Do some processing
}

```

**Expected behaviour:**
```tsx
export function testFixture(
  {
    eventName = <"MODIFY" | "DELETE">"MODIFY",
    eventSourceARN = faker.internet.url(),
  } = {},
  ...records: {}[],
): Event {
  // Do some processing
}
```

**Comment by duailibe** [comment] 2018-04-30 19:01
This is intended behavior, to align with the spec https://github.com/tc39/proposal-object-rest-spread/issues/47 even though TypeScript allows it. Shouldn't make a difference since you can't have another argument after it anyway,  you won't have any "diff issues" (which is the whole point of having trailing commas).

Duplicate of #3673

**Closed by duailibe** 2018-04-30 19:01 UTC

**Comment by bakkot** [comment] 2018-04-30 19:04
(@duailibe, technically this is about [function trailing commas](https://github.com/tc39/proposal-trailing-function-commas), not object-rest-spread, but it's the same deal.)
 
Incidentally, TypeScript [will disallow this syntax](https://github.com/Microsoft/TypeScript/pull/22262) next time a release is cut from master.

**Comment by j-f1** [comment] 2018-04-30 19:07
Duplicate of #3673

**Comment by duailibe** [comment] 2018-04-30 19:08
@bakkot Thank you, I had another issue opened, last minute I realized it was about objects and forgot to fix the link to the spec. I removed it anyways
