### ISSUE TITLE
Prettier.io : AST Manipulation (Parser & Print Samples)

### ISSUE THREAD

**Issue by gitmaruthi** [prettier/prettier#9233] opened 2020-09-18 22:00 UTC
Guys, 

I am trying to use Prettier.io for Salesforce LWC Parser, and I was unable to find syntax/samples for Parser and Print functions. I am able to Format the code for LWC - wondering if someone can guide me. I am using Prettier.io in a web page through CDN links.

1. How do I **generate AST for my HTML code**? I was able to generate it using **prettier.__debug.parse** but it is generating a very huge AST structure (I believe I can setup options to ignore data that I don't need, like start range and so on)? **Are there any samples OR what is the correct syntax to do this?**

2. How do I **Convert the AST back to HTML code** - how can I use the **Print function**? **Are there any samples OR what is the correct syntax to do this?**

Thanks in advance.

**Comment by evilebottnawi** [comment] 2020-09-19 14:10
Duplicate of #5998

**Closed by evilebottnawi** 2020-09-19 14:10 UTC

**Comment by gitmaruthi** [comment] 2020-09-19 16:53
@evilebottnawi I don't think my question was a duplicate of #5998, as I was trying to do something different. May be no one has tried what I did, in which case, we should leave it as Open than marking it as duplicate?

**Comment by evilebottnawi** [comment] 2020-09-21 12:53
@gitmaruthi prettier doesn't work with AST right now, so it is duplicate
