### ISSUE TITLE
Print width not respected in var declarations

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier#2528] opened 2017-07-21 11:14 UTC
With print width set to 100, the following remains untouched:

```javascript
const bookingCreateFunctionalTests = require('../../tsp-providers/citybikes/booking-create-functional-tests');
```

While it's expected to have it fixed into:

```javascript
const bookingCreateFunctionalTests =
  require('../../tsp-providers/citybikes/booking-create-functional-tests');
```

**Comment by bakkot** [comment] 2017-07-21 17:53
Duplicate of #1732 (and/or #2482).

**Closed by bakkot** 2017-07-21 17:53 UTC
