### ISSUE TITLE
[Feature Request] Same AST, same output?

### ISSUE THREAD

**Issue by loynoir** [prettier/prettier#11429] opened 2021-09-01 00:59 UTC
### Feature Request
Are there any prettier CLI flags, or prettier config, 
- If two file are ast logic same, generated 100% same output?

Just kind of like `terser -> prettier`.

### Reproduce
```sh
$ tail a.js b.js 
==> a.js <==
const a = 1
const b = 1

==> b.js <==
const a = 1



const b = 1
```

### Actual
```sh
$ prettier a.js 
const a = 1;
const b = 1;
$ prettier b.js 
const a = 1;

const b = 1;
```

### Expected
```sh
$ prettier a.js 
const a = 1;
const b = 1;
$ prettier b.js 
const a = 1;
const b = 1;
```

**Comment by kachkaev** [comment] 2021-09-01 07:39
Duplicate of https://github.com/prettier/prettier/issues/2068

**Comment by alexander-akait** [comment] 2021-09-01 09:45
Yep

**Closed by alexander-akait** 2021-09-01 09:45 UTC
