### ISSUE TITLE
TypeScript generics are removed incorrectly

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#5817] opened 2019-01-30 14:57 UTC
**Prettier 1.16.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9gAdKPPSiUggHgGkAaPAFQD4AFAGskebnhhjeASjx0GeWjGxwY5bA2DCeMAL4Bueoz309ILiAgYYAS2gBnZKFLZsEAO4AFVwicpSADcIWwILEAAjbFIwYTUAZQwY2ygAc2QVcjhLAAsYAFtKAHUc23gHJLA4eL8y20CygE9kcAcnSxSHOFwvaNT80mQySi7LACsHNAAhaNiE0ny4ABkUuCHSEeyQCbR4lNTKOABFcgh4dc3LJOwu7BaYRow4BzBsWxtwjDfYItCYHOQAA4AAxXdxdIrRDAtL7PbqBNaWVQAR3ItlUvVI-UGSGGoxAXXytgy2Cylgc+0OJzOa1xG3xMFIEV+BH+yAATJYVKRbJR9gBhCD5AYtKDQREgchdXhM-x4uB6PRAA)

```sh
--parser typescript
```

**Input:**
``` ts
export default {
  load<K, T>(k: K, t: T) {
  	return {k, t};
  }
}
```

**Output:**
``` ts
export default {
  load(k: K, t: T) {
    return { k, t };
  }
};
```

**Expected behavior:**
preserve TypeScript generics

**Comment by ikatyang** [comment] 2019-01-30 15:00
Regression from #5799.

cc @JamesHenry

**Comment by ikatyang** [comment] 2019-02-01 13:36
Yeah, we probably just need to fix this missing case. It's still the updated version (the OP can be reproduced) on master as I only reverted it in the 1.16 branch.

**Comment by j-f1** [comment] 2019-02-02 12:51
This is because the parser puts the `typeParamaters` on the `Property` node rather than the `FunctionExpression`.

**Comment by Jessidhia** [comment] 2019-02-02 13:10
That sounds like a parser bug to me; it's not otherwise possible to have any kind of generics on properties 🤔

But if it works...

**Comment by JamesHenry** [comment] 2019-02-02 13:57
@j-f1 Did you not see this? https://github.com/prettier/prettier/issues/5817#issuecomment-459721349

**Comment by j-f1** [comment] 2019-02-02 14:17
Should I close this PR then?

**Comment by JamesHenry** [comment] 2019-02-02 14:20
No, it's the same solution, but obviously want to avoid situations where multiple people are doing the same work

**Comment by armano2** [comment] 2019-02-04 22:58
looks like there is few more issues here:
```
export class {
  constructor<T, X, F>(k: K, t: T) {
  	return {k, t};
  }
}
```

**Comment by JamesHenry** [comment] 2019-02-04 23:53
Oh wow, merging the PR on the other repo caused this issue to be closed. I'm guessing it piggybacked my permissions on both repos?

**Comment by j-f1** [comment] 2019-02-05 13:34
Yeah, that’s one of the features of GitHub that comes in handy every so often.

**Comment by brodybits** [comment] 2019-04-04 20:28
I think this issue is now resolved by PR #6027 (TS 3.4 update which includes `@typescript-eslint/typescript-estree` version `1.6.0`).

**Comment by evilebottnawi** [comment] 2019-04-04 20:31
I think we need merge test before close this to avoid regressions in future

**Comment by brodybits** [comment] 2019-04-04 20:41
> I think we need merge test before close this to avoid regressions in future

The commit I proposed in PR #5989 should automatically close this issue as resolved and tested.

Thanks @evilebottnawi for your attention:)

**Closed** 2019-04-08 19:57 UTC
Labels: lang:typescript, priority:high, status:has pr, type:bug
