### ISSUE TITLE
<form> <input> </form> issue

### ISSUE THREAD

**Issue by zacqed** [prettier/prettier#9235] opened 2020-09-20 07:37 UTC
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAZhATgWwAQCGYMAltALwD0RkArrCVAOYIxYlwDOlADhJzErBgAazgBPAL6S8OODAAWEACbkAOiD4CNeBMXE846kDloAbUjwJZBmXAFplBGAQ0A+NVFSMetGB6g8PFRKOxw3EAAaEAgeUmhOZFBrLAgAdwAFawRElAIANwgSZSiQACMsIjEYAGUrMEYmZDZaOGi4HDK4ZWVugBkCZloCFgAxbBxnUmZkEAI-CFKFGBwzAHUFEnhOerganK2SfK3xWbBOROjGTjgbDMqmSeR0AjMb6IArTgAPACFKsDVGoEOR9RhwZ6vd4gL7fGqNMxwACKtAg8EhbzammsNyws2Wq1KPHYsDWxUUyAAHAAGaLE-hwNaVHizYlcW75CHRACOqPg91iuTmnHsUDg3W6pSwcF5JGl9xGTyQL0x0RuOBIzSwrTVCORfIhyqhWJcZTJygpSAATNE2AQSGZGgBhCA4JUgKDQLkgWg3AAqBDKuRV0PyrQAklBerAamB2HEAIJRmowcSIjE3aRAA)
```sh
--arrow-parens avoid
--parser html
--trailing-comma none
```

**Input:**
```html
<form action=/accountingentries/post/{{key}} method="post" enctype="multipart/form-data">
<input>
  </form>
```

**Output:**
```html
SyntaxError: Unexpected closing tag "form". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (3:3)
  1 | <form action=/accountingentries/post/{{key}} method="post" enctype="multipart/form-data">
  2 | <input>
> 3 |   </form>
    |   ^
```

**Expected behavior:**

**Comment by thorn0** [comment] 2020-09-20 15:18
Duplicate of #8210

**Closed by thorn0** 2020-09-20 15:18 UTC
