### ISSUE TITLE
Put single line template literal on the next line

### ISSUE THREAD

**Issue by IvanGoncharov** [prettier/prettier#5026] opened 2018-08-29 15:23 UTC
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAbaBzAZRgCcBGTAXkwB0QA3OYgTwDVHX23muPvP++g3sIAy+IsQCWUPLQDc1KJCgYc4kgCZKmAAYMhPQwOFGDxnmJkTpeHXJAAaEBAAOMSemSgAhsWIQAdwAFXwQ0ZBBvOghJABNHEAAjYm8wAGs4GAIXVJtkEgBXOCdpNEYYIJS8AFtvZAAzb2wypwArNAAPACEU9MyCb2q4EWk4BqaWkBziMuIIxO9EplwoBJcpWAB1OJgAC2QADgAGJ3WIMs2Ulwj1uFmGBOI4AEcCySfK7xq6pEbm4pAZWqknyxCKTjQNmwcAAigUIPBxv8nDBFttYntkBoUSlJNgbABhCDVWoRKDQMZOAplAAqi3CvwmcAAvsygA)
```sh
--parser babylon
```

**Input:**
```jsx
const longStr1 = "veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString";
const longStr2 = `veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString`;
```

**Output:**
```jsx
const longStr1 =
  "veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString";
const longStr2 = `veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongString`;

```

**Expected behavior:**
Same behavior for both strings.

**Comment by lydell** [comment] 2018-08-29 15:44
Duplicate of #2889

**Closed by lydell** 2018-08-29 15:44 UTC
