### ISSUE TITLE
Prettier incorrect format comments in array

### ISSUE THREAD

**Issue by B2o5T** [prettier/prettier#12357] opened 2022-02-23 23:57 UTC
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtA9AKkwDMBLAJw031wBpM05IoATAXUwF5iIIQaQIABxgl0yUAEMyZCAHcAClIRpkICQBtZEgJ4r+AIzISwAazgwAyhIC2cADIkocZEQ0MDR0+YuDjjgObIMGQArnD8cNb6cMzMMXYSUP4hEv5wAGIQZNYSMCJJqhIhMLz8ABYw1uoA6mUk8Gi+YHAWyvUkAG712qpgaHogjgxkMPJG-jkubuEgAFZoAB4WAepwAIohEPBT6u4gvhRwZKr6EtHqfPtkjjDVJMwwZcgAHAAM-IIyDNVGgqqfcGGHWc-AAjpt4GMhCoUBI0ABaJwxGKXMhwcHkOBjVKTJCuXYzBjWEhBUKElbrCHOPHTfgwM53B5PJAAJjpRhI6gCAGEINZcSBAQBWS4hBgAFTOMPxew6YQAkiwEJYwNdhABBFgWGDaVY7BgAXwNQA)

```sh
--parser babel
```

**Input:**

```jsx
const [/* first */, second] = foo
```

**Output:**

```jsx
const [, /* first */ second] = foo;

```

**Expected behavior:**

same as input

**Comment by fisker** [comment] 2022-02-24 01:33
This is known issue, related #1013

**Comment by fisker** [comment] 2023-01-29 22:22
Duplicate of #1013

**Closed** 2023-01-29 22:22 UTC
Labels: type:bug, type:duplicate, lang:javascript
