### ISSUE TITLE
Prettier not breaking line on .'s when variable names are long

### ISSUE THREAD

**Issue by campbebj** [prettier/prettier#8916] opened 2020-08-05 16:59 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VAzAlgJwM4wAEcAHgIYC2ADgDZwA6sAFlngHQ3QDmAamTljIAjOgDlKcAKIl4UACZw5AFQgBlJhADuABRwQRcCo0KEO3PgOFiJ02QuVqNOvQYoAhOGDIBXPHACSMADCZFAA4nAwAEpwZDQ0AJ6qWPEJbKpwAhC+iUoseP54ACLeFEIAFIwAlADcjIzofpDyxOTUdIzNBIScULz8ggbiFHBIPdxKCVRww3CEALyExoRkmmRYRDD5Zn0Wg9Yjtgj2KnhOuvp0FGwjWxByIfF5ZDCFAIJ4CVBg5bX1UCAADQgCBUGBYaB4ZCgfh6HT8BBQlBxNYJKHAoQ4MhgADWkVUVGxWD6yBgOG8cGBTBgFBoAHUWPA8ISwHAMlA8BssAA3DYJZDgPDokDEvw4GC6MhcChkZAYOJ+YEAKzwJDcWNx+IkABliXA5QrKSAVSRkn06ABFbwQeAGmiKkCE-CZAUwKZwPBgARgoGOgSwOlYORbZAARgADOHgVQ9H46ViqAKYx7Mtz9cCAI7W+AXKhIkBkPAAWigcEUil9ODgWdwcEl0tlSHl9qNfgoWFJ5NbxK4luz+qbhuBMGEgeDTGQACZh1iUj2ghAKDKBR6AKy+3xwJTCJHNh3cin+eQIGCqL1YMFveSqN10O1+AC+D6AA)
```sh
--parser typescript
--print-width 100
```

**Input:**
```tsx
//first example
this.longVariableNameExtendedToShowProblem
  .longVariableNameExtendedToShowProblemBecauseItCanGetReallySilly.SeriouslyThisIsDumb(
);

//second example
const longVariableName: longTypeName = 
  await this.longVariableNameExtendedToshowProblem.methodCallThatIsAsync();
```

**Output:**
```tsx
//first example
this.longVariableNameExtendedToShowProblem.longVariableNameExtendedToShowProblemBecauseItCanGetReallySilly.SeriouslyThisIsDumb();

//second example
const longVariableName: longTypeName = await this.longVariableNameExtendedToshowProblem.methodCallThatIsAsync();
```

**Expected behavior:**
Expecting prettier to break the line at some point on one of the .'s or the = sign
Since prettier keeps unbreaking the line it conflicts with line length limitations.

**Comment by evilebottnawi** [comment] 2020-08-05 17:09
Duplicate of #2482

**Closed by evilebottnawi** 2020-08-05 17:09 UTC

**Comment by evilebottnawi** [comment] 2020-08-05 17:10
And partial this https://github.com/prettier/prettier/issues/8003

**Comment by evilebottnawi** [comment] 2020-08-05 17:10
Please use search before post an issue, most of problems already were reported
