### ISSUE TITLE
space and slash for single tags

### ISSUE THREAD

**Issue by Prodnik** [prettier/prettier#13633] opened 2022-10-13 19:07 UTC
![image](https://user-images.githubusercontent.com/36890055/195686852-9d3f96cc-be7a-46b4-a38f-d8daf4947a6f.png)
There is a problem, it adds a space and a slash for single tags. How can this be fixed?

**Comment by thorn0** [comment] 2022-10-13 21:27
Why is this a problem?

**Comment by ExE-Boss** [comment] 2022-10-30 00:07
Duplicate of <https://github.com/prettier/prettier/issues/5246>

**Comment by fisker** [comment] 2022-10-30 02:45
Duplicate of #5246

**Closed** 2022-10-30 03:20 UTC
Labels: type:duplicate, status:awaiting response
