### ISSUE TITLE
Line length exceeds max-width when using template literals

### ISSUE THREAD

**Issue by fortes** [prettier/prettier#2631] opened 2017-08-16 18:09 UTC
Input:

```js
reallyLongNameThatIsQuiteLong = `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`;
```

Ouptut is unchanged. Repro here: https://prettier.io/playground/#%7B%22content%22%3A%22reallyLongNameThatIsQuiteLong%20%3D%20%60aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa%60%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

Happens with typescript, flow, and babylon parsers. Does not happen when using single quotes.

**Comment by azz** [comment] 2017-08-17 12:38
This is a duplicate of #2482

**Closed by azz** 2017-08-17 12:38 UTC
