### ISSUE TITLE
Promise then on different line if content too long

### ISSUE THREAD

**Issue by Mikaleb** [prettier/prettier#10669] opened 2021-04-09 15:00 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEANhAIYAmAiuhDCQBQCU+wAOlPh5zABY4DOAOgDmcGFRok+dYPgD6OMknw9+A9HzgAnAZAC2ABxJQAngEkyA+WXwBfBm06P8AngjoBHarT74AvAD5lXkFPCR9ffFDvBgBuB04bEAAaEAh9XGg+ZFASTU0IAHcABVyELJQSQgKSYyyUgCNNEjAAa1EAZUMwHCghZBhNdDgUuF16uDIyCYAZIyF0EhEAMQhNXRIYXF7kEBJ0GAhkkG4YXUIAdV54Pi64drKcXAA3R+MdsD46kB6NTRgippCdbIVCVDQpABWfAAHgAhJqtDokXRwaY9OAgsHDEBQ6HtHpCQhwcTwTGEcEgQyaX47eokcaEI76TQ9GDnBQ8ZAADgADClmRANOcmvodsy4L8nhiUlE4AC0uVdnwALRQOATCZHTRwTw4bUAxbApCg8nYjS6HD9QZmglEkkY41YlK0erssicpAAJmdTRwhAJAGEILojSAJQBWI7qOAAFXp5RNFKeQ1MUCmsHaYBZ6QAgmn2jBjESyRobDYgA)

```sh
--parser babel
```

**Input:**

```jsx
function loadQuota() {
      this.getQuotas({ _id: this.user.companyId._id })
        .then(quotas => this.quotas = quotas);
    }
```

**Output:**

```jsx
function loadQuota() {
  this.getQuotas({ _id: this.user.companyId._id }).then(
    (quotas) => (this.quotas = quotas)
  );
}

```

**Expected behavior:**

Same output as input

**Comment by thorn0** [comment] 2021-04-09 15:04
Duplicate of #5931

**Closed** 2021-04-09 15:05 UTC
Labels: type:duplicate
