### ISSUE TITLE
Comment in last line of YAML files gets leading newline trimmed

### ISSUE THREAD

**Issue by TheDevMinerTV** [prettier/prettier#16206] opened 2024-04-05 09:45 UTC
**Prettier 3.2.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKBDJACAcgKywGI8sQAaECABxgEtoBnZUbAJ04gHcAFLgjYpsAG17YAnmxoAjTtjABrODADK2ALZwAMoyhxkAM3Es48xSrXq6SgwHNkMTgFcLIc1sbO3HuAAedHCcjDqw4gAqITihcCKmYuY0LI5icACKrhDwJmYeAFYsAeppmdm5SInJIACOFXD8PHQiINgsqIZwACY91CAu2IxijgDCEFpa2MhtYmL9qVAO6QCCMC6Mcq7w-CH6hnlJHgAWMFpiAOrHjPAsdmBw6sI3jABuN1IzYCyyIK-uAEkoL1YOowKEGCtgeoYFJ0ocanQeOYLoo6DMkfEQq8jDQDOZODAmtgHFMER47JwCTMpNp5jQkQYYBdGN0YMdkAAOAAMNE4cHqjH5xNJ0yq+RoMGwchZbI5SAATDRXOZItKEhKQHAtHIer1urpsEtXCS4AAxCCcKbrRwzbDbCAgAC+TqAA)

```sh
--parser yaml
```

**Input:**

```yaml
---
a: ''

# 
```

**Output:**

```yaml
---
a: ""
#
```

**Expected output:**

```yaml
a: ""

#
```

**Why?**

If there's any other line after the comment it doesn't get touched. If the comment is the last line in a file, it gets the previous newline removed for some reason.

**Comment by sosukesuzuki** [comment] 2024-04-06 09:03
Thanks for the report. This should be consistent in behavior between last and non-last comments.

**Comment by MindTooth** [comment] 2024-06-22 10:23
Been like this for at least three year: https://github.com/prettier/prettier/issues/10922

**Comment by kachkaev** [comment] 2024-06-23 11:56
@MindTooth you are correct. Closing as duplicate of https://github.com/prettier/prettier/issues/10922.

**Closed by kachkaev** 2024-06-23 11:56 UTC
Labels: type:bug, lang:yaml
