### ISSUE TITLE
TypeScript: Problematic indentation of chained conditional types.

### ISSUE THREAD

**Issue by joelday** [prettier/prettier#4793] opened 2018-07-02 14:07 UTC
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwDkIATOAFWLgB4a914pKBncquAaQEt2APjwBeADpQ80vM1YJO3agPYA6AEIQIAGwAy-eNgCG2vAH48mnfsMmK1PEkkzZLNG0X2+gyqoDCAK4cMBAAtgCiAG4IMAAicABmggb80OZ4gcFhUTHxSVAp0F6OzjJy7gpcXiq+ObDpdTDFTlJlbh5VPDWqjXnJMKlSFr2J-YPNpdLlHUreao0AEnBG1NgN0bBLK3DYE61T7ZWz3QBi2kYA5ulnl3su00fVPqpnEEYwNjsm19pvHwZfbR3NrydidZTPE4BKBgAbQPoFOFDPBQmFIhGFKDA6ReADyACMAFZwWEMJ7CADcIAANCAIBgkRxkKAjNhsBAAO4ABVZCCZKCMkQg-EoNJA+OMYAA1nAYABlDBGMCCC7IGDYAJwWmCDg7GBc4wXUJGZAJEy62mEjhodSSmXyoyhOD6KBwU3mrUgRXYXXYZAgIgkDhgbD8BlijCh2AAdRFMAAFsgABwABlpkYguujxgw-sjcF90TF2DgAEcAvwSwbLsb3doLSBdaF+GqNZ6OCrtHAAIoBCDwOsNmBGfGxygJ5AAJlp6qM-G0Kr8YVrKCg0DdtKCtBH-LN9bgAF8D0A)
```sh
--parser typescript
```

**Input:**
```tsx
export type NodeType<T extends NodeKind> =
    T extends NodeKind.BoolLiteral ? BoolLiteralNode :
    T extends NodeKind.CustomEventDefinition ? CustomEventDefinitionNode :
    T extends NodeKind.Event ? EventNode :
    T extends NodeKind.EventDefinition ? EventDefinitionNode :
    T extends NodeKind.EventHeader ? EventHeaderNode :
    T extends NodeKind.Flag ? FlagNode :
    T extends NodeKind.FloatLiteral ? FloatLiteralNode :
    T extends NodeKind.FunctionDefinition ? FunctionDefinitionNode :
    NodeObject<NodeKind>;
```

**Output:**
```tsx
export type NodeType<T extends NodeKind> = T extends NodeKind.BoolLiteral
  ? BoolLiteralNode
  : T extends NodeKind.CustomEventDefinition
    ? CustomEventDefinitionNode
    : T extends NodeKind.Event
      ? EventNode
      : T extends NodeKind.EventDefinition
        ? EventDefinitionNode
        : T extends NodeKind.EventHeader
          ? EventHeaderNode
          : T extends NodeKind.Flag
            ? FlagNode
            : T extends NodeKind.FloatLiteral
              ? FloatLiteralNode
              : T extends NodeKind.FunctionDefinition
                ? FunctionDefinitionNode
                : NodeObject<NodeKind>;

```

**Expected behavior:**
No opinion on operator placement, but I'd prefer for these to not be indented. This is especially problematic once the indentation causes lines to exceed your linter's max line length. I understand that this is a special case for otherwise correct ternary formatting, but I hope an exception is made here.

Here's is a similar pattern currently supported by Prettier that I imagine this should be consistent with:

```tsx
export type LiteralNode =
    | NoneLiteralNode
    | FloatLiteralNode
    | HexLiteralNode
    | StringLiteralNode
    | BoolLiteralNode
    | IntLiteralNode;
```

**Comment by ikatyang** [comment] 2018-07-02 14:18
Hi, this looks like a duplicate of #737, let's track the issue there.

**Comment by ikatyang** [comment] 2018-07-02 14:18
Duplicate of #737

**Closed by ikatyang** 2018-07-02 14:18 UTC

**Comment by joelday** [comment] 2018-07-02 14:20
@ikatyang Thanks. Hopefully if there is no consensus on changing this for ternaries entirely, this will still be considered in this specific case. Thanks!
