### ISSUE TITLE
Lists aren't indented properly when tabSize != 2

### ISSUE THREAD

**Issue by deadalnix** [prettier/prettier#11718] opened 2021-10-25 13:00 UTC
The markdown formatter does very strange things when indenting lists with tabSize different than two. More specifically, it put the indentation in between the list marker and the text rather than before the list marker. This is important because some markdown rendered expect tabSize to be at least 4. As pointed out in #3679 for instance, this is the case for BitBucket.

**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAVAFgSwM4AIe4CGuANjjEgDpQC0uAZpgE7Yz7wC2+UuM6cpctTrY4kKABN2cLph58BZVsN5YmUzJ26rFQqCAA0ICAAcYmaNmShCTJhADuABVsIrKQgDcImCYZAARkyEYADWcDAAyoQccAAycnDI9IQkokZBIeFRJiFyAObIMEwArnBGMgFwEhLVcYRQ+SWE+XAAYhBMHIQw5o3IIIQlMBD+6DAcJADqWPDYuWBwkW6amJ6aAJ4DYNhWRnKiTDBOwfndyanpIABW2AAekQUkcACKJRDwF2nlILkscEwBt0mKEJI59EYTEw5DApr4+MgABwABkh9lEU2CJgGqQchA2exAAEd3vATqZ3INsDQoHBqtV-Ew4CTmHATi1zkgUt8jKIOJgiqUftgnq9SUkuZcfjBCAE4RIEUgACxGYqETBkRoAYQgHE5ICg0CSRhKolQsvc3KunjKAElJAgomBoWYAIKSSIwDbPL5XQisX0-MFgQNGW53ABCwTCEWisQStNDxmGJmGACZAwBfTNAA)

**Input:**

```markdown
This is a list:
- first item in the list
- second item in the list
- third item in the list
```

**Output:**

```markdown
This is a list:

-   first item in the list
-   second item in the list
-   third item in the list
```

**Expected behavior:**

```markdown
This is a list:

  - first item in the list
  - second item in the list
  - third item in the list
```

**Comment by Nuc1eoN** [comment] 2022-02-07 19:33
Oh! And I thought is was intentional!

Now I have noticed even other strange behaviour, consider this:
**Input:**
```
This is an ordered list:

1. first item in the list
2. second item in the list
3. third item in the list
```
Output:
```
This is an ordered list:

1. first item in the list
2. second item in the list
3. third item in the list
```
**However** if the first item it indented with two spaces:
**Input:**
```
This is an ordered list:

1.  first item in the list
2. second item in the list
3. third item in the list
```
The **output** will be:
```
This is an ordered list:

1.  first item in the list
2.  second item in the list
3.  third item in the list
```
If you make three spaces, it will go back to two spaces.

If you make five spaces, weird things will happen too. Prettier will simply move the paragraph one character to the right, each time you format (can be done endlessly)!!

**Comment by haoadoresorange** [comment] 2022-02-23 02:19
> The markdown formatter does very strange things when indenting lists with tabSize different than two. More specifically, it put the indentation in between the list marker and the text rather than before the list marker. This is important because some markdown rendered expect tabSize to be at least 4. As pointed out in #3679 for instance, this is the case for BitBucket.
> 
> **Prettier 2.4.1** [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAVAFgSwM4AIe4CGuANjjEgDpQC0uAZpgE7Yz7wC2+UuM6cpctTrY4kKABN2cLph58BZVsN5YmUzJ26rFQqCAA0ICAAcYmaNmShCTJhADuABVsIrKQgDcImCYZAARkyEYADWcDAAyoQccAAycnDI9IQkokZBIeFRJiFyAObIMEwArnBGMgFwEhLVcYRQ+SWE+XAAYhBMHIQw5o3IIIQlMBD+6DAcJADqWPDYuWBwkW6amJ6aAJ4DYNhWRnKiTDBOwfndyanpIABW2AAekQUkcACKJRDwF2nlILkscEwBt0mKEJI59EYTEw5DApr4+MgABwABkh9lEU2CJgGqQchA2exAAEd3vATqZ3INsDQoHBqtV-Ew4CTmHATi1zkgUt8jKIOJgiqUftgnq9SUkuZcfjBCAE4RIEUgACxGYqETBkRoAYQgHE5ICg0CSRhKolQsvc3KunjKAElJAgomBoWYAIKSSIwDbPL5XQisX0-MFgQNGW53ABCwTCEWisQStNDxmGJmGACZAwBfTNAA)
> 
> **Input:**
> 
> ```gfm
> This is a list:
> - first item in the list
> - second item in the list
> - third item in the list
> ```
> 
> **Output:**
> 
> ```gfm
> This is a list:
> 
> -   first item in the list
> -   second item in the list
> -   third item in the list
> ```
> 
> **Expected behavior:**
> 
> ```gfm
> This is a list:
> 
>   - first item in the list
>   - second item in the list
>   - third item in the list
> ```

This is intentional, look here #3990 for context

**Comment by haoadoresorange** [comment] 2022-02-23 02:21
> Oh! And I thought is was intentional!
> 
> Now I have noticed even other strange behaviour, consider this: **Input:**
> 
> ```
> This is an ordered list:
> 
> 1. first item in the list
> 2. second item in the list
> 3. third item in the list
> ```
> 
> Output:
> 
> ```
> This is an ordered list:
> 
> 1. first item in the list
> 2. second item in the list
> 3. third item in the list
> ```
> 
> **However** if the first item it indented with two spaces: **Input:**
> 
> ```
> This is an ordered list:
> 
> 1.  first item in the list
> 2. second item in the list
> 3. third item in the list
> ```
> 
> The **output** will be:
> 
> ```
> This is an ordered list:
> 
> 1.  first item in the list
> 2.  second item in the list
> 3.  third item in the list
> ```
> 
> If you make three spaces, it will go back to two spaces.
> 
> If you make five spaces, weird things will happen too. Prettier will simply move the paragraph one character to the right, **_each time_** you format (can be done endlessly)!!
> 
> EDIT: This also happens for `--tab-width=2`, so sorry for posting here, but it does seem to be a very similar bug.

intentional also, here #4114 and #4893

**Comment by Nuc1eoN** [comment] 2022-02-23 02:50
Thanks for the info.

>If you make five spaces, weird things will happen too. Prettier will simply move the paragraph one character to the right, each time you format (can be done endlessly)!!

@haoadoresorange What about this?

**Comment by haoadoresorange** [comment] 2022-02-23 03:09
> Thanks for the info.
> 
> 
> 
> >If you make five spaces, weird things will happen too. Prettier will simply move the paragraph one character to the right, each time you format (can be done endlessly)!!
> 
> 
> 
> @haoadoresorange What about this?

I noticed that behaviour too, I use tabWidth=4, if I add 2 more spaces to the content it behaves like you said.

I have no idea why but for the moment I have no interest investigating that though. Can you make a gift capturing that in a new issue so that the maintainers can take a look ?

**Comment by Nukesor** [comment] 2024-06-07 11:50
There's also still the issue of the three inserted spaces after the `-` in unordered lists.

https://github.com/prettier/prettier/pull/3990 is about respecting the indent tabWidth, which indeed works correctly.

Then there's https://github.com/prettier/prettier/issues/4114, which talks about spaces in **ordered** lists.
I understand that addition of spaces in ordered lists might be nice for readability.

However, the issue we're seeing is that spaces are added after **unordered** lists.

As seen above:

```This is a list:

-   first item in the list
-   second item in the list
-   third item in the list
```

The expected behavior would be:

```This is a list:

- first item in the list
- second item in the list
- third item in the list
```

Is this a separate issue to which a issue should be created? I couldn't find anything about this in any issues or PRs.

**Comment by glen-84** [comment] 2024-09-29 08:04
Duplicate of #5019.

**Comment by byplayer** [comment] 2024-09-30 07:35
I think this issue can be closed because it is duplicated.

**Closed** 2024-09-30 07:39 UTC
Labels: type:duplicate
