### ISSUE TITLE
Add option for `brace-style` for applicable languages

### ISSUE THREAD

**Issue by suchverynice** [prettier/prettier#7015] opened 2019-11-20 04:28 UTC
Would really love it if we can choose [this](https://eslint.org/docs/rules/brace-style#stroustrup).

Just a hardline... Pretty, pretty please, with icing and cherry on top, please?

**Expected behavior:**
```js
// https://eslint.org/docs/rules/brace-style#stroustrup
if (foo) {
  bar();
}
else {
  baz();
}

try {
  somethingRisky();
}
catch(e) {
  handleError();
}
```

**Comment by lydell** [comment] 2019-11-20 06:39
Duplicate of #840.

**Closed by lydell** 2019-11-20 06:39 UTC
