### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by todorone** [prettier/prettier#6849] opened 2019-11-06 10:25 UTC
I know that these kinda questions may be annoying, but new shiny TS3.7 just out and the only thing is stopping from using it for a lot of folks around is the absence of Prettier's support. Is there any ETA? 😊

**Comment by evilebottnawi** [comment] 2019-11-06 10:36
Please don't create issues for release, we are working on new version (duplicate of #6469) , thanks

**Closed by evilebottnawi** 2019-11-06 10:36 UTC

**Comment by todorone** [comment] 2019-11-06 10:52
@evilebottnawi Sorry, missed it. If You pin release issue for better visibility, probably there will be less such stupid topics...😸

**Comment by evilebottnawi** [comment] 2019-11-06 10:58
@todorone done :+1:

**Comment by kirillgroshkov** [comment] 2019-11-06 14:55
Can't wait:)
