### ISSUE TITLE
An unnecessary semicolon immediately after a brace

### ISSUE THREAD

**Issue by ichitera** [prettier/prettier#3927] opened 2018-02-08 10:15 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBDANJgIwB0oBLAM0wAoBnCAWzgAUAnOAE1LG3ioEo+mYCUzVgeQgF9MAXkx1GAMQCuUMFQkEBJSSFwgIABxiloNZKGwsWEAO5MrCcymwA3CKXZ6Q2GjGTk2Kg0cPoELNhgANYYAMqGkaRQAObIMCzKoSDsEGABQSH6SSEsMKzYyfTY+cFZAFY0AB4AQhHRcdiMADJJcDWFBsowhkMATP1ZCSwlyCAE2AQAnqjQ3oYsSTAA6p4wABbIABwADPrrECFbEYaz63Alrn36bACOyqRs5ZXVSIG1+iF6KQJgCksl0ABFZQQeAgkAwBY7dj7ZCjfTpbCkVBggDCDCqsyg0CeIGUIQAKgtnH8QpJJEA)
```sh
# Options (if any):
--no-semi
```

**Input:**
```js
let a, b
if (somePredicate()) {
  ({a, b} = someFunc(a, b))
}
```

**Output:**
```js
let a, b
if (somePredicate()) {
  ;({ a, b } = someFunc(a, b))
}
```

**Expected Output:**
```js
let a, b
if (somePredicate()) {
  ({ a, b } = someFunc(a, b))
}
```

**Description**
An unnecessary semicolon was inserted in the third line.

**Comment by lydell** [comment] 2018-02-08 10:28
This is actually intended. As described in the [options](https://github.com/prettier/prettier/#semicolons):

> Semicolons - Print semicolons at the ends of statements.
>
> Valid options:
> - true - add a semicolon at the end of every statement
> - false - only add semicolons at the beginning of lines that may introduce ASI failures

See #1935 and the issues it links to.

**Comment by lydell** [comment] 2018-02-08 10:28
Duplicate of #2693

**Closed by lydell** 2018-02-08 10:28 UTC
