### ISSUE TITLE
False positive in detection of inline math expression

### ISSUE THREAD

**Issue by AndrewKvalheim** [prettier/prettier#8208] opened 2020-05-02 18:09 UTC
Prettier 2.0.5 wrongly escapes the asterisks here:

**Input:**

```markdown
increase from $10 to **$20**
```

**Expected output:**

```markdown
increase from $10 to **$20**
```

**Actual output:**

```markdon
increase from $10 to **$20\*\*
```

**Example:**

```console
$ prettier --version
2.0.5
$ prettier --no-config --parser markdown <<< 'increase from $10 to **$20**'
increase from $10 to **$20\*\*
```

**Comment by thorn0** [comment] 2020-05-05 16:17
Duplicate of #6213

**Closed by thorn0** 2020-05-05 16:17 UTC
Labels: lang:markdown
