### ISSUE TITLE
[HTML] Hope: Support Wrap All Attributes, Except First And Align Attributes 

### ISSUE THREAD

**Issue by MarkSky** [prettier/prettier#6647] opened 2019-10-14 03:49 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAlgWwOYAIDOATmALwA6IAdAPQCG++cM+1Wt2cL8+MlAVgAdsFXLQA2MciGy1McXAPRgRYMfXxSZcgLSLlIXGIi0AJuijYpagF4BPEdQB8IADQgIAmOmj5koWoSEEADuAAoBCL4otABuEOgmriAARoS0YADWTADKAunm2MgwhACucG4AFjCYYgDqFejceWBw2ZGN6DGNtsjgDEnmjIQwoWnYmLTIAGbijG58+AAeAEJpmTmycAAy5nDTs+UgC4vZBWJwAIolEPD7YnMgeYRDvcm0ybZGUEkChOYwtQSMAqyAAHAAGNy-CCMWppAS9X6cOCEGJ7NwAR2u8FGHiiIHo2igcDgJlJSUIcCx6Epo3YEzuD0YmHQRVKh3wZ0u2L2SBm90OMHegJMwOQACY3MVaOgxAUAMIQTAMlBQaDokAlRgAFXeUX5jAAvoagA)
```sh
--parser html
```

**Input:**
```jsx
<img src="./assets/images/test.jpg" alt="game pic" class="game-pic" loading="lazy" />
```

**Output:**
```jsx
<img
  src="./assets/images/test.jpg"
  alt="game pic"
  class="game-pic"
  loading="lazy"
/>;

```

**Expected behavior:**
```
<img src="./assets/images/test.jpg"
     alt="game pic"
     class="game-pic"
     loading="lazy" />
```

I hope Prettier can support setting first attribute in .html file.
Just like "vue/max-attributes-per-line" in eslint-plugin-vue or "wrap-attributes: 'force-aligned'" in js-beautify and in VSCode.

**Comment by lydell** [comment] 2019-10-14 05:40
Hi!

One attribute per line is discussed in #5501.

Alignment is not going to happen. Sorry. Prettier doesn’t do alignment in general, because it generally causes large git diffs. For example, if you change `img` to `custom-img` all of the attribute lines need to be re-aligned.

**Comment by lydell** [comment] 2019-10-14 05:40
Duplicate of #5501

**Closed by lydell** 2019-10-14 05:40 UTC
