### ISSUE TITLE
Templated literals with inline functions are broken

### ISSUE THREAD

**Issue by ravecat** [prettier/prettier#5185] opened 2018-10-03 21:24 UTC
Thank you for work! Got the problem in my code

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt8BnGAT0rgIDpLSAjOSl0mGbDQA8AGU7cACtggYaAPgAUwADpQ8eYjiR4ledl0oAxHHgC+ASjwBeOXvFGcqiwANV6yJS14AJMF0wACzgAWzgzSxs8QJC4FgxsAEtg0mx6ABV0GABhCE9sUwBuNx9gAFkEtASoFho4GDSg0ONYBXNTYt9dcgwMOGwwUlrw6zli9W7e-sGwgDIZsbwwGhpXNXV1+DQYAFoBUigaTWxg7Qm+gdqitfVnQo6-YDwOXIJhmwXnyle5haWVhfUmlg2wA7nAEgBzAIwbQAdgADPCrus8Lcrs4CiAADQgGQwBLQGjIUApaQgiQpBBElCkABuEASBGxIA42FIYAA1nUAMoYdlVCHIATkOA4qq1XBSUgQ5LIMiUWo4gBWNDQACE2ZyeaRQiIqnA5aQFaKQHzBH1kCAGL0aGBEhgYMz4lUYAB1RmBZAADnhOPiEFqrrZGEt8TgEtpBpx2DgAEdyAkY1KZaRDcacbVggkhdgRRmBUwAIrkCDwNOKq2cd0ET1IABMOL2CUoApywVlKCg0CjIHItTSnGp8tqplMQA)
```sh
--parser typescript
```

**Input:**
```tsx
export default styled.label.attrs<LabelProps>({
  for: ({ labelFor }) => labelFor
})`
  color: ${({ theme }) => theme.primaryTextColor};
  ${Mixin.setThemeFont()}
  ${({ uppercase }) =>
    uppercase &&
    css`
      text-transform: uppercase;
    `};
  ${({ bold }) =>
    bold &&
    css`
      font-weight: 700;
    `};
`;
```

**Output:**
```tsx
export default styled.label.attrs<LabelProps>({
  for: ({ labelFor }) => labelFor
})`
  color: ${({ theme }) => theme.primaryTextColor};
  ${Mixin.setThemeFont()} ${({ uppercase }) =>
    uppercase &&
    css`
      text-transform: uppercase;
    `};
  ${({ bold }) =>
    bold &&
    css`
      font-weight: 700;
    `};
`;

```

**Expected behavior:**
```tsx
export default styled.label.attrs<LabelProps>({
  for: ({ labelFor }) => labelFor
})`
  color: ${({ theme }) => theme.primaryTextColor};
  ${Mixin.setThemeFont()}
  ${({ uppercase }) =>
    uppercase &&
    css`
      text-transform: uppercase;
    `};
  ${({ bold }) =>
    bold &&
    css`
      font-weight: 700;
    `};
`;
```

**Comment by lydell** [comment] 2018-10-04 06:33
Hi! This looks like a duplicate of #5147

Please add a comment here if it isn't!

**Comment by lydell** [comment] 2018-10-04 06:34
Duplicate of #5147

**Closed by lydell** 2018-10-04 06:33 UTC
