### ISSUE TITLE
Suggestion: Only remove extraneous parens in expressions

### ISSUE THREAD

**Issue by prencher** [prettier/prettier#1904] opened 2017-06-02 20:23 UTC
Contrived input:
```js
((42 % 1000) + 5 / 70) + 60
```

Gets rewritten to: 
```js
42 % 1000 + 5 / 70 + 60;
```

While this is technically identical, on our projects we standardize on the former, as it is lot faster to read and reason about for the typical developer.

There is a cognitive overhead to memorizing exact operator precedence, and further even for those of us that have, skimming the former is a lot faster than the latter.

It would be nice if parens in these cases are preserved, beyond if you did something like `((42) % 5)`, or have an option to preserve them.

**Comment by k15a** [comment] 2017-06-02 20:33
I think this is a duplicate of https://github.com/prettier/prettier/issues/187?

**Comment by vjeux** [comment] 2017-06-02 20:36
Yeah, I'm tracking all of those in #187. This is something that I want to do but it needs some thoughts to do in a cohesive way.

**Closed by vjeux** 2017-06-02 20:36 UTC
