### ISSUE TITLE
formatting doesn't work for long property definitions

### ISSUE THREAD

**Issue by marcelro** [prettier/prettier#10284] opened 2021-02-09 09:45 UTC
Hi,

I have set my Prettier to printWidth of 140.

I have this line of code in my TS file:

public updateEditedReadingSystemTestValues: EventEmitter<ReadingSystemSelectionEditEvent> = new EventEmitter<ReadingSystemSelectionEditEvent>();

instead of public you could also just write 

let updateEditedReadingSystemTestValues: EventEmitter<ReadingSystemSelectionEditEvent> = new EventEmitter<ReadingSystemSelectionEditEvent>();

The Problem is that the line is not breaking after the '=' and so the line is longer than the configured 140

**Comment by thorn0** [comment] 2021-02-09 11:41
Duplicate of #2482

**Closed** 2021-02-09 11:41 UTC
Labels: type:duplicate
