### ISSUE TITLE
Arrow parens are stripped for ternaries containing JSX

### ISSUE THREAD

**Issue by dbkaplun** [prettier/prettier#3864] opened 2018-02-01 16:39 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCEBGAhgE6YC8mAFAJTkB8VAOlJppFACaYD8TLrmADwcAlgDc6zAQMEAVABYi0ASTQBBAEpxCAGx0BPADLQA5gGEIAWwAO0BDFmETAOUKW4CwjADqIvWcIAVzQ4AAViOBgYEThiZwgHCAAhCMIAa0MRKDg0TAB6SX5WQTzRCSlMWiRMKEC9ZmoAbmYQABoQCGto9GRQEmIIAHdQkgQ0ZBBCMQgRDjbJjGRsXRD2-GJCMDTIgGVrTayTZBhiQLh2jggwJZXzkCyQ4hhwp0tCG51VkAArNAAPFKbbYwHZuOCZbIfL4QQIwaywgBMULu+2IjwmRHw+h00Hm1mIWR8sxg8mQAA4AAztfEQELeDbWCb4nKxMRweYRACOgREEReJjeyPaIUsImOpzuaEOOjgAEVAgl2Uhlp87jBCPhfBwScgEe0ToQ-IcLJZBSgoHZ5sEPBrxsrbgBfB1AA)
```sh
# Options (if any): none (default)
```

**Input:**
```jsx
const foobar = () => (
  cond ? (
    <div>
      <ThisIsAReallyLongComponentTagNameThatWillCausePrettierNotToBreakLines />
    </div>
  ) : null
);
```

**Output:**
```jsx
const foobar = () =>
  cond ? (
    <div>
      <ThisIsAReallyLongComponentTagNameThatWillCausePrettierNotToBreakLines />
    </div>
  ) : null;
```

**Expected behavior:**
Leave outside parens in place.

**Comment by j-f1** [comment] 2018-02-01 16:43
Duplicate of #3593

**Closed by j-f1** 2018-02-01 16:43 UTC
Labels: lang:javascript, type:duplicate
