### ISSUE TITLE
Improve formatting for styled-jsx

### ISSUE THREAD

**Issue by SBoudrias** [prettier/prettier#1140] opened 2017-04-06 07:30 UTC
[Styled-jsx](https://github.com/zeit/styled-jsx) recommend a style like:

```html
<style jsx>{`
  .some-css {}
`}</style>
```

Unfortunately, when prettier run, it reformats it as

```html
<style jsx>
    {
        `
        .some-css {}
`
    }
</style>
```

This kind of become unreadable and it break the CSS syntax coloring applied by the babel language syntax in atom (but probably in other editor too).

(cc @giuseppegurgone)

**Comment by bakkot** [comment] 2017-04-06 07:38
This looks like a dupe of https://github.com/prettier/prettier/issues/1140 to me.

**Comment by SBoudrias** [comment] 2017-04-06 07:39
@bakkot #1140 is this very issue 😆  - is there another one? I did search and didn't find any.

**Comment by bakkot** [comment] 2017-04-06 07:41
Heh, oops, meant https://github.com/prettier/prettier/issues/1090

**Comment by vjeux** [comment] 2017-04-06 16:42
Closing as it's already being tracked :) Thanks for the report.

**Closed by vjeux** 2017-04-06 16:42 UTC
