### ISSUE TITLE
Error: unknown type: "TSJSDocNullableType" (again)

### ISSUE THREAD

**Issue by G-Rath** [prettier/prettier#7014] opened 2019-11-20 03:36 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEAPJmD8AzjAE4CWUA5gNwA6UIANCBAA4xnSHKgCGJJCAHcACvwTcUvAG4QyAEyYgARiV5gA1hgDKrdRUrJSAVzjMAFjAC2qAOrmy8QnrBxtEx2WmOAnsnCE3MwUhHAkMCJqlFa8yABmvKihzABWhNgAQmqaOrxWcAAyFHDxickgadjaBugAisYQ8KVJZiB6JKEk-jA+rHCEYOTsSqzksLYKMObIABwADMyjEKG2aqz+o-1h0iXMAI4N8JFskiC8hAC0UHBw8rdKJHAHZI+RvNGxSAktzKFWZEYSKZfjU4PVGiUvmVWjBeMoJvIpsgAEzMUi8MioAwAYQgVhi-ig0F2IGMoQAKnDJN9ytJTABJKB3WDaQZkdgAQSZ2h66GaoQAvgKgA)
```sh
--parser typescript
```

**Input:**
```tsx
let x: ?string;

```

**Output:**
```tsx
Error: unknown type: "TSJSDocNullableType"
    at printPathNoParens (https://prettier.io/lib/standalone.js:27295:15)
    at Object.genericPrint$3 [as print] (https://prettier.io/lib/standalone.js:24859:30)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15302:20)
    at https://prettier.io/lib/standalone.js:15253:18
    at Object.printComments (https://prettier.io/lib/standalone.js:14974:19)
    at printGenerically (https://prettier.io/lib/standalone.js:15252:24)
    at FastPath.call (https://prettier.io/lib/standalone.js:15089:18)
    at printPathNoParens (https://prettier.io/lib/standalone.js:26438:23)
    at Object.genericPrint$3 [as print] (https://prettier.io/lib/standalone.js:24859:30)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15302:20)
```

**Expected behavior:**
Prettier doesn't crash.

This is a resurfacing of #5095

**Comment by thorn0** [comment] 2019-11-20 10:17
Duplicate of #5840

**Closed by thorn0** 2019-11-20 10:17 UTC
Labels: lang:typescript, type:bug

**Comment by thorn0** [comment] 2019-11-20 10:27
BTW, Prettier prints an error, but it **doesn't crash** here. If it processes a set of files, it proceeds with the next file after printing the error.
