### ISSUE TITLE
Trailing slash on void elements 

### ISSUE THREAD

**Issue by E-Emmy** [prettier/prettier#15612] opened 2023-11-09 23:26 UTC
I'm having problems with prettier...I mean it's giving trailing slash to void elements like this <meta/>

And again giving unnecessary space  <meta charset= "UTF-8"  />.

Latest prettier 

IS THERE A WAY I CAN FIX THIS?

**Comment by auvred** [comment] 2023-11-10 08:33
Please follow the issue template. Duplicate of https://github.com/prettier/prettier/issues/5246

**Comment by fisker** [comment] 2023-11-11 03:09
Duplicate of #5246

**Closed** 2023-11-11 03:09 UTC
Labels: type:duplicate

**Comment by junaga** [comment] 2023-11-25 06:56
@E-Emmy no, you have to install https://github.com/awmottaz/prettier-plugin-void-html
