### ISSUE TITLE
Line break with two params (function)

### ISSUE THREAD

**Issue by realronchi** [prettier/prettier#2413] opened 2017-07-06 17:17 UTC
See example: https://gist.github.com/realronchi/db5aa996a163aa75564def8cb6caa95c

Does anyone knows how to fix this?

**Comment by azz** [comment] 2017-07-06 23:31
Repro link.

https://prettier.io/playground/#%7B%22content%22%3A%22Example.apply(%7B%5Cn%20%20example1%3A%20'1'%20%5Cn%7D%2C%20objectExample%20)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

I'm 90% sure this is the intended behavior.

**Comment by aboyton** [comment] 2017-07-07 03:26
The output looks correct to me too. Alternatively if you put it on one line it would stay that way.

```js
Example.apply({ example1: "1" }, objectExample);
```

**Comment by azz** [comment] 2017-07-09 12:29
Closing this as I'm pretty sure it is working as intended.

**Closed by azz** 2017-07-09 12:29 UTC
