### ISSUE TITLE
Require changelog entries with merged PRs

### ISSUE THREAD

**Issue by suchipi** [prettier/prettier#4077] opened 2018-02-28 23:01 UTC
The 1.11.0 changelog took about 3 hours to write, and we didn't release until about two weeks after when (in my opinion) we could have, because no one had written the changelog yet.

Because we don't have a precedent of including detailed changelogs with point releases, I was able to release 1.11.1 in about 10 minutes today.

I know that the detailed changelogs are important to @vjeux. I am also concerned that they will continue to cause friction around releasing future versions.

I think we should keep a pending changelog markdown file in the repo, and whenever someone merges a PR, they add an entry to it. That way, cutting a release is just proofreading the entries and moving the file into `blog`- the person doing the release won't have to track down every merged PR since the date of the last release and try to understand the context of each.

If possible, it'd be nice if we could configure a GitHub bot to require a change to the pending changelog file before a PR can be merged.

Thoughts?

**Comment by vjeux** [comment] 2018-02-28 23:12
Prettier has had 3 million downloads last month: a lot of companies critically depend on Prettier for their workflow. Every single release that we do has the potential to be a breaking change since it will change the formatting of your code and you need to run a codemod to upgrade to it.

The fact that releases are spaced out and take work is a feature, not a bug.

As for your proposal to automate the release generation, I've seen it tried a bunch of times and in practice I've never seen it work. It's indeed pretty annoying to write the changelog but as you mention it's only 3 hours of work so it's reasonably short. Also, having a single person write it is great as you can reorder things, make a story around it...

I'm so grateful for you to be writing the release notes and I understand if you don't want to write them in the future, but I do think that they are very impactful. The last release notes got 2.6k page views, that's a lot of people reading them!

**Comment by suchipi** [comment] 2018-02-28 23:27
I'm not trying to complain; I don't mind writing them that much, but I recognize I might not always be around to do so. As an open-source, community-led project, I'm concerned that our current release process might be the weakest link in the project being supported by the community.

Maybe we could try to improve other parts of the changelog writing process? Here two pain points I noticed from the last time around:

* Trying to track down every PR that was merged since the last release is a bit tedious- my current workflow is to ask github for every PR merged since the date of the last release, but it means opening a lot of tabs, and it can be easy to lose one when checking the issue the PR closes (opening a new tab). If there was a script we could run that generated a list of links to PRs merged after the last tagged commit, then this could be less tedious or prone to human error. 
* I went through each issue by chronological merge date, but I put them in the changelog organized by language. This meant a lot of scrolling up and down, and I often lost my place. Since we have language tags, if the above script could sort the links by language, this would make writing the changelog a lot easier.

Maybe I could write the script since I know which things bothered me. But a script still wouldn't solve the fact that I sometimes can't tell what a PR fixed or the motivation behind it, which results in the mixed level of detail in the blog post (some changes are described like "typescript added this, it does this, so we treat it like this" and some are "this used to be bad... now it's good")

**Comment by vjeux** [comment] 2018-02-28 23:33
For the last part, I would ping people working on this to give more context or own that section of the changelog.

For the fact that you may not always be around, I think that's fine. The current cadence of a release every month and a half / two months is fine to me. The goal for prettier is to stop changing so that it can be relied upon. Ideally, in a year or two, we will just do a new release when there's a new feature added to a language we support. The printer for the languages we support will be good enough that we don't need to tweak them as much.

I view the success state of prettier as being "Done" at some point and stop changing. We're almost there on the javascript printer, it's been a few releases with very few changes.

**Comment by j-f1** [comment] 2018-02-28 23:48
I still think it would be a good idea to have a code sample and short description included in each PR. It would be fairly easy for whoever does the release to reorder & reword the release notes as needed.

**Comment by duailibe** [comment] 2018-02-28 23:54
I guess we could write a script to generate a markdown file with the language sections, titles of all the PRs included after the latest tag with links to each, can help a lot:

- we can open a PR with it and other collaborators can help writing details for each change;
- we won't lose our place with scrolling, just follow the order in the markdown already.

**Comment by ericanderson** [comment] 2018-03-01 00:44
It might be nice to do what you suggest @duailibe but also to have a different changelog per language. They are all going to be grouped that way in the changelog anyway and it will be much easier for people to collaborate on things that they actually pay attention to. (E.g. I'm only looking at JS/TS changes)

**Comment by changelox** [comment] 2018-03-20 14:37
Hey everybody! We are using nearly the same workflow for our client projects and it works great for us. Turns out that it makes writing a good changelog very easy. Our workflow looks like this:

1. A contributor creates a pull request
2. The PR is checked by our GitHub App for a changelog annotation 
3. If no changelog annotation could be found the PR is marked as failed
4. The contributor or maintainer adds the changelog annotation and the PR is marked as successful

As soon as the PR is merged into master another PR is created or updated with the newly generated changelog entry.

If you're interested in you may check it out: https://github.com/apps/changelox.
Of course feedback is appreciated ;-)

**Comment by thorn0** [comment] 2020-03-10 15:03
This has been long solved.

**Closed by thorn0** 2020-03-10 15:03 UTC
Labels: status:needs discussion, type:meta
