### ISSUE TITLE
import as, breaks line limit 

### ISSUE THREAD

**Issue by OlegLustenko** [prettier/prettier#2923] opened 2017-09-28 09:12 UTC
**Prettier 1.7.2**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22import%20sinon%20from%20'sinon'%3B%5Cnimport%20%7BcreateColumnLimits%20as%20createColumnLimitsModelMock%7D%20from%20'extensions%2Flinearity-test%2Fmodels'%3B%5Cn%5Cnimport%20%7BTestValueColumnDescription%20as%20TestValueColumnDescriptionmodelMock2%7D%20from%20'extensions%2Fcomponents%2Fadvanced-settings%2Fmodels'%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%2C%22output2%22%3Afalse%7D%7D)

**Input:**
```jsx
import sinon from 'sinon';
import {createColumnLimits as createColumnLimitsModelMock} from 'extensions/linearity-test/models';

import {TestValueColumnDescription as TestValueColumnDescriptionmodelMock2} from 'extensions/components/advanced-settings/models';

```

**Output:**
```jsx
import sinon from "sinon";
import { createColumnLimits as createColumnLimitsModelMock } from "extensions/linearity-test/models";

import { TestValueColumnDescription as TestValueColumnDescriptionmodelMock2 } from "extensions/components/advanced-settings/models";

```

**Expected behavior:**
```jsx
import sinon from 'sinon';
import {
  createColumnLimits as createColumnLimitsModelMock
} from 'extensions/something-test/models';

import {
  TestValueColumnDescription as TestValueColumnDescriptionmodelMock2
} from 'extensions/components/advanced-settings/models';

```

prettier options:
"prettier.printWidth": 80,

is it correct behavior  ?

**Comment by ikatyang** [comment] 2017-09-28 09:18
Hi, thanks for the issue. This is a duplicate of #2441 which was closed with the following [comment](https://github.com/prettier/prettier/issues/1954#issuecomment-306067705):

> This is actually intended. We have a special case for import and require with single elements where we keep them in a single line. You don't get much more information when they are in two lines and they look worse with a series of imports. This was done due to common request from people using prettier.

**Closed by ikatyang** 2017-09-28 09:18 UTC

**Comment by OlegLustenko** [comment] 2017-09-28 10:44
ok thanks
