### ISSUE TITLE
Creating random {" "} whenever spaces are seen

### ISSUE THREAD

**Issue by gazcn007** [prettier/prettier#4300] opened 2018-04-12 00:20 UTC
Great work on prettifying JSX code 👍 , just having this issue with using prettier-atom:

For example if my code is uglified like the following:

![image](https://user-images.githubusercontent.com/12766318/38649583-816fd024-3dc5-11e8-85e1-96a6da5d0993.png)

Whenever I use prettier with prettier-atom, it creates {" "}:

![image](https://user-images.githubusercontent.com/12766318/38649599-9687694a-3dc5-11e8-9f99-78e786d2c2ec.png)

This works fine with normal JSX components, but it has '_idCounter' of undefined errors (`Uncaught TypeError: Cannot read property '_idCounter' of undefined`) when using libraries such as [react-konva](https://github.com/lavrton/react-konva).

I thought it was a `prettier-atom` issue, so I opened an issue [here](https://github.com/prettier/prettier-atom/issues/407), but seems like it is `prettier`'s issue according to Rob.

**Comment by hawkrives** [comment] 2018-04-12 00:27
@gazcn007 I described this in https://github.com/prettier/prettier/issues/4223#comment-380093772, I think. 

Does that make sense? In short, I think your issue stems from JSX's space handling, where Prettier has to keep the space because JSX and HTML handle whitespace differently.

**Comment by gazcn007** [comment] 2018-04-12 00:38
@hawkrives Thanks for your fast reply, sorry I didn't see that issue.
Cool that makes sense. seems like [react-konva](https://github.com/lavrton/react-konva) doesn't handle this space diff between JSX and HTML, whenever it sees {" "} in a component, the component stops working.

**Comment by suchipi** [comment] 2018-04-12 04:53
I'm going to close this as a duplicate of https://github.com/prettier/prettier/issues/4223.

**Closed by suchipi** 2018-04-12 04:53 UTC
