### ISSUE TITLE
× Error: Couldn't resolve parser "babel". Parsers must be explicitly added to the standalone bundle

### ISSUE THREAD

**Issue by ctq123** [prettier/prettier#10401] opened 2021-02-24 07:34 UTC
**Output:**
![image](https://user-images.githubusercontent.com/12124169/108963782-86f08580-76b5-11eb-9cda-667b2e74f7a4.png)

it don't work!

prettier@2.2.1

**Comment by ctq123** [comment] 2021-02-24 07:34
![image](https://user-images.githubusercontent.com/12124169/108963953-cdde7b00-76b5-11eb-8143-0848dd54ed47.png)

**Comment by fisker** [comment] 2021-02-24 08:41
You can find the answer you need in https://github.com/prettier/prettier/issues/9801

**Comment by fisker** [comment] 2021-02-24 08:41
Duplicate of #9801

**Closed** 2021-02-24 08:41 UTC
Labels: type:duplicate
