### ISSUE TITLE
Prettier replaces brackets?

### ISSUE THREAD

**Issue by chilander1** [prettier/prettier#4246] opened 2018-04-03 09:58 UTC
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#.....)
```sh


**Input:**
```jsx
export const getApp = (appId, params = {}) => (
  async (dispatch, getState) => {
    try {
      ....


    } catch (error) {... }
  }
);
```

**Output:**
```jsx
export const getApp = (appId, params = {}) => async (
  dispatch,
  getState,
) => {
  try {
    ...


    } catch (error) { ... }

); // shoud be this '}'
```

Why such a strange behavior and how to fix it?
thanks)

**Comment by kachkaev** [comment] 2018-04-03 10:14
@chilander1 all looks good to me when I [copy your code to the playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wHM4YBBDDPAXjwAoBDGgSQBMAaPDZ7ZgFsi9PMAC+ASnoA+JgB0oePMyIBPKGCYcAlkT4wwACx7kYAZRjN40unOCLlymNjVjFjp8qIRBFIzpQpIySANweSk7iBNbGTHDY2DjSwHg+fjABQQCiADZEcCGheOKepVBhIFwgEBgwOtBEyKD8SQDuAAr8CE0ozABuEDocVSCqMMgAZsz5cNUARgJgANYU5nxggaTILgCucyAcEGBTMwXVgQW4HQKkgsyns9UAVkRoAEJLqxZCcAAygTgj3ONV2MAwYIATMCDnxsFdkCB5sx5mpctBRhhsIEYAB1YaZZAADgADNUsRACriBBhEVi4Fd+kDqtg4ABHXY6Vk3Zh3B5IaZPEAFQQ6HbYfbVIhbXJwACKuwg8Bh1Ss83xHEJSEhqoEOlyWwAwr57oioNBmSBdgUACoo3qCgricRAA).

Can you share the code block where the issue gets reproduced in the playground?

**Comment by chilander1** [comment] 2018-04-03 10:36
@kachkaev hmm... there it works well.
What could be wrong? 
I have no errors/warnings...

**Comment by j-f1** [comment] 2018-04-03 11:20
Can you reproduce this in the playground and post a link to it here?

**Comment by chilander1** [comment] 2018-04-03 11:29
@j-f1 yes, 
but in the playground it works good
[code](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wHM4YBBDDPAXjwEsATegPjwAoAdKPPAIZEAnlDBdmjIhgEwwACwCU7PMF79+MbMNXqN-AQHcBjfJOmyFnNX30aYwjHCR4HTogDoA4gFEAKgD6lAAKwQEASj4AigCqPgDKfgA0enZ4MsIANhACzC42afoCNPmphfwsKbblAL5VtfV2NYoA3Lxl-IQkeNhw0tBEcPSCxqZ4wdgQALZScB4CmZmcANodGsWMHuRUNOFwAI4Arn0wnCyKjWnb1BgAwpmHJHDYRHtHJ2fMF2sAuq3t1XWozMUhkcnk1jWmkczlcMM8vkCITC8Rit1uCXilzsGWyuVKgLSxQwLl6-WIcGWAAYfh5mLIBHSGdj9HU1s02lA1kYTCCLODONcaPdHvAXvFDmAwH0iJwyVgKcsAIy0+kwASKf6AmoESzyLjPSbYZQFOw8sbmMFWU1pNywu0I-xBUIBHzhcIAeXCLLwHIBROBeEtes4GEeEIA5AB6Q04COazmsvQ1XhakBJEAQDAwRgDZCgATYSaGYKFhBEZAgAQANwgLHTVZIyAAZgtBhmAEbYARgADWFHiMjAjCgpGQWmOGeYEDALbbcAzI8GuAmAlIUwEc8y7ZAACsiGgAELdvsDgRTOAAGRHcC3O4ghxgYZgACY7wuQDIXs9Kx2BB2smgBsMGwEcYAAdRYGB5GQAAOKkMxAiBBnA7sMErEC+meatbwzXojkYXpV3XTckFbbcP0GGZx2wScQCIEdSEyOAokOCB4HfDN1Q7SDmGg5AXy47tGEyRjbmmDdKygaBcJAR44D8f8KzI+cahqIA)

**Comment by kachkaev** [comment] 2018-04-03 11:31
> [code](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wHM4YBBDDPAXjwEsATegPjwAoAdKPPAIZEAnlDBdmjIhgEwwACwCU7PMF79+MbMNXqN-AQHcBjfJOmyFnNX30aYwjHCR4HTogDoA4gFEAKgD6lAAKwQEASj4AigCqPgDKfgA0enZ4MsIANhACzC42afoCNPmphfwsKbblAL5VtfV2NYoA3Lxl-IQkeNhw0tBEcPSCxqZ4wdgQALZScB4CmZmcANodGsWMHuRUNOFwAI4Arn0wnCyKjWnb1BgAwpmHJHDYRHtHJ2fMF2sAuq3t1XWozMUhkcnk1jWmkczlcMM8vkCITC8Rit1uCXilzsGWyuVKgLSxQwLl6-WIcGWAAYfh5mLIBHSGdj9HU1s02lA1kYTCCLODONcaPdHvAXvFDmAwH0iJwyVgKcsAIy0+kwASKf6AmoESzyLjPSbYZQFOw8sbmMFWU1pNywu0I-xBUIBHzhcIAeXCLLwHIBROBeEtes4GEeEIA5AB6Q04COazmsvQ1XhakBJEAQDAwRgDZCgDDYRiwADqLBg8mQAA4qRn1QAjMvMCvIABMGaIxdImTgUUOEHgyAAZgtBnXsCZMl3btMpgJkCAoNA4OmQPWJ2AANYUeIyMBd5BaY4ZgBWRDQACEN9uYPEBFM4AAZYsrpAjzJjkAyF7PBf1gT1lk0CroMMyHtgx4gI8cB+ABRDDqOcAZsWgy4BMAikHOCEfkhIC9EcjC9OhmHzm+iEZoWECDCWE4YAuhZ9M8ABuK4ZgI2CTIYwTsQg8EoAITEQCwq7MBAYDYZ+QgwBJuEQIcMBhjArYyTUNRAA)
@chilander1 is this the entire file or just a part of it? How do you execute prettier (editor/ command line, etc). What's its version? What's your environment in general (e.g OS)?

**Comment by j-f1** [comment] 2018-04-03 11:35
Unfortunately, there isn’t much we can do to fix this issue without a reproducible example that we can use to identify the problem.

Are you using any tools other than Prettier on your code?

**Comment by chilander1** [comment] 2018-04-03 11:40
@kachkaev 

> How do you execute prettier (editor/ command line, etc).
editor and before commit

> What's its version? 
1.11.1

> What's your environment in general (e.g OS)?
windows 10

**Comment by kachkaev** [comment] 2018-04-03 11:44
It'd be really good if you could create a minimal working example and share it as a github repo so that others can witness that behaviour too. Without that, it's really hard to tell what may be going wrong in your case.

**Comment by chilander1** [comment] 2018-04-03 13:56
@j-f1 @kachkaev 
 [this project](https://github.com/chilander1/check-prettier)
this is part of my project
please clone and try if it works for you 
please try to fix via editor files client\services\app\actions.js or client\services\app\reducer.spec.js

**Comment by kachkaev** [comment] 2018-04-03 16:40
According to these lines in your package.json, you are using `eslint --fix` after prettier:

https://github.com/chilander1/check-prettier/blob/7223adaeec350a1919d9c09ae7b4c223f7dca726/package.json#L38-L39

I suspect that this is what is causing this odd behaviour in your case.

After adding Prettier, you don't have to depend on `eslint --fix` any more. Simply adhere Prettier's formatting standards and use eslint only to catch semantically incorrect things like unused vars etc. After I've done this in my projects, editing javascripts became much more pleasant because I stopped seeing linting errors in my editor every time I type an extra space (which is a deadly sin if eslint rules are strict enough).

Switching to Prettier's opinionated formatting rules after using your bespoke fine-tuned rules may feel a bit uncomfortable in the beginning and I clearly remember this. However, after a couple of days this feeling disappears and you only enjoy writing the code. No more thinking about bulky and hard-to-maintain eslint rules and no more arguing with your colleagues about these rules!

**Comment by chilander1** [comment] 2018-04-04 07:56
I've deleted `eslint --fix` and it stopped working at all
works only via webstorm but with the same problem

**Comment by chilander1** [comment] 2018-04-04 10:46
@kachkaev ok, thanks for your work!)
why does it replace single quotes `' -> "`?
How to fix this? Is it possible to set the standard airbnb?

**Comment by j-f1** [comment] 2018-04-04 10:58
Prettier inserts single quotes if you pass `singleQuote: true` (which you have) unless the string contains single quotes.

**Comment by kachkaev** [comment] 2018-04-04 11:12
@chilander1 or you can create `prettier.config.js` in your project's root with this content:

```js
module.exports = {
  singleQuote: true
};
```

I also used to use single quotes before switching to prettier but now I find it ’cheaper‘ to use double ones. Of course, they are a bit more noisy, but on the other hand there's less difference between JS and JSON and, what is more important, this is Prettier's default.

My typical prettier config looks like this today:
https://github.com/shd101wyy/mume/blob/master/prettier.config.js
or like this, when it also comes to formatting markdowns:
https://gitlab.com/kachkaev/website-frontend/blob/master/prettier.config.js

Now that you are using Prettier without eslint (which is great), can your problem be considered as resolved? Feel free to close this issue if yes 😉

**Comment by chilander1** [comment] 2018-04-04 14:00
I've used [prettierrc](https://github.com/obartra/prettierrc).
and it works well!
thanks a lot!)

**Closed** 2018-04-04 14:00 UTC
Labels: lang:javascript

**Comment by kachkaev** [comment] 2018-04-04 14:06
You no longer need to install `prettierrc` package – your `.prettierrc` file should be picked by prettier natively. See https://prettier.io/docs/en/configuration.html.
