### ISSUE TITLE
resoveConfig pickup --config arg from command line even in API mode cause Webpack conflict

### ISSUE THREAD

**Issue by hunteva** [prettier/prettier#2879] opened 2017-09-22 06:16 UTC
Since 1.6.0 Prettier pickup '--config' arg from the command line, so if you set it up with webpack, eslint-loader and eslint-plugin-prettier and running command like

`
webpack --config webpack.dev.js
`

could have _webpack.dev.js_ file been pickup by prettier as configuration thus resulting Validation Warning like this:

> 
> ● Validation Warning:
> 
> Unknown option "devtool" with value "#source-map" was found.
> This is probably a typing mistake. Fixing it will remove this message.
>

The problem arose when a recent eslint-plugin-prettier [PR](https://github.com/prettier/eslint-plugin-prettier/pull/55) merged to accommodate Prettier 1.6.0

It feels like the resolveConfig shouldn't hang on with global command-line arguments in API mode base on the discussion [here](https://github.com/prettier/eslint-plugin-prettier/issues/58)

Please feel free to correct me if this was by design
Cheers!

**Comment by ikatyang** [comment] 2017-09-22 06:19
Hi, thanks for the report. This is a duplicate of #2870:

> This issue was fixed by #2843 few days ago but haven't released yet, for now you can install the newest prettier from github as a temporary workaround:
> 
> ```sh
> npm install prettier/prettier
> ```
> 
> or if your tools support alias for the `--config` option (e.g. `-c`), using it can also solve the problem  since cosmiconfig only read the `--config` option.

**Closed by ikatyang** 2017-09-22 06:19 UTC

**Comment by hunteva** [comment] 2017-09-25 01:02
Got it, thank you @ikatyang
