### ISSUE TITLE
TypeScript weird indentation for props decalration

### ISSUE THREAD

**Issue by tomacotuna** [prettier/prettier#6204] opened 2019-06-09 14:08 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlGBPAGzgBMAVOADywF5MNCSA6cqgHhZgAUAnCABzQA+AAYAdKJkwASYH0zVBmPoz7c4aOFgBkWpWo0w0AbWWr1mgLoBfANzjhIADQh+MAJbpkoAIbdeAd05fBDRkEG8ANwg3YicQACNubzAAa01sPmS3KABzZBhuAFc4ZwALGABbAgB1Urd4NEywOGwQ+rcI+rwwsDRQ52yNbi4knIrvZAAzbwINZwArNAoAISTU9O8KuAAZbLgpmbmQRYpsbJyiAEVCiHgD2ZKQTO4hsPjveMJoONVsmGqYjBSsgABwABmcqggGmqST4YTMQwi+2cAEcbvAePxQihvGgALRQOAkEhxNTotxqHjeMYTJDTB7ODQVNz5IqPNDnK4Y-b0w6PGAfAHEIHIABMzgK3jcBHOAGEIBVxmEoNAUSBChpSB8cQyNFYrEA)
```sh
--parser babylon
```

**Input:**
```jsx
const StyledText = styled.Text<TextProps>`
  ${p => p.preset && presets[p.preset]};
`
```

**Output:**
```jsx
const StyledText =
  styled.Text <
  TextProps >
  `
  ${p => p.preset && presets[p.preset]};
`;

```

**Expected behavior:**

I would expect for it to be as inputed format, I personally dont like the new line after `<`. Maybe some people like that, but for me it makes it harder to read, especially since I usually have only one interface there. Is there any way to stop it from doing this kind of formatting?

**Comment by lydell** [comment] 2019-06-09 17:15
Hi!

You need to specify Typescript as the parser when using the playground.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlGBPAGzgBMAVOADywF5MNCSA6cqgHhZgAUAnCABzQA+AAYAdKJkwASYH0zVBmPoz7c4aOFgBkWpWo0w0AbWWr1mgLoBfANzjhIADQh+MAJbpkoAIbdeAd05fBDRkEG8ANwg3YicQACNubzAAa01sPmS3KABzZBhuAFc4ZwALGABbAgB1Urd4NEywOGwQ+rcI+rwwsDRQ52yNbi4knIrvZAAzbwINZwArNAoAISTU9O8KuAAZbLgpmbmQRYpsbJyiAEVCiHgD2ZKQTO4hsPw+dTBuNz4YONVsjBqjEYKVkAAOAAMzlUEA01SSfDCZiGEX2zgAjjd4Dx+KEUN40ABaKBwEgkOJqLFuNQ8bxjCZIaYPZwaCpufJFR5oc5XbH7JmHR4wbzxYHEUHIABMzgK3jcBHOAGEIBVxmEoNB0SBChpSKL8cyNFYrEA)
```sh
--parser typescript
```

**Input:**
```tsx
const StyledText = styled.Text<TextProps>`
  ${p => p.preset && presets[p.preset]};
`
```

**Output:**
```tsx
const StyledText = styled.Text<TextProps>`
  ${p => p.preset && presets[p.preset]};
`;

```

When using the CLI or editor integrations the parser is usually automatically inferred from the file extension.

**Comment by tomacotuna** [comment] 2019-06-09 23:40
Ohh I see, that is weird as I am having that issue on a new project bootstrapped with Ignite Bowser. I am getting my output changed as shown in my initial comment. Any idea what rule is causing this issue? I assume there might be some conflict with the rules of ts linting and prettier, but was not able to narrow it down.


Steps to reproduce: 

Bootstrap project and add styled-components:
- `yarn global add ignite-cli`
- `ignite new project-name -b bowser`
- `yarn add styled-components`

add in `app.tsx` the following lines:

```ts
import styled from 'styled-components'

const StyledText = styled.Text<TextProps>`
  ${p => p.preset && presets[p.preset]};
`
```

and you will get:

```ts
import styled from 'styled-components'

const StyledText =
  styled.Text <
  TextProps >`
  ${p => p.preset && presets[p.preset]};
`
```

**Comment by lydell** [comment] 2019-06-10 05:11
After creating app.tsx with the code from your comment – what do you do then?

**Comment by tomacotuna** [comment] 2019-06-10 15:51
I realise i didnt link the boiler plate, https://github.com/infinitered/ignite-bowser.

I dont create the file, it is already as part of the boilerplate. After I insert the code from my comment, I save the file and Prettier runs on save, and the output is as stated in my initial comment. If you are not able to reproduce the issue, suing the boilerplate and steps above, it probably means it has to do with some local settings on my computer of prettier/eslint.

**Comment by duailibe** [comment] 2019-06-10 16:33
The problem is because the boilerplate installs an old version of Prettier (v1.12.1)

https://github.com/infinitered/ignite-bowser/blob/52e1e43e0b6bfdc05bf9f74b9b80867d8bf78f7b/boilerplate/package.json.ejs#L78

This issue was fixed in later versions

**Comment by tomacotuna** [comment] 2019-06-10 16:44
That makes sense, thanks a lot for the help ❤️

**Closed** 2019-06-10 16:44 UTC
