### ISSUE TITLE
HTML comments are not wrapped

### ISSUE THREAD

**Issue by pauldraper** [prettier/prettier#6153] opened 2019-05-24 20:33 UTC
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq19zU55bcAhgBMGqGAEsYdOMID0YiVNTTK-IS24YAtBvIBZAJ7kATvzp0DdaAHNykGjQQwAdLoPG+p81ZsQ7D5-qMTM3ILKGtbe1h-VyDPMO9fKPItTkV2RhYQABoQCAAHMWgAZ2RQPkNDCAB3YnKEEpQ+ADcIUQFskAAjQz4wAGs4GABlPN7RMOQYQwBXOBz0gHVKcTgi0bA4IfrxUSbxPWRwIpKc8aK4QxhiHssaPmQAM3dznIArIoAPACEe-sGhvj2AAy4zgj2ecxA7w+Q3GlkkAEVphB4OC6C8QKNDOdDId0h08oZxjAFm0YJRkAAOAAMOUJEHOCx6eUOhNWFyaYJyxgAjtNRMZrnxbvckE90ZDzjRRJMZpK4YjkaixRCcjA+J1SQJycgAExqnqiOhw3A+O6HKDQLkgabnfAahri84AX2dQA)
```sh
--parser html
```

**Input:**
```html
<!DOCTYPE html>
<html>
  <head><title></title></head>
  <!-- My really long comment. My really long comment. My really long comment. My really long comment. -->
</html>

```

**Output:**
```html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <!-- My really long comment. My really long comment. My really long comment. My really long comment. -->
</html>

```

**Expected behavior:**

Something like

```html
<!DOCTYPE html>
<html>
  <head><title></title></head>
  <!--
    My really long comment. My really long comment. My really long comment. My
    really long comment.
  -->
</html>
```

**Comment by thorn0** [comment] 2019-05-24 20:38
duplicate of #265

**Comment by lydell** [comment] 2019-05-24 21:45
Duplicate of #265

**Closed by lydell** 2019-05-24 21:45 UTC
