### ISSUE TITLE
Vue template indent Problem

### ISSUE THREAD

**Issue by Tinple** [prettier/prettier#4226] opened 2018-03-30 03:59 UTC
**Prettier 1.11.1**
[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG5lj4DOzAvMSAO4BOeWWOD06F0cAB4xGLdpwBGAVxgxonMgAEmNMAGsOIZgAsIXAMLQAZjR4YAgiPNQrN1AHp4kkuQqUPUpnis+orKqiAaWrr6RiaOzhgAQg6GeFAA5nBkMDQwOHBufl4+vhL+MsFKKlBqmjjaepwxZpbWGKYiYHg4OHJ4umTAwDxwzAC+owWlRZSutHRek9j4RKSkIAA0IBBY2dDMyKB4PDwmAApHCPsoeHQQNFQbIIEwyBZdzHCbcny6cDAAylg+jR0sgYDwFJ8QFQIGBXu8oSCPjwYKc+GkMHh4TgPpsAFbMcQJH46P7-PAYOAAGRBcGxuK2SiwSgATPSoUCeMjkCA6JDHlgeCCYAB1e4wQzIAAcAAZNoKIB8RXwsDzBSMhHQ6ZthgBHBTWOBovAYrFIN44qEfDA0MEQq0gtJ5ACKCgg8HZmxgeDkYqoEuQABYvXwaHV0uYMJieVBoNqQAoPgAVH1XC0fcZAA)

**Input:**
```jsx
<template>
  <div class="wrapper"><text class="button" @click="showConfirmA">Confirm</text>
    <text class="button" @click="showConfirmB">Change title</text>
    <text class="button" @click="showConfirmC">callback {{res}}</text>
  </div>
</template>
```

**Expect Output:**
```jsx
<template>
  <div class="wrapper">
    <text class="button" @click="showConfirmA">Confirm</text>
    <text class="button" @click="showConfirmB">Change title</text>
    <text class="button" @click="showConfirmC">callback {{res}}</text>
  </div>
</template>
```

**Comment by ikatyang** [comment] 2018-03-30 04:21
Hi, we currently do not support HTML-variants and there's already an issue for it, let's track it there -> #1882.

**Comment by ikatyang** [comment] 2018-03-30 04:21
Duplicate of #1882

**Closed by ikatyang** 2018-03-30 04:21 UTC
