### ISSUE TITLE
Formating take 5min

### ISSUE THREAD

**Issue by MarchWorks** [prettier/prettier#6227] opened 2019-06-15 22:23 UTC
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: Node.js API || Browser API
- Runtime: Node.js v10
- Operating System: Windows

**Steps to reproduce:**

https://codesandbox.io/s/vigorous-glitter-r3hrk
It may break your browser like me
It take 5min when I run it locally with node

**Expected behavior:**
take a reasonable time
**Actual behavior:**
Take so much time which make the build time in our app too long

**Comment by duailibe** [comment] 2019-06-15 23:01
Thank you for the report. This seems like it's the same case from #4784.

Let's track this problem over there.

**Comment by duailibe** [comment] 2019-06-15 23:01
Duplicate of #4784

**Closed by duailibe** 2019-06-15 23:01 UTC
