### ISSUE TITLE
stopped working in VScode

### ISSUE THREAD

**Issue by IlyaShumyantsev** [prettier/prettier#15190] opened 2023-07-31 15:45 UTC
Just suddenly stopped working in vscode. Tried reinstalling both plugin and vscode. No results.

**Comment by IlyaShumyantsev** [comment] 2023-07-31 15:45
![image](https://github.com/prettier/prettier/assets/32883963/9a222232-f4dd-48ca-ade1-ee6e83d42d9d)

**Comment by kachkaev** [comment] 2023-07-31 15:48
👋 @IlyaShumyantsev! Please see https://github.com/prettier/prettier-vscode/releases/tag/v10.0.0, which is a recent VS Code release. Your issue is probably a duplicate of https://github.com/prettier/prettier-vscode/issues/3099. Either way,  problems with with VS Code should be discussed in [prettier/prettier-vscode](https://github.com/prettier/prettier-vscode). This repo is for Prettier core only.

**Closed by kachkaev** 2023-07-31 15:48 UTC
Labels: scope:external

**Comment by aduggleby** [comment] 2023-07-31 15:51
Same here, clicking on "Prettier" in the bottom toolbar gives "command 'prettiert.openOutput' not found.

I've reinstalled VSCode from scratch, removed all settings (.vscode and the code settings folder) and only installed Prettier, no help. 

**Platform**
VS Code:
Version: 1.80.2 (user setup)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:40:28.909Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Prettier:
Published
1/10/2017, 11:52:02
Last released
7/31/2023, 07:48:55
Identifier
esbenp.prettier-vscode

**Misc**
- Prettier is also installed globally via NPM and works fine with CLI.
- Issue happens regardless of file type

**Comment by IlyaShumyantsev** [comment] 2023-07-31 15:56
@kachkaev Thanks for the answer! Sorry, I didn't know where to post this issue. Installing the old version really helped! Thank you!
