### ISSUE TITLE
Long string values in object literals sometimes look strange

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#3711] opened 2018-01-11 10:03 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQQEYBW2AvNsADpTbXYD0t26VCMmAntgO4CWMAFo2yo47bABtoAc2wBnVtyiTKNbAA8k2ciACMAJgDMAFgCsANgDsADgCcABj1GzVuw5MWb9g2+efH7l15OHq5BAX4+If6+3sGBUVqUAL4A3CAANCAQAA4w3NAyyKBYmBCcAApYCAUo6KgQ3AAm6SDocsgAZuhiMnAZeJjoYADWcDAAylmDCpLIrACuvSANEGAdXT0ZCj2YMGUDkgC26GvdiwQyqgBCA8OjY+gHcAAyCnAnG5lzMFlfuu+Lk0w22QIDw6DwbAkUGaWUwChgAHVGvxkJZbBlYRAegiBlkQbC4NthM1MHAAI5zbikvboQ7HJCdU4ZHoHbizTALZnTMRwACKcwg8H+GRg4KRDRRSEMIoG3DE0wAwhADkcQVBoG8MnMegAVcHVRk9RKJIA)
```sh
--tab-width 4
```

**Input:**
```jsx
var obj = {
    // an entry with a very long string
    x: "12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"
};
```

**Output:**
```jsx
var obj = {
    // an entry with a very long string
    x:
        "12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"
};

```

**Expected behavior:**

Leave it as it was. This wrapping doesn't make it any better. Especially when the property name is short and `--tab-width` is `4`.

**Comment by lydell** [comment] 2018-01-11 17:07
This is a duplicate of #2079.

**Comment by j-f1** [comment] 2018-01-11 17:14
@lydell Are you sure? I interpreted this request as asking not to break if it makes the line longer, as shown in the example.

**Comment by lydell** [comment] 2018-01-11 17:23
Yes, I'm sure. I don't interpret the issue that way. We'll reopen if I'm wrong :)

**Comment by thorn0** [comment] 2018-01-12 12:05
So, in my code, the name of the property is `url`. And I have a lot of objects like that in e2e tests. Breaking the line makes it 1 character shorter, but still looks strange IMHO. My proposal is not to break when the length of the key is less than `--tab-width`.

**Comment by j-f1** [comment] 2018-01-12 12:07
Sounds like a good idea 👍

**Comment by azz** [comment] 2018-01-12 12:14
+2 to allow for colon + space?
```js
const canBreak = k.key.value.length + 2 > options.tabWidth;
```

❓

**Comment by thorn0** [comment] 2018-01-12 13:24
Prettier tries to mimic a human, right? Would a human really write something like:
```js
var obj = {
    url:
        'http://...'
};
```
? I get a sense of [uncanny valley](https://en.wikipedia.org/wiki/Uncanny_valley) looking at it. :smile:  So I'd vote for
```js
const canBreak = n.key.value.length >= options.tabWidth;
```

**Comment by j-f1** [comment] 2018-01-12 14:00
> +2 to allow for colon + space?

I feel like the line length benefit of breaking to get 1 or 2 characters shorter is minimal:

```js
//------|
({
  x: 'bar',
  x:
    'bar'

  xy: 'bar',
  xy:
    'bar'
})
```

**Comment by musakarakas** [comment] 2018-09-18 14:41
I found a workaround. Use template literals.
``x: `1234...` `` does not wrap.
Same applies to #2079. I was going to comment there but it's closed.

**Comment by hornta** [comment] 2019-12-29 19:16
I have a similar case where a longer line than printWidth yields a line break between properties
```js
const parameters = {
  "openid.claimed_id":
    "http://specs.openid.net/auth/2.0/identifier_select",
  "openid.identity": "http://specs.openid.net/auth/2.0/identifier_select",
  "openid.mode": "checkid_setup",
  "openid.ns": "http://specs.openid.net/auth/2.0",
  "openid.realm": "http://90.230.50.89:3000",
  "openid.return_to": "http://90.230.50.89:3000/login/handle"
};
```
I think it would me more desirable to skip the linebreak between key and value when mixed with non-broken `key: value`s like this:
```js
const parameters = {
  "openid.claimed_id": "http://specs.openid.net/auth/2.0/identifier_select",
  "openid.identity": "http://specs.openid.net/auth/2.0/identifier_select",
  "openid.mode": "checkid_setup",
  "openid.ns": "http://specs.openid.net/auth/2.0",
  "openid.realm": "http://90.230.50.89:3000",
  "openid.return_to": "http://90.230.50.89:3000/login/handle"
};
```

**Comment by hornta** [comment] 2019-12-29 19:18
I have a similar case where a longer line than printWidth yields a line break between properties
```js
const parameters = {
  "openid.claimed_id":
    "http://specs.openid.net/auth/2.0/identifier_select",
  "openid.identity": "http://specs.openid.net/auth/2.0/identifier_select",
  "openid.mode": "checkid_setup",
  "openid.ns": "http://specs.openid.net/auth/2.0",
  "openid.realm": "http://90.230.51.89:3000",
  "openid.return_to": "http://90.230.51.89:3000/login/handle"
};
```
I think it would me more desirable to skip the linebreak between key and value when mixed with non-broken `key: value`s like this:
```js
const parameters = {
  "openid.claimed_id": "http://specs.openid.net/auth/2.0/identifier_select",
  "openid.identity": "http://specs.openid.net/auth/2.0/identifier_select",
  "openid.mode": "checkid_setup",
  "openid.ns": "http://specs.openid.net/auth/2.0",
  "openid.realm": "http://90.230.51.89:3000",
  "openid.return_to": "http://90.230.51.89:3000/login/handle"
};
```

**Closed** 2021-03-02 23:43 UTC
Labels: area:object literals, lang:javascript, type:enhancement
