### ISSUE TITLE
Max line length doesn't seem to be working everywhere

### ISSUE THREAD

**Issue by garetmckinley** [prettier/prettier#1110] opened 2017-04-02 00:52 UTC
I'm working on implementing prettier into my open source react grid system [hedron](https://github.com/JSBros/hedron/tree/1.0.0). I noticed that the max line length isn't taking effect everywhere. I'm using all the default options, you can see my [format script here](https://github.com/JSBros/hedron/blob/1.0.0/package.json#L23).

```js
const containerDirectionError = "Container direction must be `horizontal` or `vertical`";

const Wrapper = styled.div`
  display: flex;
  flex-wrap: wrap;
  
  ${props => props.direction && `flex-direction: ${directionToFlex(props.direction)}`}

  ${props => props.alignSelf ? `align-self: ${props.alignSelf};` : null}
  ${props => props.justifyContent ? `justify-content: ${props.justifyContent};` : null}
  ${props => props.order ? `order: ${props.order};` : null}
`;
```

[Here is the link to my script in the prettier online parser](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20%40flow%5Cnimport%20React%20from%20%5C%22react%5C%22%3B%5Cnimport%20styled%20from%20%5C%22styled-components%5C%22%3B%5Cnimport%20%7B%20withLayout%20%7D%20from%20%5C%22.%2FLayoutProvider%5C%22%3B%5Cnimport%20passOn%20from%20%5C%22..%2Futils%2FpassOn%5C%22%3B%5Cn%5Cnconst%20containerDirectionError%20%3D%20%5C%22Container%20direction%20must%20be%20%60horizontal%60%20or%20%60vertical%60%5C%22%3B%5Cn%5Cnconst%20directionToFlex%20%3D%20direction%20%3D%3E%20%7B%5Cn%20%20if%20(direction%20%3D%3D%3D%20%5C%22vertical%5C%22)%20%7B%5Cn%20%20%20%20return%20%5C%22column%5C%22%3B%5Cn%20%20%7D%20else%20if%20(direction%20%3D%3D%3D%20%5C%22horizontal%5C%22)%20%7B%5Cn%20%20%20%20return%20%5C%22row%5C%22%3B%5Cn%20%20%7D%5Cn%20%20throw%20Error(containerDirectionError)%3B%5Cn%7D%3B%5Cn%5Cnconst%20Wrapper%20%3D%20styled.div%60%5Cn%20%20display%3A%20flex%3B%5Cn%20%20flex-wrap%3A%20wrap%3B%5Cn%20%20%5Cn%20%20%24%7Bprops%20%3D%3E%20props.direction%20%26%26%20%60flex-direction%3A%20%24%7BdirectionToFlex(props.direction)%7D%60%7D%5Cn%5Cn%20%20%24%7Bprops%20%3D%3E%20props.alignSelf%20%3F%20%60align-self%3A%20%24%7Bprops.alignSelf%7D%3B%60%20%3A%20null%7D%5Cn%20%20%24%7Bprops%20%3D%3E%20props.justifyContent%20%3F%20%60justify-content%3A%20%24%7Bprops.justifyContent%7D%3B%60%20%3A%20null%7D%5Cn%20%20%24%7Bprops%20%3D%3E%20props.order%20%3F%20%60order%3A%20%24%7Bprops.order%7D%3B%60%20%3A%20null%7D%5Cn%60%3B%5Cn%5Cnconst%20Container%20%3D%20(%7B%20children%2C%20...props%20%7D)%20%3D%3E%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3CWrapper%20%7B...props%7D%3E%5Cn%20%20%20%20%20%20%7BpassOn(children%2C%20child%20%3D%3E%20(%7B%5Cn%20%20%20%20%20%20%20%20xs%3A%20child.props.xs%20%7C%7C%5Cn%20%20%20%20%20%20%20%20%20%20(child.props.direction%20%3D%3D%3D%20%5C%22horizontal%5C%22%20%26%26%2012%20%2F%20children.length)%5Cn%20%20%20%20%20%20%7D))%7D%5Cn%20%20%20%20%3C%2FWrapper%3E%5Cn%20%20)%3B%5Cn%7D%3B%5Cn%5Cnexport%20default%20withLayout(Container)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)

Maybe you can shed some light on whether this is something I'm doing wrong or a bug inside prettier.

**Comment by vjeux** [comment] 2017-04-02 20:25
For 1) prettier doesn't know yet to put a \n after `=` when it doesn't fit.

```js
const containerDirectionError = "Container direction must be `horizontal` or `vertical`";
```

For 2) we're now inlining all the expressions inside of template literals because we had too many issues with them. The side effect is that those now do not fit into 80 columns. Thanks for giving us a concrete edge case. We haven't found the perfect solution so far :(

**Comment by garetmckinley** [comment] 2017-04-02 20:41
Alright, thanks for the heads up! I'll just have to take care of those lines manually for now. Hope you guys figure out a solution ☺️

**Comment by dburles** [comment] 2017-04-04 00:42
I'm also using styled-components and now there's a bunch of cases where the line lengths are very long indeed. @vjeux where is this issue being tracked?

**Comment by vjeux** [comment] 2017-04-04 14:43
@dburles search for issues related to template literals. There's a bunch of them with context. The problem is that we don't know of a good heuristic that would solve all the existing use cases right now.

**Comment by vjeux** [comment] 2017-04-05 19:32
A few other examples that go beyond 80 columns with VariableDeclarator.

```js
const publishersInfo$: Rx.Subject<SortedPublishersInfo> =
  new Rx.ReplaySubject(1);

const requestProgress$: Rx.Observable<UserEventsRequestProgress> =
  createProgressStream(userEvent$, publishersInfo$);
    
this.userEventsRequestProgressSubscription =
  createUserEventsRequestProgressStream(
    this.events$,
    this.publishersInfo$,
  ).subscribe(userEventsRequestProgress => {
    this.setState({
      userEventsRequestProgress,
    });
  });
```

**Comment by vjeux** [comment] 2017-04-06 23:44
More template literal related issues: https://github.com/prettier/prettier/issues/786

**Comment by vjeux** [comment] 2017-04-07 18:36
For 2), I tried remove the code that removes all the breaks and it looks like

```js

const Wrapper = styled.div`
  ${props =>
  props.direction && `flex-direction: ${directionToFlex(props.direction)}`}

  ${props => props.alignSelf ? `align-self: ${props.alignSelf};` : null}
  ${props =>
  props.justifyContent ? `justify-content: ${props.justifyContent};` : null}
  ${props => props.order ? `order: ${props.order};` : null}
`;
```

which is not ideal either

**Comment by vjeux** [comment] 2017-04-07 18:37
I'm curious, what was the original formatting that you wrote for it?

**Comment by garetmckinley** [comment] 2017-04-07 19:08
What do you mean by the original formatting?

The way the wrapper was originally written was as

```jsx
const Wrapper = styled.div`
  display: flex;
  flex-wrap: wrap;
  
  ${props => props.direction && `flex-direction: ${directionToFlex(props.direction)}`}

  ${props => props.alignSelf ? `align-self: ${props.alignSelf};` : null}
  ${props => props.justifyContent ? `justify-content: ${props.justifyContent};` : null}
  ${props => props.order ? `order: ${props.order};` : null}
`;
```

(this is legacy code from the old version, don't judge the ugly code haha)

Most of the time the way that *I personally* would format a styled block like this, would be like

```jsx
const Wrapper = styled.div`
  display: flex;
  flex-wrap: wrap;
  
  ${props => props.direction &&
      `flex-direction: ${directionToFlex(props.direction)}`}

  ${props => props.alignSelf
      ? `align-self: ${props.alignSelf};`
      : null}
  ${props => props.justifyContent
      ? `justify-content: ${props.justifyContent};`
      : null}
  ${props => props.order
      ? `order: ${props.order};`
      : null}
`;
```

**Comment by garetmckinley** [comment] 2017-04-07 19:12
As for the first line that's breaking `const containerDirectionError = "Container direction must be `horizontal` or `vertical`";`, couldn't prettier simply append a `\` at the end of the last word under 80 characters, so it would become

```
const containerDirectionError = "Container direction must be `horizontal` or \
`vertical`";
```

which is right under 80. It would try to break the sentence as close to the 80 char limit as possible.

**Comment by mo** [comment] 2017-04-08 13:18
It seems long regular string literals can also make prettier output longer than 80 lines, for example:
https://git.io/vSoqZ

...is the plan to have prettier chop such long string literals into pieces, or should it insert backslashes or?

**Comment by jlongster** [comment] 2017-04-12 13:38
The maximum line length is just a suggestion to prettier. It will wrap code when possible, but if it's not possible (or the result is simply uglier) it won't wrap it.

**Comment by garetmckinley** [comment] 2017-04-12 14:57
@jlongster really? The readme made it seem like max line length is the biggest thing prettier is supposed to enforce.

**Comment by mvolkmann** [comment] 2017-04-14 14:49
Should it currently be able to change this:
```js
const aVeryLongNameThatGoesOnAndOn = require('aVeryLongPathThatSeemsLikeItWillNeverEnd');
```
to this?
```js
const aVeryLongNameThatGoesOnAndOn =
  require('aVeryLongPathThatSeemsLikeItWillNeverEnd');
```

**Comment by vjeux** [comment] 2017-04-14 14:59
@mvolkmann We made what you suggested work and many people complained. Apparently it's accepted to let giant requires like this one go over 80 columns.

**Comment by jlongster** [comment] 2017-04-14 15:11
@garetmckinley What if you are 75 columns and then use the variable `longerThanFive`? We can't possible break up a variable name (assuming that we've broken up everything else on the line that we can.

The fact is that we can only break up so much. Even better example: what if you have a variable name that is 85 columns long? That's an insane example, but it illustrates that there cases which we just can't do anything. Any kind of constraint-based layout system has to give at some point where there is too much content that can't break up. Think of in browsers when you show an image that is wider than the containing div.

It enforces a maximum line length as much as it can. "suggestion" is too light of a word, but at the end of the day, that's what it is. We will wrap code as much as we can to try to make it fit, but it's not the end of the world if it goes over. Lots of times it's more readable to let things flow a little bit over, as is the case with the `require` example above (which I agree with).

**Comment by garetmckinley** [comment] 2017-04-14 15:14
I definitely understand that there will be edge cases, I hope it didn't sound like I was complaining or anything.

**Comment by tomatosource** [comment] 2017-04-15 15:28
One seemingly simple example I found:
```
const aFairlyLongVariableName = `${alsoPrettyLong} and some more and some more and ${anotherOne}`;
```
Could be resolved reasonably by dropping the literal on the next line indented, surrounded by parens or not.

**Comment by aboyton** [comment] 2017-05-07 23:00
To add to this discussion, I completely agree that you can't (automatically) make everything under a maximum line length limit (like 85 character variable names) and that prettier should instead take the maximum line length as a "suggestion".

But for declarations or assignments, like

```js
const aVeryLongNameThatGoesOnAndOn = this.someOtherObject.someOtherNestedObject.someLongFunctionName();
```
and
```js
this.someObject.someOtherNestedObject = this.someOtherObject.whyNotNestAnotherOne.someLongFunctionName();
```
it seems to me that it would be better (prettier) to break this onto two lines like
```js
const aVeryLongNameThatGoesOnAndOn =
  this.someOtherObject.someOtherNestedObject.someLongFunctionName();
```
and
```js
this.someObject.someOtherNestedObject =
  this.someOtherObject.whyNotNestAnotherOne.someLongFunctionName();
```
respectively.

Sadly when running prettier over our codebase at work I've discovered many of my colleagues love writing long lines like this and putting them onto one line makes for really long lines.

While I understand that people like writing require statements on a single line (say #841), I do think that the output from prettier would indeed be prettier if it broke declarations and assignments onto multiple lines. Any chances of this happening? It's presently blocking our adoption of prettier :( (I can move this discussion to a new ticket if you'd prefer.)

**Comment by mvolkmann** [comment] 2017-05-07 23:11
👍 I think some people have weighed in on this and said they like it the way it is. I wonder if they are in the majority.

**Comment by vjeux** [comment] 2017-05-21 21:58
The original issue is likely the same root cause as https://github.com/prettier/prettier/issues/1183

**Comment by vjeux** [comment] 2017-05-25 01:25
The two initial examples are now much better rendered. I'm going to close this issue since it's going in all directions. If there is something specific you want fixed, please open up a different issue :)

```js
const containerDirectionError =
  "Container direction must be `horizontal` or `vertical`";

const Wrapper = styled.div`
  display: flex;
  flex-wrap: wrap;

  ${props =>
    props.direction && `flex-direction: ${directionToFlex(props.direction)}`}

  ${props => (props.alignSelf ? `align-self: ${props.alignSelf};` : null)}
  ${props =>
    props.justifyContent ? `justify-content: ${props.justifyContent};` : null}
  ${props => (props.order ? `order: ${props.order};` : null)}
`;
```

**Closed by vjeux** 2017-05-25 01:25 UTC
Labels: bug
