### ISSUE TITLE
align chained methods to the property it was chained from.

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [prettier/prettier#4961] opened 2018-08-09 04:52 UTC
**Prettier@latest**
[playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAJhAHIQwAWOUA5gOo6UAqFcACgIYBOHAtvgAoAlPmAAdKPnyQoAZwgAbOADoFEGgIDkASTFjN-KOXw0I1GvhgQi1jlACelc-g4AjCOhj5GyzUIDcEgC+EhIysl7osnBKsrIA8q4AVnDY+AC8ohJSUTFwcWxcEAAOAIxI+JocmgA02fi5sbKFJQBMFZqutfWN+c1FxQDMHWCawYFQElBwAO74Lbw40QJc+YoAbnAZAHw2ZE60DMysnDy8AuKS+Mo3vXGJKdh1V3f9JQAsHYRjUEFCQhJlJQEAJhDt8NM5gslnAVmsFJtwat5AjYf8AVAgawoKCROldpD5kVFstkRstvj8GTUcJ-oDgTiwZTLlJKEU5oSAKJcIpcYQTP6AsAcGBgCgCOA88HhRQqSW8iU8-4gGogEq4aCyZCgbjs04ILUoDjrMyEFUgVw8MAAazgMAAysUOGBzMgYFx0HBVdRolwYIUODReBw3R6vSAkrIAB4AISttodfDgABlqHBkKgOApoqqnVxfcgLW57GooObilxqDAGIRKMgABwABlzRWidB4xULFfyks25tWAEd0DhVgGgyGkJns+HootQ57VbJzEoAIrocjpydZnMgGBuGt1pCtVXujg4BTmADCEF4wcLRmm5tyTDchqn0SCQSAA)

**Input:**
```jsx
function doNothingWithTheParam (param1, callback) {
  console.log('I\'m not going to do anything about it.');
  callback();
}

const uselessObject = {
  uselessProp1: 'a',
  uselessProp2: 'b',
  uselessProp3: 'c'
};

new Promise(resolve => doNothingWithTheParam({
  ...uselessObject,
  uselessProp4: 'd'
}, resolve))
.then(() => new Promise(resolve => resolve()))
.then(() => new Promise(resolve => resolve()))
.then(() => {
  throw new Error();
})
.catch(err => console.error(err))
```

**Output:**
```jsx
/** @format */

function doNothingWithTheParam(param1, callback) {
  console.log("I'm not going to do anything about it.");
  callback();
}

const uselessObject = {
  uselessProp1: "a",
  uselessProp2: "b",
  uselessProp3: "c"
};

new Promise(resolve =>
  doNothingWithTheParam(
    {
      ...uselessObject,
      uselessProp4: "d"
    },
    resolve
  )
)
  .then(() => new Promise(resolve => resolve()))
  .then(() => new Promise(resolve => resolve()))
  .then(() => {
    throw new Error();
  })
  .catch(err => console.error(err));
```

**Expected behavior:**

Prettier is indenting the `.then` chains, it should have been:

```jsx
/** @format */

function doNothingWithTheParam(param1, callback) {
  console.log("I'm not going to do anything about it.");
  callback();
}

const uselessObject = {
  uselessProp1: "a",
  uselessProp2: "b",
  uselessProp3: "c"
};

new Promise(resolve =>
  doNothingWithTheParam(
    {
      ...uselessObject,
      uselessProp4: "d"
    },
    resolve
  )
)
.then(() => new Promise(resolve => resolve()))
.then(() => new Promise(resolve => resolve()))
.then(() => {
  throw new Error();
})
.catch(err => console.error(err));
```

Notice that the `.then`s are aligned to the original property it was chained from.

**Comment by lydell** [comment] 2018-08-09 05:51
Hi, thanks for the issue! This has already been discussed in #2164.

**Comment by lydell** [comment] 2018-08-09 05:51
Duplicate of #2164

**Closed by lydell** 2018-08-09 05:51 UTC
