### ISSUE TITLE
Preserve line breaks in attribute values

### ISSUE THREAD

**Issue by zippoxer** [prettier/prettier#8179] opened 2020-04-28 13:07 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4B0oAEBYANgIYDOFAvLiALYkC0AHAZlCR3EwGYlwAHu3j0KTMAngAnAgAdBTAIzyYyggCMI09HGlMNTAEz4iZ81p16mMaWSgU5ZaVILxBaivQK9oa+nBYAK7eAmRYUADmTACsbkJqkXYAnrEADGl0psRUtCC64VlQAHzZACoAFmQwAOQU8i4wMMkAdPioAPRY2MUgADQgEHIwmNAUyKDO0hAA7gAKzgjjKGQkM2TJ4wMadmAA1nAwAMpOYByRyLZBcAMVMIwA6hWY8I5kkkdLLzgvycjgVH6IA4FD0MDmdki9DIyF4q1BAwAVhRBAAhXYHY5kAIAGW4sPhNxAyMER3OAgAikEIPACSQESAnNJQdJ-ndGEC5NIODAHph0DAKsgWGkBlyIKCHnY5P8uXAWdg4ECAI7U+AQobLECUJhQOCBQJAlyqzAuCFkKEwpBw+lE0H0TCXaTXAYUclwKk0pXWwkDGBkDR8gVCpBGP12TBcKIAYQg9Gh-3lMSBQVBZQDyxtDOw1wAklBdLAjmBucMAIIFo7NAR00EAXzrQA)

**Input:**

```html
<div
  class="ml-8 inline-flex items-center px-1 pt-1 border-b-2
         border-transparent text-sm font-medium leading-5 text-gray-500"
  css="dead"
>
  That's pretty.
</div>
```

**Output:**

```html
<div
  class="ml-8 inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium leading-5 text-gray-500"
  css="dead"
>
  That's pretty.
</div>
```

**Expected behavior:**

Line breaks inside attribute values should be preserved.

Often times in CSS frameworks like tailwind/tachyons you would see enormously long class attributes. If not for line breaks inside attribute values, line widths would sometimes go north of 300.

**Wrapping instead of preserving?**

I think a better solution would be to wrap input values into multiple lines automatically.

I've had the pleasure of working with [VS Code Svelte](https://marketplace.visualstudio.com/items?itemName=JamesBirtles.svelte-vscode) and to my surprise it automatically introduced line breaks into my long class attributes.

For example, it transforms this input:

```html
<div
  class="mx-4 bg-gray-200 rounded-full overflow-hidden shadow-lg transition duration-300 cursor-pointer hover:bg-gray-300 transform"></div>
```

Into this output:

```html
<div
  class="mx-4 bg-gray-200 rounded-full overflow-hidden shadow-lg transition
             duration-300 cursor-pointer hover:bg-gray-300 transform"></div>
```

I thought it's pretty nice.

However, I'm not sure if it could cause conflicts with some of prettier's supported framework. I know that in Vue, a line break in an attribute value would be syntactically significant if it's binded (when the attribute's name starts with a colon or `v-bind`).

**Comment by thorn0** [comment] 2020-04-28 14:55
Duplicate of #7863

**Comment by thorn0** [comment] 2020-04-28 14:55
See also PR #7865. Would be good to get some feedback about it.

**Closed by thorn0** 2020-04-28 14:55 UTC
