### ISSUE TITLE
Support range ignore for JS/TS files

### ISSUE THREAD

**Issue by jvanbruegge** [prettier/prettier#7436] opened 2020-01-26 13:42 UTC
Pretty simple, I autogenerate some type signatures and would like that whole block to be ignored. Currently I changed my generator to add ignore comments before every line, but ranges would be nicer

**Comment by evilebottnawi** [comment] 2020-01-27 10:29
Duplicate of #5287

**Closed by evilebottnawi** 2020-01-27 10:29 UTC

**Comment by jvanbruegge** [comment] 2020-01-27 10:34
Ah, sorry. I was searching for range ignore and thus did not find that one
