### ISSUE TITLE
`prettier-ignore-start` and `prettier-ignore-end` is ignored on html

### ISSUE THREAD

**Issue by Dexus** [prettier/prettier#12989] opened 2022-06-10 13:39 UTC
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRGYDOMAhgTDtgHwA6UG2HAGUA8gFkAogBUAEgEkAcgHEcAQQCqUkZiUSFEgEqqpEgCI4AQgE0cWkQBkhnYVNUGpnTLyjAApDlIAMxwwGAAPADoYAhYoRgAbFjJoAGk4AE8cXwBfPh4YPxxGYhwWADcWUkSAI3i4KRi4xOSoHABeHABtAF0s3Kh8v1xA+hx46moA1tDIxlJ4CMSoagBXFmo4Rk4cvIGYQYBiXGKOaNiEpLgAE3UCeJwYCAeACzgcZ4gAWzg8dbeIYIwZ5JMaxVZ-HDVTJXOCBFgreIcTAHfr5Qa+Y4lM5NS43O7tHA8EAAeiJOAA1GMJhFSFcKYSSWTMDsBntDpiOGAVgQiLBQcs1hsQolGFtkaj9gUMUUSixQqQynAAMIirYdImkRiYOVkRVkoJU6g0ultDozRYQMAsOo4ODxYoMpkstEFI5jCAQPAvAgQFbUZ6leL3IFvSCwBAcAEvN5zeCcFF5SVDHAjAgBeCfKYhcIRSBBuDy6CMCLW+7MiUu4BusCvMAAaxwnySNc28dRbKT0oN8zgnwiVySLAAPsDGAAFH14CgwdIACgA5NiLi00ul5wBKUpQOk9vsD1hRRrL0ipDI4dAdefzrc7jP9weH87NE9QVftM05pfP0+ZWK33v3ge8SWtabymoaxrbBWkrohyDxHs01y3PcHS7hE3Jls6MGdjKHDlJUNR1A0T5JC+BKzvhVQsLU9QIaR0ARHgKyMM8C6oCwwosKKbQalA8SkFAcCYLUloNvAYQwJgYRbHQmArNuFD8YJODzpSOoKsqqoUvOZLPEQgQ8SAqnwSR8B4vc5I6SAXDGeMRpQCw3zaagxIsDZ64ADSlBUVE0cROItJuWGVtKCBXAa5aJrBtrbqmUG7NFYVxZFrLogEwSUYRtGmWRQ5jAg1BAjgXA4AAjH0UUwKg4VlJx3FEmGrACRQjZhNqKyPPg6SYAATES3guvk1UKnVjCGSJ9YPHAElSYw-WVZWwDZrMPadOawFWnU3QRAA+jAEQQCGBA7Y1EY7Us4IbIwO2ZdRNqUmSZLZNBIXDKMSkNgJ3kEXd2UBWRKWDdhwBLR9OB5YwLCBG8z0LcDXbBHQHDAZ6ixcUiwXYYtKledesMdkDyZhRFmOvTFVzJaTVXEjVA2Si5tOJkT24k-0zPhcEKUCLgoiSLIigqBoWg6HohjGGYlg2HYjjOHo5jcHw3P4EQJDkJQNB0AwYWeFwIAeSAnotIwyCgGwPoAO5jmwCDGyg1rmyw6TG-r1QxPWxBCI5cD2M1yDRCscAu27dYe78YACdQyBwvagcgL21TXDCVz2GCgpwAAYvQTaq8syAgPCjx6yAzwwJ88QAOrPD2jBh3AQg2-MCrzOkedgKKRcCcU7ATusTZR9axT6wAVowYRCBHdQAIorIdcD9zH+u-AQXd5yXZdF4QAkwOXtJAsgAAcAAMi8+sU5cxHgeeEJsFCKkXACOM-wBOnq2-nWqCdc1xF0Qj+kEQPdqB9yQNHQeIBiifFIPPMBcxlhTyfnPJA-tY6sGqDvK4e8kA9X1mcKoEclRfGAXHRgABWIuzF6jUVtqA2OZQA5yAUrAIQYACCkDwDAVQ24hAzjqNAuAz0gA)

```sh
--parser html
--no-semi
--single-quote
--no-bracket-spacing
--bracket-same-line
```

**Input:**

```html
<!-- prettier-ignore-start -->
<!-- SOMETHING AUTO-GENERATED BY TOOLS - START -->
{% if ctx.translationKey %}
	{% set availableTranslation = [] %}
	{%- for lgg in ctx.site.languages -%}

		{#- set translatedUrl to the homepage of that language by default -#}
		{%- set translatedUrl = "/" + lgg.id + "/" -%}

		{#- set current language class -#}
		{%- set activeClass = "is-active" if lgg.id == ctx.locale else "" -%}
		{#- loop through all the content of the site -#}
		{%- for item in ctx.collections.all -%}
			{#- check matches -#}

			{%- if item.data|hasProperty('translationKey') and item.data.translationKey != '' and item.data.translationKey == ctx.translationKey and item.data.locale == lgg.id -%}
				{%- set translatedUrl = item.url -%}
				{% set availableTranslation = (availableTranslation.push('<a class="inline-block text-xs no-underline '+ activeClass +'" href="'+ translatedUrl +'">'+ lgg.name +'</a>'), availableTranslation) %}
			{%- endif -%}
		{%- endfor -%}

	{%- endfor -%}

	{% if availableTranslation | length > 1 %}
		<div class="container mx-auto py-2">
			<div class="block text-xs">
				{{ ctx.site[ctx.locale]._t.other_content_languages_available + " " }}
				{%- for link in availableTranslation -%}
					{{ link | safe }}
					{%- if not loop.last -%}
						{{ ', ' }}
					{%- endif -%}
				{%- endfor -%}
			</div>
		</div>
	{%- endif -%}
{%- endif -%}
<!-- SOMETHING AUTO-GENERATED BY TOOLS - END -->
<!-- prettier-ignore-end -->
```

**Output:**

```html
<!-- prettier-ignore-start -->
<!-- SOMETHING AUTO-GENERATED BY TOOLS - START -->
{% if ctx.translationKey %} {% set availableTranslation = [] %} {%- for lgg in
ctx.site.languages -%} {#- set translatedUrl to the homepage of that language by
default -#} {%- set translatedUrl = "/" + lgg.id + "/" -%} {#- set current
language class -#} {%- set activeClass = "is-active" if lgg.id == ctx.locale
else "" -%} {#- loop through all the content of the site -#} {%- for item in
ctx.collections.all -%} {#- check matches -#} {%- if
item.data|hasProperty('translationKey') and item.data.translationKey != '' and
item.data.translationKey == ctx.translationKey and item.data.locale == lgg.id
-%} {%- set translatedUrl = item.url -%} {% set availableTranslation =
(availableTranslation.push('<a
  class="inline-block text-xs no-underline '+ activeClass +'"
  href="'+ translatedUrl +'"
  >'+ lgg.name +'</a
>'), availableTranslation) %} {%- endif -%} {%- endfor -%} {%- endfor -%} {% if
availableTranslation | length > 1 %}
<div class="container mx-auto py-2">
  <div class="block text-xs">
    {{ ctx.site[ctx.locale]._t.other_content_languages_available + " " }} {%-
    for link in availableTranslation -%} {{ link | safe }} {%- if not loop.last
    -%} {{ ', ' }} {%- endif -%} {%- endfor -%}
  </div>
</div>
{%- endif -%} {%- endif -%}
<!-- SOMETHING AUTO-GENERATED BY TOOLS - END -->
<!-- prettier-ignore-end -->

```

**Expected behavior:**

same result as Input

**Comment by thorn0** [comment] 2022-06-15 07:26
Duplicate of #5508

**Closed** 2022-06-15 07:27 UTC
