### ISSUE TITLE
Do not wrap single line comments, e.g. //eslint-disable-line

### ISSUE THREAD

**Issue by zastavnitskiy** [prettier/prettier#3363] opened 2017-11-30 15:28 UTC
**Prettier 1.8.2**
In some cases we want to keep comment on the same like, for example, //eslint-disable-line comments.

Prettier messes it up by moving comment to the next line.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEA+oQM4QC2chA7nDgE4AmhUAhpcQBQCU+wA9P3xwSAGxywAtIxwlWAI1FxJ4qHHxQIkzIzj0SkessasoAcyX4AOlHz4jMdPVsBGANw2Avh6ggANCAQAA640CTIoKwkMMiorKIkcAHy9KxgANZwMADKQWkSZsgw9OhJIIwQYLHxiQESifQwAAqpZuSs1QllAFYkAB4AQqkZWdnscAAyEnCdtYHoMEELAEyzZXn6esgg8goAnqLQ-iBB9BIwAOo4jDAAFsgAHAAMAacQiRepQUUlZUYAjugGHAWqw2h0kHEugFEuQcD9SjCCkoAIroCDwNYBGAKK43e5IZbY1I4VRmADCFHa200amO6ESABUFOFITU4J5PEA)

**Input:**
```jsx
function __some_weird_name__() {// eslint-disable-line no-underscore-dangle 
  return 1;
};

```

**Output:**
```jsx
function __some_weird_name__() {
  // eslint-disable-line no-underscore-dangle
  return 1;
}

```

**Expected behavior:**
```jsx
function __some_weird_name__() { // eslint-disable-line no-underscore-dangle
  return 1;
}

```

**Comment by josephfrazier** [comment] 2017-11-30 15:51
Duplicate of https://github.com/prettier/prettier/issues/1267, as well as some other issues you can find by searching for 'eslint-disable-line': https://github.com/prettier/prettier/search?q=eslint-disable-line&type=Issues

**Closed by josephfrazier** 2017-11-30 15:51 UTC
