### ISSUE TITLE
Prettier removing necessary semi-colon in front of type assertion

### ISSUE THREAD

**Issue by JamesHenry** [prettier/prettier#1819] opened 2017-05-30 12:55 UTC
This is fairly gnarly source, but it is real so we should consider it if possible 😄 

```ts
this.currentCreative['landing_pages'] = this.currentCreative['landing_pages'] || []
;(this.currentCreative['landing_pages'] as any)[0] = state.updatedFormData[stateKey].currentValue
```

```this.currentCreative['landing_pages']``` is being "cast" (really a type assertion) to `any` and having it's `[0]` property accessed.

In such a case you cannot use the `<any>` notation for the assertion, and must instead wrap it in parens and use the `as` syntax.

Because the code is written in a `no-semi` style, this is one of the few cases where there is an extra consideration. A newline starting with a `(` would join up with the previous line, so the workaround is to add a preceding semi-colon.

Running the code through prettier it becomes...

```ts
this.currentCreative['landing_pages'] =
	this.currentCreative['landing_pages'] || []
(this.currentCreative['landing_pages'] as any)[0] =
	state.updatedFormData[stateKey].currentValue
```

...which is now broken, because the semi-colon has been removed.

This "phenomenon" could certainly occur in a pure JS context too, do we have any precedent of handling such cases for `no-semi` style code?

**Comment by azz** [comment] 2017-05-30 13:08
Take a look at [`exprNeedsASIProtection`](https://github.com/prettier/prettier/blob/master/src/printer.js#L4462).

**Comment by josephfrazier** [comment] 2017-05-30 15:18
Maybe I'm misunderstanding the issue, but I think this is fixed on master (eeb8616e3cc9480af09afc629a7531c3c602e2df):

```bash
$ git log -n 1
commit eeb8616e3cc9480af09afc629a7531c3c602e2df (HEAD -> master, origin/master, origin/HEAD)
Author: Christopher Chedeau <vjeuxx@gmail.com>
Date:   Mon May 29 16:59:45 2017 -0700

    Add parenthesis for single arg types with generics (#1814)

    Fixes #1813
```

```js
$ cat test.js
this.currentCreative['landing_pages'] = this.currentCreative['landing_pages'] || []
;(this.currentCreative['landing_pages'] as any)[0] = state.updatedFormData[stateKey].currentValue
```

```js
$ ./bin/prettier.js --parser typescript --no-semi test.js
this.currentCreative["landing_pages"] =
  this.currentCreative["landing_pages"] || []
;(this.currentCreative["landing_pages"] as any)[0] =
  state.updatedFormData[stateKey].currentValue
$
```

**Comment by JamesHenry** [comment] 2017-05-30 15:23
I can't rerun today I'm afraid, but for completeness for the issue, I installed:
```
yarn add prettier@git://github.com/prettier/prettier.git#eeb8616e3cc9480af09afc629a7531c3c602e2df
```

...and ran:

```
./node_modules/.bin/prettier --parser typescript --single-quote --trailing-comma all --use-tabs --tab-width 1 --no-semi --write
```
on all the source files

**Comment by vjeux** [comment] 2017-05-30 16:29
I can't reproduce either :(

We've had quite a few fixes for `as` keyword ( https://github.com/prettier/prettier/commit/1e351436dac27b7c5ae84506bcfbf177b047a3cf https://github.com/prettier/prettier/commit/3d964b18bb613432f701679aceb7693842458882 https://github.com/prettier/prettier/commit/e22bd008153bb059820e155e5a5d492cc145e1ef https://github.com/prettier/prettier/commit/a446cf18ce787e6087d9ee25668b1a8bb042ebb7 ) but I think our house should be in order now.

Feel free to re-open if you can find a repro.

**Comment by JamesHenry** [comment] 2017-06-03 11:04
@josephfrazier @vjeux I have reproduced it - it turns out the fact that the code is within a switch case is significant:

https://prettier.github.io/prettier/#%7B%22content%22%3A%22switch%20(true)%20%7B%5Cn%20%5Cn%20%20case%20true%3A%5Cn%20%20%20%20%5Cn%20%20%20%20this.currentCreative%5B'landing_pages'%5D%20%3D%20this.currentCreative%5B'landing_pages'%5D%20%7C%7C%20%5B%5D%5Cn%3B(this.currentCreative%5B'landing_pages'%5D%20as%20any)%5B0%5D%20%3D%20state.updatedFormData%5BstateKey%5D.currentValue%5Cn%20%20%20%20%5Cn%20%20%20%20break%5Cn%20%20%20%20%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by azz** [comment] 2017-06-03 11:16
Looks like this isn't a TS-specific issue.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22switch%20(true)%20%7B%5Cn%20%20case%20true%3A%5Cn%20%20%20%20this.y%20%3D%20z%20%7C%7C%20%5B%5D%5Cn%20%20%20%20%3B%5B%5D.forEach(console.log)%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

@vjeux any reason `SwitchCase` doesn't use `printStatementSequence()`?

**Comment by vjeux** [comment] 2017-06-03 20:39
@azz no idea but the code that prints switch case has been responsible for a lot of issues in the past, so it has likely not be very well though of and would probably benefit from printStatementSequence.

**Comment by josephfrazier** [comment] 2017-06-06 21:53
Fixed in https://github.com/prettier/prettier/commit/0cfd772fd28475fcd20eb52eaf5ccaff020aa7c2 (#2008)

**Closed by josephfrazier** 2017-06-06 21:53 UTC
Labels: bug, high-pri
