### ISSUE TITLE
Styled Components pseudo-selectors issue

### ISSUE THREAD

**Issue by dvlasenko96** [prettier/prettier#7882] opened 2020-03-26 10:25 UTC
There is unexpected space after `:not`, which breaks the ts build.

**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wEl4BbPAXjxIE8AbOAEwDoWBLANwANeA3AB0oI9FlwFoJPABlOM2g2bsufEXk14uRDIwCG9JHgBmzNMKhbT5gLRdscMDE7RjkRgFcKUS9YAkwORwFAC+SFAQMAAUSCac2CS2YAAWnIwsAJR4wBrWWhT62ADmnFC2MBAYxgCMAAwYFnmaoSKCIAA0IFUu0sigRdgQAO4ACkUIRMgg+ozDhlNdAEbY+mAA1nAwAMoYa2XFyDDYnnBdKTAUjADqafC6a3Dbk5wu3K-002BEiyBlRHBcKNVsVCsgTLMAV0AFZENAAIVWGy2230FDg8igcHBkLOIFhaG2B2YAEVPFFsXFcV09olAdMlvolnBGJ0QBhsGUYNdOCwYClkAAOOo0oYA66rDDTDlwAHYbjYroAR3J8GBVSmKH0RFsWNYrDZjhVCTgwP0oP0OMYUJAAIonCOJzxRGJcDJFKtNpgTJ5fIFSAATF1jvp0gcAMIQChglCygCsbM8AIAKkzNRDrXjuKdSFAWAgdmBORgYABBPPbGBMSkZgGhUJAA)
```sh
--parser babel
```

**Input:**
```jsx
export const Item = styled.div``;

export const List = styled.div`
    display: flex;
    flex-direction: column;
    ${Item}:not(:first-child) {
        margin-top: 10px;
    }
`;
```

**Output:**
```jsx
export const Item = styled.div``;

export const List = styled.div`
  display: flex;
  flex-direction: column;
  ${Item}:not (:first-child) {
    margin-top: 10px;
  }
`;

```

**Expected behavior:**
```jsx
export const Item = styled.div``;

export const List = styled.div`
  display: flex;
  flex-direction: column;
  ${Item}:not(:first-child) {
    margin-top: 10px;
  }
`;

```

**Comment by dvlasenko96** [comment] 2020-03-26 10:27
Same issue with:
```
    ${Item}:nth-of-type (2) {
        flex-grow: 1;
    }
```

**Comment by thorn0** [comment] 2020-03-26 13:18
Duplicate of #7826

**Closed by thorn0** 2020-03-26 13:18 UTC
