### ISSUE TITLE
Is there a way to format the ts code into the following style?（typescript）

### ISSUE THREAD

**Issue by rxliuli** [prettier/prettier#9965] opened 2020-12-28 13:17 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACACgQwCcBnOQgUUMIkIB4AVbOAD3igBNjtiZCBLKAHMAfNgC82YEyo0k2XgFccAX2wAybPQA6sTDnL4YAdQAWfeMQz4wcWgGUYhnCzaduvASPHv+QpqwQ3BycdbGwAfjwiUgoZOgByA2MzCysbbEEIGAyEMj4wH095PXjhUOw5YPh-Vy4AA2wAEmABADMybCq4ZQaAH2w6rR1mto6unvLIpNNzOEtrWy6yqDDKx3gddCxsAEF2dgBpODQANXwAGyVacoBZOABbCBrArgAlOEhCdloeX0EAGmw+CgaGE-3KRzQzw4XF+nnBK2wZ0uzgCMKBIJ0ogkd0e6kk2AA2gdsAJsJCALpyZFKbDKTZ6KIkOAAKWI0AA8gAjABWHxg10RXWhbjhQgRYVxTxcL2w70+3zFAIxoO8wHpUGxhT8MvRXUmTJilGoCQIzLZnN5-IyWRyUDyBSVxSwpXKcmmKTmaUW6zgol1bjqyhGUHahE6vomiMihKlgK6FLd2A9s3mNnsvv9aMDWhAIbD5OO9LzLVDY0jg2jycMM1SCwzTiztQGSHz5acUbCYUiZtIFqgNJ9jZFXEJo3Dg8BdTb4fGdUTiK7EWryVT3ob8Cbsrq-xnEY7laXS570VZ7Kg3L5YAFXUBe0Ox0HtDjhbQgMHwmWR677prnrTQ6biOAzBqWBZzuU34xvekJPi+kLvhcShgvu8ALt+qyGmQxo0LQdS9melpXtkhAfHAfAAG5wOw2AKPazBYNe1HyBAADWCByM0c5fkecgEbEJp4QR-aDtgpEwAohD2jRdEsIx8A0RRSE4K0shNMA3GQRUWECbh+Gnv2l7WqRNiUcxskMfyzEwGxHHqZpiJ8aeul0Pp5rnkZ15iWRZkyfR8nWbZUCcRpFbLFsODCeeOxUPgaCCmEwoBrCHjircDzStmXDAmghIUt4eVYt4TrJahcAGvxOGmgZ0WxVCmTZIIuT8I6qWCM6cCuo5K61l69ZLMB857hBVaxhl8a+uh2lRdAT4DaVY5lhOylTsNFZTVMf5rv1maDbuYHtvAnZdie7nQDFhBxbQKZ1umSyAoSAB0z0voOFI8ZhN19Xdu2lUNB2zhWWkxk9L3jUiykUhNThTZhlVxEJNXnXV3mmVRflyVZNE2exwX2WFSbw4Jbl9ueoniZJ0m0f5WPYEpKLYKphAhQ5EVYSJykbqizZKlqJVZWVFXOVVtDxDNA7KTajXNfk2rtRFXWfVtt2AX6g1QAo5znGtB4GoSGta9DaFJl9AFc1u6KDCW44QyixY60dh7LoSk5lVNv6rir5uDYSDvdE7p2k8jl3xUsJvK99qsW4GwB+8dgeEReVrXubhPCwjJOJ+TPno9TmNMdjQUswTujbOLDDAbz3ji0+9DR1wNvvMQmswAaTct8Bi0Fq7Sqw8ug5aXI7fnNkpVE7hOUfcuw+t4u03p4JYtIxLDMU1J5k0wXcpzC3ivz8yLmizXktr1TdHjpdXLnDgM9dQy2z9tXy+i1IubsWgACMuZyISub00oX8QCAgNucKG2A37HAAEzf3ASAf+cBoEgDpKUbAAB6VBHVsCPwkFId+H8f5-2UoA4BmtQEAG46T4lwVAuQhCUSIIocoIBIAIAYBgHwaAxBkCgCINQAA7maBAXCUAXD4XFLh-wQBckumAdiMA7BpE8MgRQcBJEPC5NRdg1EAAywJBAKHwE1AAYjQe4hh2FCGQCAfACgbLMJMDAe45xeoATsEI8wlFzBoCsWAYgEiQACBiDAXAl1BBmOQK0C4pBJE8mIMwAAQjIuRdh8D3DgNogQcAIlRNUSAWJzA7CeGvgARQUFkLJSBInnGiSAKwB8rERWIGAfgbDmEYF8MYPg7AYAmGQB-SBAAGSR7SICkCMJdDAVj2lzDIFRZhABHMp8AQmsOEdY4gABae01FqLMNIosvgpEQmGPCZUnJkjSD3D4MowgSgLlFLgKU8p2Tqm5McFyIwXSenIEgZI3g+A+DnE8AAYQgPcU5IA5gAFZmEKFIPQfAXJhFVJqRRJQABJDgCB5HNL4GwnYHAHBoGvi80gyhlBAA)
```sh
--parser typescript
--print-width 120
```

**Input:**
```tsx
type ParserError<T extends string> = { error: true } & T
type EatWhitespace<State extends string> = string extends State
  ? ParserError<'EatWhitespace got generic string type'>
  : State extends ` ${infer State}` | `\n${infer State}`
  ? EatWhitespace<State>
  : State
type AddKeyValue<
  Memo extends Record<string, any>,
  Key extends string,
  Value extends any
> = Memo & { [K in Key]: Value }
type ParseJsonObject<
  State extends string,
  Memo extends Record<string, any> = {}
> = string extends State
  ? ParserError<'ParseJsonObject got generic string type'>
  : EatWhitespace<State> extends `}${infer State}`
  ? [Memo, State]
  : EatWhitespace<State> extends `"${infer Key}"${infer State}`
  ? EatWhitespace<State> extends `:${infer State}`
    ? ParseJsonValue<State> extends [infer Value, `${infer State}`]
      ? EatWhitespace<State> extends `,${infer State}`
        ? ParseJsonObject<State, AddKeyValue<Memo, Key, Value>>
        : EatWhitespace<State> extends `}${infer State}`
        ? [AddKeyValue<Memo, Key, Value>, State]
        : ParserError<`ParseJsonObject received unexpected token: ${State}`>
      : ParserError<`ParseJsonValue returned unexpected value for: ${State}`>
    : ParserError<`ParseJsonObject received unexpected token: ${State}`>
  : ParserError<`ParseJsonObject received unexpected token: ${State}`>
type ParseJsonArray<
  State extends string,
  Memo extends any[] = []
> = string extends State
  ? ParserError<'ParseJsonArray got generic string type'>
  : EatWhitespace<State> extends `]${infer State}`
  ? [Memo, State]
  : ParseJsonValue<State> extends [infer Value, `${infer State}`]
  ? EatWhitespace<State> extends `,${infer State}`
    ? ParseJsonArray<EatWhitespace<State>, [...Memo, Value]>
    : EatWhitespace<State> extends `]${infer State}`
    ? [[...Memo, Value], State]
    : ParserError<`ParseJsonArray received unexpected token: ${State}`>
  : ParserError<`ParseJsonValue returned unexpected value for: ${State}`>
type ParseJsonValue<State extends string> = string extends State
  ? ParserError<'ParseJsonValue got generic string type'>
  : EatWhitespace<State> extends `null${infer State}`
  ? [null, State]
  : EatWhitespace<State> extends `"${infer Value}"${infer State}`
  ? [Value, State]
  : EatWhitespace<State> extends `[${infer State}`
  ? ParseJsonArray<State>
  : EatWhitespace<State> extends `{${infer State}`
  ? ParseJsonObject<State>
  : ParserError<`ParseJsonValue received unexpected token: ${State}`>
type ParseJson<T extends string> = ParseJsonValue<T> extends infer Result
  ? Result extends [infer Value, string]
    ? Value
    : Result extends ParserError<any>
    ? Result
    : ParserError<'ParseJsonValue returned unexpected Result'>
  : ParserError<'ParseJsonValue returned uninferrable Result'>

type Json = ParseJson<'{ "key1": ["value1", null], "key2": "value2" }'> // type Json = { key1: ["value1", null]; } & { key2: "value2"; }
```

**Output:**
```tsx
type ParserError<T extends string> = { error: true } & T;
type EatWhitespace<State extends string> = string extends State
  ? ParserError<"EatWhitespace got generic string type">
  : State extends ` ${infer State}` | `\n${infer State}`
  ? EatWhitespace<State>
  : State;
type AddKeyValue<Memo extends Record<string, any>, Key extends string, Value extends any> = Memo &
  { [K in Key]: Value };
type ParseJsonObject<State extends string, Memo extends Record<string, any> = {}> = string extends State
  ? ParserError<"ParseJsonObject got generic string type">
  : EatWhitespace<State> extends `}${infer State}`
  ? [Memo, State]
  : EatWhitespace<State> extends `"${infer Key}"${infer State}`
  ? EatWhitespace<State> extends `:${infer State}`
    ? ParseJsonValue<State> extends [infer Value, `${infer State}`]
      ? EatWhitespace<State> extends `,${infer State}`
        ? ParseJsonObject<State, AddKeyValue<Memo, Key, Value>>
        : EatWhitespace<State> extends `}${infer State}`
        ? [AddKeyValue<Memo, Key, Value>, State]
        : ParserError<`ParseJsonObject received unexpected token: ${State}`>
      : ParserError<`ParseJsonValue returned unexpected value for: ${State}`>
    : ParserError<`ParseJsonObject received unexpected token: ${State}`>
  : ParserError<`ParseJsonObject received unexpected token: ${State}`>;
type ParseJsonArray<State extends string, Memo extends any[] = []> = string extends State
  ? ParserError<"ParseJsonArray got generic string type">
  : EatWhitespace<State> extends `]${infer State}`
  ? [Memo, State]
  : ParseJsonValue<State> extends [infer Value, `${infer State}`]
  ? EatWhitespace<State> extends `,${infer State}`
    ? ParseJsonArray<EatWhitespace<State>, [...Memo, Value]>
    : EatWhitespace<State> extends `]${infer State}`
    ? [[...Memo, Value], State]
    : ParserError<`ParseJsonArray received unexpected token: ${State}`>
  : ParserError<`ParseJsonValue returned unexpected value for: ${State}`>;
type ParseJsonValue<State extends string> = string extends State
  ? ParserError<"ParseJsonValue got generic string type">
  : EatWhitespace<State> extends `null${infer State}`
  ? [null, State]
  : EatWhitespace<State> extends `"${infer Value}"${infer State}`
  ? [Value, State]
  : EatWhitespace<State> extends `[${infer State}`
  ? ParseJsonArray<State>
  : EatWhitespace<State> extends `{${infer State}`
  ? ParseJsonObject<State>
  : ParserError<`ParseJsonValue received unexpected token: ${State}`>;
type ParseJson<T extends string> = ParseJsonValue<T> extends infer Result
  ? Result extends [infer Value, string]
    ? Value
    : Result extends ParserError<any>
    ? Result
    : ParserError<"ParseJsonValue returned unexpected Result">
  : ParserError<"ParseJsonValue returned uninferrable Result">;

type Json = ParseJson<'{ "key1": ["value1", null], "key2": "value2" }'>; // type Json = { key1: ["value1", null]; } & { key2: "value2"; }

```

**Expected behavior:**

![image](https://user-images.githubusercontent.com/24560368/103216845-067e0480-4952-11eb-9305-d938a187d2fd.png)

**Comment by kachkaev** [comment] 2020-12-28 16:43
Duplicate of #5814

**Closed** 2020-12-29 07:24 UTC
Labels: lang:typescript, type:duplicate
