### ISSUE TITLE
[JS] Diff between strings with backticks and double (or single) quotes

### ISSUE THREAD

**Issue by regseb** [prettier/prettier#14501] opened 2023-03-12 15:11 UTC
in JavaScript, strings with `` `backticks` `` have a different formatting than strings with `"double"` or `'single'` quotes.

**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATCBXAIwBs4B9UzAXkwB0RsHGnmXW32O26BuGqSKBkxoAllADmJclUwByNAsVLlK1WvUa1s3v3RYCAQzABrGCJMyABgRu279h46fOXTyzpAAaEBAAOZ9GRQAwAnEIgAdwAFUIQ0ZBADIgiDAE947wIQo2M4GABlAwBbOAAZMThkADMktDhM7JM8-N8jMXFkGBC8epA4IoI4BiHSgwk8A3E4ADEIEKKDGDMJBIM8GAgvEAALGCKiAHVtkXg0VrA4fLiTkQA3E9SEsAUtsTqQmCjs8QXq2t6AFZoAAe+XaJAAingIPA-kQ6t5WiF3glDIMiFtfCExDADiJsDBtsgABwABkR4TqB2yvgSWLg71ulW8AEdofAvn54igDGgALRQOBDIZbEJwNkiMVfSa-JA1eG9OpFESdbqK8FwACCS2xBHWcCicBC5UFcIRIFEEkh7Mqcv+3hgBgIeIJRKQACYHdkRER2gBhCBFWV9NAAVi2eDqABUndz5ebbj0AJJQbAIApgbH+TWp-IwVIkM1wAC+xaAA)

```sh
--parser babel
```

**Input:**

```JavaScript
const double__ = "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd";
const single__ = 'sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss';
const backtick = `bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb`;

```

**Output:**

```JavaScript
const double__ =
  "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd";
const single__ =
  "sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss";
const backtick = `bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb`;

```

**Expected behavior:**

```JavaScript
const double__ =
  "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd";
const single__ =
  'sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss';
const backtick =
  `bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb`;

```

**Comment by thorn0** [comment] 2023-03-20 16:40
Duplicate of #12408

**Closed** 2023-03-20 16:40 UTC
Labels: type:duplicate
