### ISSUE TITLE
AngularJS '.name' non-optimal formatting in chained calls

### ISSUE THREAD

**Issue by MrJohz** [prettier/prettier#5808] opened 2019-01-28 14:23 UTC
**Prettier 1.16.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgEMoBzAVwBtCd8AzHCdfAcmPKp2YG4AdKPuAA9sefABM4tQpQJtK1PviX4AdOghjKcABTNMhEnADOKgEaEwAawoQSK1EaNk4AWWIG46BDGYAafADaAPQAVCrhIUEAugCUisoqkLAMFBRwOLouAJ4AwtAwKWmc-tl5yRCp6XFQyqq0qBTwGczoWQBiDU1++NkdjekAIpKoUKgwqNDVtSr1-c2tAMpwSWJ9XSVZSytrg8Oj45PxPDAqUIReXCC+IBCYB1BGyKDUDADuAArUCI8ohABuEFQYiuIFMOAsljgMAW+jAIxIyAKzmuAAsYOgKAB1FFjYywuBLB5jVB-MZZZDgRwgkZGdIwd7gkjoQjIKQUWnXABWRkEACFwVYoQtznAADIjOCswjsuBcnkLeFpACKZAg8ClMuu+hwtJwFPMpiyNigIMwOBGMExQJgKOQAA4AAxahi0zHgzAUs3GdJ-SXXHBwACOZFQAYZBmZGo5IFp6FQiJwyJjirgKrVkqQbOjMEIpitYhtyAATNcCoQGvC8uhIygoNA-SAyLSACq5n5ZuAAX07QA)
```sh
--parser babylon
```

**Input:**
```js
import angular from 'angular';

export default angular
    .module('pages.backlog.issueManagement', [/*...*/])
    .controller('MyController', MyController)
    .filter('myFilter', MyFilterDefinition)
    .filter('mySecondFilter', MySecondFilterDefinition)
    .name;
```

**Output:**
```jsx
import angular from "angular";

export default angular
  .module("pages.backlog.issueManagement", [
    /*...*/
  ])
  .controller("MyController", MyController)
  .filter("myFilter", MyFilterDefinition)
  .filter("mySecondFilter", MySecondFilterDefinition).name;

```

**Expected behavior:**

When using AngularJS modules and a JS module bundler, it is convention to export modules in the format written above - a module definition (`angular.module('name', [deps])`), followed by a series of components, controllers, filters, etc, with the last element in the chain being the `.name` attribute.  This `.name` part is very important.

However, when Prettier sees this chained syntax, it tries where possible to put the `.name` on the same line as the previous definition.  Here you can see that it combines with the previous declaration of a filter.  I assume this is because prettier [aims to fill each line where it makes sense](https://prettier.io/docs/en/rationale.html#print-width).  However, I would argue that in this case, this produces harder-to-read code, precisely because this last line is so easy to lose in the clutter of the previous line.  I think the `.name` part should go on its own line (as shown in the input example above).

I suggest one of the two options:

1. A special case for AngularJS code (that is, where the last exported member is `.name`, and potentially only where the statement begins with `angular.module(...)` to ensure that it's only used in AngularJS module definitions).
2. A change that whenever a series of chained methods is ended with an attribute access (and the chained methods are chopped down due to line length), the attribute access should go on its own line.

For example:

```js
myArray.map(x => x * x).filter(x => x % 2).find(x => x === x).length.attr.otherAttr
```

should become

```js
myArray
    .map(x => x * x)
    .filter(x => x % 2)
    .find(x => x === x)
    .length.attr.otherAttr
```

**Comment by j-f1** [comment] 2019-01-31 01:52
Looks like this is a duplicate of #875.

**Comment by MrJohz** [comment] 2019-01-31 09:33
That doesn't look like there's much activity going on there, though.  From what I can see there's essentially an impasse between React propTypes, in which the attribute access should go at the end, and *most other* uses of method chaining, where the attribute access should go on a separate line.

Perhaps then the better solution is then to try and put a method chain on one line (hopefully satisfying the propTypes case), and if that will produce too long a line, then chop down the entire chain, including attribute access.

Alternatively, my understanding of propTypes is that they don't usually include more than one or two *method* calls.  Therefore, if there are three or more methods in a single chain, Prettier should chop the entire thing down, again including attribute access.  Otherwise, Prettier should try and keep as much on the same line, and ensure that the final attribute access is not left by itself.

Would either of these be suitable options that don't special-case propTypes very much, but do provide differentiation between the two situations?

**Comment by thorn0** [comment] 2019-11-08 15:55
Duplicate of #875

**Closed by thorn0** 2019-11-08 15:55 UTC
Labels: lang:javascript, status:needs discussion
