### ISSUE TITLE
indentation when nesting multiple ternaries doesn't get bigger

### ISSUE THREAD

**Issue by capaj** [prettier/prettier#6109] opened 2019-05-10 08:01 UTC
This was formatting correctly with indents getting bigger and bigger in some previous version.  There has been an issue for it here: https://github.com/prettier/prettier/issues/1762

Now it doesn't add indents as you go deeper into ternaries.

**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACSUDONUCMCGYA1gOYBOEArlACYDCEANhGagLyoCWmAIt-rkZwaAHSipUAflRRKjRmIlIumAMpwhYeKPESpqAOQBiAGYBmEwFYTANgOK9y7gDEIYSpmEO9+43DAmAAwmAIz2uj7KsvIgADQgEAAOMJzQmMig+GQUAO4AClkI6Sj4AG4QnDRxILhkhERwMKqJhJxQJMgwZJRw8QAWMAC2jADqfZzwmC1gcOpYE5ylEwCeyOCY6fFtnmQweXUkg-jIJviMnvEAVpgAHgBCdcSNqviDcAAybXAnZxcg1zdVG0SEIAIqUCDwH7nXogFpkHZrAi4ZbMKDVRJkNowEaVGB9ZAADkC8UxEE8IzqiTWmLgO1K33iAEcIfB9kliiB8JgALRQODCYTVMhwFmcEX7fCHY5IU4w+KeQacTrdWGYYFg1nfWW-WEwAS4mj45AAJniXXwnEYwIYgyOayg0EZIA8cAAKgJinLPABfH1AA)
```sh
# Options:
--single-quote
```

**Input:**
```jsx
 const backgroundColor = isDisabled
  ? null
  : isSelected
    ? '#f3f5f6'
    : isFocused
      ? '#ecf0f1'
      : null
```

**Output:**
```jsx
const backgroundColor = isDisabled
  ? null
  : isSelected
  ? "#f3f5f6"
  : isFocused
  ? "#ecf0f1"
  : null;

```

**Expected behavior:**
keep the indent as it is.

**Comment by lydell** [comment] 2019-05-10 10:41
Duplicate of #5814

**Closed by lydell** 2019-05-10 10:41 UTC
