### ISSUE TITLE
CSS calc split over many lines

### ISSUE THREAD

**Issue by JamieDixon** [prettier/prettier#2408] opened 2017-07-06 08:56 UTC
prettier: 1.5.2

Hi there,

First off, thanks for Prettier. We absolutely love using this tool and we're very grateful.

We're encountering an issue in one of our styled-components where `calc` CSS is being split over many lines which the browser isn't able to understand.

The prettier output:

```
    height: calc(
        100vh -
            ${({ theme }) => `${theme.headerHeightRem}rem - ${theme.infoBarHeight} - ${theme.menuSubItemsContainer}`}
    );
```

I this a bug?

Kind Regards

**Update**

The issue isn't multi-line `calc`, is the fact that prettier splits after the `-` without preserving the space between `-` and the next value. This results in `100vh - 4rem` becoming `100vh -4rem` and 💥

**Comment by lydell** [comment] 2017-07-06 09:17
`calc`s _can_ be split over multiple lines: https://jsbin.com/mazocadusu/edit?html,css,output

What am I missing?

**Comment by k15a** [comment] 2017-07-06 09:18
Maybe some older browsers don't understand that?

**Comment by JamieDixon** [comment] 2017-07-06 09:26
I realise now that the issue isn't the multi-line but rather _where_ the split is happening.

The issue here is that prettier is splitting after the `-` (`100vh -)` but isn't taking account of the space after the `-`.

Our input looks like this:

```
height: calc(
        100vh - ${({ theme }) => `${theme.headerHeightRem}rem - ${theme.infoBarHeight} - ${theme.menuSubItemsContainer}`}
    );
```

and the prettier output is:

```
    height: calc(
        100vh -
            ${({ theme }) => `${theme.headerHeightRem}rem - ${theme.infoBarHeight} - ${theme.menuSubItemsContainer}`}
    );
```

Because of the split after the `-` we end up with `100vh -4rem` instead of `100vh - 4rem`. (the space is missing)

**Comment by lydell** [comment] 2017-07-06 09:44
So styled-components (is that what you’re using?) does not let you split on several lines the same way that you can in CSS?

**Comment by azz** [comment] 2017-07-06 09:47
@JamieDixon in case you aren't aware, you can add `/* prettier-ignore */` on the line before `height:` to get you unlocked.

**Comment by k15a** [comment] 2017-07-06 09:48
This is a bug with stylis which is used by styled-components and styled-jsx.
/cc @thysultan

**Comment by JamieDixon** [comment] 2017-07-06 09:54
Thanks @azz!

@k15a This seems likely now you mention it. Thanks for pointing that out.

@lydell styled-components does let you split on several lines however because of the nature of template literals, the browser will concat those lines as-is, and won't insert spaces between the lines as it concats them.

**Comment by thysultan** [comment] 2017-07-06 10:01
I can't seem to reproduce the bug with stylis.

```css
height: calc(
    100vh -
        20rem-20-30
);
```

...produces the correct output, [REPL](stylis.js.org)

What am i missing?

**Comment by k15a** [comment] 2017-07-06 10:07
Between the `-` and `1px` should be a space. https://jsbin.com/jisihilaho/edit?css,output

![screen shot 2017-07-06 at 12 03 16](https://user-images.githubusercontent.com/20357450/27906268-26079dc4-6243-11e7-8d7e-4b16956a46dc.jpg)

**Comment by thysultan** [comment] 2017-07-07 00:42
@k15a Yes that's a bug with stylis, pushed a patch in 3.2.3

**Comment by azz** [comment] 2017-07-07 03:16
Shall we close this since there's not a lot we can do on our end?

**Comment by radeno** [comment] 2017-07-07 17:20
Same issue with long attribute values.
Eg background: ```url(/long/path/to/background-image.svg) no-repeat center center / 50% 50%;```
is divided into
```
background: url(/long/path/to/background-image.svg) no-repeat center
    center / 50% 50%;
```

Unfortunately "prettied" code doesn't work well.

**Comment by vjeux** [comment] 2017-07-07 17:21
What do you mean by "doesn't work well"?

**Comment by radeno** [comment] 2017-07-07 17:21
Maybe it is PostCSS problem.... let me investigate.

**Comment by radeno** [comment] 2017-07-07 17:30
Definitely PostCSS problem. Is there any switch to don't wrap attribute values?

**Comment by azz** [comment] 2017-07-09 12:36
Going to close this issue as the issue has been fixed in stylus.

@radeno You can raise your issue with postcss, and use `/* prettier-ignore */` to get you unblocked.

**Closed by azz** 2017-07-09 12:36 UTC
Labels: bug, CSS, dependency, high-pri
