### ISSUE TITLE
Unexpected indentation between aligned operators

### ISSUE THREAD

**Issue by Zirro** [prettier/prettier#4146] opened 2018-03-14 15:30 UTC
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUBDATgcwFcBbBGARgBoACPI02AJgEpqAfNgHSnSzpLIBmGvwYwALKw7deOAgNgBWEfLEA2ZgG4QlEBAAOMAJbQAzslB5cEAO4AFPAnMpsANwhGAJjpDZTMZFRsABtTOF0AI1xsMABrOBgAZX0Yoyh8ZBhcQnCQTwgwQJCw3TSw3Bg7aPxibCLQ3IArUwAPACFouITE7FIAGTS4epK9Qhh9McZh3JTccuQQCOwIgE9g6B99XDSYAHUvGAALZAAOAAZdLYgw3ej9Ba24ctch3Vw4AEdCI3eq7Bq6kggg1dGFiEZMtlcqY0vhgnAAIqECDwaa6GDLfaeI7IRjo6JGYKwgDCEGItQWUGgrxAhDCABVls5gWEAL6soA)

**Input:**
```jsx
foo(argument1, argument2) ||
foo(argument3, argument4) ||
foo(argument5, argument6);
```

**Output:**
```jsx
foo(argument1, argument2) ||
  foo(argument3, argument4) ||
  foo(argument5, argument6);

```

**Expected behavior:**

Prettier should not add indentation between lines where the operators align. Doing this results in output which is less readable than the input.

**Comment by lydell** [comment] 2018-03-14 17:07
@Zirro Thanks! While minimal examples are usually helpful for bug reports, in this case your example is actually too minimal. I don't think anyone writes a lone or-expression like that? Can you show a real-world example that can help us assess this? This could potentially be a duplicate of #2209.

For example, the `||`s are already aligned nicely in `if` statements:

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgCnRCmCGATgOYCuAtgjAIwA0ABEWZbAEwCU9APlwDpT16OPEwpUAzA1EsYAFk49+g4QRJjYAVilqZANnbtgAXwDcIWiAgAHGKmgBnZKCKEIAdwAKRBI5T4AbhCoACbmIPj2MMjo+AA29nAWAEaE+GAA1nAwAMpWaahQxMgwhKSJIMEQYNFxCRYFCYQwHqnE5Pg18eUAVvYAHgBCqRlZ2fiUADIFcJ11lqQwVguss+V5hI3IIEn4SQCesdBhVoQFMADqITAAFsgAHAAMFicQCeepVlsncI3+MxaEOAAR1IqEBLXwbQ6SBiXQsCXIqGKpXK9gKxFicAAiqQIPBVhYYLtLsEbshWITUqhYuiAMIQcjtLZQaD-ECkBIAFV2vlhCSMRiAA)

**Input:**
```jsx
if(foo(argument1, argument2) ||
  foo(argument3, argument4) ||
  foo(argument5, argument6)){};
```

**Output:**
```jsx
if (
  foo(argument1, argument2) ||
  foo(argument3, argument4) ||
  foo(argument5, argument6)
) {
}

```

But in this case the indentation helps showing that lines are part of the same expressions rather than the previous one.

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAEhA7hgWwEMoBPDAZxiPgIRgowEtGYALFgfgB0oAzCBAAURAE4BzAK51YARgA0GMVJkwATAEpeA4cun0FSiftiaMAH3PbBI46oDMivaoAsGi1f43n9AKxO7egA2LS9dQLkAlXpNEHkQCAAHGCZoCmRQMVE8AAUxBHSUIgA3CCYAEziQIipkPiIAGwo4eIAjUSIwAGs4GABlRM6mKHFkGFFJFpByiDA6xub44ebRGByO8WJ5pqmAKwoADwAhDu7evqI6ABlhuG3FhMkYRKe1e6nB0RXkEFaiVtIDWgVUSomGMAA6hV2MgABwABnioIgzQhHUSP1BcBWxTu8VEcAAjpImAT1kRNkR3vFmgQmGMJlMKMNxA04ABFSQQeDUkDUVpQ8owpBqeLjIhMBosgDCEAIWxQUGgeJAkmaABV-oV6jsAL66oA)

**Input:**
```jsx
// How many statements is this?
foo(argument1, argument2)
foo(argument1, argument2) ||
foo(argument3, argument4) ||
foo(argument5, argument6)
foo(argument1, argument2)
```

**Output:**
```jsx
// How many statements is this?
foo(argument1, argument2);
foo(argument1, argument2) ||
  foo(argument3, argument4) ||
  foo(argument5, argument6);
foo(argument1, argument2);

```

**Comment by Zirro** [comment] 2018-03-14 19:36
The example might still feel a bit contrived, but in this case it's a simple declarative method used to cycle through an arbitrary set of values:

```JavaScript
let identifier = 'section-B'; // this value comes from outside in real-world script

function swap(prev, next) {
  if (identifier === prev) {
    identifier = next;
    return true;
  }
}

function cycleEntries() {
  swap('section-X', 'section-B') ||
  swap('section-B', 'section-L') ||
  swap('section-L', 'section-X');
}

document.addEventListener('click', cycleEntries);
```

I agree that indentation could help in the example you give, but I would not expect the return value to be used inconsistently rather than as part of a chain all the way through in the real world.

**Comment by lydell** [comment] 2018-03-14 20:01
I'm not sure I've ever seen people write code like that. Do you write such code a lot? If not, does it matter that a few spots in the code doesn't look perfect?

You could also define the cycle as an array. Write the logic once, make it easy to add, remove and re-order the identifiers:

```js
let identifier = "section-B"; // this value comes from outside in the real-world script

const order = ["section-X", "section-B", "section-L"];

function cycleEntries() {
  const index = order.indexOf(identifier);
  if (index >= 0) {
    identifier = order[(index + 1) % order.length];
  }
}

document.addEventListener("click", cycleEntries);
```

Now, _if_ we decide to make a change – what would the change be? You agreed that indentation helps in the example I provided. What would be the rule to decide whether to indent or not?

**Comment by Zirro** [comment] 2018-03-14 21:44
> I'm not sure I've ever seen people write code like that. Do you write such code a lot?

Not this particular style, no. But this is the second time someone has told me that they've never seen code like mine before. The first time it was intended as a compliment, at least :-)

It's okay to close this issue if the pattern is rare. I was honestly not aware that this was the case.

> You could also define the cycle as an array.

Thanks for the suggestion. I did consider that approach before implementing it this way but I tend to go for the solutions which (at least I think) maximise readability, and they're usually the ones with less code.

> Now, if we decide to make a change – what would the change be? You agreed that indentation helps in the example I provided. What would be the rule to decide whether to indent or not?

My suggestion would be that if operators align across several lines like this...

```JavaScript
swap('section-X', 'section-B') ||
swap('section-B', 'section-L') ||
swap('section-L', 'section-X');
```

...or the lines vary in length but have been padded with indentation...

```JavaScript
swap('samplebar', 'samplefoo') ||
swap('foobar', 'samplebar')    ||
swap('foobar', 'foo');
```

...it should be taken as a hint that the aligned version most likely is the more readable one, causing no changes to the indentation. While I agreed with your example, I believe that style is even less likely to occur than this one.

Again, feel free to close the issue if you think that this style might be too unusual. I don't want to take up your time unnecessarily.

**Comment by lydell** [comment] 2018-03-15 07:08
Thanks for your very nice responses! I think it makes the most sense to close this issue at this point, then. Thanks for your feedback!

**Closed by lydell** 2018-03-15 07:08 UTC
Labels: lang:javascript, status:needs discussion
