### ISSUE TITLE
--check not giving enough info for [warn]

### ISSUE THREAD

**Issue by thernstig** [prettier/prettier#10294] opened 2021-02-10 13:03 UTC
**Environments:**

- Prettier Version: 2.2.1
- Running Prettier via: CLI
- Runtime: Node.js v14
- Operating System: Linux

**Steps to reproduce:**

When I have white-space issues in a JavaScript file I get the following error when running via CLI:

```sh
> prettier --check "**/*.{js}"
Checking formatting...
[warn] api/cow/moo.js
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```

If I run Prettier via ESlint (using eslint-plugin-prettier) I instead get the following output:

```sh
> eslint --max-warnings=0 .

/home/user/code/project/api/cow/moo.js
  9:1  error  Delete `⏎··⏎`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Expected behavior:**

I find the ESLint output _much_ better than that of Prettier. Hence why I have chosen to run Prettier via ESLint instead. This is unfortunate, as https://prettier.io/docs/en/integrating-with-linters.html does not recommend to use Prettier as plugin to ESlint.

The actual behavior is subpar to what I would expect. I want to know the file, the line:column and also exactly what was wrong.

**Actual behavior:**

See above.

**Comment by thorn0** [comment] 2021-02-10 13:32
Duplicate of #6885

**Closed** 2021-02-10 13:33 UTC
Labels: type:duplicate
