### ISSUE TITLE
Block code when commenting an element in array destructuring

### ISSUE THREAD

**Issue by Ayc0** [prettier/prettier#16569] opened 2024-08-13 14:41 UTC
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBtKEAmcaANJgPQBUmacMAcgUZhWadA4WgMIAWAhlADmcALqYAvJgCuNDkQDKMPvAAUeTgAUAThAAOASgDcIYiD0wAlumSg+WnQHcNdhGmQg+AGwd8Anm9MAIy0+MABrWnk+AFs4ABkLKDhkADMvGiCQ8MjdUMTBZBgtKThTGmiLQuLSkDgAD104LQtY2C8AFSaoOwsiVPSatHzPOABFKQh4fs8MkAArNDr5YbGJqaQ0mZqARzW4bT03FD40AFokuEJ8ExAivgtPfK4IaOi+dy9PG6GhEYBBGBFCyBKTwDRNBJJaazHgwaKeADqPAs8DQuTAcHkrhRFgAbijfO4wGgAiBcSUAJJQQiweRgZq6GB-amKXwjaE1XQ6GgIkK6dxcohNXHJUyJGhaGDaPiCN4c0y5LQS9wwXyNND0iyMm5cxIwBEWfAwHjIAAcAAZTFo4LsLNbpbL3hsBqYlIEDUaTUgAEymGRwdp8QJHTazODRQKXK5xASCKQyuAAMQgWjegPyH1BEBAAF8c0A)

**Input:**

```js
const [nodes, /* setNodes */, onNodesChange] = useNodesState(nodesProp);
```

**Output:**

```js
const [nodes /* setNodes */, , onNodesChange] = useNodesState(nodesProp);
```

**Expected output:**

```js
const [nodes, /* setNodes */, onNodesChange] = useNodesState(nodesProp);
```

**Why?**

When I have this piece of code, and I just want to comment out `setNodes`, I add `/*` before & `*/` after. But when doing so and applying prettier, `/* setNodes */` get's moved before the 1st `,`. But if we wanted to uncomment the code, it'd create `nodes setNodes`, which isn't valid JS:

```js
// Initial code
const [nodes, setNodes, onNodesChange] = useNodesState(nodesProp);

// After commenting
const [nodes, /* setNodes */, onNodesChange] = useNodesState(nodesProp);

// After formatting
const [nodes /* setNodes */, , onNodesChange] = useNodesState(nodesProp);

// After uncommenting
const [nodes setNodes, , onNodesChange] = useNodesState(nodesProp);
```

**Comment by fisker** [comment] 2024-08-13 15:06
Duplicate of #1013

**Closed** 2024-08-13 15:06 UTC
Labels: type:duplicate
