### ISSUE TITLE
Prettier moves block comments in destructured array assignment

### ISSUE THREAD

**Issue by bijection** [prettier/prettier#5152] opened 2018-09-28 00:23 UTC
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVkoGcaoNoD0AVAIZEEA0qARlcWOVQCYC6qAvPgIwUBMFAZgoAWFiAogIABxgBLaFmSgSAJxUQA7gAVVCRShIA3CLKbiQ1FSTABrODADKU67KgBzZDBUBXOBNdYcCowWlZuALYkyABmJAA2gRIAVlgAHgBCVrb2DiThcAAyrnAx8YkgziqBKsgWJNQAnnHQ5lIqrjAA6qYwABbIABwADBJtEIGdVlK1bXDVhiUSKnAAjt6yy6EkEVFIsQl+IIHhsp4+h1iubnFwAIreEPClBxIw9d1Mfcj8IF4ksnErgBhCDhSK1KDQRYgbyBAAq9X0+0CAF8UUA)
```sh
--parser babylon
```

**Input:**
```jsx
const [/*a*/, b, /*c*/, d] = [1,2,3,4]
```

**Output:**
```jsx
const [, /*a*/ b /*c*/, , d] = [1, 2, 3, 4];
```

**Expected behavior:**
```jsx
const [/*a*/, b, /*c*/, d] = [1, 2, 3, 4];
```

This is potentially related to #4398 and #4835, so feel free to close as a dupe.

**Comment by j-f1** [comment] 2018-09-28 00:53
Thanks for reporting this! Someone opened an issue about this before, so please follow along there instead.

Duplicate of #1013.

**Comment by j-f1** [comment] 2018-09-28 00:53
Duplicate of #1013

**Closed by j-f1** 2018-09-28 00:53 UTC
Labels: area:comments, lang:javascript, type:duplicate
