### ISSUE TITLE
Parens for arrow function with concise body on next line

### ISSUE THREAD

**Issue by andrey-shostik** [prettier/prettier#5248] opened 2018-10-11 19:16 UTC
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
```

**Input:**
```jsx
export const configureStore = () => (
    compose(middleware)(createStore)(reducer, initialState)
); 
```

**Output:**
```jsx
export const configureStore = () =>
  compose(middleware)(createStore)(reducer, initialState);
```
**Expected behavior:**
Parens for arrow function with concise body on next line **MUST** exist

**Comment by lydell** [comment] 2018-10-11 19:28
Hi! I think this is a duplicate of #2065. Let me know if that's not the case!

**Comment by lydell** [comment] 2018-10-11 19:28
Duplicate of #2065

**Closed by lydell** 2018-10-11 19:28 UTC
