### ISSUE TITLE
Weirdness with named type in TS type intersection

### ISSUE THREAD

**Issue by innermatrix** [prettier/prettier#13555] opened 2022-09-30 16:12 UTC
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAgtgXm2AB0oSYBDJbAZxgCcBLKAcwG4yBfbAMmwBCfYmQoAjGvWZtOULrLLosgwsXlkQAGhAQMMJtFrJQlBgwgB3AAqmERlJQA2FymiPaxDSmADWcGADKlAC2cAAyLHDIAGZOtHAeXr7+ARjeLKzIjACuCSBwwWJwACbFJWGUbNmUrHAAYhAMwZQw+mzIIJTZMBBaIAAWMMGOAOr9TPC0aWBwAXYTTABuE2gdYLTuICzxDDBWXqzNMXF5AFa0AB4BGY5wAIrZEPDHjvHaaQw7HUpwtGDMej6GGkMBGTGKMH6yAAHAAGd7meIjLwYDrA35wBiLKLaACOj3g+109k6tAAtFA4CUSn0GHB8Uw6fsakckLFXnl4sEmFkGLltLQbvcCVE2SdtFQxGCIVCkAAmCVeJiODIAYQgwVZ+VoAFY+tl4gAVShiezst4gRa5ACSUDKsAC-yYelwdoC6FuL3iXC4QA)

**Expected behavior:**

```
type A = {
  a: string;
} & B & {
  b: string;
};

type B = {};
```

**Comment by thorn0** [comment] 2022-10-01 19:28
Duplicate of #9261

**Closed** 2022-10-01 19:28 UTC
Labels: type:duplicate
