### ISSUE TITLE
Prettier 3.x - Package subpath is not defined

### ISSUE THREAD

**Issue by ivodolenc** [prettier/prettier#15195] opened 2023-08-01 14:23 UTC
Hi, after updating prettier to `3.0.0`, I am trying to set the main configuration from the shared configuration (npm package) but I'm getting errors via terminal:

```
["INFO" - 3:55:52 PM] Formatting file...
["ERROR" - 3:55:52 PM] Error resolving prettier configuration for ...
["ERROR" - 3:55:52 PM] Package subpath './prettier-base' is not defined by "exports" in .../node_modules/pkg/package.json

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './prettier-base' is not defined by "exports" in .../node_modules/pkg/package.json
```

### Current pkg setup

**node_modules/pkg/dist/prettier/prettier-base.mjs**

```js
export default {
  // ...
}
```

**node_modules/pkg/package.json**

```json
{
  "type": "module",
  "exports": {
    "./prettier-base": {
      "types": "./dist/prettier/prettier-base.d.ts",
      "import": "./dist/prettier/prettier-base.mjs"
    }
  }
}
```

---

And later I import it into the project:

**package.json**

This throws the errors I mentioned above:

```json
{
  "type": "module",
  "prettier": "pkg/prettier-base"
}
```

This works as expected without errors:

```json
{
  "type": "module",
  "prettier": "./node_modules/pkg/dist/prettier/prettier-base.mjs"
}
```

and this also works as expected:

```js
// prettier.config.js

import baseConfig from 'pkg/prettier-base'

export default baseConfig
```

Any advice?

**Comment by ivodolenc** [comment] 2023-08-01 15:44
Hi @kachkaev, may I ask why are you close this? Do I need to provide repo example?

**Comment by ivodolenc** [comment] 2023-08-01 16:11
I wrote "Any advice?" because maybe someone on the team already knows a quick fix or something... This is not a question but a bug report because the manual path from `node_modules` works as expected.

Also, when importing the configuration from the subpath into the custom `prettier.config.js`, that configuration works as expected (I've provided both examples above). Package subpaths works fine on my side.

It is possible that Pretier has problems finding node subpaths when the configuration is extended via package.json (prettier v3.x.x) but if you don't want to investigate further, I'm fine with that.

**Comment by kachkaev** [comment] 2023-08-01 16:54
Looking at your terminal output, looks like this is an issue specific to VS Code. This repo is for tracking issues with Prettier core only. After a bit of digging, I think I found the issue report you are looking for: https://github.com/prettier/prettier-vscode/issues/3066

**Comment by kachkaev** [comment] 2023-08-01 21:49
Thanks for creating the reproduction repo @ivodolenc! Things make a bit more sense now. I was initially confused by output like `["INFO" - 3:55:52 PM]` and `["ERROR" - 3:55:52 PM]` in your issue report. The are often a sign of people having issues in VS Code. Configuring ESM is often a bit tricky, so I thought this was a setup question of some sort. Existence of https://github.com/prettier/prettier-vscode/issues/3066 confused me even more. Sorry for that!

Using the [package you have published](https://unpkg.com/browse/prettier-issue-test-config@0.0.1/), I think I have been able to reproduce your steps a terminal, outside VS Code:

```ts
cd /tmp

mkdir prettier-issue-15195
cd prettier-issue-15195

cat << EOF > package.json
{
  "type": "module",
  "prettier": "prettier-issue-test-config/prettier-base"
}
EOF

npm install --save-dev prettier prettier-issue-test-config@0.0.1

npx prettier --log-level=debug --write package.json
```

Output:

```
[debug] normalized argv: {"":["package.json"],"cache":false,"color":true,"editorconfig":true,"write":true,"logLevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":[".gitignore",".prettierignore"],"plugins":[],"_":["package.json"],"__raw":{"_":["package.json"],"cache":false,"color":true,"editorconfig":true,"write":true,"log-level":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":[".gitignore",".prettierignore"],"plugin":[]}}
[debug] resolve config from '/private/tmp/prettier-issue-15195/package.json'
[error] Invalid configuration for file "/private/tmp/prettier-issue-15195/package.json":
[error] Package subpath './prettier-base' is not defined by "exports" in /private/tmp/prettier-issue-15195/node_modules/prettier-issue-test-config/package.json
```

Interestingly, when I make a somewhat illogical change to `node_modules/prettier-issue-test-config/package.json`, running `npx prettier --log-level=debug --write package.json` ends up working:

```diff
{
  "name": "prettier-issue-test-config",
  "version": "0.0.1",
  "license": "MIT",
  "type": "module",
  "exports": {
    "./prettier-base": {
+     "require": "./dist/prettier/prettier-base.mjs",
      "types": "./dist/prettier/prettier-base.d.ts",
      "import": "./dist/prettier/prettier-base.mjs"
    }
  },
```

```
[debug] normalized argv: {"":["package.json"],"cache":false,"color":true,"editorconfig":true,"write":true,"logLevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":[".gitignore",".prettierignore"],"plugins":[],"_":["package.json"],"__raw":{"_":["package.json"],"cache":false,"color":true,"editorconfig":true,"write":true,"log-level":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":[".gitignore",".prettierignore"],"plugin":[]}}
[debug] resolve config from '/private/tmp/prettier-issue-15195/package.json'
[debug] loaded options `{"semi":false,"tabWidth":2,"singleQuote":true}`
[debug] applied config-precedence (cli-override): {"singleQuote":true,"semi":false,"tabWidth":2}
package.json 21ms
```

I tried removing `"prettier": "prettier-issue-test-config/prettier-base",` from `package.json` and creating `.prettierrc.json` with a reference to your package path:

```json
"prettier-issue-test-config/prettier-base"
```

This also errored without the `require` `exports` hack:

```
[debug] normalized argv: {"":["package.json"],"cache":false,"color":true,"editorconfig":true,"write":true,"logLevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":[".gitignore",".prettierignore"],"plugins":[],"_":["package.json"],"__raw":{"_":["package.json"],"cache":false,"color":true,"editorconfig":true,"write":true,"log-level":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":[".gitignore",".prettierignore"],"plugin":[]}}
[debug] resolve config from '/private/tmp/prettier-issue-15195/package.json'
[error] Invalid configuration for file "/private/tmp/prettier-issue-15195/package.json":
[error] Package subpath './prettier-base' is not defined by "exports" in /private/tmp/prettier-issue-15195/node_modules/prettier-issue-test-config/package.json
```

Finally, I replaced `.prettierrc.json` with `prettier.config.js`, similarly to what you did:

```js
export { default } from "prettier-issue-test-config/prettier-base";
```

This worked:

```
[debug] normalized argv: {"":["package.json"],"cache":false,"color":true,"editorconfig":true,"write":true,"logLevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":[".gitignore",".prettierignore"],"plugins":[],"_":["package.json"],"__raw":{"_":["package.json"],"cache":false,"color":true,"editorconfig":true,"write":true,"log-level":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":[".gitignore",".prettierignore"],"plugin":[]}}
[debug] resolve config from '/private/tmp/prettier-issue-15195/package.json'
[debug] loaded options `{"semi":false,"tabWidth":2,"singleQuote":true}`
[debug] applied config-precedence (cli-override): {"singleQuote":true,"semi":false,"tabWidth":2}
package.json 21ms
```

ESM support for config files was added in https://github.com/prettier/prettier/pull/13130. There are lots of test cases, but maybe we’ve found a gap? @fisker, WDYT?

@ivodolenc, thanks again for being consistent with this issue report, and apologies again for closing the issue too early!

**Comment by ivodolenc** [comment] 2023-08-02 11:44
@kachkaev  np 👍

I'm working on shared configs and couldn't get it to work so I assumed something might be wrong since the manual configuration works fine.

Maybe I should have shared an example repo right away so it could be easier to understand.

**Comment by fisker** [comment] 2023-08-02 12:06
Looks like a bug. We should not try `resolve` here https://github.com/prettier/prettier/blob/825425c57f00268abaf3964b441a7649c8004ba0/src/config/load-external-config.js#L23

**Comment by fisker** [comment] 2023-08-02 12:10
Maybe add `"./*": "./*"` to `exports` field will work?

**Comment by fisker** [comment] 2023-08-02 12:31
Add `error?.code !== "ERR_PACKAGE_PATH_NOT_EXPORTED"` to

https://github.com/prettier/prettier/blob/825425c57f00268abaf3964b441a7649c8004ba0/src/config/load-external-config.js#L17

Seems fix it.

Maybe I'm wrong we can still import config by URL, but not let `require()` call to throw,

I don't have time to add test for it, hope someone can send a PR with this fix.

**Comment by fisker** [comment] 2023-08-02 12:46
Also found a workaround.

```js
// dist/prettier/prettier-base.cjs
module.exports = import('./prettier-base.mjs').then(m => m.default)
```

```diff
  "exports": {
    "./prettier-base": {
+      "require": "./dist/prettier/prettier-base.cjs"
    }
  },
```

**Comment by ivodolenc** [comment] 2023-08-02 13:03
> Also found a workaround.

I can confirm that this workaround works. I just added the [.cjs](https://github.com/ivodolenc/prettier-issue-15195/blob/main/dist/prettier/prettier-base.cjs) file to the pkg and after updating the pkg and restarting VSCode this works (config is extended via package.json). 

Updates can be followed [here](https://github.com/ivodolenc/prettier-issue-15195/commits/main).

**Closed** 2023-08-29 08:11 UTC
Labels: type:bug, area:cli
