### ISSUE TITLE
Errors for embedded languages on Playground are confusing

### ISSUE THREAD

**Issue by awmottaz** [prettier/prettier#10602] opened 2021-03-25 23:29 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAzgDwDpQBmArlGDAJbQAEAklAA7EzUAUDAThA1gJTXAC1ahzgxiHKNQA8FRswEA6ZZ25YAvgD4C6gulQgANCG6VoWZKACGHLgHcACjYQWUVgDZ2rATwvGARhxWYADWYgDKDMFyAObIMBzEcMZwALb+cAAmmVkAMlZQMcRWMXAAYhAcqVYwlIXIIFbMEEYgABYwqe4A6m0U8FhRYHDhLv0UAG793g1gWH4gclhwHDAOQTHVyIQey8bYOABCQaERVqlwuXJw27vJIAfhse5wAIrEEPC37nsgURzLDgNaocEKZCB2KCtThyGDdCiZGBtZAADgADMZVMtukEGA1OHBARMbsYAI4feDrNQNKxYAC0UDgWSyrVE5IoonWJS2SB2P3uy1SFHiiQFzzeFJuvLuxhgVn88MRyKQACZZUEKO5YgBhCCpHkgQkAVlaxGWABV5a4+b8Jkl6DlYOEwBwKAwYABBKCZcIwbwvb7LdTqIA)

```sh
--parser markdown
```

**Input:**

````markdown
```jsx
function Input (props) {
  return <input {...props}>
}
```
````

**Output:**

```markdown
SyntaxError: Unterminated JSX contents (2:28)
  1 | function Input (props) {
> 2 |   return <input {...props}>
    |                            ^
  3 | }
```

**Expected behavior:**
I have a Markdown file `testing.md` with the contents of the input above, and I was expecting a semicolon after the closing `>` in my output. Curious why I wasn't seeing it, I brought it to the Playground, lo and behold there is a syntax error. Easy to miss, this is one of the subtle differences between HTML and JSX.

However, using both the CLI and the VSCode plugin, I never saw this error. Running the format command on this file did nothing, and the CLI exited cleanly:

```
$ npx prettier --write --parser markdown testing.md
testing.md 36ms
```

Even the debug output has no hint of the SyntaxError:

````
$ npx prettier --loglevel debug --parser markdown testing.md
[debug] normalized argv: {"_":["testing.md"],"color":true,"editorconfig":true,"loglevel":"debug","parser":"markdown","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}
[debug] resolve config from 'testing.md'
[debug] loaded options `{}`
[debug] applied config-precedence (cli-override): {"parser":"markdown"}
```jsx
function Input (props) {
  return <input {...props}>
}
```
````

The `--check` option also has no issue.

```
$ npx prettier --check --parser markdown testing.md
Checking formatting...
All matched files use Prettier code style!
```

How can I discover SyntaxErrors on my own without using the Playground?

**Comment by thorn0** [comment] 2021-03-25 23:41
Duplicate of #8488

**Comment by awmottaz** [comment] 2021-03-25 23:54
@thorn0 Thanks for linking the duplicate! I searched all over and couldn't find a previous issue about this.

I'd like to ask more about what you wrote [here](https://github.com/prettier/prettier/issues/8488#issuecomment-638137528):

> This works as expected. Prettier is a formatter, not a syntax checker. If an embedded code block can't be parsed, it doesn't mean the whole document shouldn't be formatted as it's still valid Markdown. The Playground shows those errors for debugging purposes.

I agree with the sentiment—I certainly don't want to rely on a formatter for checking that my syntax is correct. However, when this happens, it appears to me as an end user that Prettier is not working correctly. Having this kind of debug messaging would allow me to verify whether the issue is with Prettier or something else. If the code snippet in my Markdown file is quite large, it would be a really difficult to find the root cause. The error message from the Playground made it really easy to find the root of my problem.

I do not want to use Prettier to check that I have valid syntax. But I do think it's valuable to know when Prettier encounters syntax that it does not understand.

Please consider adding this as a debugging feature!

**Comment by awmottaz** [comment] 2021-03-26 00:01
For what it's worth, it took me several hours today to discover this SyntaxError. I thought I was missing a CLI option, I read the full documentation a few times, and searched the issues for quite a while.

> If an embedded code block can't be parsed, it doesn't mean the whole document shouldn't be formatted as it's still valid Markdown.

100% agree. I am not asking for Prettier to fail when formatting the document. This is the correct behavior.

> The Playground shows those errors for debugging purposes.

It would be great if the `--loglevel debug` flag would also show this for our own debugging purposes!

**Comment by thorn0** [comment] 2021-03-26 08:06
I agree this is confusing and needs to be improved. Let's reopen this issue to track this.

**Comment by awmottaz** [comment] 2021-03-26 13:34
Here is an idea for what would have worked well for me. The only change is the inclusion of that message in the debug logs:

````
$ npx prettier --loglevel debug --parser markdown testing.md
[debug] normalized argv: {"_":["testing.md"],"color":true,"editorconfig":true,"loglevel":"debug","parser":"markdown","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}
[debug] resolve config from 'testing.md'
[debug] loaded options `{}`
[debug] applied config-precedence (cli-override): {"parser":"markdown"}
[debug] SyntaxError: Unterminated JSX contents (2:28)
[debug]   1 | function Input (props) {
[debug] > 2 |   return <input {...props}>
[debug]     |                            ^
[debug]   3 | }
```jsx
function Input (props) {
  return <input {...props}>
}
```
````

Prettier would continue to format the file how it does today, and it is not an error.

**Comment by thorn0** [comment] 2021-03-27 00:24
The main problem here is that the behavior of the playground doesn't match the local behavior of Prettier. This can be extremely confusing. These errors have to be hidden behind a checkbox to avoid this confusion.

What you're proposing is a separate feature whose implementation is tricky because Prettier actually doesn't have logs. Prettier CLI - even though it's included in the same npm package - is a separate program, a consumer of the core library just like, for example, editor integrations. These logs you're talking about are the CLI's logs. Prettier currently doesn't have a way to return debug information to its consumers, so this would require a change in the API. I'm not saying this shouldn't be done. On the contrary, if such an API had existed, the playground would have used it, and we wouldn't have had this issue in the first place. I'm just saying it's more involved than it seems.

**Comment by awmottaz** [comment] 2021-03-27 01:13
Ah I see. That makes sense! I definitely appreciate the challenge.

**Closed** 2022-08-05 14:05 UTC
Labels: type:enhancement, area:playground, area:multiparser
