### ISSUE TITLE
JS snippet requires two passes to be properly formatted

### ISSUE THREAD

**Issue by PyvesB** [prettier/prettier#12392] opened 2022-03-05 16:57 UTC
**Prettier 2.5.1**
[Playground link 1](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMB0YBOcCG8AUA5AG5yYDOAltIQJQA6UABE2gOZwxED0x3kAdwBGEAJ5oAVuRoNmrOAA8ADnDAwAQjgAmHfMCYAbHELgGkTQgAtFhADRMAtnHLkcHc5XIA1AAoGAruQAIhAw8FpeZFTQAHIAwkaBzgDqlDCWAPJKMNRQOAYAyv4AZsWUCkwAvrQgtiAQ2bnkyKA4mJgQAj5tCM0o+QI4os11Qpg4YADWnAU4TgAylFBwyMX55HCj41MzShNLbMgwmP6bIHAOJlpacFrzOFBs-m5wAGIQmA54OY-IIDj+GAQWogSwwBwGZKWNLOPZgOAFXppSjENKiP5gFwgpYbTAwHzjNhfVbrM5SBQFA4GOAARX8oRWSDWBg2dT2FDIfyExlMIKUmCWMFSWnSyAAHAAGNkdDbJcZKP785xkUgggCO9PgBIafX+5AAtMtbrcQdgNZRsAS3MSmaS6hsHJQjiczlRHtS6QySSyzjBjMLRUgAEx1Y44SgGA5xCAOG3ncgAVhBSQAKsY+szWSBiKcAJJQG6wApYSjZACCBYKMFE1O9WfJ6m20xgswWS0ZmbglUqQA) 
[Playground link 2](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMB0YBOcCG8AUAOiAG5yYDOAltMQJSFQAETaA5nDESAPQk+QA7gCMIATzQArCrRANmrOAA8ADnDAwAQjgAmHfMEYsWAGxzC4JpE2IALZcQA0R4wFs4FCjg7WqFAGoACiYArhQAIhAw8Dr+5NTQAHIAwmZhHgDqVDC2APIqMDRQOCYAyiEAZhVUSs4KAL50ANyMII4gEAVFFMigOJiYEIKB-Qg9KCWCOGI97cKYOGAA1pylOO4AMlRQcMgVJRRwcwvLqyqL22zIMJghRyBwrhY6OnA6GzhQbCHecABiEEwrjwhS+yBAOBCMAgbRAthgrhMGVs2Q85zAcFKY2yVBI2TE4LAnlh20OmBggQWbGBewO92kSlKlxMcAAiiEorskPsTId2udKORwcJzJZYSpMNsYFkdDlkAAOAAM-MGhwyCxU4IlHnIZFhAEcOfBKZ1xhCKABaHZvN6w7CGqjYSneGncuntQ6uKjXW73ahfFnszm03n3GDmGVypAAJnaNxwVBMl2SEFcroeFAArLD0gAVczjHl80h3ACSUFesFKWCoBQAghXSjAxCyQ8WGZoTisYGtNtsuUW4PV6kA)

```sh
--parser babel
```

**Input:**

```jsx
t.create('version')
  .get('/v/cowboy.json')
  .expectBadge({ label: 'hex', message: isVPlusDottedVersionNClausesWithOptionalSuffix })
```

**Output:**

```jsx
t.create("version")
  .get("/v/cowboy.json")
  .expectBadge({
    label: "hex",
    message: isVPlusDottedVersionNClausesWithOptionalSuffix,
  });

```

**New output with previous output reused as input:**

```jsx
t.create("version").get("/v/cowboy.json").expectBadge({
  label: "hex",
  message: isVPlusDottedVersionNClausesWithOptionalSuffix,
});

```

**Expected behavior:**

Prettier should get the formatting right the first time and not require multiple passes.

**Comment by Josh-Cena** [comment] 2022-03-06 05:12
Duplicate of https://github.com/prettier/prettier/issues/2803

**Closed** 2022-08-24 11:48 UTC
