### ISSUE TITLE
[HTML][Angular] Whitespace not respected

### ISSUE THREAD

**Issue by olaf89** [prettier/prettier#5487] opened 2018-11-15 07:41 UTC
**Prettier 1.15.2**

Extra whitespaces are added which causes my tests to fail asserting " text " does not equal "text"

**Input:**
```jsx
<p fxFlex data-test="country">{{answers.countryOfResidence | countryName | async }}</p>
```

**Output:**
```jsx
<p fxFlex data-test="country">
    {{ answers.countryOfResidence | countryName | async }}
</p>
```

**Expected behavior:**
Whitespace should not be added if it was originally not there.

**Comment by lydell** [comment] 2018-11-15 11:19
You might be looking for `--html-whitespace-sensitivity strict`. Read more about it here: https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgAgGYA8BiANnLpgCYCGMFAtPAM4wC8AOuBAK6wBOAnmwD5gwClHoB3ON3oA6SFxh8A8tgBKcegEsyCMHEwAfTPJ68AchQC2+oxXq8oYTAF9nqAPToBIADQgI6DCa0PTIoBTc3BDiAAoRCKEoFABuENq+IABG3BRgANZwMADK6LmaUADmyIoccH4AFjCWhADq9ZoMpXpFCR2ayR28yCCM3JpgMBnl9FIwMTkVlhTI2BSEM34AVvS4AEI5+YVFVnAAMuVwK2sbINu4ReUVxACKHBDwV+t1IKXSUsOiCocQgRDLoMawFraGD1ZAADgADH5wRAZi0cuhhuCNFJkpc-Nw4ABHDiaQnzCiLZZIVZfPwzSyaarcWr0x4vN4fGnXb7UTJQsgw5AAJj8igomkIjwAwhBLEthlBoPiQBwZgAVCiZRK0mauIA)
```sh
--html-whitespace-sensitivity strict
--parser angular
```

**Input:**
```html
<p fxFlex data-test="country">{{answers.countryOfResidence | countryName | async }}</p>
```

**Output:**
```html
<p fxFlex data-test="country">{{
  answers.countryOfResidence | countryName | async
}}</p>

```

**Comment by thorn0** [comment] 2018-11-15 14:54
Duplicate of #5463: adding white spaces around an interpolation breaks tests.

**Comment by lydell** [comment] 2018-11-15 15:00
Duplicate of #5463

**Closed** 2018-11-15 15:01 UTC
Labels: lang:angular, type:duplicate
