### ISSUE TITLE
[ts] ugly output for comment + union type

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#10599] opened 2021-03-25 08:07 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAS1jmwDMBDMOPABWwgBMBXMGAZRnJiYGc9gAOlDx4YATwxwkQkSID0cvHB4AbIjAC0DAj3IAjFXA1R0mtSbw9o5bHIC25NBqZQC0DTwIAvODNkAfPAByADkIGAAROAwVCDE4BiC-EUCggEkoKJi4uwQYJOEA4IAlF1coAHMC2TxUrNixXNgAMXICFSZsOGqioNKocoqAQT0oHAcVHpTgqMMYIirk2pm4ObhW9s7upbrohqb2FioEqeWgtjEeeDsAUWx6bFPUgFUMCuxybUqggG4-AkgUCQlhg2AWf0K8DQMGBVzBlQhAF8QAAaEAQDDzaA8ZCgGz0ADuNBsCBxKHIKgJ5EuqJAeg+YAA1nB2BhKAtkKCmHA0XA7HoEgwEgAZciVJjkCrrcZceaVZAgchMGAQWkACxgdhUAHU1QR4Dw2VQ2KT9QQAG76sQKsA8HFoog8EgwOiShzICgqJ1ogBWPDQACEGcz2ORcsKiHAPRTvSA-Wg2AtDABFJjhKNIT2xtnYJ3YBXiSQ8MBgzG0jDwmDaggMGBq5AADgADGiKxAndqPhgFRXlCRzVG0QBHNPwOgYsmKnjGOAJBK0rojghdV0Vd2ZmM8kBOuwETnYblozyVFOjjNZrecPTV2v1pAAJjRoLa5gqAGEIHZ16geABWWm8HAAAq+hkheaLmtyGRCrAbAlgQmJDFADAcGIhjRl6cCIoiQA)

**Input:**

```ts
export interface ProductStatus {
  type:
    // eslint-disable-next-line sonar/max-union-size
    | 'NotDeployed'
    | 'InDeployment'
    | 'Running'
    | 'DeploymentFailure'
    | 'RunningAbnormal'
    | 'Deleting'
    | 'DeleteFailure'
    | 'DeploymentSucceed'
    | 'SystemError'
    | 'Upgrading';
  icon: string;
  text: string;
}
```

**Output:**

```jsx
export interface ProductStatus {
  type: // eslint-disable-next-line sonar/max-union-size
  | "NotDeployed"
    | "InDeployment"
    | "Running"
    | "DeploymentFailure"
    | "RunningAbnormal"
    | "Deleting"
    | "DeleteFailure"
    | "DeploymentSucceed"
    | "SystemError"
    | "Upgrading";
  icon: string;
  text: string;
}
```

**Expected behavior:**

Don't change

**Comment by thorn0** [comment] 2021-03-26 00:16
Duplicate of #7725

**Closed** 2021-03-26 00:16 UTC
Labels: type:duplicate
