### ISSUE TITLE
Ignoring code section on website is kind of broken (I guess)

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#3322] opened 2017-11-26 21:36 UTC
https://prettier.io/docs/en/ignore.html

<img width="819" alt="screen shot 2017-11-26 at 22 35 06" src="https://user-images.githubusercontent.com/125676/33244555-2f232c84-d2fa-11e7-9270-840bbef6b8f9.png">

**Comment by azz** [comment] 2017-11-26 22:13
Looks like code fences with a `<!-- prettier-ignore -->` on the previous line are the cause.

~~~md
<!-- prettier-ignore -->
```js
code
```
~~~

@ikatyang any ideas here? I guess we could put a line break between the code fence and the comment, but it'd be a bit ugly.

**Comment by ikatyang** [comment] 2017-11-27 01:50
Since GitHub/CommonMark rendered it correctly, it should be a Docusaurus bug I guess, but don't know where to report.

**Comment by azz** [comment] 2017-11-27 22:47
Fixed in our end, not much else we can do

**Closed by azz** 2017-11-27 22:47 UTC
Labels: area:website, scope:dependency, type:bug

**Comment by lipis** [comment] 2017-11-27 23:19
What was that Docusaurus anyway?! Is it still active?

**Comment by suchipi** [comment] 2017-11-28 04:56
@lipis https://docusaurus.io/

**Comment by lipis** [comment] 2017-11-28 08:24
yes.. I found that one.. but the link to GitHub is dead https://github.com/facebookexperimental/docusaurus

**Comment by azz** [comment] 2017-11-28 10:45
It's a private repo

**Comment by lipis** [comment] 2017-11-28 10:46
I see :)

**Comment by lipis** [comment] 2017-11-28 12:14
Or more like.. I don't _see_ :P
