### ISSUE TITLE
custom parser API: calling builtin json5 parser on valid JSON5 throws syntax error

### ISSUE THREAD

**Issue by frantic1048** [prettier/prettier#4838] opened 2018-07-13 07:08 UTC
**Environments:**
- Prettier Version: 1.13.7
- Running Prettier via: Node.js API
- Runtime: ts-node v7.0.0 ,node v10.4.1 ,typescript v2.9.2
- Operating System: Arch Linux

**Steps to reproduce:**
```typescript
// sample#1
prettier.format('{ some: "jons5 stuff", and: "another one" }', {
  parser(text, parsers, options) {
    return parsers.json5(text)
  }
})
```

**Expected behavior:**

Prettier formats input JSON5 text.

**Actual behavior:**

Prettier throws syntax error.

**Context:**

I want to modify AST before prettier prints doc. Through the [documentation](https://prettier.io/docs/en/api.html#custom-parser-api), custom parser API is exactly what I want. But `sample#1` makes `parser-babylon` throws SynaxError. While this sample works well:

```typescript
// sample#2
prettier.format('{ some: "jons5 stuff", and: "another one" }', {
  parser: 'json5'
})
```

Then I walked around the source, found `parser-babylon` [uses a "parser" option to determine parseMethod](https://github.com/prettier/prettier/blob/576e5707116a9f604a86dbe6eff5b66141e2c788/src/language-js/parser-babylon.js#L40).

In `sample#1`, replace `parsers.jon5` to `parsers.babylon` throws same error. So I guess the `{ opts.parser === "jons5"}` branch in `parser-babylon` is not taken as passing `{parser: 'json5'}` to `prettier.format()`.

There's a similar issue #3150, however, it's after the parse() process.

To use prettier right now, I found a walkaround:

```typescript
import * as prettier from 'prettier'
import * as babylonPlugin from 'prettier/parser-babylon'

// copied from https://github.com/json5/json5/blob/master/README.md#short-example
const someJSON5 = `{
  // comments
  unquoted: 'and you can quote me on that',
  singleQuotes: 'I can use "double quotes" here',
  lineBreaks: "Look, Mom! \
No \\n's!",
  hexadecimal: 0xdecaf,
  leadingDecimalPoint: .8675309, andTrailing: 8675309.,
  positiveSign: +1,
  trailingComma: 'in objects', andIn: ['arrays',],
  "backwardsCompatible": "with JSON",
}`

prettier.format(someJSON5, {
  parser: (text) => {
    /* now we can ensure the {parser: 'json5'} is correctly passed to parse() :D */
    const ast = babylonPlugin.parsers.json5.parse(text, {}, { parser: 'json5' })
    return ast
  },
})
```

**Comment by frantic1048** [comment] 2018-07-13 07:17
BTW: `@types/prettier@1.13.1` lacks `json5` in type `BuiltInParserName`

**Comment by fisker** [comment] 2021-04-06 02:46
This specific case is working now, but I believe it's actually caused by checking `options.parser === 'json5'`, and we are still doing this in many other places.

**Comment by thorn0** [comment] 2021-04-06 09:54
I overlooked this one when I was closing similar issues (#3150, #6015).
The Plugin API should be used instead. It can do everything custom parsers can and much more.

**Closed by thorn0** 2021-04-06 09:54 UTC
Labels: area:api, type:bug
