### ISSUE TITLE
Prettier not proper breaking

### ISSUE THREAD

**Issue by attilacsanyi** [prettier/prettier#11344] opened 2021-08-13 09:15 UTC
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAchGGBGATnAIYDWAzhgBZzEA6UcAHgA4SF5gA2JFVAGWgBzIVFEixE8VKkBhCAFt2TWAEEMLeFAAmgyQZmHpJhcugIYAIQzBGGDPYwABAKIAzd3DAwAFAEondGxcAmJyKloGKAcKOG5vGABlJTgYagBLcQBFAFc6AE8ABRJCEkUAEiQMAHl8OMIANxJ8BIAeJPjElMU4NR8M6AA+DABeDHSMigA6OISfADEMwgpk1MnxCunWDNY4XydYgHcMmDBqAFkSVl8AsaHDhwnMmdWOOC2dvYOYp7+5xK+YRpHppTLiEplRRJGAkeD+AA0jz+7gy3HghAAqro4KimDoAkjfn8HDopjAsj5sRTuHJqCRxHACYjkU8KGRdr4AIws4kk2FkODUtG+SavVKuBK9WAw8KVQJ8hwKv68v6Ka6+CgSqWWACSOnuGCYRwwnXma16-Qp0E12rg0pg+v8yow-gA3E5HpAoKtCLkfBwfiSXLqoAArQEXNQAFQA+gARXVqAQ1ADiCZjahdf2CODwRFIlBodDgrNYuVaGTAGB0cJI1Qo9OIOguEB08Rm0doCggCVWSXBBTMKks8YyJG4EGE8brbUbpSZrfb3BmFwKCxIjQguUIpzgS-iQyJwfLlerZInU4ASrjqlcYGPL8Ib+42l24D2+8lB8OLLBH5Owi-qoMAPHy-i2AAvp6UDQVAjAgAiIAQKw1o+sgoClIQEBHJCCAUMgIATkcJAFARSFECQYCCskrBUVkwjIDAfpwEh9r4Ey7Y6AIDLCLkJDAgsHDqjAFLiIRJC5DAECISA1AwIo3AAOqZPAFB0WAcCdD6pwZI0pwFIRYD8LJWQNDARRlMI6rIO4E5xEhYYUMwVhlNRILlHAAhZHAtn2axIBOcwSQMQkeS4L5SB2SuAV0SsdCETABR7BQYC7qhsmsLusBKRkOjpMgAAcAAMSFZRAcRKWUrCEVlcANI0vlIQAjrkEWWShBEoHwAC0TBMkysnEK1yxwJZAk2VF-lIXEigZExLEzaFcDhfAfkxUhsL4Ll+XUMgABMm1lGiDFmJNID1QArLJuRxNGLRddFDkgI0+Shu2MppbsMBqLoMIFAk61xJBkFAA)

```sh
--parser typescript
```

**Input:**

```tsx
// Not breaks here
export class LongLongLongLongLongLongLongComponentA extends LongLongLongLongLongLongLongComponentB {
  
  @Effect()
  // Not breaks here
  selectSomethingQueryParam$: Observable<SelectSomeAction> = this.selectFirstSomething$.pipe(
    switchMap(() =>
      this.store$.pipe(
        select(getSomethingParamState),
        filterUndefined(),
        distinctUntilChanged(),
        skip(1),
        takeUntil(this.someElementStream$)
      )
    ),
    map(someElementId => new SelectSomeAction(someElementId))
  );
  
    constructor(
      @Inject(MAT_DIALOG_DATA)
      // Not breaks here
      public data: sharedModels.TheCoolestShinyComponentDialogData<sharedModels.MyFavouriteModel>,
      public dialogRef: MatDialogRef<TheCoolestShinyComponentDialogComponent>
    ) {}
  
}


```

**Output:**

```tsx
// Not breaks here
export class LongLongLongLongLongLongLongComponentA extends LongLongLongLongLongLongLongComponentB {
  @Effect()
  // Not breaks here
  selectSomethingQueryParam$: Observable<SelectSomeAction> = this.selectFirstSomething$.pipe(
    switchMap(() =>
      this.store$.pipe(
        select(getSomethingParamState),
        filterUndefined(),
        distinctUntilChanged(),
        skip(1),
        takeUntil(this.someElementStream$)
      )
    ),
    map((someElementId) => new SelectSomeAction(someElementId))
  );

  constructor(
    @Inject(MAT_DIALOG_DATA)
    public // Not breaks here
    data: sharedModels.TheCoolestShinyComponentDialogData<sharedModels.MyFavouriteModel>,
    public dialogRef: MatDialogRef<TheCoolestShinyComponentDialogComponent>
  ) {}
}

```

**Expected behavior:**

**Comment by attilacsanyi** [comment] 2021-08-13 09:16
I reported in an already closed ticket since [May 2021](https://github.com/prettier/prettier/issues/2482#issuecomment-836690835), thanks for helping.

**Comment by alex12058** [comment] 2022-07-04 07:55
The issue with class extends seems to be related to this very old issue created in 2018 #5156

In the thread they recommend the style:
```ts
interface Foo extends 
    VeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongClassName {}

class Foo extends 
    VeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongClassName {}
```

I think this style is more consistent and better aligns with prettiers current formatting.
```ts
interface Foo
    extends VeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongClassName {}

class Foo
    extends VeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongClassName {}
```

**Comment by thorn0** [comment] 2022-08-29 13:03
(rewording my comment [from ](https://github.com/prettier/prettier/issues/2482#issuecomment-1222358530))

It's difficult to proceed here because those are 3 separate problems. Could you please make separate isolated issues for each of them? (Tip: use the Report Issue button on the [playground](https://prettier.io/playground/) to create issues.)

**Comment by seiyab** [comment] 2023-07-30 05:54
- First one looks duplicate of https://github.com/prettier/prettier/issues/5156 or https://github.com/prettier/prettier/issues/10087, as https://github.com/prettier/prettier/issues/11344#issuecomment-1173478987 also says.
- For second one, v3.0.0 works fine.
    - ```ts
      // Not breaks here
      selectSomethingQueryParam$: Observable<SelectSomeAction> =
        this.selectFirstSomething$.pipe(
      ```
- Third one look neither duplicated nor resolved.

May I report the third one as a new isolated issue?

**Comment by kachkaev** [comment] 2023-07-30 20:03
Thanks @seiyab! Feel free to create a new issue for v3.0 if it’s not being tracked already. Let’s close this one as it’s 2+ years old and is somewhat outdated.

**Closed by kachkaev** 2023-07-30 20:03 UTC
Labels: type:bug, area:comments, lang:typescript

**Comment by seiyab** [comment] 2023-07-31 05:31
I have investigated the third problem more.
Finally I decided not to report it as a new issue by myself.

It looks a problem around decorator + [parameter property](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties) + comment ([Prettier Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAMQgj2AB0o9mDpSZsBXMGHACkYsWAAQAmcSIKF4A9DLwA5CPgBG2OMQDWFABZx1UoRk4rCASzB5RxGMSR5OUTVAgB3KABpDeAJR0AvoyBUCAeIBAYMGZsyKDE2NhuAArxCKTIIMSErsQAnulhasRgmnAwAMrEALZwADJmUHDIAGZZpHCF2MWlFRjFDQDmyBycHSDtVWbDXGOkg4RwAIqcyk1IrYTtYQBWpGjl80sr8C1tYwCOx3BJiRjpKGQAtI1w4qKhIBzEZuZQAwDCECqVWIGTgpAArB85n8FgBBGAcMwqTjwJL6eqNU6bMY6GBVQgAdR0ZngpD6YDg5TSpLMADdSbkMmByB86aMAJJQcSwcpgbBmSJw7nlGC5BbYrYgDCJdqEroYDIy8H6OlNMINdq4G7EAYgyVjPrYLUZMUYcH8wUwD4yhowQlmUQwHTIAAcAAYwupLmZ1Dq9aD1mcwrYVA6nS6kAAmMKcdoAFWIKnuGylcCqKleb1qxD+nF1cGo2BBiMGGWIqIgH12aAAQl0SmVKjVMWtU3B-P4gA)).
TypeScript v5.1.6 might not support decorator for parameter property ([TypeScript Playground](https://www.typescriptlang.org/play?#code/DYUwLgBAJiDGD2AuCBDAdgTwNwFgBQ+IAHgA7wBOkswKAzrRAGLzwQDe+EXECatY5AK6wwFABSduXAAIwEkqQHpFEAHLxIAI3IgUAawYALEDoXcSgzcACWsaCjApkgtHrTwA7mgA0ZgJTsAL74wXhAA)).
This is probably because [TypeScript 5 isn't compatible with TypeScript 4 about decorator](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#decorators).
Considering decorator is an experimental feature for TypeScript 4, I think that the problem rarely arises.
(My opinion might be biased because I rarely use decorators or classes.)

If someone encounter the problem, feel free to report it.
It can be reproduced.
