### ISSUE TITLE
Support Undo in idea

### ISSUE THREAD

**Issue by axetroy** [prettier/prettier#1093] opened 2017-03-28 14:21 UTC
recover the code from last format.

``CRTL+Z`` didn't work at all.

**Comment by vjeux** [comment] 2017-03-29 11:04
Can you tell us what IDE you used. It works for me in the Nuclide integration.

**Comment by axetroy** [comment] 2017-03-29 11:23
@vjeux 
sorry, I didn't express clearly. 

JetBrains, Webstorm.

**Comment by jlongster** [comment] 2017-04-03 18:24
This also works in Emacs. I think we should close this issue and a bug should be filed in whatever editor integration you are using.

**Comment by h-taylor** [comment] 2017-04-11 14:13
I am using Intellij with the same problem. I was able to find a work around: http://stackoverflow.com/questions/8106126/intellij-idea-cannot-undo . Essentially you can look at your local change history to get the previous version. Is there another command besides --write we could use? I think that is were the problem is happening.

**Comment by vjeux** [comment] 2017-05-21 21:49
This is very unfortunate, but I don't think that there's much we can do. If someone has a reasonable way to fix it, we should document it. I'm going to close this issue for now.

**Closed by vjeux** 2017-05-21 21:49 UTC
Labels: bug, Editor Support
