### ISSUE TITLE
Call format with an already parsed AST

### ISSUE THREAD

**Issue by Gregoor** [prettier/prettier#1274] opened 2017-04-14 10:48 UTC
Hi there :wave: 

I like what you're doing and I'm thinking about incorporating prettier into https://gregoor.github.io/syntactor/ when I make the jump to full JS support. Since I use babylon and have the current AST lying around at all times, I was wondering if it's possible to pass an AST into format?

If not and you're interested I'd go ahead and write a PR for it as soon as I really need it.

:rainbow:

**Comment by tunnckoCore** [comment] 2017-04-14 12:33
mm yea, sounds like a good idea to me, it will save time in very large codebases

**Comment by jlongster** [comment] 2017-04-14 14:57
I think there is already an issue for this. We definitely want to support this. The problem is that there are a *few* places where we inspect the original source for a few things (like we keep single blank lines that were in the original source). So we need to go through all the places we do that and figure out a good default behavior when we don't have the original source behavior.

Fwiw, there is already `prettier.__debug.formatAST`. But it's super secret and don't tell anyone about it! :) It won't reliably work because of the problems I mentioned above. We should probably rename it to `__debugSecretDontUseOrYouWillBeFired`.

**Comment by vjeux** [comment] 2017-04-14 15:06
#465

**Comment by Gregoor** [comment] 2017-04-14 15:17
That was fast :) Thanks for the helpful responses :+1:

About finding blank linkes: Can't that be deduced from the Source Location field (`loc`)? https://github.com/babel/babylon/blob/master/ast/spec.md#node-objects

**Comment by jlongster** [comment] 2017-04-17 14:50
@Gregoor that's what we do, but you need the original source to look up that location and inspect it.

**Comment by vjeux** [comment] 2017-05-21 22:08
I'm going to close this :)

**Closed by vjeux** 2017-05-21 22:08 UTC
Labels: Needs discussion
