### ISSUE TITLE
Unstable formatting

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#10076] opened 2021-01-18 12:13 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAwhALYAO0CMAFAJT7AA6U++kUAzjPgNrOutMAIwA2EMAGtCAQwBOAEwA0-AcHxjp8nFADmSfMLGSZCgDIRN2nfgC+ylvgC6+ALwGOcAKpRR4qXPkAWXQYaVxoajVpAHdpHBgAJThUOBgwAAsARXQ4WRw4Dn0YWRzFfFlk1Izs3PzC3mAARxzZAE99ADEcWS4ABTjYABFxdBIqG0cbWgBuZhsQRRAIMnDOZFA5WQho-oq1lGkRWNaOBZAhWWlJVIBlMiurZGLSkDgSITh5eU-TaV10aQ6OAdCCyEhhXC6ZAgaQhCBndIwEgiADq6XiBXuYDgNwQHHiOAAbvFWtCwBxTottB5ZDBepcdODkKhDh5FgArDgADwAQpdrjAbtIxqZtHBmay4BzuTcrCI4NkIPAJSI2SB7j1ctChNIPiIzmQ8rAUTh5DB0sgABwABkWhogHhRlzI0MNBVyhPFi2aSrg9OWpwOHAAtFA4J9PmcKs1un6GUykCzVVKQB4SDgniUU-jdPLFcrE5LFqEhCazRakAAmYuXHAiKzEEgJ14cACsZ3QHgAKrrA0m1YScgBJKDfWA3MB5FYAQVHNxgrXlKo8NhsQA)
```sh
--parser babel
```

**Input:**
```jsx
function Component() {
  const [
    unblockCard,
    { loading: unblockCardLoading },
  ] = useUnblockCardMutation({ awaitRefetchQueries: true, refetchQueries: [{query: FirstPaintDocument}]});
}
```

**Output:**
```jsx
function Component() {
  const [
    unblockCard,
    { loading: unblockCardLoading },
  ] = useUnblockCardMutation({
    awaitRefetchQueries: true,
    refetchQueries: [{ query: FirstPaintDocument }],
  });
}

```

**Second Output:**
```jsx
function Component() {
  const [unblockCard, { loading: unblockCardLoading }] = useUnblockCardMutation(
    {
      awaitRefetchQueries: true,
      refetchQueries: [{ query: FirstPaintDocument }],
    }
  );
}

```

I expect the first output to equal the second output

**Comment by fisker** [comment] 2021-01-18 12:25
Edited to use the `show second output` option from playground.

**Comment by thorn0** [comment] 2021-01-18 12:42
Duplicate of #7927

**Closed by thorn0** 2021-01-18 12:42 UTC
Labels: area:destructuring, area:idempotency, lang:javascript, type:bug

**Comment by thorn0** [comment] 2021-01-18 12:44
Destructuring + function call + object literal argument. Probably we should start fixing #7927 by providing a workaround for this particular combination first as the underlying issue is quite tricky.

**Comment by SimenB** [comment] 2021-01-18 13:28
> Edited to use the `show second output` option from playground.

Ah nice, didn't know about that one!
