### ISSUE TITLE
8️⃣0️⃣ Weird array property tabbing with 80-line-width.

### ISSUE THREAD

**Issue by Sawtaytoes** [prettier/prettier#10558] opened 2021-03-17 05:05 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAjANgQwAtMBeTACgB0pNN800BLAcygFsEZraA6MQ+gBMAZkNFoRYqRPGSZ0uYtnKxgtPmHqRajWs2TGUbpgDaAcggLhAgNYArEYTtDCwm0Nxv8dmTdzO-ETsCGzQHNwkbYWC0G0E7fU8EswBdYx4MAFdhYWoAShAAGhAIAAcYRnRkUHwAJ1qIAHcABTqENGQQfFxG-ABPDuLsWvwwGzgYAGVS0cNmZBhazLhiuDZsOEFBTYAZfChmTPxmOAAxCFq2fBgKg878TJgIIpBCGDZcAHVCRng0GbAcEm7V+jAAbr8+p0wAwXoY0HBajBmiNmFdkKJcAjij4AB4AIRGYwmk3wHB2hjgGO62JAeMmc1wcAAipkIPBqViViAZrUEbVOth8BtcC9SrVDDBPoxBDBCMgABwABmK4ogCM+I1KnXFcH5YKpxQAjmz4Ciyh0UJAoEwMJwXrU4CbGI6Ucd0UhMbSEWxGAsltymAcmaz2VTPTTuTBhdLZfKkAAmYqLfCMXBzADCEDYHq6uFFxUyCIAKsLLV7uWDlgBJKDbWCTMAS8oAQTrkxgfSZnIRAF9e0A)

```sh
# Options (if any):
--quote-props consistent
--trailing-comma all
```

**Input:**

```jsx
const blah = (
  assignment
  .chasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfdsafsadfdsafdsfsdfain
  ['oasdfasdfhakjdfhjasdhfkasdlfkajsdfkljakldfjlaksjdfksdkfjlskdjfsdlfjf']
  .stuff
)
```

**Output:**

```jsx
const blah =
  assignment
    .chasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfdsafsadfdsafdsfsdfain[
    "oasdfasdfhakjdfhjasdhfkasdlfkajsdfkljakldfjlaksjdfksdkfjlskdjfsdlfjf"
  ].stuff;
```

**Expected behavior:**
```jsx
const blah =
  assignment
    .chasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfdsafsadfdsafdsfsdfain[
      "oasdfasdfhakjdfhjasdhfkasdlfkajsdfkljakldfjlaksjdfksdkfjlskdjfsdlfjf"
    ].stuff;
```

I don't know how Prettier wants to format this, but I'm assuming it's wrong as-is.

While this may seem ridiculous, it could happen pretty easily when tabbed over.

**Comment by thorn0** [comment] 2021-03-17 13:01
Duplicate of #8079

**Closed** 2021-03-17 13:02 UTC
Labels: type:duplicate
