### ISSUE TITLE
[markdown] math nodes shouldn't be formatted

### ISSUE THREAD

**Issue by benjaminabel** [prettier/prettier#5338] opened 2018-11-04 17:07 UTC
**Environments:**
- Prettier Version: 1.14.3
- Running Prettier via: CLI
- Runtime: Node.js v11
- Operating System: Linux

**Steps to reproduce:**
When formatting this markdown code:

```md
En utilisant des tensions de commandes $U_{GS}$ n'ayant que deux valeurs: 0, ou 5V, il est possible d'utiliser le transistor comme un **interrupteur** placé entre les bornes D et S et **commandé** par la tension $U_{GS}$.

$$
U_{GS}
$$
```
**Expected behavior:**
inline Math(between $) and math blocks(between $$) shouldn't be formatted and stay as unchanged as it is latex code.

**Actual behavior:**

```md
En utilisant des tensions de commandes $U*{GS}$ n'ayant que deux valeurs: 0, ou 5V, il est possible d'utiliser le transistor comme un **interrupteur** placé entre les bornes D et S et **commandé** par la tension $U*{GS}$.

$$
U\_{GS}
$$
```

Maybe we could had a configuration option to disable formatting of certain remark nodes.

**Comment by j-f1** [comment] 2018-11-04 21:33
Thanks for opening this! We fixed this in #5050, but we haven’t released the fix yet. We’re planning to publish a new release very soon, so you should be able to get the fixed version this week.

**Comment by j-f1** [comment] 2018-11-04 21:34
Duplicate of #3700

**Closed** 2018-11-04 21:33 UTC
Labels: lang:markdown, type:duplicate

**Comment by j-f1** [comment] 2018-11-04 21:35
Duplicate of #3700

**Comment by benjaminabel** [comment] 2018-11-05 22:10
@j-f1 sorry for the noise I didn't find the issue because I didn't look at closed ones. Thanks for your feedback and this really nice package.

**Comment by j-f1** [comment] 2018-11-05 22:14
No problem and thanks for using Prettier!
