### ISSUE TITLE
Chained assignment should obey printWidth or max-line-length rule

### ISSUE THREAD

**Issue by dereklin** [prettier/prettier#3819] opened 2018-01-24 19:45 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOgCYCuAtkQJ44ykAOcAjPsWQAoBOENLlAYgVGDBmgAdKAAJxEgLyj02BiXKUaAJnnM2Hbr36CoIiVJmZchBRWpwAzGtKt2cTqR58BwsQdHTZJxoosAWGztNJ21XPXcDL2MbcxoAViCNBy0XXX0PaLlTMji4ADYk+0dnHTcPTyNs3zyAdiKQ0vCMqKqfMyU4AA4GlNC08szRAAoASk8APlFgFo8WOBgCFjEAchzSFYBuWfEAX02QABoQdnCsZFAqFgxYAHUMPHRkLoAGY5gAQwAje8e0ZGUxywNwA5gAbOAARQIEHgyAAZh8wVg4O8WB8MGDQQBhCAkD7IEBQaBwI4gL7osAAawWAGUqB8wKDkDAWARUSAAFZYAAeACFKTSYLSPkQ4AAZG6kpCI5EchksFEsQlfb6kMHQMkoogYFlsjkEFEAFW+5xlSJRxxuSpgrA+IKIBPNcuO8wAjgQMPM7Q6nbLLSArhAUbd0VRCVc4EqAG6k44fFhsADuTATCDNIA+0YgDzJeAgYARFo5HywMCLLpOBBgVGrygrKN2uyAA)

**Input:**
```jsx
this.dummy.type1.dummyPropertyFunction
      = this.dummy.type2.dummyPropertyFunction
      = this.dummy.type3.dummyPropertyFunction
      = this.dummy.type4.dummyPropertyFunction
      = this.dummy.type5.dummyPropertyFunction
      = this.dummy.type6.dummyPropertyFunction
      = this.dummy.type7.dummyPropertyFunction
      = this.dummy.type8.dummyPropertyFunction
      = () => {
        return 'dummy';
      };
```

**Output:**
```jsx
this.dummy.type1.dummyPropertyFunction = this.dummy.type2.dummyPropertyFunction = this.dummy.type3.dummyPropertyFunction = this.dummy.type4.dummyPropertyFunction = this.dummy.type5.dummyPropertyFunction = this.dummy.type6.dummyPropertyFunction = this.dummy.type7.dummyPropertyFunction = this.dummy.type8.dummyPropertyFunction = () => {
  return "dummy";
};

```

**Expected behavior:**
Keep original because 1) it reads better and 2) the transformed code violates the printWidth and max-line-length rule

**Comment by bakkot** [comment] 2018-01-26 22:50
I think this is a duplicate of #2482.

**Comment by j-f1** [comment] 2018-01-26 23:05
Yep.

Duplicate of #2482

**Closed by j-f1** 2018-01-26 23:05 UTC
Labels: lang:javascript, type:bug
