### ISSUE TITLE
Not consistent formatting of objects

### ISSUE THREAD

**Issue by NameFILIP** [prettier/prettier#4342] opened 2018-04-18 19:56 UTC
What is the idea behind having different formats of the same object? Isn't it better to have the consistent way of writing it?

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTYbJTARgBpMAjEgJkrBIGYBfAbgB0ovIoMd8hYmUpdM4iZOp0GzdiHIgIABxgBLdMlDYATjogB3AAq6EaZCGwA3CGoAmCyxmQAzbABs0cRVR3YwANZwMADKyv5qUADmyDA6AK7eIHYQYK4eXoqRXjowRn5RALbY6Z5JAFZoAB4AQn6BwSHYhXAAMpFwpZlK8TDKvbRdSeE6ORZU2FQAnu7Qjso6kTAA6vYwABbIABwADIoLEF7LfsoWC3A5Vp2KOnAAjvFqt-nYRSVIbmWKXoVqsQlJNCRKLuOAARXiEHgQ0UMEmqzsG2Q9BAcWwancwIAwhBCsULFBoNcQPEvAAVSbmD4ZOAsFhAA)

**Input:**
```jsx
const a = {a: 1, b: 2, c: 3};

const a = {a: 1, 
           b: 2, c: 3};
```

**Output:**
```jsx
const a = { a: 1, b: 2, c: 3 };

const a = {
  a: 1,
  b: 2,
  c: 3
};

```

**Expected behavior:**
```jsx
const a = {
  a: 1,
  b: 2,
  c: 3
};

const a = {
  a: 1,
  b: 2,
  c: 3
};

```

**Comment by dasa** [comment] 2018-04-18 20:12
Seems to be by design: https://prettier.io/docs/en/rationale.html#multi-line-objects

**Comment by duailibe** [comment] 2018-04-18 20:39
@dasa is correct, this is by design, it's one of the times we take the original input in consideration (i.e. not only the AST but how you originally wrote the code) because there are so many use cases for objects in JS and Prettier has not been able yet to automatically print them "correctly".

Closing this but feel free to comment if something was not yet addressed.

**Closed by duailibe** 2018-04-18 20:39 UTC
