### ISSUE TITLE
JSX variable or statement injection: close brace placement.

### ISSUE THREAD

**Issue by Strate** [prettier/prettier#1438] opened 2017-04-27 15:34 UTC
Consider the code snippet:
```jsx
{condition &&
  <Element
    withMultiLine
    properties={[]}
  />}
```
and please note close `}` character position. I suggest to place it on new line:

```jsx
{condition &&
  <Element
    withMultiLine
    properties={[]}
  />
}
```

**Comment by lydell** [comment] 2017-04-27 15:40
I think this might be a duplicate of #1297.

**Comment by vjeux** [comment] 2017-04-27 16:53
Yup, indeed a duplicate. Also there's likely a few other related issues.

**Closed** 2017-04-27 16:53 UTC

**Comment by Strate** [comment] 2017-04-27 17:23
Sorry for dup.

**Comment by vjeux** [comment] 2017-04-27 18:18
@Strate please don't be! Feel free to report all the weird things you are seeing. It really helps to figure out how to prioritize them :)
