### ISSUE TITLE
Prevent errors when pattern doesn't match any files

### ISSUE THREAD

**Issue by rienheuver** [prettier/prettier#8233] opened 2020-05-06 12:06 UTC
**Environments:**

- Prettier Version: 1.19.1
- Running Prettier via: CLI
- Runtime: node 14.1.0
- Operating System: Ubuntu 20.04

**Steps to reproduce:**

`prettier ".unknown"`

**Expected behavior:**
Have a flag in the prettier CLI just like `--no-error-on-unmatched-pattern` like ESLint. So that if we run the CLI on a bunch of projects in our monorepo, it will skip those that have no relevant files (such as assets with only image files). Instead of breaking on those projects and killing the CI.

**Actual behavior:**
No such flag is currently present in the Prettier CLI, meaning we have to build a hack to circumvent this error.

**Comment by clement9527** [comment] 2020-07-14 17:54
@rienheuver Maybe I misunderstood your use case, but why do you need to run prettier on CI? I would imagine Prettier to be ran before checking in your code to ensure consistency in code style. 

I would like to see this error gone from my terminal as well. Having no matching file to format shouldn't be considered as an error.

**Comment by evilebottnawi** [comment] 2020-07-14 18:13
Duplicate of #8136

**Comment by AlicanC** [comment] 2020-07-14 21:43
@evilebottnawi I don't think this is a #8136 duplicate. This is about having a pattern like `src/*.js` and Prettier not throwing an error if there are no files that end with ".js" in "src".

**Comment by evilebottnawi** [comment] 2020-07-15 12:24
Oh yes, sorry, my mistake

**Comment by NickdeK** [comment] 2020-09-25 11:47
Just a quick workaround for some who run into this issue when running something like
`npx prettier --write '**/*.{js,ts,jsx,tsx,md}'` and get a `No files matching the pattern were found` for one of the file types. I'm using the following to work around this issue: `npx prettier --write '**/(*.js|.ts|.jsx|.tsx|.md)'`

**Comment by alvis** [comment] 2020-10-09 09:56
@NickdeK Thx. The workaround is kind of working, as long as you have at least one file matching the expression. 👍

**Closed** 2021-01-27 22:30 UTC
Labels: area:cli, status:needs discussion
