### ISSUE TITLE
Prettier produces an error when passed a directory path.

### ISSUE THREAD

**Issue by jpickwell** [prettier/prettier#7233] opened 2020-01-08 22:19 UTC
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: CLI
- Runtime: Node 10.16.3
- Operating System: macOS

**Steps to reproduce:**

```shell
./node_modules/.bin/prettier --write .
```

**Expected behavior:**

Anything but an error. Perhaps a no-op with a warning (exit code 0).

**Actual behavior:**

Error:
> No matching files. Patterns tried: . !\*\*/node_modules/\*\* !./node_modules/\*\* !\*\*/.{git,svn,hg}/\*\* !./.{git,svn,hg}/\*\*

Exit code: 2

**Comment by thorn0** [comment] 2020-01-09 13:31
Duplicate of #6085

**Closed by thorn0** 2020-01-09 13:31 UTC
