### ISSUE TITLE
Error: "highest level" was not printed

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [prettier/prettier#15073] opened 2023-07-10 15:18 UTC
"prettier": "^3.0.0",
"eslint-plugin-prettier": "^5.0.0-alpha.2",
node --version
v18.16.0

```
Oops! Something went wrong! :(

ESLint: 8.44.0

Error: Comment "highest level" was not printed. Please report this error!
    at ensureAllCommentsPrinted (file:///home/app/.yarn/cache/prettier-npm-3.0.0-7ffbcce680-6a832876a1.zip/node_modules/prettier/index.mjs:17941:13)
    at printAstToDoc (file:///home/app/.yarn/cache/prettier-npm-3.0.0-7ffbcce680-6a832876a1.zip/node_modules/prettier/index.mjs:18102:3)
    at async coreFormat (file:///home/app/.yarn/cache/prettier-npm-3.0.0-7ffbcce680-6a832876a1.zip/node_modules/prettier/index.mjs:18405:14)
    at async formatWithCursor (file:///home/app/.yarn/cache/prettier-npm-3.0.0-7ffbcce680-6a832876a1.zip/node_modules/prettier/index.mjs:18603:14)
    at async Module.format2 (file:///home/app/.yarn/cache/prettier-npm-3.0.0-7ffbcce680-6a832876a1.zip/node_modules/prettier/index.mjs:21789:25)
```

Does not occur with "prettier": "^2.8.8" and "eslint-plugin-prettier": "^4.2.1"

**Comment by JounQin** [comment] 2023-07-11 00:55
You need provide more details.

**Comment by Eejit43** [comment] 2023-07-12 01:58
This is likely a duplicate of #15007.

**Closed** 2023-07-26 00:12 UTC
Labels: status:awaiting response

**Comment by SheldonWBM** [comment] 2023-07-28 22:11
Determined where the error occurred, deleting the comment "highest level" fixes it, but not why it occurred.
Prettier should not crash on the comment.
```
const something = (myNum: number): number => {
  if (myNum <= 11) return 0.0625;
  else if (myNum === 12) return 0.125;
  else if (myNum === 13) return 0.25;
  else if (myNum === 14) return 0.5;
  else if (myNum === 15) return 1.0;
  else if (myNum === 16) return 2.0;
  else if (zoommyNum=== 17) return 4.0;
  else if (myNum === 18) return 8.0; // highest level
  else return 10.0;
};
```

**Comment by SheldonWBM** [comment] 2023-07-28 22:15
> This is likely a duplicate of #15007.
It is unlikely related to the above issue but it is potentially related to this issue: [#10592](https://github.com/prettier/prettier/issues/10592)

**Comment by SheldonWBM** [comment] 2023-07-28 22:24
> This issue has been automatically closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.

Auto-close PRs within a month? This error is low on my priority list. Good to address on a Friday evening. Now using version 3 but, concerned that a simple comment can crash it.

**Comment by fisker** [comment] 2023-07-29 02:04
@SheldonWBM  You case is duplicated of #15007, and #15076 fixed it. [Playground](https://deploy-preview-15076--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuc0DOMAEaIFs4wAWAllAOaYC8mAFLgJ4ByArrkplKwEZwBOAlO064evKgD5MwADpRMmYgDNaDFrkwAeagEZt-TLwLNecgAwA6UwDYATAFYA3LPlwANmjgLldJqyqUdG31DGGMzc217JzlMNw8vFV91AJ0AZmCjE0wLKOdY908lRLV-HQAWDNCsi0c8uMLvVT8UzG07SrDWy2iXAoSfEpbtKw6sm266vqKB5oDWgHZRuTKJmPr+puS57QAOJcwd7swAemPMEjJCOAxMVzgANzdJ+JDO7QtTaIBfBxAAGhAEAADjBiOhkKAAIa8XgQADuAAVoQg0MgQJDXHDIfRUQCuLxIWAANYEADKkPwABlSHBkIoMR48QTiWSgYTSGRkDBeMw4ACPLhiFyeXyQGgOXcAIrMCDwOkM0UAKzQAA9SRK4NLZbSkPSCgCAI4y+AI2FA1EoSFoAC0UDgcAAJo7-iBuZDiK4OQBhPC4SFojGuF3i8h3ACCMG5xC4zBNfGpdvl+pAhBguFcAHUSPA0GywHBSSjiKD7sX6GiwGhcSB7ryAJJQJ2wUlgXjEEFhxukmD0O5JxkgIGwjwZglAtFD658R4u0geXgwU2Qsh+-uitm8edontA66t9swF1D0gwDPEB1EZA7UwAwxG4iGJcr-26hUAmCQrhni+EZA2AHMB4AAqn4WnqA5wCIjpOg6lKQuQzDLnAABiEC8H6kYcgGsYQCAXxfEAA)

We'll release it soon.
