### ISSUE TITLE
Prettier requires two saves to get it correct

### ISSUE THREAD

**Issue by imoby** [prettier/prettier#3949] opened 2018-02-11 06:42 UTC
Description: When attempting to save using vscode and eslint with prettier configuration, I get an error after the first save saying the following error. It requires me to have to save twice to get it where it needs to be.

```Replace `(⏎····<div>⏎······my·component⏎····</div>⏎··)` with `<div>my·component</div>` (prettier/prettier)```

**Step 1:**
Below is the sample code of my stateless react component example in its initial state. This below snippet threw the following warnings:
![image](https://user-images.githubusercontent.com/6380855/36070598-162c8972-0ec4-11e8-8a76-2154b29386fa.png)

```
import React from 'react';

const Login = () => {
  return (
    <div>
      my component
    </div>
  );
};

export default Login;
```
**Step 2:**
After clicking save, I get the following formatted code shown with a brand new warning:
```
import React from 'react';

const Login = () => (
    <div>
      my component
    </div>
  );

export default Login;
```
![image](https://user-images.githubusercontent.com/6380855/36070608-478ffa12-0ec4-11e8-91fa-cca497631afb.png)

**Step 3:**
Only after the second save of the file do I get to the correct format of code. Im curious why it just wont do this on the first attempt.

Final output of code after second save
```
import React from 'react';

const Login = () => <div>my component</div>;

export default Login;
```

**Comment by ikatyang** [comment] 2018-02-11 07:02
It seems it's caused by the eslint `arrow-body-style` rule, see the difference between step1 and step2.

I'm closing this issue since there's nothing we can do here.

**Closed by ikatyang** 2018-02-11 07:02 UTC
