### ISSUE TITLE
Markdown table doesn't get correctly prettified if one of the content is ``

### ISSUE THREAD

**Issue by Haroenv** [prettier/prettier#3812] opened 2018-01-24 13:26 UTC
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABAOQIYFs7qFHFEYAqAngA4GnoAicAZtgK4A2MJ3PvJGjAM5gATgEsqMMdD6y58hQtQAdKBgC0mrdp3r0G3fvS6TpsyaPmr1m7btb9qjIJjYwAa3kYAQhAjs4bCgjAAMWdkE4EMUY4gwASSZ0GBFWOAAadAB3MXZ2dGwqGigAE3QROEEOGEF0CCSoOAAPLipsAHMCGAh0MFYRCthyyurarIALBHQ2zt7xoM7alTVhqs5BdRoRTY6CDExWXAAjOBFCDBDo2Ov+dDJJ9ChDk7P61dHknpKxQSp2bAo+hA6RAEEk0iggmQoGwAwgWQACrCEFCUNgAG4QMQlYEgbAuZDhSIgo4iNzuOAwADKbTAYig7WQKTSIJKEDAhOwEQyIHpkREMARZPauGwnO5IIAVoImt4yR5KVS8HAADL0uDi4mg1gwKg6gBMmp5bRE-OQIFFIncbKyUFxVHEsAA6tiYONkAAOAAMIIdEEiTrJVHNDsqp3RGpBFQAjqwxBUhR1RUaQZFcGImakeYJ6e0AgBFVgQeApkCuI4ukpu5D6kEpbC5XMAYQguGTKCg0EjIFYkTI2COqKJcAAviOgA)
```sh
--parser markdown
```

**Input:**
```markdown
| Name             | Type    | Default                               | Description                                                                    |
| ---------------- | ------- | ------------------------------------- | ------------------------------------------------------------------------------ |
| stack            | Boolean | `false`                                 | If true, will append results of next page to current results when page changes |
| results-per-page | Number  | ``                                       | The number of results to display |
```

**Output:**
```markdown
| Name             | Type    | Default                               | Description                                                                    |
| ---------------- | ------- | ------------------------------------- | ------------------------------------------------------------------------------ |
| stack            | Boolean | `false`                               | If true, will append results of next page to current results when page changes |
| results-per-page | Number  | `` | The number of results to display |

```

**Expected behavior:**

```markdown
| Name             | Type    | Default | Description                                                                    |
| ---------------- | ------- | ------- | ------------------------------------------------------------------------------ |
| stack            | Boolean | `false` | If true, will append results of next page to current results when page changes |
| results-per-page | Number  | ``      | The number of results to display                                               |
```

Interestingly, if the original was: 

```markdown
` `
```

This get shortened into

```markdown
``
```

and subsequently breaks the table on second pass of prettier

**Comment by ikatyang** [comment] 2018-01-24 13:31
Hi, this is a duplicate of #3753, let's track the issue there.

**Closed by ikatyang** 2018-01-24 13:31 UTC

**Comment by Haroenv** [comment] 2018-01-24 14:18
sorry for the duplicate 😞
