### ISSUE TITLE
Prettier uses asterisks (*) in list when list using dashes (-) is preceded or followed by list using asterisks

### ISSUE THREAD

**Issue by TimonVS** [prettier/prettier#11304] opened 2021-08-02 10:42 UTC
Prettier wrongfully tries to format a list using asterisks (*) when a list using dashes (-) is preceded or followed by a list using asterisks. If a list using dashes is preceded by one using asterisks, it actually swaps the dashes for asterisks.

**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqABARgDpQwJlwwGZd10BadAFl1ypyisKfVKnKoFYzL0A2XrhAAaEBAAOMAJbQAzslABDAE4qIAdwAKqhApRKANhqUBPBWIBGKpWADWcGAGUJt6VADmyGCoCucMTgAW0s4ABMw8IAZJU9fJQ84ADEIFSClGBlPZBAlXxgIURAACxggwwB1Yul4OVcwOCc9GukANxrTHLA5CxB3OTgVGC0bD3TkADMjAbEAKzkADwAhG3tHJyUguCj3OEnpgJB5had3D0M4AEVfCHh9wxmQVxUBlRz0lTswzSgiiRV3DAKtIwjBisgABwABjE-wgAwqNgkOX+cFerT2YgAjjd4CNJPpcnIKFA4OFwkUVHAcdIqSMEuMkFMHocBkFpN4-Kyzhdrrc9kyDmIYEpLMDQeCkPhhTZpIYzgBhCBBRkgNFcIq+AYAFVF+mZj1a-gAklBIrAnGAAVIAIJmpwwUwXe4DAC+rqAA)

**Input:**

```md
* 1
* 2
  - 3

- 1
- 2
  - 3
```

**Output:**

```md
- 1
- 2
  - 3

* 1
* 2
  - 3
```

**Expected behavior:**

Since Prettier usually converts asterisks (*) to a dashes (-), I would expect the whole list to use dashes:

```md
- 1
- 2
  - 3

- 1
- 2
  - 3
```

**Comment by kachkaev** [comment] 2021-08-02 16:06
👋 @TimonVS! Prettier keeps both `-` and `*` because they are indicators for two separate lists. See https://github.com/prettier/prettier/issues/6814 for context.

[Adding `<!-- -->`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqABARgDpQwJlwwGZd10BadAFl1wB4BCCqlgPjqipy-UN9JRyVAKxlK6AGzjcIADQgIABxgBLaAGdkoAIYAnPRADuABX0ItKHQBsjOgJ5aFAIz06wAazgwAykveqUADmyDB6AK5wCnAAts5wACYJiQAyOsHhOkFwAGIQejE6MGrByCA64TAQ8iAAFjAx1gDqtarwGv5gcD4WbaoAbm32ZWAaTiCBGnB6MCZuQYXIAGY2UwoAVhoAHgBCbp7ePjoxcCmBcMurUSCbWz6BQdZwAIrhEPCX1msg-npTemVCnoPAljFAako9IEYE1VAkYLVkAAOAAMCkhECmTTcSjKkLg-36FwUAEc3vA5spLOUNBQoHBEokano4GTVCy5llFkgVl9rlMYqpQhF+Q8nq93hceVcFDAdM5YfDEUh8LK3KprA8AMIQGLckAEkQ1cJTAAq8ssvO+-UiAEkoMlYD4wFCVABBB0+GD2J6fKYAX39QA) makes list boundaries unambiguous, which allows Prettier to replace `*` with `-`.

**Comment by TimonVS** [comment] 2021-08-02 16:25
Hey @kachkaev, thanks, that makes sense. In my example, Prettier swaps `*` from the first list with `-` from the second list and vice versa, is that also expected behavior?

**Comment by kachkaev** [comment] 2021-08-02 16:29
Yeah I think it does. Prettier prefers `-` so when it sees the first list with `*`, it swaps the symbol. When it reaches the end of the list it finds a new list with nothing in-between, so the only option it has is to now replace `-` with `*`. The output is stable though, so it’s a one-way change.

If all bullet points are the same in the input, Prettier converts them all to `-` because they represent a single list.

**Comment by mattyclarkson** [comment] 2022-01-20 10:31
> Prettier prefers - so when it sees the first list with *, it swaps the symbol.

Marpit (a markdown presentation framework) has different meaning for `-`/`*`

`-` lists are presented all at once on a slide and `*` are presented fragmented.

Should we preserve the first seen prefix?

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAMQJYCcDOM6AygDbYAmc6Ntd9DjTzLrdAOlG9z73-004BadABUAFnHxxh6AIK4ZUEcXEQA7lFkBJKIQCGsUgE9OwoULNQMmXPoDmAWwTwKJclU4DvP3-04AVGKS0oHyimGq+ooUYQDyUEpBcjBhcmGi2M5WADwAhBacEtQABgEl6AAOigBm2AAe6Nj46FAQRNVScLgAbnCxWlDEcNTiMDCV+EgA9NP22DDiAK4ARgB0kI7TjtGVQvD6Wzu4lQvTzfhLUtMAjAAsAKzmQgB8IAA0IBCVMNjQ+MhQNFcBoAArRBAAlD6HoQSgfEArOxgADWcBgxEOcAAMthEsgavpSNJPkj9Kj0cRKuS8fZkDBcFdPnBHCt+lQKNjDPYlg44JgILgduNacgQPoljAIAixo5SAB1cQLKTUsBwYZ6BbYHoLYxisD4AGfPHSXAwUF2Jz6AlEkkgABW+HqxFppDgAEUlu04DbiXBPtSCN0xccURQNFAEdU8TB5ZRFsgABwABgDIOk8rslTFnVNfQRAEcvfALd8oeL8EJEv1+gjFEW8HALQ4dr67dJHNh6Yz-SB8K6PcWfUhCX7PjB9Cs4xQE0gAEzjuzYchQewAYQgjlbKDa+M+S2koknUNHdp6V10VFgxDAuGwPzkUAoxBgxjdbd7jvqACFkWiMViuL4iOtpwAAvmBQA)

**Comment by kachkaev** [comment] 2022-01-24 17:28
Hi @mattyclarkson 👋

Not sure I can imagine support for both `-` and `*`. [Commonmark](https://spec.commonmark.org/0.26/#lists) and [GFM](https://github.github.com/gfm/#lists) do not distinguish between markers, so looks like Marpit is not using markdown in a conventional way.

[We can’t add an option](https://prettier.io/docs/en/option-philosophy.html), so let’s imagine we’ve decided to preserve `*` (and `+`?). A lot of folks will complain, but imagine we ignore that for the sake of argument. What we may see next is a new issue that asks to keep `_italics_` / `*italics*` & `__bold__` / `**bold**` because of some other tool. A similar thing can happen to `# h1` / `h1\n==` / `## h2` / `h2\n--`. If we serve those needs too, not much will be left from Prettier 😅

My suggestion would be to reach out to Marpit folks and suggest some alternative syntax for fragmented lists. For example, this can be `- <!-- click --> list item`, which is explicit about what it does. This will surface the knowledge, so make Marpit markdowns less cryptic for folks who haven’t read the docs.

I’ll close this issue because we have expected behaviour here.

**Closed by kachkaev** 2022-01-24 17:28 UTC
