### ISSUE TITLE
Incorrect max length breakdown on bracket

### ISSUE THREAD

**Issue by Artoria-0x04** [prettier/prettier#7091] opened 2019-12-04 05:42 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEwA6VOYCWAtgMowQBOcANJmgBYQDuAwgwIYx1gCuGEYnEqlhAN0Jg4AQTCResPAF9MAXnoVqAbUhQAZoQDmAOmoATXgA9yVOADkOQgLogaICAAcYhdMlAdKShYABQCENGQQDjEIQjNXEAAjSg4wAGs4GFIPVMIoQ2QYSl5aEAYYYgAbAHUGQng0HKlRKDR6wgkYAE9IsDQItzy0YRhglMNiDmQ9DkrhtwArNEsAIRT0zNJHOAAZPLhp2fmQJes8w0q4AEVeCHhDudKcymHKSMSORK7K6ASPSjyMGqcRgDGQAA4AAxuf4QYbVFIeSL-OCvMQHNwAR1u8DGngiKA4aAAtFA4HAzBSEtRsYRqGMOBMpkgZo83MNiIRCsVSm18pcbncDiyjqUYJ9gWZQcgAExuIocQiVc6sQSTSJQaAYkD8OAAFU+BNZxzEJQAklBKbBSGAAV5pJbyN9hcbSmYIGAHsciTAvXAlEogA)
```sh
# Options (if any):
# none
```

**Input:**
```jsx
// code snippet
const {
  imStore, showChat, customerServiceAccount
} = store[config.reduxStoreName]
```

**Output:**
```jsx
// code snippet
const { imStore, showChat, customerServiceAccount } = store[
  config.reduxStoreName
];
```

**Expected behavior:**
Tried to search on keyword `bracket` and `javascript` with no luck.
I'm not sure why this happens, but IMO prettier should treat `array literal` and `property accessor` differently, leave the code as-is.

**Comment by lydell** [comment] 2019-12-04 07:06
This could possibly be another manifestation of  #2482.

**Comment by thorn0** [comment] 2019-12-04 07:43
Also very similar to https://github.com/prettier/prettier/issues/3227.

**Comment by evilebottnawi** [comment] 2019-12-04 09:37
@thorn0 yes, it is duplicate #3227, i think we can close issue and add this example

**Comment by lydell** [comment] 2019-12-04 10:26
Duplicate of #3227

**Closed by lydell** 2019-12-04 10:26 UTC
