### ISSUE TITLE
TypeScript trailing comma on type parameters

### ISSUE THREAD

**Issue by benny-medflyt** [prettier/prettier#9338] opened 2020-10-06 13:59 UTC
When setting the `--trailing-comma` setting to "all", prettier does not add a comma to TypeScript type parameters.

Example:

```typescript
export function long_long_long_long_long_long_long_function<
  AAAAAAA,
  BBBBBBB,
  CCCCCCC,
  DDDDDDD,
  EEEEEEE,  // <--- prettier removes this comma!
>(
  aaaaaa: AAAAAAA,
  bbbbbb: BBBBBBB,
  cccccc: CCCCCCC,
  dddddd: DDDDDDD,
  eeeeee: EEEEEEE,
) {
  console.log(aaaaaa, bbbbbb, cccccc, dddddd, eeeeee);
}
```

It looks like at some point in the past, prettier actually did add the trailing commas to type parameters, but this was removed in #1832 because TypeScript apparently didn't support it. TypeScript does now though (I'm not sure since which version, see <https://github.com/microsoft/TypeScript/issues/16152>)

**Comment by kachkaev** [comment] 2020-10-06 14:17
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAMwFcowYBLaPAG2gHMB9WqR51+pjtzlh40itAA8AHSh48AQWkzJAGjESAQitVKF4vAGEdurRokARYycMG8AUSvWLciQHp7eIQFo3eDNjgwKcbHi8AWwgANzgAZzwYAAtySMhAwIBDAEIxAD4ACkU8JLz8pClZaXMAI3KKwrVVczA6+sK9XXMAEzb2wtMTczhevsKbaw0ASjxgHMgocIhqOAA6WjpM-Py7Coq7evq7dva7Pr7hgG4xAF8QORAIDEEp5FAk7GwIAHcABUeEcOQQJOoXpIAT2+l1K2CSYAA1t4AMoYCHkFjIGDYIhwS5wQKlOBtHEAGSSLCISTocAAYjhkj5EXQfkkiDAIBcQNEYIFqAB1WLwcLwsBwGFfcgUELCwE-MDhEEgRHhPwwN7gujJZAEP5yy4AK3CaCU4KhsKSgTgeMRcFV6vRIG1aBhNNmAEUiBB4BbqBqQPDsHLsD8YICMBEwNhyDdmZ5ETAOeQWjFkAAOAAMl08EDlHPBGB+ngifjCzIAjs74Irrt8UElwi4oL0WjjmV4i+QvIqSSqkGr3Va5YFyMjUd37XAnS7zR3LZcYElStHY9FkAAmSfg8jUGlaCCJJJ06jUZlEOUAFWn5c7HpCaIAklA67AYcHQzBJDeYf7Zm65adTkA)

Please follow the issue template: https://github.com/prettier/prettier/blob/master/.github/ISSUE_TEMPLATE/formatting.md

**Comment by thorn0** [comment] 2021-01-26 14:02
Duplicate of #3662

**Closed by thorn0** 2021-01-26 14:02 UTC
Labels: lang:typescript, type:bug
