### ISSUE TITLE
"prettier-ignore" not working with HTML

### ISSUE THREAD

**Issue by thongpv** [prettier/prettier#4383] opened 2018-04-26 06:52 UTC
Hi sir, I have a problem in HTML

**Input:**
```jsx
<span class="icon-ic-border-color-24px">
    <span class="path1"></span><span class="path2"></span>
</span>
```

**I want output result same input, but it result: :**
```jsx
<span class="icon-ic-border-color-24px">
    <span class="path1"></span>
    <span class="path2"></span>
</span>
```

I can't use 
```jsx
<!-- prettier-ignore -->
or
<!-- prettier-ignore-start -->
<!-- prettier-ignore-end -->
```

**Comment by thongpv** [comment] 2018-05-04 02:37
Thank @evilebottnawi !

**Comment by lydell** [comment] 2018-05-04 06:58
Duplicate of #1882

**Closed** 2018-05-04 06:58 UTC
