### ISSUE TITLE
unstable nested lists in markdown

### ISSUE THREAD

**Issue by Haroenv** [prettier/prettier#3337] opened 2017-11-28 14:33 UTC
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAJTgGzgQwGc4AdKMgKnQG10BddAIwFcBLHAE3ULACdWADjDLpRYqrQYDeBALaM86ABQADAPQUAhOkgCAnvwDmACxjoAdJYpqVASko166AcwWtCx7n0HCoEpy5uHugwegKsUIaEImKi-gwAZjgQAO4xsfEhYXA8-EIOkugAolCEzDLo6jj48IQwKujMxLyE6CnQAORmhnBmAGoALOjQ6ABWhAAiuKwAbrzKAIKEANYhxnCyIRDcMBACjQIcNRGG6KYwAkhqamAcUObjHNNz5lC9avg4hhA4rEQEvDAxjU1VqMHsfkcDFkrEMvGOI0MbCeBScCggpwEEDqZDIGAAwhAUeRIYVGLxUsR0Gp0HAAB5Y3hmekweHRKCxOLoVjweG7XgAWncxnS4kqkFKZkY6AAvOg3il0ABJKBPOkAIQpKWaSlsAG4mK8WUoAIwABgt+oaSkgzE46A421kdpggkU+HCOk+OEIEM56CoKgldW4svlcEVAGU9FBoHpZJrKXBeLq9SpRVyg9AQ-M5QqsHa4IntcnU+mOZyqDIBNUwHBKuSkwscDgVAAaSr0xkwTCFwjtzsMiBM6OxqDx-sFOkMViyGsbBBmOo1OAJO3oGQAR2YOSXrJXhj0TH+XBGMHW3AEcDAGYD4pkK+w293yfL-qo+ASvPQACYzegYVKNZ61dWQ4AgZgzHcY8wFWXYHVXfAXVvD8v2TdATR-bhr2gDhWnPesElYFozGMbEoPw-g4C4fBDHwCIUJoacznI7lVXpbhjHwfhIkY6hmLIkMIjVNiZk+VgjldaA+OYoF8EietBLMZgsQ5UDwMgmSGHUiCly4njDC0kJZw0qCoDE35JNYaSKwyKEN3kx0YSpBJvUYfBYJYkMlGE1g619VEGHOAQ+ICbiqS3Hc6gAeSEaygJqYCzhgC50GqPRk1Chh0uTdl-XfezY2JfLK3sgANAAJTBbwKwoEl6IFlASYdsN4GY-PrdpeGWXKIQkWSPOME4p2hXoyK4QhYSgGpyhyIy5IU9AahgQaAAVuPwMDeXw7ZoBwI9lsG7CJQ4EbuTnPAwNgJaW3QBZVqVACxqJdl+pnOdhzMJ5XJdBDpGvBESQKlRZ27G7vl+f5uMahIKU2DpPghv5iGh4wOgNRGfmRgEgVTakaWSKJaQZappqkqA31KwowWotibpwJhmFVPAWiW1VuB5ZhAbyqmnDqPJuTMXSAPI-a6ekIlcSgDAABVd3ZQLaVKWbBbaYdllaCIHVYBJ6pka6knwGYIJaLKsAIMAzAAOWOGZSFssVCgWSI7W4xWIngOFAZCeXFbAQbhtJJwADFWDpdBg+SRVqJ6f3iAV6XinM4joAXa6ygEbspcyZp2rrNXutyxX5KRap5hrZhDAYoOpApOkjwzsGlAqmWZdWgB9VbMGisqAE10BbtvI077u+5lYLCCuNQmmTJABCIQguo4AABQRzDXjf9gQGZ0DE-h8AUHI+vsuA7d4OE4AQJgtWabgVKzmuAPwPRGHrLF9qIltWma+YlSKE0TRSxAG2EAexyaEGQKAIgMBkCuR9HAEB5IPI9RgJGeeYATjIFZDuEBjowCwM+MQEBERmgwFWvCQwsh8AEPgSA8YGp4SwV6JGTacAAAyEQ4A0KIaAyCLgYA-m4QgkA88WjJmQCAKh3VHQpCgMAkRPEYAAHUJLnmQAADjNCAiWxAlHwgEEIkBkViJwHIbRKhhiQDEBhFg3gOCrEnDwAARWYBAeAliVqMBURwNRSAfwgP3OwE4hJZAWJQGOLhICZ4ywPhApAcDiAAF9ElAA)
```sh
--parser markdown
--no-prose-wrap
```

**Input:**
```markdown
# Release

* [ ] build script
      * [ ] preamble (`/*! copyright ...*/`)
* [ ] publish script
* [ ] publish typings
      * [ ] flow
      * [ ] typescript
* [ ] Ensure `/latest` users won't get V4 on jsDelivr (Ask them to stop updating http://cdn.jsdelivr.net/algoliasearch/latest)
* [ ] migration guide
* [ ] blog post

# Code

* [ ] browse / export extras
      * iterator-ish
      * `const b = new IndexBrowser(); b.next(1000);` (could do multiple api calls)
      * `const s = new SynonymBrowser();`
      * `const r = new RuleBrowser();`
      * replace `browseAll`, `exportRules`, `exportSynonyms`
* [x] implement stateful request strategy based on the spec
      * `createRequester`
      * after 20 mins the timeout is back to default
      * after 12 seconds the first host is tried again
      * [x] host index sharing
      * [x] host index invalidation
      * [x] change host upon timeout
      * [x] timeout sharing
      * [x] timeout invalidation
      * [ ] randomise fallback host (indices)
* [ ] http
      * [ ] parse requestOptions at the http layer
      * [ ] layers
            * [ ] node
            * [ ] XHR
            * [ ] fetch (for service workers)
* [x] caching
* [x] method signatures
      * [x] change attachParameters to only attach second
* [x] implement all API methods
* [x] import default deprecation
      * `import algoliasearch from 'algoliasearch'; algoliasearch(); // logs explanation`
      * [ ] tested in all bundlers and situations
      * [ ] strip it out mostly in prod

# Tests

* [ ] ensure it works in different flavours
      * [ ] React Native
      * [ ] Angular
* [ ] integration tests
* [ ] caching
* [ ] Fix Flow edgecases

# Environement support

* [ ] service workers
* [ ] angular plugin
* [ ] proxy support (HTTP_PROXY HTTPS_PROXY=https://user:password@ip.ip.ip.ip env variables)
* [ ] evergreen browser support
* [ ] maybe polyfills for IE11


```

**Output:**
```markdown
# Release

* [ ] build script _ [ ] preamble (`/_! copyright ...\*/`)
* [ ] publish script
* [ ] publish typings _ [ ] flow _ [ ] typescript
* [ ] Ensure `/latest` users won't get V4 on jsDelivr (Ask them to stop updating http://cdn.jsdelivr.net/algoliasearch/latest)
* [ ] migration guide
* [ ] blog post

# Code

* [ ] browse / export extras _ iterator-ish _ `const b = new IndexBrowser(); b.next(1000);` (could do multiple api calls) _ `const s = new SynonymBrowser();` _ `const r = new RuleBrowser();` \* replace `browseAll`, `exportRules`, `exportSynonyms`
* [x] implement stateful request strategy based on the spec _ `createRequester` _ after 20 mins the timeout is back to default _ after 12 seconds the first host is tried again _ [x] host index sharing _ [x] host index invalidation _ [x] change host upon timeout _ [x] timeout sharing _ [x] timeout invalidation \* [ ] randomise fallback host (indices)
* [ ] http _ [ ] parse requestOptions at the http layer _ [ ] layers _ [ ] node _ [ ] XHR \* [ ] fetch (for service workers)
* [x] caching
* [x] method signatures \* [x] change attachParameters to only attach second
* [x] implement all API methods
* [x] import default deprecation _ `import algoliasearch from 'algoliasearch'; algoliasearch(); // logs explanation` _ [ ] tested in all bundlers and situations \* [ ] strip it out mostly in prod

# Tests

* [ ] ensure it works in different flavours _ [ ] React Native _ [ ] Angular
* [ ] integration tests
* [ ] caching
* [ ] Fix Flow edgecases

# Environement support

* [ ] service workers
* [ ] angular plugin
* [ ] proxy support (HTTP_PROXY HTTPS_PROXY=https://user:password@ip.ip.ip.ip env variables)
* [ ] evergreen browser support
* [ ] maybe polyfills for IE11

```

**Expected behavior:**

**Comment by Haroenv** [comment] 2017-11-28 14:50
This happens when formatting twice

**Comment by ikatyang** [comment] 2017-11-28 14:50
Hi, it seems your input is already invalid (see rendered content below), or if you're saying that the `Input` you mentioned is your first output and the `Output` is the second output, it should be a duplicate of #3295, and is already fixed on master.

There's a [`show second format (debug)` option](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAJTgGzgQwGc4AdKMgKnQG10BddAIwFcBLHAE3ULACdWADjDLpRYqrQYDeBALaM86ABQADAPQUAhOkgCAnvwDmACxjoAdJYpqVASko166AcwWtCx7n0HCoEpy5uHugwegKsUIaEImKi-gwAZjgQAO4xsfEhYXA8-EIOkugAolCEzDLo6jj48IQwKujMxLyE6CnQAORmhnBmAGoALOjQ6ABWhAAiuKwAbrzKAIKEANYhxnCyIRDcMBACjQIcNRGG6KYwAkhqamAcUObjHNNz5lC9avg4hhA4rEQEvDAxjU1VqMHsfkcDFkrEMvGOI0MbCeBScCggpwEEDqZDIGAAwhAUeRIYVGLxUsR0Gp0HAAB5Y3hmekweHRKCxOLoVjweG7XgAWncxnS4kqkFKZkY6AAvOg3il0ABJKBPOkAIQpKWaSlsAG4mK8WUoAIwABgt+oaSkgzE46A421kdpggkU+HCOk+OEIEM56CoKgldW4svlcEVAGU9FBoHpZJrKXBeLq9SpRVyg9AQ-M5QqsHa4IntcnU+mOZyqDIBNUwHBKuSkwscDgVAAaSr0xkwTCFwjtzsMiBM6OxqDx-sFOkMViyGsbBBmOo1OAJO3oGQAR2YOSXrJXhj0TH+XBGMHW3AEcDAGYD4pkK+w293yfL-qo+ASvPQACYzegYVKNZ61dWQ4AgZgzHcY8wFWXYHVXfAXVvD8v2TdATR-bhr2gDhWnPesElYFozGMbEoPw-g4C4fBDHwCIUJoacznI7lVXpbhjHwfhIkY6hmLIkMIjVNiZk+VgjldaA+OYoF8EietBLMZgsQ5UDwMgmSGHUiCly4njDC0kJZw0qCoDE35JNYaSKwyKEN3kx0YSpBJvUYfBYJYkMlGE1g619VEGHOAQ+ICbiqS3Hc6gAeSEaygJqYCzhgC50GqPRk1Chh0uTdl-XfezY2JfLK3sgANAAJTBbwKwoEl6IFlASYdsN4GY-PrdpeGWXKIQkWSPOME4p2hXoyK4QhYSgGpyhyIy5IU9AahgQaAAVuPwMDeXw7ZoBwI9lsG7CJQ4EbuTnPAwNgJaW3QBZVqVACxqJdl+pnOdhzMJ5XJdBDpGvBESQKlRZ27G7vl+f5uMahIKU2DpPghv5iGh4wOgNRGfmRgEgVTakaWSKJaQZappqkqA31KwowWotibpwJhmFVPAWiW1VuB5ZhAbyqmnDqPJuTMXSAPI-a6ekIlcSgDAABVd3ZQLaVKWbBbaYdllaCIHVYBJ6pka6knwGYIJaLKsAIMAzAAOWOGZSFssVCgWSI7W4xWIngOFAZCeXFbAQbhtJJwADFWDpdBg+SRVqJ6f3iAV6XinM4joAXa6ygEbspcyZp2rrNXutyxX5KRap5hrZhDAYoOpApOkjwzsGlAqmWZdWgB9VbMGisqAE10BbtvI077u+5lYLCCuNQmmTJABCIQguo4AABQRzDXjf9gQGZ0DE-h8AUHI+vsuA7d4OE4AQJgtWabgVKzmuAPwPRGHrLF9qIltWma+YlSKE0TRSxAG2EAexyaEGQKAIgMBkCuR9HAEB5IPI9RgJGeeYATjIFZDuEBjowCwM+MQEBERmgwFWvCQwsh8AEPgSA8YGp4SwV6JGTacAAAyEQ4A0KIaAyCLgYA-iwbwHBIB54tGTMgEAVDuqOhSFAYBoieIwAAOoSXPMgAAHGaEBEtiDKPhAIbhCCQCRWInAchtEqFGJAcQGEQiRGTUiHgAAiswCA8BrEgBWowVRHB1FIB-CA-c7ATiElkFYlAY4uEgJnjLA+ECkBwOIAAX2SUAA) on the playground, which is for such unstable issue.

<details>
<summary>Rendered Content</summary>

# Release

* [ ] build script
      * [ ] preamble (`/*! copyright ...*/`)
* [ ] publish script
* [ ] publish typings
      * [ ] flow
      * [ ] typescript
* [ ] Ensure `/latest` users won't get V4 on jsDelivr (Ask them to stop updating http://cdn.jsdelivr.net/algoliasearch/latest)
* [ ] migration guide
* [ ] blog post

# Code

* [ ] browse / export extras
      * iterator-ish
      * `const b = new IndexBrowser(); b.next(1000);` (could do multiple api calls)
      * `const s = new SynonymBrowser();`
      * `const r = new RuleBrowser();`
      * replace `browseAll`, `exportRules`, `exportSynonyms`
* [x] implement stateful request strategy based on the spec
      * `createRequester`
      * after 20 mins the timeout is back to default
      * after 12 seconds the first host is tried again
      * [x] host index sharing
      * [x] host index invalidation
      * [x] change host upon timeout
      * [x] timeout sharing
      * [x] timeout invalidation
      * [ ] randomise fallback host (indices)
* [ ] http
      * [ ] parse requestOptions at the http layer
      * [ ] layers
            * [ ] node
            * [ ] XHR
            * [ ] fetch (for service workers)
* [x] caching
* [x] method signatures
      * [x] change attachParameters to only attach second
* [x] implement all API methods
* [x] import default deprecation
      * `import algoliasearch from 'algoliasearch'; algoliasearch(); // logs explanation`
      * [ ] tested in all bundlers and situations
      * [ ] strip it out mostly in prod

# Tests

* [ ] ensure it works in different flavours
      * [ ] React Native
      * [ ] Angular
* [ ] integration tests
* [ ] caching
* [ ] Fix Flow edgecases

# Environement support

* [ ] service workers
* [ ] angular plugin
* [ ] proxy support (HTTP_PROXY HTTPS_PROXY=https://user:password@ip.ip.ip.ip env variables)
* [ ] evergreen browser support
* [ ] maybe polyfills for IE11
</details>

**Comment by Haroenv** [comment] 2017-11-28 14:54
original input was:

<details>

```markdown
# Release
- [ ] build script
  - [ ] preamble (`/*! copyright ...*/`)
- [ ] publish script
- [ ] publish typings
  - [ ] flow
  - [ ] typescript
- [ ] Ensure `/latest` users won't get V4 on jsDelivr (Ask them to stop updating http://cdn.jsdelivr.net/algoliasearch/latest)
- [ ] migration guide
- [ ] blog post

# Code
- [ ] browse / export extras
  - iterator-ish
  - `const b = new IndexBrowser(); b.next(1000);` (could do multiple api calls)
  - `const s = new SynonymBrowser();`
  - `const r = new RuleBrowser();`
  - replace `browseAll`, `exportRules`, `exportSynonyms`
- [x] implement stateful request strategy based on the spec
  - `createRequester`
  - after 20 mins the timeout is back to default
  - after 12 seconds the first host is tried again
  - [x] host index sharing
  - [x] host index invalidation
  - [x] change host upon timeout
  - [x] timeout sharing
  - [x] timeout invalidation
  - [ ] randomise fallback host (indices)
- [ ] http
  - [ ] parse requestOptions at the http layer
  - [ ] layers
    - [ ] node
    - [ ] XHR
    - [ ] fetch (for service workers)
- [x] caching
- [x] method signatures
  - [x] change attachParameters to only attach second
- [x] implement all API methods
- [x] import default deprecation
  - `import algoliasearch from 'algoliasearch'; algoliasearch(); // logs explanation`
  - [ ] tested in all bundlers and situations
  - [ ] strip it out mostly in prod

# Tests
- [ ] ensure it works in different flavours
  - [ ] React Native
  - [ ] Angular
- [ ] integration tests
- [ ] caching
- [ ] Fix Flow edgecases

# Environement support
- [ ] service workers
- [ ] angular plugin
- [ ] proxy support (HTTP_PROXY HTTPS_PROXY=https://user:password@ip.ip.ip.ip env variables)
- [ ] evergreen browser support
- [ ] maybe polyfills for IE11

```
</details>

**Comment by Haroenv** [comment] 2017-11-28 14:55
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAJTgGzgQwGc4AdKAWnQG10BddAIwFcBLHAE3ULACcWAHGGXTpKNevx4EAtgzzoAFAAMA9ACoAhOkj8AnnwDmACxjoAdBbUqlASjJi66fkzktCRrrwFCK1R89d3dBhdfhYoA0JhUT96ADMcCAB3aId6EP44bj5Be1j0AFEoQiYpdFUcfHhCGCV0JmIeQnQk6AByUwM4UwA1ABZ0aHQAK0IAEVwWADceRQBBQgBrYKM4aWCILhgIfnr+dirwg3QTGH4kFRUwdigzUfZJmbMobpV8HAMIHBYiAh4wIwqSrVGB2XzidDSFgGHiHIYGVgPPIQuQQY78CA1MhkDAAYQgSPBjgYPGSxHQKnQcAAHhieKYaTBYVEoCJKCx4LDtjxyG4jKlypBiqYGOgALzoF5JdAASSgD2pACFSUlGgobABuRjPRkKACMAAYjZq6gpIEwOOh2JtpBaYAJ5Pgwtp3jhCGC2YLoDUuOLJXBpQBlXRQaC6aTKslwHjqjVKAVKIU+2YSqVYC1wSOq6Ox+OsmJSfiVMBwcokqNzHA4JQAGnKNLpMEwGcItfrtIg9ODoag4dbyOp9BY0iLawQphqVTgcQt6CkAEcmFkJ0ypwZdIxfpwhjBVlxMmAE7wCPBsIvl9G8578HFOegAEwGyHhZq70v26RwCBMUxuTdgZZtitad8DtAUbzvPV7y4OAhXYV89ziFgmlMIxMV-V8+DgTh8AMfBwgFKhBxOdD0HCBUuCMfA+AiQjiLQn1yJpMioCmd4WAOe1oDo+gAXwCJSwY0wmAxVkPy-H8eOCYcJInKiaIMKTxO-X9WPYziWG4-M0jnfjrShck4ldBh8AAkifQUciWBLd1kUcU5+EI-xqPJBclxqAB5QRNOKdAqhWQSYDOdBKl0aMnPoULoxZERPQhUNCVimIIQADQACUwaI4scOJugBRQ4k7GCeCmazS1aHhFmisExGIsBTKMI4B3oT9dwJLhoSgKpSiyKS+IEvygoagAFaj8Fa6KNkGKAcA3KoYAamC4OasiRzwT9YD8qt0DmYaZUhbo0Pglbh0bYCjLtYDJFguEoATU7O1Md5Pm+X5qPyuJSXWNpnq+H5iHeow2i1X7XoB-4jFjClKUSSIqVpSouq4qAr2SxwQWwlitpwRgmHlPAmj8+UOpgJhbpitH6BqHIyNMFTIXQ2asckAlsSgDAABVlxZHSEBKMoORaTtFmacIrRYOJcqkTaEnwKZvyaCKsAIMBTAAOUOKZSG0-I5giC1qLsodYDgGFbuCbmjZdAEmqJegADEWGpdB7cSaVsK6eriBZHFClY5DoDHTaSn4RsrcaUqSyFyroqt-iEUqWYiyYAwCLtpxSWpDcQ7OhQ0o5jnhoAfWGzAPJSgBNdB88LwMS7LyuxQcwgLhUBpoyQfgiEICr2AAAQEMxB+H3YECmdA2L4fA5CyGr8jgLWeBhOAEEYFVGi4ESw-T6R8F0BhSwxWakKrZpCtmGUCj1PU2ZAGsQB2ZHCGQUAiBgZAjLdOB75JUyqpgQMXcwBHGQEyJc99rRgA-u8Yg98XzRhgMNWEBhd7QK-vfUYSpYQAW6IGcacAAAy4Q4BoNgQ-H8zgYD3lATwcBIAu5NGjMgEAu9KrWiSFAO+9CaIwAAOocV3MgAAHAae+LNiC8NhPwUh38QBuWQnAJBuFUFIE-mQ4gUIaF0MIEcPAABFJgEB4AyPvgtBg-D2CCKQPeUxsI2BHHxNIFRIAewkPvu3Dm09n6qJgXAAAvn4oAA

**Comment by ikatyang** [comment] 2017-11-28 15:05
Thanks for the report, looks like indeed a duplicate of #3295, and it's fixed on master, see [playground](https://deploy-preview-3331--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBiABAJTgGzgQwGc4AdKAWnQG10BddAIwFcBLHAE3ULACcWAHGGXTpKNevx4EAtgzzoAFAAMA9ACoAhOkj8AnnwDmACxjoAdBbUqlASjJi66fkzktCRrrwFCK1R89d3dBhdfhYoA0JhUT96ADMcCAB3aId6EP44bj5Be1j0AFEoQiYpdFUcfHhCGCV0JmIeQnQk6AByUwM4UwA1ABZ0aHQAK0IAEVwWADceRQBBQgBrYKM4aWCILhgIfnr+dirwg3QTGH4kFRUwdigzUfZJmbMobpV8HAMIHBYiAh4wIwqSrVGB2XzidDSFgGHiHIYGVgPPIQuQQY78CA1MhkDAAYQgSPBjgYPGSxHQKnQcAAHhieKYaTBYVEoCJKCx4LDtjxyG4jKlypBiqYGOgALzoF5JdAASSgD2pACFSUlGgobABuRjPRkKACMAAYjZq6gpIEwOOh2JtpBaYAJ5Pgwtp3jhCGC2YLoDUuOLJXBpQBlXRQaC6aTKslwHjqjVKAVKIU+2YSqVYC1wSOq6Ox+OsmJSfiVMBwcokqNzHA4JQAGnKNLpMEwGcItfrtIg9ODoag4dbyOp9BY0iLawQphqVTgcQt6CkAEcmFkJ0ypwZdIxfpwhjBVlxMmAE7wCPBsIvl9G8578HFOegAEwGyHhZq70v26RwCBMUxuTdgZZtitad8DtAUbzvPV7y4OAhXYV89ziFgmlMIxMV-V8+DgTh8AMfBwgFKhBxOdD0HCBUuCMfA+AiQjiLQn1yJpMioCmd4WAOe1oDo+gAXwCJSwY0wmAxVkPy-H8eOCYcJInKiaIMKTxO-X9WPYziWG4-M0jnfjrShck4ldBh8AAkifQUciWBLd1kUcU5+EI-xqPJBclxqAB5QRNOKdAqhWQSYDOdBKl0aMnPoULoxZERPQhUNCVimIIQADQACUwaI4scOJugBRQ4k7GCeCmazS1aHhFmisExGIsBTKMI4B3oT9dwJLhoSgKpSiyKS+IEvygoagAFaj8Fa6KNkGKAcA3KoYAamC4OasiRzwT9YD8qt0DmYaZUhbo0Pglbh0bYCjLtYDJFguEoATU7O1Md5Pm+X5qPyuJSXWNpnq+H5iHeow2i1X7XoB-4jFjClKUSSIqVpSouq4qAr2SxwQWwlitpwRgmHlPAmj8+UOpgJhbpitH6BqHIyNMFTIXQ2asckAlsSgDAABVlxZHSEBKMoORaTtFmacIrRYOJcqkTaEnwKZvyaCKsAIMBTAAOUOKZSG0-I5giC1qLsodYDgGFbuCbmjZdAEmqJegADEWGpdB7cSaVsK6eriBZHFClY5DoDHTaSn4RsrcaUqSyFyroqt-iEUqWYiyYAwCLtpxSWpDcQ7OhQ0o5jnhoAfWGzAPJSgBNdB88LwMS7LyuxQcwgLhUBpoyQfgiEICr2AAAQEMxB+H3YECmdA2L4fA5CyGr8jgLWeBhOAEEYFVGi4ESw-T6R8F0BhSwxWakKrZpCtmGUCj1PUQBrEAdmRwhkFAIgYGQIy3TgO+SVMqqYEDLuYAjjICZEuO+1owDv3eMQO+L5owwGGrCAwu8oGfzvqMJUsIALdEDONOAAAZcIcBUEwPvj+ZwMB7wgJ4GAkAXcmjRmQCAXelVrRJCgLfOhNEYAAHUOK7mQAADgNHfFmxAeGwn4NQ2hblkJwEQbhFBSAP6kOIFCaRX8QCECOHgAAikwCA8ASGaIWgwPh7ABFIHvHfVcbAjj4mkEokAPZiF33bhzaeT9lHQLgAAX18UAA).

**Closed by ikatyang** 2017-11-28 15:05 UTC
Labels: lang:markdown, status:awaiting response

**Comment by Haroenv** [comment] 2017-11-28 15:16
Thanks! Looking forward to the release @ikatyang

**Comment by ikatyang** [comment] 2017-11-28 15:19
See #3333 for the 1.9 release.
