### ISSUE TITLE
Prettier breaks jsdoc comments linebreaks

### ISSUE THREAD

**Issue by pushkine** [prettier/prettier#13179] opened 2022-07-26 11:46 UTC
**Prettier 2.7.1** [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKB6AVF9ACLPAMwgjz30ICMBDAJ0o3QBs4ZjS8BePARgG4QAGhAQADjACW0AM7JQ9OhADuABXoI5KGs2U0AnnJFU6NMAGs2AZRoBbOABlJUOMiI6ZcY6YvWxZ5wBzZBg6AFcvEDhbKjgAEzj4hxooQLCaQLgAMQg6WxoYKVTkEBowmAhhEAALGFtmAHVqyXgZfzA4K00WyQA3Fv0SsBkjEGdPOhhVU0D8tw9IgCsZAA8rINYARTCIeHnmTxF-OgmS2ljmKrE6ZxgGyTiYauQADgAGI6VPBtMxEuu4BNeq4RABHHbwabiLSlGQAWhc8XiVTocHBklR0wycyQ7gOkU8tkkIXCBI2cG2u1cuIWIhgNCo90ezyQACY6aZJMwggBhCC2HFRGQAViqYU8ABUGVo8YcQL0IgBJKCJWBWMA3CQAQRVVhg+lY+08AF9jUA)

----

**Input:**

```jsx

/**
 * foo  
 * bar
 */
let foo = 1;
```

The line ` * foo  `  ends with two spaces. On hover, the comment prints this way: 
<img width="145" alt="Code_2022-07-26_13-39-48" src="https://user-images.githubusercontent.com/30108880/180997636-f7647411-ec81-484e-a251-8bff97235b40.png">

----

**Output:**

```jsx

/**
 * foo
 * bar
 */
let foo = 1;
```

The line ` * foo` is trimmed. On hover, the comment prints this way: 
<img width="145" alt="Code_2022-07-26_13-39-57" src="https://user-images.githubusercontent.com/30108880/180997613-bb975ea1-9090-448e-a2e3-78a01a025e67.png">

**Comment by thorn0** [comment] 2022-07-26 15:28
Duplicate of #6793

**Closed** 2022-07-26 15:28 UTC
