### ISSUE TITLE
Formatting Changes in PR #9992 are unreasonable

### ISSUE THREAD

**Issue by pfeileon** [prettier/prettier#11367] opened 2021-08-19 12:22 UTC
### Input
`const x = (i = 1) => () => i;`

### Output
```
const x =
  (i = 1) =>
  () =>
    i;
```

### Issues
* It's less readable
* It's four times more lines of code

#9992, #9985

**Comment by alexander-akait** [comment] 2021-08-19 12:23
Sorry, we don't want to change it

**Comment by alexander-akait** [comment] 2021-08-19 12:24
Also duplicate of https://github.com/prettier/prettier/issues/4061

**Closed by alexander-akait** 2021-08-19 12:23 UTC

**Comment by AndrewKvalheim** [comment] 2022-04-04 23:00
It appears that #4061 is about calling functions while this is about defining them.

It’s unfortunate that this new behavior comes at the cost of reduced space in the body:

<table><tr><th>Before</th><th>After</th></tr><tr><td>

```javascript
const example = ({ env }) => (args) => {
  // Body is indented once
};
```

</td><td>

```javascript
const example =
  ({ env }) =>
  (args) => {
    // Body is indented twice
  };
```

</td></tr></table>
