### ISSUE TITLE
Prefer single line HTML template string if possible

### ISSUE THREAD

**Issue by saschanaz** [prettier/prettier#7101] opened 2019-12-05 12:48 UTC
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjADgZQK4FtcCGATgJ4B0B66CAJgMIAWAlgDY0AUDMuLABgDwMATAD4AQnADOMAAQAFIgTAwmYKTJz5iJfgHphI3gEoA3CAA0ICOhXRJyUMSIQA7nOIJ7KAgDcITGgs0RTAAazgYTHQlJigAc2QYImw4Sy4eAHVmeElotUxPJhUfIpJkcEl7S1jJOCIYBQI4wmQAMwIWWssAK0kADzEQ8MiCXDgAGVi4No6ukF6+zFi4ljgARWwIeBnO1JBoolqictQCVDgWIPQiWJgMgJgGZAAOAAZLa4hajMV0cuupHUfNNLABHTbwBTWLwgAiSAC0UDgcBoKKCRDg4KYGMazQIOzmtVwTESyT2kmWqw2W2mSHau0sMDO9xoj2QQkZilYyzoEC05Sg0BBIGwtQAKmcvPS5j4UgBJKCo2CYMA3GwAQUVmBgJFWBLgAF8DUA)
```sh
--parser babel
```

**Input:**
```jsx
bpSummary.appendChild(html`<h2>Best Practices Summary</h2>`);
```

**Output:**
```jsx
bpSummary.appendChild(
  html`
    <h2>Best Practices Summary</h2>
  `
);

```

**Expected behavior:** This needlessly makes the line length 5x. I want to keep it simple as possible.

**Comment by evilebottnawi** [comment] 2019-12-05 12:51
Duplicate of #7096

**Closed by evilebottnawi** 2019-12-05 12:51 UTC
