### ISSUE TITLE
Format untagged JavaScript template literals preceded by /* JavaScript */

### ISSUE THREAD

**Issue by mfulton26** [prettier/prettier#6817] opened 2019-11-05 16:18 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBzATgQwAcALARwBtMBeTAegCpMBxAkgRQBlN7bMADUgFc4uAJ6ZgmKPgC2cTAF8+AbgA6USFAyYAVvgBu+AMphcAS0JYaDTACkDx0xaw9+mtBHJwAdOQjYACmBpOSRVEABZMyg4cIUASmUVEAAaEAhLM3RkUHxcXAgAdwAFPIQ0ZBADCDMAE1SQACMCMABrOBgjQnwwaOxkGFxhNOIYGXIAdWIzeDRusDgjcpmzfRnRSrA0CrTotBEYYoJsGXxkADN8cn20nTQADwAhFvbO2TgOaLgLq5uQO-uRj6XjYggg8B+1zgaW6uH2uEqjXwjTg5AahHMsAmdRgxGQAA4AAwwgr7CasSoYuDw-TfNJCcFwI4ZCoofBoAC0MTgtR5DVwcCEZgFR3wJzOSEuULS+xkZgGQ2hIDQwLgoMZkL+MGR2NquOQACY0oN8GZyH0AMIQGSnSpQaB0kCCfYAFWRrKl+wUCiAA)
```sh
--parser babel
```

**Input:**
```jsx
const graphql = /* GraphQL */ `query { name }`;
const javaScript = /* JavaScript */ `console.log({name:"Mine"});`;
```

**Output:**
```jsx
const graphql = /* GraphQL */ `
  query {
    name
  }
`;
const javaScript = /* JavaScript */ `console.log({name:"Mine"});`;

```

**Expected behavior:**
```jsx
const graphql = /* GraphQL */ `
  query {
    name
  }
`;
const javaScript = /* JavaScript */ `
  console.log({ name: "Mine" });
`;

```

It would be great to make this work with basically any supported language (JavaScript, TypeScript, JSON, Markdown, GrpahQL, etc.) so that other languages can easily be used within JavaScript (even JavaScript itself, e.g. when writing a script to send to a remote browser for execution, etc.).

**Comment by lydell** [comment] 2019-11-05 16:50
We seem to have an open PR for this: https://github.com/prettier/prettier/pull/5993

**Comment by thorn0** [comment] 2019-11-05 17:36
Duplicate of #5908

**Closed by thorn0** 2019-11-05 17:36 UTC
Labels: status:needs discussion, type:duplicate, type:feature
