### ISSUE TITLE
Markdown secondary list line-wrapping behavior is confusing

### ISSUE THREAD

**Issue by kkocdko** [prettier/prettier#10463] opened 2021-03-04 15:27 UTC
This:

```markdown
Test

- List
  - Secondary
```

Is compliant and not be changed. But if I **add some content, the line-wrapping behavior comes different:**

**Input:**

```markdown
Test

- List
  - Secondary

- List
  - Secondary
```

**Output:**

```markdown
Test

- List

  - Secondary

- List
  - Secondary
```

A newline inserted to first secondary list.

I don't know why this behavior, is this a feature or bug?

Test with `v2.2.1`.

**Comment by thorn0** [comment] 2021-03-04 16:25
I don't have the full picture of this behavior of Prettier, and investigation is needed, but this issue is a duplicate.

**Comment by thorn0** [comment] 2021-03-04 16:25
Duplicate of #8004

**Closed** 2021-03-04 16:26 UTC
Labels: lang:markdown, status:needs investigation, type:duplicate

**Comment by kkocdko** [comment] 2021-03-04 16:45
Sorry to disturb you, I just search "markdown line" but found nothing.
