### ISSUE TITLE
SCSS single-line comments are formatted incorrectly

### ISSUE THREAD

**Issue by d0x** [prettier/prettier#5603] opened 2018-12-07 11:32 UTC
**Important Note:**
Prettier has nice support for Grid-Template-Areas . See [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6A5gJwJYBMAEwAOlPvlngLTwC2ADgDYCG8lTmcTAzkiWWURAALTrjiYyIpmIn4pMwX36CueOACN2+SLAQxt0eLEWllIAGYQI8WZeviydm4IDcJAL4gANCAh0Y2NBcyKDsmBAA7gAK7AjBKEwAbhB43iDqmExgANZwMADKdFnYUOjIMJgArnA+QjA0DADqQtjwXEVgcPlxrdiJrQCeyOBcwT4lXOIwUZnoNEzI5kwMkz4AVlwAHgBCmTl5+Uw0cAAyJXCLy6sgG5v5JegMcACKlfaXKzUgRZiTmMNcMCjNJ0HCwRp4GBCZAADgADD5QRBJo1MnRhqC4H9EhcfBwAI6VbAcGZMOYLJBLT4+SY0bDlKpfVSlJ6vd6Uq5fGBMdQQ3BQ5AAFh8FSY2AYDwAwhAaPNhlBoLiQJVJgAVHnxKnXbgwD7XXAQMB6r4QSowOhmgBMxvc7iAA )

The example shows only how to reproduce the issue with single-line comments!

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAKgCwJYDOGhGAygMKmkB0GACgE5wwx5wMYC2EAbnETBxwMAQyYiMBAA5wweAGZ4wI1tAwBXKRgBGcfFAAmGQcPQZInTghgAdKNQDmDPEeB2MHzx6cuAtPE4pABsVOF8xOBECJAx0dy8EmxAhEQN2DBS0jkz2JNjUeITPJIIXOG0xc2h4WCrYazy4qCKvJPkICHgOds70nq6kgG53AF8QABoQCClVKAJkUDEGCAB3Ogi55BARHggXCZBtBhEwAGtmUikTvCgHZBgGdThJnBhOIIB1fHhpE7hSBClVg8PAwACeWzABHmkxuBHYMEYIgcnBEyHkIiC8MmACsCAAPABCxzOFxEVgAMjc4OjMdiQHj8aQbg4gnAAIrqXq0rHPEBXBjwhhbAhQmH85ywD4uQTIAAcAAZJlJlvCPscpFsVfx2HwDkwAI7qPBMJEotFIDG8ybwzh4e6PPmlW5szncy10vkwETaaUGWVIABMkweIjwQRZ5AglgtICg0Bpk3U8KwPvmHt5IxGQA)
```sh
--parser scss
```

**Input:**
```scss
// This is SCSS. Prettier moves the area specification up behind the // comment
.grid {
        grid-template-areas: //
          "header header header" //
          "sidebar content content" //
          "footer footer footer";
 }
```

**Output:**
```scss
// This is SCSS. Prettier moves the area specification up behind the // comment
.grid {
  grid-template-areas: // "header header header"//
    "sidebar content content"//
    "footer footer footer";
}
```

**Expected behavior:**
```scss
// This is SCSS. Prettier moves the area specification up behind the // comment
.grid {
  grid-template-areas: // 
    "header header header" //
    "sidebar content content" //
    "footer footer footer";
}
```

There are related (closed) Issues for older Versions:
- https://github.com/prettier/prettier/issues/4311
- https://github.com/prettier/prettier/issues/4594

**Comment by theblang** [comment] 2019-11-08 18:34
This turned out to be a blocker for us using SCSS formatting. We saw that SCSS parameters were getting lost due to the comments being moved to the same line, which resulted in build errors. See the below example.

```
@include pointy_button(
    $matchingBoardButtonSelector,
    'cfMatchingBoardAnswerButtons',
    $matchingBoardFontSizeSM, // font-size desktop
    $matchingBoardFontSizeXS, // font-size mobile

    url('~vectors/non_pointy_button_light_turquoise_border.svg'), //base
    $COLOR_V3_WHITE,
    $COLOR_V3_TURQUOISE_LIGHT,


    url('~vectors/non_pointy_button_turquoise_border.svg'), // hover
    $COLOR_V3_WHITE,
    $COLOR_V3_TURQUOISE,

    url('~vectors/non_pointy_button_turquoise_background.svg'), // active
    $COLOR_V3_TURQUOISE,
    $COLOR_V3_TURQUOISE,

    url('~vectors/non_pointy_button_turquoise_background.svg'), // selected
    $COLOR_V3_TURQUOISE,
    $COLOR_V3_TURQUOISE,

    url('~vectors/non_pointy_button_dark_turquoise_background.svg'), // completed
    $COLOR_V3_TURQUOISE_GRASSY_DARK,
    $COLOR_V3_TURQUOISE_GRASSY_DARK,

    url('~vectors/non_pointy_button_green_background.svg'), //correct

    url('~vectors/non_pointy_button_yellow_background.svg'), //incorrect

    'right'

);
```

becomes

```
@include pointy_button(
    $matchingBoardButtonSelector,
    'cfMatchingBoardAnswerButtons',
    $matchingBoardFontSizeSM,
    // font-size desktop
        $matchingBoardFontSizeXS,
    // font-size mobile
        url('~vectors/non_pointy_button_light_turquoise_border.svg'),
    // base $COLOR_V3_WHITE,
    $COLOR_V3_TURQUOISE_LIGHT,
    url('~vectors/non_pointy_button_turquoise_border.svg'),
    // hover $COLOR_V3_WHITE,
    $COLOR_V3_TURQUOISE,
    url('~vectors/non_pointy_button_turquoise_background.svg'),
    // active $COLOR_V3_TURQUOISE,
    $COLOR_V3_TURQUOISE,
    url('~vectors/non_pointy_button_turquoise_background.svg'),
    // selected $COLOR_V3_TURQUOISE,
    $COLOR_V3_TURQUOISE,
    url('~vectors/non_pointy_button_dark_turquoise_background.svg'),
    // completed $COLOR_V3_TURQUOISE_GRASSY_DARK,
    $COLOR_V3_TURQUOISE_GRASSY_DARK,
    url('~vectors/non_pointy_button_green_background.svg'),
    // correct url('~vectors/non_pointy_button_yellow_background.svg'),
    // incorrect 'right'
);
```

**Comment by codepushr** [comment] 2019-12-22 13:42
I'm experiencing the same issues:
```
$kt-media-breakpoints: (
	// Extra small screen / phone
		xs: 0,
	// Small screen / phone
		sm: 576px,
	// Medium screen / tablet
		md: 768px,
	// Large screen / desktop
		lg: 1024px,
	//1024px,
		// Extra large screen / wide desktop
		xl: 1399px
) !default;
```

**Comment by robert-j-webb** [comment] 2020-02-16 01:47
@jsnajdr I'm trying to fix this right now and I'm starting to think that it's an issue with the css-vales-parser.

I could probably write something ugly that would take care of this case but I don't know if that's the best thing for this situation.

**Comment by jsnajdr** [comment] 2020-02-18 09:48
> I'm trying to fix this right now and I'm starting to think that it's an issue with the css-vales-parser.

@robert-j-webb Yes, that's true. From my experience (I spent part of the 2018 Christmas vacation debugging that 🙂), most of the CSS formatting issues are caused by bugs in the PostCSS parser family. See #4659 for another issue that got fixed by an upstream parser fix.

**Closed** 2020-06-09 15:41 UTC
Labels: area:comments, lang:css/scss/less, type:bug
