### ISSUE TITLE
Prettier is stripping newlines at EOF

### ISSUE THREAD

**Issue by ehaynes99** [prettier/prettier#14357] opened 2023-02-14 05:09 UTC
To be clear, this is NOT and issue asking for the ability to disable the newlines at EOF. I know there are a ton of those, and I agree with the decision to refuse them.

The issue is that prettier IS removing the newline at EOF. This does not occur on the playground, however, it's consistent in editors and the command line. Github's formatting won't let me include a trailing newline in code blocks either, so this is a convoluted 1-liner that demonstrates:

```sh
printf "%q" $(printf "console.log('hello')\n" | npx prettier --parser=typescript)
```
Output:
```sh
console.log\(\"hello\"\)\;
```

* `printf "%q"` escapes special characters in the supplied text
* `$(...)` makes a subshell
* `printf "console.log('hello')\n` emits javascript with a trailing newline
* ` | npx prettier --parser=typescript` pipes it to prettier, which then returns to be formatted by the outer `printf`

To reproduce locally, you could simply create a file like:

**Input:**

```ts
// example.ts
console.log('hello') // newline here (github markdown strips this) ->
```
Then format it:
```sh
npx prettier --write
```

**Output:**

```ts
// example.ts
console.log('hello') // no newline
```

**Expected behavior:**

The newline at the end of the file should be retained.

OS is Arch Linux, all packages up to date, but this has been happening for a few months now.

**Comment by fisker** [comment] 2023-02-23 00:57
Duplicate of #12319

**Closed** 2023-02-23 00:57 UTC
Labels: type:duplicate
