### ISSUE TITLE
JSON Syntax Error

### ISSUE THREAD

**Issue by epiqueras** [prettier/prettier#2276] opened 2017-06-26 21:01 UTC
./locales/en.json
./locales/en.json: SyntaxError: Unexpected token, expected ; (2:14)
```bash
  1 | {
> 2 |   "abc": 1,
    |        ^
  3 |   "hello": "2",
  4 |   "edf": "3",
```

**Comment by vjeux** [comment] 2017-06-26 22:01
JSON support hasn't yet landed, and this is not a valid JavaScript statement (it's a valid javascript expression). I'm working on the next release, so please wait a bit more :)

**Closed by vjeux** 2017-06-26 22:01 UTC

**Comment by epiqueras** [comment] 2017-06-27 00:00
@vjeux 
Oh, since the Readme listed a json parser I assumed it supported json. Awesome work, looking forward to the next releases!

**Comment by jbmusso** [comment] 2018-04-03 22:29
Although released, I can confirm this error pops up with prettier@1.11.1 configured with the "typescript" parser.
Config file:
```json
```
See also: https://github.com/azz/pretty-quick/issues/23#issuecomment-376331064

**Comment by suchipi** [comment] 2018-04-03 22:41
@jbmusso configuring prettier with `parser` in your prettierrc/package.json will force prettier to use that parser for all files by default, including JSON. That's why it errors. Prettier autodetects files based on extension so in most cases you do not need to set the parser.

**Comment by coleturner** [comment] 2018-06-15 17:54
Experiencing this error in v1.13.x:
It was working however in v1.11.x, both are using the bablyon parser

@vjeux I believe there is a breaking change between these versions

**Comment by lydell** [comment] 2018-06-15 18:07
@coleturner Prettier 1.13 fixed a bug where your `parser` choice in your config file was incorrectly ignored for some files (see #4633). The `babylon` cannot parse many JSON files because they are not valid JS programs. Some people have run into this error because they added `parser: "babylon"` at the top level of their .prettierrc, which is a really bad idea. See #4642 and #4638. Hope this helps.

**Comment by texastoland** [comment] 2018-07-18 04:20
I'm getting this error with no `parser` specified. My override was also ignored.

```yaml
overrides:
  - files: "*.json"
    options:
      parser: json
```

**Comment by j-f1** [comment] 2018-07-18 10:15
@texastoland Can you open a new issue and fill out the [formatting template](https://github.com/prettier/prettier/issues/new?template=formatting.md)?
