### ISSUE TITLE
Template literals have conditional formatting when used as function arguments

### ISSUE THREAD

**Issue by zsakowitz** [prettier/prettier#13056] opened 2022-06-29 21:54 UTC
When used as function arguments and in function calls, template literals conditionally insert a newline before and after themselves depending on whether there is a newline in the source code.

**Prettier 2.7.1**
[Playground link 1](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzKAKABgHSgQwCMw8sBKAbjxABoQIAHGAS2gGdlR8AnbiAdwAKPBBxT4ANv3wBPDnULd8YANZwYAZXwBbOABlmUOMlSS2cBUtXqNDZYYDmyGNwCuFkHG2E4AE19+evhQDq74DnAAYhDc2vgwLCHIIPiuMBC0IAAWMNoSAOpZzPBsdmBwGqLFzABuxTLJYGzyIIbm3DCCSg5xJmYeAFZsAB4ajhJwAIquEPB9EuZ0dtztyYREcBKZDNyGMPnMvjBZyAAcAAxLfOb5SgzJO3DtNcZ0AI4z8F2MYilsALRGPx+TLcOAfZhgrrhXpIUwLDzmbTMZxuRHjKafYxw-p0GBEA5HE5IABMeKUzAkjgAwhBtLDPGwAKyZVzmAAqRDE8MWIBq7gAklAArANGBdkwAILCjQwGQTebmAC+SqAA), [playground link 2](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzKAKAOlABLgAxwEMAjMHAgSgG4cQAaECABxgEtoBnZUYgJ34QA7gAUBCHimIAbYcQCePJqX7EwAazgwAysQC2cADLsocZKllc4KtZu06W60wHNkMfgFcbIOPtJwACaBQUbEUC6exC5wAGIQ-PrEMBwRyCDEnjAQjCAAFjD6MgDqeezwXE5gcDqS5ewAbuUK6WBcyiCm1vwwomouSRZWPgBWXAAeOq4ycACKnhDwQzLWTE783emkZHAyuSz8pjDF7IEwecgAHAAMa0LWxWos6Qdw3Q3mTACOC-B9rFIMlwALRmIJBXL8OA-dhQvrRQZISwrHzWfTsdxeVHTOa-cxI4ZMGBkE5nC5IABMRLU7BkrgAwhB9IjfFwAKy5TzWAAqZCkyNWIAa3gAklAQrAdGBDmwAILinQwBQzZbWAC+aqAA)

```sh
--parser babel
```

**Input 1:**

```jsx
fn(`
abc
`);

```

**Output 1:**

```jsx
fn(`
abc
`);

```

**Input 2:**

```jsx
fn(
  `
abc
`);

```

**Output 2:**

```jsx
fn(
  `
abc
`
);

```

**Expected behavior:**

Prettier should select one style and stick with it. The Prettier website mentions that only cases where newlines are taken into account are in object literals, object type literals, and decorators, yet the compiler produces different results in this case.

I have found that the minimal example requires that the template literal have a single newline with no other characters. If no newlines are present in the source string, Prettier correctly formats the function call as a single line in the result.

**Comment by zsakowitz** [comment] 2022-06-30 20:56
After experimenting, I noticed that this issue does not occur in computed property access, where a newline is inserted before multi line strings whether or not one existed beforehand.

**Comment by alexander-akait** [comment] 2022-07-01 03:53
Duplicate of https://github.com/prettier/prettier/issues/2068, we look at newlines (for function call) in your source code to decide to keep the newline or not for better DX, we can solve it only introduce the `--pure` option

**Closed by alexander-akait** 2022-07-01 03:53 UTC
