### ISSUE TITLE
eslint Replace `⏎@observer·` with `@observer⏎` (prettier/prettier)

### ISSUE THREAD

**Issue by imcodingideas** [prettier/prettier#4399] opened 2018-04-30 04:49 UTC
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMGAGn2HwGEItoECBffAMxwfwHIdTyPADpQM2PNXwQARgGc4OAG4KqqKACs45fG07ce6GQA8AtPzIxhoxhJoAhAK4wY0ACoQIAG2kkcVR87QOhxc6Lzm5CbSHjCyMDgkmFYiYrgEPAB0APQAMqhxGWCysslQkFBx+A4OqAAmigAs+AC8+PwAjjX8ABQ81XVZjTwAlCIiAAJqmuS9AMowDrXMsnlxI-jjMvJKCiJgniTF+POLy6sEcEbwULWydAzYUMzUIvj4kIxPsAAidQCyEAcsG6wxeUDebxgAAt8hl2HAYGAoSclrBZCDXjoxuD8HFcHAWvgngB3fDQ2GYLiYWQZFFnfIwDFQTHwxHIhao2IgsEQskwml4-hwhFIuloplvFjYt78G4KbnATFvcqVGhxU5o4KtckClz8aUQ-gLHDg7pKiEAHhgJGkngJ+0OsgAciR0HBmkIQOrOXdrba4J6AHzm3lWqGkWrBnG80PxKMxhP4MOBl1ui1ZaHxxOxqGBgCq2ygrrg6czIcTyYAougSKhPKXc+WE8mnRB4LIG1ns29k98SABPO4ASSL5FQyk7TZjLbgpNmDmk6HyslQ0A7Gcb0e7yYAgmO15Ot82Mzgu9ONxGz7HorV+1eY8BvcsMjXMN0n7AWoH8GajxX4vgADWcD9s0wD9PUDQgiw97ZlakaPhyzAZEWbosKWkZTs2MAIR+MAZA4hbFuhGaYX+cE4YGiEavhcA1nWJGUVh06UdRnIoW2cCyIxZHdixuFIbAGS1AOsgjhY45wDxsH-gJNEobO86Lsuq4VPQQIwNJzGxrxfHTgELhQO4Xg+Ke2kVgZ0CBpWtSoDA6aWVAMl8Rajn4HI8z9naHogCJUAAOa7CA+B1GBeEZAA+nUMHmdm3xwHa8CxeejnORWWSOcZ3i+GloakblSYnmlwzDFK5GFTAN53uWpY2naZ6jDiZVlSIlziAQSzsCQDieAQYqxOcIggBQIAQJgMCqbIyCgL4XDEgACr4CBTSgJCKBAdTDSA0gJGAwEwLMmBkGo-nIPEDhwCNajbDA80JP5NbIF1njyCN6iyEYdi7ftszFnkTxPSQL2XSAR04NsyDbTaXnQFtlJqDAADqdTQsgAAcAAMI2UhA8iIwkmCQ5SXEKMoW0dF0cB3SQD0kIDwMjfIS5nTgF2MyddoAIoOJxLNsyAfrI7UqNIAATCN8S1p4J30Ogj0oFATBbYRcCuDaK3PfILAsEAA)
```sh
--single-quote
```

**Input:**
```jsx
import React, { Component } from 'react'
import { observer, inject } from 'mobx-react'
import { ButtonToolbar, Button } from 'react-bootstrap'

import './List.css'

const uuidv4 = require('uuid/v4')

@inject('StudentsList') @observer
class StudentsList extends Component {
  componentDidMount() {
    this.fetchStudents()
  }

  store = new this.props.StudentsList()

  fetchStudents() {
    this.store.fetchStudents()
  }

  render() {
    const { students } = this.store

    return (
      <table className="students table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Notes</th>
            <th>Days Inactive</th>
            <th>New Submissions</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {students.map(student => (
            <tr key={uuidv4()}>
              <td>{student.name}</td>
              <td>{student.username}</td>
              <td>{student.email}</td>
              <td>{student.notes}</td>
              <td>{student.daysInactive}</td>
              <td>{student.newSubmissionsCount}</td>
              <td>
                <ButtonToolbar>
                  <Button>Edit</Button>
                  <Button bsStyle="danger" id={student._id}>
                    Delete
                  </Button>
                </ButtonToolbar>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    )
  }
}

export default StudentsList

```

**Output:**
```jsx
import React, { Component } from 'react';
import { observer, inject } from 'mobx-react';
import { ButtonToolbar, Button } from 'react-bootstrap';

import './List.css';

const uuidv4 = require('uuid/v4');

@inject('StudentsList')
@observer
class StudentsList extends Component {
  componentDidMount() {
    this.fetchStudents();
  }

  store = new this.props.StudentsList();

  fetchStudents() {
    this.store.fetchStudents();
  }

  render() {
    const { students } = this.store;

    return (
      <table className="students table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Notes</th>
            <th>Days Inactive</th>
            <th>New Submissions</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {students.map(student => (
            <tr key={uuidv4()}>
              <td>{student.name}</td>
              <td>{student.username}</td>
              <td>{student.email}</td>
              <td>{student.notes}</td>
              <td>{student.daysInactive}</td>
              <td>{student.newSubmissionsCount}</td>
              <td>
                <ButtonToolbar>
                  <Button>Edit</Button>
                  <Button bsStyle="danger" id={student._id}>
                    Delete
                  </Button>
                </ButtonToolbar>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    );
  }
}

export default StudentsList;

```

**Expected behavior:**
I do not want @observer decorators to goto a new line. This should be on one line:

`@inject('StudentsList') @observer`

**Comment by lydell** [comment] 2018-04-30 09:48
Hi! I searched the issue tracker for “decorator” and found this: #1974. Let’s keep the discussion over there.

**Comment by lydell** [comment] 2018-04-30 09:48
Duplicate of #1974

**Closed by lydell** 2018-04-30 09:48 UTC
