### ISSUE TITLE
Bug? Prettier breaks SVG close tag

### ISSUE THREAD

**Issue by wizardnet972** [prettier/prettier#5541] opened 2018-11-24 10:06 UTC
**Prettier 1.15.2**

Bug? Prettier breaks SVG close tag.
 
**Input:**
$ prettier index.html

**Output:**
![image](https://user-images.githubusercontent.com/4997825/48966870-2e674500-efe1-11e8-9b3e-67d3f2f846c1.png)

**Expected behavior:**
SVG should have a close tag in the same line...

**HTML**
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
<header>
    <a href="#servicesSection" title="Services Section" class="anchor-link js-anchor-link"
    >Scroll
    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12">
      <g transform="translate(-230 -602)"><path d="M236 602l-1.06 1.06 4.19 4.19H230v1.5h9.13l-4.19 4.2L236 614l6-6z"></path></g></svg
  ></a>
</header>

</body>
</html>
```

**Comment by ikatyang** [comment] 2018-11-24 11:00
It's not a "bug" (i.e., it won't break the output) but we should improve it. Let's track it in #5322 since _SVG file_ and _SVG in HTML_ use the same whitespace rule.

**Comment by ikatyang** [comment] 2018-11-24 11:00
Duplicate of #5322

**Closed by ikatyang** 2018-11-24 11:00 UTC

**Comment by marcelcremer** [comment] 2019-01-22 14:25
@ikatyang I just encountered the same problem. I understand your feeling that it's not a bug, because the output HTML is still parseable. 

However, the syntax highlighting of various IDEs will break (e.g. VS Code in my case) if the SVG is not closed "correctly".
Same line:

![image](https://user-images.githubusercontent.com/6123724/51541608-87285200-1e59-11e9-9ecf-8a7617ec8038.png)

After prettier format:

![image](https://user-images.githubusercontent.com/6123724/51541643-9effd600-1e59-11e9-8df5-e659a5692389.png)

I'd love if this could be changed (fixed), before the SVG-Support is implemented (which might take a bit longer).

**Comment by lydell** [comment] 2019-01-22 15:31
@marcelcremer You should report that to VSCode as well, I think.
