### ISSUE TITLE
Empty Tag not converting to self-closing on format

### ISSUE THREAD

**Issue by SohilK03** [prettier/prettier#8714] opened 2020-07-06 06:46 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet
<Navbar></Navbar>
```

**Output:**
```jsx
// code snippet
<Navbar></Navbar>
```

**Expected behavior:**
```jsx
// code snippet
<Navbar/>
```

**Comment by thorn0** [comment] 2020-07-06 07:54
Duplicate of #6452

**Closed by thorn0** 2020-07-06 07:54 UTC
