### ISSUE TITLE
defect html tags for svg (+path)

### ISSUE THREAD

**Issue by Dexus** [prettier/prettier#12987] opened 2022-06-09 15:13 UTC
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOiAO4C0AZgK4EG4EDmS9AbAPQBGAEy4AHgW50ALIJEBbAEbTqAPkpRUAB3zEyVEAwJxRuTPDkk6YBPABOq9ahLYOO0hWr0puABbTccrZ0IvCiMHQctnAIdDwADHHUuLYQRvqYchxJonIEUB4gPjAwmkh8fDSVAHQ0AMxVELYcfEIJcXzOWSC42JhwNAoQovpxuKMArMK4k0IOGppEMD64DJis+mBMtlGwAMKpjUno+gCy43HeQuM8YKMCtTxVAJw8AOx0Ap9VcbW1uEJSAAcwSB-yBAGVAbhak8hM83rgoVceLhPk9vr9Ef9roiSACoZ8BBi-viwYCAF4nIRCV5VWoCby1QG0+lSAgCQFSD6csCPfGxKqkvlAj6PWqvJ5jYJwng0gjSqqy97UxU0sAC-nCp6iukSjVSbUq2VQuIAGSEAhRtTigKqn0B8tecW+421TpdT3VwuB3p14u1vqNQhN8qDr3+MrV+qhvu9qLFErGEdVr3ZF1RF15goNuC18d1krzQdtCQE5NUqD4CyWag0HRcKn2ck00BsJEcVdrlaw2C7Pbcek8jBYbE4kn4U3EkhkU0UyhAXe0hHc+kMxlM5ks1lgcHsC8cnQHBS8vn8gWCuFC4Ui0SgsQSSRSaWoGS6Yly+X0RRKZQq1TqDRNC0bT1m+vT9IMwzUKMExTDMcxaIsyyrOs1CbNsNj7AQhzdMc1BnOmyK3KiDzwu8hLEmSIJIhCUIwnCLzhkiOJopRzEooCeKghRPwkqC+KUtSLIMtCzJ0gy7KctyUhZpq2YxvJfqJnECpKqGkbKhpXqKVqSkBtmhqRia5qWtCNp2hyjrOnErp0O6NmetGTmWgWTnFmM6kpsmSraUKOnyfm-pJmGabeAImZ5nmLlBUWRnfHEZYVlWSFdqBKgAKqaOgixwO2daaKlPYqCAAA0IAQJoMCYNAJDIKARDbBANAAAoNQgtUoEQBA0EQACetVlQothEGAADWcAwOCRByHApqYFAcDIAwXUkHAg3DWNE3ggsYDzRwyAwLYTBrSAcCKHA6DoBdppEFAHBMEQHBwAAYo0ciLFVd3ICARBMDAEClYUMC5AA6j4Zi5TtcDgu1Zg4GYvXfSQh2YGAMCA-Nq22DAzXDRw71LStJ0AFYkKI4J7UYACKTAQPAhMEKtZULLYWPfUUuSA5otjzTAIOYOgSzIICcTMykq0g8NmjfdzuW7tgi1lQAjrT8C4xVHU-ZYC0XRdgNRCrmBRLjj0E0gy2Mydq1yJgDNMyAJCU3ANN04tSCHcdZUwEQCj84LPjIEIXvDWse1Nmbp0kOMgNMKtAAqPsdRb9vYMdACSUBXbA4JgDzlUAIKZ+CMC9UYdtwAAvhXQA)

```sh
--parser html
--no-semi
--single-quote
--html-whitespace-sensitivity strict
```

**Input:**

```html
<div class="w-full lg:w-6/12 xl:w-4/12 mb-4">
<p class="flex items-center">
<svg class="w-4 h-4 mr-2 text-green-600" role="img" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512">
<path fill="currentColor" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path>
</svg>Components
</p>
</div>
<div class="w-full lg:w-6/12 xl:w-4/12 mb-4">
<p class="flex items-center">
<svg class="w-4 h-4 mr-2 text-green-600" role="img" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512">
<path fill="currentColor" d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"></path>
</svg>Updates
</p>
</div>
```

**Output:**

```html
<div class="w-full lg:w-6/12 xl:w-4/12 mb-4">
  <p class="flex items-center">
    <svg
      class="w-4 h-4 mr-2 text-green-600"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewbox="0 0 512 512"
    >
      <path
        fill="currentColor"
        d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"
      ></path></svg
    >Components
  </p>
</div>
<div class="w-full lg:w-6/12 xl:w-4/12 mb-4">
  <p class="flex items-center">
    <svg
      class="w-4 h-4 mr-2 text-green-600"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewbox="0 0 512 512"
    >
      <path
        fill="currentColor"
        d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"
      ></path></svg
    >Updates
  </p>
</div>

```

**Expected behavior:**

```html
<div class="w-full lg:w-6/12 xl:w-4/12 mb-4">
  <p class="flex items-center">
    <svg
      class="w-4 h-4 mr-2 text-green-600"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewbox="0 0 512 512"
    >
      <path
        fill="currentColor"
        d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"
      ></path>
    </svg>Components
  </p>
</div>
<div class="w-full lg:w-6/12 xl:w-4/12 mb-4">
  <p class="flex items-center">
    <svg
      class="w-4 h-4 mr-2 text-green-600"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewbox="0 0 512 512"
    >
      <path
        fill="currentColor"
        d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z"
      ></path>
    </svg>Updates
  </p>
</div>

```

In my view there is something broken for html tags.

**Comment by Dexus** [comment] 2022-06-14 09:09
@alexander-akait 

this is SVG close tag

```html
 ></path></svg
    >Updates
  </p>
```

No nothing very exotic html/css, but our build system is something big and static...

**Comment by vezzoo** [comment] 2022-07-22 09:01
Hi, I'm having the same issue. Are there any updates?

If you want to know more about my case, just take a look at this [issue](https://github.com/prettier/prettier-vscode/issues/2620) that has been opened to prettier-vscode.

**Comment by fisker** [comment] 2022-07-22 10:38
I say we should implement svg support(or adopt a plugin).
For svg inside html, we can call that parser to format.

**Comment by vezzoo** [comment] 2022-07-22 12:57
That's ok in that case, but I think the problem is extended on every html tag, not only the svg one.
I've seen this problem for a long time before opening an issue, sometimes on divs, sometimes on spans and sometimes on angular things such as ng-container, ng-content or components selectors.

One solution might be that closing tags cannot be split across multiple lines like opening tags?

**Comment by thorn0** [comment] 2022-08-21 22:28
This isn't SVG-specific. I'd say this is a duplicate of https://github.com/prettier/prettier/issues/8302, see also https://github.com/prettier/prettier/issues/7153

Here's a demo of the same behavior with the `button` tags instead of `svg`:

**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UqARgK4wzQFFZ4DCANpmANYAEAtnAISoD0taiVyNmLfsVycehCeUpRcAVQAO6AIbwS8qrMGjW03gJxDJB8X0lHZVnYtUb4twSAA0ICCpiZoAZ2RQdQAnYIgAdwAFEIQAlHUGcPUATwCPYmD1VjgYAGV1LgAZTCg4ZAAzBL84dMzsvJUskoBzZBhg0hqQOA5iOHR0fsL1KGbSdWa4ADEIYI5NH1HkEHVyCHcQAAsYDgYAdU3MeD9GsDhc2KOcI+TlsD80kBLq4JhIzOb5iqqugCs-AAeuRaDDgAEVSBB4N8GNUPI1gi9lttdhsVMESjA9ph0DBNsgABwABnhYWqe0yKmW6LgL2wZQ8AEdIfB3l44is-ABaUr9fobYJwZmYQXvCZfJCVWFdaocTBtDoykHglllSU-DwwdTEbG4-FIABMmsymCYozoEA4Eu6fgArBtSNUACrauJSuEgbCdACSUEGsFyYAx3gAgn7cjBkqCYdUAL6xoA)

```sh
--parser html
```

**Input:**

```html
<div>
<button>
<div>Click me!</div>
<b>Click</b> me!
</button>Update<button>
<div>Click me!</div>
<b>Click</b> me!
</button>Update
</div>
```

**Output:**

```html
<div>
  <button>
    <div>Click me!</div>
    <b>Click</b> me!</button
  >Update<button>
    <div>Click me!</div>
    <b>Click</b> me!</button
  >Update
</div>

```

**Comment by thorn0** [comment] 2022-08-21 22:33
Closing in favor of #8302

**Closed by thorn0** 2022-08-21 22:33 UTC
Labels: status:awaiting response, lang:html
