### ISSUE TITLE
Strange linebreak with long arguments and callbacks

### ISSUE THREAD

**Issue by wavebeem** [prettier/prettier#2239] opened 2017-06-23 17:23 UTC
When a function call has a callback but also has many and/or long arguments, for specific lengths the callback formatting is quite strange.

Input:

```js
someFunctionCallWithBigArgumentsAndACallback(thisArgumentIsQuiteLong, function(cool) {
  return cool
})
```

Actual Output (strange line break in `function`):
```js
someFunctionCallWithBigArgumentsAndACallback(thisArgumentIsQuiteLong, function(
  cool
) {
  return cool;
});
```

Expected Output:

```js
someFunctionCallWithBigArgumentsAndACallback(
  thisArgumentIsQuiteLong,
  function(cool) {
    return cool;
  }
);
```

Note that if `thisArgumentIsQuiteLong` is a little bit longer, or you add more parameters, the expected output formatting happens. It's only for specific lengths that this strange formatting appears.

**Comment by azz** [comment] 2017-06-24 02:50
This oddity is not specific to function arguments, by the way:

Input:
```js
someFunctionCallWithBigArgumentsAndACallback(thisArgumentReallyIsQuiteLong, [ 1, 2, 3, 4, 5 ]);
```
Output:
```js
someFunctionCallWithBigArgumentsAndACallback(thisArgumentReallyIsQuiteLong, [
  1,
  2,
  3,
  4,
  5
]);
```
Expected:
```js
someFunctionCallWithBigArgumentsAndACallback(
  thisArgumentReallyIsQuiteLong,
  [1, 2, 3, 4, 5]
);
```

But I'm not sure how this case should be handled:

Input:
```js
someFunctionCallWithBigArgumentsAndACallback(thisArgumentReallyIsQuiteLong, { foo: 1, bar: 2 });
```

Output:
```js
someFunctionCallWithBigArgumentsAndACallback(thisArgumentReallyIsQuiteLong, {
  foo: 1,
  bar: 2
});
```

_Potentially_ Expected:
```js
someFunctionCallWithBigArgumentsAndACallback(
  thisArgumentReallyIsQuiteLong,
  { foo: 1, bar: 2 }
);
```

**Comment by wavebeem** [comment] 2017-06-24 03:43
Hmm, I can see why those cases could happen, for long arrays and large objects. But breaking inside a function argument list probably shouldn't happen unless the total length of the argument list is too long to fit within the line length limit (roughly speaking).

I hope I'm explaining this clearly, this is kind of tricky, hahah.

**Comment by azz** [comment] 2017-10-04 10:26
I have no idea when, but this is now fixed!

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22someFunctionCallWithBigArgumentsAndACallback(thisArgumentIsQuiteLong%2C%20function(cool)%20%7B%5Cn%20%20return%20cool%5Cn%7D)%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A70%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Atrue%7D%7D)
```sh
--print-width 70
--use-tabs
```

**Input:**
```jsx
someFunctionCallWithBigArgumentsAndACallback(thisArgumentIsQuiteLong, function(cool) {
  return cool
})
```

**Output:**
```jsx
someFunctionCallWithBigArgumentsAndACallback(
	thisArgumentIsQuiteLong,
	function(cool) {
		return cool;
	}
);

```

and

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22someFunctionCallWithBigArgumentsAndACallback(thisArgumentReallyIsQuiteLong%2C%20%5B%201%2C%202%2C%203%2C%204%2C%205%20%5D)%3B%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A70%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Atrue%7D%7D)
```sh
--print-width 70
--use-tabs
```

**Input:**
```jsx
someFunctionCallWithBigArgumentsAndACallback(thisArgumentReallyIsQuiteLong, [ 1, 2, 3, 4, 5 ]);

```

**Output:**
```jsx
someFunctionCallWithBigArgumentsAndACallback(
	thisArgumentReallyIsQuiteLong,
	[1, 2, 3, 4, 5]
);

```

**Comment by wavebeem** [comment] 2017-10-04 14:14
Thanks!

**Comment by suchipi** [comment] 2017-10-08 10:23
Do we have snapshots for these cases? If not, we should add them, so that we don't introduce an unintentional regression later (considering the cause of the fix is unknown)

**Comment by azz** [comment] 2017-10-08 12:01
Arg, I went to add snapshots and found out this isn't fixed, apparently I was re-testing with print width 72, which does not exhibit this issue, re-opening.

**Comment by thorn0** [comment] 2021-02-09 22:09
Fixed by https://github.com/prettier/prettier/pull/9662
Let's add a test from this issue and close it.

**Closed** 2021-02-09 23:06 UTC
Labels: area:function calls, lang:javascript, type:bug, type:tests
