### ISSUE TITLE
Prettier should not remove line preceding line starting with semicolon

### ISSUE THREAD

**Issue by calebeby** [prettier/prettier#4841] opened 2018-07-14 01:45 UTC
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOEA2cB0mIDmAFAOQAWcm+ABDBQE5wkCUAOlOwNwDaAhgDTUARoLABdEPxAQADjACW6ZKF716EAO4AFVQjTIQvAG4R5AE0kgh9XmADWcGAGUZt+VALIY9AK5wp7mhw9DBaNgQAtrzIAGa8mEFSAFZoAB4AQjb2jk68EXAAMu5wsfGJIK70QfQGQrxCAJ74UJYy9O4wAOrmdMgAHAAMUm0QQZ02MgZtcNVGJVKMAI4+8oxhvJHRSHEJ-iBBEfKlu1Jo7gTYAIo+EPDH5TD13Wa9SABMUt688pjnAMIQCJRAxQaDzEA+IIAFXq+m2ZTgAF9EUA)
```sh
# Options (if any):
--no-semi
```

**Input:**
```jsx
console.log('hello there')

;[a, b, c]
```

**Output:**
```jsx
console.log("hello there")
;[a, b, c]
```

**Expected behavior:**

```jsx
console.log("hello there")

;[a, b, c]
```

**Comment by ikatyang** [comment] 2018-07-14 07:08
Hi, this is a duplicate of #1510, see https://github.com/prettier/prettier/issues/1510#issuecomment-299496344 for more info.

**Comment by ikatyang** [comment] 2018-07-14 07:08
Duplicate of #1510

**Closed by ikatyang** 2018-07-14 07:08 UTC
