### ISSUE TITLE
Rehashed: Spaces inside JSX curly braces are removed

### ISSUE THREAD

**Issue by Hummel-Mors** [prettier/prettier#7067] opened 2019-11-28 10:10 UTC
Copied from issue # 95

I would like to start the discussion again. It would be great, if the spaces were not removed.

I use to write my JSX like this

```javascript
<div className={ className }>
  Bla bla bla
</div>
```

Note the spaces inside the className curly braces.

But it's formatted like this

```javascript
<div className={className}>
  Bla bla bla
</div>
```

**Comment by lydell** [comment] 2019-11-28 10:16
Duplicate of #2651

**Closed by lydell** 2019-11-28 10:16 UTC
