### ISSUE TITLE
Line exceeds max width when calling function with string argument followed by function argument

### ISSUE THREAD

**Issue by keithkml** [prettier/prettier#1473] opened 2017-05-01 19:40 UTC
Demo link below. Using Prettier 1.2.2

```js
////////10////////20////////30////////40////////50////////60////////70////////80
test('really long string never ends wow its really long', function checkHoursValidity(assert) {
////////10////////20////////30////////40////////50////////60////////70////////80
  assert.end()
////////10////////20////////30////////40////////50////////60////////70////////80
});
```

Prettier produces the following (column number comment added for illustration purposes):

```js
////////10////////20////////30////////40////////50////////60////////70////////80
test("really long string never ends wow its really long", function checkHoursValidity(
////////10////////20////////30////////40////////50////////60////////70////////80
  assert
////////10////////20////////30////////40////////50////////60////////70////////80
) {
////////10////////20////////30////////40////////50////////60////////70////////80
  assert.end();
////////10////////20////////30////////40////////50////////60////////70////////80
});
```

[Demo link](https://prettier.github.io/prettier/#%7B%22content%22%3A%22test('really%20long%20string%20never%20ends%20wow%20its%20really%20long'%2C%20function%20checkHoursValidity(assert)%20%7B%5Cn%20%20assert.end()%5Cn%7D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by vjeux** [comment] 2017-05-22 01:24
Sorry this went through the cracks, I didn't properly triage it. This is actually intended, we special case "it" and "test" calls as many people ignore the 80 column limits for this case in their tests.

**Comment by keithkml** [comment] 2017-05-22 14:27
Thanks for the explanation. Wouldn't it be better to just special case the first argument? I find the formatting of the function parameters in my example to be very ugly. Would be better if the function were on a new line IMO.

**Comment by vjeux** [comment] 2017-05-22 14:57
Oh, I'm sorry, I didn't realize that the first argument was split, which indeed looks terrible. Need to be fixed somehow.

**Comment by keithkml** [comment] 2017-05-22 16:19
Thanks for reconsidering! I updated the issue details to clarify :)

**Comment by lydell** [comment] 2017-09-27 19:33
#2877 was reverted since it caused other issues, so re-opening.

**Comment by duailibe** [comment] 2017-12-10 02:48
I'm not sure when it happened, but this is now fixed: [playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8DOMAUByATnAQwBsiBPAAiOgHNyNcBLKWqOANzl3IQBM1yA7hAHkGMfvmJlKNbABpyAMwCuUMDAbRyYABZwwAawASEZbjQA1Ygx5jSmAmjScYASnLAAOlHLlHz3BgAOl5MV28AX1cAbm8QORAIAAcNaDRkUCTGWAB1GxgdZAAOAAYEmAIAIzyeAuQAJgS0JmoiOABFZQh4ZEViZ3LcAgYiFoBhCABbSYJkEChoOHiQSqHDOBgAZSSCMBbkGFxlOASAKzQADwAhNYMNzYJJuAAZJiWkPqIBkB3zTjnFFQBMtnJMGAcjicQMpnAAVKrpD79KFMAIwAAKQ2oM16yIS+AAjsoGPhMQRsbMkV8oVkIM4ckMknNlgRcLhhOjWQhESBljwIGBcdSEo4YELvqYYEllDB6uK4BEIkA)

I'll add a regression test

**Closed by duailibe** 2017-12-10 02:48 UTC
Labels: lang:javascript, type:bug
