### ISSUE TITLE
[TypeScript] Error raised when "//" is included as text in JSX Code.

### ISSUE THREAD

**Issue by clentfort** [prettier/prettier#3346] opened 2017-11-29 10:57 UTC
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAE8NMwJTgEMwYA6AZQDEBhAHmAF8A+TAXkwAoBKd1zgDpRMmOmgAORKMwD0MujIlTmQ7iAA0ICOJgBLdMlBEMyAGZEANmjiaARgCcSAazgwKksLqgBzZDHsArjYgACYQYGaW1ppe1vYwAAqO3gC2RJFWwQBWaAAeAEKOYC5uRClwADJecBnRWgEw4g0ATH6BwZL2ccggMACe4nBoYPa6Ohog4qOwAOq6ITAAFsgAHAAMmlMQ1jOO4m1BmvZwAI4BusdJRKnpSOaZmtYpugfBaF7eFnAAigEQ8LVgjAiLY5gtlkhmpp-ERdBYPjQICk0j0oNAapoAtYACogtCAxiMIA)
```sh
--parser typescript
```

**Input:**
```tsx
const test: React.SFC<{}> = () => (
  <span>//</span>
)
```

**Output:**
```tsx
Error: Comment location overlaps with node location
```

**Second Output:**
```tsx
SyntaxError: ';' expected. (1:16)
> 1 | Error: Comment location overlaps with node location
    |                ^
```

**Expected behavior:**

No error should be raised.

**Comment by azz** [comment] 2017-11-29 11:03
Hi, thanks for reporting this. This is a known issue (duplicate of #2347), with the root cause tracked in https://github.com/eslint/typescript-eslint-parser/issues/339

**Closed by azz** 2017-11-29 11:03 UTC
