### ISSUE TITLE
return chain with comments cause important issus with promise

### ISSUE THREAD

**Issue by menems** [prettier/prettier#4271] opened 2018-04-06 10:41 UTC
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEMERAFAJT7AA6U+d+ATnDOg7VHAO74AKDEAWxwBnOORr16AOhgALBCXL4AvAD5e-IaKlNhEADYA3MWTITJ+APSX8ABwjpm5yTPlRFFNRsEi4OuHpGJma0+AC+IAA0IBC2uNDCyKAAhgz8nDypCIkoyYYQOAAmUSDJwjDIqMn6otEARgzJYADWzADKtk04UADmyDAMjtGFEGCV1bUg3aIMMHzJPQLJ4zVw0QBWwgAeAEKNLe3JAnAAMt1wK5MOMLboMABMl2sgnQwzyCB1yXUAnvrQJVsDG6MAA6kU5MgABwABmiQIgolBjVsHyBATgDGMJUavTgAFEoMUkHCQLienA2jBUhUSdEmABHdA4JjzRbLJBVVbRURCfqDZ7Cbo9fRwACK6GIF05E2e1Lq4MKkKQ92iA2SOH0woAwoIlh8oNALtF0KIACrfHJc0RhMJAA)
```sh
--range-end 
--range-start 
```

**Input:**
```jsx
function toto() {
    return new Promise()
      .then(() => Promise.resolve())
      // pouet
      .then(() => Promise.resolve())
  }
```

**Output:**
```jsx
function toto() {
  return (
    new Promise()
      .then(() => Promise.resolve())
      // pouet
      .then(() => Promise.resolve())
  );
}
```

**Expected behavior:**
```jsx
function toto() {
  return new Promise()
      .then(() => Promise.resolve())
      // pouet
      .then(() => Promise.resolve())
  
}
```
That's  i think a big issu if you want chain promise that in this situation is resolve with an object () before the real promise as done .

**Comment by lydell** [comment] 2018-04-06 12:33
Hi! Thanks for the issue. This is a duplicate of #968

**Comment by lydell** [comment] 2018-04-06 12:33
Duplicate of #968

**Closed by lydell** 2018-04-06 12:33 UTC

**Comment by hawkrives** [comment] 2018-04-06 13:01
Also, @menems: surrounding a return value with parenthesis doesn't change the return value at all, as parenthesis only affect the operator precedence (plus, minus, await, etc). There's no intermediate object to be worried about.

**Comment by menems** [comment] 2018-04-06 15:05
yes you right @hawkrives  thanks
