### ISSUE TITLE
Prettier tries to format html files when run as Webstorm file watcher

### ISSUE THREAD

**Issue by avalanche1** [prettier/prettier#4405] opened 2018-05-01 05:11 UTC
Prettier tries to format html files when run as Webstorm file watcher.
It thinks somehow my html is jsx.
And thus throws errors:

```
/usr/local/bin/prettier --write client/main.html

[error] client/main.html: SyntaxError: Expected corresponding JSX closing tag for <meta> (4:1)
[error]   2 |   <title>Mia Republika</title>
[error]   3 |   <meta name="viewport" content="width=device-width">
[error] > 4 | </head>
[error]     | ^
[error]   5 | 
[error]   6 | <body>
[error]   7 |   <main></main>

Process finished with exit code 2
```

I've installed Prettier as per https://prettier.io/docs/en/webstorm.html

**Comment by lydell** [comment] 2018-05-01 10:05
Hi! This is a really confusing issue that keeps coming up. Prettier does not support HTML (yet, #1882) and unfortunately defaults to handling everything it doesn't know what it is as JavaScript (which is why it thinks your HTML is JSX). We want to get rid of this default: #2884

Duplicate of #2884

**Comment by lydell** [comment] 2018-05-01 10:06
Duplicate of #2884

**Closed by lydell** 2018-05-01 10:05 UTC

**Comment by avalanche1** [comment] 2018-05-06 00:32
Not really. Because I need it for css as well as js. And there is no way to select multiple file types - at least I couldnt see it.

**Comment by dasa** [comment] 2018-05-07 15:59
> And there is no way to select multiple file types

I created a separate watcher for each file type as a workaround.
