### ISSUE TITLE
Tagged template strings shouldn't be on a new line

### ISSUE THREAD

**Issue by alexlafroscia** [prettier/prettier#1014] opened 2017-03-15 23:41 UTC
I'm an `ember` user, which uses tagged template strings for component testing.  Normally, you'd write something that looks like:

```javascript
this.render(hbs`
  <p>Some stuff here</p>
  {{some-handlebars-stuff}}
`);
```

For some reason, Prettier instead turns this into:

```javascript
this.render(
  hbs`
  <p>Some stuff here</p>
  {{some-handlebars-stuff}}
`
);
```

It doesn't seem like this should be necessary based on line length... is there something I'm missing? Or is this an error on Prettier's end?

**Comment by vjeux** [comment] 2017-03-19 22:36
Oops, sorry I didn't see this issue earlier. There are many other issues related to template literals but it's not clear what the right solution is. Some pointers:

Related discussion: https://github.com/prettier/prettier/issues/786
Related PR: https://github.com/prettier/prettier/pull/873

**Comment by alexlafroscia** [comment] 2017-03-20 19:43
No problem! Thanks for replying. I'm fine if you want to close this issue/combine it with #786, since they both fall under "template literals do some funky stuff".

**Comment by ryanflorence** [comment] 2017-03-25 06:31
I'm getting some fun stuff too:

```jsx
<Dropdown.Item selectable={false}>
  {m`
    No results for {value}
    ${{ value: <em>{value}</em>}}
  `}
</Dropdown.Item>
```

turns into

```jsx
<Dropdown.Item selectable={false}>
  {
    m`
    No results for {value}
    ${{ value: <em>{value}</em> }}
  `
  }
</Dropdown.Item>;
```

**Comment by bakkot** [comment] 2017-03-25 09:29
It might be worth special-casing tagged template literals where the first line of the template literal is the empty string. It seems a pretty common pattern.

**Comment by jlongster** [comment] 2017-03-27 21:46
Template strings are really hard with something like prettier. However, currently we attempt to integrate each line in a template string into the printer in a "correct" way, so that it properly measures each line, etc. This may have been a bad choice. We can just unconditionally maintain the original formatting with this change:

```patch
diff --git a/src/printer.js b/src/printer.js
index 2c7fb15..35485d9 100644
--- a/src/printer.js
+++ b/src/printer.js
@@ -1384,17 +1384,17 @@ function genericPrintNoParens(path, options, print) {
 
       parts.push(";");
 
       return concat(parts);
     case "ClassDeclaration":
     case "ClassExpression":
       return concat(printClass(path, options, print));
     case "TemplateElement":
-      return join(literalline, n.value.raw.split("\n"));
+      return n.value.raw;
     case "TemplateLiteral":
       var expressions = path.map(print, "expressions");
 
       function removeLines(doc) {
         // Force this doc into flat mode by statically converting all
         // lines into spaces (or soft lines into nothing). Hard lines
         // should still output because there's too great of a chance
         // of breaking existing assumptions otherwise.
```

The problem is that there will be some odd behavior. Take this expression:

```js
foo(`
 one lines
 two lines
 three lines
`);
```

Even though the string spans 5 lines, the printer will only see it as one line. In fact it'll only read & measure the first line (which is blank). So it you add a bunch of stuff after the string, like other args, the printer won't measure things correctly (and wrapping will be wrong). Also, the printer doesn't think the expression contains newlines, so it won't force parent expressions to break, which could cause strange formatting. Basically the whole measurement algorithm is off.

But it only happens for any expressions right after the string, and it will be "reset" into a correct state in the next "outer" expression. Even though it will produce errors in wrapping, maybe it actually produces code that's closer to what the user expects.

I'm not sure what else to do. Either we let string templates possibly mess up our formatting, or we try to print it and mess up its formatting.

**Comment by bakkot** [comment] 2017-03-27 22:51
@jlongster
> we attempt to integrate each line in a template string into the printer in a "correct" way, so that it properly measures each line

That actually does sound like the best thing to do. But if that's so, I don't understand where the extra linebreaks come from e.g. [here](https://prettier.github.io/prettier/#%7B%22content%22%3A%22f(%60%5Cn%60)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D).

I'm guessing it's treating the linebreak inside of the literal as if it were a printer-inserted linebreak, which I think it probably shouldn't do: if the only linebreak in a group is *inside* of a template element, that group shouldn't be wrapped.

**Comment by jlongster** [comment] 2017-04-07 15:55
@bakkot Sorry for the delay. The newlines come from the fact that we convert `\n` inside template literals into `literalline`, which is basically a special type of `hardline`. (It's a hard line that does not output indentation.) Because it's a hard line, it forces all parents to break. So embedding a template literal with a newline always forces things around it to break. If you look at your example, it's breaking the function argument list.

**Comment by jlongster** [comment] 2017-04-07 16:42
Sorry for diverging this conversation, but I'm continuing to explore this here: https://github.com/prettier/prettier/issues/1090#issuecomment-292588030

**Comment by giuseppeg** [comment] 2017-04-08 09:34
> or we try to print it and mess up its formatting.

Imho original strings formatting should be kept even if that means that template literals look ugly and not nicely formatted.

**Comment by jlongster** [comment] 2017-04-11 16:40
https://github.com/prettier/prettier/pull/1144 was merged as a quick fix for a specific case but I think I have a more general solution for fixing templates in most cases and if that works we'll revert it. Taking over this issue to track the more general solution.

**Comment by sean-shirazi** [comment] 2017-04-17 03:27
Just wanted to give another example of this behaviour using v1.1.0:
```js
  const res = await graphql(
    `
    query LogIn($credentials: Credentials!) {
      logIn($credentials)
    }
  `,
    { credentials }
  );
```

**Comment by bakkot** [comment] 2017-04-17 03:31
@sean-shirazi, for reference, how would you like that be formatted?

**Comment by sean-shirazi** [comment] 2017-04-17 03:50
@bakkot I'd like ``` ` ` ```'s behaviour to be consistent with `()`, `{}` and `[]`. For example:

```js
  const res = graphql(shortArg)
  const res = graphql({ shortArg })
  const res = graphql(`shortArg`)

  const res = graphql(
    veryveryveryveryveryveryveryveryveryveryveryveryveryveryvery_long_arg,
  );
  const res = graphql({
    veryveryveryveryveryveryveryveryveryveryveryveryveryveryvery_long_arg,
  });
  const res = graphql(`
    veryveryveryveryveryveryveryveryveryveryveryveryveryveryvery_long_arg,
  `);

  const res = graphql(
    { manyargs1 },
    manyargs2,
    manyargs3,
    manyargs4,
  );
  const res = graphql({
    `manyargs1`,
    manyargs2,
    manyargs3,
    manyargs4,
  });

  const res = graphql(
    {
      manyargs1,
      manyargs2,
      manyargs3,
      manyargs4,
    },
    manyargs2,
    manyargs3,
    manyargs4
  );
  const res = graphql(
    `
      manyargs1,
      manyargs2,
      manyargs3,
      manyargs4,
    `,
    manyargs2,
    manyargs3,
    manyargs4
  );
```

What do you think?

**Comment by tomekwi** [comment] 2017-05-09 12:22
@sean-shirazi I like that!

I don’t think it’s possible to get 1:1 the same behaviour, because unlike `()`, `[]` and `{}` the whitespace inside template strings isn’t ignored by the interpreter. But it looks like we can get very close to that behaviour by:

1. treating the opening `` ` `` (with or without tag) just like we treat an opening `(`, `[` and `{`;
2. assuming the user will take care of any indentation _inside_ the template string; and
3. treating anything after the closing `` ` `` just like anything after a closing `)`, `]` and `}`.

This way, depending on the indentation before formatting, you might end up with a result like:

```
  const res = graphql(
    `
  manyargs1,
  manyargs2,
  manyargs3,
  manyargs4,
`,
    manyargs2,
    manyargs3,
    manyargs4
  );
```

which you could then reindent by yourself:

```
  const res = graphql(
    `
      manyargs1,
      manyargs2,
      manyargs3,
      manyargs4,
    `,
    manyargs2,
    manyargs3,
    manyargs4
  );
```

**Comment by vjeux** [comment] 2017-05-21 21:42
Both the first two examples now remain as is

```js
this.render(hbs`
  <p>Some stuff here</p>
  {{some-handlebars-stuff}}
`);

<Dropdown.Item selectable={false}>
  {m`
    No results for {value}
    ${{ value: <em>{value}</em> }}
  `}
</Dropdown.Item>;
```

I'm going to close this issue as it's mostly solved.

**Closed by vjeux** 2017-05-21 21:42 UTC
Labels: Needs discussion
