### ISSUE TITLE
markdown: Ensure headings pad text value with a leading space

### ISSUE THREAD

**Issue by polarathene** [prettier/prettier#10509] opened 2021-03-12 00:57 UTC
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiAEnANliACAdQgCcsATAHSitVT0wEMyBLKAcz3gGcYqbaAIhDhcoAchh5IxYnDCSA7sxgALPFwAODMHBAAaEBA0xm0LslAMZEBQAUrCcygZYFDAJ7mDAI2LaA1nAwAMpaYKxsyDDEAK5wBnAAtt5wZGSpADIM7DEMbHAAYiSJDDAm7MggDDEwEPogKjCJWAQqyiJhcMGOyswAbsrulWBcXiCsXHDEMLZ+bCXIAGYukwYAVlwAHgBCfmCBIQyJcBmsukjLWKsgG5vBEVhwAIoxEPBLK-EgWsSTxJUlYj+Mg2KD1DTEVgwAjMMiqZAADgADAYIRBJgQ-BpKhCRFM+roDABHV7wWZGJxVLgAWigcFSqXqshJzFkszyCwunwMk0SzCisS+XAez1J50u1xgDG8MLhKmQACYDNEGMwsBEAMIQRKckAiACs9RikwAKtKnBKvn04gBJKDpWDBMCQ4wAQXtwRg7keHyucAAvv6gA)

```sh
--parser markdown
```

**Input:**

```markdown
#Hello World

## Heading test

###Doesn't correct with space
```

**Output:**

```markdown
#Hello World

## Heading test

###Doesn't correct with space

```

**Expected behavior:**

Lines starting with `#` heading syntax should ensure the text content following it has a leading space padding the value.

Seems related to https://github.com/prettier/prettier/issues/8550

**Comment by thorn0** [comment] 2021-03-12 01:29
`#Hello World` isn't a heading in Markdown. See https://spec.commonmark.org/

**Comment by thorn0** [comment] 2021-03-12 01:30
Duplicate of #8550

**Closed** 2021-03-12 01:30 UTC
Labels: type:duplicate

**Comment by polarathene** [comment] 2021-03-12 01:36
Ah ok, thanks for better clarifying the reason that #8550 was closed. I thought this was something Prettier would help resolve, but what you meant when closing was that it's not the responsibility of Prettier to fix this type of problem, that'd be a linting tool, and Prettier would just ensure consistent formatting :+1:
