### ISSUE TITLE
Code-breaking semicolon added when formatting range in arrow function with comment

### ISSUE THREAD

**Issue by rotu** [prettier/prettier#12964] opened 2022-06-02 00:24 UTC
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEAzKmC8mAFEQJQEB8mwAOnpgE4YCuDUA3JgPRd0C+pdiAA0ICAAcYAS2gBnZKACGDBhADuABWUJ5KRajWKAnvNEAjBorABrDAGVFAWzgAZKVDjJs+2XHOWbe3ErdwBzZBgGZj8QOEczOAATRKSXRShQ5kVQuAAxCAZHRRhpDOQQRWYYCBEQAAsYR1QAdTqpeFlgsDg7HXapADd2o3KwWVMQd18GGA1LUKKvHxiAK1kADzsw9ABFZgh4JdRfUWCGafKzRQTUWvEGdxhmqUSYOuQADgAGU9VfZss4nK9zg0wGnlEAEd9vA5hJdBVZABaDxJJK1JjQqRMObZRZIbzHGK+RxSCJRYnbOB7A6eAnLUQwa7PV7vJAAJkZlikqDCAGEII58bFZABWWrMXwAFWuukJJxAA2iAEkoClYHYwA9JABBNV2GBGdBHBWWDI9JkzZAARg+ojNOQAomrkABma18PhAA)

```sh
--parser babel
--range-start 18
--range-end 31
```

**Input:**

```jsx
let fn = (() => {
  return; //
});
```

**Output:**

```jsx
let fn = (() => {
  return; //
};);
```

**Expected behavior:**
The semicolon after the arrow function is not added.

Note that this does NOT happen when the arrow function is replaced with a `function` expression, nor if the comment inside the arrow function is removed.

**Comment by zsakowitz** [comment] 2022-06-05 19:26
I wonder if this is related to #12963, because a semicolon was added improperly in that issue as well.

**Comment by rotu** [comment] 2022-06-05 19:43
> I wonder if this is related to #12963, because a semicolon was added improperly in that issue as well.

I don't think so. This happens with the Babel parser and the parse tree looks correct to me, unlike with #12963

**Comment by rotu** [comment] 2022-06-05 20:32
Based on further experimentation, I think this happens WHENEVER formatting a range inside a braced arrow function expression where the range ends with a comment (either `//` or `/*..*/`) but does not start with a comment.

**Comment by jschuur** [comment] 2022-06-12 17:56
> Based on further experimentation, I think this happens WHENEVER formatting a range inside a braced arrow function expression where the range ends with a comment (either `//` or `/*..*/`) but does not start with a comment.

I can confirm this. I had commented out a line at the end of a modified range of lines and had the editor.formatOnSaveMode setting set to 'modifications' and this added a semicolon at the very end of my file (the closing part of an IIEF: `};)();`.

![Uploading CleanShot 2022-06-12 at 18.54.47@2x.png…]()

Once I uncommented the line in question (and removed the semicolon), a new one was not added on save.

My solution, in the meantime, was to just go back to 'file' for editor.formatOnSaveMode. This solves it, since I never end a file with a comment.

**Comment by bubbaspaarx** [comment] 2022-06-24 14:30
We are seeing an issue here too. We have the noSemi option and it's adding a semi-colon before the code and breaking it. 
We are working in react. Not sure if that is relevant but worth mentioning

**Comment by medmin** [comment] 2022-06-26 18:57
any solution ? Otherwise, I have to disable prettier

**Comment by randallmeeker** [comment] 2022-06-29 22:46
same here v2.7.1
input
```
          map((data) => {
            // this can be anything, code or comment, if I remove this, then it works
            return data.sort();
          }),
```

output
```
         map((data) => {
            // this can be anything, code or comment, if I remove this, then it works
            return data.sort();
          });,
```

**Closed** 2022-07-25 09:28 UTC
Labels: type:bug, lang:javascript, area:ranges

**Comment by demetriad** [comment] 2022-10-23 19:44
Annoying, happening to me too on v9.9.0.

**Comment by jeremybradbury** [comment] 2023-01-31 23:04
The semicolon prefix before parens happens randomly for unknown reasons. 

Restarting IDE (vscode) doesn't fix the problem, but sometimes if you make another white-space change you can get it to save without inserting it but then any other changes will bring it right back.

It's really hard to duplicate on other systems, even with the same codebase.

right now i am stuck with an arrow function as a parameter getting this treatment:

```
 functionName(
  ;({ ...args }) => {
   ...
  ```
