### ISSUE TITLE
Empty object param destructuring formatted incorrectly

### ISSUE THREAD

**Issue by vkrbt** [prettier/prettier#6797] opened 2019-11-04 13:43 UTC
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAS1jmwDMBDMOPAJTkpgGEIBbLKBGABWwgwGc8wAL4BuADpRJ6LLjyQo-fHQbM20Tklr0wMAHQAxRgB4Vute048+-AHx4AvHlIBXKLoLRtq1pdgAKES0zJl8NWGsBAEohSXEYbDgYF2woPCgXABtMiShhEAAaED4YT0VkUHJsXgB3LiqEfmQQckya8gBPJqKAI2xKAGskgGUMSiIAc2QKTP44IoALGBZMgHUFgnh+Maphxs2CADdNjuawfm6QIjncHnIJlnJp1rmigCt+NAAhfrAhmGG5BYcAAMkQ4MgEi55iAPmhhpNMnAAIouCDwZ6zGFjbA3ZowDoYOD8MDYAgYGCFEAYMmwVYEAAmMAWyAAjAAGdlFGkQOarfoYZo04kkQ4QooARzR8EiTRQCn4BCUnCpiSlBESdweTyQM1eIDmLAIkOw0KKiqgEyRqPREKQUJhMHIPXpTJZSAALEUEuQCJlJmpHs1WpkqS45gAVZ1yvVwYTCIA)
```json
{
  "arrowParens": "always",
  "bracketSpacing": false,
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": true,
  "jsxSingleQuote": false,
  "printWidth": 100,
  "proseWrap": "preserve",
  "quoteProps": "consistent",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 4,
  "trailingComma": "all",
  "useTabs": false
}
```

**Input:**
```jsx
export interface ReactComponentProps {};

export const ReactComponent: React.FC<ReactComponentProps> = function ReactComponent({}: ReactComponentProps) {
	return null;
}

```

**Output:**
```jsx
export interface ReactComponentProps {}

export const ReactComponent: React.FC<ReactComponentProps> = function ReactComponent({
    ,
}: ReactComponentProps) {
    return null;
};

```

**Expected behavior:**

```jsx
export interface ReactComponentProps {}

export const ReactComponent: React.FC<ReactComponentProps> = function ReactComponent({

}: ReactComponentProps) {
    return null;
};
```

Comma inside empty object is not valid.

**Comment by lydell** [comment] 2019-11-04 16:50
Duplicate of #6435

**Closed by lydell** 2019-11-04 16:50 UTC
