### ISSUE TITLE
Statement with multiple assignments not respecting print width

### ISSUE THREAD

**Issue by nunocastromartins** [prettier/prettier#5762] opened 2019-01-17 13:06 UTC
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnCBbOA1AhgJwEtcAjAGzgEYACAXmvSzyNIoCY6HMcDjy4AzJ0Y8W-ACzDuzPhQCsnKAFcyZANwgANCAgAHGIWipkoAvggB3AAoEExlLgBuEQgBMtIEvlxgA1nBgAZV0fQigAc2QYfCU4bQALGAwyAHV4wnhUELA4QLsMwkcMgE9kcFRjbTDUOHwYK29wjFxkADNcMhrtACtUAA8AIW8-AMDcLAAZMLg2jq6QXr7AsPCKAEUlCHhZzriQEPwa-DKSUmKyaA9dIlgUtxh45AAOAAZta4galO9dMuu4I6OGbafBwACOSkIoIauCaLSQ7V22hqGEIURie1QK3Wm22CLmexgpDurgeyDY2miuEIZBWAGFMM0ylBoMCQEoagAVUj2RE1AC+-KAA)

**Input:**
```jsx
someVariable1 = someVariable2 = someVariable3 = someVariable4 = someVariable5 = null;
```

**Output:**
```jsx
someVariable1 = someVariable2 = someVariable3 = someVariable4 = someVariable5 = null;
```

**Expected behavior:**
```jsx
someVariable1 = someVariable2 = someVariable3 = someVariable4 = someVariable5 =
  null;
```
or (similar to other operators):
```jsx
someVariable1 =
  someVariable2 =
  someVariable3 =
  someVariable4 =
  someVariable5 =
  null;
```

**Comment by nunocastromartins** [comment] 2019-01-17 13:11
Interestingly, the input ([playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnCBbOA1AhgJwEtcAjAGzgEYACAXmvSzyNIoCY6HMcDjy4AzJ0Y8W-ACzDuzPhQCsnGgGpqlANwgANCAgAHGIWipkoAvggB3AAoEExlLgBuEQgBMtIEvlxgA1nBgAZV0fQigAc2QYfABXOG0ACxgMMgB1BMJ4VBCwOEC7TMJHTIBPZHBUY20w1Dh8GCtvcIxcZAAzXDJa7QArVAAPACFvPwDA3CwAGTC4ds7ukD7+wLDwigBFGIh4Oa74kBD8WvxyklISsmgPXSJYVLcYBOQADgAGbRuIWtTvXXKbuDHRyzbT4OAARxihDBjVwzVaSA6e20tQwhCisX2qFWGy2O0R832MFI91cj2QbG00VwhDIqwAwpgWuUoNAQSAYrUACqkexI2oAXwFQA)):
```jsx
someVariable1 = someVariable2 = someVariable3 = someVariable4 = someVariable5 = 1 + 1;
```
outputs correctly:
```jsx
someVariable1 = someVariable2 = someVariable3 = someVariable4 = someVariable5 =
  1 + 1;
```

However, the input ([playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnCBbOA1AhgJwEtcAjAGzgEYACAXmvSzyNIoCY6HMcDjy4AzJ0Y8W-ACzDuzPhQCsUpr1ZwAbJxoBqapQDcIADQgIABxiFoqZKAL4IAdwAKBBFZS4AbhEIATQyBJ8XDAAazgYAGUTYMIoAHNkGHwAVzgjAAsYDDIAdXTCeFRosDgI1wLCDwKAT2RwVCsjWNQ4fBhHILiMXGQAM1wyFqMAK1QADwAhINDwiNwsABlYuD6BoZBRsYjYuIoARWSIeFXBtJBo-Bb8OpJSarJofxMiWBzfGHTkAA4ABiNniAtHJBEx1Z5wK4eFZGfBwACOyUIsI6uC6PSQ-VORhaGEIiRSZ1QO32h2OGLWZxgpDePg+yDYRiSuEIZB2AGFMN06lBoNCQMkWgAVUhuTEtAC+4qAA)):
```jsx
someVariable1 = someVariable2 = someVariable3 = someVariable4 = someVariable5 = someVariable6 = 1 + 1;
```
still incorrectly outputs (does not respect print width):
```jsx
someVariable1 = someVariable2 = someVariable3 = someVariable4 = someVariable5 = someVariable6 =
  1 + 1;
```

**Comment by j-f1** [comment] 2019-01-17 14:32
See #2482.

**Comment by thorn0** [comment] 2019-01-17 22:18
Duplicate of #4340

**Closed** 2019-01-17 23:30 UTC
