### ISSUE TITLE
scss formatter removes comma altering behavior

### ISSUE THREAD

**Issue by yajo** [prettier/prettier#8855] opened 2020-07-28 06:50 UTC
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASCBaGALOBbODAM2hgGckACACmoEEAnASwEMAbAGkrJajIzJxmRAJQcRAbhAcQEAA4wm0MslAsGDCAHcACuoQqU7LSwCeKmQCMGLMAGs4MAMpzbTKAHNkMBgFc4MtgweGwA6thM8GSuYHBOBpFMAG6RpsjgZBYg7oIMMDo2HngsyETsgjIAVmQAHgBCNvaOTiwEADLucKXlASDVNU7uHmxwAIq+EPDdbBUgrgy56WRgmdJzzLChTAAmOMgAHAAMMnKagqE2cumncLlJXTIAjhPwBfKGICz8UHBw239rBhwZ5MIEFFhFEpIMozXqCPBMbx+OFDEbjSZdaE9GQwFiWLa7bDIABMOJsTDYQwAwhA8MV0rcAKxrXyCAAqeMMMNmSX8AEkoP9YE4wMwFHRBU4YKYRtNBABfeVAA)
```sh
--parser scss
```

**Input:**
```scss
$o-theme-fonts: ((Arial, sans-serif),);
```

**Output:**
```scss
$o-theme-fonts: ((Arial, sans-serif));

```

**Expected behavior:**

```scss
$o-theme-fonts: ((Arial, sans-serif),);
```

Removing the comma flattens the list, and that's not desired.

**Comment by evilebottnawi** [comment] 2020-07-28 11:49
It is expected, we don't keep `,` in one line declarations

**Comment by Yajo** [comment] 2020-08-01 14:52
But that's altering the code behavior! It was a list in a list, but after prettier it's just a list.

**Comment by evilebottnawi** [comment] 2020-08-01 15:20
@Yajo Can you provide example?

**Comment by Yajo** [comment] 2020-08-01 16:43
Yes, of course. Left SCSS, right CSS, live compiled at https://www.sassmeister.com/:

![Peek 01-08-2020 17-42](https://user-images.githubusercontent.com/973709/89106048-7da08280-d41e-11ea-8365-cc4175aa7fce.gif)

**Comment by evilebottnawi** [comment] 2020-08-03 11:35
Thanks! Feel free to send a PR with fix

**Comment by nex3** [comment] 2022-11-08 00:46
Duplicate of https://github.com/prettier/prettier/issues/6356?

**Comment by alexander-akait** [comment] 2022-11-08 00:47
@nex3 Yes, thank you, duplicate of https://github.com/prettier/prettier/issues/6356

**Closed by alexander-akait** 2022-11-08 00:47 UTC
Labels: type:bug, lang:css/scss/less
