### ISSUE TITLE
.prettierignore from CLI 

### ISSUE THREAD

**Issue by anishmittal2020** [prettier/prettier#5757] opened 2019-01-15 20:11 UTC
My `.prettierignore` :

```
Templates/Submodule/pandoc-letter/example/letter.md
```

- I read that prettier searches at `./.prettierignore`. So, `prettier --write Templates/Submodule/pandoc-letter/example/letter.md` is ignored, here the path is relative to the location of `.prettierignore`.

- But when I execute `prettier --write example/letter.md` from  a path relative to ${PWD} but not relative to `.prettierignore`, it isn't ignored.

- But logically it should be ignored. Prettier should find the ignore file recursively up and then ignore accordingly.

**Comment by ikatyang** [comment] 2019-01-16 14:00
> - But when I execute `prettier --write example/letter.md` from  a path relative to ${PWD} but not relative to `.prettierignore`, it isn't ignored.

`--ignore-path` defaults to `.prettierignore`, which means you need to manually specify it in this case, for example: `prettier --write example/letter.md --ignore-path ../../../.prettierignore`.

> - But logically it should be ignored. Prettier should find the ignore file recursively up and then ignore accordingly.

I have never seen up-traversing for `.ignore` files. Did `.gitignore` work that way?

**Comment by j-f1** [comment] 2019-01-16 14:04
`.gitignore` traverses _down_ from the repository root.

**Comment by ikatyang** [comment] 2019-01-17 08:01
`git` commands are applied from the repo root (where `.git/` lives), but there's no concept for repo in Prettier.

**Comment by anishmittal2020** [comment] 2019-01-17 16:38
May be prettier could check if its a git repository and if so could behave like git. Or else do you recommend to put prettierignore in each folder? But in that case Vscode extension doesn't work as it looks at project root.

**Comment by thorn0** [comment] 2020-06-06 19:23
Duplicate of #4081

**Closed by thorn0** 2020-06-06 19:23 UTC
Labels: area:ignore, status:needs discussion, type:enhancement
