### ISSUE TITLE
--prose-wrap: always   is not working

### ISSUE THREAD

**Issue by Nandainkle** [prettier/prettier#15225] opened 2023-08-09 02:52 UTC
**Prettier 3.0.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwB0QdTyGBuOqDuAD2z30hQAzgQCSUTAFcCAXg758ACgCU+GQD58weQvxMYknFCU7d+ADxDMJY2AA2JIUIByJdHDkgYAWiYOYqABucPg+AEZ2EGAA1qHeAO7eFJJ2dgzqpmYWACZBAg5Oru6ePhR2PHGo8OhC3mAI8Dj0IBnGWWbmuYH5ji5uHgyl5dyV1bX1sHBNPgBWkiKoFACedQ1T6ZntCuYOYXB2PYX9JUnQPkI2QnHw3D5gJJgB0Nc8PlBw0jgkdt4AHAAMcUwYW8AEYAHQAVg2bS2WQAwlUlpstuYAPS7fatOHbNFdbGovFBAntcyoCTSFFmGBLTADLyvBhU3T2XpFelDCo+RLJVKjOA1VaTaa+CCSKDZODZOJzBbLbx7GDxOAIOJhXCSkXqnCa7xCCB2VDS8IAcz1hgoZDg3kNJoAFo1vCamEsgdxvABmF63BUQbKu0pnbzuXKSWg+G4R15g-6AiNfYRVVDQbzfA74ChReZIU3mnCW+reGAJqwkJiwDNZoQ57ximCG97eKDQEK5C4RKU1sCGfU4JsQbzZaiYfBtkgd7I1yNNj7F76euPeO1ggBMao1Uxnn3noMBme71fCG77UhwmHKTNhWygxwYYCRl5x+HPVrtBs1ngAosL8Iiafh2UfHFAm+SR6QACSWTVxxIbIgPaNESV0dFSygJDlHYNoAF9MJAAAaEAIEeZNhGQUAy2oeIAAUywQIRkBAb54hIJZ6IIsIvhiOAYAAZX6AAZck4GQS07CEOB2M46JuJ46x7ygE1kGLMCCPE9BUCUnAVJAIRyRNcoAEVJAgeARO+cSCJmIRuB4vTDOM0ykFEiyQAARwcuAqOHeiUEcGcpSlfCvC+VAGxNeEaHQEgGLTILdIU8oAEEYGLVAwmkTypkE94zLEiSQAddA7AAdTtKo4FLeoeLopNAiRBiwCcILAjA8RJVgHiwBwVBHkSiUeJpcpcpczBqHE4qvkwGK7GY1igvJcS8C8kgTSi4b8usHBFoYmk6SELqepgILRvJGBiqNGA7WQFd-gIph3NQJhltW6KnPM-KYHHc7sku66CPmOAABVxx85z8oFPZsklbJ+JsE1JBWuAADFcCilK9Ji6QIBALCsKAA)

```sh
--parser typescript
--print-width 20
--prose-wrap always
```

**Input:**

```tsx
import React from "react";

export const Input =
  () => {
    return (
      <span className="t-relative t-block t-w-full">
        <div className="t-flex t-items-center ">
          <div className="t-flex t-items-center t-justify-center">
            <label className="t-font-sans t-text-caption t-text-neutral-80 t-pb-1.5">
              City
            </label>
          </div>
        </div>
        <input
          type="text"
          className="t-flex t-w-full t-items-center t-rounded t-justify-between t-border t-border-solid t-bg-surface-lighter-grey t-px-3 t-text-body t-font-medium t-text-text-100 t-transition-all  focus:t-bg-surface-transparent focus:t-outline-none disabled:t-cursor-no-drop disabled:t-text-neutral-30 t-h-12 t-border-neutral-10 focus:t-border-purple"
          name="city"
          placeholder="Enter City Name"
          value="Hyderabad"
        />
      </span>
    );
  };

```

**Output:**

```tsx
import React from "react";

export const Input =
  () => {
    return (
      <span className="t-relative t-block t-w-full">
        <div className="t-flex t-items-center ">
          <div className="t-flex t-items-center t-justify-center">
            <label className="t-font-sans t-text-caption t-text-neutral-80 t-pb-1.5">
              City
            </label>
          </div>
        </div>
        <input
          type="text"
          className="t-flex t-w-full t-items-center t-rounded t-justify-between t-border t-border-solid t-bg-surface-lighter-grey t-px-3 t-text-body t-font-medium t-text-text-100 t-transition-all  focus:t-bg-surface-transparent focus:t-outline-none disabled:t-cursor-no-drop disabled:t-text-neutral-30 t-h-12 t-border-neutral-10 focus:t-border-purple"
          name="city"
          placeholder="Enter City Name"
          value="Hyderabad"
        />
      </span>
    );
  };

```

**Expected behavior:** 
```
import React from "react";

export const Input =
  () => {
    return (
      <span className="t-relative t-block t-w-full">
        <div className="t-flex t-items-center ">
          <div className="t-flex t-items-center t-justify-center">
            <label className="t-font-sans t-text-caption t-text-neutral-80 
                              t-pb-1.5">
              City
            </label>
          </div>
        </div>
        <input
          type="text"
          className="t-flex t-w-full t-items-center t-rounded t-justify-between 
                     t-border t-border-solid t-bg-surface-lighter-grey t-px-3 
                     t-text-body t-font-medium t-text-text-100 t-transition-all
                     focus:t-bg-surface-transparent focus:t-outline-none 
                     disabled:t-cursor-no-drop disabled:t-text-neutral-30 
                     t-h-12 t-border-neutral-10 focus:t-border-purple"
          name="city"
          placeholder="Enter City Name"
          value="Hyderabad"
        />
      </span>
    );
  };
```

**Comment by kachkaev** [comment] 2023-08-09 09:08
👋 @Nandainkle! This option is for Markdown only, see its docs: https://prettier.io/docs/en/options.html#prose-wrap

Prettier is a formatter and changing strings is [out of its scope](https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about). If you want to split `className` in your example, you can use [`clsx`](https://www.npmjs.com/package/clsx) or [`cn`](https://github.com/shadcn-ui/ui/blob/3c9f7ca0e20638bf75833ef920f9b23f5d97bc71/apps/www/lib/utils.ts#L1-L6).

**Prettier 3.0.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwB0QdTyGBuOqDbPfYfMKPgC++KjXogAAgHoANqgBG0gK4xUsgM5sOHOAA9uBSFA0EAklEyr8AXg758ACgCUtgHy97D-ExjKcgo5e3vgAPBqYJIJgsiQaGgByJOhwdiAwALRMsWoAbnD4mQqyEGAA1oUZAO4ZFMqysgxuwSFhACaoufyx8UkpaZkUsvqVqPDoGhlgCPA4Es2CrSGhHV0xcYnJqQyDw3qj45PTsHBzmQBWyqaoFACeUzOnTS1LDqGxCnCy3Rt92+m1aCZDRRDSVeB6TJgEiYNTQcH6TJQOCqHAkWQZAAcAAZKpgFBkAIwAOgArM9Fq9WgBhMa3F6vUJyEifWQLKlvaSrdmMrmdHlLUKoSyqBkhGC3TD-CEwBhi7zrXpbGzAASOADkuxGmRqdQaBzgEweJzOWQgyigbTgbUql2udwynxgVTgCEqClwVtNHpwXoyGgg8ja6oANJrHQBzf3+ChkOAZeQRgAWswyEaYtzxegyAGYEZDHRA2pnBkCMikOspaJkZRla4Tsbia2iTGNUNAMujZKH1RRSlckEUoxoY3G6y2IiQmLBRP2NIOMuaYPJkRkoNACh0QcVrQuwP4Azg1xAMm1qJh8FuWcM2gva8jUejc9ie5kk0SAEzuz2nNcomBohiDazvu85FD+R5WDgmDDOqzhCPKDhQMqDBgHScqUq8MFxkmgZemkACiJr4LSEr4H8GEcvguToso-wABK3F6LIkG0lGvNIAreEyk5QFxzjsIsQiCSAIYgBAsLtiYyCgFO1BVAAClOCAaMgIDolUJC3KpYkKGi5RwDAADKWwADLCnAyCxpocC6fpZSGUZkRoVAEbIABdFiRohqoO5OCeSAGjChGwwAIrKBA8BWei3liecGh6EZwVhRFUVINZsUgAAjqlcAKeeqkoHEf7WtaonpGi6jBdSNDoCQalduVQWucMACCMAAYoqh5ac5nItFNliSm6CyAA6kmYxwJO0xGSpba5HSalgPE5W5HRFhWrARlgDgqCwq1lpGRKwwDZlmDUN5o1opgDWyJp2nlcK3l4PlJARnVp22SAkQ4M9akSlKGg7XtMDledwowKNqBtDASbIB+2JiUwOWoEwr3vfV6UxV9MAslDMNw0gH5iVccAACosoVGVfYanxtFabSmVEEbKG9cAAGK4HVHXBQ1qgQCAQhCEAA)

```sh
--parser typescript
--print-width 20
--prose-wrap always
```

**Input:**

```tsx
import React from "react";
import { cn } from "@/lib/utils";

export const Input =
  () => {
    return (
      <span className="t-relative t-block t-w-full">
        <div className="t-flex t-items-center ">
          <div className="t-flex t-items-center t-justify-center">
            <label className="t-font-sans t-text-caption t-text-neutral-80 t-pb-1.5">
              City
            </label>
          </div>
        </div>
        <input
          type="text"
          className={cn('t-flex t-w-full t-items-center t-rounded t-justify-between t-border t-border-solid','t-bg-surface-lighter-grey t-px-3 t-text-body t-font-medium t-text-text-100 t-transition-all','focus:t-bg-surface-transparent focus:t-outline-none disabled:t-cursor-no-drop disabled:t-text-neutral-30','t-h-12 t-border-neutral-10 focus:t-border-purple')}
          name="city"
          placeholder="Enter City Name"
          value="Hyderabad"
        />
      </span>
    );
  };

```

**Output:**

```tsx
import React from "react";
import { cn } from "@/lib/utils";

export const Input =
  () => {
    return (
      <span className="t-relative t-block t-w-full">
        <div className="t-flex t-items-center ">
          <div className="t-flex t-items-center t-justify-center">
            <label className="t-font-sans t-text-caption t-text-neutral-80 t-pb-1.5">
              City
            </label>
          </div>
        </div>
        <input
          type="text"
          className={cn(
            "t-flex t-w-full t-items-center t-rounded t-justify-between t-border t-border-solid",
            "t-bg-surface-lighter-grey t-px-3 t-text-body t-font-medium t-text-text-100 t-transition-all",
            "focus:t-bg-surface-transparent focus:t-outline-none disabled:t-cursor-no-drop disabled:t-text-neutral-30",
            "t-h-12 t-border-neutral-10 focus:t-border-purple",
          )}
          name="city"
          placeholder="Enter City Name"
          value="Hyderabad"
        />
      </span>
    );
  };

```

Closing as intended.

**Closed by kachkaev** 2023-08-09 09:08 UTC
