### ISSUE TITLE
Input() Output() line break

### ISSUE THREAD

**Issue by CarlosGzz** [prettier/prettier#4968] opened 2018-08-09 15:10 UTC
Input and Output decorators in Angular become unreadable if you have several of them. The line break makes readabilty harder and easier to lose an attribute in between decorators. Please revert this change.

**Input:**
export class Products {
@Input() strong = false;
}

**Output:**
export class Products {
  @Input()
  strong = false;
}

**Expected behavior:**
export class Products {
@Input() strong = false;
}

**Comment by suchipi** [comment] 2018-08-09 15:17
Hi, this is a duplicate of https://github.com/prettier/prettier/issues/4924, please follow discussion there.

**Comment by suchipi** [comment] 2018-08-09 15:17
Duplicate of #4924.

**Closed by suchipi** 2018-08-09 15:17 UTC
