### ISSUE TITLE
[TypeScript] Regression: Comment in type argument moves to invalid JSX

### ISSUE THREAD

**Issue by gavinpc-mindgrub** [prettier/prettier#7128] opened 2019-12-11 15:42 UTC
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wGUIBbOAFQAsBLKAczyT3KoHEE5t6xqATwxwAPAB0oAeil4AErzh56RPAEMClKrDwB3WorwBJAOQU8MNQBsA1oxZqARhACu+GAYvCla7ExfaMKqOcPZ4LkRwACZ4BthwkhxwRrC8AGZqYEoAZOyUcADyHrwp8NgZWXi5AJpwMACCUBDF2KXpmTnsMPRWVgVQcACyOMmp5R2SAHx4ALzqfqoz08AAvgDcIAA0IBAY3dBEyKC+2BC6AAq+CIcoagBuEPRRWyCO2Jk2daQYmfbIMNgXHBtrQYBQrAB1BjwIg-LKka70bp3JGCZDgIiHbaMSK4c7vJgUNTIDJWSLbABWRDQACF3mBPjBSGoqAAZRhwEnWckgKloUj2KxwACKLmanKQpJ5P2wuPRMG8RDAfD2LwwfFgEKeHmQAA4AAzbdUQSIQ94YdHquC4u6c7YARzF8HxuxuIDURAAtANotEXvFHfR4vi1ITiZLucCQJEKPR-oCo0RBSKnRKpVHLI4tVEdUgAEzbAFqHr2ADCWnDICaAxeERoThu6e2dyBKSiCCZyvoe0aUVICqFXLJcBWKyAA)

Between 1.18.2 and 1.19.1, formatting of the following TypeScript code started yielding invalid syntax when used in a JSX file:

```typescript
interface SomeGenericType<T> {}
interface SomeInterface {}
interface SomeOtherInterface {}
interface YetAnotherInterface {}
interface StillOneMoreInterface {}

export const SomeThing : SomeGenericType<
// Here is a comment where I'm talking about the type arguments being used here
SomeInterface & SomeOtherInterface & YetAnotherInterface & StillOneMoreInterface
> = args => {};
```
(The interface declarations are not material to the bug, just to keep out other errors.)

Result in 1.18.2:
```typescript
export const SomeThing: SomeGenericType<
  // Here is a comment where I'm talking about the type arguments being used here
  SomeInterface &
    SomeOtherInterface &
    YetAnotherInterface &
    StillOneMoreInterface
> = args => {};
```
Result in 1.19.1:
```typescript
export const SomeThing: SomeGenericType<// Here is a comment where I'm talking about the type arguments being used here
SomeInterface &
  SomeOtherInterface &
  YetAnotherInterface &
  StillOneMoreInterface> = args => {};
```
This produces a number of syntax errors in JSX.  Note that no JSX-specific syntax is used in this case.  But the result is valid in a regular TS file.

Thanks for maintaining Prettier, it is a humane technology that improves our team members' lives every day!

**Comment by thorn0** [comment] 2019-12-11 16:41
Oops, this part—`SomeGenericType<//`—indeed [causes syntax errors](https://www.typescriptlang.org/play/?jsx=1#code/JYOwLgpgTgZghgYwgAgMoHsC2EDiETTAIAqAngA4QA8xAfMgN4C+AsAFCiSyIobYCS4aPCSNWHId1F8IAeTAALaIK4iUzdp2E9kATQhgAgiHSLlktWM0WdqMMAA2D2QQCy6KBBXbRDZOPYIAA9yDzBkBHQQAGdwmWIFUABzAC40LFx8QhIKagB6POQACWgUYGjkOAisbHBkAHclT2R+AHJMZDA4BwBrZMqAI3QAV3CzTtzKqCTh2rAKgYh+4eiIABNkJoh2GW8pFAAydmR07HkmvcsjthP9IxMzKEuda5O7R2c3Dy8bJHoAXimSQq-3ozAA3EA). I guess this is caused by https://github.com/prettier/prettier/pull/6467.

**Comment by thorn0** [comment] 2019-12-11 17:02
Fixed by https://github.com/prettier/prettier/pull/6901, but not yet released.

@lydell We seem to have been getting more and more of such fixed-but-not-yet-released issues. Time for 1.19.2?

**Closed by thorn0** 2019-12-11 17:02 UTC
Labels: area:comments, lang:typescript, type:bug

**Comment by lydell** [comment] 2019-12-11 17:27
@thorn0 I’m not opposed to 1.19.2, but I won’t have time for it myself.

**Comment by gavinpc-mindgrub** [comment] 2019-12-11 18:05
Thanks, all!
