### ISSUE TITLE
feat(prettier playground): Add json config upload

### ISSUE THREAD

**Issue by doc-han** [prettier/prettier#6353] opened 2019-08-02 14:46 UTC
## Feature
It would be awesome if one could upload a prettier JSON config in the playground.

## Reason
Let's say I'm working on open source issues where I am to add validation to an input. In this case I'm to edit just a single file. 

Best way to do this is not to make a local copy of my fork when the project is so huge(around 600MB).  

Hence, with this feature, I will be able to copy the lint config into the playground and fix the code.

**Comment by lydell** [comment] 2019-08-03 18:11
Duplicate of #6142

**Closed by lydell** 2019-08-03 18:11 UTC
