### ISSUE TITLE
Currently in Cosmo city 10°/30°

### ISSUE THREAD

**Issue by Mancosa2023** [prettier/prettier#16538] opened 2024-08-04 13:01 UTC
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq19zrlcAhgCadyQ8qhpwYPcmEo8ATgGdxAXiYgAqvgBiAWgAcq8gHpBw1DACWMOnAa4ArrNkIrAT3IBmAAwAG8rgjyNBB+li6ohhZWNizh3Pyc9o7OdG5evv6BwWChMQBGEHxunDGG+YX4EEGOEADu5CbhcDQmQuHyMLLQAObkAIw+hgBMACzeLcIipQVuAMo8MA58PC7jE62G7Z1QPb2D3oa9umMsa6frZbN2UEtFJ2f3bR3dfQBs+4N7q-enjc3kdz8poU-DJtnApKEvq12i5GADvpResB4d9hJA6BAHEhyHRzF1qLk6HY4ABuFGo8gAM2gMG08nMAC84NjhoMAA4ADzJUApa3gHNpPFxXSg2LAzjgsm5vIAvuTATC4Tyzo9YS1YrQlWiCuDcm4AOJ2Lp2cgAWR4AGs7PkQAAaEAQNkWaDyZCgOSdGrEOQIV0oIU1Zau+25WQ8MAW8RzMQAGXMUDgyEpQsUIbDEajbPD8a6yA6xPtiho5jzsgLIDgHLZkvMYlgQvwkqgcnMcD9yboqZA9O21gAinYIPAkym4PaAFbyDkzHP9wfDpAdrsAR3ncGInTZfpAPHk2gTcD4h7tIA6PHMuO2-hoNB4yB3dDoJ57XWsAEEYB1zLk7PBiJK4wTEdOzHEB2DoAB1ShLDbLNxRmX1LHMAA3UJ7zAeRgxAZDiQASWuZwZjAWRzCdN9rhmGBYUTRdR3tNlOkUCCwzZe8GLbSVkMTe140UWQYA3HgulvYCuyzBRJXvXIeFyOAn3okjYAg8w+BgShkF0Tx7ScVdzCcQThLvWiQPtCRcmU1T1KQQZ7TsRR8Bk9s6IrGhZL4I8+BjHhtjsIS4E0CBZFvT8c3vHhfwgEAZRlIA)

```sh
--parser babel
```

**Input:**

```jsx
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>Currently 30° Cosmo City</title>
</head>
Currently 30° Cosmo city
<body >

</bodyTomorrow >
  </em>
    </strong 10°/24°>
       </body Saturday>
          </strong 12°/18°>
             </body Sunday >
                </strong 16°/22°>
                   </em> 
        </body Change city>
        <styl>
            h1{
                colour: lightblue;
                font-size: 42px;
                text-align: center;
            }
            </styl>
        </styl>
   </html>
   code by Gugu Makubo
```

**Output:**

```jsx
SyntaxError: Unexpected token (1:1)
> 1 | <!DOCTYPE html>
    | ^
  2 | <html>
  3 | <head>
  4 |     <meta charset="UTF-8" />
```

**Expected output:**

```jsx

```

**Why?**

**Comment by kachkaev** [comment] 2024-08-04 20:24
👋 @Mancosa2023! I see to issues preventing Prettier from parsing your snippet correctly:

- Used `parser` is `babel` instead of `html` (`babel is for JavaScript files)
- The HTML has syntax issues, starting with `</bodyTomorrow >`.

Here is a fixed snippet, which is understood by Prettier well:

**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq19zrlcAhgCadyQ8qhpwYPcmEo8ATgGdxAXiYgAqvgBiAWgAcq8gHpBw1DACWMOnAa4ArrNkIrAT3IBmAAwAG8rgjyNBB+li6ohhZWNizh3Pyc9o7OdG5evv6BwWChMQBGEHxunDGG+YUmwqbyMC7WFZUNlACMwCwN7Q2QdBAOSOR05gDm1Ll0dnAA3G0dMwBm0DDa8uYAXnB9ACwATAAOAB5TUDMz8HuLPAODUH1gznCyh8fCAL7TT+HVtdFHQrG0jCwQAAaEAQHYWaDyZCgOSyCAAd2IcgQUJQF3hPBcUJBuVkPDAAGtxABlHhiAAy5igcGQswuihxeMJJJ2+Kpg2QMFk4xBiho5k53LgILgex293MYlgF3w9ygcnMcFRdLoDJAyygg2sAEU7BB4LT6cKQAAreR7YnsnV6g1IFVqgCONrgxDhO1RIB48m01LgfD9wJAXJ45gGmv8NBoPGQnrodEDGq1cAAgjAueZcnZ4MR7pTqYbVcb2HQAOqUSxK1m3YkoyzmABuoRjYHk2JA9fGAEkoP7YMSwLJzODkz3iTVrAW1Ts4YoS3idjHp0r7vWaSCqYpZDBXTxBlHJ8bWQp7jHi4Hp1SYCXzHwYJRkLpPCCnE7zE4d3vo3ajSCJLlr7e95IFsIJ2Io+A8Lkyo-iAcA0Lkfr+nw5I8Jqdi7nAmgQLIUZpuyMY8FmEAgM8zxAA)

```sh
--parser html
```

**Input:**

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>Currently 30° Cosmo City</title>
</head>
Currently 30° Cosmo city
<body >

</body>
        <style>
            h1{
                colour: lightblue;
                font-size: 42px;
                text-align: center;
            }
            </style>
   </html>

```

**Output:**

```html
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Currently 30° Cosmo City</title>
  </head>
  Currently 30° Cosmo city
  <body></body>
  <style>
    h1 {
      colour: lightblue;
      font-size: 42px;
      text-align: center;
    }
  </style>
</html>

```

If you are just starting to learn HTML, try using syntax validator in addition to Prettier. Here is one (just an example):
https://validator.w3.org/#validate_by_input

![Screenshot 2024-08-04 at 21 22 58](https://github.com/user-attachments/assets/e120f4e0-0b34-4c3a-b155-da94c4b73375)

Hope it helps!

Prettier can only format a file if its syntax is correct, so I’ll close this issue as intended behavior.

**Closed by kachkaev** 2024-08-04 20:24 UTC
