### ISSUE TITLE
Unexpected object literals formatting within template literals

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier#1662] opened 2017-05-22 14:05 UTC
Input:

```javascript
const content = `
const env = ${ JSON.stringify({
	assetsRootUrl: env.assetsRootUrl,
	env: env.env,
	role: "client",
	adsfafa: "sdfsdff",
	asdfasff: "wefwefw",
  	fefef: "sf sdfs fdsfdsf s dfsfds"
}, null, "\t") });
`;
```

Prettier:
```javascript
const content = `
const env = ${JSON.stringify({ assetsRootUrl: env.assetsRootUrl, env: env.env, role: "client", adsfafa: "sdfsdff", asdfasff: "wefwefw", fefef: "sf sdfs fdsfdsf s dfsfds" }, null, "\t")});
`;
```

Above clearly breaks print width setting. Is that intended? Or can we clarify it as a bug?

If it's intended then it'll be great if there would be some option to turn off formatting within template literals as prettier output doesn't seem maintainable in that case.

**Comment by josephfrazier** [comment] 2017-05-22 14:38
Searching the issues for 'template object' shows that this is related to (and possibly a duplicate of) https://github.com/prettier/prettier/issues/821

**Comment by medikoo** [comment] 2017-05-22 14:41
> Searching the issues for 'template object'

I searched "template literals" and that one didn't appear. Thanks for reference, closing then

**Comment by vjeux** [comment] 2017-05-22 14:55
Actually, #821 is unrelated. It's likely related to https://github.com/prettier/prettier/issues/1183, but need to double check to confirm the root cause.

**Comment by josephfrazier** [comment] 2017-05-22 15:08
One way to fix this is to get rid of the `removeLines` call [here](https://github.com/prettier/prettier/blob/aeed7840e2e6f8975cc820780ffecc6fcad08728/src/printer.js#L1676)

This causes the original input:

```js
const content = `
const env = ${ JSON.stringify({
	assetsRootUrl: env.assetsRootUrl,
	env: env.env,
	role: "client",
	adsfafa: "sdfsdff",
	asdfasff: "wefwefw",
  	fefef: "sf sdfs fdsfdsf s dfsfds"
}, null, "\t") });
`;
```

to be formatted as:

```js
const content = `
const env = ${JSON.stringify(
              {
                assetsRootUrl: env.assetsRootUrl,
                env: env.env,
                role: "client",
                adsfafa: "sdfsdff",
                asdfasff: "wefwefw",
                fefef: "sf sdfs fdsfdsf s dfsfds"
              },
              null,
              "\t"
            )});
`;
```

which looks better to me. However, this change causes a couple of tests to fail, but the snapshots arguably should be updated anyway:

<details>

```
Summary of all failing tests
 FAIL  tests/strings/jsfmt.spec.js
  ● flow - undefined-verify

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -11,23 +11,75 @@
     pipe.write(
       `\n  ${chalk.dim(`\u203A and ${more} more ${more} more ${more} more ${more}`)}`,
     );
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     foo(
    -  `a long string ${1 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3} with expr`
    +  `a long string ${1 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3} with expr`
     );

    -const x = `a long string ${1 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + (function() {
    +const x = `a long string ${1 +
    +  2 +
    +  3 +
    +  2 +
    +  3 +
    +  2 +
    +  3 +
    +  2 +
    +  3 +
    +  2 +
    +  3 +
    +  2 +
    +  (function() {
         return 3;
    -  })() + 3 + 2 + 3 + 2 + 3} with expr`;
    +  })() +
    +  3 +
    +  2 +
    +  3 +
    +  2 +
    +  3} with expr`;

     foo(
    -  `a long string ${1 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + (function() {
    +  `a long string ${1 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    (function() {
           const x = 5;

           return x;
    -    })() + 3 + 2 + 3 + 2 + 3} with expr`
    +    })() +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3} with expr`
     );

     pipe.write(
    -  `\n  ${chalk.dim(`\u203A and ${more} more ${more} more ${more} more ${more}`)}`
    +  `\n  ${chalk.dim(
    +    `\u203A and ${more} more ${more} more ${more} more ${more}`
    +  )}`
     );

      at Object.test (tests_config/run_spec.js:25:62)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  ● flow - undefined-verify

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 2.

    - Snapshot
    + Received

    @@ -11,23 +11,75 @@
     pipe.write(
       `\n  ${chalk.dim(`\u203A and ${more} more ${more} more ${more} more ${more}`)}`,
     );
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     foo(
    -  `a long string ${1 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3} with expr`,
    +  `a long string ${1 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3} with expr`,
     );

    -const x = `a long string ${1 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + (function() {
    +const x = `a long string ${1 +
    +  2 +
    +  3 +
    +  2 +
    +  3 +
    +  2 +
    +  3 +
    +  2 +
    +  3 +
    +  2 +
    +  3 +
    +  2 +
    +  (function() {
         return 3;
    -  })() + 3 + 2 + 3 + 2 + 3} with expr`;
    +  })() +
    +  3 +
    +  2 +
    +  3 +
    +  2 +
    +  3} with expr`;

     foo(
    -  `a long string ${1 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + 3 + 2 + (function() {
    +  `a long string ${1 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    (function() {
           const x = 5;

           return x;
    -    })() + 3 + 2 + 3 + 2 + 3} with expr`,
    +    })() +
    +    3 +
    +    2 +
    +    3 +
    +    2 +
    +    3} with expr`,
     );

     pipe.write(
    -  `\n  ${chalk.dim(`\u203A and ${more} more ${more} more ${more} more ${more}`)}`,
    +  `\n  ${chalk.dim(
    +    `\u203A and ${more} more ${more} more ${more} more ${more}`,
    +  )}`,
     );

      at Object.test (tests_config/run_spec.js:25:62)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)


Snapshot Summary
 › 2 snapshot tests failed in 1 test suite. Inspect your code changes or run with `npm test -- -u` to update them.

Test Suites: 1 failed, 567 passed, 568 total
Tests:       2 failed, 1853 passed, 1855 total
Snapshots:   2 failed, 1617 passed, 1619 total
```
</details>

**Comment by vjeux** [comment] 2017-05-22 15:11
@josephfrazier oh yeah, I think that we should do that, now that we have a better solution for template literals.

This solves the second issue here: https://github.com/prettier/prettier/issues/1626, and there's a concrete plan for the remaining two.

Omg, there's a chance that we can get template literals figured out :)

**Comment by josephfrazier** [comment] 2017-05-22 15:11
Great, I'll open a PR

**Closed** 2017-05-22 16:00 UTC
Labels: bug
