### ISSUE TITLE
--debug-check for typescript is not working but --write

### ISSUE THREAD

**Issue by ianmuninio** [prettier/prettier#4415] opened 2018-05-03 17:03 UTC
**Prettier 1.12.1**

The `--write test.ts` works perfectly but `--debug-check`.

```sh
--debug-check test.ts
--debug-check --parser typescript test.ts
```

**Input:**
```ts
// test.ts
const test = { "asd": 1 };
```

```json
// .prettierrc
{
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "useTabs": false
}
```

```json
// .tslint.json
{
  "extends": ["tslint:latest", "tslint-config-prettier"],
  "rules": {
    "no-implicit-dependencies": false,
    "no-submodule-imports": false,
    "object-literal-sort-keys": false,
    "only-arrow-functions": false
  }
}
```

**Output:**
```ts
test.ts
```

**Expected behavior:**
```sh
[error] src/index.js: ast(input) !== ast(prettier(input))
[error] Index:
[error] ===================================================================
[error] ---
[error] +++
[error] @@ -17,6 +17,6 @@
[error]                    "method": false,
[error]                    "key": {
[error] -                    "type": "StringLiteral",
[error] -                    "value": "asd"
[error] +                    "type": "Identifier",
[error] +                    "name": "asd"
[error]                    },
[error]                    "computed": false,
[error]
[error] Index:
[error] ===================================================================
[error] ---
[error] +++
[error] @@ -1,1 +1,1 @@
[error] -const test = { "asd": 1 };
[error] +const test = { asd: 1 };
[error]
```

**Comment by suchipi** [comment] 2018-05-03 17:12
This happens because `--debug-check` [massages the AST](https://github.com/prettier/prettier/blob/67f1c4877ee1090b66d468a847caccca411a6f82/src/cli/util.js#L130) based on rules defined by the parser, and we [massage the keys out of the AST](https://github.com/prettier/prettier/blob/master/src/language-js/clean.js#L61) because we know we will change them.

Basically, we consider this a "safe" AST change, so we don't flag it.

Is this change causing an issue for you?

**Comment by ianmuninio** [comment] 2018-05-14 01:37
Sorry for the delay. We are trying from JS to migrate to Typescript and we have the same config setup so we expected the same output.

**Comment by suchipi** [comment] 2018-05-24 01:52
Ok. This change is safe in both JavaScript and TypeScript, so I'm going to close this issue since this is the intended behavior.

**Closed by suchipi** 2018-05-24 01:52 UTC
Labels: area:cli, type:question
