### ISSUE TITLE
[styled-components] Support adjacent interpolations

### ISSUE THREAD

**Issue by jacobbuck** [prettier/prettier#2744] opened 2017-09-03 23:14 UTC
Input:

```js
const Test = styled.div`
  margin-top: 1rem;
  margin-bottom: 1rem;
  padding: 2em;

  ${props => props.variant === "dark" &&
    css`
      color: white;
      background-color: black;
    `
  }
  

  ${props =>
    props.variant === "light" &&
    css`
    color: black;
    background-color: white;
  `}
  ${props => props.size === "small" && css`font-size: 0.75rem;`}
  
  transition: background-color 120ms linear;
`;
```

Output:

```js
const Test = styled.div`
  margin-top: 1rem;
  margin-bottom: 1rem;
  padding: 2em;

  ${props =>
    props.variant === "dark" &&
    css`
      color: white;
      background-color: black;
    `} ${props =>
      props.variant === "light" &&
      css`
        color: black;
        background-color: white;
      `} ${props =>
      props.size === "small" &&
      css`
        font-size: 0.75rem;
      `} transition: background-color 120ms linear;
`;
```

Expected:

```js
const Test = styled.div`
  margin-top: 1rem;
  margin-bottom: 1rem;
  padding: 2em;

  ${props =>
    props.variant === "dark" &&
    css`
      color: white;
      background-color: black;
    `} 

  ${props =>
    props.variant === "light" &&
    css`
      color: black;
      background-color: white;
    `}
  ${props =>
    props.size === "small" &&
    css`
      font-size: 0.75rem;
    `} 

  transition: background-color 120ms linear;
`;
```

**Comment by azz** [comment] 2017-09-03 23:19
Hi, this is a duplicate of #2291.

**Closed by azz** 2017-09-03 23:19 UTC
